### ISSUE TITLE
Revise idleTime mechanism

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#10008]
@NicholasCouri asked in https://github.com/microsoft/FluidFramework/pull/10007

> I'm not sure if changing idleTime right now, together with MaxOps is the right thing to do - should we wait for more data ? Currently, idleTime is 15 secs.

I believe it makes total sense to reduce idleTime to 10s, maybe even 5s. And data suggests that 72% of last summaries (files at rest, looking at last summary produced for such files) are done with reason = "idle" and P95 = 138 ops being summarized, so reducing this timer will reduce number of trailing ops for sure. It's possible that the need for that change will be reduced due to MaxOps change in that PR.

But the main reason why I think we should take it a bit slower is different - it's wasteful to summarize 2-3 ops frequently - it does not give us much but increases COGS and pressure on service. So I think we should think how to have much tighter idleTime when there are many unsummarized ops, and lax idleTime when we have few. I.e. it seems the best outcome is
- Remove maxOps trigger (but keep the value in policy)
- Defined idleTime = log(unsummarized ops / maxOps), or something very similar - i.e. having close to infinite value (well, not infinite, but high, let's say 30 seconds) when we have 1 unsummarized op, and zero when we reach maxOps unsummarized ops.

That way it becomes less function of idleness of the product, and more a function of rate of changes.

Useful query to look at last summary stats:

let lastSummary = union Office_Fluid_FluidRuntime_*
| where Data_eventName == "fluid:telemetry:Summarizer:Running:Summarize_generate"
| summarize max(Event_Time) by Data_docId;
let end = union Office_Fluid_FluidRuntime_*
| where Data_eventName == "fluid:telemetry:Summarizer:Running:Summarize_generate"
| where Event_Time < ago(3d)
| project Event_Time, Data_docId, reason = Data_summarizeReason, Data_opsSinceLastSummary;
lastSummary | join (end) on Data_docId, $left.max_Event_Time == $right.Event_Time
| summarize count(), avg(Data_opsSinceLastSummary), percentile(Data_opsSinceLastSummary, 95) by reason

**Comment by kian-thompson** [comment]
Closed to track in AB#128
