### ISSUE TITLE
Enhance test infrastructure to support disconnect after sequencing but before receiving ack from orderer

### ISSUE THREAD

**Issue by justus-camp** [microsoft/FluidFramework#10013]
Spawned from #9986. We observed behavior in the TaskManager DDS from the load tests due to this [fault injection logic](https://github.com/microsoft/FluidFramework/blob/562a0722eec42a9c31eb2d256dc9f1ea0be720e9/packages/test/test-service-load/src/runner.ts#L246) where the sequence below is occurring (taken from @ChumpChief's comment which succinctly spells out the scenario):

1. Client sends a volunteer op prior to disconnect
2. Orderer sequences the volunteer op
3. Client disconnects (without seeing the volunteer ack)
4. Orderer sequences the client leave op
5. Client reconnects, and sees the volunteer ack

With the current test infrastructure, this sequence isn't possible to recreate in a unit test. This functionality would likely be useful to a number of DDSs.

**Comment by vladsud** [comment]
I think you would need to be more precise on what you mean by test infrastructure.
If you mean UT (which I'd assume TaskManager should exercise), then you can use mock implementations for anything you want / need and simulate state transitions.

You can also use end-to-end and provide your own document service to control connectivity that way - see "Raise disconnected event" UT.

You can also precisely control inbounding and outbounding of ops, and thus disconnect container with pending non-acked ops from a given container to simulate condition you hit in TaskManager - see 

LoaderContainerTracker class / IOpProcessingController interface.
Also most end-to-end tests leverage ITestObjectProvider, which exposes opProcessingController property to control op processing angle.

So, I think we have all the right capabilities here, and this bug should be changed to track particular work in TaskManager.
