### ISSUE TITLE
Chapter 3 file produces pretty huge summaries

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#10014]
Chapter 3 file summarizes too many data stores.

[File in question](https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!bmPo6zZge0ekRy_ZY0lO6VU6IViOt_NErtioTywuOoS1ap45rHl3S59rQHWSoqsK&item=01THIE7YVDNDMLOO2Z3ZCKOVEKSFGQ6NED&file=https:%2F%2Fmicrosoft-my.sharepoint.com%2Fpersonal%2Fswatijain_microsoft_com&siteUrl=https:%2F%2Fmicrosoft-my.sharepoint.com%2Fpersonal%2Fswatijain_microsoft_com&nav=cz0lMkZwZXJzb25hbCUyRnN3YXRpamFpbl9taWNyb3NvZnRfY29tJmQ9YiFibVBvNnpaZ2UwZWtSeV9aWTBsTzZWVTZJVmlPdF9ORXJ0aW9UeXd1T29TMWFwNDVySGwzUzU5clFIV1NvcXNLJmY9MDFUSElFN1lWRE5ETUxPTzJaM1pDS09WRUtTRkdRNk5FRCZjPSUyRmIwMzk2NWVhLWU3ZDYtNGRkMC1iMTJhLWY5ZTZiMTk0NTFiYyUzRnN0YXJ0JTNEdW5kZWZpbmVkJTI2ZW5kJTNEYTQyNTNlZTgtN2FhYy00NTNmLWE5NzEtNzk2MWJkZTk4ZDRhJmZsdWlkPTEmcD0lNDBtcyUyRm9mZmljZS1mbHVpZC1jb250YWluZXI%253d) 

If I type space in main text (and delete it), I see only 2 ops flowing in the system (as expected).
Yet, summary that follows modifies 24-27 trees, and a ton of maps (od directories):

"treeNodeCount":23,
"blobNodeCount":35,
"handleNodeCount":328,
"totalBlobSize":371195,

Size is also large. 105Kb of that is main Sequence (not ideal, but expected), the rest - seems like should not be there.
There is some impact due to us summarizing whole data store (no incrementality here - we should fix it), but it still does not explain why so many maps/directories are saved.

**Comment by vladsud** [comment]
@agarwal-navin - FYI, I have a feeling Nicholas might need your help here (at least with breakpoints and overall flow)

**Comment by NicholasCouri** [comment]
Navin and I were looking at the data and we found 2 fronts to work on: 

a) We are re-generating a full summary instead of partial one due to the code added due the BlobAggregationStorage  that forces the full summary for blobs and incrementing the node count. 

               // If BlobAggregationStorage is engaged, we have to write full summary for data stores
                // BlobAggregationStorage relies on this behavior, as it aggregates blobs across DDSs.
                // Not generating full summary will mean data loss, as we will overwrite aggregate blob in new summary,
                // and any virtual blobs that stayed (for unchanged DDSs) will need aggregate blob in previous summary
                // that is no longer present in this summary.
                // This is temporal limitation that can be lifted in future once BlobAggregationStorage becomes smarter.
                const contextSummary = await context.summarize(true /* fullTree */, trackState);

b) There is also the fact that we add one treecount for every .channels we add to the code. 

Ex.

                "458d5e02-c830-42de-aaa3-b01a87996c49": {
                    "type": 1,
                    "tree": {
                        ".channels": {
                            "type": 1,
                            "tree": {
                                "root": {
                                    "type": 1,
                                    "tree": {
                                        "header": {

**Comment by agarwal-navin** [comment]
> I'm not sure why #b happens. Are we essentially regenerating whole tree, and reusing only blobs (leaf nodes)?

No, we aren't regenerating the whole tree. But when we do summarize a data store, we add 2 trees for it (one for the data store and one ".channels" to add its DDSs). So, for every data store summarized, there is one extra tree in the summary which is basically overhead.
We were wondering if we should make it clear in telemetry how many tree nodes there are for actual data stores and DDS and how many are just overhead. We can just subtract the number of ".channel" trees when looking at telemetry which is equal to number of data stores summarized + one at root for adding data stores.

**Comment by vladsud** [comment]
I'm not sure I follow. There is /.channels/dataStoreA/.channels/DDS1 kinds of paths (I believe)
If nothing changed in datastore, I'd expect (in best case) to see only /.channels/dataStoreA entry that points to previous handle, and no sub-channels for dds. In other words, in a file that has few changes, number of nodes should asymptotically be number of data stores, not 2X, or 5x. Is there any reason we can't get there?

**Comment by agarwal-navin** [comment]
Yes, you are right. That is the behavior when nothing changes and that part is not a problem at all. I was talking about the scenario when something changes.
Let's say 1 DDS in 1 data store got an op. Assuming that the DDS adds only blobs in its summary data, one would think this would result in 2 node being summarized. However, the actual number of tree nodes in the summary is 4:
- 1 for `/.channels` that contains data stores.
- 2 = 1 each for the data store tree and `.channels` in it: `/.channels/dataStoreA/.channels`.
- 1 for the DDS: `/.channels`/dataStoreA/.channels/DDS1`.

So, we would want to ignore the `/.channels` sub-trees when looking at how many trees were summarized because of X number of ops.

**Comment by vladsud** [comment]
Got it. I'd not worry that much about changed data stores, as ideally there should be 1-2 per summary (in most incremental cases).
I'd think most cases where summary metadata is large, it's because we have too many data stores in a file, likely due to too many deleted tables. GC will fix it, but for now that's likely the biggest issue - would be nice to confirm it (and not worry about it till we have GC done).

**Comment by agarwal-navin** [comment]
Sounds good.

**Comment by NicholasCouri** [comment]
https://dev.azure.com/fluidframework/internal/_workitems/edit/219
