### ISSUE TITLE
Too many short "write" connections

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#10022]
> Office_Fluid_FluidRuntime_Performance
| where Data_eventName == "fluid:telemetry:Container:ConnectionStateChange_Disconnected"
| where Data_connectionMode == "write"
| where Data_clientType == "interactive"
| where Data_reason notcontains "Closing DeltaManager"
| where Data_reason notcontains "Switch to write"
| summarize count(), countif(Data_duration < 5000) by Data_reason
| where count_ > 10000

Data_reason | count_ | countif_
-- | -- | --
socket.io (disconnect): transport close | 865,561 | 542,446
socket.io (error): websocket error: {"type":"TransportError","description":{"isTrusted":true}} | 17,379 | 98
socket.io (disconnect): ping timeout | 25,025 | 24
setAutoReconnect | 34,708 | 227
OdspSocketError (server_disconnect): AccessExpired | 60,889 | 436
Nack (BadRequestError): Nonexistent client | 65,517 | 4
ODSP socket error (server_disconnect): AccessExpired | 10,985 | 516

I'd think that the very first step on this journey would be understanding and fixing https://github.com/microsoft/FluidFramework/issues/9799

**Comment by vladsud** [comment]
This does not look great:

Office_Fluid_FluidRuntime_Performance
| where Data_eventName == "fluid:telemetry:Container:ConnectionStateChange_Disconnected"
| where Data_connectionMode == "write"
| where Data_clientType == "interactive"
| where Data_reason notcontains "Closing DeltaManager"
| where Data_reason notcontains "Switch to write"
| where Data_duration < 1000
| summarize count(), dcount(Data_containerId)

I get 454K total hits via 1274 unique containers !
Some clients experience a top of these failures!

In addition to understanding the cause here, I think we should review https://github.com/microsoft/FluidFramework/pull/9243 and see if it should catch such containers (in its current form), or criteria should be broadened to capture such cases and close such containers.

An example of container that hits these issues non-stop: Data_containerId == "7585da0d-f2a0-4266-ad71-fee068d80f8f"
It captures new file being created, so it did not hit 10K unsummarized ops, yet was losing connection all the time.
Did it make progress? Was user experience screwed?

@andre4i - FYI

**Comment by NicholasCouri** [comment]
Track by https://dev.azure.com/fluidframework/internal/_workitems/edit/416?
