### ISSUE TITLE
SharedTree: Tree Representation

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#10034]
# Tree Representation

Where #9475 concerns the abstract data model, this issue concerns how tree data is concretely represented in storage, over the network, and in memory.

## Introduction

Because tree data is used and processed in a variety of ways, there is a large design space to explore to find an optimal set of representations that strike the right balance between storage, network, memory, and CPU costs. In particular, there is a tension between maintaining optimized representations for each usage and minimizing memory and data copying costs associated.

## Important Scenarios

This section describes customer scenarios that are potentially impacted by tree representation choices.

### Startup Time

Minimizing the time required to start an application and/or load a document is a high priority for most customers. One scenario where we feel this acutely is when adding Fluid-powered collaboration to a mature application. For mature applications, often the only viable integration path is to map the application's native file format or internal data structures to Fluid DDSes.

In the past, using our built-in DDSes to model tree-like data would typically lead to significantly more data being stored and transferred with a corresponding impact to startup time. SharedTree and Property DDS reduce this overhead, but there is still room for improvement. As a guideline, an amortized ratio of 1.25x growth is a good initial target.

Another potential contributor to startup time are the retrieval and application of "catch up" ops after the last summary has been loaded.

### Framerate

Most customers use Fluid as part of a reactive system that propagates data changes to their application's state and UI. For these customers, local responsiveness is almost always critical for user experience, with some applications like Whiteboard and collaborative VR approaching soft real-time requirements.

Because precise dependency tracking is often prohibitively costly, many reactive systems use conservative approximations that over-invalidate. As a result, distributed data structures frequently have a very high ratio of reads (e.g., rebuilding a vertex buffer because a single vertex is being dragged.)

While the application author can sometimes tweak the scope of invalidation to help mitigate this, this often requires restructuring data in ways that can be difficult for a mature application. Additionally, for some applications, slow read performance can be a user experience bottleneck (e.g., recalculating spreadsheets and rendering 3D scenes).

This leaves us with a general desire for DDS read performance to be comparable to native field and array access. It is also important for invalidations to be light-weight, fine-grained, and sufficiently specific that sophisticated applications can perform optimal incremental recalculation.

### End-to-end Latency

For a subset of applications like a shared Whiteboard or collaborative VR, end-to-end responsiveness can be nearly as important as local responsiveness. This scenario combines aspects of the previous two: ops must be compact and fast to process and apply. After application, read and invalidation performance become important, as before.

### Bulk Async Updates

While many real-time scenarios tend to stream small updates (e.g., inserting characters as the user types), bulk updates do occur, such as subdividing a mesh. In some environments it may be possible to use higher-level commands to avoid transmitting large changesets, but there will always be scenarios where bulk uploads and broadcast are unavoidable.

This again puts pressure on the tree representation to be compact, but also is motivation to support features like snapshot isolation and/or on-demand paging of tree content. At the extreme, we would expose a stream-processing interface that supports building transactions that exceed the client's memory.

Another consideration is the need for a back pressure to inform the sender when it is producing updates faster than the service or other clients can process the changes.

### Query Support

The current ODSP and FRS storage services are basic key/value blob stores. However, our future plans include supporting service-side query processing of tree data. There are two motivating scenarios. The first scenario is to improve the scalability of partial checkouts.

The second motivation is to support non-Fluid clients that occasionally need to read/write tree data or batch process changes. For these clients, we want to expose tree data via in a standard way (e.g., REST APIs or a GraphQL endpoint) without the overhead of running a full Fluid client on the service.

## Potential Variants

This section lists considerations for the main tree data usages.

### Storage

The storage service is responsible for processing queries for tree data as well as incrementally updating the stored tree data as the tree is edited. Queries are for a subset of the tree at a specific branch/revision.

Considerations for this variant:

- Data should be chunked to the optimal size for the underlying storage provider (typically 4-8KB.)
- Data should be organized to minimize required reads and maximize parallelism to reduce end-to-end latency.
- Data encoding should balance efficient incremental summary updates, query processing, and compact size.

### Query Result

When returning query results, we may want to preprocess the raw chunks before returning them to the client. When fine-grained permissions are involved, preprocessing is practically unavoidable.

At the extreme, query results could be a distinct format with real-time transcoding in the service. Some potential optimizations to be explored:

- Merge chunks into a bulk response to reduce redundancy.
- Elide portions outside of the user's query/permissions.
- Strip other non-essential data (e.g., scaffolding, if present)
- On-the-fly compression.

In addition, it is likely we will want to leverage precalculated query results for common requests, such as loading the latest summary or accelerating "catch up" for a stale client that is reconnecting.

### Transmission

As a principle, Fluid minimizes service costs by shifting work to the clients when possible. In SharedTree, this means that the writer/sender includes extra information in the changeset to minimize the need for clients and services to page additional information into memory when processing changes.

Examples of extra information retained in the op transmission format:

- Constraints that are used to verify that the writer/sender's intended semantics are preserved (including validation that the edit continues to adhere to schema).
- Type information that allows light-weight observers to react to modifications to specific types without maintaining a working tree.

### Rebasing

Before a changeset can be applied to the local working tree the changeset must be rebased to take into account preceding concurrent edits. Ideally, rebasing would be straightforward to apply "in place", in a streaming fashion, or "on the fly" as the changeset is applied to the working tree. However, it's possible that that the practical option will be to parse the changeset into a form that is more easily manipulated in memory.

### Working Tree

Finally, there must be an in-memory representation of the client's checked out working tree. There is an open question if this is a reification of the data model, a projected domain model, a cache of patched query results, or something different.

**Comment by DLehenbauer** [comment]
@yann-achard-MS, in your latest thinking, do you ever need to rewind the local working tree to an earlier revision, or will incoming changesets always be 'postbased' to the tip of the local working tree?

**Comment by yann-achard-MS** [comment]
@DLehenbauer - postbasing should allow us not to require rewinding the tree. The only asterisk attached to that has to do with how we support undo. Since we don't want edits to contain all the necessary information to make undo possible without looking at the history, we may find it palatable, as a matter of implementation detail, to use rewinding as way to recover past information for the sake of undo.

**Comment by DLehenbauer** [comment]
@ruiterr - I didn't mean to imply that every copy of the tree data must carry scaffolding, constraints, etc.

Under 'potential variants', I was enumerating everything "changeset-like" that needs a concrete representation.  That's probably broader than the title of this GitHub issue implies, but it may still make sense to include them initially?

**Comment by ruiterr** [comment]
> Under 'potential variants', I was enumerating everything "changeset-like" that needs a concrete representation. That's probably broader than the title of this GitHub issue implies, but it may still make sense to include them initially?

Maybe we should at least provide the option. Again, it depends on the what the purpose for this structure is. Especially with regard to history. In scenarios, where we intend to preserve history and enable branching, will we have two structures, one a pure commit graph with deltas and the Tree Representation is only used for lookup of states (and fine grained history queries) or do we intend to merge all of this into a single History/State tree structure?

In the latter case, this structure would need information about scaffolding, constraints, etc to enable merging /rebasing of branches. Otherwise, it might suffice to keep this in the commit graph.

**Comment by dstanesc** [comment]
Appears true to me that the _SharedTree_ goals (such larger sizes, more efficient data management) create a novel and indirect pressure on the fluid framework itself. For instance enumerated NFRs _(startup time, frame rate, end-to-end latency, bulk interaction style)_, although have an inherent domain _(tree representation)_ component, are pretty general and probably better addressed w/ a more holistic perspective, such framework plumbing. I am interested whether such discussions happen.

**Comment by DLehenbauer** [comment]
Hi @dstanesc - If you're asking if we plan to make changes to the Fluid runtime and services to support SharedTree requirements, the long-term answer is yes.  Our roadmap for SharedTree is heavily influenced by the need to stage runtime and service enhancements to support SharedTree's goals.

If you're asking if we plan to retrofit SharedTree features to the other DDSes, the short-term answer is no, although that's motivated by a desire to ship a SharedTree MVP soon rather than a strategy, so by no means a final decision.

At the moment, the most active discussion in this area is how to structure our storage, which is being led by @CraigMacomber.  He has an initial set of thoughts in draft form is this PR #10246.  I warmly invite your feedback (in the PR or this issue, whichever is easier.)

**Comment by dstanesc** [comment]
FYI @DLehenbauer. Investigating now the above proposed strategy with a general purpose [persistence module](https://github.com/dstanesc/O-O-O-O-O-O-O). Notable status:
- The data is partitioned according to the graph theory in vertices edges and properties. 
- The graph structure is inspired by the Neo4j's index-free adjacency, that is each element (ie. vertex, edge or property) acts as a micro-index for the nearby element. 
- The elements are persisted in a custom binary format as ordered lists of fixed size records. 
- Because of the fixed size, the offset of the element can be computed externally without scanning the data. 
- The references between vertices, edges and properties are offsets in a logical binary array. This allows an extremely efficient path navigation, independent of the overall data graph size. 
- Vertices, edges and properties are stored separately in own logical persistence structures. 
- The persisted structures are partitioned in blocks using content-based slicing. 
- The preferred algorithm at this stage is FastCDC. The blocks are the atoms, the indivisible storage units. 
- Blocks are content-identified, meaning their identity is deterministic and computed as a cryptographic hash of the block content.
