### ISSUE TITLE
Log dataStoreRuntime version separate from runtimeVersion

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#10037]
Since dataStores are loaded dynamically according to their codeDetails, the FF runtime version they're built on may differ from the FF runtime version of the containerRuntime that's loading them.  We would like to observe whether they always match now or not in practice.

We know this is not a well-supported seam, and we are discussing how we might require these to be in lock-step.  I wonder if we'll always need to support at least N/N-1 due to the nature of how code is deployed/updated in a CDN - if the code is downloaded in one bundle there will always be the possibility of a mismatch, even if only briefly during a partner's deployment.

**Comment by curtisman** [comment]
@markfields @vladsud I don't think this is supported scenario, right? Didn't we discuss removing this compat test config as well (i.e. `CompatKind.DataRuntime` and `CompatKind.NewDataRuntime`

**Comment by markfields** [comment]
Cc @agarwal-navin. AFAIK we have to support n/n-1 for Loop's sake and don't have plans to weld these together.

Now I am wondering what n means - prerelease breaking version or public major version? Hopefully we can avoid supporting this between, say, 1.0 and 2.0. That would be very burdensome. I think Vlad brought up this point internally.

**Comment by agarwal-navin** [comment]
We have to support N/N-1 as per the last conversation with FFX. We should remove N/N-2 compatibility test for this layer though.

**Comment by curtisman** [comment]
But do we have that requirement between containerRuntime/datastoreRuntime?

**Comment by agarwal-navin** [comment]
Leevi said that they do have these scenarios.

**Comment by vladsud** [comment]
Tracked in ADO
