### ISSUE TITLE
E2E error for test related to GC

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#10053]
This seems to failing for odsp, r11s. However the driver does not seem to be an issue,
**Link for the E2E test pipeline:** https://dev.azure.com/fluidframework/internal/_build/results?buildId=63577&view=ms.vss-test-web.build-test-results-tab&runId=1335418&resultId=101420&paneView=debug

**Test Failing is this:** https://github.com/microsoft/FluidFramework/blob/160894b09d74a7ef366b1a9ae27aa090c7d2d5fc/packages/test/test-end-to-end-tests/src/test/gc/gcContainerRuntimeCompat.spec.ts#L184
 
**Stack Trace:**
No matching version found in /mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/node_modules/.legacy Error: No matching version found in /mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/node_modules/.legacy at resolveVersion (/mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/dist/versionUtils.js:130:15) at Object.checkInstalled (/mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/dist/versionUtils.js:214:21) at Object.getContainerRuntimeApi (/mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/dist/testApi.js:114:52) at getContainerRuntimeFactory (dist/test/gc/gcContainerRuntimeCompat.spec.js:75:58) at Context.<anonymous> (dist/test/gc/gcContainerRuntimeCompat.spec.js:143:62) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by agarwal-navin** [comment]
Tracked by AB#428
