### ISSUE TITLE
Enforce Named Exports Only

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#10062]
We currently use a lot of wildcard exports from our packages. This leads us to over exporting things we don't need, as frequently we need something across file within a package, so it need to be exported at its definition, but isn't needed outside but due to the wildcard export it's automatically exported.

Ideally there is an es-lint rule we could enable to block wildcard exports. If we had something like that, we could write a script to convert all existing exports to named exports using something like ts-morph. this would prevent the unintentionally expansion of our api

**Comment by anthony-murphy** [comment]
fyi @tylerbutler and @curtisman

**Comment by tylerbutler** [comment]
This lint rule will disallow `export * from ___` statements:

```ts
"no-restricted-syntax": [
    "error",
    {
        "selector": "ExportAllDeclaration",
        "message": "Exporting * is not permitted. You should export only named items you intend to export."
    },
]
```

And it could be limited to only index.ts files using an override in the lint config. Might make sense to enable for some packages individually.
