### ISSUE TITLE
Move reference sliding to Zamboni

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#1008]
Currently local references are slid during the remove process. This makes it hard to add new references to the removed segments in sequence delta events. Sequence delta events are always fired before zamboni runs, so moving the sliding there would allow local references added to removed segment to correctly slide.

[AB#25](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/25)

**Comment by vladsud** [comment]
@anthony-murphy , any plan to make it into reality some day? Or should we close?
