### ISSUE TITLE
Make it easier for hosts to learn when locally saved container state is invalidated by user changes

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#10127]
Container and container runtime expose "dirty" flag that has meaning "data is not preserved in storage".
Outlook team is asking to change this definition and provide more capabilities.

**Scenario:**
Detached container can be serialized by app to avoid data loss.
App may do it on-demand, either on timer or based on user input (like user clicking Save for Draft).
Application thus needs to know if container changed from last save (while container is still detached).
But today's semantic of dirty flag results in container to always be dirty while detached, thus making it impossible for hosting app to know if another save is needed (or data will be lost on closure of such detached container)

**Proposal:**
1. Switch boolean to enum something like {saved, savedLocallyOnly, notSavedAnywhere}
   - any changes in container would transition it to notSavedAnywhere model
3. Provide ability for host to invoke transition notSavedAnywhere -> savedLocallyOnly (for detached containers only). Or maybe invoke it automatically on a call to serialize container.

I think most of that should not be tied actually to detached vs. attached states. As with Wes work same will be true for attached states as well (i.e. need can be the same for attached container).

**Comment by vladsud** [comment]
@markfields, it would be great if you can spend some cycles in June and see if what I've written makes sense, and provide any clarifications as needed. Once we know it's feasible (and we are Ok to add that differentiation), I'd want to give this task to someone else.

**Comment by vladsud** [comment]
One complication - we base events on ops today, and there are no ops in detached container. We likely need to consider other mechanisms to know that container is being changed.

**Comment by vladsud** [comment]
I'm not sure if we want to go that route, but here is one way to work around complexity of no ops in detached state.
We can say that DDS always send ops. And in case of detached container state, they would immediately get acked by container runtime and processed as if they arrived from service. Without any further changes it would do nothing to calculation of dirty state. But it would allow container to differentiate such state and not count such fake acks when calculating dirty state.
A bit ugly, but will work, and will actually simplify (or streamline) any consensus-based DDSs - they essentially do the same think, but within DDS itself.

The state that is really weird is - container is attached (i.e. ops are flowing), but DDS itself (possibly with data store) is not attached. I'd think that because such case is not part of file yet, we should not count changes in them as changes to file. At the same time we can do reverse (and I think it would not matter for most part for our scenario), but it would complicate things, as now we have fake ops and real ops, and mixing those together might cause problems. I think long term we can get rid of this state - I really want to remove all this logic with detached objects and make DDS & data store immediately attach on creation.
See https://github.com/microsoft/FluidFramework/issues/9575

One important consideration - having ops (even if fake) in detached state allows interesting future workflows. For example, we can enable hosts to serialize container state at some point, and then serialize ops on top of it, thus allowing incremental save as user keeps typing in detached state. I think clients like Outlook will love feature like that.

Some code references:
1. mapKernel.ts, set() method - see !this.isAttached check
2. consensusRegisterCollection.ts - write() method, and !this.isAttached() check.

We need to brainstorm possible solutions here.

**Comment by markfields** [comment]
@ssimic2 - FYI on this in case you have input, you've worked in this space recently right?

**Comment by kian-thompson** [comment]
Closed to track in AB#395
