### ISSUE TITLE
ContainerRuntime.SummarizeOnDemand - state === enabled vs state === disableHeuristics 

### ISSUE THREAD

**Issue by NicholasCouri** [microsoft/FluidFramework#10125]
The IContainerRuntime has a method called SummarizeOnDemand that will invoke the method of same name from the Summarizer.
 There used to be a n argument disableHeuristics? to the summarizer's start that would allow us to run the summarizer once with the heuristics disabled.   Part of the work we did during the PR #10047 , we ended up removing that argument and assuming the ISummaryConfiguration would have the state == "disableHeuristics"  in case the consumer would like to run the summarizer on demand. 

We might have a problem in case the original config has state == "enabled"  and, for some instance, its summarizer is not running but the codepath to execute the summarization on demand gets invoked. That scenario would have problems as we would spawn the heuristics runner and we probably do not.

I'm pasting Vlad's comment here but wanted to make sure this is not a supported scenario before resolving this new issue. 

![image](https://user-images.githubusercontent.com/26266632/166393625-a1bcf063-664c-4041-b25a-84c939539418.png)

**Comment by vladsud** [comment]
Tracked in ADO
