### ISSUE TITLE
Remove the deprecated routerlicious-host package

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#10171]
This package is unused, and can be safely removed in vNext.

**Comment by Sassyprogrammer1** [comment]
I would like to work on this issue.

**Comment by ChumpChief** [comment]
Sounds good!  This will also need a notice in BREAKING.md noting the removal (similar to the one I added here announcing the upcoming removal: https://github.com/microsoft/FluidFramework/pull/10170/files#diff-2ca7cfddacad8b7deb1ca47ca14b05b62307e07c545d0459400b51f2f5c93f81R34)

**Comment by Sassyprogrammer1** [comment]
Hi ChumpChief, greetings for the day! This would be my first contribution to the fluid framework so before actually submitting the PR I would like to clarify a couple of things as suggested in the PR guidelines:

1) I am assuming this package to be one of the client packages mentioned as `packages/drivers/routerlicious-host` in the root folder of the directory.
2) After going through the documentation, Api deprecation guide and the PR guidelines I suppose by the removal of this package means to simlpy delete the package or if there are any detailed guidelines on removing packages please mention that here.
3) To test the framework after making changes I guess `npm run build:fast` would be a good practise to follow although the package is not being consumed in examples. If there is any specific CI commands that needs to be run for this perticular issue please mention it here.

I hope my questions are not silly as this is going to be my first contribution. Looking forward to the response.

**Comment by Sassyprogrammer1** [comment]
please have a look:

https://github.com/microsoft/FluidFramework/pull/10616
