### ISSUE TITLE
Make wording for functions consistent in Angular doc

### ISSUE THREAD

**Issue by scottn12** [microsoft/FluidFramework#10206]
### Issue Category

- Typo or editorial suggestion 
  - https://fluidframework.com/docs/recipes/angular/
### Details

There are a couple of instances in this article where functions are referred to as "methods". This should be made consistent with the rest of the article where they are referred to as functions.

**Comment by SohamRatnaparkhi** [comment]
Hi, can I be assigned this issue?
Thank you!

**Comment by scottn12** [comment]
Closed via https://github.com/microsoft/FluidFramework/pull/10209. Thank you @SohamRatnaparkhi!

**Comment by SohamRatnaparkhi** [comment]
> Closed via #10209. Thank you @SohamRatnaparkhi!

You are welcome!
