### ISSUE TITLE
Need a callback to notify all clients after interval collection creation

### ISSUE THREAD

**Issue by amruth-ms** [microsoft/FluidFramework#10205]
There is an API to get interval collection `getIntervalCollection(label: string): IntervalCollection<SequenceInterval>`. With this API, if the interval collection with the given "label" does not exist then the interval collection with the label is created. But when interval collection creation happens there is no call back method provided to notify all clients that an interval collection with a certain label has been created.

The request is to provide a call back when interval collection is created so that all clients get notified when an interval collection is created.

**Comment by Abe27342** [comment]
(copied from some private discourse):

> I think `sharedString.on("createIntervalCollection", (key, local) => { /* subscribe */ });` should work for that use case and is currently in the code. If I'm reading it right it runs into the same awkwardness with us prefixing the keys, so you'll need to strip that prefix in the meantime to actually meaningfully use the key.

(the prefixing I mention was addressed by #10598, see context there)

@amruth-ms going to close this issue. Feel free to re-open with more details if that answer isn't sufficient for your needs.
