### ISSUE TITLE
Fluid Relay Service should support summaries with the size at least 150MB

### ISSUE THREAD

**Issue by milanro** [microsoft/FluidFramework#10201]
## Feature

**Problem**
The summary execution at the DDS fails if the overall size of the size is around 30MB or more. It fails at Fluid Relay Services where it works with Tinilicious server. In our use-cases, we need the summaries well over 100MB. The only way known to us how to achieve it now is to split the data across more DDSes which however brings some challenges at management, atomicity and integrity of those data.

**Investigation**
We tried to investigate Property DDS summarization. It looks like it splits the summary to summary chunks. However, when communicating with FRS, it looks that all those chunks are posted in one request and the answer from FRS historian is HTTP code 413 which means Payload Too Large.

In the picture bellow we see the object requestConfig which contains summary chunks named summaryChunk_xx. The size of 1 summary chunk is 6.8MB. That requestConfig is passed to the fetch method completely with no chunking. And then the request fails on HTTP code 413.

![RequestFromSummaryPDDS](https://user-images.githubusercontent.com/30476743/167401908-b2672759-2fcd-4394-912a-f22a9c981bd1.png)

**Solution alternatives**

***Chunking support***
If the client code communicating with FRS would post the summary in chunks, the limits of payload size on the FRS server could stay relatively low. Both client and server would have to support chunking but the fix would be transparent for users of Property DDS as it already supplies the summary in chunks. 

***FRS payload size***
Alternatively, FRS could support payloads around 150MB which is (only temporarily) acceptable solution.

**Comment by tylerbutler** [comment]
@ahmedbisht @yangg-msft Can you take a look at this?

**Comment by tylerbutler** [comment]
Note that this could be a PropertyDDS-only thing, due to how it's integrated with Fluid. Maybe its summarization strategy could be changed to produce smaller summaries. So this could be something that should be addressed at the DDS level instead of or in addition to server-side changes.

If that's the case, then I suggest we open a new issue for any PropertyDDS or DDS infrastructure changes and leave this one to cover server-side changes.

**Comment by milanro** [comment]
Hi @tylerbutler, it looks to me that PropertyDDS does it's job in cutting summary to chunks. Of course it cannot reduce the size of overall summary as long as the data are there and cannot be reduced. But it populates the ISummaryTreeWithStats so that it cuts the content to blob chunks.

The result of summarization which is passed to fluid client is as follows.

```
export interface ISummaryTreeWithStats {
    stats: ISummaryStats;
    summary: ISummaryTree;
}
```
The summary content is stored under the object

```
export interface ISummaryTree {
    type: SummaryType.Tree;
    tree: { [path: string]: SummaryObject };
}
```
Where SummaryObject can be ISummaryBlob

`export type SummaryObject = ISummaryTree | ISummaryBlob | ISummaryHandle | ISummaryAttachment;`

Property DDS cuts it's content to blobs with limited size (I saw 6,8MB). I was expecting that the reason for this cut was that fluid could optimize the communication with server. This was only my understanding and it does not look to work this way but it looks to me that it could be a way.

**Comment by vladsud** [comment]
> we need the summaries well over 100MB

This is not a requirement we want to go with. Summaries should be incremental relative to user changes. In most (like 99.99% cases) user changes are small, and thus summaries should be small.
There will be always a case of user pasting 10Mb of text or similar change (like import of a lot of data). I think it's responsibility of the application to figure out how to partition that process to allow summaries to be within reasonable envelope.

I think you should work with particular DDSs implementations that do not satisfy incrementality requirements. I'd guess @taylorsw04 is the right person to start with here (for tree-related DDSs). If any other DDS is causing trouble, please loop me in.

I'll add one more thing here that goes cross DDS (and does not help with incrementality part but may help with overall size question). We should seriously consider various packing / compression algorithms: https://github.com/microsoft/FluidFramework/issues/9406

**Comment by DLehenbauer** [comment]
@vladsud - I'm interpreting milanro's request as:

* They need a tree DDS that scales to at least 150mb of data in the near term.
* The current failure point is that monolithic summaries unnecessarily yield a very large summary tree.

So, I think you're correct that the underlying request is for incremental summaries.

@milanro - Did I get that right?

**Comment by dstanesc** [comment]
@DLehenbauer - True, our request is of at least 150mb of data for both tree and PropertyDDS

@vladsud - Thank you for the guidance.  We do understand that any particular DDS should provide stable partitions (blobs) in support to incrementality. Thus the incremental upload/download can be handled by the driver alone (such as skipping blobs known to be available in doc storage from previous uploads). Am I correct?

@ruiterr - I see that PropertyDDS already uses compression (actually unsure whether packr refers to msgpack ) but I believe the chunking done in the summarize method is probably unlikely to yield very stable partitions as the tokenizing applies sequentially on mutated and already serialized content.

**Comment by vladsud** [comment]
I'd split the work into these buckets - not all buckets are required by all DDSs:
1. Stable partitioning algorithm. It should result in (amortized over time) only one blob having different content across summaries for trivial user changes. For example, if we are talking about plain text, it's not Ok to break it at 1000 characters per blob, as inserting one character at the beginning of text causes all blobs to be different form previous summary.
2. Ideally - DDS having smarts not to generate blobs that are same from previous summary, but instead simply referencing blob from previous summary. I.e., not even waste CPU and memory to generate stuff that is not needed.
   - This method is preferred over alternative, especially when we are talking about 100Mb per summary payload (non-incremental). We would love to have an ability to run summaries often, and code (overall) scale well on low-end machines.
3. Alternative: DDS always generates blobs, but we add a layer that can detect blobs with exactly same content and dedup them
   - If we go that route, I'd prefer it to be in a layer that is a driver adapter (from interface POV), but logically belonging to container runtime layer (i.e., container runtime wraps actual storage with this adapter). It should not be driver-specific, and this logic should be isolated and tested independently, i.e., not baked into driver.

Please note that # 2 and # 3 are not exclusive - we would benefit from having both of them. # 2 is more efficient for single DDS scenario, # 3 helps with cross-instance deduping (for example all attribute blobs for a map can be deduped that way).

**Comment by milanro** [comment]
@DLehenbauer @vladsud 
> * They need a tree DDS that scales to at least 150mb of data in the near term.
correct

> * The current failure point is that monolithic summaries unnecessarily yield a very large blob upload.
The point is that Property DDS which we use tries to split the monolithic summary into chunks (smaller blobs). After discussion with @ruiterr I understood that fluid used to support that chunking and it used to send every blob in one request which looks to be changed now and all blobs are sent at once.

**Comment by vladsud** [comment]
Chunking or not, we do not want to send 150Mb to service every 15-60 seconds if user typed a single character.
I can't comment about Property DDS (do not know much history here), but we never had (at least when it comes to support in runtime or FRS driver) capability to dedup / reuse blobs, so whatever summary produced was sent to service.
Service can do blob dedup (content addressable storage), but it only helps with storage aspect of the problem, it does not help with client perfr (CPU, bandwidth) and COGS.

DDS involved here needs to be smart to do stable partitioning and blob reuse across summaries (it's less reuse, it's more about referencing blobs in previous summaries).

**Comment by milanro** [comment]
It looks to me that Fluid Relay Service now supports maximum size of the summary up to 1MB. I would like to ask whether such dramatic change really happened  (probably on Historian) or whether I have wrong test data. When posting summary over 1MB, I am getting (413 Request Entity Too Large) : 
browser-ponyfill.js:518          POST https://historian.westus2.fluidrelay.azure.com/repos/xxx/git/summaries?token=xxx net::ERR_FAILED 413
Based on our previous discussions I understand the reason for such change.
