### ISSUE TITLE
Add link to official homepage for Safari in supported browser list

### ISSUE THREAD

**Issue by scottn12** [microsoft/FluidFramework#10210]
### Issue Category

- Typo or editorial suggestion 
  - https://fluidframework.com/docs/faq/

### Details

At the bottom of this page there is a list of browsers supported by FluidFramework. Each browser is linked to its official homepage, except for Safari. This should be made consistent by linking Safari to https://www.apple.com/safari/

**Comment by Josmithr** [comment]
Happy to take this on :)
