### ISSUE TITLE
`build:fast` failing on clean main

### ISSUE THREAD

**Issue by Josmithr** [microsoft/FluidFramework#10231]
I am consistently running into a build failure on a clean main (revision d112cfb). 

Running `npm install` followed by `npm run build:fast` results in a build failure in `@fluid-internal/merge-tree-client-replay`. 

The failure appears on line 17 of `clientReplayTool`:

```typescript
// eslint-disable-next-line import/no-internal-modules
import { TestClient } from "@fluidframework/merge-tree/dist/test/testClient";
```

Looking at the build output log, I frequently (but not always) see `@fluid-internal/merge-tree-client-replay` being built *before* `@fluidframework/merge-tree`. In either case, `@fluid-internal/merge-tree-client-replay` begins building before `@fluidframework/merge-tree` completes its build.

```shell
@fluid-internal/merge-tree-client-replay: error during command 'tsc'
@fluid-internal/merge-tree-client-replay: src/clientReplayTool.ts:17:28 - error TS2307: Cannot find module '@fluidframework/merge-tree/dist/test/testClient' or its corresponding type declarations.
@fluid-internal/merge-tree-client-replay:
@fluid-internal/merge-tree-client-replay: 17 import { TestClient } from "@fluidframework/merge-tree/dist/test/testClient";
@fluid-internal/merge-tree-client-replay:                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@fluid-internal/merge-tree-client-replay:
@fluid-internal/merge-tree-client-replay:
@fluid-internal/merge-tree-client-replay: Found 1 error.
[276/560] x @fluid-internal/merge-tree-client-replay: tsc - 10.291s
```

It seems as though the above import pattern is at odds with our parallel build here.

**Comment by tylerbutler** [comment]
Note: this doesn't repro with `npm run build`.
