### ISSUE TITLE
Excel: separate node-specific and browser-specific packages

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#1032]
FYI: I encountered the following error while plugging Fluid into the Excel/Augloop:

```
C:/AugmentationLoop/node_modules/@microsoft/fluid-component-core-interfaces/dist/componentRender.d.ts(13,17): error TS2304: Cannot find name 'HTMLElement'.
```

A convenient workaround is to append "dom" to the list of libs in their tsconfig.json, but it's not ideal as it reduces compile-time safety for a backend-only customer.

I would have to do some research to recommend a best practice here, but likely it involves factoring packages to separate browser-specific and node-specific code.

**Comment by vladsud** [comment]
@DLehenbauer , is this still relevant?
