### ISSUE TITLE
Collect roundtrip latencies for signals

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#10399]
It would be great to collect roundtrip latencies for signals, similar to how we do so for ops.
It's much simpler for signals, as we have pretty much no pausing, no queues, etc.
So just measuring time between outbound and inbound queues would be sufficient.
This would be equivalent to durationInboundQueue property in OpRoundtripTime event.

Place where it would be of enormous help - #8908, where we would be able to compare times for ops and signals and tell with much more confidence if problems are in ordering service around op processing.

**Comment by NicholasCouri** [comment]
Tracked by https://dev.azure.com/fluidframework/internal/_workitems/edit/413
