### ISSUE TITLE
Deprecate view-related interfaces.

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#1041]
Once the scenarios these support are proven to be supportable just using popular UI frameworks and demonstrated patterns, we should not continue to maintain these.  #1290 will precede this as an intermediate step.

- [x] IComponentHTMLRender
- [x] IComponentHTMLVisual
- [ ] IComponentHTMLView
- [x] IComponentReactViewable

**Comment by vladsud** [comment]
@ChumpChief , can you please glance? I think we can close this item :)
