### ISSUE TITLE
Remove trackState from IChannel's getAttachSummary and summarize methods.

### ISSUE THREAD

**Issue by NicholasCouri** [microsoft/FluidFramework#10455]
## Work Item

While adding documentation for the Summarizer in this PR: #10435 , we realized the trackState argument from IChannel is not actually required. It is currently only used for testing purposes where the context around the scenario would be ignored and the test would simply validate the  summary/attachment functionality. 

This work item will track down  whether we can remove this trackState and automatically decided whether the
handles will be used or not.  Outstanding question is how we will adjust the tests once it has been removed. 

**Approach**
TBD

**Open questions**
How to fix the current tests

**Comment by vladsud** [comment]
Tracked in ADO
