### ISSUE TITLE
Stop exposing ITelemetryLogger as a public interface/member of containerContext

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#1051]
As a platform, the Fluid Runtime should standardize only on a very small logging interface (ITelemetryBaseLogger) and this is what the Loader takes in today. To reduce confusion we should remove all public references to the internal helper ITelemetryLogger.

Today ITelemetryLogger is exported out of common-definitions and a public "logger" of type ITelemetryLogger exists off of containerContext. Through discussions with the Fluid Runtime team, we believe these should are Fluid Runtime specific and not public APIs and it was likely not intentional to expose "logger" to container/component code.

**Comment by vladsud** [comment]
I did it recently (maybe as recent as 0.40) - compat layer boundaries only use ITelemetryBaseLogger.
