### ISSUE TITLE
Review all asserts in the framework and change them into a thrown error unless data loss has to be prevented

### ISSUE THREAD

**Issue by marco-ms** [microsoft/FluidFramework#10539]
## Work Item
With every new release, it looks like new asserts in the code are introduced. These asserts seem used to enforce bad states or bad api sequence calls, but have the down side effect to crash working code, which in turn can cause data loss or anyway bad user experience.
An example in this PR: https://github.com/microsoft/FluidFramework/pull/7699/files#diff-01eeb7567dd98442afb9a308001150972f600ef3f04e17a71f88b34a0b8ee153R444

**Approach**
Whenever a code asserts, let's log a warning and then proceed to throw an error instead, which can be catch. If the documentation is lacking details on any behavior, please document it further to avoid "surprises" from the caller point of view, see also: https://github.com/microsoft/FluidFramework/issues/10537

**Open questions**
- Why are we asserting? What is the goal in that?

**Additional context**
- Teams bundles many pieces of this frame work, making an assert means crashing entire parts of it and can cause lot of user pain.

**Acceptance criteria**
- Only assert whenever there is data loss to be prevented.

**Comment by vladsud** [comment]
I've opened a task for that specific assert - it should be an exception with proper text:
https://dev.azure.com/fluidframework/internal/_workitems/edit/628

asserts are exceptions. There is (unfortunately) no good alternative in JS (in native code we would terminate process right away - directly). So, I'm not sure what is the purpose of proposal of replace it with exceptions - it's one and the same thing, the difference is only in message. Asserts are supposed never to be hit in production, we monitor them through telemetry and follow up when they happen.

asserts are used across repo where we validate invariants. They are there to capture bugs sooner, ideally before we release next release (or even better - before PR is merged). I do not see what reviewing asserts gives us - it's like review random IF statements in code for correctness.

Checking invariants early and often allows us to ship higher quality code.
There are plenty of documentation on that on internet (and experience in various teams, like Office, Edge, Midori), key keywords to look for are "fail-fast" and "process abandonment"
