### ISSUE TITLE
Several container's APIs may throw or even worse assert, while inline documentation states nothing of that

### ISSUE THREAD

**Issue by marco-ms** [microsoft/FluidFramework#10537]
### Issue Category

- Incorrect/Outdated information
  - https://github.com/microsoft/FluidFramework/blob/main/common/lib/container-definitions/src/loader.ts
```
   /**
     * Allows the host to have the container force to be in read-only mode
     * @param readonly - Boolean that toggles if read-only policies will be enforced
     * @alpha
     */
    forceReadonly?(readonly: boolean);
```

- We just learnt that calling this API on a closed container may result in an assert. Further more there was a proposal to throw an  error (better). Either ways, it has to be documented every behavior that is not allowed and what that means.

### Details
Please go through all public APIs in IContainer and documents which one are throwing and which one asserts and when exactly. The caller should not have a "surprise" thrown error or even worse an assert that is not able to catch.

**Comment by vladsud** [comment]
I've opened ADO task to replace assert to throw with better error message and have better description.
https://dev.azure.com/fluidframework/internal/_workitems/edit/628

I'm not sure what going through all public APIs will do. APIs will throw when they are misused. They may throw for a lot of other reason we do not control - it's JS, and exceptions are the part of the language and natural code flow.

I think documenting main pitfalls or non-obvious things is needed, yes.
