### ISSUE TITLE
Get all intervals with 'walkSegments' API

### ISSUE THREAD

**Issue by amruth-ms** [microsoft/FluidFramework#10606]
## Feature

It would be nice to load interval information at the same time when other data like marker or text data is being loaded. As of now, walkSegments API is used to load all the information from Fluid like Marker data or text data. So, the request from this feature item is to make loading interval information through the same 'walkSegments' API work as well. 

As of now, all intervals can be loaded with the following code and this works perfectly fine. 
`for (let intervalCollectionLabel of sharedString.getIntervalCollectionLabels()) {`
    `const unscopedLabel = intervalCollectionLabel.startsWith("intervalCollections/") ? intervalCollectionLabel.substring(20) :` `intervalCollectionLabel;`
    `const intervalCollection = sharedString.getIntervalCollection(unscopedLabel);`
    `for (let interval of intervalCollection) {`
        `// Do something with interval.`
    `}`
`}`

**Comment by Abe27342** [comment]
@amruth-ms could you elaborate on the usage here? The thing that's slightly odd about this request is that unlike markers, intervals have two endpoints that may be quite far apart in the tree. Current public APIs already would allow a user to see the endpoints of each interval as you walk all segments. To avoid making arbitrary decisions about how to return intervals (which don't align with segments) as part of a segment walk, if we implemented this I think the right way to go about it would be to provide something like a `getIntervalFromEndpoint(endpoint: ReferencePosition): SequenceInterval` API.

The reason why I'm curious to learn more about usage is that for the cases I can think of, such an API wouldn't be much easier to work with than the current API, which supports iteration of all intervals and spatial search for all intervals overlapping a region. Since implementing the O(1) query above would require some memory overhead, I wouldn't want to add it without good reason.

**Comment by amruth-ms** [comment]
Hi @Abe27342 . Thank you for your comment. My primary thinking when filing this feature was, as far as I know, we don't `get` information from Fluid directly. We send ops to Fluid and provide a call back method to receive information back from Fluid. The same mechanism is being followed when walking segments. We use walk segments API(` walkSegments<TClientData>(
        handler: ISegmentAction<TClientData>,
        start?: number, end?: number, accum?: TClientData,
        splitRange: boolean = false`) and provide a call method to get information back from Fluid. Even though the current APIs(`getIntervalCollectionLabels(): IterableIterator<string>` and `getIntervalCollection(label: string): IntervalCollection<SequenceInterval>` ) to get all intervals from Fluid are very easy to use, this doesn't seem to align with sending ops and getting information back through a call back method mechanism we typically use. So, when filing this request I was thinking more in a stylistic sense rather than performance sense(probably not a great way of thinking). 

I was imagining the usage of `walkSegments` API for Intervals as follows. When we get segments though a call back method during walking segments, we could either get a start segment or an end segment of an interval (sometimes, I think start and end segments are the same for an interval).  If we get a segment that is associated with an interval then if it is the segment that is associated with just the start point of an interval then we don't do anything. If it is the segment that is associated with the end point of an interval, then we add that interval into our local list of intervals. Not sure if I my understanding of segments is totally correct here. But this is how I was imagining to use `walkSegments` API for intervals.

I am not sure if I completely understand when you said the following 
> Current public APIs already would allow a user to see the endpoints of each interval as you walk all segments 

> I think the right way to go about it would be to provide something like a `getIntervalFromEndpoint(endpoint: ReferencePosition): SequenceInterval` API

I don't see the segments of intervals when walking through all segments through `walkSegments` API . Am I missing something here?

**Comment by amruth-ms** [comment]
Hi @Abe27342 . Thank you so much for the detailed explanation :) . Getting the interval information through an API like `getIntervalFromEndpoint(endpoint: ReferencePosition): SequenceInterval` makes sense. But I do see your point about directly getting information from Fluid. I thought the call back method under `walkSegments` API, might be used asynchronously. But it looks like the call back method is being called in a synchronous way. So even after implementing an API like `getIntervalFromEndpoint(endpoint: ReferencePosition): SequenceInterval` it would not be much different from the way we are getting intervals now(i.e through `getIntervalCollectionLabels` and `getIntervalCollection` APIs I mentioned in the description). I don't think there is any action needed from Fluid w.r.t this feature, as I don't see any benefit by adding a new way of getting intervals as the current APIs that we are using are straight forward to use. Thanks again for the detailed explanation!! Will close this feature request as won't fix.

**Comment by Abe27342** [comment]
no problem! Thanks for the continued feature requests--some of the other ones you made around interval collection are good callouts and scheduled for next month :)
