### ISSUE TITLE
Re-export ConnectionState from fluid-framework

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#10681]
We use connection state on the FluidContainer API but we don't re-export it for developers to consume.

add `ConnectionState` to the items re-exported from container-definitons in fluid-framework. [FluidFramework/containerDefinitions.ts at main · microsoft/FluidFramework (github.com)](https://github.com/microsoft/FluidFramework/blob/main/packages/framework/fluid-framework/src/containerDefinitions.ts)

**Comment by curtisman** [comment]
@skylerjokiel We probably need tools to detect and prevent this from happening again?
