### ISSUE TITLE
Design: Container Loading

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#1069]
## Existing Flow
![image](https://user-images.githubusercontent.com/1951092/73386233-60c69f00-4283-11ea-8651-744d50f10f88.png)

## Possible Flows
CREATE_ALWAYS | Creates a new file, always.   If the specified file exists and is writable, the function   overwrites the file, the function succeeds
-- | --
CREATE_NEW | Creates a new file, only if it does not already exist.   If the specified file exists, the function fails
OPEN_ALWAYS | Opens a file, always. If the specified file does not exist and   is a valid path to a writable location, the function creates a file
OPEN_EXISTING | Opens a file, only if it exists.   If the specified file does not exist, the function fails.

## Considerations

- Cancellation: #1069
- IFrames
- Pre-fetching
- Logging
- Lifecycle events
- Error handling
- Offline Creation
- Creation from Snapshot/Summary

**Comment by vladsud** [comment]
@anthony-murphy , @tylerbutler , can we move it somewhere to docs and close the issue? It has been around for 1.5 years mostly without any changes.
