### ISSUE TITLE
Abstract the scheduling algorithm in ContainerRuntime::ScheduleManager inside an interface to make it pluggable

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#1071]
This came up in PR #1049 .

We would like to make the op scheduling algorithm in ScheduleManager pluggable by abstracting it inside an interface. As per Kurt's comments:
Can we abstract the scheduling algorithm itself inside an interface? Probably too much for this PR but eventually it would be nice to be able to specify an algorithm to use via this interface. Right now the code is very UI specific. And given that the majority of current customers are UI focused that makes sense. But we do have cases where we are running code in a web worker or on the server side and so frame granularity isn't the target.

Couple of things to consider when making it pluggable:
- In ScheduleManager, we pause the queue if its time quanta to process ops expires and schedule a resume via setTimeout. We might want to hook on the animation frame rather than a timeout.
- Every time we schedule a resume (as mentioned above), we increase the time quanta for the next set of ops. This is done so that we keep the app somewhat responsive while ensuring that we don't fall too far behind in op processing. However, there might be apps who would prefer the app to stay responsive rather than ever lag and pay the cost of being behind.

**Comment by vladsud** [comment]
Given that we did not make any progress here for almost 1.5 years, closing. Good idea, but if it becomes higher priority, we can always reactivate
