### ISSUE TITLE
[IntervalCollection] changeProperties API has an event that gets fired twice on a local client

### ISSUE THREAD

**Issue by amruth-ms** [microsoft/FluidFramework#10759]
## Describe the bug

Under interval collection there is an API `public changeProperties(id: string, props: PropertySet)`. When a client calls this API, the client will get notified back about the change in interval properties through `changeInterval` event. 

But the event `changeInterval` is getting fired twice after calling `changeProperties` API. When the event is fired for the first time, it seems to happen synchronously (i.e, immediately after calling `changeProperties` API, without sending the op to the server). When the event is fired for the second time, this seems to happen asynchronously after some sort of acknowledgment of the OP from server.

### To Reproduce
1. Open a document with one client. 
2. Insert an interval. Call `changeProperties` API on the same interval. 
3. Observe that client gets notified about the change in interval properties twice through `changeInterval` event. 

### Expected behavior
Local client that called `changeProperties` API, should immediately get notified about the change in interval properties through `changeInterval` event. And the local client should not get notified about the change in the interval properties again after that. If there are any other clients collaborating on the same document, then they should also get notified about the change in interval properties after server receiving the OP. 

[AB#907](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/907)

**Comment by Abe27342** [comment]
addressed by #10966
