### ISSUE TITLE
[IntervalCollection] change API has an event that gets fired twice on a local client

### ISSUE THREAD

**Issue by amruth-ms** [microsoft/FluidFramework#10761]
## Describe the bug
Under interval collection there is an API `public change(id: string, start?: number, end?: number): TInterval | undefined`. When a client calls this API, the client will get notified back about the change in interval position through `changeInterval` event.

But the event `changeInterval` is getting fired twice after calling `change` API. When the event is fired for the first time, it seems to happen synchronously (i.e, immediately after calling `change` API, without sending the op to the server). When the event is fired for the second time, this seems to happen asynchronously after some sort of acknowledgment of the OP from server.

### To Reproduce

1. Open a document with one client.
2. Insert an interval. Call `change` API on the same interval.
3. Observe that client gets notified about the change in interval position twice through `changeInterval` event. When client gets notified about the interval position change for the first time, the interval does not even have the updated position. Only when client gets notified for the second time, the interval that is passed through `changeInterval` seems to have the updated position of the interval. 

###Expected behavior

Local client that called `change` API, should immediately get notified about the change in interval position through `changeInterval` event. And the local client should not get notified about the change in the interval position again after that. When the local client gets notified about the change in interval position, the interval that is passed through `changeInterval` event should have the updated position of the interval. If there are any other clients collaborating on the same document, then they should also get notified about the change in interval position after server receiving the OP.

**Comment by Abe27342** [comment]
addressed by #10966
