### ISSUE TITLE
[IntervalCollection] changeInterval event should include delta information to support undo/redo operations

### ISSUE THREAD

**Issue by amruth-ms** [microsoft/FluidFramework#10762]
## Describe the bug
When an interval position or properties are changed through `public change(id: string, start?: number, end?: number): TInterval | undefined` or `public changeProperties(id: string, props: PropertySet)` APIs respectively, the client gets notified about the change in interval position or properties through `changeInterval` event. The listener of the `changeInterval` event has the method declaration as shown in the code below.  The listener does not have any parameter which will hold the delta value. Like if interval properties are changed through `public changeProperties(id: string, props: PropertySet)` API, the listener should have a parameter which gives the old parameters. Similarly, if interval position is changed through `public change(id: string, start?: number, end?: number): TInterval | undefined` API, the listener should have some parameter which indicated the previous position of the interval(Like previous text segments of the interval). The previous values will be used when a user performs an `undo` operation. When an undo is the interval will be restored with its previos value.   

> (event: "addInterval" | "changeInterval" | "deleteInterval",
>         listener: (interval: TInterval, local: boolean, op: ISequencedDocumentMessage) => void);

**Comment by Abe27342** [comment]
addressed by #10966
