### ISSUE TITLE
Consider bumping the TypeScript target to ES2018 or later

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#10922]
## Work Item
**Describe the outcome you expect**
The TypeScript compiler transpiles some newer syntax depending on the value of target in the tsconfig. Today, this is set to ES2017 for the Fluid Framework repo. Bumping this version to ES2018 would result in features like object spread/rest to no longer be transpiled. If we were able to bump all the way to ES2020, more verbose features like ?. and ?? to no longer be transpiled. In experiments in the internal Loop repo, moving to ES2020 would enable us to ship ~175KB of less JavaScript. Having similar changes in the FF repo would drive that even smaller. Note that we are not ready to move to ES2020 on the Loop side yet, since we need to revisit our supported browser story first.

**Approach**

**Open questions**

What is the official supported browser matrix for Fluid Framework?
Should FF ship ES2020 and rely on consumers to use babel to transpile if necessary (it isn't possible to "un"-transpile)?

**Additional context**

The Loop team has bumped from ES2017 to ES2018 since that's compatible with our existing browser support matrix. This only had modest ~15KB decrease, but it is expected to have no negative impact on our users. We added eslint rules to ensure that no one uses regex features not supported in Safari or older versions of FF: https://eslint-plugin-es.mysticatea.dev/

**Acceptance criteria**

Fluid Framework publishes a

**Comment by christiango** [comment]
This should not be closed, @vladsud is this the right issue for tracking this work?

**Comment by christiango** [comment]
@vladsud any update on this one?

**Comment by Abe27342** [comment]
The next major release targets ES2020 due to #15941.
