### ISSUE TITLE
Compiled with problems: Warning under node modules

### ISSUE THREAD

**Issue by osfprieto** [microsoft/FluidFramework#10965]
## Describe the bug
When bumping office-bohemia to version 1.1.0, we're seeing compilation warnings being detected by webpack around `SummaryType`.

```
Compiled with problems:X

WARNING in ../../node_modules/@fluidframework/driver-base/node_modules/@fluidframework/driver-utils/lib/blobAggregationStorage.js 244:21-37

export 'SummaryType' (imported as 'SummaryType') was not found in '@fluidframework/protocol-definitions' (possible exports: FileMode, MessageType, NackErrorType, ScopeType, TreeEntry)
```

These seem to be internal to the node modules.

### To Reproduce
Bump user code to 1.1.0.

Reproduced on office-bohmia runnnig `yarn start --to demo-host`.

### Expected behavior
Compilation shouldn't yield warnings.

**Comment by osfprieto** [comment]
@tyler-cai-microsoft

**Comment by tyler-cai-microsoft** [comment]
Investigating

**Comment by tyler-cai-microsoft** [comment]
Ran a local build on release branch `release/1.1` and did not experience any build errors. Also investigated the files in question, and both seem to include `SummaryType`.

**Comment by tyler-cai-microsoft** [comment]
The last impactful change to `SummaryType` was done 8 months ago. Considering that the local build and our internal pipeline build is passing, we do not think this is a bug on our end.
