### ISSUE TITLE
Unexpected error when container load is canceled

### ISSUE THREAD

**Issue by pragya91** [microsoft/FluidFramework#10996]
[This code change](https://github.com/microsoft/FluidFramework/pull/9195/files#diff-e8890301d42492461946dabfe47f88be2b209b931ca47bbe01066e34aa37b871R69), introduced throwing of a new exception in `runWithRetry` utility even when the operation was "cancelled". Since cancelled operations are intentional, the error could be just logged and not thrown.

**Comment by vladsud** [comment]
@pragya91, if a function is supposed to return something (let's say a snapshot fetched from storage), there is no way to log an error and return nothing. It should either return snapshot or fail with exception. So really, there are 3 options here:
- continue infinitely with retries despite knowing that result is not useful (as whole thing is cancelled)
- reorganize code base across all layers and add | undefined and proper handling to each layer to mean that operation did not complete
- throw exception.

# 3 is the natural way to handle issues in JS. It's not ideal, as exceptions should be for exceptional cases, but that's a paradigm of the language. We should get to be bottom of these particular issues, but these exceptions should not bubble up to observable APIs as whole operation (Container) is closed, so eventually such exception should not be something you look at (i.e. it will register in our telemetry but should not propagate to APIs and app telemetry). We should fix issues where it's not the case.

**Comment by pragya91** [comment]
I believe we can close this issue since it seems to have been fixed with this PR that you pointed: https://github.com/microsoft/FluidFramework/pull/11000/files

**Comment by vladsud** [comment]
The PR you mentioned was not merged - it was closed. These ADO items are tracking follow up here and providing better error messaging - scheduled to September sprint.

https://dev.azure.com/fluidframework/internal/_queries/edit/674/?triage=true.
https://dev.azure.com/fluidframework/internal/_queries/edit/669/?triage=true

Let's continue discussion in ADO
