### ISSUE TITLE
Error in snapshot update script

### ISSUE THREAD

**Issue by WayneFerrao** [microsoft/FluidFramework#11174]
## Describe the bug
The script `npm run test:update` in packages/test/snapshot is used to save and update the current snapshots to the new format. The bug is that the script does not seem to update all applicable snapshots. 
For example, in this [PR](https://github.com/microsoft/FluidFramework/pull/11049), summaryCount was removed. This necessitated an update to the snapshot tests. However, running the `npm run test:update` script did not remove instances of summaryCount in the current snapshot files in `content/snapshotTestContent/SharedMatrixDeletes/current_snapshots/` which woud lead to assertion errors as seen below.

![snapshot error](https://user-images.githubusercontent.com/23732584/179853587-586a3159-2801-4ae3-949e-ceb58b886b54.PNG)
To be clear the difference in assertions is that summaryCount was expected and the 'actual' did not have it.
This bug may have to do with the update script not reaching/updating every snapshot.

### Expected behavior
The expected behaviour in this example would be that ALL (not most) instances of summaryCount would be removed from snapshots when running `npm run test:update`. This had to be fixed manually by going into the files in the relevant directory and removing 'summaryCount'

**Comment by andre4i** [comment]
Moved to ADO:1460
