### ISSUE TITLE
The assert polyfill is needed when using InsecureTokenProvider

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#11350]
PR #10488 added a dependency on the node "assert" package in test-runtime-utils. That package contains InsecureTokenProvider, which is used in many demos and samples in the browser, so the assert dep introduces the need for a polyfill.

The assert polyfill is quite large and we should avoid requiring it.

**Comment by zhonglin94** [comment]
I face the same problem. Is there any workaround to fix this in Angular 12 projects?

**Comment by tylerbutler** [comment]
The fix for this should be in upcoming version 1.2.6 and 2.0.0-internal.1.2.0.
