### ISSUE TITLE
build error: pnpm

### ISSUE THREAD

**Issue by anjola-adeuyi** [microsoft/FluidFramework#11355]
## Describe the bug

Encountered build error several times -: `pnpm nx build @fluid-experimental`

### To Reproduce
1. Go to `pnpm branch`
2. Click on `pnpm nx build @fluid-experimental`
3. See error

**Comment by tylerbutler** [comment]
Hi @anjola-adeuyi! Thanks a lot for trying out the pnpm branch and filing this issue. The pnpm branch was an exploration into alternative tools to use within the repo. We're planning work right now to update the repo tooling, and the pnpm branch has been removed.
