### ISSUE TITLE
Presence in CodeMirror is not always correct

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#1157]
CodeMirror has presence but it's off by one when typing. This is because the signal hits the other users before the op.

Update the presence to use the character typing as the notification to move the CP instead of always sending a signal. The signal should only be sent on cursor or selection indication.

**Comment by vladsud** [comment]
Related: https://github.com/microsoft/FluidFramework/issues/3591
IMHO, we should either make it production quality or cut
