### ISSUE TITLE
Move  DefaultServiceConfiguration to Protocol Definitions

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#1167]
We should centralize  DefaultServiceConfiguration in protocol definitions, and unify usages. It would also be good to do some research and document the reason/meaning for the values. @tanviraumi may have some insights.

**Comment by curtisman** [comment]
Definitions in the services are refactored in #4435 and #4462.

There is only one copy in `test-loader-utils/src/mockDocumentDeltaConnection.ts` which is probably ok to have a copy just for testing.
