### ISSUE TITLE
React Example should contain de-registering function for useEffect

### ISSUE THREAD

**Issue by rsommerfeld** [microsoft/FluidFramework#11794]
### Issue Category
- Missing page/section/topic

### Details
The React Demo ([here](https://github.com/microsoft/FluidExamples/tree/main/react-demo), or [here](https://fluidframework.com/docs/recipes/react/)) obtains a connected container with an useEffect hook like this:

``` Typescript
// Add to the top of our App
const [fluidMap, setFluidMap] = React.useState(undefined);

React.useEffect(() => {
    getMyMap().then(myMap => setFluidMap(myMap));
}, []);
```

where `getMyMap` creates or connects to a new container and returns one of the shared DDS'.

However, this can result in multiple active container connections as described in [Issue 11304](https://github.com/microsoft/FluidFramework/issues/11304). The issue is that react can sometimes re-run the useEffect hook for various reasons, resulting in the creation of another active connection without cleaning up the previous one properly.

The solution (as proposed in the issue), is to give react a de-registration function that cleans up the old connection (disconnect the container), when the useEffect function is re-run. For that the `getMyMap` function will have to be refactored into a `getContainer` function, which can then be used like this:

``` Typescript
React.useEffect(() => {
  let container;
  (async () => {
    container = await getContainer();
    const myMap = container.initialObjects.myMap;
    setFluidMap(myMap)
  })();

  // Return a de-registration function that disconnects the old container whenever the hook re-runs
  return () => {
    if (container != null) container.disconnect();
  };
}, []);
```

The README/documentation should probably also explain why the return function is necessary and how it works (i.e., the reference to container is bound to the "let", which will update once the async function finishes).

ADO Item: [AB#4196](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/4196)

**Comment by Vishruta-Patil** [comment]
Can I work on this issue ?

**Comment by tylerbutler** [comment]
@Vishruta-Patil - we would happily accept a pull request that addresses this issue. I can be your point of contact to help with details like where to make the changes, code review, etc. Please just \@mention me as needed. Note that this issue will need to be fixed in two repos - this one and the https://github.com/microsoft/FluidExamples repo.

**Comment by Vishruta-Patil** [comment]
Thanks @tylerbutler.
Can you pls tell me the files where I have to make changes?

**Comment by Vishruta-Patil** [comment]
Also, Do I have to make a seperate issue in the Fluid examples repo @tylerbutler

**Comment by tylerbutler** [comment]
@Vishruta-Patil Sorry for not replying sooner! The majority of the changes needed here are in the https://github.com/microsoft/FluidExamples repo. That's where the code is. There are also documentation updates that will be needed but that can be done separately.

The code changes should be made here: https://github.com/microsoft/FluidExamples/tree/main/react-demo

**Comment by Vishruta-Patil** [comment]
Sorry for not been active, I didnt get notification of the previous reply. I will start working on this PR.

**Comment by postmeback** [comment]
Any update on this ?
