### ISSUE TITLE
Memory is leaked after an iframe is disposed

### ISSUE THREAD

**Issue by marco-ms** [microsoft/FluidFramework#11841]
## Describe the bug
We are seeing a memory leak in Teams

### To Reproduce
1. Create a draft in teams (for example a bulleted list)
2. Discard it
3. Repeat steps 1+2 N times
4. Open dev tools > Memory > run GC > take a memory snapshot

This is how it looks like, created three components, discarded them, it leaked all three with the same stack.

### Expected behavior
No memory leak.

### Logs
![image (3)](https://user-images.githubusercontent.com/29441719/188932887-34679796-e7d3-49ec-9f5a-057eca0d33d4.png)

**Comment by anthony-murphy** [comment]
@vladsud  is there someone on your team that can look into this? seems like something fishy is going on with the abort controller implementation used here

**Comment by anthony-murphy** [comment]
i briefly looked at it, and i do see the usage of some global weak maps in the library. i don't see an obvious problem, but weak maps are very subtle, so there could be an issue: 
https://github.com/mysticatea/abort-controller/blob/master/src/abort-signal.ts

**Comment by vladsud** [comment]
@marco-ms, can you please educate us on what this graph actually represents? How do you read it?
Are AbortController and AbortSignals the only object that are leaked?
If there are more, how can we get full list?

**Comment by curtisman** [comment]
@marco-ms also, why you think the reference to the AbortController is at fault here?

**Comment by marco-ms** [comment]
I actually didn't say AbortController is at fault here, it could be very well be Teams or FluidFramework, we are still trying to figure it out.

**Comment by anthony-murphy** [comment]
It looks like there was a global element being injected into the console for dev tool detection. This was happening both inside and outside the iframe, and due to the long-lived windows in the application there were object trees not being cleared up.
