### ISSUE TITLE
Issue using certain versions of fluid framework

### ISSUE THREAD

**Issue by tummalasujith** [microsoft/FluidFramework#11926]
npm i @fluidframework/driver-utils@^0.59.4002 does not work. but npm i @fluidframework/driver-utils@0.59.4002-73950. npm and pnpm are unable to resolve versions with -. How do you suggest we handle these?

![image](https://user-images.githubusercontent.com/11410643/189772182-224232e7-e5f6-432e-bb58-ebf690e84704.png)

**Comment by taylorsw04** [comment]
@tylerbutler or @Abe27342, do either of you have suggestions here?

**Comment by Abe27342** [comment]
@tummalasujith  What version of `npm` are you on and how is your `.npmrc` configured? It works for me pointing at npmjs:

![image](https://user-images.githubusercontent.com/5222607/190454499-964ba824-51a4-4e3e-8b1c-9df51e7a26fc.png)

![image](https://user-images.githubusercontent.com/5222607/190454531-f331babd-4a99-412d-9649-5860399b42c2.png)

I'm guessing this is a feed configuration issue. I see you're in the Microsoft org--if you're pointing at an ADO feed that upstreams npmjs, IIRC there's a possibility that you don't have permissions to cause the internal feed to grab packages from its upstreams.

**Comment by tummalasujith** [comment]
My npm is at 6.14.16. Right, we are pointing to OneDrive internal feed. We tried piercing cache and multiple people try it. exact version works, but not with caret. Sound like we need to look into our feed configuration to see if there is a setting to avoid prerelease versions when using caret.

**Comment by curtisman** [comment]
@tummalasujith,  Just to close on this issue: npm semver ^ ranges doesn't consider any prerelease versions unless the version also has a prerelease tag:
e.g. ^0.59.4002-0 will match 0.59.<patch> where patch >=4002 *and* prerelease version with prefix 0.59.4002 *only*
But ^0.59.4002 will only match 0.59.<patch>  where patch >=4002  and no prerelease versions.
