### ISSUE TITLE
Add optional AbortSignal to Map.wait

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#1193]
related to #1192 and #1191

**Comment by vladsud** [comment]
Should we close old items? I.e. if we did not get to it in a year, and are likely not get to it in another year, the value of keeping on backlog is low.

That said, it would be great to articulate a reason for having waits at all.

**Comment by ChumpChief** [comment]
My opinion is same as before, that I'd prefer to remove waits.  I'm in favor of closing this.

**Comment by vladsud** [comment]
Closing this issue.
#5192 tracks more generic usage of AbortSignal across all waiting APIs.
#6188 tracks improving or getting rid of wait() method.
