### ISSUE TITLE
MergeTree: Corruption when clients race to insert at removed position

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#1214]
Given the following sequence:
* Client 1 inserts "a" at position 0
* Client 1 removes 0-1
* Without seeing client 1's changes, client 2 inserts "X" at position 0
* Client 1 receives acks for its insertion/removal, but has not yet seen client 2's insertion
* Client 1 inserts "c" at position 0

Client 1 will arrive at the sequence "Xc" while other clients will converge on "cX".

**Comment by DLehenbauer** [comment]
Capturing @jack-williams investigation:

The current logic for tie breaking 0 length offsets immediately descends into block nodes. At the segment level, tie breaking is done based on when the segment was inserted, to put newer before older.

What happens if there are consecutive blocks filled with local unacked segments (i.e., segments that the remote client didn't know about, and therefore have net 0 length when calculating the insertion position?):
```
    [BLOCK]            [BLOCK]
[local][local]      [local][local]
```
In today's implementation, a remote insert at position 0 will see the first block has zero net length and recurse into that tree, then append at the end of the local segments:
```
       [BLOCK]                 [BLOCK]
[local][local][remote]      [local][local]
```
This is incorrect: all the locally inserted segments are "newer" than the incoming remote segment, and therefore should appear before the incoming segment.
```
   [BLOCK]                 [BLOCK]
[local][local]      [local][local][remote]
```

**Comment by vladsud** [comment]
I'd hope that the issue described here was long fixed.
@anthony-murphy , @DLehenbauer , can you please take a look?

**Comment by anthony-murphy** [comment]
This never got completely fixed. If I remember correctly, we needed #1008 and #1009 for the right fix, as it breaks existing undo redo implementations, but i need to re-examine, as there have been other changes that could help here.
