### ISSUE TITLE
Remove code handling commits in summaries/snapshots

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#1219]
There is some code that has logic for handling commits in summaries/snapshots that should be removed or replaced with error throwing to fail fast.  Check for usage of `ISummaryCommit` or `SummaryType.Commit`, and other commit types in `ITree` or `ISnapshotTree`.  For example: `SummaryTreeConverter.convertToSummaryTree`.

**Comment by vladsud** [comment]
Covered in https://github.com/microsoft/FluidFramework/pull/4682

**Comment by vladsud** [comment]
Mostly resolved with #4682
