### ISSUE TITLE
Many public APIs currently typed to `any` should be constrained to Serializable

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#1239]
Many of our public APIs predate `Serializable`, and instead are incorrectly typed as `any`, 'IMapLike`, `PropertySet`, etc. (which are all overly permissive.)  Usually, this manifests as data loss when the values are transmitted to remote clients or reloaded from a snapshot.

Constraining these types to `<T extends Serializable = Serializable>` would help guard against accidental loss at compile time.  (See runtime/matrix/src/matrix.ts as an example).

**Comment by vladsud** [comment]
I believe this is essentially a dup of #136 and we made a decision to punt it.
Please reactivate if you disagree
