### ISSUE TITLE
Feature: support custom headers in RouterliciousDocumentServiceFactory

### ISSUE THREAD

**Issue by bryanchen-d** [microsoft/FluidFramework#12666]
## Feature
For our scenario (Azure Notebooks), we have our owned host of routerlicious/tinylicious backend, and we need to put it behind a proxy with a layer which will validate certain custom headers. 

**Describe the solution you'd like**
Currently the RouterliciousDocumentServiceFactory doesn't take any custom headers. I am thinking to add a `customHeaderProvider` parameter in the constructor of RouterliciousDocumentServiceFactory, RouterliciousOrdererRestWrapper, and RouterliciousStorageRestWrapper, it will look like this:
```typescript
class ... {
  ...
  constructor ( 
               private readonly tokenProvider: ITokenProvider, 
               private readonly headersProvider?: ()=>Promise<{}>, 
               driverPolicies: Partial<...> = {}
  ){
      ....
  }
}
```

**Existing work**

None

**Describe alternatives you've considered**

An alternative way is to pass in a custom translator of the AxiosRequestConfig which can overwrite the handle of function `axiosRequestConfigToFetchRequestConfig` before sending out the network request, not sure if that would be too flexible?

**Additional context**

**Comment by znewton** [comment]
Adding an extra param where you have it in your example code block would be considered a breaking change to the R11sDocumentServiceFactory public API contract. It would be more ideal to add it as a property to the `driverPolicies` object param, because it does not alter param order and follows the current pattern for adding custom configuration options to the driver.

**Comment by znewton** [comment]
> An alternative way is to pass in a custom translator of the AxiosRequestConfig which can overwrite the handle of function axiosRequestConfigToFetchRequestConfig before sending out the network request, not sure if that would be too flexible?

This seems to be too tied to a current implementation details. I think a `headerProvider` type of callback function is the better path.

**Comment by znewton** [comment]
It is probably also be worth mentioning here that if `enableRestless: true`, then these headers will only exist in the request body, and not in the actual request headers until they are parsed within the service. To make the custom headers parseable within a proxy before the service, you would have to disable restless using `enableRestless: false` in the same `driverPolicies` param object.

**Comment by bryanchen-d** [comment]
> Adding an extra param where you have it in your example code block would be considered a breaking change to the R11sDocumentServiceFactory public API contract. It would be more ideal to add it as a property to the `driverPolicies` object param, because it does not alter param order and follows the current pattern for adding custom configuration options to the driver.

Agree for putting into the `driverPolicies` in `RouterliciousDocumentServiceFactory`, however the `RouterliciousOrdererRestWrapper` and `RouterliciousStorageRestWrapper` don't take the entire policies object, so I think we have to add an extra parameter there, thoughts?

**Comment by bryanchen-d** [comment]
> It is probably also be worth mentioning here that if `enableRestless: true`, then these headers will only exist in the request body, and not in the actual request headers until they are parsed within the service. To make the custom headers parseable within a proxy before the service, you would have to disable restless using `enableRestless: false` in the same `driverPolicies` param object.

I found that there are issues needed to be fixed when we set `enableRestless: false`: 
1. the `body` should be stringified before calling `fetch`. (in restless mode, this is done by the `RestLessClient.translate(..)` function)
2. Need to append a header `'Content-Type':'application/json'`

**Comment by bryanchen-d** [comment]
Also the `getAuthorizationHeader` for RouterliciousRestWrapper only return `Basic` type tokens, while we want to use `Bearer` tokens, I assume the headerProvider pattern can also be used to overwrite the default authorization header in this case?
