### ISSUE TITLE
Automated syntax correction for solidity compiler in vs code

### ISSUE THREAD

**Issue by grapevinegizmos** [microsoft/FluidFramework#12727]
## Feature
**Is your feature request related to a problem? Please describe.**

Because the VSCode solidity dev environment doesn't catch syntax and similar errors while you're coding, its pretty usual for me at least to make a bunch of typos,, missing ,s unbalanced brackets etc.  Hardhat requires a  a "compile" step which is quite tedious, because it only finds a few errors at a time, these need to be corrected, before you will get a new batch of also trivial errors.  

So when you're done with the writing and run "hh compile" to find all the errors, you never get more than a few in a single pass, and you need to correct these and then run hh compile again which finds a new (but not complete) list of obvious errors.

**Describe the solution you'd like**

It would be super great if copilot could do the job that VS Code doesn't do and mark obvious syntax errors, or have some kind of syntax check function that would reveal all the errors and make suggestions for fixes, which you could just accept.  For me at least, 90% of the error corrections are trivial (missing closing brackets, missing keywords, etc.) all things which I think Copilot already recognizes, at least when its suggesting code.  Would save me a lot of time at least until the VSCode dev environment gets as good for solidity as it is for Typescript and simialr languages, where the errors are evident as soon as you type them.

**Existing work**

Errors of this syntax and typeos when writing pretty much any other strongly typed language Java or Typescript are marked in the UI with red squiggly's.  But for some reason, not in solidity.  I suspect has something to do with the the solidity compiler and the way integrated into VS Code.

**Describe alternatives you've considered**

The alternative is just running 'hh compile' about 15 times until you've got all the errors identified.

**Additional context**

**Comment by tylerbutler** [comment]
@grapevinegizmos This issue does not seem related to the Fluid Framework. Can you clarify how Fluid is involved?

**Comment by grapevinegizmos** [comment]
Apologies Tyler I thought I was posting in the Github Copilot suggestion box.
