### ISSUE TITLE
In createOdspCreateContainerRequest support the option of setting the LoaderHeader.cache header

### ISSUE THREAD

**Issue by tiffany-ou** [microsoft/FluidFramework#12891]
## Feature

For our scenario (Loop), we want to specify that we want to override the container loader's default caching behaviour to not use any caching in the request returned by `createOdspCreateContainerRequest`. The problem with using the default caching behaviour in our scenario is that after attaching the container with the request returned, the ODSP file gets created with a cached file name instead of the `fileName` parameter provided to the `createOdspCreateContainerRequest` function.

The current workaround for this has been to modify the request returned by createOdspCreateContainerRequest by adding `[LoaderHeader.cache]: false` to its headers after, but it would be cleaner if this could be set in the function itself.

**Describe the solution you'd like**
Allow specifying a value for LoaderHeader.cache header through a parameter, e.g.:

```
export function createOdspCreateContainerRequest(
    siteUrl: string,
    driveId: string,
    filePath: string,
    fileName: string,
    createShareLinkType?: ShareLinkTypes | ISharingLinkKind,
    useLoaderCache?: boolean) {
       ... 
      headers: {
         ...
         // set LoaderHeader.cache to useLoaderCache if it exists
         ...
      }
      ...
}
```

**Comment by vladsud** [comment]
@tiffany-ou, our current plan is not to provide this kind of capability.
But instead, to remove caching altogether from Loader.
https://github.com/microsoft/FluidFramework/pull/14680 is the very first step on this jorney
https://dev.azure.com/fluidframework/internal/_workitems/edit/3118 tracks this work.

Please reach out if you think this item should stay around.
