### ISSUE TITLE
resolveWithLocationRedirectionHandling removes dataStorePath or deep link informaiton on redirection

### ISSUE THREAD

**Issue by rshreenath** [microsoft/FluidFramework#12956]
## Work Item
**Describe the outcome you expect**
resolveWithLocationRedirectionHandling was added to handle location redirection errors. In the case where file location has been changed, the error information has the new file location, the utility function reloads the file from the new location. The issue is that the original URL may have additional meta data like deep linking information etc which are stripped when the file is reloaded from the new location.

**Approach**

**Open questions**

**Additional context**

**Acceptance criteria**

**Comment by bmeersma** [comment]
@jatgarg Hi Jatin, can you please provide an update about the status of this item when you get a chance? Thanks.

**Comment by jatgarg** [comment]
Opened a corresponding item in ADO

**Comment by jatgarg** [comment]
https://dev.azure.com/fluidframework/internal/_workitems/edit/2601
