### ISSUE TITLE
Service: Contract with database driver is unclear/fragile for service implementors

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#13051]
The reference Fluid service uses a database for storing the op log and metadata.  The actual database implementation is abstracted by a driver, with the Fluid Framework repo containing 4 different implementations (Routerlicious, In-Memory, LevelDB and LocalSession.)

Each database implementation is responsible for parsing and executing a JSON-based query language.  Currently these queries are typed as "any", which makes the contract unclear and fragile for engineers implementing a database driver.

The ideal fix is to strongly type the objects used to represent the query DSL so that future language changes will result in compilation errors.

The contract for the database driver is found here:
/server/routerlicious/packages/services-core/src/database.ts

```ts
export interface ICollection<T> {
    find(query: any, sort: any, limit?: number, skip?: number): Promise<T[]>;
    findOne(query: any): Promise<T>;
    findOrCreate(query: any, value: T): Promise<{ value: T; existing: boolean; }>;
    update(filter: any, set: any, addToSet: any): Promise<void>;
    updateMany(filter: any, set: any, addToSet: any): Promise<void>;
    upsert(filter: any, set: any, addToSet: any): Promise<void>;
    deleteOne(filter: any): Promise<any>;
    deleteMany(filter: any): Promise<any>;
    distinct(key: any, query: any): Promise<any>;
}
```

**Comment by ruiterr** [comment]
It seems there are already TypeScript types for the mongo interface: https://github.com/mongodb/node-mongodb-native/blob/main/src/mongo_types.ts

However, we should strip out everything we are currently no using, since the other database implementations would have to implement everything specified in the driver types.

**Comment by DLehenbauer** [comment]
(@ruiterr - Good find.  Thx!)
