### ISSUE TITLE
Documentation for rendering patterns

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#1316]
There are numerous ways to render in the Fluid world. We should document them.

- [x] Document view-adapters
- [x] Document view-interfaces
- [ ] Document samples added as part of #1289
- [ ] Consider rendering overview document.

**Comment by vladsud** [comment]
@ChumpChief, any plan to address it in near future? If not, we should close

**Comment by ChumpChief** [comment]
I think these are sufficiently documented at this point (there are more samples now).
