### ISSUE TITLE
Type safety for JSON serializable things

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#136]
From Tyler's Soduku feedback:

> Mistake #1: Trying to store objects in a DDS that are not safely JSON round-trippable

This is approximately the solution:

```ts
export type JsonPrimitive = undefined | boolean | number | string;
export type JsonObject = { [index: string]: JsonPrimitive | JsonArray | JsonObject };
export type JsonArray = (JsonPrimitive | JsonObject)[];
export type Json = JsonPrimitive | JsonArray | JsonObject;
```

As I've mentioned before (#3145), we should also call Object.freeze(..) on these objects.

**Comment by tylerbutler** [comment]
We have had a lot of discussion about this over the past year, and some things were implemented, like AsJsonable. However, the general consensus has been that this requires too much "fancy type handling" and ultimately is more confusing than helpful.

The current plan is to close this, and _possibly_ remove the things we put in place already with follow up issues.
