### ISSUE TITLE
General Build Problems

### ISSUE THREAD

**Issue by dstanesc** [microsoft/FluidFramework#13972]
## Describe the bug
1. The Fluid general build fails with errors
2. The experimental/property-inspector webpack fails with errors

### Linux System

```sh
$ uname -a
Linux hermes 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### To reproduce the general build error
```sh
git clone git@github.com:dstanesc/FluidFramework.git
git switch property-parity # fresh branch based on c5ebd543e649f029ca7e49134b60e0fa6b09599c
nvm use
npm i -g pnpm
pnpm install
npm run build:fast
``` 

### Error
Failed Tasks:
[159/798] x @fluidframework/container-runtime: tsc --project ./src/test/tsconfig.json - 18.213s
[551/798] x @fluid-experimental/partial-checkout: webpack --color --no-stats - 37.530s
[554/798] x @fluid-experimental/property-inspector: webpack --color --no-stats - 43.272s
Did not run 118 tasks due to prior failures.
See attached, full log included

### To reproduce property-inspector error
```
cd experimental/PropertyDDS/examples/property-inspector
npm start
```
### Error
See attached, full log included

### Expected behavior
No error

### Logs
[build.log](https://github.com/microsoft/FluidFramework/files/10574281/build.log)
[property-inspector.log](https://github.com/microsoft/FluidFramework/files/10574286/property-inspector.log)

### Notification
@ruiterr @sharptrip @nedalhy @milanro

**Comment by nedalhy** [comment]
Thanks for reporting the issue @dstanesc. 
Which Node version are you using ?

**Comment by dstanesc** [comment]
@nedalhy 

Thank you for looking into. Using the recommended version by the framework which is specified in the `.nvmrc` file:
```sh
nvm use
Found '.nvmrc' with version <14>
Now using node v14.19.0 (npm v6.14.16)
```

**Comment by dstanesc** [comment]
I was able to compile successfully the branch. I am using `nvm` to manage `node` and `npm` versions and an interesting side-effect seemed to be  a strange cross-pollination between `v18.12.1` and `v14.21.2` pnpm repos. Definitely smth. to keep an eye on, however not related to the FluidFramework build.
Closing the ticket w/ this finding.
