### ISSUE TITLE
Directory SubDirectories should extend ISharedDirectory and not IDirectory

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#1403]
We want SubDirectories in the SharedDirectory dds to be directly eventable. 

Work items: 
- Move generic and "valueChanged" event emitter from ISharedDirectory to IDirectory. 
- SubDirectory should extend event emitter and when making the emit(...) action should emit on both the root and on itself.

**Comment by ChumpChief** [comment]
I think this was satisfied by #4556
