### ISSUE TITLE
Handle promise rejection in connectToDeltaStream()

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#1406]
## Describe the bug

In container.ts, we connect to delta stream without awaiting on promise, 
        const startConnectionP = this.connectToDeltaStream();
        startConnectionP.catch((error) => {
            debug(`Error in connecting to delta stream from unpaused case ${error}`);
        });
This debug statement wont get executed because the function wrapping this may return and then this would be rejected floating promise.

### Expected behavior

Find a way to log this.

**Comment by vladsud** [comment]
This code changes million times over last year, and I believe we no longer have issues here.
