### ISSUE TITLE
Request to resolve url is cached even if request is different (has different headers)

### ISSUE THREAD

**Issue by montselozanod** [microsoft/FluidFramework#14198]
## Describe the bug
At this moment, in the function createCachedResolver inside Loader.ts, there is code to cache requests to resolve url. When we try to request resolving a url in two separate requests with different headers, the headers of the second one are ignored since the url is already cached. Shouldn't the cache check that both requests are the same and have the same headers?

### To Reproduce
1. Make a request to resolve a url from ODSP
2. Make another request to resolve a url from ODSP which includes a header param such as isSharingLinkRedeem

### Expected behavior
The sl param is included in the resolved url returned

### Actual
SL param is not included in the resolved url since the request was already cached.

**Comment by jatgarg** [comment]
Opened here: https://dev.azure.com/fluidframework/internal/_workitems/edit/3495
