### ISSUE TITLE
Container IFrame Project Summary

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#1419]
This issue contains a summary of the goals for the Container IFrame Project which contains the work item break down:
https://github.com/microsoft/FluidFramework/projects/19

Have a loader on the outside which wraps the driver in a proxy, and have a loader on the inside of the iframe which is a proxy to the outer loaders driver proxy. 

![image](https://user-images.githubusercontent.com/1951092/75195656-34316600-570f-11ea-8b77-375beab61098.png)

 - Simpler Container Proxy  – There are scenarios where the host needs access to things like quorum, audience, other container properties. By having the real driver outside the iframe, we can instantiate a trusted container that has a real quorum, audience, etc. rather than proxying them across the iframe boundary.

 - Resource utilization – This will be pay to play. If a host doesn’t care about the container proxy it won’t need to get it, and will only pay for the driver and the driver proxy in the frame, which I think we can keep pretty light, but we should do profiling to make sure that is the case.

 - Compatibility – The host will likely only have one version of the loader code, which will need to be compatible with the inner version of the loader code. We have strong compatibility guarantees around the loader, as a loader can’t load a container that it’s not compatible with regardless whether there is an iframe or not.

 - Safety – All the code running in the host will be trusted as it’s runtime code, or code like office web host. Just like the non-iframe case we need to make sure this code behaves well and doesn’t compromise the host.

 - Security – By default this proposal will keep tokens out of the iframe. We will need a mechanism for the host to proxy additional things into the iframe, probably via scope. My opinion is that we shouldn’t pass tokens into the iframe, but proxy api’s for doing privileged things back to the host. However, there will be no technical reason tokens couldn’t be passed in. The origin of the iframe will also be controlled by the host, or office web host. The runtime will be design to work with the strictest mode possible, but less strict modes will also be supported.

 - Untrusted Driver – I think this is a bit of scope for this , as you can’t have a loader without a driver, so any kind of dynamic driver and credential obtaining will need to be handled before the runtime

**Comment by vladsud** [comment]
@anthony-murphy, is there a value in keeping this item active? I'll mark won't fix for bot to close unless there is some activity.
