### ISSUE TITLE
SharedTree DataBinder 

### ISSUE THREAD

**Issue by dstanesc** [microsoft/FluidFramework#14293]
## Feature
Provide a [SharedTree](https://github.com/microsoft/FluidFramework/tree/main/packages/dds/tree) API to register listeners for change notifications associated with selected [EditableTree](https://github.com/microsoft/FluidFramework/tree/main/packages/dds/tree/src/feature-libraries/editable-tree) paths and selected categories of events such `insert`,`modify`, `delete` and `move`.

Highlighting also the importance of notifications to match the dispatch granularity of the expected logical operations, ie. single value modification to yield one and only-one `modify` event, independent of the number and the kind of technical operations performed to achieve this particular modification.

## Motivation
 Justifying current request, similar functionality is already provided by the DataBinder feature of the [SharedPropertyTree](https://github.com/microsoft/FluidFramework/tree/main/experimental/PropertyDDS) distributed data structure. Feature [documentation](https://github.com/karlbom/FluidFramework/blob/ce0036d92dab78eeb485005b7db5c9790534e564/docs/content/start/property-binder/property-binder-callbacks.md). Feature [implementation](https://github.com/microsoft/FluidFramework/blob/main/experimental/PropertyDDS/packages/property-binder/src/data_binder/dataBinder.ts).

## Example API (mirrors current PropertyDDS API)
```ts
 tree.registerOnPath(['path1', 'path2'], ['insert', 'modify'], callback, {isDeferred: true});
```

## Related
A crude and inefficient [prototype](https://github.com/dstanesc/FluidFramework/tree/binding-property-parity-playground/examples/data-objects/hello-shared-tree) analyzing the possibility of a data binder API using existing  [SharedTree](https://github.com/microsoft/FluidFramework/tree/main/packages/dds/tree) capabilities. Deserves noted the unexpected [EditableTreeContext](https://github.com/microsoft/FluidFramework/blob/main/packages/dds/tree/src/feature-libraries/editable-tree/editableTreeContext.ts) notification behavior. For instance in case of a single modification (eg.  to a sequence field `tree.field1[index1] = {[valueSymbol]:value1}`) 6 `deltas`, reflecting 3 distinct `insert` and `delete` notifications are dispatched.
> Note: Listening to index events instead, such opening access to `indexEventEmitter.on("newLocalState", (delta: Delta.Root) => {})` brings as expected the notification cardinality down to 1 `delta` (incl. 1 `insert` and 1 `delete`).

**Comment by DLehenbauer** [comment]
For June, I think we converged @CraigMacomber's proposal to expose an event from the proxy that allows users to register for deltas to the subtree of that specific node.  (This is different than the path registration shown above.)

Questions:
- Are we agreed that this is sufficient for June?
- Do we have an API proposal yet?  I'm particularly interested in:
  - Are we starting to leak the fact that updates are non-atomic and do not preserve temporal order?
  - What is the strategy for users needing to identify/read from deleted nodes to synchronize their local model?

**Comment by DLehenbauer** [comment]
TODO: @nmsimons suggests looking at SharedDirectory eventing as a comparison point.

**Comment by DLehenbauer** [comment]
Capturing notes from our previous sync:
* We're still aligned on the POR that we will support event subscriptions to subtrees rooted at specific nodes.
* This will have some semantic differences for customers currently using path-based registration:
    * Moving the node associated with the change subscriptions will change the path being observed.
    * Deleting the node associated with the change subscriptions will remove the subscription.  Inserting a new node/subtree at the previously observed path will not restore the subscription.
* Post-June, we may introduce the ability to filter a subscription to a path within a subtree.

Other:
* Property DDS supported arbitrary grouping of event notifications that is independent of transaction boundaries.

**Comment by dstanesc** [comment]
To my current understanding, the semantic differences have good chances to be bridged by a careful design of the emerging API. For instance:
- Providing low level symmetric APIs, ie. `register` _and_ `unregister` could allow observers to `unregister` existing callbacks when `move` operations are occurring. 
- The `register` API could return a handle to facilitate `unregister`ing of a particular callback
- Additional arguments to the callback function could be already important enablers to more refined or custom policies. For instance:
  - A `node` argument (considering that the tree-node holds both APIs - `register` and `unregister`) may simplify dynamic unregistering of the callbacks
  - A `path` argument may support higher level components to filter events selectively (eg. skip or include paths withing the subtree)
- The ability to register multiple callbacks per Anchor would allow behavior partitioning, eg. higher level components to isolate callbacks for registration/unregistration (ie. meta-data) vs. actual data mgmt. callbacks

Any thoughts? @DLehenbauer @CraigMacomber @ruiterr @nedalhy @sharptrip  @milanro

**Comment by dstanesc** [comment]
Another topic for team agreement could be whether `AnchorEvents` would not benefit from adding change-category specific callbacks, ie. aligned w/ the atomic changes (such `Insert`, `Delete`, `SetValue`).

Currently:
```ts
export interface AnchorEvents {
  // ...
  childrenChanging(anchor: AnchorNode): void;
}
```
Possible interface evolution, reflecting existing Delta visitor signature, would permit fine-granular subscriptions together w/ propagation of specific details.
```ts
export interface AnchorEvents {
  // ...
  childrenChanging(anchor: AnchorNode): void; // preserve the coarse granular callback
  childrenDelete(anchor: AnchorNode, start: number, count: number): void; // add
  childrenInsert(anchor: AnchorNode, start: number, content: Delta.ProtoNode[]): void; // add
  childrenSetValue(anchor: AnchorNode, value: Value): void; // add
  childrenMoveOut(anchor: AnchorNode, start: number, count: number, id: Delta.MoveId): void; // add
  childrenMoveIn(anchor: AnchorNode, start: number, count: number, id: Delta.MoveId): void; // add
}
```
The binder API could reflect that further.

**Comment by DLehenbauer** [comment]
@dstanesc - I've been wondering if there is a reasonable pattern where we could register an IDeltaVistor with an anchor to receive callbacks for just the subtree.

Then once we have the full generality of an IDeltaVistor subscription, build simpler patterns on top of it:

```ts
let isInvalid = false;

const invalidate = () => {
    if (!isInvalid) {
        isInvalid = true;
        requestAnimationFrame(() => {
            // (Handle invalidation of subtree here)
            isInvalid = false;
        });
    }
}

const visitor = {
        // A simple observer marks the subtree as invalid for any change in the subtree.
    	onDelete(..) { invalidate(); }
	onInsert(..) { invalidate(); }
	onMoveOut(..) { invalidate(); }
	onMoveIn(..) { invalidate(); }
	onSetValue(..) { invalidate(); }
	
	// TODO: separate onDeleting() / onDeleted() callbacks?
		
	// One the subtree is marked as invalid, return 'false' to squelch further callbacks:
	enterNode(index: number)  { /* continue: */ return isInvalid; }
	exitNode(index: number)  { /* continue: */ return isInvalid; }
	enterField(key: FieldKey)  { /* continue: */ return isInvalid; }
	exitField(key: FieldKey)  { /* continue: */ return isInvalid; }
};

// When the change event is raised, we return a visitor we want to add to the stack of IDeltaVistors
// to invoke for the traversal of the subtree.
anchor.on("change", () => visitor);
```

As a shortcut for simple cases, we could also allow this:

```ts
// Invoked once as delta manager enters the subtree.
anchor.on("change", () => { invalidate();  /* returns void */ });
```

...just some ideas.  Perhaps we can walk through this thread on Wednesday?

**Comment by dstanesc** [comment]
@DLehenbauer  - This is an interesting point. I also entertained the idea of just registering an DeltaVistor during the [very first](https://github.com/microsoft/FluidFramework/blob/ae61c2125e89267856f4eaaacdd8508fd075759e/examples/data-objects/hello-shared-tree/src/App.tsx#L234) prototype (before current AnchorSet evolution which wraps around an internal visitor and seem to invite delegation). From the usability standpoint combining multiple callbacks in a visitor ( evtl. skipping not interesting callbacks, hence finer granular API still possible) may be reasonable imho. @CraigMacomber @sharptrip @ruiterr

**Comment by ruiterr** [comment]
@dstanesc how would the proposed system behave, if I create a resolver and the set of nodes returned by the resolver changes (e.g. insertion into an array, modification of a subtree, move). Would the registration be updated automatically to follow the new resolution? If not, why do we need the additional indirection with a resolver? Couldn't we just put the array of nodes into the binding function and leave it to the user how to find the nodes?

**Comment by milanro** [comment]
> @dstanesc how would the proposed system behave, if I create a resolver and the set of nodes returned by the resolver changes (e.g. insertion into an array, modification of a subtree, move). Would the registration be updated automatically to follow the new resolution? If not, why do we need the additional indirection with a resolver? Couldn't we just put the array of nodes into the binding function and leave it to the user how to find the nodes?

If I understood well, the resolver is supposed to calculate the relevant nodes on the fly by the custom code considering the initial conditions (such as path for example). That way we could capture the changes automatically, it would depend on the code cleverness. @dstanesc please comment whether I see it correctly.

**Comment by dstanesc** [comment]
@ruiterr  @milanro  - Indeed the goal is reaching behavior a pseudo-parity w/ existing PDDS binder. 

The resolver is a generalization for various node resolution techniques (for instance introducing support for path based language). The belief I shared somewhere above in the thread was that the binder could react to changes and modify registrations accordingly. 

This part is not yet impl. but theoretically one way would be to react on `afterBatch` events and interpret the delta. Beyond 'cleverness' (or complexity), what concerns me most is the inherent overhead. 

Reconsidering also former conceptual approach shared [earlier](https://github.com/microsoft/FluidFramework/blob/ae61c2125e89267856f4eaaacdd8508fd075759e/examples/data-objects/hello-shared-tree/src/App.tsx#L171), before AnchorSet eventing was avail. This approach appears more efficient for static path registration (which is desired as feature) by filtering current events based on the `UpPath` or its equivalent (once provided as argument to the callback).
