### ISSUE TITLE
Packages are distributing typescript source files unneccessarily.

### ISSUE THREAD

**Issue by dzearing** [microsoft/FluidFramework#14338]
## Describe the bug

Every `package.json` in the repo should have a `files` key, which is an allow list of files to be included in the npm packages. Please add these and republish. Right now, source files are being distributed unnecessarily with at least some packages.

Example, see `src` here:

https://unpkg.com/browse/@fluidframework/server-lambdas@0.1038.3000/

Because `files` lists are missing, AND `.npmignore` files seem to be missing or are incomplete, typescript code is included with the npm published artifact. This can cause build issues downstream. (For example, if TypeScript ends up using the src rather than typings, build can fail on settings that work in the repo but not on the external typescript source.)

Please fix.

**Comment by christiango** [comment]
I believe this is done intentionally so that things like sourcemap loader can ensure that Fluid Framework packages can be resolved back to the TS files by the browser devtools and livesite tools.

**Comment by christiango** [comment]
Let's make sure this doesn't regress the ability for tools like source-map loader to include Fluid Framework source ts

**Comment by tylerbutler** [comment]
Just to be clear, this is an intentional behavior in Fluid packages today, not a bug.

**Comment by tylerbutler** [comment]
> For example, if TypeScript ends up using the src rather than typings, build can fail on settings that work in the repo but not on the external typescript source.

@dzearing Do you know the circumstances under which this happens?
