### ISSUE TITLE
ContainerServices.generateContainerServicesRequestHandler does not return the container service if it doesn't implement IComponentRouter

### ISSUE THREAD

**Issue by ZeguangWu** [microsoft/FluidFramework#1439]
## Describe the bug
If a container service doesn't implement IComponentRouter, it doesn't returned by the generateContainerServicesRequestHandler function.

After a bit investigation the issue seems to be in the RequestParser.createSubRequest() function, the condition `startingPathIndex > this.pathParts.length` is not correct.

But I'll leave it to your guys to fix it since I'm not super familiar about the impact.

```
   /**
     * Creates a sub request starting at a specific path part of this request's url
     *
     * @param startingPathIndex - The index of the first path part of the sub request
     */
    public createSubRequest(startingPathIndex: number): IRequest | undefined {
        if (startingPathIndex < 0 || startingPathIndex > this.pathParts.length) {
            return undefined;
        }
        const path = this.pathParts.slice(startingPathIndex).join("/");
        return {
            url: path + this.query,
            headers: this.headers,
        };
    }
```

**Comment by skylerjokiel** [comment]
Closing this bug because the larger plan is to remove the Aqueduct Container Services code in October. It has been deprecated and replaced by the Providers pattern.

#3799
