### ISSUE TITLE
SparseMatrix/TableDocument should have consistent method names

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#1446]
We are inconsistent with our names of methods. For example, we user "annotate" instead of "set" in some cases, but the corresponding getter uses "properties". I.e.

`annotateRows` / `getRowProperties`, `annotateCols` / `getColProperties`

We should be consistent and use either "properties" or "annotations" consistently.

More context here: https://github.com/microsoft/FluidFramework/pull/1441#pullrequestreview-370060768

**Comment by vladsud** [comment]
I'd want to punt this given that we are not investing into matrix 1.0 (which is deprecated).
@anthony-murphy - if we are planning to make changes here, can you please put a bit better description such that it can truly be called "good first issue" that I'm about to mark it?
