### ISSUE TITLE
Pattern docs: Op grouping

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#1447]
Need to call out it's not atomic.

> Grouping became a runtime-wide feature. You use it like this:
>
> ```ts
> this.context.hostRuntime.orderSequentially(() => {
>    // anything you do in here is grouped
>});
>```
> ...but remember that grouping isn't atomic, it just guarantees that ops from other clients won't be  interleaved.

From <https://github.com/microsoft/FluidFramework/issues/1251#issuecomment-589290584>

***

> You can use group ops (aka batches) for that. But
> * (I believe) they can't survive JS turn (i.e. no asynchrony - you need to generate all changes synchronously)
> * Events fire for each op separately.

***

**Comment by vladsud** [comment]
@tylerbutler - feels like we should either make small doc change or close this old issue.
