### ISSUE TITLE
Removing all columns from matrix DDS - column remove events mismatched with DDS data state

### ISSUE THREAD

**Issue by SeanSnyders** [microsoft/FluidFramework#14476]
## Describe the bug

We use fluid internally in an SDK and do not expose it to our clients.

Performing this call on the matrix DDS:
```
matrix.removeCols(0, matrix.colCount);
```
will result in arbitrary number of "column removal" events from the framework with no indication of when the events are done firing.
This makes it difficult to track and to communicate a "data structure empty" event when using fluid internally and it not exposed to clients.
Also, when querying the matrix DDS on "column removed" events, it seems that the DDS is already empty and contains no data, and thus the event information and the state of the DDS is then mismatched. This adds to the complexity in knowing when the last "column removed" event has been sent and to reliably send out a "data structure empty" event. It also provides no way of acting on the events when state of the DDS is to be used in business logic due to the mismatch.

### Expected behavior

Either:
1. match DDS state with "column removed" event, but this would not be async, or
2. for our specific use-case we need to clear the whole matrix DDS, thus a `matrix.clear()` would work and then a single event that signifies the all the columns that were removed.

ADO Item: [AB#4197](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/4197)

**Comment by DLehenbauer** [comment]
Behind the scenes, SharedMatrix uses MergeTree to track the mapping between logical row/cols and their current locations in storage.  Modifying the rows/cols manipulates the segments in the MergeTree, which generates MergeTree 'delta' events.  The SharedMatrix maps these events to the current logical rows/cols when raising the SharedMatrix callbacks.

What the customer is observing is that removing a consecutive range of items in the MergeTree can generate effect multiple MergeTree segments, each of which is generating a separate notification as we map removed segments to their logical row/col positions.  (See 'permutationVector.ts:onDelta()')

The segment ranges are already sorted by descending position to help avoid the need to deal with shifting indices when reacting to notifications.  Consider also coalescing adjacent segments prior to invoking callbacks.

**Comment by SeanSnyders** [comment]
Any further positioning on this issue? Will there be a fix for this forthcoming?
