### ISSUE TITLE
FluidHelloWorld project is broken. It runs into R11s fetch and 400 bad request errors with tinylicious.

### ISSUE THREAD

**Issue by applegrew** [microsoft/FluidFramework#14811]
## Describe the bug
The FluidHelloWorld demo project does not work.

### To Reproduce
1. Go to [official doc](https://fluidframework.com/docs/start/quick-start/) and follow all the steps.
2. When `npm start` is run, it will ask to install latest `tinylicious`. Respond with `y`.
3. Both webpack serve and tinylicious start.
4. Open url http://localhost:8080 but it shows a blank page.

### Expected behavior
We should be seeing a dice graphics as shown on the official doc.

### Logs
In browser console the following errors are noticed.

    POST http://localhost:7070/documents/tinylicious 400 (Bad Request)

<img width="634" alt="Screenshot 2023-03-28 at 9 35 59 PM" src="https://user-images.githubusercontent.com/434574/228301376-cf7579e2-e83d-4c4f-b7d0-489431ef8d3b.png">

I am using node 16 in OSX. I also tried upgrading `@fluidframework/tinylicious-client` and `fluid-framework` to current latest but that did not help.

**Comment by NicholasCouri** [comment]
> Thanks for the report. FYI--@NicholasCouri is investigating another tinylicious 400 issue that is likely the same cause.

Sorry @Abe27342, I only saw this thread now!  Yes, I checked in the fix that should be in for tinylicious 0.7.2 - please let me know if this is not the case.

**Comment by NicholasCouri** [comment]
> This impacted me as well. If it helps, it seems to have been introduced in 1.3.6.
> 
> As a fix for development purposes, these work for me: @fluidframework/test-client-utils@1.3.5 @fluidframework/tinylicious-client@1.3.5

@jonverrier I will follow-up to get the version tinylicious-client@1.3.7 released (containing the tinylicious fix)

**Comment by jonverrier** [comment]
Yep, all works now.

**Comment by ryanbliss** [comment]
This appears to have popped up again for someone in our org. It was working for him last night. Here were his logs:
![image](https://user-images.githubusercontent.com/11748606/235266988-068708ae-93bc-4744-b38e-841cda7f5433.png)
Note it works for me on my Windows computer. Any help appreciated.

In `package.json`, we have the following...
```
    "dependencies": {
        "@fluentui/react-components": "^9.18.6",
        "@fluentui/react-icons": "^2.0.194",
        "@fluentui/react-theme": "^9.1.5",
        "@fluidframework/azure-client": "~1.0.3",
        "@microsoft/live-share": "1.0.0-preview.10",
        "@microsoft/live-share-canvas": "1.0.0-preview.10",
        "@microsoft/live-share-media": "1.0.0-preview.10",
        "@microsoft/teams-js": "^2.11.0-beta.0",
        "@testing-library/jest-dom": "^5.16.5",
        "@testing-library/react": "^13.4.0",
        "@testing-library/user-event": "^14.4.3",
        "fluid-framework": "^1.3.6",
        "lodash": "^4.17.21",
        "prop-types": "^15.8.1",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-router": "^6.4.2",
        "react-router-dom": "^6.4.2",
        "use-resize-observer": "^9.1.0",
        "uuid": "^9.0.0",
        "web-vitals": "^3.1.1"
    },
    "devDependencies": {
        "@fluidframework/test-client-utils": "^1.3.6",
        "@types/lodash": "^4.14.191",
        "@types/react": "^18.0.0",
        "@types/react-dom": "^18.0.0",
        "@typescript-eslint/eslint-plugin": "^5.48.1",
        "@typescript-eslint/parser": "^5.48.1",
        "@vitejs/plugin-react": "^3.0.1",
        "dotenv-cli": "^6.0.0",
        "eslint": "^8.31.0",
        "eslint-config-prettier": "^8.5.0",
        "eslint-plugin-prettier": "^4.2.1",
        "eslint-plugin-react": "^7.31.11",
        "eslint-plugin-react-hooks": "^4.6.0",
        "start-server-and-test": "^1.15.2",
        "vite": "^4.0.4"
    },
    "scripts": {
        "build": "tsc && vite build",
        "start:client": "vite",
        "start:server": "npx @fluidframework/azure-local-service@latest",
        "start": "start-server-and-test start:server 7070 start:client"
    },
```

We have also tried `npx @fluidframework/tinylicious-client@0.7.2`  and `npx @fluidframework/azure-local-service@1.3.5`. Any help is appreciated...
