### ISSUE TITLE
Still hitting assert 0x331 "Unexpected pending message received" in SharedDirectory

### ISSUE THREAD

**Issue by zagriswo** [microsoft/FluidFramework#15005]
It looks like the fix for #14394 was incomplete. If you have you have multiple layers of depth in the subdirectories when deleting and re-creating them, you'll still hit assert 0x331. For example, in the repro I had in #14394, I was creating a subdirectory called "foo" right off the root. If you tweak that repro to instead create a subdirectory "bar" off the root, create "foo" as a child of "bar", and also delete & re-create "bar" when deleting & re-creating "foo", 0x331 will be triggered.

I haven't debugged much to see why this is the case - my hunch is it's because the various `isSubDirectoryDeletePending` checks don't work if an ancestor was also deleted & re-created.

**Comment by curtisman** [comment]
@jatgarg can you take a look please?

**Comment by jatgarg** [comment]
Taking a look

**Comment by jatgarg** [comment]
Pr for this issue: https://github.com/microsoft/FluidFramework/pull/15018

**Comment by jatgarg** [comment]
Merged the PR. Patch release is in progress.
