### ISSUE TITLE
Improvement: Make local server generate client leave messages more similarly to real services

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#15163]
Can be demonstrated in any of the examples - load in local mode, hit refresh a couple times, and inspect the quorum members.  There will be lots of zombie clients because no leave messages were generated (you can also check the deltas in the sessionStorage to verify this).

**Comment by anthony-murphy** [comment]
i believe the deli timeout for client is 5 min, do they disappear after that.

**Comment by ChumpChief** [comment]
Looks like they do leave after 5 minutes, which is good to know.  Still seems like we should be able to do something to better approximate what customers will observe in normal operation with the real services, esp. trying to avoid things like:
* Demos using audience/presence showing zombies for 5 minutes after a refresh
* No summaries generated for 5 minutes after the most recent refresh

Basically - though zombie clients can exist in real scenarios, they're not the norm and they disrupt/hinder several features we'd want to demo or test.

Maybe some `onbeforeunload` handler in the `LocalDocumentDeltaConnection` that calls `deltaConnection.disconnect()`?  Or if that feels too much like a "clean" disconnect we could have it reach straight to the `LocalWebSocketServer` to unsubscribe the pubsub?

**Comment by anthony-murphy** [comment]
no doubt that it can be improved, just wanted to call out the current behavior is expected.

**Comment by ChumpChief** [comment]
Updated title to better reflect that this is an improvement.
