### ISSUE TITLE
Issues with the client-debugger documentation.

### ISSUE THREAD

**Issue by nchrisr** [microsoft/FluidFramework#15213]
- The documentation says to use `npm i @fluid-tools/client-debugger` to install the client-debugger, but running this command just gives a 404 error. One has to download the whole repo, and build locally in order to use this. 

- The documentation also says to use: `initializeFluidClientDebugger({...});` to start the debugger, however after building and installing the client debugger locally, I notice that there is no such function. Not sure what the correct way to use this tool is but this seems to be inaccurate.

### Issue Category

- Incorrect/Outdated information
  - [**client-debugger installation**](https://github.com/microsoft/FluidFramework/tree/main/packages/tools/client-debugger/client-debugger#installation)
  - [**Client-debugger initialization**](https://github.com/microsoft/FluidFramework/tree/main/packages/tools/client-debugger/client-debugger#initialization)

ADO Item: [AB#4198](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/4198)

**Comment by Josmithr** [comment]
Note that these libraries are in early incubation stages - they are not yet ready for public consumption. They are strictly repository-private (for now) so installing them will not work outside of the repo context. The documentation has also become stale as we have continued our prototyping work, but we will certainly update it before it becomes externally available.

**Comment by Josmithr** [comment]
I would recommend not using these yet, as the shape of the APIs is changing pretty rapidly.

In the short term, I'll add some extra documentation to indicate the prototype nature of these libraries, until we're actually ready for developers to use them.

Sorry for the confusion.
