### ISSUE TITLE
Move mocha tests in components package from <component_name>/test to <component_name>/src/test

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#1541]
Currently, most of the tests in components package is under <component_name>/test. They should be moved to <component_name>/src/test.
This is so that we can run these tests in vscode. As per the entry for "Debug Current Test" in .vscode/launch.json, it looks for tsconfig.json in <current_dir>../../tsconfig.json. So, it ends up looking for the tsconfig.json in packages/components.

**Comment by vladsud** [comment]
I believe such move was done.
