### ISSUE TITLE
Remove lodash dependency from @fluidframework/datastore

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#15415]
We've seen that lodash/cloneDeep can contribute several KB to bundle size (~5-6KB in #15362), so removing this dependency could potentially yield some savings.

It looks like currently this clone is a bit excessive - algorithm seems to clone and then walk that clone to prune it to the desired result.  Instead, seems we could walk the original and build up our own clone excluding the items that should be pruned (and not modify the original in the process).

**Comment by martinyis** [comment]
Hey, could I work on this issue if possible? Thank you!

**Comment by ChumpChief** [comment]
@jatgarg should probably comment on feasibility and whether I'm missing any requirements that would change the recommendation here first.

I also note that the comment [here](https://github.com/microsoft/FluidFramework/blob/main/packages/runtime/datastore/src/localChannelContext.ts#L193) seems to think we can remove this back-compat at this point - if true, that would be a preferable and more trivial fix.

Also please make sure to check out the [contributing guidelines](https://github.com/microsoft/FluidFramework/blob/main/CONTRIBUTING.md) if you haven't already.  Thanks!
