### ISSUE TITLE
Reconcile IProvideComponentHandle and IComponentLoadable

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#1564]
The plan was that IComponentLoadable would indicate a component provides an IComponentHandle.

However, due to to the desire to transition the runtime incrementally, the `IComponentLoadable.handle` property was made optional while the `url` property was phased out.

Meanwhile, we introduced IProvideComponentHandle, which is used to query a component to determine if it provides an IComponentHandle.

We really only need one of or the other.

**Comment by vladsud** [comment]
I believe this is a dup of #4165
