### ISSUE TITLE
SharedTree SchemaBuilder does not expose its schema so far

### ISSUE THREAD

**Issue by noencke** [microsoft/FluidFramework#15768]
A `SchemaBuilder` can be populated over time to build up a substantial schema. However, the schema can't be queried until the builder is finished. This is inconvenient if you'd like to access existing parts of the schema in order to populate other parts of the schema later.

 It would be useful if the builder could be queried for schema that have been added so far, e.g. something like:

```ts
const builder = new SchemaBuilder("Example");
builder.primitive("number", x);
// ...
// Get the schema for "number" before the builder is finalized:
const numberSchema = builder.get("number");
// ...
```

To work around this right now, you have to manually keep a map of the schema types that need to be re-used. This means passing both the builder and this map into various contexts.

**Comment by DLehenbauer** [comment]
Perhaps consider instead allowing duplicate identical declarations?

A couple of motivations:
* Avoids potential bugs due to type name collisions.
* Allows for adding structural typing in the future where type Ids are computed via hash, and therefore not necessarily known ahead of time.

**Comment by sharptrip** [comment]
@DLehenbauer in case of, e.g., recursive dependencies just allowing to put duplicates into the builder would still require to use an extra cache to stop the recursion.

The first proposal from @noencke however could be simplified: particularly, in our case, there is no need to get the normalized schema before the builder is finalized, but only its lazy version (i.e. a capturing function), just that it could be used again to build further field schemas.
