### ISSUE TITLE
SummarizableObject API Design

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#1653]
The SummarizableObject is an especially complicate data structure, in that all the data written to it, must also be written to it in the summarizer. We should explore if we can make the api of this data structure easier to use, or more explicit in it's limitations

related to #1641

https://github.com/microsoft/FluidFramework/pull/1641#discussion_r398826800
https://github.com/microsoft/FluidFramework/pull/1641#discussion_r398878895

**Comment by vladsud** [comment]
@agarwal-navin, can you please update this issue with latest status? I.e. a lot of time has passed, hard to say the level of relevance prior discussions have to current state.
