### ISSUE TITLE
Handle support in SummarizableObject?

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#1683]
From [#1679 (comment)](https://github.com/microsoft/FluidFramework/pull/1679#discussion_r401105884).

Should we support handles as part of "extended Jsonable" type in SummarizableObject.

**Comment by vladsud** [comment]
that's a good item, but I do not think we will get to it any time soon, so it's appropriate to close.
Note that https://github.com/microsoft/FluidFramework/issues/4329 tracks more generic of either protecting DDSs against handles stored in them (when DDS does not support it) or adding such support, across all DDSs.
So to some extent this is dup, though that uber bug would need to be split (likely) when we get to it.
