### ISSUE TITLE
Ability to reject old loader / container runtime (compatibility)

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#1698]
We need versioning handshake between loader & container runtime.

Scenario: 
- Teams client took v1 of the loader and shipped it
- user on desktop does not want to, or can't (due to corp policy) upgrade client for really long time.
 (or same can happen on mobile - both iOS & Android allow for a user to disable app updated)
- Runtime teams maintains back compat for a year and then removes it for V1 of loader.

Expected:
- some reasonable error to the user notifying that user needs to upgrade application.

What happens today:
- some random crashes.

**Comment by markfields** [comment]
@vladsud is this concern being addressed by other work? I feel it's important to consider still, so reopening.

**Comment by vladsud** [comment]
There is tension here between adding version info or using feature detection as a way to reject old objects.
I think we prefer the later, as it's more granular, allows optionality and works better in presents of forks in versioning (major / minor / patch releases), plus it's much easier to understand from code what actually happens and why version is rejected.

That said, I definitely remember a case where it was not enough, where a combination of specific version of loader & driver caused issues. It was due to runtime behavior differences, not API shape differences.
