### ISSUE TITLE
Publish server container images with semver

### ISSUE THREAD

**Issue by kurtb** [microsoft/FluidFramework#1708]
## Feature
**Is your feature request related to a problem? Please describe.**
Docker doesn't check if tags have changed when running. This makes using "latest" problematic since you likely aren't actually on the latest.

**Describe the solution you'd like**
Similar to our NPM packages we should publish our docker images with a semver. and also update the ranges during publish. This is the common practice on Docker Hub.

For instance - if we just published routerlicoius at 1.2.3

We'd update routerlicoius:1, routerlicious:1.2, and routerlcious:1.2.3

The containers themselves would follow the semver as far as breaking changes go.

Then in our base docker-compose files we could reference either the major or major/minor pair. And rev this whenever a new service version is available.

**Comment by vladsud** [comment]
@tanviraumi , @anthony-murphy , can you please triage? We either need a plan to make it happen or punt - no need to keep old issues around.

**Comment by tanviraumi** [comment]
@curtisman I believe some of this already happens today. We do publish images with build numbers. Although we may not patch older versions?

**Comment by curtisman** [comment]
Correct.  We are tagging images with version number and latest.  
But I didn't follow the recommendation above for the floating tag for major an major.minor.
We can probably close this for now unless there is a demand for it.
