### ISSUE TITLE
Need a way to grab a snapshot from a live document to be used as a template or for automation

### ISSUE THREAD

**Issue by KRyan** [microsoft/FluidFramework#1748]
## Feature
**Is your feature request related to a problem? Please describe.**
We will want to boot new documents against a template snpashot (see #1746).  This means users will be need to create a snapshot from a live document.

**Describe the solution you'd like**
Some sort of tool to grab a single snapshot for the live document, which can be later provided as a template to boot from.

**Comment by jatgarg** [comment]
open

**Comment by jatgarg** [comment]
Workitem=497
