### ISSUE TITLE
Stop requiring guestDisplayName as pre-condition for requestSocketToken: true as part of joinSession payload

### ISSUE THREAD

**Issue by AndreiZe** [microsoft/FluidFramework#17892]
## Work Item

**Describe the outcome you expect**

fetchJoinSession allows requestSocketToken argument which can be set to true to instruct /joinSession backend to fetch access token for Push service and return it back as part of joinSession response payload. Current implementation sends such instruction only if guestDisplayName argument value is not undefined. That used to be required by joinSession implementation, but it is no longer the case. In fact, requestSocketToken is set to true in MSA case and the caller is forced to specify guestDisplayName which does not make sense in case of MSA user (it is not guest scenario).

**Approach**

The code change required is very simple. In the following code we need to remove check for guestDisplayName !== undefined:
[fetchJoinSession](https://github.com/microsoft/FluidFramework/blob/75f06ac03de68ddadf590446220a58e543423714/packages/drivers/odsp-driver/src/vroom.ts#L85) 

**Open questions**

None

**Additional context**

None

**Acceptance criteria**

Code change

**Comment by jatgarg** [comment]
I am going to open an ADO task and will schedule it in a future sprint. Will update once I schedule it.
