### ISSUE TITLE
Protect from lingering inactive summarizers

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#1791]
Currently, summarizer clients can outlive their parent containers for just long enough to summarize one more time.  This means that when other clients are deciding whether or not to spawn a summarizer, they also verify that there are no other summarizer clients in the quorum.

It might be nice to protect against the error case where a bad/inactive summarizer client remains in the quorum indefinitely, preventing other clients from spawning summarizers.

**Comment by vladsud** [comment]
@arinwt , is this still interesting task? I think code accounts for any old client, including summarizer, so this issue is fixed?

**Comment by arinwt** [comment]
We are already working on this anyway when changing elected summarizer client #5222. I will close it when I make that change.
