### ISSUE TITLE
Objects Stored on DDS's should be frozen

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#1792]
We should freeze objects once they are stored on a DDS to prevent bugs with data manipulation not reflected in the data structures.

See:
#136

**Comment by vladsud** [comment]
Issue #5738 looks into a bunch of options in the space and I believe arrives to conclusion that we need to implement deep cloning (semantically at least), not freezing / making things readonly.
I'd propose we use #5738 to continue this discussion and close this one as a dup of it.
Please reactivate if disagree.
