### ISSUE TITLE
ComponentRegistry should not be defined in container-runtime

### ISSUE THREAD

**Issue by kurtb** [microsoft/FluidFramework#1836]
## Feature
**Is your feature request related to a problem? Please describe.**
By defining a helper class like the `ComponentRegistry` on the container-runtime we force component developers to take a hard dependency on the container runtime. Their dependency on the container should be at the interface boundary only. Similar to how we don't want any container to take a hard dependency on the loader package. 

**Describe the solution you'd like**
Migrate this code to one of the util packages.

**Comment by vladsud** [comment]
This is FluidDataStoreRegistry now in same container-runtime package

**Comment by kenluck2001** [comment]
It seems that `IProvideFluidDataStoreRegistry` is imported in `packages\runtime\container-runtime-definitions\src\containerRuntime.ts`
