### ISSUE TITLE
Change when "connected" event fires for view-only connections.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#1839]
Today, there are two problems with view-only connection:

1. If there are no ops on the wire, client does not even know it is behind and will not proactively fetch ops. This totally breaks experience.
2. We have no good signal in telemetry when client is up to date, given default view-only connection. This makes it hard to investigate issues. See [one of the discussions](https://teams.microsoft.com/l/message/19:53328301da384b33bcc81111124e3ab4@thread.skype/1587317929881?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1587317929881&teamName=FFX%20(WAC%20Bohemia)&channelName=Bugs&createdTime=1587317929881)
3. And as a side effect of that, host (and users) has no good signal on client being behind. It looks like we are connected and up-to-date, when we are not.

First, we need to proactively ask storage for ops, in the same way we do when we initially connect.
I also propose that we fire "connected" only once we process "current" op, i.e. latest OP on the web socket.
And if there are no ops, we fire it only after storage request is processed.

Long term, we need better articulation to the host on how far behind this client is, such that client can build proper UX around catching up, i.e. have more than Boolean state of  connected/disconnected.

**Comment by danielroney** [comment]
This has been rolling forward since April. I'm questioning that it's really a high priority bug.
