### ISSUE TITLE
Need to bump axios to 1.6.0+ (and test) to address vulnerability

### ISSUE THREAD

**Issue by astegmaier** [microsoft/FluidFramework#18401]
## Describe the bug

The loop team started receiving component governance alerts related to the version of axios used by some fluid framework dependencies.

The vulnerability is [documented here](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx), and it affects versions of axios earlier than 1.6.0.

There are a few fluid framework packages that are using a fairly old version of axios (`^0.26.0`). The release notes show a number of breaking changes between these old versions and the fixed version, so I'm not sure it's safe for us to just use yarn resolutions to force the upgrade on our side.

<img width="339" alt="image" src="https://github.com/microsoft/FluidFramework/assets/1000369/fb83d6fb-6193-49a4-a71c-5777ea8c5172">

**Comment by JasonGore** [comment]
A couple of [recent](https://github.com/microsoft/FluidFramework/pull/18312) [PRs](https://github.com/microsoft/FluidFramework/pull/18414/files) have bumped `axios` but there is still [an instance in `@fluidframework/driver-utils`](https://github.com/microsoft/FluidFramework/blob/main/packages/loader/driver-utils/package.json#L76) that needs to be bumped as well.

**Comment by JasonGore** [comment]
@alexvy86 Since you did the other two PRs is this an update that you're planning on doing as well? Thanks!

**Comment by alexvy86** [comment]
Not me specifically but @jatgarg has some work items on his plate to do it soon.

I'd expect that using an override / yarn resolution to force 1.6 on your end while we make this change should be ok; in the cases where we already upgraded axios we didn't have to make any code changes, and AFAIK we don't do anything too fancy with it, so what I saw in axios' release notes didn't seem particularly concerning.

**Comment by astegmaier** [comment]
It looks like this work was completed in #18848. Although the change is not yet published (8.0.0 and 2.0.0-dev-rc.1.0.0.225277 has it, but 2.0.0-internal.8.0.0 and 2.0.0-internal.7.4.0 do not) - presumably this will happen soon enough, though.

**Comment by bryanchen-d** [comment]
@jatgarg would there be a new patch release for 1.x version with this fix?
