### ISSUE TITLE
Allow SharedTree to be passed across iframe boundary

### ISSUE THREAD

**Issue by cclauson** [microsoft/FluidFramework#19018]
Hi all,

I have a scenario in which it would be useful to pass a SharedTree across an iframe boundary [as described here](https://stackoverflow.com/questions/36055926/pass-a-javascript-object-to-an-html-iframe-as-an-object#:~:text=One%20can%20simply%20pass%20the,the%20window%20of%20the%20iframe.&text=You%20should%20use%20window.,iFrames%20embedded%20in%20your%20site.).  This works save for one issue--I end up hitting [this assert in sorted btree](https://github.com/qwertie/btree-typescript/blob/e54ffd3c042fd066be55262751691b271413794c/b%2Btree.ts#L593).  The reason this occurs is that the iframe has a separate JS execution context where a different version of the SharedTree module is initialized, and so the comparator functions are different and don't compare referentially equal.

Here's a PR that offers one possible solution:
https://github.com/microsoft/FluidFramework/pull/19017
I can definitely think of others, though, and would welcome discussion of alternatives.

Thanks so much!

**Comment by taylorsw04** [comment]
@cclauson can you give a bit more detail (such as a scenario and call stack) around how this happens? How does the `diffAgainst` method end up being invoked in such a way that two b-trees with different (referentially) comparators are diff'd?

**Comment by cclauson** [comment]
Hi Taylor, thanks so much for the reply. :)

I was actually just about to repost and withdraw this item.  The reason is that based on more prototyping, passing the SharedTree across the iframe boundary no longer looks like the best way to provide host-component iframe isolation, so I no longer think any SharedTree changes will be needed.

To try to reexplain why this happens, though--when a sourced iframe is loaded, it has its own JS execution context and initializes its own versions of the modules, and as such the global functions there are not referentially equal to the global functions in the parent frame.  In the scenario I was referring two above, the Forest constructor is called once in one JS execution context and another time in a different one, resulting in Forests that fail if diff'd.

Sorry for the randomization.  I can provide exact call stacks on a different channel if there's still any interest in this, but again right now it looks like we're okay for our goals.

Thanks and best wishes,
Cooper

**Comment by taylorsw04** [comment]
No problem, let us know if you have other questions, and good luck!
