### ISSUE TITLE
Add an async call in the component initialization path

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#1905]
We may need an async step in the component initialization path that will be called after initialize, i.e. after componentInitializingFirstTime/componentInitializingFromExisting and componentHasInitialized are done.
The above methods are called synchronously and there is no way for components to do additional setup work after the component has finished initializing. I mean they can probably schedule async tasks from componentHasInitialized but it might be worth to explicitly provide a way to do that.

**Some context as to why I am suggesting this**
I ran into this circular dependency problem when using root component in Vltava to integrate LastEditedTracker. Basically, the problem is that any component that need access to functionality provided by the root component have to do so after the root component has completed initializing (so that they can request it).
This means they cannot do that in the componentHasInitialized method unless they fire off an async task or do it in response to some other event (like in #1784, I do it in response to a user action).
I believe it might be worth to provide a function "post" initialization so they can do things like 
requesting IComponent* from the root component.
I feel this may make the root component model a bit simpler to use.

Please let me know your thoughts @anthony-murphy @skylerjokiel @vladsud @curtisman

**Comment by vladsud** [comment]
All methods are async:
    protected async initializingFirstTime(props?: S): Promise<void> { }
    protected async initializingFromExisting(): Promise<void> { }
    protected async hasInitialized(): Promise<void> { }

I believe adding more more method that is async but factory does not wait for would be very confusing, as (on initial look) it would not be clear how it differs from hasInitialized.
Given that what you ask can be accomplished today (by simply launching async task from hasInitialized), I do not see a need to add it to framework - this (if needed), can be done as in derived class.

That, and the fact that there was no movement, means punt.
Please reactivate if disagree.
