### ISSUE TITLE
Improve the logging with PII information - as in rejectDeferredRealize

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#1920]
Right now, we omit the entire error message if it containsPII. We need to preserve the part of the error thats not PII.

Also, the PII information is removed from the Error string but it is still present in the call stack. It should be removed from the call stack as well.

**Comment by markfields** [comment]
Riffing on Curtis's comment, to avoid duplication maybe the PII is what goes in a separate field on the error object, and it's always removed before logging.  I think we can upgrade the `CustomErrorWithProps` class to support this kind of thing safely.

**Comment by markfields** [comment]
Riffing on Curtis's comment, to avoid duplication maybe the PII is what goes in a separate field on the error object, and it's always removed before logging.  I think we can upgrade the `CustomErrorWithProps` class to support this kind of thing safely.

**Comment by markfields** [comment]
Moving to November to take pressure off finishing this month, per conversation with Si and Curtis.

**Comment by markfields** [comment]
> Also, the PII information is removed from the Error string but it is still present in the call stack

This is covered by #3755

**Comment by sumedhb1995** [comment]
Information added to the remote channel context telemetry regarding the data store being loaded in can also be potential PII and would need to be stripped out prior to 3P objects being loaded in
https://github.com/microsoft/FluidFramework/pull/4451

**Comment by markfields** [comment]
@chensixx - FYI I'll take this one from here, this topic has been coming up a bunch recently and I have several things in mind to do here. I'll put you on the PR though since we had discussed this area together!

**Comment by ChumpChief** [comment]
Another item to consider similar to #3755 that was duped in here, is when the `error.message` may contain PII (e.g. potentially IP addresses from network errors).

**Comment by vladsud** [comment]
Moving to Feb - work in privacy domain is a must for GA.
