### ISSUE TITLE
Blazor SDK

### ISSUE THREAD

**Issue by xperiandri** [microsoft/FluidFramework#19249]
Use Fluid Framework in Blazor

**Comment by kashms** [comment]
Hey @xperiandri, Fluid Framework currently only supports JS/TS projects. However, it looks like Blazor SDK supports a JavaScript interop that you can try leveraging with Fluid Framework: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0
Note: I haven't tried it so please keep me posted on how it goes, would be happy to help you through any issues
