### ISSUE TITLE
Use @fluidframework/azure-client can not create container and get Error: 0x883 at app.js:125 

### ISSUE THREAD

**Issue by LuBu0505** [microsoft/FluidFramework#19274]
## User Azure Fluid quick start docs, and try to start it in my loca.
 [quickstart-fluid-relay](https://learn.microsoft.com/zh-cn/azure/azure-fluid-relay/quickstarts/quickstart-dice-roll )

 
### Logs

The browser console error: 
```
[webpack-dev-server] Server started: Hot Module Replacement enabled, Live Reloading enabled, Progress disabled, Overlay enabled.
bootstrap:24 [HMR] Waiting for update signal from WDS...
app.js:125  Error: 0x883
    at assert (assert.mjs:18:1)
    at new SharedTree (sharedTree.js:28:15)
    at TreeFactory.create (treeFactory.js:27:1)
    at new LocalChannelContext (localChannelContext.js:186:1)
    at RuntimeWithRequestHandler.createChannel (dataStoreRuntime.js:206:1)
    at RootDataObject.createSharedObject (rootDataObject.js:95:1)
    at RootDataObject.create (rootDataObject.js:83:1)
    at createObject (rootDataObject.js:39:1)
    at rootDataObject.js:42:1
    at Array.forEach (<anonymous>)
(anonymous) @ app.js:125
Promise.catch (async)
./src/app.js @ app.js:125
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:6
(anonymous) @ startup:6
index.js:485 [webpack-dev-server] Disconnected!
index.js:485 [webpack-dev-server] Trying to reconnect...
```

![image](https://github.com/microsoft/FluidFramework/assets/69841770/404d085c-8dac-47df-80c5-70784d8eb752)

The client code I used:
	const { container } = await client.createContainer(containerSchema);
![image](https://github.com/microsoft/FluidFramework/assets/69841770/d1b0ff68-4c46-4ef8-a45d-dd5270f7576f)

**Comment by nmsimons** [comment]
Alternatively, if you start from a clean clone of the repo and use Node 14, it should work.

**Comment by LuBu0505** [comment]
Thanks @nmsimons ,  You are right.  

when i downgrade nodejs version from ~16 to ~14.  the FluidFramework for azure works.  
![image](https://github.com/microsoft/FluidFramework/assets/69841770/754bdfa4-c67a-45e5-b235-a19a48aebfb6)

and it works in my local. and connect to azure fluid relay server in Mooncake. 
![image](https://github.com/microsoft/FluidFramework/assets/69841770/c550b86d-9dbf-40a9-be17-c0dac4b1f17e)


Thanks very much.
