### ISSUE TITLE
Stumbling blocks for Aqueduct data object authors

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#193]
A list of common stumbling blocks for data object authors, in case anyone wants to brainstorm ideas for improving the ergonomics of the framework:

1. Failures during a data object first init permanently wedges the document.
2. Hangs/races when accessing map keys are difficult to debug.
3. Creating data object/DDSes with duplicate ids results in corruption.
4. Data object registration is easy to forget, crashes the runtime, and is "non-local" to the component.

**Comment by vladsud** [comment]
@skylerjokiel - is this something we need to account for in 1.0 for 3rd parties?
