### ISSUE TITLE
Intervals not at expected location sometimes after undo-ing

### ISSUE THREAD

**Issue by amruth-ms** [microsoft/FluidFramework#19352]
## Describe the bug

With the latest changes in this file(https://github.com/microsoft/FluidFramework/blob/main/packages/dds/sequence/src/revertibles.ts), the undo/redo with intervals is more flexible now. But there are a few instances where after undo-ing the intervals don't seem to be repositioned at the expected location. Below are the repro steps for one such case: 

### To Reproduce

1. Type 9 characters. In this example, let’s say the user typed “123456789”
2. Insert an interval with the same start and end positions of offset 2(after character “2”).
3. Delete characters from offset 2 to 4(characters “3” and “4”).
4. Now trigger undo.
5. Observe that the interval is at the expected location at offset 2(after character “2”).
6. Now delete the character at offset 4(the character “5”). The text should now be “12346789”.
7. Now trigger undo.
8. Observe that the interval is now at offset 4(after character “4”) instead of being at offset 2(after character “2”).

**Comment by scarlettjlee** [comment]
We're looking into this and will update when we have more info.

**Comment by amruth-ms** [comment]
@jzaffiro thank you for the update :). It looks like the changes in the above commit did not reach our repo yet. I will verify if the bug is fixed on our end once we update our FF versions and give you an update.
