### ISSUE TITLE
Log outstanding op count and summary failure during container load not summarize

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#2010]
We should add a signal that can be used to track  summary health. Rather than tracking summaries directly, i think we should track load, and make the following questions answerable for this event:

- Was this load from a summary?
- How may ops were fetched from storage, and applied?

The second questions is probably more important, as if the number of ops retrieved from storage is high, it implies there isn't a recent summary for the document. 

_[edit] Adding some of @arinwt's comments from similar issue #2075_ 

We already have some dashboards and queries for tracking summary health, but we should take the next step and have alerts around these KPIs to get proactive on these types of issues.

It may take a few iterations to figure out the exact thresholds for bad scenarios, but it should be possible to get ahead of docs that aren't summarizing, etc.

Some ideas:

- docs that are failing to summarize; for example "Summarizing_cancel" events (with an error in the log?)
- long trail of ops since last successful summary (as tracked by summarizer)
- fallback long trail of ops since snapshot we loaded from

**Comment by markfields** [comment]
Places to detect long ops since summaries:
* When creating a summary (this exists, but is kind of late to raise the signal)
* When summarizer starts
* When connecting - how many ops are loaded (this is Tony's suggestion above). Could be noisy, but it's the earliest chance.

**Comment by markfields** [comment]
Ok @wes-carlson and I just talked, to summarize (har har):
* Current telemetry (e.g. [these charts](https://portal.aria.ms/health/aa3161633c1343e0b1c1072b710cb544/author)) is based on a [cube](https://portal.aria.ms/cube/26eaecb12cef413e89e1aa3c15a833d7/settings) that aggregates data logged in [summarizer.ts](https://github.com/microsoft/FluidFramework/blob/2d31367e400e7f21e4638f4be2421e88998e22c5/packages/runtime/container-runtime/src/summarizer.ts#L501) (e.g. the `opsSinceLastSummary` prop)
* Per Arin's and Tony's comments above, we think instrumenting container load will be a stronger signal here. @wes-carlson is going to take a look at what specific instrumentation we'd need to generate similar charts from that other source this week.

**Comment by markfields** [comment]
Break down all summary loads by:
* Explicit failure (with an error) -- kick into Safe Summary
* Implicit failure (too many ops loaded - e.g. 1k)
* Successful (and recent)

**Comment by vladsud** [comment]
I believe we already have all telemetry here, in multiple places.
First - TreesLatest perf events - it has data about ops, blobs, trees, size, etc.
Second - Container:Load events - tells what version it was loaded from, some other data.
Third - we issue number of ops we were behind when issuing Connected event (including properties on if it was first connection, etc.).

**Comment by vladsud** [comment]
Same for summary generation - it's already instrumented pretty well, anything in particular we are missing?

**Comment by markfields** [comment]
Very cool, thanks for sharing. Kabir and I will start by familiarizing ourselves with all those instrumentation points and walking through these scenarios with the logs open to see if anything else seems missing.  Maybe we will end up closing with no further code changes.

**Comment by ksbrar** [comment]
Closing this issue. As part of Q1 2021 reliability push, we're adding relevant queries in the ADO repo.
