### ISSUE TITLE
Provide Clear Telemetry Signal when Missing or Duplicated or Misordered Ops are Detected

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#2011]
It is possible in some of our service architecture for ops to be lost due to bugs. If this happens both clients and the server should be able to detect it, and provide a clear signal it has happened, so the issues can be discovered and resolved quickly.

**Comment by markfields** [comment]
@agarwal-navin - Your current investigation into https://github.com/microsoft/FluidFramework/issues/3840 might yield some insight into what would be effective here

**Comment by markfields** [comment]
GitHub ate @anthony-murphy's response, but followed up offline and we agree on closing this one.
