### ISSUE TITLE
Loader::request() may not work properly for getting non-default components

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#2079]
request may always return the default component as it ignores the parts of the request URL after the container ID.
Maybe its the URL resolver's job to add the component's path into the resolved URL that it returns in resolver. But most of the URL resolvers that we have (TestResolver, InsecureUrlResolver, CreationDriverUrlResolver, etc.) does not include the component path in the resolved URL that is returned.

**Comment by anthony-murphy** [comment]
@agarwal-navin I don't really understand this issue. Is there a repo? The todo component uses sub component routing, and worked fine the last time i checked.

**Comment by agarwal-navin** [comment]
Todo component's sub component routing works because it always requests the default component when loading a new tab. For example, when the clicker sub component in todo is clicked to open in a new tab, it calls loader.request and expects the clicker component in it to load. Since clicker is the default component in that Container, it works just fine.
However, if the Container has other components and you want to load them via loader.request, it would not work.

The bug however is not in the Loader but in most of our url resolvers which ignore the path in the request url after the document id. The resolved url they return only contains the path up to the document id from the original url. This works fine if you are resolving a Container or requesting the default component.
Also, note that default component loading only works because an empty string is an acceptable request url for returning the default component.

@chensixx has fixed most of our url resolvers to take care of this and she was able to repro the bug both in the todo component and in tests.

**Comment by chensixx** [comment]
All resolvers that need to be fixed now are done.  Tracking routerlicious resolver in another issue #4232
