### ISSUE TITLE
Implement methods related to detached container in other drivers/resolvers/loaders.

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#2109]
## Describe the bug

After this PR #2022, where we have removed the experimental interfaces and added the apis to original interfaces due to which there a some drivers, resolvers etc where these methods are not implemented. Take a look what makes sense for each of these classes and implement them/put apt comment if not.

**Comment by vladsud** [comment]
@jatgarg, can you please take a look at what actually needs to be done here (if anything)?
Can you please categorize it here?
Or resolve if nothing needs to be done.
