### ISSUE TITLE
FF client Buffer error under browser

### ISSUE THREAD

**Issue by huntj88** [microsoft/FluidFramework#21252]
## Describe the bug
Version with bug: `2.0.0-rc.4.0.1`
This bug does not happen on `2.0.0-rc.2.0.1`

Manual step to fix locally at bottom.

![image](https://github.com/microsoft/FluidFramework/assets/10103298/4701c2c8-fb9a-436a-89e6-abb7fd00d570)

### To Reproduce

1. clone Live Share SDK from `https://github.com/microsoft/live-share-sdk`
2. check out commit `1956dff6e5126b10768858d27d15f7a32e639107`
3. navigate to sample `samples/typescript/08.3d-model`
4. npm install
5. npm run start
6. navigate to `http://localhost:3000/` in browser
7. see blank screen, with error in console 

### Expected behavior

App should work.

### Manual steps required to fix locally
change file node_modules/@fluid-internal/client-utils/lib/trace.js

from:

```typescript
import { performance } from "./indexNode.js";
```
to:
```typescript
import { performance } from "./performanceIsomorphic.js";
```

**Comment by tylerbutler** [comment]
This was fixed by #21257, which was released in [2.0.0-rc.3.0.7](https://github.com/microsoft/FluidFramework/releases/tag/client_v2.0.0-rc.3.0.7) and [2.0.0-rc.4.0.5](https://github.com/microsoft/FluidFramework/releases/tag/client_v2.0.0-rc.4.0.5)
