### ISSUE TITLE
Reduce the bundle size of containers

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#2185]
## Feature
As we start exploring more embedding scenarios for fluid, including loading fluid components in mobile scenarios, we'll have to reduce the cost to load a container. A big area of opportunity we have here is with regards to the amount of code we need to load #366 already covers some of the overhead we are incurring in the loader, contianer, and component layers due to the Node polyfills. This issue specifically tracks some improvements we can make to what needs to get included in a container.

For reference, the container on fluid preview is  220KB (60.99KB gzipped), which is quite heavy considering you'll also have to download one or more components. 172 KB of this bundle is code coming from the Fluid Framework, while the rest is container specific code written by the app team. 

Areas of improvement:
* Reduce the need to include many of these node polyfills (this work is common to loader/container/components, so may be better tracked as an all up effort).
* Delay loading container functionality that is not needed for the initial load. In particular, the chrome coverage report shows that there is a bunch of code around summarizing that is not needed in the initial render and is showing up as unused.

**Comment by heliocliu** [comment]
#3188 tracks removing the url polyfill
