### ISSUE TITLE
Docs Site Search - support full text search

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#2210]

**Comment by markfields** [comment]
@tylerbutler - I mean, this feels important still, but not sure how/when this would be done.  I'll let you decide if we should let it expire (well, manually close at this point) or want to keep it on the backlog.

**Comment by tylerbutler** [comment]
@markfields Yes, this is important. I've put it on the list for July.

**Comment by tylerbutler** [comment]
Dupe of #8012.
