### ISSUE TITLE
Change the message type to Jsonable in submit method in IDeltaConnection

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#2251]
The message type in the following `submit` method should be Jsonable and not any:
```
export interface IDeltaConnection {
    ...
    submit(messageContent: any, metadata: unknown): number;
    ...
}
```

Created from the comment in the following PR:
[#2235 (Comment)](https://github.com/microsoft/FluidFramework/pull/2235#discussion_r427685464)

**Comment by vladsud** [comment]
I believe decision was made to abandon similar approach for DDSs as it was hard to impossible to make it happen.
Main issue tracking discussions: https://github.com/microsoft/FluidFramework/issues/136
Closing, please reactivate if disagree
