### ISSUE TITLE
Enable strictNullChecks throughout

### ISSUE THREAD

**Issue by GaryWilber** [microsoft/FluidFramework#2358]
The TypeScript option `strictNullChecks` is currently disabled in most `server/routerlicious` packages. We should work on enabling it.

**Comment by markfields** [comment]
Updating title and removing `area: server` tag. All our packages should use `strictNullChecks`.  Packages under `examples` dir are maybe a lower priority... but really everything should.

**Comment by markfields** [comment]
Also worth auditing/considering the `strict-boolean-expressions` ESLint rule.  See also: https://github.com/microsoft/FluidFramework/issues/2809 and https://github.com/microsoft/FluidFramework/pull/3770

**Comment by markfields** [comment]
@GaryWilber - if you want this issue to stick around, reopen, maybe noting which packages still need to be fixed up.  Thank you and @curtisman for your work here btw!
