### ISSUE TITLE
Setup repo health report script

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#2381]
this will give us a sense of how engaged the community is and how well the team is doing at responding to issues and PRs. Fluent has a script and report that we should copy.

**Comment by tylerbutler** [comment]
@danielroney Could you follow up on the script with the Fluent team? Once we have it we'll determine how/if to automate.

**Comment by tylerbutler** [comment]
This is done, but I need to document how to use the script.

**Comment by tylerbutler** [comment]
This is documented in the repo management info.
