### ISSUE TITLE
Log additional request performance metadata in ODSP driver

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#2396]
The ODSP folks recently started returning the necessary HTTP headers for us to be able to get more advanced performance information from the [resource timing API](https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API). We may want to add some code in the driver to log any metadata from there that we think is worth having on the client.

**Comment by markfields** [comment]
Is this PR related...? It's reading the `sprequestduration` header and logging it, along with a bunch of other timing info.
https://github.com/microsoft/FluidFramework/pull/3600

cc @jatgarg

**Comment by christiango** [comment]
Looks like it is, I was logging this issue on behalf of the ODSP team. Since it looks like they made this change, we should probably close the issue.

**Comment by curtisman** [comment]
Yep.  I have confirmed with Ram Ramasubramanian that this change is already done.
