### ISSUE TITLE
Handle hardcoded Auspkn links

### ISSUE THREAD

**Issue by SamBroner** [microsoft/FluidFramework#2401]
A few containers, including Waterpark, rely on a hardcoded link to Auspkn. We should refactor these to take in a link. 

An example of the hardcoded elements is on display in this PR: https://github.com/microsoft/FluidFramework/pull/2402

**Comment by tylerbutler** [comment]
@SamBroner Is this still valid?

**Comment by tylerbutler** [comment]
Triage: Yes still valid; @SamBroner will update with details.
