### ISSUE TITLE
Webpack-Component-Loader should try to determine if service is available

### ISSUE THREAD

**Issue by SamBroner** [microsoft/FluidFramework#2440]
## Feature
**Is your feature request related to a problem? Please describe.**
When I use the webpack component loader, I sometimes forget to start my service or the service broke. This is confusing to me because I expect my service to be up. This may be confusing to new developers because they assume that "npm run start:tiny" to work without additional dependencies.

**Describe the solution you'd like**
A descriptive error originating from webpack-dev-server (Looks like you wanted to run against tinylicious, you didn't start that service, here's the guide)

**Existing work**

**Describe alternatives you've considered**

* Include tinylicious in yo-fluid so that it's more discoverable, potentially trigger that service with webpack
* Include tinylicious in webpack-dev-service

**Additional context**

**Comment by tylerbutler** [comment]
This was completed.
