### ISSUE TITLE
Add infra to discover bundle sizes and size deltas

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#2449]
## Work Item
**Describe the outcome you expect**

We should be able to easily examine sizes of bundles (from their imported modules etc) within fluid framework to identify modules that shouldn't be imported or are larger than desired, similar to tool from the live site analyzer (https://fluidpreviewlivesitehub.azureedge.net/bundle) or to the size auditor used by fluentui (https://github.com/apps/size-auditor).

**Approach**

Just add some scripts, bro
Maybe add some pipes and bots too
Use base-host as the consumer for considering what modules are consumed.  If we end up running this as part of the CI loop, we would stick to examining deltas for packages consumed by base-host.

**Open questions**

It's unclear if we want to have size deltas be presented for all changes (like flientui does), or just have this as a tool that can be run when pertinent.  Having it run for all changes means adding steps to the CI loops to webpack/minify all our packages, then having each PR run webpack and compare to the baselines as well.  It's possible we don't want to add that time to the CI loop.

If we decide not to run deltas for every change, then this work probably isn't necessary or worth because we already get this information (though at a slower cadence) from the live site analyzer.

**Additional context**

**Acceptance criteria**

- [x] Add a webpack config to minify sources to all relevant packages in fluidframework to get accurate sizes for real world consumption.  Est. 16hr
- [x] Write (copy from fluentui https://github.com/microsoft/fluentui/blob/master/scripts/tasks/bundle-size-collect.js) script to collect file/bundle sizes for consumption by the size-auditor tool, and update all relevant package to run this script.  Est. 8hr
- [x] Add/update build pipelines to generate size information for published builds.  Est. 4hr
- [x] Integrate size-auditor bot into fluidframework to provide size-deltas for each change for relevant packages.  Est. 8hr
Total swag 36hr

**Comment by christiango** [comment]
Great to see this issue was resolved. Where can I see this in action?

**Comment by heliocliu** [comment]
@christiango It's active in the PRs now, but broken atm because the automated checks aren't working.  You can see what it looks like in #3824 though.
