### ISSUE TITLE
Bring IContainer interfaces to maturity

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#2465]
Currently, the IContainer interface layer has not been fully updated to match the usage patterns Bohemia has for Container. As such, in many scenarios, instead of using the interface, the Container class is directly specified as the type across the codebase. Furthermore, to our partners, Bohemia provides an ExternalContainer type that builds upon Container and IContainer. As long as we maintain the ExternalContainer layer and have IContainer changes be backwards compatible, we can avoid breaking our 1P partners. Once we achieve the goal of having our 1P partners all using the IContainer interface, we can apply further changes to improve said interface such that it provides a clearly defined and useful set of functionality for both our 1P and 3P partners. This document will provide a plan of action and a survey of what is available on each of these three different types and where the exposed functions get used in the Bohemia codebase: https://microsoft-my.sharepoint-df.com/:fl:/p/sumbhatt/EeVGlvYFKUJOpSpt2BXZGywBkpOAhoIEbJWe2ZMg_BCMYw?e=GdM1Eg

For a quick summary of the 3 phases:
1. Apply code changes for the next FF Runtime version (0.52) to add to the IContainer interface in such a way that it can be used across Bohemia instead of Container

This will include adding the following:
- connectionState
- connected
- setAutoReconnect()
- resume()
- audience
- clientId
- readOnlyInfo
- forceReadonly()
And deprecating and adding the following:
- codeDetails -> getSpecifiedCodeDetails()

2. Migrate Bohemia to only IContainer usage after 0.52 release. Since the Loader will now only be returning IContainer types, we will get compiler errors if there are any gaps in the Container and IContainer interface, but there shouldn't be since the above list is based on the usage survey compiled in the next section

3. As a longer term phase 3, we can update the IContainer interface to now actually provide the desired developer surface. With phase 1 & 2 completed, we know that the IContainer is the only exposed layer and any work to update the surface only needs to be done on this exposed layer. This can include work such as instead of exporting the deltaManager wholesale, we instead provide a specific class with control functions that allow the consumer to dictate how they want the op stream to be processed.

Please find additional details, rationale, and a full survey of the Container and IContainer interface usage in the attached doc

Subtasks: (with timeline proposed by Dan)
Nov/Dec
- [x] #8316
- [x] #8317

January 
- [x] #8318

February
- [ ] #8319
- [ ] #8320

**Comment by vladsud** [comment]
Please see some details from #1707

**Comment by sumedhb1995** [comment]
@danielroney  Survey of differences between Container and IContainer, and their usage in Bohemia + plan for moving forward with changes:
https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!hHsirWQOoU2heUUWGCPCxh30vuxFqQZHpGAGJHpXxq0ciqj-SgV4S7_BjyC2h-qk&item=01L6VZH7HFI2LPMBJJIJHKKKTN3AK5SGZM&file=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fsumbhatt_microsoft_com&siteUrl=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fsumbhatt_microsoft_com

**Comment by danielroney** [comment]
Updating title to scope this to IContainer. A new epic has been created for ILoader interfaces.

**Comment by sumedhb1995** [comment]
Phase 3 is tracked in its own epic here: https://github.com/microsoft/FluidFramework/issues/8319
Closing this out as completing the required work prior 1.0
Additional work will continue to improve the IContainer dev surface in the Phase 3 epic
