### ISSUE TITLE
Ability to distinguish edits between different users of same local DDS

### ISSUE THREAD

**Issue by kurtb** [microsoft/FluidFramework#249]
When implementing multiple component views of a DDS where each view is bridging to a different local data model (i.e. sequences bound to different instances of CodeMirror) it would be helpful to be able to distinguish which view just made the change - i.e. some kind of local clone or shadow copy - so that when the change event fired there was enough information to detect which local user made the change.

**Comment by vladsud** [comment]
Closing all really old issues. This one is 1.5 years old!
