### ISSUE TITLE
[merge-tree] Change imports to work around https://github.com/microsoft/web-build-tools/issues/1029

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#2543]
api-extractor is currently not compatible with local imports that create a new namespace. That is, imports of the form import * as MyNamespace from "./localFile"; See microsoft/rushstack#1029.

The workaround is either to explicitly name all the imports, (i.e. import { IIntegerRange, Property } from "./base";) or to use TypeScript namespaces.

merge-tree uses the import * pattern a lot, so switching to explicit imports is possible but is a big code change, and might make the code less readable. This bug tracks a better workaround, namely using namespaces.

NOTE: This issue is being ported from our old repo.

**Comment by tylerbutler** [comment]
Closing this since we don't _need_ merge tree API in the docs since it's all internal. We can revisit this after api-extractor fixes it.
