### ISSUE TITLE
Wire efficiency of the Fluid protocol has room for improvement

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#2676]
A potential partner asked about the wire efficiency of the Fluid protocol and I thought I'd share my quick investigation.  This is for a single op to zero one cell of a SharedMatrix.  The total # of bytes enqueued on the WebSocket was 416B.

Category | Percentage
-|-
JSON Encoding | ~64%
Information | ~30%
Socket.IO | ~6%

The percentages above split the difference between a very conservative estimate and a more realistic estimate where most integers are assumed to be 4B and discriminators are 1B.

To conservatively estimate the actual information transmitted, I assumed:
* GUIDs carry 16B of information
* All integers carry 8B
* Discriminators like "opType" reduced to integers.
* Arrays include an integer length followed by discriminated entries

Source|Bytes used|Bytes of information|Efficiency
-|-|-|-
Socket.IO|23B|23B?|100%?
ClientID & BoxCar | 43B | 24B | ~56%
IDocumentMessage (less tracing) | 84B | 24B | ~29%
Tracing | 76B | 32B | ~42%
Double-encoding | 30B | 0B | 0%
Content (less double-encoding) | 160B | 72B | ~45%

For a very conservative estimate of 42% efficiency (or 58% overhead).

Efficiency drops to 30% (or 70% overhead) if we assume most integers are 4B and discriminators are 1B.  If we discard unnecessary information like tracing, we approach 20% efficiency (or 80% overhead).

**Comment by vladsud** [comment]
@DLehenbauer, I wonder if it matters that much.
On websocket, it seems like it's more important to fit it into single IP packet - I think number of bytes there is secondary.
Storage compresses ops in big chunks (at least ODSP), so it compresses very well (If I'm not mistaken, when we fetch ops, 2K ops is on average results in 70-80K compressed payload).

I've looked into couple compression schemas as part of https://github.com/microsoft/FluidFramework/issues/4589#issuecomment-744021516, if you find it interesting

**Comment by vladsud** [comment]
Either way, we should either have a plan to improve here, or punt
