### ISSUE TITLE
Request Parser should handle pathing correctly when createSubRequest is called

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#2677]
## Describe the bug
Today RequestParser handles createSubRequest pathing by joining subparts with '/' and returning undefined when it does not see valid path parts beyond the subrequest. This introduces a few bugs detailed below. Note that this issue has so far hidden another bug in ComponentHandles in the Fluid repo so the component handle issue might want to be fixed first before fixing this issue. @skylerjokiel is there an issue for the componenthandle bug?

### To Reproduce
Call RequestParser.createSubRequest(1) on several paths which exposes several (all related) bugs in the createSubRequest logic

Bug 1: leading slash (and trailing slash where needed?) is dropped:
Setup: Request URL is "/id/id2/"
Expected: "/id2" or "/id2/"
Actual: "id2"

Bug 2: Returned value for final sub request is undefined instead of '/'
Setup: Request URL is "/"
Expected: "/"
Actual: ""

Bug 3: Returned value for sub request is undefined and does not include query params
Setup: request url is "/?queryParams
Expected: "/?queryParams"
Actual: undefined

**Comment by vladsud** [comment]
Note: undefined is gone from API signature, it throws when called out of range.
Other parts of issue are still the same and need to be evaluated.
