### ISSUE TITLE
Drafts: Implement ability to rehydrate detached container

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#2692]
Scenario:
OWA / Teams:  user created a message draft (detached container) and moves away, closing browser.
User needs to come back and continue working on draft.

To implement it, Fluid framework needs to provide a way for host to
1. capture state of detached container at any moment in time (snapshot, saving drafts on a timer)
2. Allow user to continue editing 
3. rehydrate container from that state later on
4. repeat 1-3 any number of times.
5. attach container to storage.

Container representation should be mostly opaque to host (i.e. it's either a string, or jsonable object, likely later is preferred).
Implementation wise, we should heavily rely on snapshots, but ensure that capturing snapshots does not change container state (see # 2 above - we should not assume that capturing snapshot transitions container to attached state - these are two different actions).

**Comment by jatgarg** [comment]
Closing with: https://github.com/microsoft/FluidFramework/pull/3572
