### ISSUE TITLE
SharedNumberSequence is just SharedObjectSequence<number>

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#2696]
The only difference between these two DDSes is that SharedObjectSequence allows the user to specify the `T` type parameter while SharedNumberSequence hard codes `T` to `number`:

```ts
export class SharedObjectSequence<T> extends SharedSequence<T>
export class SharedNumberSequence extends SharedSequence<number>
```

I'd recommend:
* Deleting SharedNumberSequence
* Merging SharedObjectSequence into SharedSequence (making SharedSequence<T> the concrete type people use.)

**Comment by vladsud** [comment]
@DLehenbauer, @anthony-murphy, can you please make progress - either agree on next step or punt?
It's not worth sitting on it for a year :)
