### ISSUE TITLE
Remove value type usage in Sequence

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#2754]
There's no more public exposure of `.createValueType()` from our DDSs after #2574, but we still use it internally (off the map kernel) in Sequence.  If we are able to remove this usage then we can get rid of some otherwise unused infrastructure in map kernel.

**Comment by vladsud** [comment]
@ChumpChief , is this item still relevant?

**Comment by ChumpChief** [comment]
Yes as far as the goal of removing the value type infrastructure in map, though I've been thinking a potentially easier route forward would be to first split the kernel and move the value type support over to sequence, rather than trying to eliminate the dependency immediately.
