### ISSUE TITLE
Resolve waitAttached promise on attached after attachOp roundtrip.

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#2763]
## Describe the bug

Due to back-compat component attach deferred promise needs to be resolved earlier rather than when it is actually attached because we declare the component as attached in getAttachSnapshot before the attached event is fired due to back compat reasons. Once we remove that, resolve the promise on attached event.

**Comment by vladsud** [comment]
@jatgarg - is this item still relevant?

**Comment by jatgarg** [comment]
Will take a look soon.
