### ISSUE TITLE
Loader need to cache paused container

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#2765]
See https://github.com/microsoft/FluidFramework/blob/master/packages/loader/container-loader/src/loader.ts#L290

While container that is never resumed should not be cached, today's mainstream scenarios all start with paused container, and later on it is unpaused. We do not reuse such container in copy/paste scenarios today, which results in substantial hit in perf (loading another instance of same thing).

More info in [this discussion](https://teams.microsoft.com/l/message/19:70dd7738d97f48f7b68b7a0c8ef0e03c@thread.skype/1594327746790?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1594144202017&teamName=FFX%20(Fluid%20Framework%20and%20Experiences)&channelName=Office.com&createdTime=1594327746790)

**Comment by heliocliu** [comment]
Closing because this seems the same as #4489
