### ISSUE TITLE
Improve back compat compatibility

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#2841]
Currently, our testing strategy involves N/N-1 testing.
This is good start, but that is not sufficient long term, and even now it cases problems, because hosts are not picking up loader changed fast enough.

In terms of priority:
1. We need to support N-2/N for loader/container runtime pair, and if possible, even further out (N-4/N might be good starting point). I do not know, but we should think if that means that all pairings needs to be hit (N-3/N, N-2/N, N-1/N), or hitting only extreme end (N-4/N and maybe N-1/N) is enough

2.  Lower priority, but we need the same for container runtime to component runtime boundary.

**Comment by SamBroner** [comment]
This seems like an E2E testing issue (Just flagging the E2E word)

**Comment by heliocliu** [comment]
Are we happy with the version coverage for end-to-end tests now (n/n-1, n/n-2)?  The actual test coverage aside, adding n/n-3 or n/n-4 shouldn't be difficult if we think it's useful.

**Comment by vladsud** [comment]
For compatibility below container runtime line (i.e. container runtime to data store runtime): we are good as is. It only exists to support components developed in multiple repos, and given a chance for different repos to pick up fluid bits independently, but supporting N-1 only forces everybody to move forward quickly. We do not support dynamic component loading, so that's not a concern.

For loader to container runtime compatibility: What we have is far from needed. Once Teams ships their client, we should assume the version of loader they ship will be in use for a year minimum. Even if we release new loader version and they immediately pick it up, some number of users will not upgrade / disable upgrades / their admin will sit on 6-month or 12-month office release branch. So old loader will need to work with new container runtime for at least a year.

It's hard for me right now to translate that to requirement for our testing, as clearly we do not want to test compat for N-100...N versions. But we need a strategy here, and we need it soon.

**Comment by vladsud** [comment]
Bumping to April as it's a much for GA. It does not have to ship as part of GA, but any build that we release past GA has to have much stronger compat story than what we have today. So essentially it has to be done by end of April

**Comment by vladsud** [comment]
Copying data from 5693:

Apps that ship with a version of loader will be in prod quarters, maybe years.
We need to ensure that

we test older versions that were shipped many months back
when we decide to break compat, we do it in predictable manner, raising proper errors to the user (Office.com) and falling back to links in Teams / OWA
Have one error code that is documented (and used in shared UX) to deal with above.

**Comment by vladsud** [comment]
I think we should add two configs:
1. Loader at 0.39 and everything else latest
2. Loader + Driver at 0.39, and everything else - latest

Where 0.39 is the fixed version that does not change over time

**Comment by vladsud** [comment]
This is being addressed by PR https://github.com/microsoft/FluidFramework/pull/6240
