### ISSUE TITLE
request for a URL with no handler throws

### ISSUE THREAD

**Issue by BrianMar** [microsoft/FluidFramework#2859]
## Describe the bug
Create a new Fluid component with yo fluid

Make a request in componentIntializingFirstTime as follows:

    protected async componentInitializingFirstTime() {
        this.root.set(diceValueKey, 1);

        const shouldFail =  await this.context.hostRuntime.request(
          {
            url: '_ShouldFail_',
            headers: { wait: false } 
        });
        if (shouldFail) {
            console.log(shouldFail);
        } 
    }

### To Reproduce
'npm run start' to start the project.
Open localhost:8080 in the browser
F12 to bring up the debugger
Set a breakpoint on the "const shouldFail...' line
Re-open localhost:8080 (remove the generate document name from the URL)
Stop at the breakpoint.
Step over the line.

### Observed behavior
The debugger never returns. The code is hung. Console output:

common.js:114 fluid:telemetry:Container ContainerClose {"loaderId":"f36ef06f-3ac3-4d85-916f-45dec8392bb1","clientType":"interactive","loaderVersion":"0.20.4","containerId":"44b12efb-3c80-4d8f-9908-c036d56ac5d1","sequenceNumber":3,"category":"error","error":"Process _ShouldFail_ does not exist","message":"Process _ShouldFail_ does not exist","canRetry":false,"errorType":0,"docId":"polite-zinc","containerAttachState":"Attached"}  Error: Process _ShouldFail_ does not exist    at CreateContainerError (http://localhost:8080/node_modules/@fluidframework/webpack-component-loader/dist/fluid-loader.bundle.js:153559:16)    at http://localhost:8080/node_modules/@fluidframework/webpack-component-loader/dist/fluid-loader.bundle.js:150310:113 +0ms
debug @ common.js:114
......Full stack trace 
[TestLog.txt](https://github.com/microsoft/FluidFramework/files/4950523/TestLog.txt)
below....
polite-zinc:1 Uncaught (in promise) Process _ShouldFail_ does not exist

### Expected behavior
The request call should return with a rejected promise

### Logs
Attached

**Comment by vladsud** [comment]
I believe we hit couple cases like that in the past where exceptions would be thrown on request path and we addressed some one them.
https://github.com/microsoft/FluidFramework/pull/5215 will address that at it's core.
