### ISSUE TITLE
Fix shared-text / FlowContainer to not use 'client-api' and update 'documentId' usage

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#2915]
There are two problems with `shared-text` component:
1. It uses api.Document from client-api which it should not.
2. It uses `documentId`. With detached container flow, the `documentId` does not update until the container is attached, so shared-text needs to account for that.

From https://github.com/microsoft/FluidFramework/pull/2889#discussion_r461118215, https://github.com/microsoft/FluidFramework/pull/2889#discussion_r461943314 and https://github.com/microsoft/FluidFramework/pull/2889#discussion_r461944027

**Comment by curtisman** [comment]
Related to #2625

**Comment by vladsud** [comment]
Moving to August, given that downstream issue https://github.com/microsoft/FluidFramework/issues/2903 is in August

**Comment by chensixx** [comment]
I believe this is all fixed by Matt's PR #7382
