### ISSUE TITLE
Remove "fluid/component" mimetype support

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#2934]

**Comment by Dhoot** [comment]
@vladsud & @anthony-murphy can I work on it ?

just validating my understanding about this issue after doing some code reviewing in whole FluidFramework wherever we have mimetype check as "fluid/component" it should be removed / replaced with "fluid/object"

**Comment by vladsud** [comment]
Of course you can! I'll assign it to you!

You should only need to delete references to fluid/component, as it should already always exists with appropriate duplicated check for fluid/object. I.e. 

```
            !(
                response.mimeType === "fluid/component" ||
                response.mimeType === "fluid/object"
            )) {
```
or
```
(response.mimeType !== "fluid/component" && response.mimeType !== "fluid/object")
```

**Comment by Dhoot** [comment]
Thanks on it now!

**Comment by Dhoot** [comment]
PR #6355 is merge!
