### ISSUE TITLE
Track in telemetry response time for snapshot fetch requests

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3072]
The ask from Ram is to have insights into all pieces of this request.
Currently we track total time, and SPO tracks their processing time.
It would be great to track "download" time, i.e. total time takes from first byte till last byte/

**Comment by vladsud** [comment]
@raandra, @jatgarg, is this done? I thought I saw a PR with implementation.
If not, when it will be done? Should it be moved to October, or Next?

**Comment by raandra** [comment]
@vladsud This is done!

**Comment by jatgarg** [comment]
Yes, we can close it.

**Comment by vladsud** [comment]
Thanks, closing!
