### ISSUE TITLE
typescript-eslint rules shouldn't run on .js files

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#3098]
## Describe the bug
See https://github.com/microsoft/FluidFramework/pull/3069#discussion_r466638274

### To Reproduce
See https://github.com/microsoft/FluidFramework/pull/3069#discussion_r466638274

### Expected behavior
No in-file suppressions required for typescript-eslint rules in a .js file.

**Comment by curtisman** [comment]
We will come back and do it if there is a need. Currently, the file is already not looked at by eslint because it is not in `src`
