### ISSUE TITLE
Snapshot tests are not always failing from errors

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#3107]
Errors encountered in the threads are not always propagating and causing the tests to fail.

The error I consistently repro (every time) was an op handling error (attach message was throwing because of some bad code). The output would include the error details, because the logger was printing them, but the test itself wasn't failing.

**Comment by heliocliu** [comment]
More detailed discussion in the PR, but I went with just re-throwing all errors in the replay-tool logger.  This could potentially cause problems depending on the expectations of the replay-tool (e.g. if some failures are expected), so I can revisit if that's the case (once replay-tool is working again)
