### ISSUE TITLE
Add E2E test cases for r11s route for detached container.

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#3114]
## Describe the bug

Add E2E test cases for r11s route for detached container, so that we know when something is broken.

**Comment by SamBroner** [comment]
Hey @jatgarg is this work that you're going to do in September? Does it need to be done?

**Comment by jatgarg** [comment]
@markfields This is done, right?

**Comment by markfields** [comment]
Yep #3612
