### ISSUE TITLE
Coding guideline: When to use assert messages

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#3132]
Because this has come up a couple of times in code reviews, I wanted to propose the following guideline on when to include the optional 'message' parameter when using the node "assert" module:

My practice is generally:
* Always include a message when a failure indicates an end user error.  (e.g., vetting parameters of a public API)
* Always include a message when using "assert" within test code to help diagnose test failures from logs.
* Use a comment instead of a message when the assertion indicates a Fluid bug.  (e.g., vetting internal self-consistency)

An example of the last case:
```ts
// Vet that the 'cells' array has already been updated to match the matrix's new dimensions.
assert.equal(cells.length, rowCount * colCount);
```

The motivation for using a comment instead of a message in the last case:

1.  Assertion messages count against our bundle size.
2.  Assertion messages sometimes impact runtime performance.

(In theory, gzip helps and hopefully it's rare that providing a message impacts inlining or register allocation, but my bias is still to prefer comments.)

**Comment by markfields** [comment]
> IMO, if a function has more than one assert, adding a message helps in knowing which one was hit

I've definitely been bit by this.

Furthermore, talking with @anthony-murphy, he pointed out that once the JS is minified, the stacks can get a big mangled relative to the source code, so this is important in any case.

Perhaps we should look into a tagging mechanism like y-arnold used to do in the old Office codebase.

**Comment by vladsud** [comment]
@DLehenbauer, I believe it's time to close this issue. Today, message is required (it's not optional), but related later by tag. I'm not a big fan of it as is (as it's equivalent to forcing me to write a message on every IF statement), but I think this ship has sailed.

**Comment by DLehenbauer** [comment]
Tagged asserts is a reasonable compromise.
