### ISSUE TITLE
MessageType.Attach triggers remotedComponentContext.realize()

### ISSUE THREAD

**Issue by cosmincatrinescu** [microsoft/FluidFramework#318]
My second client container runtime ends up calling instantiateComponent during resolve() as a result of incoming remote ops.  This seems unexpected and should not happen (e.g. virtualization or single component loads will likely not need to get to that remotely inserted component)

Callstack:
realize (componentContext.js:92)
await in realize (async)
getComponentRuntime (containerRuntime.js:552)
await in getComponentRuntime (async)
(anonymous) (OfficeContainerRuntimeFactory.js:20)
request (containerRuntime.js:404)
get (getOfficeComponentFactoriesRegistry.js:154)
getComponentFactoryFromRegistry (getOfficeComponentFactoriesRegistry.js:221)
get (getOfficeComponentFactoriesRegistry.js:213) "{ sourceType:'spfx', id:'foo' }"
await in get (async)
get (containerRuntime.js:1063)
realize (componentContext.js:89)
await in realize (async)
(anonymous) (containerRuntime.js:755)
Promise.then (async)
processCore (containerRuntime.js:755)
process (containerRuntime.js:515)
process (containerContext.ts?8677:216)
processRemoteMessageNew (container.ts?95c1:1026)
processRemoteMessage (container.ts?95c1:985)
process (container.ts?95c1:850)
processMessage (deltaManager.ts?ef93:882)
eval (deltaManager.ts?ef93:201)
processDeltas (deltaQueue.ts?0640:162)
updatePause (deltaQueue.ts?0640:108)
resume (deltaQueue.ts?0640:78)
resume (container.ts?95c1:357)
eval (container.ts?95c1:622)
Promise.then (async)	
await in resolveCore (async)
resolve (loader.ts?13fa:172)

**Comment by vladsud** [comment]
A lot of things have changed (including op processing becoming non-async).
I believe we do not realize data stores until they are absolutely needed.
Closing all really old issues (this one is 1.5 years old)
