### ISSUE TITLE
Simplify channelDeferred  in data store context

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3185]
this.channelDeferred in DataStoreContext.ts can be replaced with simple promise (and code simplified), once we do not need to support direct calls to bindRuntime().
This can be done once https://github.com/microsoft/FluidFramework/pull/3112 is in and a version passes by.

**Comment by danielroney** [comment]
Per discussion at milestone planning, moving un-projected issues to Next.
