### ISSUE TITLE
requestFluidObject circumvents the FluidObject delegation pattern

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#3237]
## Work Item
**Describe the outcome you expect**
requestFluidObject in dataStoreHelpers.ts lets you pass in a type, and it will cast the response value to that type and hand it back. But really what it's returning is a `FluidObject` (that is, we don't know what it is), and that object should be queried for the desired interface - and maybe another object will be returned, as opposed to the object in hand.

**Approach**
Update the signature to `requestFluidObject<T = unknown>(...): Promise<FluidObject<T>>`, updating usages like this:

old:

```
const foo: IFoo = requestFluidObject<IFoo>(...);
```

new (type annotations are illustrative and not required):

```
const fluidObject: FluidObject<IFoo> = requestFluidObject<IFoo>(...);
const foo: IFoo | undefined = fluidObject.IFoo
```

**Additional context**
- Some types being passed in may not implement the IProvide pattern and thus would be incompatible with `FluidObject` pattern. So we'll have to deal with those.
- We'll have to explicitly handle the undefined case now, which will hopefully be straightforward - I guess we can just `!` it to get the same behavior as before.

**Acceptance criteria**
Remove the direct cast to `T` in requestFluidObject, replacing with a cast to `FluidObject<T>` so the caller deals with the provider/FluidObject pattern properly.

**Comment by markfields** [comment]
This should still be done.

**Comment by markfields** [comment]
FYI @anthony-murphy I updated the original comment to reflect the new world with `FluidObject` replacing `IFluidObject`.  I've heard you talk about deprecating the requests paradigm from the runtime layer anyway so in that case this is moot.

**Comment by anthony-murphy** [comment]
yeah. i created an item for that: #8169

**Comment by markfields** [comment]
This still matters IMO but leaving closed since we're tracking work internally in ADO now.
