### ISSUE TITLE
Remove back-compat code for SummaryTracker

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#3243]
Remove all references to SummaryTracker and fully switch to SummarizerNode.

- Can delete SummaryTracker and ISummaryTracker altogether
- Can remove ConditionalSummarizerNode in place of just regular SummarizerNode
- Can remove back-compat checks for SummarizerNode across component context/runtime boundary

**Comment by anthony-murphy** [comment]
remove the dummy summary tracker: https://github.com/microsoft/FluidFramework/pull/4512#discussion_r534612448 and close this issue

**Comment by arinwt** [comment]
> remove the dummy summary tracker in 0.31 or later: [#4512 (comment)](https://github.com/microsoft/FluidFramework/pull/4512#discussion_r534612448) and close this issue

For posterity:
The original PR didn't make it into 0.30, but rather into 0.31, so actually the follow-up change needed to be in 0.32 or later.

**Comment by anthony-murphy** [comment]
0.32 should release this week. maybe just sit on this PR for a couple days, and checkin after release
