### ISSUE TITLE
Document driver behavior

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#325]
We've had questions from the SPO team regarding specific driver behavior that should be documented. For example:
- Fallbacks on failures
- Component protocol for joining the session and making the component live?
- How 'aggressively' it joins a session
- Whether its resilient to being disconnected
- Whether it obeys the 429/503s etc from service, etc.?

**Comment by leeviana** [comment]
Leaving a comment so it's not marked as stale.

**Comment by jatgarg** [comment]
Workitem=495

**Comment by leeviana** [comment]
@jatgarg Does this mean it's tracked somewhere else now? How do I interpret this? :P
