### ISSUE TITLE
Add a flag to IAgentSchdeuler.pick() that conveys what the user intent is

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#3305]
The user intent should tell whether the task should be picked no matter what. For example, if client is in "read" mode, we will still go ahead and pick the task by probably changing the client to "write" mode first.

Once this is done, the end-to-end tests in `packages\test\end-to-end-tests\src\test\agentScheduler.spec.ts` should be updated as per the new API design. Right now these tests first convert the client to "write" mode and then runs the tests.

**Comment by vladsud** [comment]
Moving to January, as people are asking about it. In particular tasks FC needs support here.

**Comment by ChumpChief** [comment]
I don't think this is needed anymore.  I also suspect that this scenario doesn't need to track the intent within the `IAgentScheduler`, as the "should switch to write if no write clients connected" characteristic of the task is already known by the read clients prior to switching to write, at least in the scenarios discussed so far.
