### ISSUE TITLE
UpgradeManager should handle code proposals from "read" mode clients

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#3312]
Currently, if a client in "read" mode proposes a new code via the UpgradeManager, it fails. UpgradeManager should handle this scenario by resending the quorum op which gets nack'd due to the "read" only mode.

Once this is fixed, remove the workaround in `packages\test\end-to-end-tests\src\test\upgradeManager.spec.ts` that sends an op before proposing new code so that the Container is switched to "write" mode.

Also, look at `packages\test\end-to-end-tests\src\test\contextReload.spec.ts` tests. They don't use UpgradeManager but propose code as soon as Container is loaded. It should either not do that as soon as Container is loaded or should use UpgradeManager.

**Comment by vladsud** [comment]
Is this same as #1539 - Proposal: Quorum: reliable workflow ?

Other items that look related:
#1280 - Fluid Framework helper utility for proposing code 
#5014 - Encapsulate waiting for write connection in Container.proposeCodeDetails
#3280 - Remove workaround in 'contextReolad.spec.ts' and 'upgradeManager.spec.ts' test around quorum proposal

@arinwt , @anthony-murphy - can you please take a look?

**Comment by agarwal-navin** [comment]
Tracked by AB#445
