### ISSUE TITLE
Remove branchId from code

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3428]
Fluid Framework code base has branchId arguments passed it from container to DDSs in load path.
This is done to support branching feature - ability to branch documents.
That said, this feature is disabled on multiple levels (and caused data correctness in the past).
Branching, if implemented in future, is very unlikely to be based on current implementation, for the following reason:
- branching (if part of same document in storage, i.e. file in SPO) does not need to leak to lower levels - this can be part of URI resolver / driver.
- any merging of long lived forks would require 3-way merge, relying on replaying ops will produce non-ideal, and in many cases not expected outcomes.
- if we rely on OPs for merging forks, we likely would expose this differently. We are looking at this area right now as part of "not losing data" direction, and most directions assume loading container at base (common) seq number and restoring container in a steate of "local non-submitted changes", to allow natural process of connection and syncing to do rebasing (of local changes) and merge.

Whoever has time should take a look at it.
If you do start work, please let others know

**Comment by ChumpChief** [comment]
With #4313 and #4358 this is as removed as possible until we bump the version.  The remaining work after the version bump is tracked with #4346.
