### ISSUE TITLE
Duplicate entries in FluidDataStoreRegistry ctor

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3434]
Places like FluidDataStoreRegistry do not validate that there are no entries with same names passed in.
While unlikely developers could make mistakes and such mistakes will be rather hard to debug if we do not raise them soon.
Need to look at other places like that and add asserts.

**Comment by danielroney** [comment]
Per discussion at milestone planning, moving un-projected issues to Next.
