### ISSUE TITLE
all examples download chromium

### ISSUE THREAD

**Issue by mattetti** [microsoft/FluidFramework#3491]
Samples have Puppeteer as a dependency and it downloads a full copy of chromium blowing up the node modules. The Brainstorm example has a node_modules of 625Mbs on my machine (Linux).

**Comment by tylerbutler** [comment]
Triage: We are leaving the puppeteer dep for examples, but it has been removed for Hello World. Our rationale is that the examples are intended to be more realistic, and testing is a part of that. The Hello World, on the other hand, is focused on getting something up and running quickly, and showing how testing works is not critical there.
