### ISSUE TITLE
Fluid Service documentation page

### ISSUE THREAD

**Issue by mattetti** [microsoft/FluidFramework#3493]
This is about: `docs/concepts/server/server.md`

* The documentation page doesn't explain anywhere that a Fluid service is a server type solution (aka backend) that needs to run on the internet.

* The drivers section doesn't link to anything allowing the reader to learn more (linking to GitHub is fine)

* The more information should be called "reference server implementation" and explain how to get routerlicious up and running locally using Docker (and link to GitHub for those wanting to build/tweak the image themselves)

**Comment by markfields** [comment]
@SamBroner I'm adding your assignment here, I had been chatting with Matt about this so he assigned it to me, but it's not something that's particularly on my radar to update, nor do I have much depth of knowledge here. Feel free to pass around further... :)
