### ISSUE TITLE
API: switching the Fluid service should be simpler

### ISSUE THREAD

**Issue by mattetti** [microsoft/FluidFramework#3496]
tinylicious is the recommended developer server and the API requires the usage of the `getTinyliciousContainer` API call, but using such a dedicated function call means that we  can't easily swap Fluid service making the API brittle and hard to discover.

Suggestion:

Move from something like this:

```ts
import { getTinyliciousContainer } from "@fluidframework/get-tinylicious-container";

async function start(): Promise<void> {
    const container = await getTinyliciousContainer(documentId, DiceRollerContainerRuntimeFactory, createNew);
}}
```

To something more like this:

```ts
import { containerRetrieval } from "@fluidframework/get-tinylicious-container";

async function start(): Promise<void> {
    const container = await containerRetrieval(documentId, DiceRollerContainerRuntimeFactory, createNew);
}}
```

Where both tinylicious and routerlicious exposes the same API to get a container (with potentially optional params or a config call)

**Comment by ChumpChief** [comment]
I think @SamBroner already satisfied this with #3610
