### ISSUE TITLE
SharedMatrix is linked from the docs but doesn't have API docs

### ISSUE THREAD

**Issue by mattetti** [microsoft/FluidFramework#3515]
https://fluidframework.com/apis/matrix/sharedmatrix/

Linked from https://fluidframework.com/docs/concepts/dds/#optimistic-data-structures

**Comment by tylerbutler** [comment]
Triage: We'd like to have a class description and some basic usage information in the TSDocs. Some of this info may already be in the package readme.

**Comment by tylerbutler** [comment]
@DLehenbauer are you working on this?

**Comment by curtisman** [comment]
@skylerjokiel assigning to you for tracking.

**Comment by tylerbutler** [comment]
This was fixed as far as I can tell.
