### ISSUE TITLE
SharedCell isn't documented but linked from the docs

### ISSUE THREAD

**Issue by mattetti** [microsoft/FluidFramework#3516]
https://fluidframework.com/apis/cell/sharedcell/ is linked from the DDS page and doesn't have a TSDoc.

**Comment by tylerbutler** [comment]
Triage: We'd like to have a class description and some basic usage information in the TSDocs. Some of this info may already be in the package readme.

**Comment by tylerbutler** [comment]
@ChumpChief are you working on this?
