### ISSUE TITLE
Name collisions are possible in snapshot (.chunks, .component)

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3542]
Blob with this name
```
const chunksBlobName = ".chunks";
```
is written in the root of container runtime tree, thus in the same namespace as data stores.
If data store with such name is created, it will cause corruption of the tile.

We need to isolate namespace of special blobs and data stores.
I believe (need to check) same goes with .component blob and DDs.
Within DDSs I believe things are correct (as .attributes is not colliding with DDS blobs as they are under "content" sub-tree), but need to check

**Comment by arinwt** [comment]
Closing this issue with PR #4485, because that PR allows for clients to read in the new format.
Opened another issue #4706 to track the work for writing in the new format. This must go in a release 2 versions later than the first to ensure compatibility requirements.
