### ISSUE TITLE
Can't view some parts of the Docs site on mobile

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#3559]
### Issue Category
- Other - Bug on mobile

### Details
Visiting https://fluidframework.com/docs/ on mobile, the TOPICS dropdown doesn't let me view the FAQ or Glossary:

![image](https://user-images.githubusercontent.com/12305068/92526185-e62b0e00-f1d9-11ea-8602-a806d3982f77.png)

**Comment by mattetti** [comment]
I found the issue looking at the template and opened a PR for this issue https://github.com/microsoft/FluidFramework/pull/3562 /cc @nmsimons

**Comment by mattetti** [comment]
@markfields can you check now please, the PR was merged

**Comment by markfields** [comment]
All good!
