### ISSUE TITLE
API page's content gets cut off on mobile 

### ISSUE THREAD

**Issue by TamineCM** [microsoft/FluidFramework#3560]
### Issue Category

- Other: Bug on Mobile 

### Details

Visiting https://fluidframework.com/api/ on Safari mobile, some of the content and background gets cut off. 

Image:
![image](https://user-images.githubusercontent.com/30443611/92526949-20e17600-f1db-11ea-92f0-a847e8d645b5.png)

**Comment by micahgodbolt** [comment]
looks more like the dropdown is spilling out than anything getting cut off

**Comment by micahgodbolt** [comment]
@TamineCM what version safari are you on? I tried a couple via browserstack and it seemed to work fine

![image](https://user-images.githubusercontent.com/1434956/92529794-02ca4480-f1e0-11ea-8d30-8f845ea8a6cb.png)

**Comment by micahgodbolt** [comment]
Issue is the API page on mobile. There are items in that list that are too wide for the width of the select, causing it to increase in width

**Comment by skylerjokiel** [comment]
I'm also seeing this. IPhone 11, version `13.6.1`

**Comment by micahgodbolt** [comment]
yeah, not an ios issue at all, just select content being too big. PR coming
