### ISSUE TITLE
Documentation Website Unreachable: 429 – Throttled

### ISSUE THREAD

**Issue by bramus** [microsoft/FluidFramework#3580]
### Issue Category

- Other

### Details

The website is unreachable: 429 – Throttled.

<img width="1229" alt="Screenshot 2020-09-09 at 10 23 49" src="https://user-images.githubusercontent.com/213073/92574135-02d14f80-f287-11ea-8e6b-83cd3b8a1b6d.png">

Somebody better turn the resource dials up to 11 ;)

**Comment by igorzaika** [comment]
I see the same in UK, apparently region specific, @SamBroner is checking with the Azure team.

**Comment by bramus** [comment]
Surfing from Belgium here. Still seeing 429 right now.

**Comment by xitter** [comment]
+1 from India.

**Comment by SamBroner** [comment]
Yep. We're looking at it now. Many regions are back up, but we'll update here once we're confident.

**Comment by aligoren** [comment]
> +1 from India. Intermittent load:
> <img alt="Screenshot 2020-09-09 at 4 27 57 PM" width="1577" src="https://user-images.githubusercontent.com/8026722/92590238-7d1ac780-f2b9-11ea-8fc7-a5375999b73f.png">

![image](https://user-images.githubusercontent.com/4205423/92612500-996f3200-f2c2-11ea-9f08-1eede165387c.png)

**Comment by SamBroner** [comment]
We have a provisional mitigation in place. We've passed all of our internal tests so far. Please let us know how it's working for you.

**Comment by bramus** [comment]
Works fine now. Thanks!

I'll leave this open for you to close if you see fit.

**Comment by igorzaika** [comment]
Fixed for me as well, thank you @SamBroner !

**Comment by SamBroner** [comment]
No problem. Also thanks to @tylerbutler
