### ISSUE TITLE
FluidFramework.com Playground exit full screen button not available in Docs/Source tab

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#3588]
If I got into full screen mode (either by clicking the button in the Canvas tab, or auto transition to it after a while in the content), I can't get out of it (exception using the escape button which is not discoverable), because the UI is missing in the Docs and Source tab.

**Comment by tylerbutler** [comment]
Triage: post launch "cleanup" bucket? Within the next week.

**Comment by micahgodbolt** [comment]
This is an issue in storybook itself. Logged an issue here https://github.com/storybookjs/storybook/issues/12820

**Comment by vladsud** [comment]
@micahgodbolt, any reason to keep this issue, given that's external?
Trying to keep our backlog clean :)
