### ISSUE TITLE
ProseMirror and codemirror examples: Desyncronization

### ISSUE THREAD

**Issue by andy-bond** [microsoft/FluidFramework#3591]
## Describe the bug

On the ProseMirror Example, it is possible to desyncronize the two Fluid Containers. 

Not only is this not supposed to happen, but there is also no indicator that the containers have become desynced.

![image](https://user-images.githubusercontent.com/10934345/92756166-90ca3a80-f35a-11ea-8afb-0fa24020a004.png)

### To Reproduce
1. Go to https://fluidframework-docs.azureedge.net/playground/?path=/story/react-demos-prosemirror--demo
2. In the left container, Click at the end of the text "Hello World!"
3. In the left container, Click the unordered list button
4. In the left container, Tap the "Enter" key
5. In the left container, Tap the "Enter" key again
6. Notice that the right-hand Fluid Container is no longer syncronized to the left container

### Expected behavior

I would expect desyncronization not to occur - however, I realize that there are times when this will happen. 

If it is inevitable that they desyncronize, it would be nice to show some indicator that the two containers have desynced.

**Comment by andybond006** [comment]
I believe the same issue occurs for the Draft.js editor as well. Not sure if you want that as a separate issue or modify the title of this one.

**Comment by anthony-murphy** [comment]
Thanks for reporting and filing this @andybond006 and double thanks for the great repro steps. I can get both issues to reproduce.  I think a single issue should suffice here.

**Comment by vladsud** [comment]
@SamBroner , @skylerjokiel - we need a plan to either address it or remove samples (or maybe document all limitations).
I think assessment is required in terms of - it's just a leaf bug, or the approach is wrong and we are going to see bugs like that in other areas.

I have not looked too deeply here, but CodeMirror & ProseMirror support OT natively, and in this case the right solution seems to be map it directly to Fluid ops (figure out what to do with summaries), but not try to map it to any existing DDS (like Sequence), as this only works if editor model is constrained by (can be mapped to) insert/delete/annotate operations (and that is not going to change in the future). In the later cases I'd assume that we would not have bugs like this.
