### ISSUE TITLE
API page is breaking mobile navigation

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/FluidFramework#3601]
![image](https://user-images.githubusercontent.com/1434956/92947988-916fd900-f40d-11ea-829b-a787528d2f36.png)

https://fluidframework.com/apis/

**Comment by micahgodbolt** [comment]
this is happening due to long words in the description (hello crazy long class names) and them not breaking. Need to either do a different layout that allows more room for those words, or possibly update css to word-break

**Comment by tylerbutler** [comment]
@micahgodbolt Are you still looking at this?

**Comment by micahgodbolt** [comment]
Here's an example of 2 lines of text, right next to each other, with words that simply won't fit on a single line

![image](https://user-images.githubusercontent.com/1434956/95878866-8cfb5080-0d2a-11eb-933e-8c8f5c65b853.png)


the package is already breaking due to having dashes in the package name, but the word LastEditedTrackerDataObject will not break without `word-break: break-word`.
