### ISSUE TITLE
Can't run "npm run build" within common or server packages due to a genver error

### ISSUE THREAD

**Issue by KRyan** [microsoft/FluidFramework#3606]
## Describe the bug
Running "npm run build" (or specifically, "npm run build:genver") fails within several common/ and server/ packages. 

### To Reproduce
1. In a cloned repository, "npm install" and "npm build".
2. Change directory to \common\lib\common-utils
3. "npm run build"

Expected: build to run
Actual: 
`'gen-version' is not recognized as an internal or external command,
operable program or batch file.`

Note: it also repros in \server\* directories such as \server\routerlicious\packages\services

### Expected behavior
Build to complete successfully

**Comment by tylerbutler** [comment]
@KRyan did you run npm i from the common-utils package dir? The common packages are not managed by Lerna so they're like standalone packages in the repo.

**Comment by KRyan** [comment]
@tylerbutler -- ah, thanks, that was the issue!  After running npm i in the appropriate directory, it works.
