### ISSUE TITLE
Continuously looping GIF is an accessibility problem

### ISSUE THREAD

**Issue by bmeersma** [microsoft/FluidFramework#3619]
On https://fluidframework.com/playground/?path=/story/welcome--page there is a continuously looping GIF which is a [WCAG 2.2.2](https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html) problem.

To solve the issue, add a pause button or stop the GIF loop after 5 seconds.

**Comment by tylerbutler** [comment]
This will be fixed by https://github.com/microsoft/FluidStorybook/pull/62.
