### ISSUE TITLE
The tree structure in the learning section doesn't seem to be accessible with a screenreader

### ISSUE THREAD

**Issue by bmeersma** [microsoft/FluidFramework#3621]
The tree diagram's structure doesn't seem like it is exposed to screen readers programmatically. https://fluidframework.com/docs/advanced/summarizer/

To fix the issue we can also represent the tree dialog as a multi-level unordered HTML list.

**Comment by tylerbutler** [comment]
@bmeersma Considering the protocol diagram here: https://fluidframework.com/docs/advanced/summarizer/#protocol

Is this what it would be in HTML?

```html
<ul>
 <li>root</li>
 <ul>
  <li>.protocol</li>
  <ul>
    <li>quorumMembers</li>
    <li>quorumProposals</li>
    <li>quorumValues</li>
    <li>attributes</li>
  </ul>
  <li>_scheduler</li>
  <li>DataStore_1</li>
  <li>DataStore_2</li>
 </ul>
</ul>
```

Can we make this a screen-reader only element?

**Comment by bmeersma** [comment]
@tylerbutler yes, that looks like what I was thinking. I'm not sure how to make it a screenreader only element, but I think that would solve the problem. Arnavi may have ideas about this.

**Comment by tylerbutler** [comment]
Related issue on the mermaid side: https://github.com/mermaid-js/mermaid/issues/1013
