### ISSUE TITLE
Architecture diagram is not properly accessible

### ISSUE THREAD

**Issue by bmeersma** [microsoft/FluidFramework#3622]
https://fluidframework.com/docs/concepts/architecture/

Alt-text does not convey the architecture of the Fluid framework, but instead states that the image is an architecture diagram. To fix this we could link to an accessible Visio diagram or provide alt-text that describes the contents of the image.

**Comment by tylerbutler** [comment]
@bmeersma Can you give me an example of describing the contents of the image with sufficient detail? I think I can fix other diagrams once I have a solid example.

**Comment by bmeersma** [comment]
@tylerbutler I would think something like this, the Fluid service is connected to a client which contains the Fluid Load and the Fluid Runtime (Container). The Fluid Loader contains document service factory, code loader, scopes, and UrI Resolver and the Fluid Runtime contains multiple Fluid objects and distrubted data sctructures.

This probably needs some work, but I think that level of detail would be helpful.

**Comment by micahgodbolt** [comment]
Going to kick this out to next. I know tyler is working on this a bit, but it's not a 1 off fix and will take a bit of time to get everything done.

**Comment by vladsud** [comment]
Really old issue. Any plan to move forward, or should we punt it?

**Comment by bmeersma** [comment]
@vladsud I don't think we can punt this. @tylerbutler can you please help drive this to closure? Thanks.
