### ISSUE TITLE
FluidFramework.com skip to main content function isn't working

### ISSUE THREAD

**Issue by bmeersma** [microsoft/FluidFramework#3624]
1. Load fluidframework.com
2. Tab
Select skip to main content
3. Observe that focus stays on the skip to main content element.

**Comment by tylerbutler** [comment]
@bmeersma Can you explain what should happen when the main content element is selected? Is the behavior on <https://code.visualstudio.com/> also incorrect?

**Comment by bmeersma** [comment]
@tylerbutler the behavior on code.visualstudio.com seems correct. When I activate the skip to main content function, I would expect the focus to move to a different region of the webpage, but on fluidframework.com the focus seems to stay in the same spot for me. If you turn on Narrator it's a bit easier to see the different I think.
