### ISSUE TITLE
DataObject initialization call is not guaranteed to complete before create promise is resolved

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#3628]
When creating a new DataObject instance via the runtime, the create method promises return before any async initialization logic is guaranteed to complete for DataObjects with initialization logic (see Aqueduct DataObjects). This can lead to the odd behavior where an intuitive usage of runtime APIs like the below:

  const dataObjectRuntimeChannel = await runtime.someCreationFlow();
  dataObjectRuntimeChannel.bindToContext();

Will result in bugs because ops submitted during initial component initialization (and thus seem like they should always exist during the rest of the DataObject lifecycle) are not actually captured in the bind/attach message for said DataObject. To clear up this confusion and avoid future bugs, either initialization should be guaranteed during the creation promise or APIs need to be renamed more clearly to reflect actual behavior.

**Comment by vladsud** [comment]
PureDataObjectFactory not awaiting DataObject creation (and skipping it by default). we do create object on init ([see here](https://github.com/microsoft/FluidFramework/blob/0076d7e0c23fffcf5f6df042a1f49a6838c1b111/packages/framework/aqueduct/src/data-object-factories/pureDataObjectFactory.ts#L177)), but we do not await **instanceP**

I think we should in such case (and in case of summarizer for summary block DDS, maybe we should consider dropping on-demand creation given it creates problems in multiple paths).

**Comment by tylerbutler** [comment]
@vladsud @leeviana How much pain is this causing at the moment? How critical is it to address this soon (say, within the next few weeks)?

**Comment by vladsud** [comment]
It's one line change really, and it causes potential data inconsistencies, so worth resolving soon

**Comment by leeviana** [comment]
Yes, it's a public API issue with data inconsistencies. We have "mitigated" this issue with careful orchestration of our base-container logic so it's not currently affecting FFX scenarios but it's still probably something of concern for the Framework in general :)

**Comment by vladsud** [comment]
Putting an await will block resolving internal to data store handles (like DDS handles). Need to design it

**Comment by vladsud** [comment]
Fixed
