### ISSUE TITLE
Synchronization of flowcharts/workflows/canvas elements

### ISSUE THREAD

**Issue by weedkiller** [microsoft/FluidFramework#3636]
## Feature
Hello, inside the web we have there are many free OSS like JsPlumb or other D3.js for flowchart process.

Using this we drive automation/assembly lines, which is based on a flow chart as the work flow manager from a website.

- [ ] Can we get a sample to sync and update the server side and other clients at the same time.
- [ ] How can we enable one display as edit and the others ad view only

**Comment by SamBroner** [comment]
Hey @weedkiller, can you add some more details to the scenario?

We have a few sync examples in the repository and in github.com/microsoft/fluidexamples. Do any of those examples meet your needs?

**Comment by tylerbutler** [comment]
@weedkiller I'd love to hear more about what you're imagining! As Sam mentioned earlier, we have several examples showing how to use the DDSes in the framework to replace or augment existing data models. We haven't explored diagramming specifically, but if you explore that scenario we'd love to hear about it.

**Comment by weedkiller** [comment]
Hello, please consider a use case may help, like a `class of teacher/students viewing an interactive flowchart` or a group of technicians following an assembly line flowchart on the web browser.

I would like to see a use case sample where, 

- [ ]  Students/Teacher wants update the diagram, and how is the next-state handled across the class/group.
- [ ]  Can we get a sample to sync and update or persist this back to the server side and other clients at the same time.
- [ ]  How can we enable one display as edit and the others ad view only

In SignalR this was easily understand with the hub model, but I could not find a full working sample to show how to handle this/diagrams and server side synchronizing with a Controller.

**Comment by weedkiller** [comment]
unresolved
