### ISSUE TITLE
Drafts: non-bound data stores might be part of the graph.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3647]
I think we have a big gap.

When serializing Drafts, we do not serialize non-bound data stores.
It's possible we have non-bound data store, but its handle is stored in a DDS that is bound to container and thus gets serialized.
So completely skipping non-bound data store, we might be creating broken links. I.e. when container is de-serialized, and someone follow links, it may end up with broken handle.

Note that this is not a problem outside of Drafts.
That's because when we invoke attachGraph() workflow due to some handle being attached, we traverse full graph and bind & attach all objects in this graph, including data stores that are part of this graph.

I do not know what's the solution here (need to think about it), but putting it on your plate.

**Comment by jatgarg** [comment]
@vladsud But deserialization of detached container also goes through the attach graph flow.

**Comment by vladsud** [comment]
Interesting, I missed that, you are right. Do we have UT coverage for this case? Specifically on serialization/ de-serialization path
If so, please lose the issue. Otherwise let's change it to track adding test coverage

**Comment by jatgarg** [comment]
I have 1 E2E test for this where handle of data store is store in root map of bounded data store and then we check that it is serialized properly. We can add more.

**Comment by jatgarg** [comment]
Closing this issue as we already have support as per the discussion. Also added more end to end tests for the same in reference PR.
