### ISSUE TITLE
Implement blob support for Drafts

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3648]
https://github.com/microsoft/FluidFramework/pull/3573/files implements blob support.
Initial implementation does not include implementation for the following:
1. Creation of blobs in detached container.
2. Code to correctly serialize & de-serialize Drafts (detached container)
3. Code to include blobs (from #1) in initial snapshot used to create a file.

Other designs are possible (including storage providing "staging" area for blobs, where blobs are uploaded as part of # 3, but before actual file creation, and storage "moves" blobs into file in some fashion).
We might need to think about them, but for simplest workflows (relatively small payloads), it's much better to use existing infrastructure and not add new concepts.
This might require some changes in existing implementation.

Note that the bare minimum here is
1. we consistently fail when uploadBlob fails in detached state. I.e. feature is not implemented, and it's obvious to developers that it's limited to detached case.
2. Uploads during Attaching state of container are waiting for container attach event before call is made to driver. I.e. we have container identify before calls are made

**Comment by SamBroner** [comment]
Note: This is not *required* any upcoming timeline, but it's a good to have for performance tracking. The expectation is that this will create a bunch of questions, rather than answer them.
@tylerbutler

**Comment by anthony-murphy** [comment]
related to #6128
