### ISSUE TITLE
Isomorphic performance

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#3654]
It looks like performance functions were added in Node 8.5+.
https://nodejs.org/api/perf_hooks.html#perf_hooks_perf_hooks_performance

Right now we are using performance-now for isomorphic `performance.now()` functionality.
We also have a reference to `performance.getEntriesByType()`.

Replace `window.performance` with `perf_hooks.performance` in case of Node.

**Comment by heliocliu** [comment]
Cool! So we can get rid of the performance-now polyfill as well

**Comment by tylerbutler** [comment]
@arinwt @heliocliu Would this be a good first issue for an external contributor?

**Comment by heliocliu** [comment]
@tylerbutler probably, but I believe Arin already began working on this and someone already checked in an isomorphic break that depends on this that needs to be resolved soon or backed out

**Comment by tylerbutler** [comment]
@heliocliu Thanks; makes sense.
