### ISSUE TITLE
Prepare for Webpack 5

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#366]
Webpack 5 is coming soon and we should make sure that Fluid is ready! One breaking change that stands out as a problem is the [removal of automatic node polyfills](https://github.com/webpack/changelog-v5/blob/master/README.md#automatic-nodejs-polyfills-removed). This is a great change, but it likely requires some work on the framework side, since we are currently relying on the fact that webpack was polyfilling node.js server APIs, like Buffer, on the client. 

Not sure what the right course of action here is, but options include removing these node dependencies (becoming truly isomorphic) or providing lightweight polyfills of our own.

**Comment by heliocliu** [comment]
Looks like #3719 resolved the last issue around node polyfills here? @christiango fyi

**Comment by christiango** [comment]
@heliocliu - have you confirmed that FF builds fine with webpack 5? We're still very behind on FF in our repo, so I haven't been able to confirm FF is compatible with webpack 5. I am re-opening the issue until we have confirmed that FF builds with webpack 5.

**Comment by heliocliu** [comment]
@christiango Thanks, I misunderstood the conversation around that PR to mean that you had already determined that to be the only issue left 🙃 my bad.

**Comment by christiango** [comment]
@heliocliu - I was able to get 0.26 container code to work with Webpack 5, thanks for all the hard work here!

However, our dev server is not working due to server-services-client's dependency on crypto and stream. Both of these come from jsonwebtoken


BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
 @ ../../common/temp/node_modules/.pnpm/jws@3.2.2/node_modules/jws/lib/sign-stream.js 4:10-24
 @ ../../common/temp/node_modules/.pnpm/jws@3.2.2/node_modules/jws/index.js 2:17-45
 @ ../../common/temp/node_modules/.pnpm/jsonwebtoken@8.5.1/node_modules/jsonwebtoken/sign.js 3:10-24
 @ ../../common/temp/node_modules/.pnpm/jsonwebtoken@8.5.1/node_modules/jsonwebtoken/index.js 4:8-25
 @ ../../common/temp/node_modules/.pnpm/@fluidframework/server-services-client@0.1012.1/node_modules/@fluidframework/server-services-client/lib/auth.js 6:0-36 26:11-19
 @ ../../common/temp/node_modules/.pnpm/@fluidframework/server-services-client@0.1012.1/node_modules/@fluidframework/server-services-client/lib/index.js 5:0-23 5:0-23
 @ ../../common/temp/node_modules/.pnpm/@fluidframework/local-driver@0.26.3/node_modules/@fluidframework/local-driver/dist/localResolver.js 11:33-82
 @ ../../common/temp/node_modules/.pnpm/@fluidframework/local-driver@0.26.3/node_modules/@fluidframework/local-driver/dist/index.js 14:9-35

**Comment by christiango** [comment]
Tagging @anthony-murphy since it looks like you have recently worked in this space. Is there any way we can break the jswonweb token sign dependency for local testing via local-driver?

Webpack 5 just released and by default it won't load at all. There is a workaround that we can apply here, but I would prefer landing on a solution that works out of the box for all partners using webpack 5 (which is now released)

**Comment by heliocliu** [comment]
We only use 3 APIs from jwt currently (verify/encode/sign), so it wouldn't be too bad to minimally abstract these APIs into a very thin shim in common-utils and find a browser friendly implementation if this is needed right away?

**Comment by christiango** [comment]
I wonder if we can use a different library from here:

jsrsasign looks decent: https://jwt.io/

I can try to see if this is a simple replace today

**Comment by christiango** [comment]
Resolving since I think we are there after getting rid of assert and jwt.
