### ISSUE TITLE
Add telemetry for snapshot size & number of blobs in writeSummaryTree

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3660]
We do have telemetry from runtime, but we do not have any in driver.
This means we do not have visibility into actual payload size, as well as effectiveness of blob reuse code.

**Comment by SamBroner** [comment]
Who is looking for this telemetry? When do we want to do this work?

**Comment by tylerbutler** [comment]
@vladsud Can you give us a little more info about this and who needs it?

**Comment by vladsud** [comment]
Whoever is interested in quality of framework, and container authors who want to better understand performance characteristics of their solutions.
In practical terms, it's me, Christian, and ideally - all OCEs.

**Comment by tylerbutler** [comment]
@vladsud Thanks. I didn’t know there was an open PR.

**Comment by vladsud** [comment]
There wasn't (at the time). Some issues are easier to address right away than keep tracking :)
