### ISSUE TITLE
Allow Container.SetAutoReconnect() be called in detached container state

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3666]
Today this function asserts that Container.resume() was called, which is impossible to do for detached container (and is part of container attachment process).
It's reasonable to say that hosting application should be able to set reconnection policy for detached container before attach is triggered.

We should consider allowing such call in load path as well.
Historically it was a bit tricky due to our API surface. But currently setAutoReconnect() is in the form of policy not action, so it's fair to say that policy can be set at any time.

**Comment by gmRr7** [comment]
R
