### ISSUE TITLE
Map DDS has dependency on "path", which doesn't exist in the browser

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#3667]
## Describe the bug
The map DDS has a dependency on the path node module in directory.ts, which forces a polyfill to be included by webpack for path. Can we remove or replace this dependency with something that is browser compatible? 

### To Reproduce
1. Bundle the Map DDS in webpack and set `node: { path: false}` in the webpack config
2. Webpack emits an error of the following form "Can't resolve path'

### Expected behavior
It should bundle in Wepack 5

**Comment by christiango** [comment]
If we're confident the unit tests for directory are exhaustive, I can take a stab at this. I'm afraid to break things since I haven't actually used ShareDirectory before, but the change doesn't seem too complicated

**Comment by tylerbutler** [comment]
@heliocliu Is this covered by isomorphic work that you're doing?

**Comment by heliocliu** [comment]
@tylerbutler nope, wasn't part of it.
