### ISSUE TITLE
error in  '@fluid-internal/end-to-end-tests' during 'npm run build'

### ISSUE THREAD

**Issue by Ethernetz** [microsoft/FluidFramework#3695]
## Describe the bug
Running "npm run build" fails and gives error

### To Reproduce
1. 'git clone https://github.com/microsoft/FluidFramework.git'
2. 'cd FluidFramework'
3. 'npm install'
4. 'npm run build'

### Expected behavior
build to run

### Actual

@fluid-internal/end-to-end-tests: [build:esnext] ../../../node_modules/@fluidframework/container-runtime/dist/summarizer.d.ts(133,9): error TS2416: Property 'IFluidLoadable' in type 'Summarizer' is not assignable to the same property in base type 'ISummarizer'.

![image](https://user-images.githubusercontent.com/10564713/93806179-c7d00400-fc16-11ea-9cd2-644bcd49cccc.png)

**Comment by tylerbutler** [comment]
@Ethernetz I think this was fixed by @wes-carlson in #3696. If you are still having problems please let us know.

**Comment by Ethernetz** [comment]
After pulling from origin, I now get this error

`@fluid-internal/end-to-end-tests: [build:esnext] ../../../node_modules/@fluidframework/core-interfaces/dist/fluidObject.d.ts(9,18): error TS2320: Interface 'IFluidObject' cannot simultaneously extend types 'Readonly<Partial<IProvideFluidDataStoreFactory>>' and 'Readonly<Partial<IProvideFluidDataStoreFactory>>'.`

![image](https://user-images.githubusercontent.com/10564713/93920989-f1a02e00-fcdd-11ea-8586-457bacd4ef8b.png)

Any ideas?

**Comment by Ethernetz** [comment]
Works after deleting and reinstalling directory

**Comment by tylerbutler** [comment]
@Ethernetz Glad to hear you're sorted!
