### ISSUE TITLE
Investigate whether we can use ES modules with Node, maybe stop building commonjs

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#3745]
I'm not 100% clear what the level of support is (e.g. experimental vs. production, requires a flag to enable or not, maybe changed in Node 14, etc.).  If we can, then maybe we can stop building commonjs target.

https://nodejs.org/api/esm.html#esm_introduction

**Comment by vladsud** [comment]
I'm hearing that this transition is not trivial. Unless we are planning to do it in next 6 months, I'd propose to close this issue.

**Comment by ChumpChief** [comment]
Seems fair.
