### ISSUE TITLE
Tighten .npmignore configurations

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#3747]
Currently, our .npmignore files exclude very little.  This results in larger-than-necessary npm packages, including things like the .ts files, README files, tests, various config files, etc. which folks installing our packages likely have no use for.  We should scope these out more cleanly so that our npm packages only contain useful contents.

**Comment by tylerbutler** [comment]
I'd prefer we use an _inclusion_ list rather than an exclusion list.

**Comment by curtisman** [comment]
We would like to keep the README.md so that user can find it without going to the repo.
We need to keep the source for user debugging via source map back to *.ts.

The only thing probably are tests.
