### ISSUE TITLE
Add UT step to Tinylicious CI

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#3757]
https://github.com/microsoft/FluidFramework/pull/3756 added a few tests to unblock others from writing tests, but they don't run in the CI.

**Comment by markfields** [comment]
What we do here will depend on how Tinylicious is built and packaged.  Right now it's a standalone package in the repo, but @anthony-murphy has suggested moving it to the server repo - but that also has some drawbacks wrt the Docker image. So still open discussion.

It's not a ton of work to just add the step as-is, but if this other conversation converges soon it would be better to let this be a follow-along at that point.

**Comment by tylerbutler** [comment]
@markfields Do you think we need to focus on Tinylicious during October?

**Comment by vladsud** [comment]
Really old issue. If we have no plan here, should we punt?
