### ISSUE TITLE
Add links to docs and projects from the community

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#3761]
The website and root README would benefit from a section of links to docs and projects from the community. This would be a way to cross-promote awesome community content. Some things we could link to:

- https://medium.com/@kurtberglund/deploy-and-run-your-own-fluid-framework-service-8c82294e74b7
- https://medium.com/@kurtberglund/how-a-fluid-framework-service-works-c82fe9f78ae9

**Comment by micahgodbolt** [comment]
this is a nice to have, pushing out to next
