### ISSUE TITLE
TypeError: Cannot read property 'eventName' of undefined

### ISSUE THREAD

**Issue by wes-carlson** [microsoft/FluidFramework#3779]
## Describe the bug
`PerformanceEvent` in `packages/utils/telemetry-utils/src/logger.ts` contains this code:
``` ts
  public reportEvent(eventNameSuffix: string, props?: ITelemetryProperties, error?: any): void {
        if (!this.event) {
            this.logger.sendErrorEvent({
                eventName: "PerformanceEventAfterStop",
                perfEventName: this.event!.eventName,
                eventNameSuffix,
            });
```
This non-null assertion will always throw here since we know `this.event` isn't defined. I have seen this error in tests that are failing for other reasons.

### Expected behavior
This should either not throw in this case or throw a more useful error.

### Logs
```
(node:31699) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'eventName' of undefined
    at PerformanceEvent.reportEvent (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:411:43)
    at PerformanceEvent.end (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:394:14)
    at container.load.finally.then (/home/wes/fluid/packages/loader/container-loader/dist/container.js:139:27)
```

**Comment by tylerbutler** [comment]
This is high priority since it affects the OCE's ability to investigate issues in prod by creating noise in the telemetry system.

**Comment by markfields** [comment]
As usual, can't assign to myself 😠

**Comment by vladsud** [comment]
In addition to fixing telemetry (not hitting undefined de-reference), let's look at Contanier.load() flow and how we can hit this issue.

The error suggests that cancel() was called before end() in .then handler.
This suggests that "close" was invoked, and then load() succeeded.
The code (other that unhandled exception) works correctly. I'd say two things needs to happen:
1. We need to understand why closing container does not fail load() and if it should fail load.
2. Irrespective of that, Container.load (static version) likely need to account for that flow and not result in unhandled exception somehow.

**Comment by markfields** [comment]
@vladsud - Let's have a separate issue for that, I'm going to merge my PR tonight.
@wes-carlson - Can you collect logs from a failed test run that hits this error? Looking for the cancel event that happens first, in case there's any insight there (e.g. callstack)

**Comment by markfields** [comment]
https://github.com/microsoft/FluidFramework/issues/3936 is now tracking the specific case under `Container.load`
