### ISSUE TITLE
Failures during data store load are not properly handled / logged

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3783]
Failure during op processing during data store loading are not recorded in Fluid telemetry and leave objects in partially constructed state. this is based on observing bits on 0.25. I did some work here on second part, but not sure if it's in 0.25, and if it's sufficient.

Here is an example where we throw this exception:
                    assert(!this.contexts.has(id), "Unexpected attach channel OP");

Stack:
    at T.process (officeContainer.js:formatted:13016)
    at Z.bindRuntime (officeContainer.js:formatted:9997)
    at Function.load (officeContainer.js:formatted:12849)
    at u.instantiateDataStoreWithInitialState (officeContainer.js:formatted:13603)
    at u.instantiateDataStore (officeContainer.js:formatted:13600)
    at Z.realize (officeContainer.js:formatted:9864)
    at async getDataStore (officeContainer.js:formatted:4683)
    at async o.handleRequest (officeContainer.js:formatted:4583)
    at async St (tableroComponent.js:1)

Second part of the problem is that we throw exceptions from request() handler. All errors, including exceptions (likely at all levels in the stack) should be handled uniformly, similar to how we force all functions returning promises to be async and convert exceptions to rejected promises. Currently we rely on status codes, if we follow same path we need to convert exceptions to error code. Ideally IMHO we should move away from error codes and use built into language constructs (i.e. exceptions converted to rejected promises).

**Comment by markfields** [comment]
@vladsud - let me know when you're working on this, I'd love to learn more here and work together on a fix.

**Comment by vladsud** [comment]
@leeviana , I believe there is addressed in loadAndTrackComponent() - the code is now wrapped in try/catch around loading data store. Can you please double check me here and reactivate if I got it wrong?

I do not see any other outstanding work - I made loading code safer / catching all errors and propagating them down in earlier changes.

**Comment by leeviana** [comment]
Yes, in our container's handlers we now do this properly. As long as the handler load paths/other load paths in Fluid also wrap this appropriately we should be good :)
