### ISSUE TITLE
Fluid repo allows throwing strings (and likely other objects)

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3807]
Searching for "Not found" yields things like
'''
return Promise.reject("Not found");
'''
in many places.
The right behavior is to throw only Error objects, as it allows better tracking (capturing of callstack) and debugging.
If I'm not mistaken, there is eslint plug in for that that needs to be enabled and all issues fixed.

**Comment by tylerbutler** [comment]
I think the relevant ESLint rule is [prefer-promise-reject-errors](https://eslint.org/docs/rules/prefer-promise-reject-errors).

**Comment by vladsud** [comment]
Nope, it's [no-throw-literal](https://eslint.org/docs/rules/no-throw-literal)

**Comment by curtisman** [comment]
no-throw-literal is for throw and prefer-promise-reject-errors is for Promise.reject.  no-throw-literal is already enabled, so I am enabling prefer-promise-reject-errors now.
