### ISSUE TITLE
Accessibility: [MAS2.4.3]: Keyboard focus is getting lost after invoking the links under 'In This Article'.

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#3814]
**Build details:**

**OS Version:** 2004(20221.1000)

**Edge Dev Version**: 87.0.654.0 (Official build) dev (64-bit)

**URL:** <https://fluidframework.com/docs/>

**Repro Steps:**

1\. Navigate to any link under 'In This Article' at the right side of the page and invoke it.

2.Now observe the keyboard focus.

  
**Actual Result**  
Keyboard focus is getting lost after invoking the links under 'In This Article'.  

  
**Expected Result:**  
Keyboard focus should not be lost after invoking the links under 'In This Article'. It should fall on the respective link section which was invoked.

  
**Note**:

This issue is observed in all the given links as well-

https://fluidframework.com/docs/get-started/quick-start/
https://fluidframework.com/docs/get-started/tutorial/
https://fluidframework.com/docs/get-started/examples/
  

**Note**: Marking this as low impact as the user is able to focus on the link section after pressing tab.

  
**User Impact:**  

Users with motor impairment who are dependent on keyboard will face difficulty in understanding the flow of the application.

  

**MAS Reference:**

**MAS 2.4.3 - Focus Order**

**Comment by micahgodbolt** [comment]
These 'in this article' links are anchor tags that link to specific sections of the page. In this case, the page reloads and the focus is placed on that section linked to. So it seems that these links are working as expected. 

https://fluidframework.com/docs/#next-steps is a link to the docs page with focus placed in the 'next-steps' section of the page. 

This is also consistent with the vs code docs site which uses the same theme https://code.visualstudio.com/Docs#first-steps

**Comment by micahgodbolt** [comment]
![docs](https://user-images.githubusercontent.com/1434956/95789735-e9ab2c80-0c92-11eb-8c15-26db4ce946b8.gif)

I believe this is expected behavior. Click on section and focus moves to content. Subsequent tabs move you through the content.
