### ISSUE TITLE
Provide a way to download the full opstream directly from the fluid debugger UI

### ISSUE THREAD

**Issue by KRyan** [microsoft/FluidFramework#3819]
## Feature

**Describe the solution you'd like**

From the Fluid Debugger UI, we should add a link to download the full opstream as json.  

Sometimes developers need to examine the full opstream for a document.  The Fluid Debugger provides a quick visual way to play op-by-op, but it's common to want to view the full opstream side-by-side while doing this.  It is possible to download the full opstream via the fetch-tool, but this requires the developer to have an active repo clone, run a tool to fetch keys, and run on the command-line locally.  Iit would be much simpler for most developers to press a button from the fluid debugger UI. So this feature would enable more efficient bug investigations and empower devs to examine the effect of their features more easily.  

**Existing work**
/packages/tools/fetch-tool

**Describe alternatives you've considered**
Engineers can just use the fetch-tool -- but it has a higher barrier to entry for the reasons mentioned.

**Comment by tylerbutler** [comment]
@KRyan Did you assign this to yourself because you are working on it?

**Comment by KRyan** [comment]
Fixed with #3827
