### ISSUE TITLE
Discrepancy between container.serialize and loader.rehydrateDetachedContainerFromSnapshot

### ISSUE THREAD

**Issue by aboktor** [microsoft/FluidFramework#3832]
## Feature
**Is your feature request related to a problem? Please describe.**

There is a discrepancy between the container.serialize() return type and the loader.rehydrateDetachedContainerFromSnapshot(). The former returns a string while the latter accepts an ISummaryTree.

**Describe the solution you'd like**

I think both should be ISummaryTree with serialization/deserialization left to the host to handle

**Existing work**

Nothing I'm aware of.

**Describe alternatives you've considered**

This doesn't block the e2e flow but requires hosts to depend on an internal implementation detail (that .serialize() returns a JSON.stringify of an ISummaryTree).

**Additional context**

None

**Comment by aboktor** [comment]
@vladsud @jatgarg fyi

**Comment by aboktor** [comment]
I should add that this should probably be consistent with OdspDocumentServiceFactory.createContainer

**Comment by jatgarg** [comment]
@aboktor Do we need to cherrypick this in release/0.27.x
