### ISSUE TITLE
Consolidate duplicate code on fetching ops

### ISSUE THREAD

**Issue by KRyan** [microsoft/FluidFramework#3833]
## Work Item
We have at least three locations where we asynchronously fetch ops: the fluid-fetch tool, the fluid debugger (as of PR https://github.com/microsoft/FluidFramework/pull/3827), and the DeltaManager itself.  We should consolidate. 

**Describe the outcome you expect**
Need a unified way to asynchronously retrieve ops in a performant way with appropriate retry logic and guards against server throttling. 

**Approach**
We could either use events or es2018 async Generators.  (Since we no longer support old Edge, we can take a hard dependency on es2018.)

**Additional context**
See the discussion in the PR here: https://github.com/microsoft/FluidFramework/pull/3827#discussion_r499705975

**Acceptance criteria**
Duplicate code references are replaced.

**Comment by vladsud** [comment]
This is already done. Driver API is changed to ask for all ops at once, and it does proper retries and back off logic (as part of driver implementation).
Let me know if I miss something.
