### ISSUE TITLE
Formalize ODSP nonce as ContainerSessionId

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#3865]
## Feature
The odsp driver uses an optional nonce field to disambiguate clients across the shared web socket. There are cases where other layers of the stack would like to identify a container session across client ids. It's possible we can unify the nonce implementation with the concept of a client session id. I envision this id being included as part of the join message sent by the server such that container sessions can be identifies in the op stream.

**Comment by vladsud** [comment]
@GaryWilber, @marcmasmsft - any chance you can help driving it across SPO/PUSH?
I.e. it's easy for us to provide containerID (as an example) to all SPO APIs, such that server (if needed) could stitch all events together and track user across API calls. We would need someone on your side to design that (i.e. tell us how to propagate this info - it can be as simple as query param / header on all fetch calls, and nonce on socket connection, or something else).

**Comment by GaryWilber** [comment]
I'll let Marcelo speak about the SPO side of it.

For Push, we could reuse nonce depending on what the string is. If we use containerId, we need to be sure that the container will only be connecting with a single client at a time. So it might be cleaner to add a new property to the `IConnect` message such as `containerId` or `correlationId`. And we would start logging that in the push telemetry. 
Sounds like the goal is to have some unique identifier that let's us correlate events between the SPO <-> FFX <-> Push, so `correlationId` sounds like a good fit for it.
