### ISSUE TITLE
API pages are missing events

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#3893]
Our API docs don't show any event information. For example, see: https://fluidframework.com/apis/cell/isharedcellevents/

This is the definition of the interface:

```ts
export interface ISharedCellEvents<T extends Serializable> extends ISharedObjectEvents {
    (event: "valueChanged", listener: (value: T) => void);
    (event: "delete", listener: () => void);
}
```

And this is what's displayed on the site:

![image](https://user-images.githubusercontent.com/19589/95619315-499b9c00-0a23-11eb-946b-4e7eea5d8036.png)

Not very helpful.

**Comment by SamBroner** [comment]
@tylerbutler can you drive who owns this?

**Comment by vladsud** [comment]
@tylerbutler - any update / action plan to address it? It's rather old task with no action

**Comment by tylerbutler** [comment]
@vladsud Good callout. This is on my list of next things in the API docs. I'll update the milestone. We don't have a plan but we will.

**Comment by tylerbutler** [comment]
This is resolved: https://fluidframework.com/docs/apis/fluid-framework/isharedmapevents/
