### ISSUE TITLE
Investigate removing whatwg-fetch & isomorphic-fetch so it doesn't get downloaded by the livesite

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#3927]
Successor of #2185

npm run bundle-analysis:collect will put the bundle size analysis into the artifacts folder. whatwg-fetch represents 6.96K of parsed size there.  isomorphic-fetch doesn't represent any significant amount of size, but we should see if it can be removed entirely as well because it's an implementation of a browser api for node.

We should:
-Investigate how much of this library is actually used within the codebase
-In the case that only a small proportion is used, we should abstract the used APIs into our own implementation into common-utils and remove our dependency on this library to reduce the bundle size. #2450 tracked how this was done for another library.
-OR, if an equivalent library is already available that accomplishes the size issues, evaluate using that instead.

**Comment by curtisman** [comment]
I think we should switch to node-fetch, which is isomorphic already.
