### ISSUE TITLE
Delay load container functionality that isn't needed for initial load

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#3928]
Successor of #2185 (more context in original issue)

Delay loading container functionality that is not needed for the initial load.  In particular, the chrome coverage report shows that there is a bunch of code around summarizing that is not needed in the initial render and is showing up as unused.  Depending on when that code does get used and its size, this may mean immediately async queuing the download or downloading on demand.

**Comment by vladsud** [comment]
@heliocliu, @arinwt - we should either have a plan here or punt.
Bundling is something that container author controls (not FF), so other than laying out code in certain way and providing some info to container developers on what functionality / packages to split into separate chunks, I'm not sure what else we can do.
Is is the expectation that we will use dynamic imports in our code and define "summarization" chunk?

**Comment by heliocliu** [comment]
@vladsud @arinwt Given the context of the original issue my vote would be to punt because there isn't already a plan in this area nor does it seem we're going to invest in making one any time soon.  Optimization around chunking on the ffx side doesn't sound trivial, and it's not clear at the moment this is the best way to approach the broader issue.

**Comment by vladsud** [comment]
Ok, closing. We can always reactivate once we have more concrete plan here.
@christiango - FYI, in case you disagree (or could more clearly articulate expectations and priority)
