### ISSUE TITLE
remove snapshot() path from Container

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3929]
Only summaries should be used.
There are some places (DDS) where we still use "snapshot" terminology & types - we should change that to use summaries.

As part of it, we should remove / move to r11 driver(s) all GIT specifics like FileMode and remove them from protocol-defintions.

**Comment by vladsud** [comment]
@arinwt - FYI

**Comment by vladsud** [comment]
I'm sure there are duplicates of this item :)
The most challenging part here would be fixing tooling, i.e. replay tool. It's a must to maintain it (tests would fail otherwise). We either need to move it to summaries, or do a conversion somewhere for it to still get snapshot when runtime talks summaries.

**Comment by ssimic2** [comment]
Given we have completed some of the work around old snapshots, it may be good to time redefine scope of this ticket. And close it if needed.

**Comment by agarwal-navin** [comment]
Adding @scarlettjlee to this since she is working on related topic - https://github.com/microsoft/FluidFramework/issues/8460

**Comment by scarlettjlee** [comment]
The DDS work is done and I created a separate task for moving git code from protocol-definitions (#9003). So this issue should just be for removing snapshot from Container.

@ssimic2, do you want to keep this open until you do the removal after the deprecation? Otherwise we can close.
