### ISSUE TITLE
Prepend error_ to telemetry event properties populated from an error object

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#3931]
## Feature
**Is your feature request related to a problem? Please describe.**
When looking at the logs, there's no immediate way to tell where the data in a particular column came from, since we merge the properties of given `event` and `error` objects in [prepareErrorObject](https://github.com/microsoft/FluidFramework/blob/7e3b5ce6b2820ef1a3610cdb9ba716f6bcebc9ba/packages/utils/telemetry-utils/src/logger.ts#L53).

**Describe the solution you'd like**
Proposed solution would be to update `prepareErrorObject` to prepend `error_` to property names copied over to the `event` object from the `error` object.

**Comment by markfields** [comment]
@vladsud, @wes-carlson, @curtisman - Interested in your thoughts on this proposal. Thanks.

**Comment by vladsud** [comment]
I'm not sure it would be more readable.

for example, from this code, I'd not expect to search for error_ properties in telemetry (from https://github.com/microsoft/FluidFramework/pull/3900):
```
                        const error = {
                            errorType: ContainerErrorType.dataCorruption,
                            message: "Two messages with same seq# and different payload!",
                            clientId: this.connection?.details.clientId,
                            sequenceNumber: message.sequenceNumber,
                            message1,
                            message2,
                        };
                        this.close(error);
```

+ @arinwt as well

**Comment by markfields** [comment]
Well we already have the convention (in our primary 1P data pipeline) of adding Data_ in front. And we already convert the `message` field from that object to a property called `error` in telemetry. So I don't think this is much of a stretch.

The problem I'm trying to solve is not quite what I would call "readability" but rather "tracability". When I'm looking at the log output, I'd like to find the line of code that generated that data.  I think learning that `error_sequenceNumber` maps to `sequenceNumber` property set on the error object passed to the logger is not bad.  And coming back to the error message example, then `error_message` maps back to error's `message` property - this is clearer to me than `error` property mapping back to error's `message` property.

**Comment by vladsud** [comment]
Data_ is Aria implementation detail - all custom properties come that way.
Just to make sure it's clear - we will get Data_error_sequenceNumber.

**Comment by markfields** [comment]
There doesn't seem to be consensus on this proposal and it's not a priority right now, closing.
