### ISSUE TITLE
"Parent summary does not exist to reference by handle" error with 1300+ hits  from 10/13 to 10/15

### ISSUE THREAD

**Issue by chensixx** [microsoft/FluidFramework#3949]
## Describe the bug
I was looking at any errors popping up recently and this one has the most hits. Almost all in the same session with the same document. Investigating now. And the hits increased since yesterday.

### Logs
In the past 2 days, 401d9e8a-145b-44d4-ac11-aa08133f91e6 has 330 hits
189e28e2-065a-4a7d-903d-4ef5f009d82b had 1000+ hits, both in the same doc.

**Comment by skylerjokiel** [comment]
@chensixx , we shouldn't be tracking Microsoft product related issues in the Fluid Framework open source issues. Please track this in the FFX repo and open targeted bugs in the Fluid Framework repo.
