### ISSUE TITLE
New load flows need a way for container to "hook" into them

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#3953]
Today the Fluid Framework code is moving towards using handles instead of URLs. However our container is blocked from moving all of our component references to handles because loading using handles currently goes through a different load path that does not allow our additional base container load logic to run.

During component load, we log telemetry and also connect components to each other via generic data request processor systems (used for triggering commanding surface, getting discover data and previously powering the formula component), so we either need a hook into the default load process or for the default load process to respect our handle logic.

@agarwal-navin @vladsud

**Comment by vladsud** [comment]
I believe right way of doing it involves couple things:
1. Components of "eco-system" (whether it's Office eco-system) need to require some "central authority" object to be passed to them (more on that later). This is optional / can be done later, as you can use /services/... requests for now to get to it.
   - On component creation, handle to # 1 is written out for future use
   - on load, it's resolves to have an object in hand.
3. All components of given eco-system use same base-class (implementing policy) or at least implement same policy:
   - on load, get their hands to # 1
   - register itself with it. That involves whatever handshake eco-system requires.

I do not see any other solution that results in proper composition.
I.e. the scenario that we need to be solving is "I'm building a set of objects with certain assumptions, policies, how do I make it work and compose into bigger system (where bigger system is another set of objects, eventually rooting in container):

The problem should be phrased in context of "how do I get to root / root has to implement certain policy" (here root - container) as that does not compose across multiple eco-systems with different requirements.

First, we need to agree on direction, then break it into work items based on identified gaps, if any.

**Comment by vladsud** [comment]
One more thing to add: whether handles are used or not, you do not control when data store and data object is loaded.
I.e. process of "resolution" may load it, or may return already loaded object.
Handles do not change anything here, only data object / data store themselves know when they are loaded. 
So changing to handles has no impact on existing workflows, but it would be really great to actually move from centralized policy system to something that can compose and be able to use it in other containers.

**Comment by leeviana** [comment]
I think we can get to the point where we inject a "load wrapper" and "create wrapper" service of some sort into components on load. However this would probably want to happen with the provider pattern which I believe we can't currently hook into until we can figure out how to introduce provider support from the container, not just host scope. Is anyone looking into this?

Related: https://github.com/microsoft/FluidFramework/issues/3799

**Comment by leeviana** [comment]
Can we remove the requiring more information tag so this doesn't get autoclosed? :) Also, good news, Justin on our team is going to be ramping up in the providers/services space so hopefully we'll be getting some traction on dependency injection from container -> components soon. Please work with him to help get started here!

**Comment by leeviana** [comment]
We had an ongoing email thread in which it was stated that handle.get() should go through our load flows. I tested this in our repo and this is not the case today. Should I open up a separate issue for this or can we reuse this issue? (since it's the same need/scenario)

**Comment by vladsud** [comment]
@leeviana, framework will not be adding any global things, we will only remove over time most global things.
Players in the system should not ask for things, they should be provided things. I.e. components participating in consumer/producer eco-system should call into "manager" of that consumer/producer eco-system on load and register themselves with it. Components can get to such manager via two ways:
1. (Ideal) it's provided to it on construction, and component serializes handle to such manager for later use.
2. (not ideal, but maybe used for staging): there is hard-coded URI path in container to ask for it.

But we will not be adding global hooks to intercept loading.
This goes against core principles of building reusable eco-systems. Imagine that we have another repo exactly like Bohemia with exactly same requirements, but slightly different contracts. And now we want to use components form one repo in another, but both of them want to control everything in container. That will never work.

Let's chat about it more

**Comment by leeviana** [comment]
The reason we need a way to look into the loading process is precisely to avoid what you mentioned with components wanting to control things in the container. Today we do not have container specific code in components, but we do want to have container level insight/hooks into loading. The only way to do that without touching individual component code of every component we host (unscalable, think about 3rd party components we have no control over) is to have an invisible ecosystem hook/concept that runs outside of the component level boundary.

**Comment by leeviana** [comment]
I opened another issue related to not being able to use the provider pattern recently and Tony answered. This may help us eventually transfer from solution 2 to more of a solution 1 pattern as suggested by Vlad. This is a recent development so we still need to try it out, but it may help.

**Comment by agarwal-navin** [comment]
@leeviana  Can you please share the other issue here?

**Comment by leeviana** [comment]
Ah yes, here: https://github.com/microsoft/FluidFramework/issues/6769

**Comment by vladsud** [comment]
Closing all old issues in github. All the work is tracked in ADO now.
