### ISSUE TITLE
Out of memory cause by deep clone message

### ISSUE THREAD

**Issue by qianfeiqianlan** [microsoft/FluidFramework#3956]
## Describe the bug
When receive a op message(eg. add a SharedMap into SharedObjectSequence), processMergeTreeMsg (sequence.ts: 612) will be called. It will cloneDeep message.

https://github.com/microsoft/FluidFramework/blob/8e642efc86f534a2afa9f7170c88bae70e438050/packages/dds/sequence/src/sequence.ts#L612

And if [**message.contents.seg.items**] type is a **RemoteFluidHandle[]**, the **routeContext.runtime** will be clone.

It seems will cause two issues,
1. will clone **routeContext.runtime.context.container._deltaManager.connection._details.initialMessages**, it will be throw **'initialMessages called twice'** error [issues/3938](https://github.com/microsoft/FluidFramework/issues/3938) and [issues/3707](https://github.com/microsoft/FluidFramework/issues/3707)
2. will alloc a lot of memory (for my test case, It's **500 times** more than no-cloning the routeContext.runtime at least)
 

### To Reproduce
1. at client A, add SharedMap into SharedObjectSequence
2. at client B, monitor memory used, it will increase high-speed

### Expected behavior
not use a lot of memory when receiving an op

### Some memory alloc compare when clone or not clone
clone (2050 ContinerRuntime object will be generated):
![Screen Shot 2020-10-16 at 6 15 24 PM](https://user-images.githubusercontent.com/12892568/96253885-f60eec80-0fe6-11eb-960f-76e50e971695.png)

not clone (only 4):
![Screen Shot 2020-10-16 at 6 37 53 PM](https://user-images.githubusercontent.com/12892568/96254029-32424d00-0fe7-11eb-8a7c-80eec1478a9c.png)

For my test case, I modify cloneDeep source code to skip clone 'routeContext', I have no clear idea to fix that, cloneDeepWith? or delete routeContext?

**Comment by anthony-murphy** [comment]
Thanks @qianfeiqianlan. I should be able to get to this next month. The specific fix is fairly trivial, i think we can just shallow clone the message `stashMessage = {...message}` as we really only care about modifying the refseq, and then wholly replace the content below. In my mind the more important thing here is to add some tests for this scenario, which is likely more work than the fix it self.

**Comment by qianfeiqianlan** [comment]
yep, cannot agree with more. keep quality is the hardest.
