### ISSUE TITLE
Introduce the concept of root / non-root DDS

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#3970]
We need the concept of root and non-root DDS similar to data stores. This will be required for collecting individual DDSes within a data store. Root DDSes will be considered as referenced and hence not collectible. We will start from root DDSes and iteratively find out other fluid objects that are referenced.

**Comment by vladsud** [comment]
@agarwal-navin, can you please glance and comment on what's remains here. Or should we close it as done?

**Comment by agarwal-navin** [comment]
This is tracking the concept of `root` in DDS not data stores (I am guessing that's what you assumed?). We still need this in order to start collecting DDSs.

**Comment by agarwal-navin** [comment]
This is still required and will be done some time next year.

**Comment by agarwal-navin** [comment]
Tracked by AB#374
