### ISSUE TITLE
Fetch-Tool should support custom UrlResolvers

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#3990]
## Feature
**Is your feature request related to a problem? Please describe.**
Today you have to hard-code every UrlResolver you want Fetch-Tool to support. This is unwieldy and doesn't scale, and should be replaced with a plugin model.

**Describe the solution you'd like**
@curtisman had a good idea:

> you can design the plugin model by presence of package of a certain name pattern, and the tool will dynamically load in those packages.

So as long as the fetch-tool and the custom url resolver plugin are installed globally, it will work.  "Convention over configuration" as @tylerbutler pointed out.

**Additional context**
Url Resolving logic for the tool happens [here](https://github.com/microsoft/FluidFramework/blob/6f9ada6d46ed6df17a94ef9f956171ac8ba1003d/packages/tools/fetch-tool/src/fluidFetchInit.ts#L116), as of now. It simply loops over the list of hard-coded Resolvers that are supported until one successfully resolves. Instead of the hard-coded list, the list would be dynamically populated based on which packages are found to be installed.

**Comment by markfields** [comment]
Btw when we talk about installing fetch-tool globally, I'd like to rename it to Fluid Fetch, i.e. package name `@fluidframework/fluid-fetch`. It's a useful tool that 3P devs in our OSS community would want to be able to use as well - so getting the readme etc cleaned up too with an eye on that scenario would be sweet.

**Comment by vladsud** [comment]
This is great idea, but this issue has been around for a long time without any movement. So we either figure out how to make it into the plan for the next 6 months, or punt.
Given that it feels like 3P is the place where it might be most interesting, @skylerjokiel - is this something that your team is interested to put resources into some resasonable time frame? If not, let's close it.
