### ISSUE TITLE
Container Summary Recovery Mechanism

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#3994]
## Feature
We've seen some cases where container summaries get into a bad state due to bugs. Frequently this results in a summary that persists the bad state and makes the document impossible to open. 

**Describe the solution you'd like**
We should consider building a library to help recover documents. My first thought is that we walk the summaries backward in an iframe, trying to load at each until we can load on successfully, and then reply ops on top of it. Ideally, we can then connect at this point to take a new summary, and continue with the document.

**Comment by curtisman** [comment]
SharePoint has a version restore mechanism as well.   While I think this is worth while for other services, how important is this for our current scenario?  @anthony-murphy

**Comment by anthony-murphy** [comment]
Next seems reasonable. I did think about the odsp recovery mechanism as well, that will lead to data loss for at least the op tail. Ideally this would result in no data loss. also, as our partners push to GA i think having more automated mechanisms for recovery become increasingly necessary to scale our support. 

Something else i've thought about is support for forking. If we had that, then the fluid debugger would almost do all the above. Just need the ability to push the result somewhere as a new container

**Comment by vladsud** [comment]
Pretty old item, not much movement, and I'd guess - very little chance that we will do anything in next 6 months.
@anthony-murphy - punt?
