### ISSUE TITLE
Fallback for big snapshot download failures

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4005]
Observing behavior of this file (see below), I believe we need to make changes to how we download snapshot in SPO driver. The issue is that we fail with really large files / snapshots, and we need to have a strategy (even if not perf-optimized) to recover in such cases.
We should put some timeout / limit (baked into driver, in addition to any limits that SPO has on their side - see ISnapshotOptions.mds) and if it fails, report error to telemetry and switch to mode without blobs.

Currently this is blocking issue - we can't open 

[Chapter 1](https://fluidpreview.office.net/p/c3BvOmh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQtZGYuY29tL3RlYW1zL09mZmljZU9ubGluZVByYWd1ZQ%3D%3D/b!BOyJN6Bkykm_L66EicZFaDKnQ_cydFFLqph8D-t_9vqaMsGC4Tm9RYec9Rh5aw3l/01N5X4JN6S6ARYASACENCKCD7KFOSCXJIK/Chapter-1-Collaborative-Components-Status)
[Teams thread](https://teams.microsoft.com/l/message/19:53328301da384b33bcc81111124e3ab4@thread.skype/1603252323204?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1603252323204&teamName=FFX%20(Fluid%20Framework%20and%20Experiences)&channelName=Bugs%20%F0%9F%90%9B&createdTime=1603252323204)

**Comment by vladsud** [comment]
@skylerjokiel @kabirkhan - FYI. Given how important that document to management of team's operations, we need to try to remedy it ASAP. I.e. hotfix into 0.27 would be nice to have, given that this is just a fallback (i.e. it needs to be activated only if we are already failing to open a file).
For safety, we could use different logic to main, i.e. for example go with large or no timeout.

**Comment by jatgarg** [comment]
Should we go with restriction of 1 min?

**Comment by vladsud** [comment]
I'd make it 30 seconds. 1 min is too large. Even at 30 seconds timeframe, we already lost most of the users. So it's more of a safety than anything else.
At the same time, we might go for bigger time-frame on really slow networks.
So I'd say we need to get some number in, and then keep looking at telemetry and adjust knobs based on that. The threshold should be somewhere at 99.9% percentile for time, and that will keep changes as we go to GA.
