### ISSUE TITLE
Fluid Debugger should either close window or disable controls on choosing snapshot 

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4006]
For 90Mb file, when I select snapshot to load and click Ok, nothing happens.
This is due to it taking forever (to be precise - 2 minutes) to download snapshot.
All that time UI is still there in its original form, allowing user to click buttons and leaving user unsure if anything is happening.

Jatin - any chance you can take a look into it? This is not urgent

**Comment by KRyan** [comment]
Seems like disabling controls and adding "loading" UI would be ideal.

**Comment by jatgarg** [comment]
Reopening

**Comment by vladsud** [comment]
I'd let it close :) Multiple reasons:
1. Snapshots are smaller (images are out) and we will continue to make them smaller
2. It's not clear what's the future of the tool, especially with ODSP deleting ops and snapshots. It's useful for other services (FRS) and understanding of how system works, but it's no longer on critical path.
So it's not clear how we will justify improvements in it. We need to have some scenario where it's used, otherwise it will slowly die (though it does not require any support, i.e. cost of supporting it is close to zero, so keeping it is fine too).
