### ISSUE TITLE
Don't Use lfs in FluidFrameworkTestData

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4024]
## Work Item
These files are all json, which git can handle fine. lfs makes it hard to update as the diffs are not available.  we should move all the files to just be git not lfs.

example: https://github.com/microsoft/FluidFrameworkTestData/pull/3

**Comment by SamBroner** [comment]
I think the issue is the file size. (How long will clones take?)

Is there an issue with the current setup? My perspective is that the test data is only used by devs who can handle the addtl complexity of using LFS, while most people benefit from the reduced download cost.

**Comment by anthony-murphy** [comment]
The problem is that we can't review diffs to modification to the test data. since its in an optional sub module size isn't a huge issue

https://github.com/microsoft/FluidFrameworkTestData/pull/4
