### ISSUE TITLE
Optmize PrefetchDocumentStorageService behavior

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4034]
[Teams thread](https://teams.microsoft.com/l/message/19:9034865f2a4f49b5ab8df4569dbb0e73@thread.skype/1603302504888?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1603302504888&teamName=FFX%20(Fluid%20Framework%20and%20Experiences)&channelName=LiveSite%20%E2%9A%A0&createdTime=1603302504888)

We had discussions before (and I even raised PR) to augment container caching strategy, like kill cache 5 seconds after end of boot, or sync with driver policy and not cache if driver is caching.

But given how bad things are lately, and the fact that we would benefit from simplify, I'd propose we remove it altogether. And instead say (for future) that it's a driver responsibility to do caching if it wants / needs that. SPO driver already does caching, we will likely need to build similar mussel in r11s given perf requirements will be very similar

@tanviraumi  - thoughts?
@ksbrar - assigning to you as OCE, given amount of feedback we might want to implement and backport fix to 0.27 rather soon.

**Comment by tanviraumi** [comment]
Is there any specific reason for the driver to cache? I have always imagined drivers to be simple and mostly responsible for wire protocols. So may be the container/runtime should cache?

**Comment by tanviraumi** [comment]
By container, I mean container.ts, where PrefetchDocumentStorageService caches currently.

**Comment by tanviraumi** [comment]
I am trying to figure out why ODSP driver decided to cache? Is it because we did not have prefetch and they stared caching first? Or prefetch service has some limitation that cannot be fixed and we will always need to rely on drivers?

**Comment by vladsud** [comment]
Some reasons why it's likely will always be the wrong layer:
- we are adding caching on host level, to store snapshot from previous time and using it if it did not expire
- driver is always in better position to define a protocol that is optimized to bring more data over less roundtrips and reduce latency.
- all workflows will required faster boot, with ideal goal of hitting speed of light - single http request to get initial rendering to the screen. R11s is likely not to escape that as well.

**Comment by vladsud** [comment]
Basically optimizations are always about end-to-end flow, they almost never work when doing locally without understand bigger picture. There is great article on that from Google / Chrome, I'll try to find it.

**Comment by vladsud** [comment]
@tanviraumi , I want to make sure I directly answered your question: ODSP caches this information because:
1. It fetches all the blobs & all the trees in one HTTP request, so it has no other option than to cache it to make use of it. This is done to get speed of light in terms of rendering. We are moving from "all blobs" to "all header and dot blobs", but the key reason is the same.
2. Host has its onw long-term cache (that survives session) that we tap into, if it's not too old
3. (not implemented yet, but opened a bug) we want to share that cache across multiple instances of driver, i.e. share between summarizer & main container.

**Comment by vladsud** [comment]
Talked to Tanvir. We discussed issues and strategies here. Here is my proposal (not for release branches):
1. Limit prefetcher to only trees, headers and "." blobs - we can't afford do suck in 1TB of file if user wants only 1M component!
2. Remove from cache any entry on usage by runtime - runtime never asks for same data twice.
3. Not caching anything outside of # 1 - do a pass through read() and return data - same reason as # 2
4. Implement eviction from cache on some timer for data in # 1 bucket that was not requested - the value of this cache is low, client will fetch it on demand on as needed bases. I propose 15 second timer as a starting point.

I'd suggest to commit these changes one by one (i.e. break into separate issues)

**Comment by ksbrar** [comment]
For completeness, as a temporary fix https://github.com/microsoft/FluidFramework/issues/4034 introduced enums to disable (for ODSP) and enable `PrefetchDocumentStorageService()`.

**Comment by ksbrar** [comment]
https://github.com/microsoft/FluidFramework/pull/4394 adds the same enums change from 0.27 to the main branch.

**Comment by vladsud** [comment]
@znewton - I believe you were thinking about moving PrefetchDocumentStorageService  into driver-utils and utilizing only in R11S. Is there an issue tracking it (i.e. is this a dup)? If not, do you want to take ownership?

**Comment by znewton** [comment]
Yup! I opened issue #6245 to track the work (not yet started, but should be quick once I do).

**Comment by vladsud** [comment]
Ok, closing as dup of #6245
