### ISSUE TITLE
Broadcaster/lambdas is not isomporphic

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4040]
Lambda.ts has a reference to setImmediate, which is [not supported in nearly any browser](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate)

https://github.com/microsoft/FluidFramework/blob/0076d7e0c23fffcf5f6df042a1f49a6838c1b111/server/routerlicious/packages/lambdas/src/broadcaster/lambda.ts#L99 

It is used by the localOrderer, which should run in a browser context. Webpack 4 automatically polyfilled setImmediate when it was used, Webpack 5 does not. We should not use setImmediate if this code runs in a browser context.
![image](https://user-images.githubusercontent.com/1581488/96878741-0d5b3900-1430-11eb-9672-b14f4ace84b4.png)

**Comment by christiango** [comment]
@curtisman since this may be the  the last webpack incompatiblity I'd be willing to make a PR here. Just not familiar enough with the code to understand the intent here.

Naive options:
* Replace with Promise.resolve
* Replace with setTimeout

I think setTimeout probably most preserves the intent, but it may come at a perf penalty and possibly get throttled by the environment

**Comment by christiango** [comment]
@curtisman  - gentle ping on this issue since local-server collaborative scenarios are completely busted in webpack 5 by default. Unless you know to do this:

https://github.com/microsoft/FluidFramework/blob/3e679f9bd85286fc89d22290f28db89bc16e02e3/packages/tools/webpack-fluid-loader/src/loader.ts#L33

**Comment by anthony-murphy** [comment]
@tanviraumi Thoughts here?

**Comment by tanviraumi** [comment]
I read somewhere that its not the same and setTimeout(0) will have more perf penalty. Can't seem to find the link anymore.

How about we abstract it out as a params to the lambda? The service will pass setImmediate and local server will pass setTimeout(fn, 0). I did a similar flow to tackle Christian's token signing change (https://github.com/microsoft/FluidFramework/pull/4176)

@GaryWilber FYI

**Comment by christiango** [comment]
The parameter makes sense to me, should keep the server code equivalent

**Comment by christiango** [comment]
@tanviraumi - I'm not familiar with this code, is there a clear path anywhere for us to pass a different value for the setImmediate function?

**Comment by tanviraumi** [comment]
The changes will be similar to #4176 The lambda will have a new param and every thing that runs in local path (localNode, localOrderer, localDelta....) will send setTimeout(). Only the usage in routerlicious (only routerlicious-base package I think) will send setImmediate

**Comment by christiango** [comment]
Sent out a PR #4305, rather than do the work to plumb it through, I'll fall back to set timeout if setimmediate is not available in the environment. Made the change a bit smaller and hides this implementation detail.

**Comment by christiango** [comment]
Pending server packages publish to remove the hack we have in webpack-fluid-loader
