### ISSUE TITLE
Too much logging is coming from processChunk

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4043]
![image](https://user-images.githubusercontent.com/46826984/96901240-da24a400-1447-11eb-803a-83674d38748c.png)

**Comment by vladsud** [comment]
I believe this is coming from Chapter 1 document.

**Comment by vladsud** [comment]
We should also see where the time is spent. I.e. only small portion is spent in oTel, likely we can make overall processing cheaper.
And we also need to look why we log that even, maybe it's ok to leave logging as is, but there is some other functional bug that needs to be fixed?

**Comment by anthony-murphy** [comment]
sounds good. pushing this to November, as i won't have time in the next week :)

**Comment by curtisman** [comment]
Are we still using SnapshotV1?

**Comment by anthony-murphy** [comment]
yes

**Comment by vladsud** [comment]
This bug has rather big impact on [Chapter 1 document](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.office.com%2Flaunch%2Ffluid%2Fcontent%3Fdrive%3Db!BOyJN6Bkykm_L66EicZFaDKnQ_cydFFLqph8D-t_9vqaMsGC4Tm9RYec9Rh5aw3l%26item%3D01N5X4JN6BX23SZCTFTFB2D5PEQUKWMZ3E%26file%3Dhttps%3A%252F%252Fmicrosoft.sharepoint-df.com%252Fteams%252FOfficeOnlinePrague%252FShared%2BDocuments%252FFluid%2BPreview%2BDocs%252FChapter%2B1%2BCollaborative%2BComponents.fluid%26siteUrl%3Dhttps%3A%252F%252Fmicrosoft.sharepoint-df.com%252Fteams%252FOfficeOnlinePrague%26auth%3D2&data=04%7C01%7Cvladsud%40exchange.microsoft.com%7C7b46d4597fd34da2c9b808d88be718d9%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637413171998154273%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V5wPkpDIdNzt5T2d15vs3lOnxzc1kT94SHXondkC0Ys%3D&reserved=0)

Can we prioritize investigation here?

**Comment by christiango** [comment]
@ksbrar - can we port this to release/0.29 so we can take this as a hotfix downstream?
