### ISSUE TITLE
make usage of PrefetchDocumentStorageService conditional on driver caching policy

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4047]
Related issue: https://github.com/microsoft/FluidFramework/issues/4034

Add to a driver ability to communicate to loader that it does caching.
Container class not to instantiate PrefetchDocumentStorageService when driver caches data.
Which is the case for SPO driver.

**Comment by vladsud** [comment]
Here is very old PR that tried to do that, never committed:
https://github.com/microsoft/FluidFramework/pull/1396
@tanviraumi - FYI

**Comment by tanviraumi** [comment]
Given the urgency, this looks like the best fix for now. Once this is in, we can start discussing the items mentioned here (https://github.com/microsoft/FluidFramework/issues/4034#issuecomment-714754949)

**Comment by ksbrar** [comment]
https://github.com/microsoft/FluidFramework/pull/4051 addresses the contemporary bug that initially prompted this issue, see https://github.com/microsoft/FluidFramework/issues/4034 for long-term discussion.
