### ISSUE TITLE
Correctness: 'FlushMode.Manual' should be the default

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#4048]
(Lifting this as a separate issue from #3788)

'FlushMode.Manual' reduces concurrency related bugs by synchronizing op processing/[JS task](https://javascript.info/event-loop) boundaries between clients.

It does this by ensuring that all ops that are generated within a [JS task](https://javascript.info/event-loop) by one client will be dispatched sequentially and within the same [JS task](https://javascript.info/event-loop) on all remote clients.

This means that when a client performs multiple ops in a single turn like this:
```ts
matrix.insertCols(/* colStart: */ 3, /* colCount: */ 1);
matrix.setCell(/* row: */ 0, /* col: */ 3, { text: "Total", cellFormat: CellFormat.currency }); 
```

All remote clients will see the same ops applied consecutively within a single turn.  Therefore clients using the common pattern of coalescing rendering with 'requestAnimationFrame()' (or similar) can assume that columns will always have initialized headers w/cell formats, exactly as they observe locally.

The current default does not provide these guarantees.  State changes that are "task-atomic" on one client can be interleaved with callbacks like requestAnimationFrame and/or ops from other clients when processed by remote clients, greatly increasing the number of potential states a remote client can observe, and consequently the number of hard to reproduce bugs that only happen during collaboration.

(Most customers are setting FlushMode.manual today.)

**Comment by vladsud** [comment]
@ChumpChief  - FYI.
I agree here with Daniel :)

**Comment by DLehenbauer** [comment]
FYI - Blobs do not work with FlushMode.Manual or orderedSequentially (#4166).  (Found via a failed test case when flipping the default to Manual.)

**Comment by vladsud** [comment]
Assigning to myself couple tasks to make progress on decision designs:
#4048 - Correctness: 'FlushMode.Manual' should be the default
#3788 - BatchManager should be removed, all the bugs in Runtime related to not using batches in right places fixed

**Comment by vladsud** [comment]
Usage of FlushMode.Manual today:
- A bunch of examples
- RuntimeFactory class (seems to be used only in webFlow example)
- Some UTs

It does not look like shipping scenarios actually use it, as manual is the default choice.
That said, due to presence of BatchManager and its logic (see discussion in #3788), clients do get some level of implicit batching most of the time.

**Comment by vladsud** [comment]
In support of FlushMode.Manual mode as default (or maybe the only one):

I have a hard time envisioning the system where behaviors are not symmetrical across sender / receiver clients. I.e. if client that generates ops does not allow interruption of the flow while doing some activity (i.e. it's done in one JS turn), then same should be applied to a client that receives side-effects of that activity (ops). Failure to do so is equivalent to allowing random JS turn interruption and processing of events (input and rendering), which is definitely not expected by the developer. If developer truly wants interruption / faster delivery of ops, then developer should yield JS turn and accept the fact that the world might change by the time continuation runs (and adjust APIs if this is reusable component). There might be small set of cases where it's all about raw processing (no input, no rendering), but these cases are exceptions that are solved by exposing dangerous tools (flush() call).

Maybe other way to say it - simple things should be simple, complex things should be possible.

**Comment by vladsud** [comment]
Note - BatchManager does not allow ContanerRuntime to deliver its promises. Whether it's calling flush() or using FlushMode.Automatic, ContainerRuntime can't deliver promises it delivers due to BatchManager standing in a way to adding its own policies on when ops are actually send to the web socket.

**Comment by ChumpChief** [comment]
I think I'm on the same page as you, if these match your thinking?

1. JS turn should never matter either because batching is not required, or else an explicit (non-turn-based) mechanism is used to explicitly define the batch.
2. The concept of a batch should not exist in the driver or the loader layer and should be removed.  These layers should be free to send/receive ops at any granularity.  Instead, the work of packing/unpacking batches should exist only in the `ContainerRuntime`, which could implement `flush()` like `DeltaManager` has currently or whatever alternative batching mechanism it likes.

**Comment by vladsud** [comment]
I'd add to that list that default one should be FlushMode.Manual (i.e. JS-turn based batching), with flush() being only available on ContainerRuntime class (and not on any interfaces). Basically individual players (if they are not container, like components) should not have access to this primitive unless someone explicitly provides access to it, as it does not work at all with code / component composition.

**Comment by vladsud** [comment]
I think one open questions here (if we move in this direction) - do we need orderSequentially? Note that flush() today in the middle of orderSequentially() callback breaks batch (no warning), and orderSequentially callback is synchronous.

I think it comes down to making decision if we support FlushMode.Automatic (i.e. there is a way to change default) or we simply push people to use flush() manually as a mechanism to control faster flashing. In later case orderSequentially is not needed. In the former case it's useful tool, but it also means that all concepts in runtime should assume and support FlushMode.Automatic mode (this likely is mostly noop at this point).

One other consideration - batches (and ability to know when batch is over) is useful technique for something like building new DDS out of multiple DDSs on same channel (using my experience with shared matrix V1). That said, we are missing functionality here (for example, batches are flattened and there is no ability to observe boundaries of inner batches on receiving end, which makes it harder to implement such strategy).

**Comment by anthony-murphy** [comment]
> I think I'm on the same page as you, if these match your thinking?
> 
> 1. JS turn should never matter either because batching is not required, or else an explicit (non-turn-based) mechanism is used to explicitly define the batch.
> 2. The concept of a batch should not exist in the driver or the loader layer and should be removed.  These layers should be free to send/receive ops at any granularity.  Instead, the work of packing/unpacking batches should exist only in the `ContainerRuntime`, which could implement `flush()` like `DeltaManager` has currently or whatever alternative batching mechanism it likes.

@ChumpChief batches do have server side garunetees that cannot be provided client side, specifically ops in a batch will have sequential ordering, and no other ops will be interleaved. There is a sever side contract enforced here that involves the driver loader layer, and i don't think that can be changed.

**Comment by ChumpChief** [comment]
> @ChumpChief batches do have server side garunetees that cannot be provided client side, specifically ops in a batch will have sequential ordering, and no other ops will be interleaved. There is a sever side contract enforced here that involves the driver loader layer, and i don't think that can be changed.

I was kind of imagining that the implementation might look like the `ContainerRuntime` packing those ops into a single "batch op" before submitting it through the loader layer (and so from the server's perspective it's only sequencing a single op).  Haven't thought about it heavily though.

**Comment by vladsud** [comment]
I'd personally leave re-evaluation of how batches are implemented at loader / driver / service layers as a separate topic :)
I.e. I'd not change that for now (we have a way to do it), but worth pointing out that it's not perfect:
- service needs to play along, while it could be done completely on client side ("batch op"). That said it has some sizable side-effects (no sequence numbers assigned for ops, which will break a lot of things).
- ContainerRuntime could hold ops and deliver them in one go, vs. today's world of DeltaManager having some logic and more APIs to support (at a layer that does not have service delivery, thus slower to churn).

So while not perfect, I think that's an area that does not become more expensive to fix over time, so I'd assign it low priority :)

**Comment by DLehenbauer** [comment]
> so from the server's perspective it's only sequencing a single op

**Comment by vladsud** [comment]
Here is how I'd tackle it:
1. Ensure that flush() can't be called from within orderSequentially() callback.
2. Rename FlushMode.Automatic to FlushMode.Immidiate
3. Rename FlushMode.Manual to FlushMode.JSTurn or FlushMode.Automatic (i.e. something more telling, "manual" does not convey intent, IMHO) and make it a default selection, removing code that sets it in samples.
