### ISSUE TITLE
Fix Loading From Ops

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4049]
## Describe the bug
With detached container we always need to load from a snapshot to start. Currently if the container request passes `headers.version === null` we skip all snapshots, and load from ops only. This now causes a problem. We should update to load from the oldest snapshot when `headers.version === null`

https://github.com/microsoft/FluidFramework/blob/2b21b9dc5ab906a07924418e01d15bbf2d586237/packages/loader/container-loader/src/container.ts#L205
https://github.com/microsoft/FluidFramework/blob/2b21b9dc5ab906a07924418e01d15bbf2d586237/packages/loader/container-loader/src/container.ts#L1000

**Comment by jatgarg** [comment]
@ram-ramasubramanian Do we have any way to refer to oldest snapshot?

**Comment by jatgarg** [comment]
@anthony-murphy, I had a PR out for this: https://github.com/microsoft/FluidFramework/pull/4259 where I was asking the oldest snapshot from the storage service but you suggested that the other design where we have a op which would contain the oldest snapshot version fired after connection is made after attaching the container.
I still think the return on investment seems less here for the op approach and that seems prone to errors until a perfect implementation is done, like firing op/loading null runtime and then switching to actual runtime. Currently in my PR I have kind of a hack to fetch the oldest version for snapshot fetching but we can improve that on server side by making the server return just the oldest snapshot version according to a specific rest call like a query param in getVersions call and then server would return the oldest snapshot version in that case. In nov, I talked to @marcmasmsft  about this and he seemed convinced on that.
So just wanted to think or take your opinion once more before I start the work on any path.

**Comment by anthony-murphy** [comment]
This sounds like a reasonable path forward to me

**Comment by vladsud** [comment]
@anthony-murphy , @jatgarg , is this important to get fixed this quarter? unless existing prototype PR is easy to finish in a day or so, I'd rather push it to backlog (assuming there is no dependency on GA), as we have more work in a "must" category than we can accomplish. Please readjust milestone if you disagree.

**Comment by anthony-murphy** [comment]
seems fine to push out. we might want to disable the feature aka only load from snapshot never `version==null`

**Comment by vladsud** [comment]
@jatgarg , @anthony-murphy, I think we should punt on this work and instead remove "null" handling for versions.
There is no really "old" snapshot capability today in ODSP where they delete snapshots very quickly.
At some point, we would need ability from to load state of the file at particular sequence number (this would be a must for delay-loading data stores / DDSs and partial snapshots, as snapshot blobs could be deleted in a file, but are needed by client that is behind / offline). ODSP will implement that using they file versioning feature. We would be able to leverage that by asking snapshot closes to seq #0. We will need to design all of that whenever that happens, but likely the way we do it will be quite different from current workflows and we will need to design it properly whenever that happens.

**Comment by jatgarg** [comment]
I think they always keep the first/oldest snapshot and never delete it. But right now there is no way to just get that snapshot as I tried. The only way seems to be get all snapshots(10) and then choose the oldest one but that seems undesired. So I agree the best way is to get a snapshot at a particular seq number for this. So we can close this issue?
I have another PR open long time back to remove the null handling and I can work on that?

**Comment by anthony-murphy** [comment]
seems reasonable to me. i don't know if we can remove, as i think some of our tooling/testing needs it, but at a minimum we should not expose the functionaliy publicly

**Comment by jatgarg** [comment]
I am looking what is required here as for testing and will remove it from public eyes.

**Comment by vladsud** [comment]
ODSP does not keep first snapshot anymore. They guarantee that they keep a snapshot that is at least 1 month old. But that's it.
I do not believe any of our tooling uses version=null, that would not work (we no longer support opening files form ops, and null currently maps to ops, not some snapshot).
So I'd propose remove null handling altogether (and make API a bit more readable, as there always was a lot of confusion between undefined/null)

**Comment by jatgarg** [comment]
ok. Taking a look.
