### ISSUE TITLE
Cannot find module 'nan' when setting up FluidHelloWorld

### ISSUE THREAD

**Issue by Flavyoo** [microsoft/FluidFramework#4087]
When installing the dependencies for the FluidHelloWorld app, users might encounter an issue with the module 'nan' not being available. I was able to fix this by deleting the package-lock.json file and running `npm install` after.

### To Reproduce
1. git clone https://github.com/microsoft/FluidHelloWorld.git
2. cd FluidHelloWorld
3. npm install

### Expected behavior
Dependencies should be installed with no issues.

**Comment by curtisman** [comment]
Thank you for the report.  I have tried your steps, and wasn't able to reproduce the error.
Looking at the package-lock.json, the project don't seem to haven't an dependency to the `nan` package.
Can you try `npm ci`?

**Comment by Flavyoo** [comment]
Thanks for looking into it. It is working for me now after removing the package-lock file.

**Comment by SamBroner** [comment]
Excellent! I'm going to resolve this issue then.
