### ISSUE TITLE
Add telemetry triggers / alerts 

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4092]
Last week showed that we have no good story around early detection of regressions in couple areas, specifically summarization.
While we can do better at testing (see https://github.com/microsoft/FluidFramework/issues/4084), we need to add alerts to the system around key metrics and be able to react to those alerts right away.

This is mostly not new work - dashboard Wes built already were build with this in mind, tracking key metrics that matter for health.
I'd use dashboard for defining actual triggers, but here are couple areas based on last week:
1. Duration of TreesLatest: below 10s for 95th percentile
2. Duration if Container:Load - below 10s for 95th percentile (note that this may have low correlation with above - on one hand it's more unique work, on another it relies on caching of snapshots, so may not include TreesLatest call).
3. Number of ops in TreesLatest: below 1000
4. Summarization errors
5. Followed by count of all errors per day - need some limit where alert fires.
6. Container critical errors - similar, some limit per number of open instances.

**Comment by markfields** [comment]
Plan for November is to break this out into a stack-ranked list of dashboards to implement along with alerts, and commit to implementing at least one during the month.

**Comment by markfields** [comment]
Some of these are already covered in November, and any others will fall below the cut line since it's a short month.  During December planning we'll break this out into the next set of tactical telemetry improvements and close this.  Moving to December.

**Comment by vladsud** [comment]
We should either commit to make some progress here or punt
