### ISSUE TITLE
exceptions during loading channels (DDS) result in request() throwing, unhandled exception and no indication to the user that component failed to load.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4146]
From https://office.visualstudio.com/OC/_workitems/edit/4528157?src=WorkItemMention&src-action=artifact_link

As for telemetry & unhandled exception, all stacks point out to loadChannel() being on the stack.
I believe this is results of calling FluidDataStoreRuntime.request() and it calling getChannel() and not wrapping it in try/catch to convert to 404 or some other reasonable error. Unfortunately we chose design here that adds another way to propagate errors and mismatch in expectations - code does not expect exceptions. I believe we will need to change it in future, but for now we need to wrap with try/catch and report errors to our telemetry.

Kabir - any chance you can address it, and ideally get it into 0.27? The change should be rather trivial and will help us better understand the problem, as it would be much easier to get all the other Fluid logs around it.

Marking as October, as this issue affects too many files, needs to go into 0.27.

IcM: 212126706

**Comment by ksbrar** [comment]
@vladsud, looking into this also I think you tagged a random Kabir elsewhere on GitHub

**Comment by vladsud** [comment]
Yep, it was copy/paste error (different formats of at-mentions in github & ADO), sorry!

**Comment by ksbrar** [comment]
Np, good advertising for Fluid!

**Comment by kabir** [comment]
Nice to meet you ;)

**Comment by ksbrar** [comment]
@vladsud Can this issue be closed?

**Comment by vladsud** [comment]
I believe so
