### ISSUE TITLE
Deprecation of "jwt" key from IResolvedUrl.

### ISSUE THREAD

**Issue by tanviraumi** [microsoft/FluidFramework#4147]
Relevant PRs: #4126 #4133 

r11s driver now requires a token provider, so we don't need to keep the tokens.jwt in IResolvedUrl anymore, since it will create confusions. I have removed it from most places in the above PRs. But there are two places where we are still using the jwt fields. We should take a look into those.

1. https://github.com/microsoft/FluidFramework/blob/main/packages/tools/fetch-tool/src/fluidFetchInit.ts#L17
2. https://github.com/microsoft/FluidFramework/blob/main/packages/drivers/local-driver/src/localDocumentServiceFactory.ts#L97

For now I have made a DefaultTokenProvider in r11s driver to work around this issue. We should delete that once the two usages are removed.

**Comment by jatgarg** [comment]
open
