### ISSUE TITLE
Incoming remote op sequence# <= local collabWindow's currentSequence#

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4150]
Hot bug:
https://office.visualstudio.com/OC/_workitems/edit/4528157?src=WorkItemMention&src-action=artifact_link

I got access to customer file that customer does not want to share broadly, so I'll put my observations here.

We are in loadChannel() and processing ops one by one that we accumulated while DDS was not loaded.
current op seq # is **1040**

But this.mergeTree.collabWindow has this state:
> clientId: 0
> collaborating: true
> currentSeq: **2285**
> localSeq: 0
> minSeq: 2285

It's pretty clear that it reflects latest state of the file, not channel! Somehow it got updated before we were able to process all ops for that channel.

The initial seq number comes from this stack:
> startCollaborating
> startOrUpdateCollaboration
> loadHeader

I.e. it comes from chunk.headerMetadata.sequenceNumber!
This looks wrong, as we will process ops from catch up blob, and they will have sequence numbers that are lower than snapshot sequence number - I believe we need to use MSN as a seq number in current architecture.

If that's the case, then the obvious question - why we do not see that same problem in our testing? Don't we test catch up blobs? It seems like it should be trivial to hit.

IcM: 212126706

**Comment by ksbrar** [comment]
Partial change for better error handling / logging is tracked by https://github.com/microsoft/FluidFramework/issues/4146

**Comment by anthony-murphy** [comment]
We've seen similar issues before, and they are usually the result of summarizer error. Sequence is just particularly sensitive to these types of issues. My hunch is that this is related to the summarizer issue where we aren't correctly pausing the incoming queue, so ops sneak in during the summary. @ChumpChief investigated that issue, is there a pr or issue for it?

**Comment by vladsud** [comment]
@anthony-murphy, are you saying that snapshot in this file is wrong (based on the data I've provided above)? I.e. what is the expectation of sequence number to be in the header? Should it be equal to MSN?

**Comment by vladsud** [comment]
And if it's the case, can we add asserts / checks at the time of creating asserts (in merge tree) to catch issues earlier?
The right invariants should be asserted on every steps (defensive programming) - that's the only way not to waste a lot of time chasing these issues and guessing.

**Comment by ChumpChief** [comment]
Instance we saw was tracked by #2139.  @chensixx ported some telemetry that had gotten left behind with #3839 that we were hoping would help with future investigations.

**Comment by ChumpChief** [comment]
> We've seen similar issues before, and they are usually the result of summarizer error. Sequence is just particularly sensitive to these types of issues. My hunch is that this is related to the summarizer issue where we aren't correctly pausing the incoming queue, so ops sneak in during the summary. @ChumpChief investigated that issue, is there a pr or issue for it?

You might be also thinking about #3907 -- this one is pretty easy to verify the hypothesis, if the summary op has a different sequence number in the "message" field vs. the referenceSequenceNumber

**Comment by anthony-murphy** [comment]
The sequence number in the header metadata is the min sequence number for the overall snapshot, and the specific sequence number to generate the snapshot of the merge tree at. the sequence then adds catch up ops to bring that snapshot forward to the snapshot's sequence number.

**Comment by anthony-murphy** [comment]
and there are a bunch of snapshot tests with catch up ops, so i don't think this is an obvious problem. however, this happens is something subtle

**Comment by abrahamrq** [comment]
This file shows the same error https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!4PvB7en15Uuzx4a7PsSP8WtTLkHr1GlGpP80mq3i9F--IqWoC9f2Q6J1wL76kAbU&item=01S5BCLYEHIEKHSQRNTFB3GIKW4Z47QG7X&file=https:%2F%2Fmicrosoft-my.sharepoint.com%2Fpersonal%2Fjustinmoore_microsoft_com&siteUrl=https:%2F%2Fmicrosoft-my.sharepoint.com%2Fpersonal%2Fjustinmoore_microsoft_com

**Comment by anthony-murphy** [comment]
closing an dup of #4296
