### ISSUE TITLE
Access IResolvedUrl from Container Context

### ISSUE THREAD

**Issue by jodom** [microsoft/FluidFramework#4164]
## Feature
**Is your feature request related to a problem? Please describe.**

Fluid data objects may need access to container **_resolvedUrl_** through a Container context api. Current use case includes data objects requiring resolvedUrl at runtime, to use as input to host share-link logic.

**Describe the solution you'd like**

Add `readonly resolvedUrl: () => IResolvedUrl | undefined` to **IContainerContext** or **IContainerRuntime** contracts. Implementation should just proxy **container.resolvedUrl** which already exists.

**Existing work**
This is a new feature on Container context. Similar pattern exists with **_getAbsoluteUrl_**

**Describe alternatives you've considered**

Hosts and host services already have access to container resolvedUrl from (top level) loaded container. Services hard code reference to resolvedUrl of this single container instance, however, data objects should be able to 'contextualize' their container  in nesting scenarios, where multiple containers are loaded and reusing the same service instances from host is ideal.

**Additional context**

**Comment by jodom** [comment]
This may be point in time, hosts currently dont manage their own url resolvers and reach back to the container to get abosolute url, resolved url etc. As you mention, the share link logic is implemented in scope. What this change introduces is a way of getting the abstracted driver information by the data object so it can use scope services. cc @leeviana , @jatgarg .

**Comment by jodom** [comment]
> The driver owns the format of the resolved url. There is no guarantee the formats will be at all simialr across drivers, r11s, odsp, .... So the container shoud not couple to the resolved url format. What specific information are you trying to access?

Resolved url format and type definition are a separate but related and subsequent discussion. For now, we just want to access driver resolved url from container context without any considerations or care for underlying driver type. We already do this from `container.resolvedUrl` interface

**Comment by anthony-murphy** [comment]
If i understand the scenario correctly my preferred design looks something like this:

1. Add and optional options argument to getAbsoluteUrl
2. Wrap your storage url resolver in a new url resolver. pass through most calls, but if some option is set, generate a sharelink instead.
3. call get absolute url with the share link option with the understanding, that other host may ignore the option.

**Comment by jodom** [comment]
This flow doesn't resolve our use case as hosts and data objects - which is to generate the share link ourselves with fine grained control of permission levels on it.
The implemented flow is:

1. Get file information from driver resolved url. Entry could be at the host level, in which case we can use loaded `container.resolvedUrl`, or at component level, in which case we **need** context.resolvedUrl`.

2. Pass this file information to some host logic for selecting and controlling permission levels. Logic should be able to deduce driver and resolver type from resolvedUrl.

3. Generate share link with file information and selected permission level (host logic calling resolver.getAbsoluteUrl)

If we start from getAbsoluteUrl, hosts logic then has to work backwards, breaking sharelink down into file and pathing information so it can select permissions, try to match driver type, select resolver and then go through the share link rebuilding flow.

It'd be cool to pass desired permission levels to getAbsoluteUrl optional options argument in the flow you mention above, though I'm not sure where hosts would get that information without prior knowledge of driver and resolver

**Comment by anthony-murphy** [comment]
why can't 1 and 2 happen within getAbsoluteUrl? That is what i am propsing. it already has the resolved url, and 2 can come from anywhere as the code is owned by the host

**Comment by anthony-murphy** [comment]
I host already fully controls what happens in getAbsoluteUrl. you may be choosing got just pass a resolver's implementation, but you can and should override that with something host specific. The only missing piece is the options to know to generate a share link

**Comment by jodom** [comment]
> why can't 1 and 2 happen within getAbsoluteUrl? That is what i am propsing. it already has the resolved url, and 2 can come from anywhere as the code is owned by the host

This seems like a possible flow, considering just the ODSP implementations today, it doesn't seem like we need file info to determine permission level (scopes), and host UI can determine literally hard code desirable permission scopes and pass those along with option to generate share link to a revised getAbsoluteUrl api. @vivekmogalapalli, @AndreiZe , could you confirm this hypothesis. 

That said, current host flows specific to ODSP resolver has entry points requiring file info (1) to reuses shareDIalog UX that maintains allowed permission scopes (2) and abstract the call to getAbsoluteUrl, getShareLink (3).

I know this is tied to a specific host driver and implementation. Exposing resolvedUrl on container context however, enables ODSP specific flows without coupling container interfaces to resolved url format

**Comment by jodom** [comment]
> The host already fully controls what happens in getAbsoluteUrl. you may be choosing just pass a resolver's implementation, but you can and should override that with something host specific. The only missing piece is the options to know to generate a share link

Much neater. Also changes cross host expectations and shared logic flows short term. I think we should still implement this proposal or variant. cc @leeviana, @jatgarg for thoughts
