### ISSUE TITLE
Blob attachments & batches do not work together

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4166]
[1:21 PM] Daniel Lehenbauer
Discovered that Blob attachment does not work w/FlushMode.Manual or 'ordereSequentially'.  This is because ContainerRuntime.submit(..) clobbers the opMetadata with {​​​​​​​​ batch: true }​​​​​​​
Easy fix to merge instead of clobber, but I was wondering if blob attach could use localOpMetadata?

**Comment by DLehenbauer** [comment]
@wes-carlson - I was going to go ahead and fix this, but then began wondering why the BlobAttach message is using metadata instead of passing the blobId in the message content?

**Comment by vladsud** [comment]
This is for storage to pick it up, and storage layers never look at content
