### ISSUE TITLE
Expose appendDataStorePath and resolveDataStore resolver interface methods to components so they can use it

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#4169]
Like getAbsoluteUrl, appendDataStorePath and resolveDataStore methods need to be usable from component code.

**Comment by leeviana** [comment]
@jatgarg FYI, making this for tracking purposes. Also this probably overlaps with some of @chensixx work with adding new APIs to all the resolvers

**Comment by curtisman** [comment]
@leeviana,  can you give us some usage pattern at you are thinking about?

**Comment by leeviana** [comment]
Yep! These have both been vetted pretty thoroughly with both teams, this is just the official tracking issue:

- appendDataStorePath is a way for component code to synchronously append context information to component path information to a link initially created with getAbsoluteUrl(). Since getAbsoluteUrl is async it cannot be used in browser copy logic (which has to be sync) and there is contextual information that generally needs to be added to the component path that is only known at copy time.
- resolveDataStore is the "undoing" of the getAbsoluteUrl() method. The getAbsoluteUrl method produces a driver specific URL with component pathing information stored in it and subsequently we need a method to be able to then take that driver specific URL and retrieve component pathing information from it :)

**Comment by anthony-murphy** [comment]
I don't think we can assume we can always synchronously append to an external url, or even append at all.

I don't understand the use case for parsing the external url. Why would a data store need to do this?

**Comment by leeviana** [comment]
Unless component path information involves regenerating something service side (which it shouldn't because file/storage operations happen on the container level), I think append still makes sense, I haven't come across a case yet where it doesn't.

resolveDataStore would be used in cross-container references or host loading flows, not internal container references. To load a component you would need to first resolve the container and then request the componentPath off of the container. The only way to get this componentPath from a driver specific URL is via the resolver logic

**Comment by anthony-murphy** [comment]
I wouldn't expect a case with odsp, but other servers might have that case. i could see server producing friendly/short urls, rather long ugly storage urls. I don't think i'm ready to prevent this use case, and adding this api would prevent it.

In the case where a component is a host, it should get a loader, either via scope, or bring on itself, and just resolve the external url on the loader which should resolve to the data store. i think there were some bugs in this area that @agarwal-navin fixed, but that is how it should work. i don't see a need for resolveDataStore

**Comment by anthony-murphy** [comment]
I also believe when resolving an external url the loader will resolve to a handle, somewhere, not specifically a datastore. @vladsud might have additional insight on this, but i would worry methods like these would also cause issues that that approach as well.

**Comment by agarwal-navin** [comment]
> In the case where a component is a host, it should get a loader, either via scope, or bring on itself, and just resolve the external url on the loader which should resolve to the data store. i think there were some bugs in this area that @agarwal-navin fixed, but that is how it should work. i don't see a need for resolveDataStore
You can call loader.request() with the url containing the component path and that should give you back the component. Reading through this thread, I believe that would take care of this use case, unless I am missing something.

**Comment by agarwal-navin** [comment]
There were some bugs in the url resolvers where it was not returning the right component. @chensixx is going through the url resolvers and fixing them :-). If you come across a url resolver where this is not working, please let me or @chensixx know and we will be happy to take a look.

**Comment by anthony-murphy** [comment]
it looks like loader is plumbed all the way to the dataStoreRuntime, so you should just resolve on that, and you will get whatever you are requesting, local, or not.  if that doesn't work. then there are bugs we should fix

**Comment by leeviana** [comment]
For append we _do_ call getAbsoluteUrl in the initialize and cache it. However we need to add context information that is only available during the sync copy operation to the component url. The only way we were able to design around this limitation is by introducing a sync "appendpathtourl" method. (until web browsers allow async copy/paste operations)

Hmm, for the Loader logic, you're saying that Loader.resolve(<full container url with path information>) will resolve the container plus the component information? I don't understand how this would work today as the component path is stored in a very specific way in the resolved url and the wider Fluid Framework ecosystem doesn't have any insight/architecture around component path. This need is based on the cross-container paste solutions you worked with Mara on, which requires being able to get component path information right now.

**Comment by leeviana** [comment]
Even today in our host loading path, we have to treat the component separately... it should be easy to test out though, but I'm fairly certain that unless something big has changed the Loader.resolve() logic doesn't have enough information about the component path. I'll test it out at some point in time and get back to you on that one.

**Comment by anthony-murphy** [comment]
for the loader resolution it designed to work, and if it doesn't i would consider them bugs, not sure which layer the bugs are at though. Basically the url resolver should do the right thing for any external url, if it's not, it probably means there are bugs in you url resolver that should be fixed

**Comment by agarwal-navin** [comment]
@leeviana loader.resolve() would only resolve a Container. loader.request() can resolve components as well.

**Comment by leeviana** [comment]
Right, but how do we get the information to pass into loader.request?

**Comment by anthony-murphy** [comment]
you should already have a url, if it is relative it will be resolved within the container. if it is absolute it will go to the loader, resolve to a container, and then request into the container for the path

**Comment by leeviana** [comment]
So you're saying that Loader.resolve() will also to the request into the container based on the absolute url? Today Loader.resolve() loads a Container, my question is how do we get the component? Today we have to do another call to request({url: path}).

**Comment by anthony-murphy** [comment]
just call loader.request, that will do everthing

**Comment by anthony-murphy** [comment]
and if it doesn't there are bugs

**Comment by leeviana** [comment]
Got it, so Loader.request(<absoluteurl>) should do all the stuff and return a component with the correct things. How do we get the container for that component? I think Loader.resolve(<url>) and Loader.request(<url>) will probably create two different container instances.

**Comment by agarwal-navin** [comment]
They won't create separate instances unless you have disabled caching in the Loader.

**Comment by leeviana** [comment]
ooh nice so each Loader only keeps around once instance of each container instance. Got it, let me see if this works, this'll be amazing if it does!!

If it does, we can drop the resolveDataStore requirement and we just need to figure out the sync appendDataStoreUrl story. :) This requirement has been around for longer with no other proposed solutions so we'll have to come up with another solution if we can't add this all the resolvers.

**Comment by anthony-murphy** [comment]
for append i don't love it, but i think i'd just push it to scope, rather than the driver, as the driver will also have cross iframe concerns which make anything sync impossible

**Comment by leeviana** [comment]
The usage of append is all internal to the iframe because it's entirely due to component model internal virtualization/context. External hosts already have all the urls they need via regular Container APIs and we'd like to leave it that way. We currently have a hack in our scope object that exposes the resolvers passed in to the Loader to all components but we'd definitely like to remove it, hence this issue. The reason why it doesn't belong natively in the scope object coming from each host is because the logic is very driver/resolver specific so the implementation of this logic should away from both host and component code and only dependent on the container runtime knowing its resolver internally, similar to getAbsoluteUrl. i.e. copy/paste should work if we're on peer to peer or FRS etc not just sharepoint.

**Comment by anthony-murphy** [comment]
> The usage of append is all internal to the iframe because it's entirely due to component model internal virtualization/context

That's my point. The driver (resolver, and document factory) may live outside of the iframe, so all methods need to be async to proxy. adding any sync call on this interface break that

**Comment by leeviana** [comment]
Ah I see, yeah that makes sense. Hmm, that's an interesting challenge because scope is in the same boat of living outside of the iframe, our hack just happens to be on the inside of the frame (but when the iframe boundary moves this will be a problem). Does anybody else have ideas as how to do url manipulation in a sync way in a component? @jatgarg?

**Comment by leeviana** [comment]
I wonder how difficult it would be for scriptor to save "context metadata" every time a user does a selection or a mini ... menu is clicked etc. I can still imagine some race conditions here where the url hasn't been generated by the time the user decides to click copy or do ctrl+c but as long as most of the expensive logic happens upfront with the getAbsoluteUrl caching maybe it's okay...

We'll need some dedicated scriptor effort here though to rework component copy/paste so that it keeps working without the hack, I'll point this towards Kyle if that's really the only way we think we can do it.

**Comment by anthony-murphy** [comment]
So something i see coming down the pipe is the requirement to store handles to any external url given out. A possible solution is to create a url manager that always has a url ready, that points to an empty handle. when a data store asks for a url, it gives it a handle, it sets the handle to the previous provisioned url, and give it back synchronously, while in the back ground retrieving a new url

**Comment by anthony-murphy** [comment]
similar thoughts :) in what i propose you could potentially hand out the url before the handle in ready, rather than having to pre-pre-prepare it

**Comment by leeviana** [comment]
Ah yeah that makes sense, there's a world where maybe we could have a container service/provider that's exactly this "clipboard/url manager" that helps with container url management. Then any component can plug into to get/set url/handle data. Still would require work from components to plug into this every time context changes but I don't think that can be avoided.

**Comment by anthony-murphy** [comment]
yeah. i still see a possible scope here as well. maybe the host can optionally provide a sync url creator. if it exists, we use it, otherwise we fall back to some pre-provisioning logic. We haven't closed on how scope functions in a iframe, but my guess is it will be some combination of explicit proxies and local state that is somehow instantiated.

**Comment by anthony-murphy** [comment]
i would also love to see something like the container url manager built as a shared and reusable data store or something

**Comment by leeviana** [comment]
The host would have to have some knowledge of the resolver that was used to load the container though. This might be possible with some other resolver APIs (I can open up _that_ can of worms in another issue) specifically for host usage but at least for today we don't want any hosts digging into resolver implementation details outside of Container.IResolvedUrl and Container.getAbsoluteUrl()

**Comment by anthony-murphy** [comment]
yeah. i think scope is pretty underdeveloped. that will also need to mature in order to handle more complex scenarios like we are talking about here.
