### ISSUE TITLE
Remove 15 second timeout on socket connections in SPO driver.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4177]
[Teams thread](https://teams.microsoft.com/l/message/19:53328301da384b33bcc81111124e3ab4@thread.skype/1603904301524?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1603904301524&teamName=FFX%20(Fluid%20Framework%20and%20Experiences)&channelName=Bugs%20%F0%9F%90%9B&createdTime=1603904301524)

https://office.visualstudio.com/OC/_queries/edit/4601632/?triage=true
https://office.visualstudio.com/OC/_queries/edit/3663497/?triage=true

I propose we do the following steps:
1. Remove timeouts (15000 / 20000) or substantially increase them
2. Add ability to do two connections in parallel, one starting 15 seconds (or so) behind the first one.
3. Chose whatever one comes in first, and clearly closing second one.

IcM: 212256035

**Comment by vladsud** [comment]
@ChumpChief , @GaryWilber - FYI

**Comment by vladsud** [comment]
Per Gary, AFD is going away with PUSH v2 design, so likely we do not want yet to implement my proposal.
That said, looking at telemetry for fluid:telemetry:OdspDriver:FailedAfdUrlFallback, there are roughly 2K hits per day, and 15% of them are at 15 seconds. Meaning a lot of users are hitting that timeout. That said, numbers over last 10 days are way worse

Worth pointing out that in some sessions I've looked where we hit 15 seconds, it took long time to connect successfully, i.e. we might have got lucky (eventually) that it was under timeout.
All of that points to the need to increase timeout number. I'd go with 60 seconds for now and reassess in 10 days after it goes to production.

Note that distribution is hockey stick. Session_Id == "439bbb9b-3d27-42fd-8644-ad7a2b07bfff" had 467 timeouts!

What we are missing also is how long it took to connect, i.e. actual establishing of connection.
We record on fluid:telemetry:Container:ConnectionStateChange_Connecting a bunch of telemetry, but this info is missing - DeltaManager should collect it and provide on "connect" event.

**Comment by micahgodbolt** [comment]
I'm going to re-open this issue. Though #4249 mitigated the issue, the problem still remains. 

@vladsud suggested 3 possible steps. First is done, but there are 2 others as well. 

- [x] 1. Remove timeouts (15000 / 20000) or substantially increase them
- [ ] 2. Add ability to do two connections in parallel, one starting 15 seconds (or so) behind the first one.
- [ ] 3. Chose whatever one comes in first, and clearly closing second one.

**Comment by vladsud** [comment]
We should not do # 2/3 as PUSH v2 that we are moving to will eliminate the need for AFD, so there will be no secondary connection to make.
But we should use this issue to figure out what kind of telemetry we can use to diagnose the problem. For example, can we use Resouse API here to figure out where socket connection is stuck? Is this DNS resolution, establishing TCP connection, or websocket / socket.io handshake?

**Comment by jatgarg** [comment]
I checked whether we can use the resource timing api to measure the socket conenction. But seems like we can't.
Fetching performance.getEntriesByName(url); where url is socket url does not return anything. Seems like it can be used for fetch and some other functionality.

**Comment by jatgarg** [comment]
So, I don't think we can do anything else here from client side.
