### ISSUE TITLE
Improve error message for createChild

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/FluidFramework#4220]
Current message of "Create SummarizerNode child already exists" is not descriptive enough to give user an idea of how to fix the problem. 

https://github.com/microsoft/FluidFramework/blob/61bd2cc14e8b88b234627c81984707d05541663c/packages/runtime/runtime-utils/src/summarizerNode.ts#L650-L651

**Comment by anthony-murphy** [comment]
there is another assert somewhere where we assert a similar thing. not sure why we are hitting this assert instead now. We should add a new assert way up the stack, which asserts that a datastore with a duplicate id has been created

**Comment by anthony-murphy** [comment]
This is the assert that should fire. I think it should be done earlier in the method:
https://github.com/microsoft/FluidFramework/blob/a016be9cbdf840822250415fd93befc6bf313c3a/packages/runtime/container-runtime/src/containerRuntime.ts#L1566

**Comment by anthony-murphy** [comment]
also. i think we should move away from a simple assert here, and log/throw an error that makes it clear this is a permanent data corruption
