### ISSUE TITLE
OdspDriverUrlResolver2 is missing unit tests

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4225]
The ODSPDriverUrlResolver2 is based on some code we found useful from an internal repo that was ported to the shared layer. However, the unit tests were not brought over. We should port the unit tests to the odsp-driver package

**Comment by skylerjokiel** [comment]
There's a larger problem of testing in the ODSP Driver layer. Making this a bigger issue and moving it to Next so we can resource it correctly.

**Comment by christiango** [comment]
> There's a larger problem of testing in the ODSP Driver layer. Making this a bigger issue and moving it to Next so we can resource it correctly.

Completely agreed! I think we need more test coverage and a proper "inner dev loop" within the FF repo. This one item should be cheap in that we have tests in the internal repo that just need to be moved over here

**Comment by curtisman** [comment]
Please migrate the existing test as well.
