### ISSUE TITLE
Evaluate performance impact of debug dependency

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4226]
Throughout the repo there are usages of debug. We should follow up here and make sure we want to keep this dependency vs leveraging the logger more thoroughly and adding some "verbose" local debugging capabilities.

Here are some things to think about:
* Bundle size - debug + it's dependency ms are actually pretty small, coming in at ~6KB before compression. This is about 5% of our current minimal bundle that has just a container runtime. Would be nice to shave off that ~6KB, but there are bigger opportunities for bundle size alone, like lodash which is about 17KB uncompressed
* Runtime cost - I don't have a ton of evidence of heavy resource usage at runtime, but my expectation is that debug should have no cost unless it is opted in to. I do see it having an impact at runtime below (t.useColors is coming from debug, cost is <.2 ms in this sample), but I don't see it frequently enough to be considered a serious problem. It may be a one time initialization cost from evaluating the module, in which case it is not a big concern. If we do see it frequently, then I it would raise the priority of this.
![image](https://user-images.githubusercontent.com/1581488/98023447-cd933a80-1dbb-11eb-807c-037be6a51022.png)

As a summary, there isn't a huge known issue here, but would be good with someone in the telemetry space on Fluid Framework to define the direction here for local debugging vs internal logger and to be confident that we aren't seeing any runtime cost when users have not opted in

**Comment by curtisman** [comment]
I have looked at the code and these are initial cost only.  There should be very small performance hit, as long as the caller doesn't do heavy computation to create the debug message.
