### ISSUE TITLE
SPO driver: Blobs should not have epoch

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4277]
Not urgent issue, but worth addressing for better perf / consistency

Blobs in the system are immutable.
We should double-check claims in this issue, and make sure that blob IDs are unique, i.e. they is no way to get duplicate ID after epoch change (which is possible if, for example, IDs were sequential numbers, and file restore would reset counter back in time).

But assuming blob IDs are unique across restores / file being overwritten, the following should be true:
1. Blob fetch API should not have epoch payload and epoch should not be validated on client or on server,
2. removeAllEntriesForDocId() should not exist, but rather changed to include only file & type properties from ICacheEntry, i.e. leave ability for driver to delete individual entries for a file (snapshots, blobs, ops), not all the data.

Even if this work can't be done because blob entries are not unique, removeAllEntriesForDocId() should be changed to at least take IFileEntry not docID, as all other APIs take ICacheEntry that uses IFileEntry as file identification, not docId.

**Comment by SamBroner** [comment]
This is work for sharepoint? Or you want to harden our systems to not rely on the epoch data?

**Comment by vladsud** [comment]
Out system should be more performant in presence of epoch changes, and not discard immutable blobs from host caches.
IN order to do so, changes are required on SPO (likely) and SPO driver (for sure)

**Comment by jatgarg** [comment]
As per latest discussion, we should not assume anything on epoch change as blob id 'a' with epoch 'x' != blob with id 'a' and epoch 'y'. So we should clear all data in cache on epoch change. So item 1 will remain as it is.
