### ISSUE TITLE
Simplify logic for convertSnapshotToITree api

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#4278]
Refer this: https://github.com/microsoft/FluidFramework/blob/ee14a3966db4a44053e760b3b8c981d0595a66b4/packages/runtime/datastore/src/utils.ts#L10
`blobMapInitial` simply contains entries one-to-one with `snapshot.blobs`, so basically converted from plain JS object to Map.

Then loop through those entries in `blobMapInitial` and add them to `blobMapFinal` if they exist in `blobMapInitial` (redundant?). Seems like `blobMapInitial` and `blobMapFinal` are the same.

_Originally posted by @arinwt in https://github.com/microsoft/FluidFramework/pull/4230#discussion_r519020998_

**Comment by arinwt** [comment]
Correction to my comment, after looking more closely it is not redundant. It is using the `value` not the `key` to index `blobMapInitial`. Still a little curious what the intent is here, i.e. is it okay that it only goes 1 layer deep?
```
{
    a: "b",
    b: "c",
    c: "d",
    d: "c"
}

a -> c
b -> d
c -> c
d -> d
```
Example above shows what a cycle looks like or a depth of 3.
