### ISSUE TITLE
Deprecate PureDataObject.url in favor of handle.absolutePath

### ISSUE THREAD

**Issue by cosmincatrinescu** [microsoft/FluidFramework#4281]
Should PureDataObject.url go away with IFluidLoadable.url going away?

**Comment by SamBroner** [comment]
@vladsud do you have a perspective on this?

**Comment by vladsud** [comment]
Yes, it's already marked properly:
    // Back-compat <= 0.28
    public get url() { return this.context.id; }

We go through back-compat comments time to time and delete them.
IFluidLoadable.url is already gone.

**Comment by vladsud** [comment]
I already removed it :)
