### ISSUE TITLE
Differential Summary Erroneously Including Old Ops

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4296]
We're seeing when a differential summary is produced, and that summary contains very old ops, which leads to numerous summary corruption issues due to the replaying of these old operations

PR to disable differential summaries #4285 

related summary corruption #4150 
related summary corruption #4248

**Comment by micahgodbolt** [comment]
@anthony-murphy I see that #4285 was merged. I'm guessing there are next steps before this issue is closed? Should we consdider IcM 212298442 mitigated at this point?

**Comment by anthony-murphy** [comment]
we see the summarizer loaded from an old summary, not most recent, the ops it contains are from that summary, but the base summary is correctly the previous summary. this was the first summary from that client.  a hypothesis is that we are not truncating the outstanding ops in all cases before we generate the summary.

**Comment by anthony-murphy** [comment]
Seems like differential summaries can also have negative impact on tree size. This makes sense, as it results in lots of small blobs (1-2 ops). I think we need to consider the end goal for a feature like this? at some point i don't think we should allow further modification, likley after the first differential summary, until the datastore can property summarize

**Comment by anthony-murphy** [comment]
@curtisman @vladsud @arinwt @agarwal-navin 

I don't know what the right thing to do here is. Right now, i think my preference is to just permanently disable the feature, and remove the code. Differential summaries break sequencing guarantee's, hide problems, hurt perf (real and perceived), and cause problems around GC and trailing ops.

My other idea it to make things read-only once they differentially summarizer until then successfully summarize, this could happen at the data store, or container level, but I'm not sure this is a good experience either. This would limit the above issues, but would likely be complicated to implement and enfore.

open to other idea.s

**Comment by vladsud** [comment]
It would be great to better understand the issue before we are making determination. Is this lack of test cases / stress tests? If so, do we have an estimate on how long it will take to have right test collateral to have enough confidence to enable them?

I think long term I agree with you, that this feature likely needs to go away. Some of the reasons we started on this path (like components being removed from files, including their factories) should be solved by proper versioning / converters direction.

Do we have any data on when differential summary would get involved? I.e. categorization of cases? (like a bug resulting in exception; factory removed; etc.)? That would be helpful. Or maybe if we can determine what telemetry to add to collect that kind of data, we can wait couple months and make determination based on data?

I have a feeling (without any data) that running it once and letting container to fail if summaries keeps failing after that point is good enough (i.e. covers case of removed component factory, but old file with lingering ops).

That all said, we need to balance it with a fact that any data collection / analyzes will take time / effort, and possibly we can make a guess on direction without it.

Note: Differential summaries do not break sequencing guarantee. Code that loads data store / DDS already rehydrates objects to current sequence number before it becomes visible to the rest of the system.

**Comment by anthony-murphy** [comment]
Great points. I fully understand why we went down this path, and it made sense at the time.

I'm not sure on telemetry, but we could get that added or understood. 

For the last note, there were tons on complaints about seeing ops replay when we had our spike in differential summaries, which found the corruption. So i don't think we do internal only replay. I'm also not sure that is possible or right to do internal only replay, as if the component code doesn't see all op it can break eventual consistency, and internal only replay would hide ops while bringing dss forward.

**Comment by vladsud** [comment]
getInitialSnapshotDetails():
```
                const loadedSummary = await this.summarizerNode.loadBaseSummary(tree, localReadAndParse);
                tree = loadedSummary.baseSummary;
                // Prepend outstanding ops to pending queue of ops to process.
                // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
                this.pending = loadedSummary.outstandingOps.concat(this.pending!);
```
```
    private async realizeCore(): Promise<void> {
        const details = await this.getInitialSnapshotDetails();
        // Base snapshot is the baseline where pending ops are applied to.
        // It is important that this be in sync with the pending ops, and also
        // that it is set here, before bindRuntime is called.
        this._baseSnapshot = details.snapshot;
        const packages = details.pkg;

        const { factory, registry } = await this.factoryFromPackagePath(packages);

        assert(this.registry === undefined);
        this.registry = registry;

        const channel = await factory.instantiateDataStore(this);
        assert(channel !== undefined);
        this.bindRuntime(channel);
    }
```

bindRuntime() is where we play this.pending , and realize() returns completed promise only when realizeCore() is completed. 
I'm not sure I see a way for ops to keep playing after data store is available to consumers.
 
While everything is possible :), I highly doubt it's directly impacted on how we realize data store - it always comes back at same reference seq number as the rest of the container.

**Comment by anthony-murphy** [comment]
It might just be perceived, as I imagine this would slow down data store realization, so they might pop in later than data stores that don't have outstanding ops.
