### ISSUE TITLE
Validate Runtimes notleader not called on all transitions

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4297]
notleader should fire in all cases where the client is no longer the leader. inlcuding:
- disconnect
- close
- dispose
- readonly

**Comment by vladsud** [comment]
It is definitely called on disconnect:
```
        this.runtime.on("disconnected", () => {
            if (this.runtime.attachState !== AttachState.Detached) {
                this.clearRunningTasks();
            }
        });
```
Close causes dispose, so the only thing missing is dispose.

**Comment by anthony-murphy** [comment]
Good to hear. I was unsure of the behavior, and FFX was saying it wasn't working as they expected

**Comment by curtisman** [comment]
Please add test for all these code path.
