### ISSUE TITLE
Summaries: detecting mistakes early: blob names

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4310]
As we added blob support, we introduce ".blobs" entry in root of the tree.
Older builds would assume it's data store entry and we would create data store context for it, that results in
- failure to summarize if we force full summary
- two entities (BlobManager and ".blobs" data store context ) competing when writing out summaries - putting entries into same namespace with same name.

It would be great to
1. Assert at all levels of summary that all entries are unique.
2. For Data store context to do some basic validation of a summary in constructor, not delay it to realize() method. Things like - there is attributes blob with reasonable info.

**Comment by anthony-murphy** [comment]
I wonder it we also want to blob datastores from starting with `.` and reserve that for internal blobs. It will make future proofing easier, as all blobs that start with `.` can be ignored when initializing data stores

**Comment by anthony-murphy** [comment]
#4485 is the best we can do. validating blobs would be async. I don't think we want an optimistic network call just for this, as those can impact perf/reliablity
