### ISSUE TITLE
Can buildSnapshotTree() not calculate SHA?

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4311]
Why buildSnapshotTree() is async?
The only thing that is async there is gitHashFile().
Which I wonder - why is it needed?
ISnapshotTree does not have notion of sha, it has only notion of ID. I assume we need unique IDs across possibly many calls to buildSnapshotTree(), but can we achieve that with something simpler? Like a (global) counter somewhere? Or maybe even a snapshot path (that way we can pass in "root path" of that tree, and then this function can keep adding to it, or just calculate some checksum of paths - still keeps it async, but substantially reduced calculation size.

Either way, it would be great to take a look if we can remove CPU payload here, especially given that it applies to all data stores in snapshot, even if we never realize data store (as it's called for each data store in ContainerRuntime constructor).

**Comment by vladsud** [comment]
Ah, found this item that I could not find last time.
@anthony-murphy , I believe you addressed it, feel free to resolve!

**Comment by anthony-murphy** [comment]
fixed with #4536
