### ISSUE TITLE
Investigate - DDSs that don't explicitly serialize handles do not allow handles to be in its data

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#4329]
From https://github.com/microsoft/FluidFramework/pull/3975#discussion_r521627438

DDSs such as Ink, Counter, SharedSummaryBlock do not serialize any handles. This issue it to investigate and make sure that they do not support handles in their data. Otherwise this should break GC which (currently) requires handles to be serialized.

**Comment by tylerbutler** [comment]
@agarwal-navin Have these DDSes been reviewed to see if they need handle support? Should there be some type-level way of expressing this? E.g. DDSes like this implement ICantStoreHandles or something like that?

**Comment by agarwal-navin** [comment]
I don't think the have. The idea behind this work item is that if a DDS does not support handles, we should have some way of validating that the data being stored is not a handle. I am not sure how we enforce that but this work is about coming up with that plan.
For example, a new DDS added should either support handles or not and we should make sure the right thing happens when data is added to the DDS.

**Comment by agarwal-navin** [comment]
Tracked by AB#407
