### ISSUE TITLE
ODSP in-memory caching improvements (between main & summarizer clients)

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4334]
Breaking out from https://github.com/microsoft/FluidFramework/issues/4037

Cache in ODSP driver is not shared between multiple container instances using same driver factory. Main client & summarizer double amount of memory used and number of network calls (of we need to fetch blobs).

Once that's done, we should implement cache-on-read: revert https://github.com/microsoft/FluidFramework/pull/4303/commits/05dae61db1be157be997852cb27bd62b7f55cfc4

Also we should share and trim over time other caches (like trees)

**Comment by ChumpChief** [comment]
Removing my assignment as I'm not currently planning to look at this.
