### ISSUE TITLE
Web sockets hang around even after calling "container.close()"

### ISSUE THREAD

**Issue by Zlatkovsky** [microsoft/FluidFramework#4335]
## Describe the bug

Even with calling "container.close()", websockets continue to hang around. See the screenshot below:

![image](https://user-images.githubusercontent.com/2230453/99101922-2d46ce00-2592-11eb-847f-317eea4579f4.png)

This might be causing websocket exhaustion (and just an overall unneeded load on the server).
Issue could be in the ODSP, Fluid Runtime, or socket.io -- so needs further investigation to determine what exactly is causing it.

Feel free to contact Michael Zlatkovsky (MSFT) for more details.

**Comment by jatgarg** [comment]
So as I checked we only close sockets if there is some socketProtocolError(not on container close) or if the no of references to it become 0 as we reuse socket. We decrease the reference count by 1 on container close.
As I checked we do close connections/sockets on close but in the network tab it shows up like that only.
I am also seeing that even if close the socket, it shows like that in network tab. Also confirmed with @Zlatkovsky .
So closing the issue.

**Comment by jatgarg** [comment]
@Zlatkovsky also confirmed with this:
I validated by downloading the sample app from https://javascript.info/websocket, adjusting it to have a "close" button, and seeing that while the socket is running the time says "Pending". But after I close it, an actual time (e.g., 20 seconds) appears, and the waterfall gets a blue bar at the end.
Thanks.
