### ISSUE TITLE
Spike in Error 'reentrancy not supported'

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4337]
Looking at packages\drivers\driver-base\src\documentDeltaConnection.ts it doesn;t look like we clear the connection listeners which are not tracked before disconnect, so they can still fire, and call disconnect again, which fire this assert

IcM: 213865476

**Comment by anthony-murphy** [comment]
Actually, looks like the connection listener's are clean up, but this timeout is not:
```
            // Give extra 2 seconds for handshake on top of socket connection timeout
            setTimeout(() => {
                if (!success) {
                    fail(false, createErrorObject("Timeout waiting for handshake from ordering service"));
                }
            }, timeout + 2000);
```

**Comment by tylerbutler** [comment]
@anthony-murphy Triage thinks this bug is low-pri. Let us know if we're missing something.

**Comment by tylerbutler** [comment]
Raising to medium pri based on https://github.com/microsoft/FluidFramework/issues/4337#issuecomment-729109668.
