### ISSUE TITLE
Tool to Generate Combined Summary from Fetch Summary

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4342]
It would be great to have a tool that can be run on a fluid fetch generated summary to generate a combined summary.

I would like the tool to have two modes, one that only includes `.` blobs, and one that includes all blobs. the `.` blob mode would be good for understanding structure, and all blobs would good for investigating content.

**Comment by anthony-murphy** [comment]
@markfields FYI

**Comment by curtisman** [comment]
Wouldn't a UI tool be better  to exploring a summary?

**Comment by anthony-murphy** [comment]
i'm not a big fan of UI, I can't usually combine with  other tools, and am limited by the scenarios they are designed for
