### ISSUE TITLE
NPM release does not work with pre-release dependencies

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/FluidFramework#4347]
I cut a new branch for the 0.29 release. Before I could bump it to 0.29.1 I needed to publish the npm package. Upon running pipeline I got an error that `release shouldn't contain a prerelease dependency`

**Comment by micahgodbolt** [comment]
to fix this I had to first run a publish pipeline for the pre-release dependency (routerlicious in this case). With that package now released I needed a PR to bump all of the pre-release 0.xxx.0-0 to release 0.xxx.0. This PR would only work after the publishing of the 'xxx' release

**Comment by curtisman** [comment]
This is by design to make sure that we don't release something that is unstable.
