### ISSUE TITLE
There are no UTs for packages/drivers/odsp-driver/src/rateLimiter.ts

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4357]
Also, can we add telemetry when we hit some limits? Like 6 concurrent requests?
Ideally this is flexible functionality exposed by RateLimiter, where users of it can add their own policy.

**Comment by jatgarg** [comment]
Resolving as unit tests were added in this PR: https://github.com/microsoft/FluidFramework/commit/a9b08ce59e5947a05c4fd83d830ed8285f77a35d.
Also we already log the length of wait queue for blobs fetch telemetry as that would be the place most likely to hit the limit.
