### ISSUE TITLE
Investigate why server failures cause client scheduler to assign leader twice

### ISSUE THREAD

**Issue by sumedhb1995** [microsoft/FluidFramework#4367]
## Describe the bug
On the documents listed in this IcM incident, it looks the the scheduler leader election causes the leader to be picked twice

### To Reproduce
Affected document can be found in this ICM ticket but it does not show any UX errors since the leader has been already elected:
https://portal.microsofticm.com/imp/v3/incidents/details/213502782/home

### Expected behavior
Client scheduler should only pick the leader once

### Logs
Office_Fluid_FluidRuntime_Error
| where Data_eventName contains "fluid:telemetry:AgentScheduler_FailedWork"
| where Data_error contains "false == true"
| where Data_docId == "ZyX6vqLK9FtvWv523oxFHqDiphhknltgzwaz0oNObCI%3D"
| where Event_Time >= ago(10d)
| project Data_key, Data_error, Data_eventName, Session_Id, Event_Time
![image](https://user-images.githubusercontent.com/7992711/99860684-a9b84e80-2b48-11eb-90e3-81af6d3204b8.png)

**Comment by tylerbutler** [comment]
Seems high pri since this implies the scheduler is unreliable.

**Comment by sumedhb1995** [comment]
Query to see erroring documents:
Office_Fluid_FluidRuntime_Error
| where Event_Time < ago(1d)
| where Data_eventName contains "AgentScheduler_FailedWork"
| where Data_error contains "false == true"
| project Data_docId

Sample erroring docId: OP7jlbXJAqOVNuE%2BZTDuG33qU2eMbWF8dSwayeoZ%2FxA%3D

Additional info from the ticket:

This error specifically should not be corrupting documents as it looks like it being caused by a client scheduler being handed a task that is already running on it.

Since the client is already processing the task, it should complete successfully and we see no further UX issues on the document despite the assertion since it is ignoring a repeated task.
We see the error as an ambiguous false === true instead of "task is already running" since the error is caught after being thrown from the worker
![image](https://user-images.githubusercontent.com/7992711/99716259-bd868680-2a5c-11eb-9468-2a25de05a338.png)

**Comment by sumedhb1995** [comment]
On further debugging, we can see that the key for the event is leader. This looks like a sign that the leader is being selected twice in subscribeToLeadership and the assertion being thrown is this one in scheduler.pick

![image](https://user-images.githubusercontent.com/7992711/99861672-a70b2880-2b4b-11eb-91ae-0472d31e28b6.png)

This could be due to clearRunningTasks emitting the "lost" event for the "leader" task id too late.
If we try to pick a leader again before this, this error will show

**Comment by vladsud** [comment]
No hits after November 17th,
Looking at runtime versions, last hits are for 027, no hits for 0.28 or 0.29
There were hits in 0.26.9, but there is likely no data for earlier versions as Kusto keeps only 30 days of data.
While there is no clear indication what "addressed" this issue, I definitely touched that code over last 2 months (refactored a bit) and it's possible I (not knowing) addressed the issue.

Note that fluid:telemetry:AgentScheduler_FailedWork event captures not just assert tracked here, but also other errors. There are some small number of  hits with empty error, including in 0.29, but counts are rather low, and no hits past 25th - we will look into it only it raises higher in stats
