### ISSUE TITLE
Too many files are already hitting epoch errors, even though nobody should be using it (it's in development feature)

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4384]
Office_Fluid_FluidRuntime_Error
| where Event_Time > ago(5d)
| where Data_message == "Epoch Mismatch"
| summarize count() by Data_eventName, Data_docId

Given that I 100% hit it using Fluid Fetch tool, I believe it's bug in our code!

That's 44 files in 5 days! Some file hit 40 errors!

**Comment by jatgarg** [comment]
@vladsud This is not behind any feature gate, so ffx on 0.28 FF would automatically use it.

**Comment by vladsud** [comment]
The event list (that has that error) seems really suspicious (with counts):

fluid:telemetry:OdspDriver:EpochVersionMismatch	103
fluid:telemetry:Summarizer:HandleSummaryAckError	47
fluid:telemetry:DeltaManager:GetDeltas_DocumentOpen_cancel	1
fluid:telemetry:Container:ContainerClose	6
fluid:telemetry:DeltaManager:GetDeltas_InitialOps_cancel	1
fluid:telemetry:SequenceLoadFailed	14
fluid:telemetry:DeltaManager:GetDeltas_ReconnectOps_cancel	2
fluid:telemetry:DeltaManager:GetDeltas_autoReconnect_cancel	1
fluid:telemetry:DeltaManager:GetDeltas_OutOfOrderMessage_cancel	1

Especially fluid:telemetry:SequenceLoadFailed, which just gets blobs from cache (in driver, populated from snapshot)

**Comment by jatgarg** [comment]
According to telemetry I am seeing there are more that 100 epoch errors thrown by server too: 

Office_Fluid_FluidRuntime_Error
| where Event_Time > ago(5d)
| where Data_eventName has "EpochVersionMismatch"
| where Data_error !has "Epoch Mismatch"
| summarize count() by Data_error

  | Data_error | count_
  | Error 409 from the server, msg = , type = cors | 105
  | Error 409 from the server, msg = Conflict, type = cors | 3

**Comment by jatgarg** [comment]
@ram-ramasubramanian @williamlhf @GaryWilber Can we check why we are getting 409 errors. They are of 2 types as you can see in my comment above. One has status text set as Conflict while for other it is empty.

**Comment by williamlhf** [comment]
Can you see the error message at all? Is it empty? You can use this chart to see when an Epoch mismatch got thrown: https://jarvis-west.dc.ad.msft.net/dashboard/share/1188296B

**Comment by jatgarg** [comment]
Message is empty if thrown by server or "conflict" sometimes as you can see in the query result.

**Comment by williamlhf** [comment]
If you look at this chart: https://jarvis-west.dc.ad.msft.net/dashboard/share/12A96EA, there aren't many Epoch 409s thrown in the past 7 days. Could you provide a request id that encountered 409 but does not correspond to a spike on the chart?

**Comment by vladsud** [comment]
Is this "the other 409" problem? I.e. Antler concurrency issues propagated up to client?
If yes, can we stop using 409 for this issue and start using 429?

@jatgarg , irrespective of that, can you please take a look why so many fluid telemetry events are getting this error. They do not look related in any way. And why Data_errorCode == OdspErrorType.epochVersionMismatch is not present in telemetry (I believe)

**Comment by jatgarg** [comment]
One thing, as I am checking I do see Data_statusCode == 409 in the telemetry. There is no property "Data_errorCode" recorded in telemetry for any error. I think you mean Data_errorType which should be OdspErrorType.epochVersionMismatch. But one thing it is a enum recorded as "real" in telemetry and not as string. As I am seeing Data_errorType is recorded as 0, 1, 2 etc but only for a couple of errors. I am not seeing it is getting recorded for 409.

Looking at this: "can you please take a look why so many fluid telemetry events are getting this error"

**Comment by jatgarg** [comment]
I checked some of the events and why they include epoch mismatch error in them and it make sense to me:
1.)  fluid:telemetry:Summarizer:HandleSummaryAckError 47: Here we try to refresh the summary ack and make getsnapshotcall which then goes through epoch tracker and validate epoch changes. And it has try catch so it catches the epoch error and them log it into telemetry with this event name.
2.) fluid:telemetry:Summarizer:HandleSummaryAckError 47: Here same we get the blob either be fetching from storage or from cache. In both case epoch is validated and because of try/catch we log event with this eventname.

I think we need to resolve it one by one.
1.) First we need to add more telemetry in epoch tracker to log the old and new epoch and whether fetch was from cache or server.
2.) Spo needs to fix the other 409 error which are not epoch errors.
3.) Fix this issue: https://github.com/microsoft/FluidFramework/issues/4277 where we don't validate epoch for blobs.

After all this we can check how many errors we are getting related to epoch.
@vladsud @williamlhf @ram-ramasubramanian

**Comment by vladsud** [comment]
I see more fluid:telemetry:OdspDriver:EpochVersionMismatch errors that corresponding errors responding to epoch. I assume that's expected if it happens on boot (we just clear cache and move on with data from server/TreeLatest), but worth double checking

I'm not sure how to interpret summarizer failing with epoch, but only summarizer. I.e. I'd expect main client to fail pretty quickly (because PUSH realizes epoch change), Why we do not see main client failures?
Looking at last 10 days, here is what I see:

interactive	38
noninteractive/summarizer	228

This just does not match my mental model of how errors would be distributed.
Maybe other way to say it - it looks like summarizer keeps failing, but maybe we do not receive / propagate errors from ordering server connection?

**Comment by jatgarg** [comment]
I think one of the main reasons we are seeing these errors for summarizer is due to upload summary and it is due to concurrent updates. @ram-ramasubramanian @williamlhf We need to stop throwing non epoch 409 error to client.

**Comment by jatgarg** [comment]
Closing this as no fix is required at our end for this currently.
