### ISSUE TITLE
"Stop prefetching when using ODSP driver" is missing in main

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4388]
This PR is missing from main:

[release/0.27] Stop prefetching when using ODSP driver. (PR #4051)

**Comment by ksbrar** [comment]
> This PR is missing from main:
> 
> 
> 
> [release/0.27] Stop prefetching when using ODSP driver. (PR #4051)
> 
> 

vladsud I thought the idea was to make this fix in 0.27 but make the more involved adjustments in main later on?

**Comment by vladsud** [comment]
To be honest, I do not remember all the details. I think the decision was to not have any pre-fetching for SPO, and have better algorithm for all other drivers that need to use it (like evict things from cache, only prefetch header blobs, etc.).
So I think we need it. Sorry if there was some miscommunication.
+ @tanviraumi

**Comment by ksbrar** [comment]
@vladsud, not sure of ODSP upgrading - should this change be picked to 0.28/29 as well?

**Comment by vladsud** [comment]
I'd skip 0.28 / 0.29, unless we hear feedback (again) that this is a must. In 0.27 it was a combination of many things, we we tried desperately address each direction :)

**Comment by wes-carlson** [comment]
PrefetchDocumentStorageService is causing issues with the ".blobs" tree that BlobManager puts in snapshots, should we port this to 0.28/0.29 to fix this?

**Comment by vladsud** [comment]
Well, given this new info, I think yes. @ksbrar , any chance you can take care of that.

That said, porting this change is a workaround for the issue. 
I.e. there needs to be a bug opened to fix PrefetchDocumentStorageService , right @wes-carlson?

**Comment by wes-carlson** [comment]
#4401

**Comment by ksbrar** [comment]
For completeness:
* https://github.com/microsoft/FluidFramework/pull/4394 adds the change to main (with some additional fixes).
* https://github.com/microsoft/FluidFramework/pull/4410 adds the change from main to 0.28
* https://github.com/microsoft/FluidFramework/pull/4409 adds the change from main to 0.29
