### ISSUE TITLE
Blob de-duping is broken in prod

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4389]
We spend too much time retrieving this file from SPO.
Primary reason - too many blobs.
Inspecting file we see a ton of duplicated blobs, basically telling us that dedupping in SPO driver is not working!
For example, there are a ton of "[]" blobs.

[File](https://www.office.com/launch/fluid/content?drive=b!BOyJN6Bkykm_L66EicZFaDKnQ_cydFFLqph8D-t_9vqaMsGC4Tm9RYec9Rh5aw3l&item=01N5X4JN6BX23SZCTFTFB2D5PEQUKWMZ3E&file=https:%2F%2Fmicrosoft.sharepoint-df.com%2Fteams%2FOfficeOnlinePrague%2FShared+Documents%2FFluid+Preview+Docs%2FChapter+1+Collaborative+Components.fluid&siteUrl=https:%2F%2Fmicrosoft.sharepoint-df.com%2Fteams%2FOfficeOnlinePrague&auth=2)

We need to address the issue, but also add tests to make sure we never break it again.

**Comment by tylerbutler** [comment]
@vladsud what is prod in this context? ODSP?

**Comment by tylerbutler** [comment]
@GaryWilber Is this something you're aware of?

**Comment by vladsud** [comment]
This is SPO driver bug, so it's us.
Prod - production, from our point of view - latest release branches and main.
From Bohemia perspective - production bits that use latest release branch.

**Comment by curtisman** [comment]
Is it because we disabled summary node?

**Comment by vladsud** [comment]
I do not know, but very unlikely. Dedupping happens in SPO driver, and it's independent piece of code from anything else.

**Comment by vladsud** [comment]
@jatgarg, have you had a chance to take a look? This is causing some perf loss, and blocks deeper investigation of perf (see issue #4417, #4301). So we need to address this soon.
If you are not going to get to it this week - please let me know and I'll spend some time on it.

**Comment by jatgarg** [comment]
@vladsud I looked at blob de duping last week. Actually it is not broken but the way it is implemented is not efiicient. Mainly due to limitations on server side. Ex, we can not de dup within same summary unlike r11s and spo folks recommended at that time to refer to blobs only from last summary. So I am taking a look at it and will talk to spo folks on how we can improve it and if possible de dup within same summary too.

**Comment by vladsud** [comment]
Ah, makes sense.
@marcmasmsft, @ram-ramasubramanian , we need help from you here. Client can refer to other blobs (by reference) when producing tree by using pair of summary handle + path. That way we can refer to any blob in previous summaries. But when we generate a summary where there are 10 identical blobs, but no similar blob in previous summary, then we can't dedup them, we that schema (handle + path) does not support referencing current (in-process) summary.
I think it would be great to have "current summary handle" (some special handle value) that we can use (that SPO understands) such that client can dedup all those blobs.

handle = commit ID in this context.

**Comment by jatgarg** [comment]
Also we will need that deduping in create new summary too.

**Comment by vladsud** [comment]
I think it will be generic solution, i.e. any summary (including file creation) should refer to itself.
But call out.

It is also worth pointing out that a set of tricks we can pull on client side will always be limited.
For example, summarizer loaded from a snapshot, but did not have to load full file (because only portion of the file changed).
But new blobs are created, we only de-dup against blobs that summarizer knows about (loaded into memory), and it will not be able to de-dup against existing blobs (in previous snapshot) that were not loaded by client.
It's hard to access how big the lost opportunity is here, but two possible solutions:
1. server has also code to dedup. Costly, and only a fallback (as we are paying upload bandwidth cost anyway).
2. Each blob to also contain checksum data as part of the tree structure, such that we do not need to load blobs to be able to dedup / reference them.

**Comment by vladsud** [comment]
I believe the problem of creating duplicate content within same summary is small. I.e. it needs to be looked into, but it's not the primary reason we are that inefficient today.
This conclusions comes from the fact that Chapter 1 document referenced above is not created in one go. I.e. 99% chance is that new tables, as well as new rows & columns are added over long period of time, with a lot of summaries in between "empty" and "full document" stages. As result, we have enough opportunities to dedup newly added content (especially newly added rows / columns -> newly added child Schriptor components).

Based on that logical conclusion, I traced code a bit. Couple key observations:
1. Any place where we reset this.blobsShaToPathCache, we need to have some telemetry (ideally error message?), and have follow up if we need more sophisticated logic. Currently we lose all cache data and future summaries are not reusing blobs.
   - See this.blobsShaToPathCache.clear() calls
2. I believe the logic on how we update this.blobsShaToPathCache when writing new summary is wrong. We completely replace old knowledge with new knowledge based on the blobs written in new summary. This is fine for paths that were changed, but we completely forget (destroy information) about paths that did not change! I.e. blobs that were reused in current summary from previous summary by virtue of data store / dds reusing non-changed parts of the tree. This is likely the main reason we are in such a bad shape.

**Comment by vladsud** [comment]
@jargarg, I've looked through your December items, and all of them are not that urgent, this bug is much more urgent, so I'll move it to December - I'd appreciate if you take a look asap.

**Comment by vladsud** [comment]
I forked the problem of same blobs in same summary into #4633

**Comment by vladsud** [comment]
Please note that this.blobsShaToPathCache should retain information about paths that did not change (i.e. were reused).
We need to be careful with paths that are gone (not just overwritten, but gone completely) from new snapshot - info about blobs on such paths needs to be cleared. This should not happen today, but will happen in the future with GC. Here, we might lose efficiency. That's because we remember a first path that has some blob content, even if many paths in the tree have same content. When GC deletes that first path, current summarizer will lose info about SHA of all blobs under that tree, and will stop being able to reuse them even if such blobs are present in other parts of the tree.

I think we should not concern ourselves with this when implementing first simpler solution, but need to open a bug to think about best way to solve it before GC is fully implemented.

**Comment by jatgarg** [comment]
Closed with above PR.
