### ISSUE TITLE
Design: GC using minimal memory

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#4398]
I've been thinking about how to do GC over bigger-than-memory DDSes like SharedLog/Tree and wanted to invite collaboration on the problem.  Here is a first attempt at a design that I think is promising:

### Algorithm

1.  Each DDS produces a graph of GC nodes, reusing blocks of previously serialized nodes to avoid loading unchanged regions into memory when producing summaries.

2.  During GC, we walk the graph of serialized GC nodes, inserting each node into a randomized [bloom filter](https://en.wikipedia.org/wiki/Bloom_filter) to build a conservative set of marked nodes.

3.  If during the walk we encounter a node that intersects the bloom filter, we insert it into a traditional set. If we encounter a node already in the traditional set, we've detected a cycle and stop descending.

4.  After the walk terminates, we intersect the resulting bloom filter with the total set of priorly created nodes to see what can be safely deleted.  (Nodes created after seq# of the GC graph are ignored.)

Being conservative, the bloom filter may falsely indicate some orphaned nodes were marked due to collision.  However, because the filter changes on each GC pass, previously missed nodes will eventually be collected.

### Analysis

To a first approximation, GC remains O(n) and the memory required for GC is bounded by the size of the bloom filter.

There are two pathological cases:
* A high collision rate, causing the size of the traditional set to grow until it dominates the memory cost.
    * ...could be detected and the GC restarted with a different filter.
    * ...but probably not worth worrying about if filter is reasonably constructed.
* The graph that has a single cycle from the last node walked to the root will cause the entire graph to be walked twice before the cycle is detected.
    * ...could be improved by including randomly sampled nodes in the traditional set.
    * ...but also probably not worth worrying about since the pathological case is still O(n).

**Comment by agarwal-navin** [comment]
Tracked by AB#376
