### ISSUE TITLE
Identify runtime version that created file in telemetry?

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4405]
OCE duty is rotating around finding correlations (as a way to infer possible causation) - particular error condition with things like runtime version, loader version, time, type of client, etc.
Doing so quite often quickly leads to identification of change that causes the trouble.

But issues might be discovered down the road, possibly by all clients, because "originating" client (the one who created a file) caused some trouble.

I wonder if we want to start recording (in snapshot) version of runtime that created this file, and report it in telemetry on open (as a property on Container:Load_end event).

Similar, we might want to look at other places like data stores - we write out version of snapshot into file, but we rarely bump it, and we do not report it in telemetry. As we GA, we will have zero access to user files, so we need to start thinking on what kind of data we might be getting through alternative channels that might be useful to have in telemetry.

This is just a thought :)

**Comment by markfields** [comment]
@vladsud seems like a good idea, just curious if your thinking has changed or you're just letting it expire to keep our issue list shorter, and if it comes up again we could pursue it?

**Comment by vladsud** [comment]
Simply pruning backlog - just too many good ideas :) If someone wants to take it - we can reactivate.
