### ISSUE TITLE
Move away from "global" leader election model

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4413]
Assigning to Matt based on our discussion.

ContainerRuntime exposes leader election API (**leader** property, events **"leader"** and **"notleader"** events).
This presents "global" leadership, i.e. single point that different tasks are using to assign one client to run a task.
It's "global" because single client would be running all the tasks!
Instead I believe we should refactor code to move it into reusable class, and make LeaderTaskId = "leader" provided by each user, with no defaults, I.e. each sub-system (like spell-checking) would use its own key to select task-specific leader, which allows tasks to be distributes across more clients. While it's not given it will happen right away, at least it allows us to change Scheduler in the future to implement it, without need to change API in the future.

This change has some back compat implications (I believe) that we need to consider.

**Comment by ChumpChief** [comment]
Moving to next as I'm not planning to work on this in January.

**Comment by ChumpChief** [comment]
I'll be spending time on this in March.

**Comment by ChumpChief** [comment]
Fixed by a series of changes, finished in #6542.  Specifically `TaskSubscription` is a good tool for achieving granular task assignment on `AgentScheduler`, or `TaskManager` can be used for a queued assignment strategy across granular tasks.
