### ISSUE TITLE
Implement stress test against SPO to test scalability limits

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4423]
The following operations can result in coherency failures in SPO and retries:
1. Blob upload (like images)
2. snapshot upload
3. Ops upload by ordering service (PUSH) 
4. Any file metadata changes

We need to test that
1. Client can actually cope with these issues, as some of them will be exposed to client as 429 errors
2. Validate that scalability limits are satisfactory for our product. If not, raise this issue with SPO.

I'd suggest we do this work no later than in January to have enough time to react if we learn that things are not working at scale we need.

**Comment by tylerbutler** [comment]
@vladsud Can you define "coherency failures" for me?

**Comment by vladsud** [comment]
I believe terminology comes from here: https://en.wikipedia.org/wiki/Cache_coherence
I can't find good external reference specifically for "coherency failure" / "coherency error", other than [this](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-fsshttp/6d078cbe-2651-43a0-b460-685ac3f14c45#:~:text=Coherency%20failure%20error%20codes%20are%20as%20described%20in,changes%20with%20its%20local%20version%20of%20the%20file.):
> Because multiple clients can coauthor a file, if two or more clients sent an upload request simultaneously, all requests except the first one fail with a coherency error. Coherency failure error codes are as described in [MS-FSSHTTPB]. If the upload request fails with a coherency error, the protocol client sends a download request to get the latest changes to the file from the protocol server. The protocol client automatically merges the latest changes with its local version of the file. If the protocol client is unable to do an automatic merge, it exposes the merge conflict to the user and lets the user do a manual merge. The protocol client then sends another upload request to upload the merged version of the file to the server. The upload request succeeds if the file has not been updated by another client since the last download request made by the current client.
> 
> A typical scenario for using this protocol involves a word processing application that enables coauthoring and the multiuser editing of files that are stored on a single protocol server.

The term is used rather regular in context of other systems to describe same condition - where modification / upload succeeds only "baseline reference" of the change is same as the head of commit chain, i.e. client is up-to-date.
In context of SPO, the actual management is hidden from clients, from client perspective the error shows up as result of two clients making concurrent (but independent from client perspective) modifications to a file.

**Comment by anthony-murphy** [comment]
related to #4084 and #4656

**Comment by curtisman** [comment]
@markfields might be good to break this item up into multiple issues.

**Comment by vladsud** [comment]
Worth pointing out that with SPO moving to PUSH v2 architecture, the amount of failure we are getting here skyrocketed.
SPO is prototyping with retry logic on their side to work-around some of these problems, but we should expect that problem (i.e. how storage is actually implemented and what scalability characteristics it has) to be front and center of how well Fluid can scale.

As such, having mostly driver/storage- agnostic tests here would not only help us ensure that SPO + Fluid works well, but also would help future storage implementers measure their Fluid perf, as well as compare storage offerings between each other.

**Comment by markfields** [comment]
Yes we should break this out.  I hope to work on this but I'm not willing to commit to any improvements here for Feb. ODSP's IDC team is also thinking about this, and even using our load test tool.  So I expect we'll have some good conversations this month, and may even have time to iterate on the tool and its capabilities and the scenarios it simulates at scale. Moving to March because I do believe this is the next priority, just trying to be realistic about Feb resourcing considering the other items* higher up on the backlog.

cc @curtisman, @vladsud, @anthony-murphy 

\* Prerequisite things like getting the load test running in a Pipeline again (https://github.com/microsoft/FluidFramework/issues/4662), getting our e2e tests running against any server (https://github.com/microsoft/FluidFramework/issues/4660), and collecting telemetry for those e2e tests and the load test when they run (https://github.com/microsoft/FluidFramework/issues/4661).

**Comment by markfields** [comment]
PS - for further inspiration, see also https://github.com/microsoft/FluidFramework/issues/4084 which I'm closing out as a dupe of this.
