### ISSUE TITLE
Limit the usages of embedding the version in code

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4428]
Our team leverages long term caching of javascript assets via webpack. The goal is to minimize the amount of bytes we require repeat visitors to our site to download between deployments. One thing I've noticed is that Fluid Framework frequently embeds npm package versions in the JavaScript files. For patch bumpes in particular, this is problematic because often times the contents of the modules do not change at all, but the version number is incremented. From an end user perspective, the code is practically the same, but we've invalidated the bits they already had in the cache.

Can we revisit the strategy of embedded the version number so frequently into the code? If we need this for logging, can we put this in just one place rather than in every single npm package?

![image](https://user-images.githubusercontent.com/1581488/99827550-a1432200-2b0e-11eb-95a0-5e404844a567.png)

**Comment by curtisman** [comment]
@christiango How well does webpack maintain the same chunking and stable code generation from build to build?
How do you detect some chunk not change and be reused between your build?

**Comment by christiango** [comment]
It's gotten pretty good since webpack 4. We don't manually check that the chunk isn't changed between our builds, we upload our JS files to the same folder in the CDN and part of the filename is a hash of the content.

Here are more details on webpack caching: 
https://webpack.js.org/guides/caching/

If we are able to keep most of these versions out of the bundles, we can probably offset some of the bundle size impact of Fluid Framework, especially for hot fixes.

**Comment by tylerbutler** [comment]
Triage: We're won't fixing this because we're moving towards independent versioning for each package, and we're not aware of any good ways to centralize this value for telemetry purposes when all packages are independently versioned.
