### ISSUE TITLE
Explore moving Quorum/Audience and dealing of "connected" event into DeltaManager

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4429]
I think there has to be a single layer that controls connectivity eventing / states and clientID switching.
Right now DeltaManager (DM) & Container have certain assumptions about each other behavior, like
1. DM does not know about "connected" events, but yet it does a lot of things that take it into account. For example, we switch this.clientSequenceNumber only we send op, because the only safe way where we can change it when we moved to "connected" state, not just connected to socket.
2. It's possible that we can remove setConnectionState() API and instead stick to "connected" event from delta manager and all layers that need to subscribe to it? This needs to be very carefully evaluated, as today we assume container runtime was the very first user who has a chance to observe this event, not DDSs.
3. Solution for https://github.com/microsoft/FluidFramework/issues/4399 will add more connections between these two layers
4. We pass Quorum & Audience to container runtime and data stores, but if it was on some delta manager interface, we would not need to pass it separately, as all "users" within container should be able to read this data.
5. updateQuorumJoin & updateQuorumLeave examples of callbacks we will keep adding to this layer if quorum is abstracted away

**Comment by ChumpChief** [comment]
On the surface I'm kind of opposed to this.  My perspective is for DeltaManager to be specific to the local client's connection to the service so bringing in data structures and knowledge about other clients feels like we're mixing concerns.  I'll think about it a bit more though.

**Comment by vladsud** [comment]
I hear you, but I also worry of DeltaManager having a ton of callbacks (like # 5 I've just added in the list above) and complexity of this code not decreasing, but increasing.
Maybe other way to think about it - some of the logic in DeltaManager has to know about quorum. If we can isolate it / move away, leaving bare bones of connection - that would be great too. But then Container becomes bigger. I think better model is to move some of the existing DeltaManager logic into some middle tier between driver and rest of loader, and combine all quorum / connected logic in one layer.

**Comment by ChumpChief** [comment]
Moving to next as I'm not planning to work on this in January.

**Comment by vladsud** [comment]
Keeping it alive, as Matt is working in this area, so we should re-evaluate this issue once the design is closer to being complete.
