### ISSUE TITLE
PrefetchTree is creating too many timers

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4430]
For large documents, we are seeing over a second of continuous CPU time spent on PrefetchTrees
![image](https://user-images.githubusercontent.com/1581488/99832342-3d702780-2b15-11eb-927c-c37863aa19e8.png)

On closer look, it's clear we're spending too much time setting and clearing timers:
![image](https://user-images.githubusercontent.com/1581488/99832759-e159d300-2b15-11eb-8176-2370ec455964.png)

The timer management is taking about 75% of all the time for prefetchtrees. For this complex document I profiled, prefetch trees takes about 1 second.
![image](https://user-images.githubusercontent.com/1581488/99832862-10704480-2b16-11eb-96d7-a15bf06a99cd.png)

**Comment by christiango** [comment]
FYI @vladsud this is from the document you shared with me that had poor render + post render performance

**Comment by jatgarg** [comment]
We have disabled prefetching for odsp in case policy is set. @ksbrar Can you give more info to @christiango for this?

**Comment by christiango** [comment]
Should we perhaps have better defaults in the driver? I expect this would impact everyone.

We also do need to follow up on the timeouts here since those that do need this behavior will have very poor performance for larger documents.

**Comment by vladsud** [comment]
I've provided feedback on that in PR :)
Simple approach with such timers almost never works. While "system" can do better, there is usually substantial overhead where solution is required in "user" mode.
Canonical solution we do here - separate tracking of "system" timer (the actual timer object) and its expiration and "user" portion of it (actual requirements of particular system, like blob cache). Changes in "user" timer should result in moving "kernel" timer only if "kernel" timer is about to fire (let's say in next 300ms), otherwise we let it fire and reschedule to final "user" time.
That way we amortize calls to timer API with close to O(1) result for many workloads.

**Comment by vladsud** [comment]
Given this is very recent regression, I've put November as a milestone.

**Comment by vladsud** [comment]
Sorry, just saw Jatin's comment. It is orthogonal to prefetcher layer, any read will cause timer activity, the core of the problem is in ODSP driver.

**Comment by ChumpChief** [comment]
Looking -- also do you have a link to the document that the above trace is from?  I'd like to understand the usage here better.

**Comment by vladsud** [comment]
I believe this is [Chapter 1 document](https://dev.fluidpreview.office.net/p/c3BvOmh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQtZGYuY29tL3RlYW1zL09mZmljZU9ubGluZVByYWd1ZQ%3D%3D/b!BOyJN6Bkykm_L66EicZFaDKnQ_cydFFLqph8D-t_9vqaMsGC4Tm9RYec9Rh5aw3l/01N5X4JN6BX23SZCTFTFB2D5PEQUKWMZ3E/Chapter-1-Collaborative-Components)

**Comment by vladsud** [comment]
And based on earlier discussion, a lot of expensive work happens after initial render - the document is not responsive for a while, and that's I think where timers are firing (though I have not looked at profiles- this is my guess based on looking at this doc last week before these changes)

**Comment by ChumpChief** [comment]
Fixed in main -- @christiango are you also wanting a port to 0.29?

**Comment by christiango** [comment]
Thanks for the quick turnaround. I think we'd like to take this and the fix for #4433 in a 0.29 patch if we think that's a safe thing to do.

**Comment by ChumpChief** [comment]
Opened #4443 for porting this one, I'll defer to @jatgarg for #4433.

@sumedhb1995 FYI on 0.29 patch request
