### ISSUE TITLE
Rename SummaryTree to distinguish it from ISummaryTree

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#4434]
These should be renamed as per https://github.com/microsoft/FluidFramework/pull/4403#discussion_r527936677

**Comment by curtisman** [comment]
Related #4683

**Comment by arinwt** [comment]
I feel like `SummaryTree` is really just `Summary`. That's the possible returned summary type (either handle or tree).

From the comment, it could look something like this:
old name|old tree only|new name|new tree only
-|-|-|-
SummaryTree|ISummaryTree|Summary|ISummaryTree
ISummarizeResult|ISummaryTreeWithStats|ISummaryWithStats|ISummaryTreeWithStats
IContextSummarizeResult|IChannelSummarizeResult|ISummaryWithGcData|ISummaryTreeWithGcData
ISummarizeInternalResult|_none_|ISummarizeInternalResult|_none_

**Comment by agarwal-navin** [comment]
that sounds good. summarize will stop returning GC data so the third row won't be needed anymore.
