### ISSUE TITLE
Add messages to all asserts

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#4439]
Every call to `assert` or one of its functions in our code should have a message. We should simply modify our assert function in our [assert.ts](https://github.com/microsoft/FluidFramework/blob/716eb9e1b7c90ab4e1b1fa4f6ce78ed13e3b6d9b/common/lib/common-utils/src/assert.ts#L12) to require message.

There have been two errors in two days that I've personally investigated where the lack of message caused trouble, since the resulting error message in the logs is something like `false == true` or `undefined == true`. So this can conflate unrelated callstacks, or simply obscure the failing line of code.

**Comment by markfields** [comment]
assert.ts is in common-utils, so we should probably make effort to update all usages to include the message first before making the parameter required, since that would add quite a cost to bumping common-utils version.

**Comment by curtisman** [comment]
One consider is code size, since in assert are not "compiled" away.  So all the string added will increase package size for the user.

**Comment by DLehenbauer** [comment]
+1 to Curtis's feedback (see #3132.)

**Comment by vladsud** [comment]
Well, we know where it ends :) Removing debug strings quickly becomes # 1 opportunity to reduce binary / package size. We have build solutions in this space over years. For example, devmain uses tagging mechanism that assigns unique tag (DWORD, shows up as 'abcd' in C++ code) to each (ship) assert, as a post-process step (robot submitting changes). This is rather easy to replicate. The only complication is multi-repo (and desire not to have common DB / sync), which has solutions (tag consist of two parts, first part is unique per repo).

Before moving forward with change, it would be great to access the impact to bundle size - of existing code and incremental impact of this PR. In my view the fact that occasionally we need to differentiate two asserts in same function does not trump size concern.

**Comment by heliocliu** [comment]
Another +1 to the size feedback, particularly because changes like this lead to a death by a thousand cuts situation, and can become incredibly time consuming to fix later.

I remember for the devmain tags, they got put into one of the CPU registers so we got it as part of a barebones crash report but probably not super relevant here.  The tags also never get recycled 🤔

**Comment by anthony-murphy** [comment]
We have no choice here. we need messages in all asserts. we can build a tagging system later, but we don't have it now, and we can't ship with empty messages and we can't diagnose or debug on minified code without them

**Comment by markfields** [comment]
I agree it's worth some cost now.  Let's get the bundle analysis on the PR so we can quantify that cost, and I'll open an issue for an assert/error tagging system.

**Comment by anthony-murphy** [comment]
building a rudimentary tagging system should be easy. just a script that runs as part of our release process, but we still want messages, as the tagging script can move these to comments

**Comment by anthony-murphy** [comment]
also. we could get rid of assert, and use logger.assert (which doesn't currently work) this brings event context, like the concatenated event name. this makes the tagging script even easier as global unquiness is less important.

**Comment by DLehenbauer** [comment]
FYI - A couple of alternatives I've thought were worth looking at:

https://www.stacktracejs.com/ - programmatically returns sourcemapped callstacks.
https://github.com/power-assert-js/power-assert - captures the source of the failed assertion, showing variables and current values.  (Also claims to support sourcemaps.)

**Comment by vladsud** [comment]
I want to poke here a bit more. I think "we have no choice" is not really true. That basically tells me that our current system of collecting "dumps" is not adequate and should be improved. Is it really that hard given version and minimized stack to point to particular like of code where assert is placed?

I'm also not clear if we are saying that measuring impact happens before merge or after. I believe it should happen before, and include holistic analyzes of impact of all assert strings (existing and being added) to help us clearly articulate overall direction.

@christiango - FYI, you might already have answers around impact on bundle size, as well as what's missing in terms of diagnostics not to require messages in final bundles.

BTW, I agree that ideal solution is the one where strings are there, but some (bundling?) process augments them to not pay the cost.

**Comment by anthony-murphy** [comment]
> That basically tells me that our current system of collecting "dumps" is not adequate and should be improved.

agree completely. but we are not there today, and unless someone can commit to doing the work to get us there today, we need to messages

**Comment by anthony-murphy** [comment]
I agree with all the concerns in this thread, but i'd rather start these conversations from a place where we are confident in the ability to debug and diagnose errors, and from my experience we are not there. i've been stung by minimized callstacks that fail to deminifiy a number of times. The only alternative i see is someone taking strong ownership of those cases meaning if a call stack can't be linked to specific code in a specific version they will own figuring out the issue.

**Comment by christiango** [comment]
To answer @vladsud's - Yeah, these asserts will add up and I also don't agree that we don't have other choices rather than putting messages on every assert. We're already over budget on bundle sizes for Fluid Framework, especially for mobile scenarios.

There are a few things I could recommend:
* Have folks dive into "why" the callstacks aren't being deminified sometimes. The tool for deminifying callstacks was something that was an FHL project, it doesn't have active funding, but that doesn't mean we can't have folks continue to improve it. Do we have an example of a stack trace that we can't deminify today with tooling?
* Don't include verbose messages and instead have tags, as others have alluded to here. React does this:
* https://reactjs.org/blog/2016/07/11/introducing-reacts-error-code-system.html

**Comment by anthony-murphy** [comment]
I agree there are other, and better solutions, but these are not funded. Happy to view adding messages as a short term stop gap as next steps on figured out, and then we can go remove all the messages.

**Comment by anthony-murphy** [comment]
filed #5409 as i think it is the most actionable solution for the fluid framework.

**Comment by christiango** [comment]
Yes, but the short term solution does come with a performance penalty. Do you have examples where the deminification doesn't work? A call stack alone should be enough to know which assert is failing

**Comment by anthony-murphy** [comment]
I don't off hand, but I know I've struggled in the past. There were issues around multiple asserts in a method, and minification hiding method information and failing to deminify. These were generally ok since we had access to the document and could debug, but if we didn't have document access we wouldn't have been able to make much progress without adding messages.

**Comment by anthony-murphy** [comment]
Update here. I'll wait until after we cut 0.36 tomorrow to check this in. But I still think we should go forward. This will give us the 0.37 release to do something like  #5409, but as of now that work is not funded.

**Comment by curtisman** [comment]
If we are going to strip it out and replacing it a number/code, can't we just do it up front by declaring a const enum at the top of the file and use those there?
