### ISSUE TITLE
Data Store Registry should expose subregistry logic

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#4472]
The Fluid Framework code internally accepts nested component factories (i.e. subregistries) and operates on arrays of component type keys, not just single strings. In order to use the runtime data store registry effectively (without reimplementing subregistry logic), it would be great if the same sort of helpers/component array keys were exposed at this level instead of a single string.

For example get(string) would turn into get(string[]), so it can be used for loaded subregistries and logic that has already turned all strings into its runtime array.

Also for iteration purposes, in order to iterate over the registry, the registry should provide more than just top level entry iteration and also associate the proper array keys with each iterated entry.

**Comment by leeviana** [comment]
I believe this logic already exists somewhere in the runtime code when it processes component type arrays and just needs to be moved to the shared helper layer so that all code that works with the registry can use it. :)

@vladsud @anthony-murphy

**Comment by leeviana** [comment]
Related to #4193 where we want to augment the component/subcomponent registry pattern provided by the framework without reimplementing the entire registry and fluidExport patterns.

**Comment by anthony-murphy** [comment]
Registry entries can implement IFluidRegistry, so you can already walk the path. Registries themselves are not aware of sub registries, this is by design.  I'm not sure what the ask here is, or why it is needed.

**Comment by leeviana** [comment]
Hmm, that makes sense, so for at least get() we can just do a series of gets and I think it'll be fine.

We still might have a problem of iteration though, if we want to iterate through all entries. But thinking about this, it makes sense that we might only need to iterate through two lists, the top level registry and the sub registry instead of the entire swath of registries, which would also make this use case more manageable with just a series of gets.

Thanks for the suggestions, I'll try them out when we integrate with Vlad's change and get back to you if there's something missed in the helper. :)
