### ISSUE TITLE
ODSP Driver: Two TreesLatest calls are observed when loading file 

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4473]
They have same callstack, and are happening next to each other.
There should be only one call loading the file. And even if summarizer is loaded right away (does not look like it), it should use cached version.

Reproducible in staging, on a new empty file.

  | m | @ | bohemia.js:2
  | g | @ | bohemia.js:2
  | (anonymous) | @ | bohemia.js:2
  | (anonymous) | @ | bohemia.js:2
  | Promise.then (async) |   |  
  | schedule | @ | bohemia.js:2
  | fetchAndParseAsJSON | @ | bohemia.js:2
  | (anonymous) | @ | bohemia.js:2
  | timedExecAsync | @ | bohemia.js:2
  | fetchSnapshotCore | @ | bohemia.js:2
  | async function (async) |   |  
  | fetchSnapshotCore | @ | bohemia.js:2
  | fetchSnapshotWithTimeout | @ | bohemia.js:2
  | fetchSnapshot | @ | bohemia.js:2
  | (anonymous) | @ | bohemia.js:2
  | timedExecAsync | @ | bohemia.js:2
  | (anonymous) | @ | bohemia.js:2
  | p | @ | bohemia.js:2
  | getVersions | @ | bohemia.js:2
  | getVersions | @ | bohemia.js:2
  | getVersion | @ | bohemia.js:2
  | fetchSnapshotTree | @ | bohemia.js:2
  | load | @ | bohemia.js:2
  | async function (async) |

**Comment by jatgarg** [comment]
Both of them seems to be from 2 different containers. It looks like 2 interactive containers are getting created.

**Comment by vladsud** [comment]
Thanks @jatgarg!
@christiango - can you please take a look? Is this expected? Even if it is, it does not feel right for many reasons (impacts interactive boot, we hit storage extra time for nothing, etc.)

**Comment by christiango** [comment]
I don't think this is expected. Can we have one of the OCEs take a first look? Either FFX or FF?

**Comment by christiango** [comment]
Could it be a bug in the rate limiter? I'm seeing it on the top of the stack in both calls. 

Any reason you thought I should take the first look here @vladsud? Seems like it is in the runtime layer.

Here is an image from the profile I took that give a sense of timing, the second call is around the same time as join session

![image](https://user-images.githubusercontent.com/1581488/100164911-cb2d7900-2e6d-11eb-9c5f-19f25cc7656b.png)

**Comment by jatgarg** [comment]
No, I am seeing 2 containers getting created having different containerId. So I don't think rate limiter has anything to do with this.

**Comment by christiango** [comment]
Here are the callstacks.
First one:
![image](https://user-images.githubusercontent.com/1581488/100165264-ab4a8500-2e6e-11eb-88b3-9f1b07b29fb9.png)
![image](https://user-images.githubusercontent.com/1581488/100165333-dd5be700-2e6e-11eb-8715-3195b45ad5de.png)

Second one:
![image](https://user-images.githubusercontent.com/1581488/100165348-e6e54f00-2e6e-11eb-8889-9f228c6609d0.png)

**Comment by christiango** [comment]
Seems like when we try to load a component from an existing container, it is loading the container again.

**Comment by christiango** [comment]
It's late in my timezone, so I'll be getting offline. Can the FF team take point here for the initial investigation? I can pull in folks from the app side tomorrow if we have a root cause there

**Comment by vladsud** [comment]
Yes, @sumedhb1995 , any chance you can take a first peak at where the problem is, and if possible, better understand where regression came from? Thanks!

**Comment by christiango** [comment]
It is something on the Fluid Preview side, we've escalated it as a livesite incident
