### ISSUE TITLE
Refresh PAT for build-docs' GitHub Action step

### ISSUE THREAD

**Issue by sumedhb1995** [microsoft/FluidFramework#4478]
## Describe the bug
The PAT used in build-docs pipeline's GitHub Action step expired, causing the pipeline to fail for merges to main from #4458 onwards

### To Reproduce
1. Sample failure can be viewed here https://dev.azure.com/fluidframework/internal/_build/results?buildId=10552&view=logs&s=926788dc-3843-5763-e5bc-e1a2e68d811c

### Expected behavior
PAT should be refreshed and build pipeline should pass

**Comment by tylerbutler** [comment]
This should be resolved. I'll leave this open for the time being while I verify the pipeline works as expected.

**Comment by tylerbutler** [comment]
Fix works as expected; closing issue.
