### ISSUE TITLE
Loader should return cached container

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#4489]
When something like Loader.request() is called, it does not utilized the cached container feature because of various design problems. This means we cannot rely on the Loader to reliably give us back the same instance of a loaded container which causes performance issues (multiple trees/latest calls etc.) if we want to use Loader.resolve() to get a container and Loader.request() to get a component or any other flow that may use the Loader multiple times.

More details from Vlad:
Unfortunately it is pretty broken, as Container exposes a bunch of state (forceReadOnly, paused, etc.) that different users may not agree on. This is known, and we plan to look into it in some future, but no concrete plans for now. As result, I believe right now we are not caching containers, so two calls will result in two containers loaded (at least when they are paused, not sure what happens next).

@vladsud, @anthony-murphy, @agarwal-navin

**Comment by anthony-murphy** [comment]
This doesn't seem that hard to fix. I see two options

1.  Ignore options and always use cache, unless nocache specified
2. Provide explicit header to use cache

I prefer the first. The host owns the loader and getting a container. It should know if it uses pause or reconnect, and likely wants the same behavior for all containers, and has the nocache options if it doesn't. Even beyond the loader options there are a bunch of scenarios that will affect all consumers of a container, like close, so it doesn't seem necessary to make loader options special.

**Comment by leeviana** [comment]
Yeah, I'm a fan of simplicity and I think 1) "ignore options" should work. :)

We can dig deeper into the pause flow to get more details on how this will work:

-> Loader.resolve() with pause=true -> container (paused)
-> Loader.request() -> component. same container used and same pause state as previous.
-> unpause container
-> both container/component work and are usable and are based on the same container instance.

This fits the model, right? I think it also makes sense that if the unpause container happens between resolve and request that the container state after Loader.request() is still unpaused, which also fits into the "just return the container" flow. Do you agree?

**Comment by anthony-murphy** [comment]
Exactly. pause only represents the initial state, think of it as start paused. if it already started, then it doesn't really apply.

**Comment by leeviana** [comment]
Works for us, I think :D Let's let Vlad chime in on other design architecture things we should keep in mind.

Do you think this could be a short term fix? If so, fixing this plus https://github.com/microsoft/FluidFramework/issues/4491 would essentially close https://github.com/microsoft/FluidFramework/issues/4490 again, which is only necessary as long as we can't use Loader.request() for our needs.

**Comment by anthony-murphy** [comment]
i much prefer that over something like #4490 as the less coupled to url format the host can be the better.

**Comment by vladsud** [comment]
I think full solution would require the following steps:
1. Move all "stateful options" from Container to Loader. Things like forceReadonly() (not sure what other things like that are there)
   - it applies to all "guest" containers as well, and Loader is the right "context" here.
2. Make sure that when Container is closed, it gets removed from cache
   - I believe it's not the case today
3. When Loader is created, allow the caller to specify if caching is enabled or not.
   - This setting is applied to all containers, no matter if starting paused or not, loaded from latest version or not.

Unfortunately, there is no easy way to trim cache / evict from it. # 2 above partially solves it for scenarios, but as a general mechanism, JS lacks proper primitives (like weak references, "reversed" WeakMap would be great) to implement any reasonable caching strategy.
Consider scenario where "guest" component is deleted from container - there is nothing in the system to realize that and remove such container from cache. Maybe in the future we may connect it to GC feature and implement proper cleanup (through ref-counting, but I doubt it (as GC is tied to summarizer who does not care about external URIs)
So I'm a bit skeptical this area is "fixable" and personally I'd prefer to cut whole thing out, but I do not have an alternative to implement sharing of containers for guest components (or similar scenarios).

+ @curtisman, as we discussed it in the past.

**Comment by anthony-murphy** [comment]
That seems mostly reasonable, had similar thoughts myself. Even a cached loader will still need to support no-cache for the summarizer. All existing scenarios use their loaders 1-1 with containers, so just ignoring options to start caching could be as easy first set, but it also shouldn't be too difficult to make those loader options either.

**Comment by leeviana** [comment]
Yes, this sounds reasonable to me. I don't think it's a functionality breaker to have containers that aren't closed hang around in the cache even in the page removes references to it (this can happen for non-Fluid canvases too, like a container loaded in an OWA email and then removed... if the Loader reference is still around the container cache would still be around). It's just a nice-to-have optimization/cleanup, could even be manually triggered via some Loader mechanism for hosts that really care as a starting point.

**Comment by leeviana** [comment]
Making a note here from the postmortem to also add some automation that ensures container caching actually functions when this work goes in.

**Comment by anthony-murphy** [comment]
I chatted with @skylerjokiel a bit about this issue, and i think @heliocliu can pick it up as he will be looking at some refactoring in this area, so this seem like a good issue to start with.
