### ISSUE TITLE
Loader.request() does not handle component query params properly

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#4491]
When we briefly switched over to using Loader.request() a feature in scriptor stopped working that relied on query params on the component path. i.e. componentId?queryParam1=foo&queryParam2=bar.

This leads me to believe that whatever logic in Loader.request() that pulled out component path information did not accurately transfer query param information.

**Comment by leeviana** [comment]
Maybe related to this? https://github.com/microsoft/FluidFramework/issues/2677

@agarwal-navin @chensixx

**Comment by chensixx** [comment]
request parser **should** always return the query params. which feature exactly is having issues? maybe some debugging can pin point where the problem is

**Comment by leeviana** [comment]
When we call Loader.request(<fulldriverURL>), where the full driver URL is a sharepoint URL with a data store path that has query params, I have strong reason to believe the actual request URL that ends up getting routed to the component doesn't have the query params.

So for example if the driver URL contains "componentId/?queryParam1=foo&queryParam2=bar", what gets passed to the request() method in the component is expected to be "/?queryParam1=foo&queryParam2=bar" but instead isn't so. Since we control the load handler logic (I hope, otherwise there are other problems) and it's the same in all scenarios that means the path that was passed to container.request() somehow lost the query params. It's probably pretty easy to debug into this specific case to see where the params are being lost, but if @agarwal-navin happens to know exactly where the Loader.request() component url handling logic is, it might be just an easy "unit test & fix" issue in the framework code.

Also it's completely possible the url manipulation logic where it's being dropped isn't using request parser at all for its helper logic, so it might not be related and just be a similar url handling bug.

**Comment by agarwal-navin** [comment]
@leeviana You are right, it should be easy enough to figure out where this is broken. @chensixx and I will take a look and get back to you.

**Comment by leeviana** [comment]
Just leaving a note on this issue about adding a unit test as well, one of the followups from the postmortem :)
