### ISSUE TITLE
Hosts require lightweight way to detect if a URL is supported by resolvers

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#4498]
Many hosts have strict requirements on the size of their "isFluid" check for links. Most notably Teams and mobile scenarios are particularly concerned with bundle sizes and Win32 and other apps want to optimize/potentially rewrite these checks in their native language to be as performant as possible because it needs to be run on every link that passes through their canvases without extreme overhead like loading sharepoint sized dependencies or spinning up a WebView.

Today we work around this by manually calling a standalone method from the odsp driver folder "resolveDataStore". Once the need for us to manually retrieve data store path information from urls is removed (https://github.com/microsoft/FluidFramework/issues/4490), this check will only serve as a glorified "isThisAFluidSPOLink" for hosts. This seems like functionality that should come from the resolver shape itself, not arbitrarily created as a one-off helper.

The traditional Fluid Framework way to implement this check would be to call ResolverImplementation.resolve(URL) and see if it returns undefined. Some resolvers do this better than others (some resolver implementations today try to resolve all sorts of things it doesn't actually support). However, even/especially the resolvers that implement resolve well (like the odsp resolver), there is the matter of the resolve logic being too heavy computationally for a quick check/rewrite (think kicking off sharing link generation, or tenant credential validation etc.) and too large in bundle size (the entire resolver class and all of its dependencies are imported along with that check).

So instead today we basically have something like this in our code that all hosts use in this shape:

```
import { resolveDataStore } from '@fluidframework/odsp-driver/lib/resolveDataStore'; // notice we don't import the whole package

isThisProbablyAFluidUrl(url) {
   if (resolveDataStore(url) {
      yes, this is probably a fluid URL
   }

   no, at least today if you're using SPO this is probably not a fluid URL
}
```

This is a short term solution to the problem of giving hosts a lightweight way to perform an isFluid(url) on all links that pass through their canvases but as you can see, it's tied to a specific hardcoded resolver that we have explicitly built in support for and it relies on a method exported from the driver package that there is no contractual guarantee/prompting for storage implementers to know about this need an implement it.

What we would like ideally is for all resolvers to implement something of the shape "lightweight check for URL likelihood" and export it in a way that it is tree-shakeable and light for hosts to use.

@jatgarg @anthony-murphy

**Comment by leeviana** [comment]
oh... I don't think this is a bug, it was probably just the the top template button for issues and I didn't know it would add a label, hahaha. This is more like a feature request :P

**Comment by leeviana** [comment]
There are a couple driver URL specific things we are designing that probably fit into this "lightweightUrlResolverSpecific" precheck method. It would be great if this check also gave us the "containerPackageName" hint if any and any "preconnect" URLs that can be used to for faster driver connection performance.

**Comment by anthony-murphy** [comment]
I don't think this can or should be part of IUrlResolver, as it may not be possible for all servers to support a synchronous and cheap api like this, and the runtime doesn't require it.  Additionally, adding to the IUrlResolver shape isn't really compatible with being light weight, and tree shakable. We can add an interface, but it won't be required. It will be up to the host or their meta resolver to combine and check these for whatever endpoint they support, and that support this kind of functionality

**Comment by leeviana** [comment]
Yeah, I don't think this can be part of the interface, was just looking for suggestions to making something like this more noticeably "recommended" by resolvers somehow. What we can do today is craft this method explicitly in the odspurlresolver folder (and maybe the local and FRS drivers although I don't think either have particularly good url validation logic today) and hope that anyone else creating a resolver will pick up on the pattern?
