### ISSUE TITLE
Plan & Implementation for sub-data store Garbage Collection 

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4499]
We need to design and implement sub-data store Garbage collection.
Data store can implement a collection of items, where items are referenced by ID (uuid), and ID is the key into root map (or similar structure). Such items can be exposed by data store to outside world via request route.

As result, we need solution for cases like that.
Relevant discussion that is useful reference: [link](https://office.visualstudio.com/OC/_git/office-bohemia/pullrequest/624041?discussionId=13556266)

The core of the problem is that GC at other levels (data store, DDS) do not chance container itself. I.e. summarization process simply marks parts of the tree as deleted, but no changes of content happens.
With sub-DDS GC, we need to (eventually) remove content from DDS, which requires ops, which likely needs to be some process asynchronous to actual (original) summary generation. It should also follow other GC processes around when content can be physically deleted (as non-referenced content maybe accessible by undo/redo, copy/paste).

At minimum, we should allow data store to know about such content, such that it's excluded from other activities (like search contract).

**Comment by agarwal-navin** [comment]
Tracked by AB#377
