### ISSUE TITLE
We have two implementations of GarbageCollector class for an in-memory cache

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4500]
Can we rationalize this?

**Comment by jatgarg** [comment]
@vladsud Sorry I don't know anything about this as I haven't worked on it.

**Comment by vladsud** [comment]
https://github.com/microsoft/FluidFramework/blob/0076d7e0c23fffcf5f6df042a1f49a6838c1b111/common/lib/common-utils/src/promiseCache.ts
https://github.com/microsoft/FluidFramework/blob/ae0afbe51902a335b1a6115651e35c9d45bac4df/packages/drivers/odsp-driver/src/odspCache.ts

Related PRs:
https://github.com/microsoft/FluidFramework/pull/1770
https://github.com/microsoft/FluidFramework/pull/2240

**Comment by markfields** [comment]
Oh yeah, thanks for opening, I should have opened an issue I guess and not just left a comment in the code :)

**Comment by jatgarg** [comment]
comment
