### ISSUE TITLE
Clarify/Improve Container.forceReadonly usage during connect

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#4501]
Apparently calling `Container.forceReadonly` during the load sequence doesn't work, which feels a bit surprising. @kmui reported that calling it after the "connected" event comes back doesn't work, but wrapping it with a setTimeout() after the "connected" did work.

Either the API should work whenever it's called, or it should be clearly documented how/when to use it. See also, documentation [here](https://github.com/microsoft/FluidFramework/blob/main/packages/loader/container-loader/README.md#Readonly-states).

cc @vladsud as FYI

**Comment by curtisman** [comment]
What exactly doesn't work?

**Comment by kmui** [comment]
I expect "readonly" event to fire due to readonly bit being flipped.
calling forceReadonly did not trigger the readonly event to fire when calling it immediately after the container resovles, or even right after "connected" event.

**Comment by vladsud** [comment]
Where do you listen for "readonly" event? I.e. is it Container, DeltaManager, or something else?
Does Container.readonly property reflects changes or also broken for you?

**Comment by curtisman** [comment]
@kmui can you provide additional information or a repro?

**Comment by kmui** [comment]
Container.readonlyPermission reflects the correct state

Container.readonly event was never triggered.

**Comment by vladsud** [comment]
I believe we had a discussion about it somewhere else, but I do not remember details.
More detailed description would help, as not clear what exactly does not work (event where? I believe events are fired only by delta manager, which might be a gap, but they do fire).

Event better - please add UT to demonstrate what does not work.
There are already UTs in this space, so it should be rather trivial to add, and will be the ultimate test of the fix working.
