### ISSUE TITLE
Epoch data is incorrect, causing failures

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4513]
This does not look right:
eventName = fluid:telemetry:OdspDriver:EpochVersionMismatch
clientEpoch  = 17c8c132-38aa-490d-a9ea-4e0034ae2c53
serverEpoch = 17c8c132-38aa-490d-a9ea-4e0034ae2c53,17c8c132-38aa-490d-a9ea-4e0034ae2c53

Why epoch value is repeated twice, causing our check to fail and raise error to user?

**Comment by jatgarg** [comment]
I have brought this to attention of odsp folks. We get server response from network call response. @ram-ramasubramanian

**Comment by vladsud** [comment]
Can you please assess user impact? I.e. that causes failure to open document. If too many sessions / documents are affected, it's possible we need to open ICM ticket / do something urgent about it

**Comment by jatgarg** [comment]
Yes, I am looking at it today.

**Comment by jatgarg** [comment]
I am seeing about 900 container close in last 7 days because of this. So I disabling the epoch check on client side till server fixes the issue.

**Comment by jatgarg** [comment]
Disabled client epoch validation for now until server fixes the epoch returned in response.

**Comment by jatgarg** [comment]
Closing as fix is being put on server side.

**Comment by vladsud** [comment]
Did we enable it back on client? If not, what is the issue tracking it?
We have to have an issue not to forget about it (and resolve in PR that re-enables it).
Reactivating, with assumption that this issue will be used to track eventual re-enabling on client.

**Comment by jatgarg** [comment]
Closing with the PR as e have reenabled it: https://github.com/microsoft/FluidFramework/pull/4605
