### ISSUE TITLE
Design and implement SPO versioning / epoch

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#452]
Files on SPO can be restored by tenant admin and user.
This results in "undo" of ops.
Whenever that happens, we need to communicate that change to all interested clients such that they do not try to catch up / submit any ops.

Scenarios:
1) Active client connected to PUSH
2) Offline client that will try to connect / catch up in the future.
3) Same as above, but client that fetches ops from storage before it succeeded to connect to PUSH (not possible today, but protocol should take that into account).

Likely key pieces of implementation:
1) Storage (PUSH & SPO) track "version" or epoch for a file. It starts with some predictable number (0 or 1) and is incremented every time file is overwritten through external means.
2) Whenever clients retrieve ops from storage, or attempt to connect to PUSH, there has to be a handshake between client and server regarding expected version by client and current version on the server. In case of mismatch, client has to disconnect and issue critical error on container.
3) PUSH has to kick all clients whenever file is overwritten through external means. It may or may not communicate reason - it's not that important
4) Client has to retrieve "starting" version when loading file. This naturally happens due to # 2 when there are no snapshots (staring from socket). For loading from snapshot case, it would be ideal to store that information in snapshot itself, as it also helps for future scenarios where storage does not store ops (and thus the only way for runtime to retrieve ops is by storing them as part of snapshot). But, this design required SPO to go through every snapshot in file and bump version in snapshot, which is likely not ideal. Not sure what's best design in here.
5) We need to come up with proper mechanism to raise "file was overwritten" error to hosing environment / app, such that it can show proper error dialog / reload page (as needed). Currently, this is handled through raising errors through "error" handler on container with statusCode property as a pivot to differentiate various interesting cases. We might use or not use that mechanism.

Across all decisions, we need to understand separation of concerns between driver & runtime.

**Comment by anthony-murphy** [comment]
@vladsud and @jatgarg I think we will want to complete #3478 before this work, as i think we need to have a way so shutdown the session cleanly. I'm not sure what else in on your plate right now Jatin, but if you have bandwidth you could pick up  #3478

**Comment by jatgarg** [comment]
Right now, I am engrossed in driver work of having a sharing link in the POST call for teams scenario which needs to be finished by upcoming week and then this epoch needs to go in before mid October. I will be able to take a decision early next week depending upon the current work that I am doing. Maybe I will accommodate this.

**Comment by vladsud** [comment]
I'm not sure I see the connection. epoch failures are not different from any other critical errors that we already have (and deal) in the system. In all critical error cases we do not want to automatically reload page, we want to let user save any state (through copy/paste) and only then reload (if needed).
Context reload has quick different semantics - we have to ensure that user state is not lost, and I believe we do want automatic reload.  If we can't achieve them, then yes, we may want to give up on seamlessness of scenario and move to similar manual refresh mode. But I'd not tie that decision (and implementation) to epoch, given it just a corner case of more general critical failure path.

**Comment by jatgarg** [comment]
I think I can take up the work. But as @vladsud  pointed out and I was of the same opinion, that epoch mismatch error should be handled by manually reloading or copy/paste scenario just like other critical errors. So I can take this up after implementation of epoch for which I have a PR out.

**Comment by anthony-murphy** [comment]
@jatgarg is there anything left to do here?

**Comment by vladsud** [comment]
The last I remember - PR is still active, I've left some comments that needs to be addressed. Correct me if I'm wrong.

**Comment by anthony-murphy** [comment]
Can we link the PR to the issue then?

**Comment by jatgarg** [comment]
https://github.com/microsoft/FluidFramework/pull/3785

**Comment by jatgarg** [comment]
> The last I remember - PR is still active, I've left some comments that needs to be addressed. Correct me if I'm wrong.

@vladsud Took the PR suggestions. You can take a look at it now.

**Comment by jatgarg** [comment]
Closing with the PR: https://github.com/microsoft/FluidFramework/pull/3785
