### ISSUE TITLE
SharedObject isAttached() is incorrect or misleading

### ISSUE THREAD

**Issue by jenn-le** [microsoft/FluidFramework#4541]
The function returns true even when the runtime's attach state is 'Attaching'. 
I'm not sure if 'Attached' and 'Attaching' are both considered attached but if so, I think a rename would help.

**Comment by SamBroner** [comment]
Good point. I think @jatgarg  would have the right context.

**Comment by jatgarg** [comment]
@Thakugan Is there anything specific you want to do with Attaching state and that is why you need to differentiate between these too?

**Comment by SamBroner** [comment]
Besides the existing behavior, what do we think the correct behavior should be? I would guess that isAttached should only be true when the container isAttached. Although I may be wrong?

The interface definitely indicates that it would return...

```typescript
 /**
  * Returns whether the given shared object is attached to storage.
  * @returns True if the given shared object is attached
  */
isAttached(): boolean;
```

**Comment by vladsud** [comment]
The API is correct assuming that the purpose of its existence is to answer the question "should I submit ops or should I continue to operate in detached state where local changes result in no ops and no local state tracking".
If you look at repo, 99% of usage is though this.isAttached(), i.e. it should be private API, and likely renamed to better reflect the intention of API.
There is some value for it to be public as we saw it many times people make mistake of how to treat Attaching state - it is only for internal tracking (waiting for attach op) and the rest of the code should always operate in exactly same way as with Attached state.

The three exceptions where making it private would break the build:
1. UTs - most of them are already converted to use attachMode.
2. SharedObjectHandle - same, can (and likely should) use attachMode. It's worth evaluating if not overwriting isAttached() is the right solution here.
3. SubDirectory reaching out to parent SharedDirectory object.

No exceptions in Bohemia repo - used only in DDS they implement.

So I think the right thing to do here is simply rename API to better reflect the intention and possibly - make it protected.
But only if we find better name that confuses less people on intention and right place to use.
