### ISSUE TITLE
Update getGCData in SharedObject / DDS to not use full summarize

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#4547]
The getGCData uses the data generated during summary to find list of outbound routes from a DDS. For this, it runs the full snapshot logic. This needs to be changed to make it more efficient and not run full snapshot.

**Comment by scarlettjlee** [comment]
@agarwal-navin, I was looking at how to avoid serialization here, related to async summarization. I tried a couple of approaches (see linked commits). 
1. Effectively force all implementations of SharedObject to override getGCDataCore, with a utility function that will walk any object to find handles. SharedObject.ts and utils.ts are the most interesting things in here: https://github.com/scarlettjlee/FluidFramework/commit/7dd4d9883879e7dbba5f36db8330267dca50b4a6 (This is not complete, there are some more DDSs to be fixed up.)
This is a bigger change, which seems counter to [I think] the original motivation of reusing snapshotCore to reduce the burden on DDS creators.
I tried to make it a little less painful by adding an abstract method `get GCRoot` to return the object to be examined but it's not saving much and leads to some ugliness of having to implement it unnecessarily when getGCDataCore is overridden.
2. Change SummarySerializer to GCSerializer which is used _only_ during GC (summarization uses regular FluidSerializer) and have it only collect handles and not serialize. It's totally lying about being a serializer though, which could theoretically result in unexpected behaviour. https://github.com/scarlettjlee/FluidFramework/commit/975b1c0229bbfd1b5c90f4ce8a751b4abbca8637

Thoughts?

FYI, @DLehenbauer.

**Comment by agarwal-navin** [comment]
I like the approach for #2 more because #1 is too complex and like you said adds burden to DDS creators. I wouldn't want to do this unless necessary.

For #2, if we can somehow limit the scope of where and how the GCSerializer is used, we should be fine for now. For example, serialize could return **_only_** the serialized handles in the data - we can serialize the existing `serializedRoutes` array and return it or we can store the serialized handles (output of `serializeHandle` API), serialize this list and return it. I am guessing that serializing these simple array / object list should not be that expensive?

**Comment by scarlettjlee** [comment]
Okay, we'll go with some variation of option 2. In that case, that doesn't change the work for async summarization. (Option 1 would have removed summarization code path from GC so it wouldn't have needed to be also split into sync and async passes.)

**Comment by agarwal-navin** [comment]
Tracked by AB#406
