### ISSUE TITLE
Design ODSP API for requesting multiple blobs

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4590]
SPO Snapshot API is switching from returning all the trees and all the blobs for a given file to returning only subset of this information. This is done to optimize time to render, including dropping images from initial response. But also not to return such things as search blobs, and blobs and trees marked for collection by GC.

As result, we need an API to request missing data.
We do not have any API to request trees.
And blob requests are limited to be done one by one, with 6 sockets max per domain, it make take a lot of waiting for client to inbound 100-1000 blobs required for rendering trivial table.

Issue https://github.com/microsoft/FluidFramework/issues/4589 tracks the work to optimize snapshot format, which is likely to be generic enough for fetching individual sub-trees and blobs. As result, we are only missing 'query language', i.e. description of how client requests data.

As mentioned above we need to
1. Be able to request number of blobs
2. Request sub-tree. For simplicity, I think we should start with assumption that this request should
   - including all sub-trees for such tree (i.e. deep request, not shallow).
   - include all the blobs that would be usually returned through snapshot route. I.e. if will exclude (for client to use # 1 above if needed) all binary big blobs uploaded as such, as well as search blobs, and possibly some other blobs if response is too big, but otherwise it should include all other blobs that are part of the tree.
3. (future) Request a tree and all the blobs (same semantics as regular snapshots) for a component. I.e. having component ID (guid) which is a path in the tree, request snapshot filtered to this component. This is identical (from API and driver handling) to above (but require big changes in runtime structure to be able to use such API, due to components being stored as flat list, not as hierarchy).

Note that there is good risk that client already has these blobs (due to blob reuse across trees).
If we want to address this case, we can go with one of the following paths:
1. Client also provides a version of snapshot it loaded from, such that storage can calculate what client has. This is not full solution, as client get download blobs by getting them though this API (i.e. downloading multiple trees that share blobs).
2. Client communicates its "knowledge", i.e. all the blob IDs that it knows about (already downloaded) and storage excludes them. Given number of blobs in snapshot can be large, that can create rather big request payload that partially defeats the purpose.
3. Start with returning all the blobs and recording in telemetry on how much duplication we have, and adjust in future steps based on this data. Given that this API is likely to be used only for sub-trees that are marked for deletion, duplication rate should be low.

**Comment by vladsud** [comment]
And for API itself, if possible, it should be a POST call where client payload (request) is a flat list of tree & blob IDs.
This, assuming that storage can differentiate types (blob vs. tree) and client does not need to provide this info.
We should figure out how to make such request future proof. In particular, it would be great to have a place to specify "options" - either for whole request or for individual ID. That might be useful in the future if we want to ask for tree without blobs, or shallow tree (former is similar to blobs=0 on snapshot fetch).
"latest" can be used to specify the ID of latest snapshot, similar how we do it today.

@marcmasmsft, @ram-ramasubramanian - please take a look. Please link to any relevant work items on your side.

**Comment by vladsud** [comment]
Per investigation in issues #4589 (optimization of snapshots), it does not look like we need partial tree snapshots any time soon, and thus there is no need to download sub-trees. In example (Chapter 1 document), the full tree structure takes less than 3% of full payload.
As such, this item will track only request and download of many blobs.
Also snapshot format is suitable as response for blob request. So this item is mostly about format of request, that can be as simple as POST with a list of blob IDs to request. The benefit of this approach is less code on server and client. The con - slightly bigger response, due to usage of dictionary (i.e. indirection to resolve IDs - we would spend 2-3 extra bytes per blob).

**Comment by vladsud** [comment]
This work item will be required to solve https://github.com/microsoft/FluidFramework/issues/6371 - GC has rather big impact on snapshot size

**Comment by vladsud** [comment]
@marcmasmsft, @jatgarg , @sunnyhuang2008 , we need to make some progress here.
Is this something we can make happen using new file format, under "experimental" bucket in September?
https://github.com/microsoft/FluidFramework/issues/6371 has more data on where it would be used right away, and requirements.

**Comment by vladsud** [comment]
@jatgarg, assigning to you in September to see if we can figure out a way to make parallel progress on this item with binary snapshot. It might be ideal to use this item as a staging for bigger snapshot workflow, as we have easier time to flight it by starting to leverage in GC blob download scenario where client has a way out if API is disabled or does not work (download one by one). The other big plush - server could fully control staging here by either including or not including GC blobs into existing summaries, and thus forcing client to download these blobs or not. So it feels like it has much easier way to stage all the work and prove by shipping and have much more confidence RE more critical snapshot download workflow.

**Comment by jatgarg** [comment]
Moving to Oct. I will start working on it by Sept end/Oct start so that we will something in October as the roll out for Binary snapshots will also happen by Oct end.

**Comment by jatgarg** [comment]
Wanted to move it to Jan as based on talks with server folks this is not going to be in server response till Jan due to holiday season.

**Comment by jatgarg** [comment]
Wanted to move it to Jan as based on talks with server folks this is not going to be in server response till Jan due to holiday season.

**Comment by vladsud** [comment]
We can consider adding an API to fetch whole tree of blobs (to storage interface).

Alternative solution - each blob read does not happen right away, but rather cached by driver and processed on 0-ms timer.
Once timer fires, we aggregate all request that happened during this time and issue multi-blob read request.

In either case, ODSP may return only some blobs, as they plan to do 10Mb limit. Navin opened an issue to collect telemetry here, but I think in initial implementation we should not care and fall back to reading blobs one by one (as we do today). We do not expect it to be hit ever. But the moment it's not true, we should reconsider design (implement second design).
