### ISSUE TITLE
Update examples to use containedValueChanged event

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#4595]
With #4556 we now have localized eventing on subdirectories ("containedValueChanged").  We should consider using these events in our examples where we currently do path inspection on the "valueChanged" event.

Based on a quick search, looks like the following might benefit:

- [ ] examples\data-objects\primitives\src\main.tsx
- [ ] examples\data-objects\todo\src\TextList\TextListView.tsx
- [ ] examples\data-objects\vltava\src\fluidObjects\tabs\dataModel.ts

**Comment by atiqueahmedziad** [comment]
Hey, can I work on it?

**Comment by zubinchopra** [comment]
Hey @ChumpChief first time contributor here. Can I take a look at this one? Would love to know if there any helpful tips you can provide to start off with this :)

**Comment by ChumpChief** [comment]
Sure, sounds good :)  Generally speaking these samples are registering for valueChanged on the root directory and then checking that the path matches the subdirectory they're interested in.  Instead they could be registering for the (relatively newer) containedValueChanged event directly on the subdirectory in question and then would not need to examine the path anymore.

Please do let me know if you hit any issues with the new event, I'd value feedback on it! :-D

**Comment by ChumpChief** [comment]
Also apologies to @atiqueahmedziad, I must have missed your message over the holiday :(  If you'd like to split the work or collaborate with @zubinchopra, we're happy to have you both here :)

**Comment by zubinchopra** [comment]
Hey @ChumpChief, I took a look at the code for `main.tsx` and found the following listener:
`this.props.map.on("valueChanged", (changed) => {`

I see that the event being listened for is 'valueChanged`. Is the proposed solution to replace that registry with `containedValueChanged` or remove it altogether?

**Comment by ChumpChief** [comment]
It would be a replacement, but additionally the registry would be made on the `mapDir` subdirectory instead of on the `root` in that case.

**Comment by zubinchopra** [comment]
Hey @ChumpChief, I have submitted a sample PR for the change only in `main.tsx` for now: https://github.com/microsoft/FluidFramework/pull/5186

Will you be able to review it and let me know if the changes look good?
