### ISSUE TITLE
Turn off hot-swap upgrade by default, making it opt-in

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#4600]
Right now the host refreshes the page on "contextDisposed" event by calling `container.close()` in an event handler.

Since this is our primary code path for the foreseeable future, we'd like to move this responsibility into the container itself, giving a way to opt in to hot-swap upgrades, but by default closing the entire container.

The main work here is figuring out where to put this configuration.

**Comment by anthony-murphy** [comment]
We should just make this a config passed in from the loader, and have it off hot swap off by default

**Comment by arinwt** [comment]
How should the host configure the loader for this?

- options (type: `any`)
- scope (type: `IFluidObject`)
- something new in constructor contained only within loader?
- new request header?

**Comment by anthony-murphy** [comment]
options seem right to me. default to off. we can turn on in tests where it makes sense.
