### ISSUE TITLE
Upgrade Fluid to latest version of socket.io-client 

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4608]
Socket.io released V3 recently. As a consumer of Fluid, I am not looking for any new features, but the new version of socket.io does update the versions of debug and ms that it uses to the latest versions, which makes it compatible with what Fluid Framework already requires.

Upgrading socket IO could resolve #4080

We should also update the duplicate package checker exception in the bundle tests package to remove all the socket.io specific overrides:
https://github.com/microsoft/FluidFramework/blob/955a4c77c7c4b29c66572097caf5818983b7ef25/examples/utils/bundle-size-tests/webpack.config.js#L50

**Comment by christiango** [comment]
I tried to make a PR to upgrade, but it seems socket.io is incompatible across client and server with V2/V3 so this required coordination among ODSP and FF.

https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html

Perhaps as a part of this conversation, we can discuss if we still need/want to use socket.io rather than a thin layer above native web sockets. It's a heavy library (includes a polyfill for websockets we don't need).

In fact, they even have a whole section calling out what socket.io adds in 2020: 
https://socket.io/blog/socket-io-3-release/

I wonder how much of that list we actually use.

**Comment by curtisman** [comment]
@GaryWilber on thought of getting rid of socket.io

**Comment by GaryWilber** [comment]
I'm up for replacing socket.io with something else as long as we find a good alternative. Are there any suggestions? I also imagine we would want alfred to use the same replacement. +@tanviraumi as fyi

In the meantime, there is a way to have the server run socket.io 2 and socket.io 3 in parallel. So we could support a client upgrade to socket.io 3 if that's desirable.

**Comment by christiango** [comment]
From the client perspective, I think we'd want to use native websockets directly to reduce bundle size impact, since socket IO brings in a bunch of other code around falling back to long polling. What else do we need from socket.io from the client perspective? I think there is some notion of rooms, is that available standalone? Can we implement a lightweight version of it ourselves?

@vladsud also had found that our current socket setup is CPU intensive, which is why we defer it to after the initial render. Not sure how much socket.io is to blame here, but it may provide us with an opportunity to improve

**Comment by GaryWilber** [comment]
WebSockets by themselves are pretty barebones. Here are a few things socket.io does for us that we would need to support in a replacement:

1. Rooms - Rooms is a serverside concept that's used when we want to emit messages to a select group of connections. In our case, we setup a room for each document. That way we can easily broadcast ops to all clients for a document.
2. PubSub backplane support - In Alfred / Push v2, clients can connect to any document from any frontend machine. Socket.io has support for inserting an "adapter" which allows us to insert Redis into the mix. So when we emit ops to rooms, those ops are broadcasted & received by all relevant frontend machines via Redis.
3. Connection keep-alive / ping pong - WebSockets don't have a built in mechanism for detecting broken connections. Socket.io solves this by implementing a ping-pong event. Every minute or so the server/client will send a ping-pong event back and forth. The server disconnects the websocket if it hasn't received a reply for some time.

1 & 2 are serverside pieces. 3 is something thing we would need to support in the client and server. We would also need to decide on the message protocol between the client & server (message serialization, chunking, etc). I'm not quite sure how much work this would all be, it should be possible though.

**Comment by tanviraumi** [comment]
I am okay with changing socket.io to something lighter as well. Between Push and alfred, I believe the basic usages of socket.io are very similar. So we can possibly abstract out the core usage and both can benefit by the same code.

This is the lightweight library that I know of (https://github.com/websockets/ws). But lightweight may come with additional code. For example, this library does not support keepalive so we would have to implement it ourselves.

**Comment by vladsud** [comment]
I support as well exploring here and improving (as socket.io has a lot of perf problems), but this will take months to make it happen. So we likely want to track it orthogonally from pure upgrade to socket.io V3

**Comment by curtisman** [comment]
The question is whether we want to upgrade to socket.io V3 at all though?  Is there any reason we can't stick with V2 and work on replacing it completely?

**Comment by jogonzal** [comment]
@curtisman  @vladsud There is a known security vulnerability with versions of socket.io-client < 3.4.1 that is affecting us because of this dependency

https://github.com/socketio/socket.io-parser/commit/dcb942d24db97162ad16a67c2a0cf30875342d55

**Comment by curtisman** [comment]
@jogonzal The fix for socket.io-parser was backported to 3.3.2: https://github.com/socketio/socket.io-parser/releases/tag/3.3.2. 
The dependency for socket.io-client -> socket.io-parser is ~3.3.0.  So you should be able to update your lock file to get the security fix.

**Comment by jogonzal** [comment]
Perfect, that is helpful!
________________________________

**Comment by tanviraumi** [comment]
@curtisman @vladsud and @GaryWilber : We should also come up with a plan on when to migrate to the simpler library. It will be a very big work item, so we need to get on board with that

**Comment by vladsud** [comment]
I totally agree with you, but realistically this is not that high in priority (at least for me). Yes, bundle size is huge, but currently we have a lot of other perf items that are much more important. I guess if we have resources to attack it, sure, but my feeling is that runtime team & Gary will be busy with shipping quality for quite a while (before and after GA of Fluid Experiences)

**Comment by tanviraumi** [comment]
Makes sense. I will leave it with you guys to track it, whenever you feel appropriate. My guess (not backed by data) is, it will also reduce server cogs since we will able to serve more connections from a single box.

**Comment by curtisman** [comment]
Just want to point out that different driver/service can have use different versions, right? It may be possible to do r11s driver first?

**Comment by tanviraumi** [comment]
Correct! We are currently collecting data on scale characteristics on FRS. Depending on the outcome, we might want to tackle it sooner. FYI @sharmakhushboo

**Comment by christiango** [comment]
This issue is still relevant and should not be auto closed

**Comment by tanviraumi** [comment]
r11s is already on socket.io v4 and I believe Push has migrated as well (@znewton and @GaryWilber to confirm).

So we should be in a spot to upgrade the client now.

@jatgarg to check the driver/common code.

**Comment by GaryWilber** [comment]
Yes Push is running socket.io v4

**Comment by znewton** [comment]
Just confirmed that FRS is running Socket.io v4. The title of this issue is upgrade client to v3. We want to upgrade to v4, correct?

**Comment by tanviraumi** [comment]
@christiango can confirm but I believe anything >= 3.x should be enough to close this issue.

If @jatgarg and you can confirm that drivers/clients are also up to date, we should be good for now.

**Comment by christiango** [comment]
I think V4 would probably also work, right now the issue is that FF requires 2 versions of debug to be included in bundles (one for socket.io and one for internal usage)

**Comment by jatgarg** [comment]
We are using this package version at client side:     "socket.io-client": "^2.4.0",

**Comment by tanviraumi** [comment]
I think we should update the client version as well. I see 2.4.0 is being used in both drivers. We can pick the r11s driver one and test it out. For ODSP, assign someone appropriate.
