### ISSUE TITLE
Fluid Container Load Flow

### ISSUE THREAD

**Issue by SamBroner** [microsoft/FluidFramework#4610]
Goal: =<2 libraries to install, <5 LOC to connect to a service

What should the library look like? 
E.g. what methods should be available on the Fluid module?
```typescript
import Fluid from "@fluidframework/aqueduct"
```

How should we connect to a Fluid service?
```getTinyliciousContainer()``` is not sufficient unless we want to import a driver from each service. 
E.g.
```ts
import getTinyliciousContainer from "@tinylicious/loader";
import getRouterliciousContainer from "@routerlicious/loader";

const tinyContainer = await getTinyliciousContainer(...);
const r11sContainer = await getRouterliciousContainer(...);
```

**Comment by SamBroner** [comment]
Alternative:

```typescript
import tinylicious from "@tinylicious/loader";
import r11s from "@routerlicious/loader";
import frs from "@FRS/loader";

const tinyContainer = await tinylicious.init(...);
const r11sContainer = await r11s.init(...);
const FRSContainer = await FRS.init(...);

if (newContainer) {
    container.resolve('/', {...initSchema})
} else {
    container.request('/')
}

```

**Comment by micahgodbolt** [comment]
would it make sense to pass the 'newContainer' into the container itself, so there's just a single call?
```js
container.resolve('/', newContainer, {...initSchema})
```

**Comment by micahgodbolt** [comment]
oh i see the resolve vs request......would need to consolidate those into a single function that could do either based on the 'newContainer'

**Comment by SamBroner** [comment]
@ChumpChief, do you see this is being part of the work you're currently doing?

**Comment by ChumpChief** [comment]
Potentially could be, I had not been looking at this part in particular yet.

**Comment by LarsKemmann** [comment]
I'm not sure if this is the best place for this feedback, but I figured I'd start here. It's still a mystery to me why Fluid would require API consumers (especially at the Aqueduct level) to have to plumb together different data object/DDS _types_ in factory methods. If I _use_ a data object type, that should be enough to get it wired up into whatever ambient dependency injection/factory context is provided by default. Similarly, if I _define_ a new data object type that uses various nested data object types, that should be as simple as defining a class that inherits from a shared base class and then using the nested data object types. Expecting the user to know to create a `ContainerRuntimeFactoryWithDataStore` and add various provider entries etc. is putting a lot of mental-model load on the user. I've been experimenting with Fluid for a couple months now and still don't know how to create a simple React app with a custom data object type that uses two or three different nested data object types. 😆
