### ISSUE TITLE
Fetch tool never finishes on complex file

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4635]
Fluid fetch tool hangs on [Chapter 1](https://dev.fluidpreview.office.net/p/c3BvOmh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQtZGYuY29tL3RlYW1zL09mZmljZU9ubGluZVByYWd1ZQ%3D%3D/b!BOyJN6Bkykm_L66EicZFaDKnQ_cydFFLqph8D-t_9vqaMsGC4Tm9RYec9Rh5aw3l/01N5X4JN6BX23SZCTFTFB2D5PEQUKWMZ3E/Chapter-1-Collaborative-Components) document: when downloading ops, and eventually exits (I assume crashes with no message).

Two items based on that:
1. We should investigate and fix underlying problem
2. We should add ability to download snapshots only and skip ops. Ops is where it hangs, but user may not need ops (and does not need to wait for very long time to look into snapshot only).

**Comment by jatgarg** [comment]
Closed with above PR.
