### ISSUE TITLE
ODSP driver: fluid:telemetry:OdspDriver:TreesLatest_end telemety is not very useful

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4636]
Some things that are wrong or missing:
1. **Trees** property is always 2 - that represents number of commits. We are lacking any data on number of actual tree nodes.
2. **Blobs** property tells us about unique blobs. It would be great to get data on number of leaf blob nodes in all trees, i.e. get a sense on blob reusability in given snapshot
3. We have **bodysize** as a metric for overall payload size.  It would be great to add metrics on combined size of all blobs.
4. **seaquenceNumber** is not part of payload, It's calculated a bit down in this function after we already issued this event
5. It would be great to get from SPO and record in our telemetry total snapshot size. I.e. include blob sizes that were excluded from this snapshot because they are too big or are images.

**Comment by anthony-murphy** [comment]
Related to the above, it would be useful to know the number of blobs referenced in the trees that are not included in the blobs

**Comment by vladsud** [comment]
That's Data_blobs  - # 2

**Comment by jatgarg** [comment]
For 5th point an issue has been opened at server side: https://onedrive.visualstudio.com/SPIN/_boards/board/t/Team%20Prague/Backlog%20items/?workitem=982134

**Comment by jatgarg** [comment]
Sub issue has been opened for last point: https://github.com/microsoft/FluidFramework/issues/5016
