### ISSUE TITLE
Fault Injection Document Service Factory Wrapper

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4656]
We should build a wrapper document service factory that injects retriable failures on service calls that we can run all tests based on our testing abstraction #4655 in a mode where faults are randomly injected

**Comment by markfields** [comment]
Considering this closed for now, it's only implemented in the Stress Test, and that is good for now. If we come back to wanting to push on e2e tests with this kind of approach we can revisit.
