### ISSUE TITLE
SharedString: make markers inserted in the sequence dds have a sequential id

### ISSUE THREAD

**Issue by montselozanod** [microsoft/FluidFramework#4659]
## Feature
Right now when we create a sharedstring and insert markers to it, the id of said marker is not required and is assigned by developers if need be. When developers (if needed) assign an id to said marker, this id is arbitrary and has no notion of the order of the marker compared to other markers in the DDS. 

This issue, therefore looks to unblock the scenario where given a marker id, we can understand if said marker is within a range of 2 markers by using as ids infinite precision numbers.

**Describe the solution you'd like**
Ideally we want to create a mixin, when creating the sharedstring, where upon a marker insertion op is acked by the server, we assign an id to the marker in between the markers it was inserted on. Solution should not generate ops on id assignment to avoid creating spammy ops.

**Describe alternatives you've considered**
- We had discussed having the client leader assign ids for all their local ops + non-local ops of other clients to make sure we avoid collisions because of markers being inserted at the same time. This approach was dropped because, leader assignment is unrelated to processing ops, so if we relied on the leader to assign ids, we could potentially miss assigning the id to several paragraphs when leader went offline. 
- In the draft pr out, I had explored assigning said ids inside processTreeMsg. Nevertheless, this solution will not work given that at that time the position of the segment is not right and hasn't  reached consistency. 

#4641 considers a draft pr for issue

**Comment by montselozanod** [comment]
@anthony-murphy and @vladsud as fyi for the issue here.

I'm in the midst of prototyping assigning the id in sequenceDelta and passing in the mixing as part of the SharedStringFactory. From offline conversation though it sounds like there are changes required to make sequenceDelta understand if an op has been acked or not

**Comment by anthony-murphy** [comment]
@montselozanod  how's the prototyping of the mixin going? 

This is basically the change i think should be made to support ack events: https://github.com/microsoft/FluidFramework/compare/main...anthony-murphy:merge-tree-ack-event

**Comment by montselozanod** [comment]
I forgot to update this issue. I updated the draft pr to use the change for supporting ack events you suggested above. In this change, we listen for ack events. When an ack op comes, we add the marker to a sortedSegmentSet, and check its previous and next marker to assign the id

**Comment by anthony-murphy** [comment]
leaving this open for now, as it would still be great to get the sequential id generation code checkedin

**Comment by vladsud** [comment]
@montselozanod, @anthony-murphy, should this item be closed? If not, can you please clarify what work it tracks?

**Comment by anthony-murphy** [comment]
I'd love a framework package for generating sequential ids, as it seems generally useful.
