### ISSUE TITLE
Automate Service Load Tests

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4662]
packages\test\service-load-test\src\nodeStressTest.ts

**Comment by markfields** [comment]
I think I clicked something by accident just now... Moving back to To do column...

**Comment by markfields** [comment]
Some tasks:
- [ ] Add SPO Test tenant creds to key vault and add them to the variable group
- [ ] Add pipeline
- [ ] Probably future PR/issue: Use the driver code from test-drivers package and support different servers.
