### ISSUE TITLE
Data Corruption Error Categorization

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4663]
There are a number of cases where the an error represents data corruption, we should ensure all these cases throw errors that indicate they are data corruption.

**Comment by anthony-murphy** [comment]
I don't think what we currenly have is consistent:
https://github.com/microsoft/FluidFramework/blob/b91400ffff95b29bf42a6904c3ea0370638ac9ac/packages/loader/container-utils/src/error.ts#L38

https://github.com/microsoft/FluidFramework/blob/2653ae49204d8fa82eeb91b131489fa53f2fdc89/packages/loader/container-definitions/src/error.ts#L23

**Comment by markfields** [comment]
Here's one to mark as corrupting:  https://github.com/microsoft/FluidFramework/blob/e30d869bc93b059f0ca33bdf9a1e64b5d131e3ba/server/routerlicious/packages/protocol-base/src/quorum.ts#L160

**Comment by anthony-murphy** [comment]
we should probably do a review of asserts, especially around the delta manger, and start tagging those and data corruption

**Comment by anthony-murphy** [comment]
https://github.com/microsoft/FluidFramework/blob/d50f6b0d5160c848a584b55045a38f0529c2a23f/packages/loader/container-loader/src/deltaManager.ts#L1368

https://github.com/microsoft/FluidFramework/blob/d50f6b0d5160c848a584b55045a38f0529c2a23f/packages/loader/container-loader/src/deltaManager.ts#L1371

**Comment by anthony-murphy** [comment]
https://github.com/microsoft/FluidFramework/blob/b3c7ab594e7dfbe35b7b9de5530056cb3ad8eefd/packages/loader/container-loader/src/container.ts#L1621

**Comment by ksbrar** [comment]
(Added while investigating https://portal.microsofticm.com/imp/v3/incidents/details/226937962/home):
https://github.com/microsoft/FluidFramework/blob/main/packages/dds/merge-tree/src/mergeTree.ts#L2229-L2233

**Comment by markfields** [comment]
I may jump on this this week to accelerate while @ksbrar is OCE.

**Comment by markfields** [comment]
@anthony-murphy and I discussed renaming this error type to `dataIntegrityError` in part to reflect that these errors may be transient as opposed to permanent corruption. They'll still be the highest priority to burn down as a team.
