### ISSUE TITLE
Implement ack notification

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4666]
At-mention Notification feature requires learning about when operations gets acknowledged by server.
This shows up in two different ways:
1. Actual notification is sent only when content (at-mention text) landed in the file. I.e. we ensure that user does not get notification, but there is actually no notification in the file itself.
2. Issue #4659 requires generating sequential IDs based only on acked content, such that all clients arrive to exactly same state.

Shared directory and Sequence are two data structures where we need to expose ack events. Currently, change events reflect either local (non-acked) changes, or remote changes, but events are not fired for ack of local changes.

That said, we should do proper changes across the board, including map.

**Comment by vladsud** [comment]
@curtisman - can we get someone implementing it this month? It blocks notification FC

**Comment by curtisman** [comment]
Do we have a proposal how it can be exposed?  
Does the ack needs to be associated with the action (e.g. returning a promise on action) or having an "event"?
If it is an event how it is different from the normal "valueChanged" event, or "op" event?

**Comment by vladsud** [comment]
The best course of action would be for @anthony-murphy working with @montselozanod to design it based on requirements of sequential ID feature.
But to answer your question, yes, ack needs to be associated with action, in a sense of identifying data content of DDS (in case of merge tree - segments). Feature in question here needs to assign unique IDs to all acked (remote and local) segments with certain properties.
Whiteout too much thinking about it, I'd say that evening system we have should expose ability for subscriber to subscribe to
1. Changes (current model, includes local lies)
2. Acks (changes known to all clients)

I.e. these are two independent events (I do not see a need for 3rd one - receiving both in the form of one event).

**Comment by vladsud** [comment]
I'll add that we either find time to do it right, or we go with current prototype Montse shared that relies on listening and parsing merge tree ops. It's not ideal, but time is too tight - we just can't sit on it - there is work that is blocked by it (i.e. ack notifications -> sequential IDs -> add sequential IDs to URIs and notifications -> consume all this info in ODSP notification service) 0 all of that ideally be done by end of Feb.

**Comment by anthony-murphy** [comment]
From the merge tree perspective this is straight forward, and the code is factored in a way that adding this event is easy. 

I would just reuse merge tree's existing mergeTreeMaintenanceCallback, and add a new type for acknowledged, and call the callback from ackPendingSegment. This is basically the change:

```

            const deltaSegments: IMergeTreeSegmentDelta[] = [];
            pendingSegmentGroup.segments.map((pendingSegment) => {
                overwrite = !pendingSegment.ack(pendingSegmentGroup, opArgs, this) || overwrite;
                if (MergeTree.options.zamboniSegments) {
                    this.addToLRUSet(pendingSegment, seq);
                }
                if (!nodesToUpdate.includes(pendingSegment.parent)) {
                    nodesToUpdate.push(pendingSegment.parent);
                }
                deltaSegments.push({
                    segment:pendingSegment,
                });
            });
            if(this.mergeTreeMaintenanceCallback) {
                this.mergeTreeMaintenanceCallback(
                    {
                        deltaSegments,
                        operation: MergeTreeMaintenanceType.ACKNOWLEDGED,
                    },
                );
            }
```

Just nee to make sure exisitng usage of the maintaince event can handle the new value, and add some tests

**Comment by vladsud** [comment]
I'd vote we scope it to Merge tree for now, we need to unblock existing scenarios, Symmetry in other DDSs could sit in backlog

**Comment by anthony-murphy** [comment]
closing for now. we will handle this in the context of #4659
