### ISSUE TITLE
Too many empty blobs (catchupOps, interval map collection) in complex documents with a lot / large tables

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4667]
Looking at [Chapter 1](https://dev.fluidpreview.office.net/p/c3BvOmh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQtZGYuY29tL3RlYW1zL09mZmljZU9ubGluZVByYWd1ZQ%3D%3D/b!BOyJN6Bkykm_L66EicZFaDKnQ_cydFFLqph8D-t_9vqaMsGC4Tm9RYec9Rh5aw3l/01N5X4JN6BX23SZCTFTFB2D5PEQUKWMZ3E/Chapter-1-Collaborative-Components) document has 565 "catchupOps" blobs. Spot-checking 3 - they are empty ([]).
Why are we writing them out?
Can we not do that? Unfortunately tree representation is not the most compact in current snapshot, and SPO in general is sensitive to number of nodes, so that feels like trivial optimization to have?

This is related to overall investigation into ODSP snapshot efficiency: https://github.com/microsoft/FluidFramework/issues/4589

**Comment by arinwt** [comment]
I started looking at this and found a comment which says the catchupOps are for back-compat, pointing to this issue: #84.

This is purely scoped to sequence and merge tree, so I'll let @anthony-murphy provide his input.

It seems like it should be possible to start handling the case where the catchupOps blob doesn't exist (i.e. be able to read the new format), and then in +2 versions implement a change to be able to write in the new format. The "new format" here being that catchupOps blob may not exist.

**Comment by vladsud** [comment]
Ah, when I opened this bug, I was thinking about _outstandingOps blob for some reason :)
catchupOps indeed is one key blobs for Sequence.
That said Documents like Chapter 1 have a lot of Scriptor components, and thus a lot of Sequences. It would be great both for catchupOps, but also for interval map collection not to write empty blobs (and handle that properly on read).
Should be rather simple change, as long as it's staged (first - read part, then in 2 releases - write part).

@anthony-murphy - any chance you can take a look here?

**Comment by anthony-murphy** [comment]
Yeah. i think we already have the first half of catchupOps staged with the previous rename so not writing should be straightforward. Interval collections i'll need to look at, they are not well supported, but also not used.

**Comment by vladsud** [comment]
It would be great to fork an item for interval map collection before resolving it with above mentioned PR.
Change for interval map collection looks trivial as well, but will require staging (i.e. 2 changes split in time).

**Comment by vladsud** [comment]
Opened a bit more broader https://github.com/microsoft/FluidFramework/issues/4792 to track interval colleciton proposal and possible flattening of Sequence tree
