### ISSUE TITLE
replay-tool does not work with Bohemia's detached create

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#4703]
1. Enable fluid-debugger in Bohemia's dev preview
2. Through the debugger, download any recently-created document's ops/messages.json
3. Run the downloaded messages.json into the replay-tool to generate a snapshot file e.g. from `packages/tools/replay-tool`: `node dist/replayTool.js --indir ~/Downloads/test --outdir ~/Downloads/testOut --write --to 5000`

Expected: replay-tool succeeds
Actual::
```
  fluid:telemetry:Container ContainerClose {"loaderId":"ad8a9645-4452-4f3f-9320-8bc51259731a","clientType":"interactive","loaderVersion":"0.32.0","containerId":"77a629fa-2eb8-45fa-a506-bfebf9ecb5b2","sequenceNumber":3,"category":"error","error":"Null runtime should not receive messages","message":"Null runtime should not receive messages","errorType":"genericError","docId":"FileStorageDocId","containerAttachState":"Attached","containerLoaded":true} tick=626 Error: Null runtime should not receive messages
  fluid:telemetry:Container     at NullRuntime.process (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/nullRuntime.js:54:15)
  fluid:telemetry:Container     at ContainerContext.process (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/containerContext.js:148:22)
  fluid:telemetry:Container     at Container.processRemoteMessage (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/container.js:1202:26)
  fluid:telemetry:Container     at Object.process (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/container.js:1039:40)
  fluid:telemetry:Container     at DeltaManager.processInboundMessage (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/deltaManager.js:1052:37)
  fluid:telemetry:Container     at DeltaQueue.worker (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/deltaManager.js:148:18)
  fluid:telemetry:Container     at DeltaQueue.processDeltas (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/deltaQueue.js:128:22)
  fluid:telemetry:Container     at /Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/deltaQueue.js:107:22 +0ms
UnhandledRejectionPromise
Error: Null runtime should not receive messages
    at NullRuntime.process (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/nullRuntime.js:54:15)
    at ContainerContext.process (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/containerContext.js:148:22)
    at Container.processRemoteMessage (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/container.js:1202:26)
    at Object.process (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/container.js:1039:40)
    at DeltaManager.processInboundMessage (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/deltaManager.js:1052:37)
    at DeltaQueue.worker (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/deltaManager.js:148:18)
    at DeltaQueue.processDeltas (/Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/deltaQueue.js:128:22)
    at /Volumes/Macintosh HD - Data/b/GitHub/FluidFramework-1/packages/loader/container-loader/dist/deltaQueue.js:107:22
Deadlock in ReplayTool!
```

**Comment by heliocliu** [comment]
Attaching a small example messages.json that produces this error 
[messages.json.zip](https://github.com/microsoft/FluidFramework/files/5763238/messages.json.zip)

**Comment by heliocliu** [comment]
Spoke with Jatin, replay-tool cannot work with just a messages.json file for detached create new because there's no proposal op, so in order to build a new snapshot we need an existing snapshot plus ops to process on top of it.  Replay-tool is supposed to be able to handle that (to be verified)

**Comment by markfields** [comment]
I believe @Vladsud and I discussed this a while back - I thought we opened an issue but I can't find it.

I think what we were saying is that now that SharePoint holds onto the initial summary, the fetch tool should mark that one up in its name (unless the numerical IDs are already sufficient, I can't remember exactly how it looks), and then the replay tool should load that summary first before replaying ops.  I believe this functionality needs to be added to replay tool.

In the meantime you can manually load from the summary, I think.  Can't remember exactly how the tool works off the top of my head but I'm pretty sure I remember successfully doing so with Vlad.  He's messing with the Replay Tool now anyway so probably has all this fresh in his mind :)

**Comment by vladsud** [comment]
Replay tool is broken big time. Here are some problems:
1. Need to load always from 9th snapshot (as written by fetch-tool). Easy to work-around by using --from arg, but we need to make our tools smarter to just do it automatically
2. There is some structural changes in how components encode package paths. I've added handling for that today locally, will raise PR shortly.
3. Biggest one - we do not have factory for https://graph.microsoft.com/types/SharedArray DDS in our repo. We need some fix for "unknown" DDSs. We can't summarize them properly, but it would be great to do something not to fail. I.e. it's Ok to lose coverage for unknown DDSs, but we need to ensure that the rest of the tool works.

I'll take care of # 2. Need help with the rest.

**Comment by vladsud** [comment]
One more blocking issue: https://github.com/microsoft/FluidFramework/issues/4894

**Comment by vladsud** [comment]
Solved with https://github.com/microsoft/FluidFramework/pull/4901
