### ISSUE TITLE
Refactor fluid-fetch/replay-tool/debugger to support bringing additional functionality to debuger

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#4704]
#4141 tracks integrating the entire document bug repro workflow into the debugger tool (downloading, anonymizing, and previewing a buggy/problematic "third-party" i.e. Bohemia document to share with us).  Currently this functionality is split among fluid-fetch, replay-tool, and debugger.  Typically debugger could take a dependency on fluid-fetch/replay-tool and leverage their functionality that way, but fluid-fetch and replay-tool are currently published as `@fluid-internal` (because they are internal tools) whereas debugger is published under `@fluidframework` despite essentially being an internal tool because Bohemia uses it (`@fluid-internal` packages are not published to npmjs).

The functionality that debugger needs must find a home inside a `@fluidframework` package, or these `@fluid-internal` packages need to be published in a location that Bohemia can still consume (e.g. offnet) and Bohemia's package feeds need to be set up to find them.

**Comment by heliocliu** [comment]
The sanitizer/anonymizer functionality currently in the debugger tool should probably also be moved as part of refactoring here, though there aren't any direct consumers right now

**Comment by curtisman** [comment]
The tool-utils library package will be a good place to shared these functionalities

**Comment by curtisman** [comment]
Also #630 is a related issue

**Comment by heliocliu** [comment]
Noting to also revert the part of #4705 that removes the MergeTreeDeltaType enum usage
