### ISSUE TITLE
Investigate - Move summary definitions from protocol-definitions in server to client

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#4728]
Summary protocols such as ISummaryTree, ISummaryHandle, etc. should be part of the client repo. There are a few dependencies that the server repo has on these. These should be investigated to check if they can either be removed or the protocol can be split.

**Comment by curtisman** [comment]
Is this a dup of #4002 and #4003?

**Comment by agarwal-navin** [comment]
Looks to be a dupe of #4002.

**Comment by agarwal-navin** [comment]
This may actually be a superset of #4002. We should ideally move all of summary protocol definitions to client.

**Comment by curtisman** [comment]
@wes-carlson and I have talked about this before.  I don't know if there is another issue that cover all the type in `SummaryTree`,

**Comment by curtisman** [comment]
Related to #4683

**Comment by agarwal-navin** [comment]
Closing as these interfaces have moved to common libs.
