### ISSUE TITLE
Hello World - Get & Set Data

### ISSUE THREAD

**Issue by SamBroner** [microsoft/FluidFramework#4737]
We need a basic Getting Started guide in the Hello World repository so that we can get feedback on the API surface.

The Getting Started Guide should mimic the Getting Started Guide on https://fluidframework.com/docs/get-started/tutorial/

We should also introduce the Data Object and flag the behavior of getXContainer.
----
Work on improving the Fluid Hello World experience based on a Data-Oriented value proposition has begun. The work is being done here: https://github.com/microsoft/FluidHelloWorld/tree/new-hello-world

**Comment by micahgodbolt** [comment]
@sambroner can I get a bit more clarity around done criteria on this one?
