### ISSUE TITLE
Table DataObject

### ISSUE THREAD

**Issue by SamBroner** [microsoft/FluidFramework#4741]
We already have the table data object, should we formalize it as an offering for 2d array style data?

**Comment by SamBroner** [comment]
@micahgodbolt, do you want to self assign this? I believe you're doing the work.

**Comment by micahgodbolt** [comment]
Majority of table based UIs expect something like the following for data

```js
const header = [{ key: 'name', value: "User's Name" }, {key: 'age', value: "User's Age"}];

const items = [
  { 'name': 'Mickey', 'age': 30}
  { 'name': 'Minney', 'age': 28}
] 
```

1. An array of headers, either strings or objects with a key and value (and possibly other data regarding sorting, state, visibility)
2. An array of items, usually an object with `key: value` pairs where key matches a key in the header data and value is either a string or some function the returns the cell data

### In scope
1. Leverage a SharedMatrix to store the data, and then have a simple getter for header and items in the format above. Getter can take in params like range and columns. 
2. Setters will be a callback that specifies the row/cell edited (onBlur), and we'll update the SharedMatrix and fire an event that the table has changed


### Out of scope (for now)
1. Doing per cell shared strings/coauthoring
2. Having more refined eventing
