### ISSUE TITLE
Formalize Package Definition

### ISSUE THREAD

**Issue by SamBroner** [microsoft/FluidFramework#4743]
The IPackage, IFluidPackage, and IFluidModule concepts are only barely clear in code. We need to have a clearer definition of a valid package, possibly with a validator that verifies that the resource exists and is valid?

**Comment by ChumpChief** [comment]
Pay-for-play approach probably focuses on pulling these definitions out of the runtime.  At which point these interfaces become optional (still fine to define better but perhaps less important).
