### ISSUE TITLE
Blob API telemetry needs improvements

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4773]
In order to be able to investigate various issues in production, we need better telemetry.
The following things are missing and would be great to add:
1. ODSP's createBlob() does not log blobID.
2. ODSP's readBlobCore() should record blobID for "readDataBlob" event.

**Comment by vladsud** [comment]
@wes-carlson, I've assigned it to Jan, as it's rather small change and it would be great to take care of it soon, to ensure we could debug issues related to image failrues.

**Comment by wes-carlson** [comment]
Should have been closed by #4786
