### ISSUE TITLE
ODSP: Errors on file creation do not propagate correlation ID / cancel event is not an error

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4781]
Based on [this investigation](https://teams.microsoft.com/l/message/19:53328301da384b33bcc81111124e3ab4@thread.skype/1610391437693?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1610391437693&teamName=FFX%20(Fluid%20Framework%20and%20Experiences)&channelName=Bugs%20%F0%9F%90%9B&createdTime=1610391437693)

fluid:telemetry:OdspDriver:createNewFile_cancel contains sharepoint correlation ID.
But when this error is propagated to fluid:telemetry:Container:ContainerClose, correlation ID is not there.
It would be great for errors to keep all of their properties, including correlation IDs.

I have not looked at details, i.e. what's the issue here.

Also cancel event should be an error event - we already do so in other places (I believe in summarization and loading from snapshot). Not sure if it's one-by-one fixing (like in this place), or logger should just make all cancel event (by default) errors.

**Comment by jatgarg** [comment]
@vladsud I couldn't see in code where we are recording the sprequestguid. Also in telemetry I only see few places where we are getting this telemetry,
