### ISSUE TITLE
Consider flattening Sequence storage and making Interval Collection blob optional if empty

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4792]
ODSP storage is sensitive to number of nodes. 
So, while this might not be good practice in general (of design runtime based on one storage data point), I wonder if we want to consider flattening sequence storage. I.e. instead of having 

	header
	content/header
	content/body
	content/catchUpOps

We have

	(optional, only if not empty) intervalCollection
	header
	body
	(optional, PR is out) catchUpOps

This obvious adds a requirement for Sequence to know about all the names that merge tree can write out, which is not ideal. And it has non-trivial back compat impact, so chances of us doing anything here is low.

**Comment by anthony-murphy** [comment]
Flattening seems good. I'd love to use some kind of mixin/plugin model for shared interval to make it truly pay to play, and decouple it from shared string even more. This would also open the door for other indexing type that preserve data on top of the shared string

**Comment by vladsud** [comment]
@anthony-murphy - are you planning to take a look soonish? If not, I'd rather close it :)
The priority of that item dropped a bit with latest improvements in ODSP storage (it's less sensible now to edge count) and upcoming blob aggregation. Might be still good change if it's not that hard, but if it's a ton of work, it's probably worth punting.

**Comment by anthony-murphy** [comment]
I think we should just close this, as this would be a format breaking change for shared string, which would also affect things like search, so does not seem worth it.
