### ISSUE TITLE
Clear cached snapshot when too many ops are applied

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4794]
Currently, the ODSP snapshot cache is only updated on initial load. For long running sessions, it is possible that many ops will be applied on that snapshot. This is problematic since a user may reload the page and experience perceived data loss on the initial render. Similarly, the perceived performance in the scenario where we load a snapshot that is many ops behind may be bad since the time to apply all the ops may be worse than the token + network overhead of fetching the latest snapshot.

The proposal here is to have a heuristic in place that clears our the snapshot cache for a document once a specified number of ops (value to use TBD) have been applied on top of that snapshot.

**Comment by vladsud** [comment]
I think policy implementation should not be driver, as different scenarios / hosts may have different view on right policy.
It's better if this is done outside. I can think of two options:
1. This is part of OWH as it deals with same type of content (Office containers) and thus has better view into what's best.
2. This can be done as cache adapter, i.e. an object that wraps cache interface, thus making it possible to share code, but making it optional / overwritable (as host may or may not chose to use this adapter with some default policy).

Either way, I'm not convinced this belongs to Fluid repo

**Comment by christiango** [comment]
I'm not sure this is something that is unique to our scenarios, which is why I suggested it be something in the FF layer. I definitely could see the challenge in setting a driver policy, as this might vary by container type and we'd need to set the policy on load before we have the container type.

However, I'm also not fully convinced this (or at least a very basic version of this) does not belong in the driver. I don't think the problem is specific to Office, so I'd like to avoid an Office specific solution or force duplication across consumers of fluid.

**Comment by vladsud** [comment]
We can build a generic cache adapter that would take (as an input) number of ops, we would clear cache after that many ops were observed for a file on top of snapshot. This is simple, but OWH (on behalf of office container) would need to figure out the right number here.

**Comment by christiango** [comment]
I logged a work item on our side to do it entirely on our side, assuming we have the right APIs already (I think we do). But in the meantime, let's keep this issue open and we can migrate the office solution to the repo if there is a good need for it.

**Comment by vladsud** [comment]
This is actually implemented in the driver :)
CacheOpsLimitHit telemetry event fires in the driver when it happens.
This is controlled by HostStoragePolicy.opsCaching.totalOpsToCache policy, which by default is at 5K ops.
