### ISSUE TITLE
Opstream request in ODSP driver subject to options calls

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#4796]
There are some scenarios in the odsp driver where an opstream request is made to fetch the latest ops. SPO APIs have a URL length limit that sometimes forces us to put the access token as a header rather than include it in the URL as a parameter. This forces the request to no longer be a "simple" request, which means an OPTIONS call may be required. This OPTIONS call adds an additional network roundtrip and makes overall performance worse.

We recently addressed a similar problem in trees/latest by moving that API to use "POST" instead of "GET". This enabled us to avoid OPTIONS calls all together. We should aspire to make this change on other critical ODSP APIs like opstream.

**Comment by christiango** [comment]
> Can you please add a note on if this is theoretical issue, or it does happen every time (based on your observations)? I.e. better understand the priority of this work

It's not a theoretical issue. It happens for me every once in a while. The browser caches OPTIONS, so it won't happen every time, but certainly at P95. The tokens have gotten so long that it always goes down the path of putting it as a header for me

**Comment by vladsud** [comment]
@danielroney, any chance you can help here by working with SPO on design / implementation from their side?
I.e. ping Ram for him to own first part of it and communicating to us a solution that we implement on client side?
There is precedent here, so it should not be something out of the blue for SPO

**Comment by danielroney** [comment]
I can help drive this, but just so I understand... I thought OPTIONS was for determining api communication options at run time. Can't we know these options at dev time and just assume we'll send the token in the header without paying the OPTIONS tax? Or are POST requests still preferable to GETs independent of the OPTIONS tax?

**Comment by christiango** [comment]
Options requests are made by the browser, not by our code. It happens whenever we have a custom header on the request.

The biggest problem with OPTIONS is that it adds a network roundtrip that impacts performance at higher percentiles.

**Comment by christiango** [comment]
Here's a write up on OPTIONS/Preflight requests:
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

**Comment by curtisman** [comment]
See discussion in issue #4811.  @jatgarg mentioned that the server already accept the POST call.  So it should be pretty simple to switch it on the client side.  Assigning to Jan and @jatgarg to do the work.   If the work can be done across the board, we might want to dup this to #4811 and have that issue track the work.

**Comment by christiango** [comment]
Oh cool, it looks like a dupe of #4811, fine resolving this as a duplicate of the recently opened #4811
