### ISSUE TITLE
Upgrade to Typescript version 4

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4800]
We currently use typescript version 3. Most of our partners are on 4, and we think there are improvements around incremental build in 4 that will increase the stability of our build process.

@skylerjokiel this could impact your area? Any thoughts?

FYI @curtisman

**Comment by tylerbutler** [comment]
From <https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/>

> With TypeScript 4.0, there are no major breaking changes.

That's reassuring.
