### ISSUE TITLE
Snapshot tests: Add capability to test handle tracking across summaries

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#4810]
#5135 tracks adding a basic way to test summaries. This issue tracks adding more functionalities such as tracking handles across summaries and verifying that we don't re-summarize or generate GC data when its not expected.

**Comment by markfields** [comment]
@agarwal-navin this looks like a dupe of #5135, if so please close.  Thanks!

**Comment by agarwal-navin** [comment]
Its not a dupe. Its confusing, I was being lazy when I updated these issues :-P.  I will update the title to reflect that.

**Comment by tylerbutler** [comment]
@agarwal-navin @arinwt Do you think there's more design thought/planning required here? If so, when do you plan to be ready to execute?

**Comment by agarwal-navin** [comment]
Yes, I think this does need some designing work. Currently, we are both busy with some high priority work. I think we should look at this in June. @arinwt, what do you think?

**Comment by arinwt** [comment]
Closed by #6860
