### ISSUE TITLE
Use POST calls in odsp driver for blobs, ops etc.

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#4811]
## Feature
Move the getOpStream, getBlob etc calls in odsp driver to start using the POST flow instead of get flow so as to save options call.

**Comment by curtisman** [comment]
Is #4796  a dup of this issue?

**Comment by jatgarg** [comment]
https://github.com/microsoft/FluidFramework/issues/4796 is subset of this issue.

**Comment by curtisman** [comment]
@jatgarg is there server work that needs to drive here, or are those already in place?

**Comment by jatgarg** [comment]
Those are already in place now. We were seeing how the post call for trees latest works. Since that works fine, we can move other get calls too.

**Comment by jatgarg** [comment]
I would probably try to achieve this in jan itself so that we can see the improvements sooner.

**Comment by vladsud** [comment]
Note: this is lower priority than https://github.com/microsoft/FluidFramework/issues/4769.
Moving it for now.

**Comment by vladsud** [comment]
Talked to Marcelo and he had some really good points here:

When URI is too long (or always with POST), we should move only token into headers, and leave epoch and other key arguments in query string. This is a mush for many APIs to be cachable (including fetching blobs). I.e. if epoch or blobID is not in query params, then request would be non-cachable by browser.

Setting it to April

**Comment by jatgarg** [comment]
"When URI is too long (or always with POST), we should move only token into headers, and leave epoch and other key arguments in query string" - Yes we already follow that.

**Comment by jatgarg** [comment]
Closing the issue with above PR as we won't be moving blobs call to post as that would make it non browser cacheable and we want that for blobs.
