### ISSUE TITLE
API to Force a Container to Reconnect in Write Mode

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4813]
## Feature
Currently in order to transition from a read connection to write connection we need to issue and op, and then wait for that op to submit, nack and reconnect. This is what a number of our tests do. There are also cases, like for setting a new code proposal, or other quorum value where we'd want to update to a write connection before issuing the request.

**Comment by vladsud** [comment]
I believe there should be no such direct capability, and instead we should address the short comings in particular areas. For example:
1. Quorum is the only DDS that does not do proper retries. It's not the problem of forcing initial connection to "write", it's the problem of failing on losing connection (and having retry baked into it or having a layer on top that does it).
2. The other area where it shows up - task selection (Agent scheduler). There are two different intentions when developer picks task - developer either want to make changes only if we are already in write mode (background opportunistic task), or force it (task selection is result of user action).

 In # 2, I believe it's expected that DDS would attempt to send an op and it would make it through by flipping connection mode (i.e. switch of mode is indirect, no direct API to do so).

**Comment by anthony-murphy** [comment]
I've come around on this and fully agree. we can just close this.
