### ISSUE TITLE
SummaryAckWaitTimeout after Version Restore (Epoch change)

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#4832]
Version restore for ODSP storage results in the data going back to a older time. Epoch number will change on the protocol to indicate that the version of the data and op stream has diverged from the version before, so that the client should reload.

However, the data could be (always for ODSP?) restore to a time where a Summary is submitted, but the `SummaryAck` isn't in the op stream.  That result in the client to wait for 2 mins (and issue the `SummaryAckWaitTimeout` error) before it would summarize.

The client should be more resilient and summarize immediately if the the `SummaryOp` was from the previous Epoch from it's own `Join` message.

**Comment by curtisman** [comment]
FYI @vladsud

**Comment by anthony-murphy** [comment]
seems related to #3881

**Comment by arinwt** [comment]
Discussed with @jatgarg, we are thinking #3881 will cover this scenario as well in most cases. The client join op (at least) will have a server timestamp significantly later than the original summary op, which should bypass the summaryAckWaitTimeout.

**Comment by curtisman** [comment]
How well can we rely on the server time stamp? (Is it UTC? Will it change completely when changing server? Etc.)

**Comment by jatgarg** [comment]
Actually it should work fine as I talked with @GaryWilber . They just use Date.now() which is:
"The static Date.now() method returns the number of milliseconds elapsed since January 1, 1970 00:00:00 UTC."

**Comment by jatgarg** [comment]
Closing with above PR. https://github.com/microsoft/FluidFramework/pull/5117
