### ISSUE TITLE
quick start fails with no UI

### ISSUE THREAD

**Issue by amdeymsft** [microsoft/FluidFramework#4836]
## Describe the bug
following instructions at https://fluidframework.com/docs/get-started/quick-start/
npm start generates a website with no UI

### To Reproduce
following instructions at https://fluidframework.com/docs/get-started/quick-start/
note UI is empty

### Expected behavior
Dice Roller UI

### Logs
from windows terminal
[start:server] C:\Users\amdey\repos\FluidHelloWorld\node_modules\@fluidframework\server-services-utils\dist\asyncLocalStorage.js:16
[start:server] const asyncLocalStorage = new async_hooks_1.AsyncLocalStorage();
[start:server]                           ^
[start:server]
[start:server] TypeError: async_hooks_1.AsyncLocalStorage is not a constructor
[start:server]     at Object.<anonymous> (C:\Users\amdey\repos\FluidHelloWorld\node_modules\@fluidframework\server-services-utils\dist\asyncLocalStorage.js:16:27)
[start:server]     at Module._compile (internal/modules/cjs/loader.js:776:30)
[start:server]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
[start:server]     at Module.load (internal/modules/cjs/loader.js:653:32)
[start:server]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[start:server]     at Module.require (internal/modules/cjs/loader.js:690:17)
[start:server]     at require (internal/modules/cjs/helpers.js:25:18)
[start:server]     at Object.<anonymous> (C:\Users\amdey\repos\FluidHelloWorld\node_modules\@fluidframework\server-services-utils\dist\index.js:18:10)
[start:server]     at Module._compile (internal/modules/cjs/loader.js:776:30)
[start:server] npm ERR! code ELIFECYCLE
[start:server] npm ERR! errno 1
[start:server] npm ERR! @fluid-example/hello-world@0.1.0 start:server: `tinylicious`
[start:server] npm ERR! Exit status 1
[start:server] npm ERR!
[start:server] npm ERR! Failed at the @fluid-example/hello-world@0.1.0 start:server script.
[start:server] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

from browser console
Uncaught ReferenceError: process is not defined
    at Object../node_modules/util/util.js (util.js:109)
    at __webpack_require__ (bootstrap:18)
    at Object../node_modules/assert/build/internal/assert/assertion_error.js (assertion_error.js:35)
    at __webpack_require__ (bootstrap:18)
    at Object../node_modules/assert/build/assert.js (assert.js:36)
    at __webpack_require__ (bootstrap:18)
    at Module../node_modules/@fluidframework/routerlicious-driver/lib/documentService.js (app.c7affda94a877a27f2f0.js:18889)
    at __webpack_require__ (bootstrap:18)
    at Module../node_modules/@fluidframework/routerlicious-driver/lib/documentServiceFactory.js (app.c7affda94a877a27f2f0.js:19057)
    at __webpack_require__ (bootstrap:18)

**Comment by a-tarasyuk** [comment]
Which version of NodeJS do you use to run the example? ["async_hooks"](https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage) available since _v12.17.0_,  _v13.10.0_. I didn't find any mention of supported NodeJS versions, maybe need to add them or add some _polyfill_ for `async_hooks`.

**Comment by amitdey1987** [comment]
my version of node.js is 14.15.4

**Comment by amdeymsft** [comment]
my nodejs version is 14.15.4

**Comment by skylerjokiel** [comment]
Thanks @amdeymsft , I can also reproduce this and I'm taking a look.

**Comment by micahgodbolt** [comment]
This was due to a webpack upgrade. Reverted to a working version of webpack here https://github.com/microsoft/FluidHelloWorld/pull/53

**Comment by amdeymsft** [comment]
thank you I was able to validate the fix.
