### ISSUE TITLE
Routerlicious driver is not compatible with Webpack 5

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/FluidFramework#4843]
Webpack 5 removes the 'process' polyfill 

> process is not defined.
webpack 5 does no longer include a polyfill for this Node.js variable. Avoid using it in the frontend code.

https://webpack.js.org/migrate/5/

Routerlicious still depends on 'process' and will silently fail on start. This happened when upgrading our helloworld example.  

see https://github.com/microsoft/FluidHelloWorld/pull/53

**Comment by mohamedmansour** [comment]
Any update on this? Even adding the alias "process/browser" doesn't work.

**Comment by mohamedmansour** [comment]
To make it work with Webpack 5, you need to add this to webpack config:
```
  plugins: [
    new webpack.ProvidePlugin({
      process: 'process/browser'
    }),
  ],
    resolve: {
    alias: {
      "buffer": "buffer",
      "url": "url",
      "querystring": "querystring-es3",
      "crypto":" crypto-browserify",
      "stream": "stream-browserify",
    }
  }
```

Adding the `process/browser` to an `alias` didn't work, but ProviderPlugin did work.

**Comment by tylerbutler** [comment]
This should not have been closed.
