### ISSUE TITLE
Documentation & Topic Structure

### ISSUE THREAD

**Issue by SamBroner** [microsoft/FluidFramework#4847]
The existing documentation on FluidFramework.com is fairly encyclopedic. Can we improve the learning path through Fluid so that developers can easily learn about Fluid and do new useful things with every topic they learn?

I propose we have a *flatter* learning structure, where there are 1 or 2 lessons we expect developers to learn, but, after that, mostly all topics start from scratch and address a specific scenario.

## Proposed Topics
Hello World
- [ ] [Get and Set Data](https://github.com/microsoft/FluidFramework/issues/4737)

Hello World ++ (10x level course)
- [ ] Alternative Views {React, Vue, Angular, etc)
- [ ] Connect to managed service (should this be as simple as: How to play with your friends)

20x  level courses
- [ ] 2nd Data Object in container(same type)
- [ ] 2nd Data Object *type* in container
- [ ] DIY DataObject
- [ ] Using DDS
- [ ] DataObject w/ View (Do we have a specific name for this?)
- [ ] [Host a Fluid Gateway](https://github.com/microsoft/FluidFramework/issues/4736)
- [ ] Building a Fluid Package
- [ ] Testing a Fluid Application

30x level courses
- [ ] Authentication
- [ ] Access Control
- [ ] Two containers on one page
- [ ] Build your own Distributed Data Structure
- [ ] Custom Container Requests
- [ ] Batch operations
- [ ] Upgrade from container version 1 -> container version 2

## Exit Criteria
The exit criteria of this issue is (1) verifying this list & (2) building out & linking issues for each scenario.

**Comment by curtisman** [comment]
@tylerbutler FYI

**Comment by LarsKemmann** [comment]
This is helpful. The documentation should _start_ with Aqueduct, and not introduce all the lower-level stuff until later. If Aqueduct is supposed to be an easier onboarding route, that should be what's used in _all_ the 10x & 20x documentation.

**Comment by tylerbutler** [comment]
@SamBroner Do you want stubs created for any of these topics?
