### ISSUE TITLE
Improve Loader policy specification/move stateful Container options into Loader policy

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#4880]
Followup from issue #4489, pull #4862

There are some stateful options (`LoaderHeader.cache`, `LoaderHeader.pause`, `LoaderHeader.reconnect`, and forceReadonly in particular) that can be provided in a Loader request that get applied in some way when the Container is created.  These options should not vary per Container, and should be consistent across all Containers created by a Loader.  If different options are needed, a new Loader should be created first.  This is particularly relevant in the guest component case, where a container will load another container.  The loading container does not know about the host's policies, but they should be applied by default to the loaded container.  To that end, these options should be moved into the Loader policy from request headers, and consumers should be updated to create a new Loader where needed.

**Comment by anthony-murphy** [comment]
related to this, i've also thought we might was container create event on the loader, than a host can you to manage all containers created by their loader. this will then give the host visibility into guest containers and allow it to apply a consistent policy to those as well as host created containers

**Comment by heliocliu** [comment]
Some points came up about how static loader policy may go against the goals of the loader which I was hoping @vladsud you could comment on (going off your [comment here from an earlier pr](https://github.com/microsoft/FluidFramework/pull/4862#discussion_r561652647).  Particularly, that these options that currently exist in request headers (e.g. `cache`, `pause`, and `reconnect`) tend to lead us to create a loader for every single container (where we may typically expect to create many containers with a single loader), and where the idea of creating a new loader for a different policy doesn't really feel like it solves the problem and only introduces additional steps that weren't present before.  Though I don't think this applies as much to an arbitrary policy function that a host may provide (which may be more what you were referring to, in which case this is more about what to do with the existing stateful options).

The summarizer for example already changes these options, meaning in a very basic case an additional loader is getting created.  For other cases that want a specific policy and may not be aware of the host policy, if they are allowed to create a new loader it sounds like this will lead to them creating a new one in every case, which also feels like it defeats the point of having the policy in the first place (though not sure if this is expected to be possible in a data object).

So I think for the existing options, even if they are made available as static loader policy, it would make sense to still allow them to be overridden to be more restrictive as part of requests.  This provides a bit more flexibility to avoid creating extra loaders, while also enforcing the same restrictions.

**Comment by heliocliu** [comment]
Closing for the above reasons.  The arbitrary policy callback for the loader is handled in another issue.
