### ISSUE TITLE
Redact error messages from dependencies we don't control to avoid PII leaks

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#4908]
We've seen several cases where we log verbatim the `message` property from an error object that comes to us from a dependency (e.g. the server), and find later that it contains info we'd rather not log. We should consider how to avoid this.  Something like mark up such info in the FDL and then our internal partners can only log that in certain cases (e.g. for internal users).

**Comment by vladsud** [comment]
Moving to Feb - work in privacy domain is a must for GA.

**Comment by markfields** [comment]
@vladsud's comments:

> I personally thing that scrubbing will not scale. I'd rather do this kind of ladder:
> 	
> 1. Internal users (MSFT), only our code: log everything
> 1. 3p: Drop all info about IDs (like component IDs, including stack)
> 1. external users: drop all info about error (i.e. message, stack)
> 
> This makes it much easier to manager it. And with enough internal users problems are likely to be hit in this ring, so we will have at least some sessions that will give us actionability. And the rest will give us counts.
>  
> I initially implemented 2 for all users (partially, as stack is still there), and what I've learned is that it's really hard to make progress without that information. We keep using backdoor (the fact that stack is still collected) as a way to work around it. So I think dropping information ALWAYS will make it almost impossible for us to act on some of the escalations, and we need our internal ring to be the one that provides all the data.
>  
> I'd add that I want something like perfTrack in WIndows, i.e. system that can dynamically enable providers and collect data (on machines that hit problems), but that's probably a dream that is way out...

**Comment by markfields** [comment]
Just chatted with Vlad, adding some additional commentary to the above.

The guiding thought is to go with an "opt-in" model for any sensitive data, rather than "opt-out". So details from errors are assumed to be too sensitive to collect unless we can be assured that they're not. Of course this will be an iterative effort but we'd rather carefully dial up collection to ease investigation rather than have to deal with privacy incidents and dial back.

Practically, this will likely mean certain logging/error APIs including `assert` need to support some additional metadata for tagging purposes, and then the logger implementation provided by our 1P and 3P hosts can inspect those tags to determine what properties are permissible to be logged.

**Comment by markfields** [comment]
Thinking about a design along the lines of the code sketched out below (written here, not in a .ts file...), probably a little simpler in terms of the tagging/grouping of properties.  Also need to really decide if we want to default to redacting `message` from foreign errors.  Will make debugging _very_ hard and I think convention typically would be for those to be hard-coded but apparently not always, from our recent experience.

These interfaces/functions would go in `common-definitions` and `common-utils`, and we would update `assert` and all our `Error` types to use these interfaces.

```typescript
interface IFluidTelemetryProps {
    safe: { [key: string]: value };
    codeInfo: { [key: string]: value }; // e.g. callstack
    pii: { [key: string]: value }; // e.g. EUII, OII
}

interface IFluidError extends Error {
    errorType: string;
    getFluidTelemetryProps: () => IFluidTelemetryProps;
    addTelemetryProps: (props: IFluidTelemetryProps) => void;
    innerError?: any;
}

function isIFluidError(err: any): err is IFluidError {
    // check for presence of errorType and getFluidTelemetryProps
}

function wrapInFluidError(err: any): IFluidError {
    if (isIFluidError(err)) {
        return err;
    }

    return {
        errorType: "generic",
        message: err.message,  // Apparently even this is unsafe... but might want to budge on that...
        getFluidTelemetryProps: () => ({
            codeInfo: { "stack": err.stack }
        }),
        innerError: err,
    };
}
```

**Comment by markfields** [comment]
This needs a bit more thought at this point, adding `design-required` label. Will not converge in Feb, plan to move to March.

**Comment by markfields** [comment]
Ok I've been thinking in this space for quite a while now. The conversation has ballooned way beyond the scope of error messages (per the title), and I want to discuss that briefly so we can once again just focus on error message.

The main (only?) source of privacy incidents (actual or potential) has been due to **our own logging code actively logging TMI for with data coming over the wire from the service**.  See https://github.com/microsoft/FluidFramework/issues/6139 as a PRIME example. So we need to fix that issue and be vigilant (including doing some auditing) to ensure we are not being too permissive here.

As for a "foreign" error object thrown somewhere that we catch and attempt to wrap/handle, we are already careful to only copy over `message`, `stack`, and `errorType`. So the question becomes - when would "foreign" code (e.g. a package dependency from npm, or someone else's component) throw an error that would include personal data _in the message, stack or errorType fields_.

And for this, let's separate out the "Code Artifacts" type stuff (package name, function names, etc from 3P code) from the "User Personal Data" type stuff (content, user names, etc).  For the former, it's not an issue today for Msft because we have no 3P code loaded in 1P experiences.  This concern is heavily on our minds for when we start pursuing those scenarios.

In my estimation, `stack` cannot contain user personal data.  And `errorType` feels very safe as well, unless someone is trying to troll us (if you're reading this - please don't! ;)).

So that leaves `message`.  This is where I can truly imagine a problem, e.g. some text-based component encounters a bug and throws an error with the contents of the broken text run in the message. The best strategy I have in mind is to always throw errors marked in some way so that we can distinguish errors we threw v. unknown errors, and if it's unknown, we can't preserve the message.  The message is usually also in the stack, so we also would need to scrap the stack.

The alternative is to take a "wait and see" approach, and lean on the "PII scanners" already in use to detect such leaks, and clean them up as they come.  I believe this may be a valid choice, and will continue to look into it so we can close this out.

**Comment by vladsud** [comment]
I do not have answers, but some random thoughts:

JS runtime error will include names of properties. Is this Ok to log from 3P?

I think over time it will be all about defaults, SLAs, options and particular scenarios and expectations. I.e. 3P having ability to understand default collection policy and their implications and ability to chose different defaults, including not sending any data to MSFT. Maybe it should be default, hard to say.

I also think it will differ based on how users perceive what they interact with. If it's add-in installed by user, then it's logical to assume that it's add-in responsibility to make right steps to adhere to SLA it provides to a user. But if it's 1P installing some extension points without communicating to a user changes in SLA re privacy and data collection, then it's our responsibility to ensure right things happen (i.e. adhering to our original SLA with users).

**Comment by markfields** [comment]
Splitting hairs here - I think "Privacy Agreement" is the term you mean when you say "SLA" (which means "Service Level Agreement" and typically refers to service up-time).

**Comment by markfields** [comment]
I think we are ready to close this issue out in its current incarnation.

* We should strip the error message from the stack to isolate the problem, see #5559
* We should continue to wrap errors of unknown origin into our own error objects with an `errorType` and a static `message` that allows easy correlation between logs and code. Other relevant data should go in telemetry props, rather than using a string format for the message
* When we wrap an unknown error, what do we do with its message? Today we use it on the new error object. But instead we can use the `name` property on `Error` if present, and prefix with a static message, delimiting with `:`. The error message itself can go on an `innerError`. We will need to be auditing this column for sensitive data, and at some point tag it as well per Vlad's last comment.

I have a more detailed proposal written up in an internal document which I plan to share with the team next week.

**Comment by markfields** [comment]
After thinking this through some more, I realized - the fundamental problem here is that we are "overloading" in a sense the `message` field, for both the kind of static "error code" strings I'm promoting in my latest comment, alongside raw/unknown messages from `Error`s thrown to us.

Better to leave `message` as-is, and add a new concept of `errorCode` which will be string consts as described above.

**Comment by markfields** [comment]
Full proposal is [here](https://microsoft-my.sharepoint-df.com/:fl:/p/mfields/EfCSIi1Po7ZOmFlYOTSOiMUBjr-piHG0c6YNR0kf1tdOhg?e=nWiVBx).  I wish I had written it as a GitHub discussion to be open to the community - if anyone outside Msft is reading this and wants to hear more, let me know ;)

**Comment by markfields** [comment]
Rethinking the last few comments - My proposal is really addressing #6315. It's related to this in that it will hopefully help us be less dependent on the root error/stack, so that in the future we could do what this issue is about - redact them in different environments.  I've opened https://github.com/microsoft/FluidFramework/issues/6609 to track the work to actually tag foreign error messages (distinct from error codes we instrument ourselves).

For now, though, we are not going to prioritize that.  I also wrote a tool to help audit error messages to potentially identify content that doesn't belong, but until we have a concrete case in hand, I don't think it's a top priority.

Cases mentioned in the initial comment are more about how we parse and log stuff when creating our own error objects, and we need to continue to be disciplined there, but that's not directly relevant to this.

FYI @vladsud on this direction.  Closing this one out.

**Comment by markfields** [comment]
As for the 3P-in-1P scenarios, I think the basic tagging work already done is sufficient for now and won't be opening another issue to drill in more there. The interesting work for Office Fluid is probably more going to happen in our private codebase anyway.
