### ISSUE TITLE
Provide easier way for Bohemia to trigger summarization during tests

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#4909]
Currently there is some friction on the Bohemia side around triggering summarization during their tests.  While we test summarization on our end, Bohemia needs to test it as well in their document compatibility test case (so they can verify that their old documents will load and summarize correctly under newer runtimes).

We need to look into our own summarization tests and determine if they can be replicated for Bohemia, and provide guidance on how to do so.  If the steps are too difficult/complex, we will need to create a simpler way to trigger it first.

**Comment by heliocliu** [comment]
@leeviana fyi

**Comment by vladsud** [comment]
@agarwal-navin - this feels like non-stop ask in light of GC work. Are there dups?
Also this is part of request in https://github.com/microsoft/FluidFramework/issues/6260
Should can we close as dup?

@arinwt - FYI

**Comment by agarwal-navin** [comment]
IMO, there are 3 different types of APIs needed for testing summaries:
1. An API to generate summary which can then be analyzed if needed. It will run locally and the summary is not sent to the server. This is what the current `summarize` API on container runtime can be used for and we have tests that do this. We should make this more easily accessible though.
2. An API to generate summary when needed and this summary gets uploaded to the server and ack'd. Basically, the regular summarizer flow with ability to control when the summary happens. We don't have this today and it may not be straightforward to add this. # 1 and # 2 can probably be done via the same API.
3. An API to generate summary which can then be used to load another container. This will be similar to the `serialize` and `rehydrateDetachedFromSnapshot` APIs on the Container except that it can be run on an attached container. Basically, # 1 plus an API that can load a container from the summary. I believe this is the ask in this work item.

We should probably create issues for these 3 scenarios and everything should fall into one of these buckets.

Having these APIs will be helpful not just to the users of framework for also to the framework itself. I have been wanting to have these in place for our testing anyway :-). I am not sure about the priority though. Even though some of them are not straightforward but we do have tools to do all of these currently.

**Comment by leeviana** [comment]
Not stale

**Comment by curtisman** [comment]
@NicholasCouri Does #8251 address this issue?  Do we have documentation around how this can be achieved?

**Comment by NicholasCouri** [comment]
> @NicholasCouri Does #8251 address this issue? Do we have documentation around how this can be achieved?

This is the first time I'm seeing #8251 - I don't think we have documentation around it. Do we have @agarwal-navin? I was looking at #8251 and would it be possible for partners to use the same idea we had on the end-to-end tests Paul had created?

**Comment by agarwal-navin** [comment]
Yes, I would say it is covered by #8251. I am currently updating our tests to use `summarizeOnDemand`. We can use this in Bohemia as well. We will probably learn the pain points around restrictions around summarizer election and we can improve it for testing.

**Comment by leeviana** [comment]
Did we ever add this documentation so we can try using this in tests?

**Comment by leeviana** [comment]
@agarwal-navin do you have the docs/usage of the summarizeOnDemand API?

**Comment by agarwal-navin** [comment]
@leeviana `summarizeOnDemand` is used extensively in our end-to-end tests. It's used in the office-bohemia repo in a couple of tests as well. You could take a look and try it other use cases if needed and give us feedback.
I will close this work item since `summarizeOnDemand` is available for use.
