### ISSUE TITLE
GC -> partial snapshots -> failure to download blobs / blob de-duping

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4940]
State of the world:
1. As part of implementing better blob de-duping algorithm, we realize full tree.
2. As part of GC work, we will be marking trees as not used and storage will not include them in snapshot
3. Aa part of perf work, we are punting for GA ability to deal with partial snapshots (with exception of images), i.e. whole system will not work well (if at all) if there are some blobs that are missing in snapshot but are needed by runtime.

This results in two potential gaps:
1. If part of the tree is returned back to life (undo/redo, copy/paste) clients will start reading these blobs that are missing from snaphot. And given that we only have single-blob-read API, that will add a lot of latency and a lot of stress on server
2. Blob-deduping process does not deal with it right now at all:
```
        for (const [key, value] of Object.entries(snapshotTree.blobs)) {
            const blobValue = this.blobCache.get(value);
            assert(blobValue !== undefined, "Blob should exists");
```

Let's use this item to defined a plan, then we can figure out actual work items.

I have a feeling that plan needs to include these items:
1. An API to read many blobs at once. Possibly we can push it out as a fast follow up to GA, but then it means we also push out summaries returning partial results (including GC blobs).
2. Make blob-deduping more intelligent and at least not crashing.

**Comment by jatgarg** [comment]
I will follow up on blob deduping part :)

**Comment by vladsud** [comment]
@jatgarg, can you please fork (and reference issue) and make sure it gets in this release? Otherwise images would get broken when this release gets integrated into Bohemia. Can you please double check it did not made it into 0.33? Thanks!

**Comment by jatgarg** [comment]
You mean we need to put a hotfix in 0.33 and make this sub issue a blocker for 0.33 integraation?

**Comment by vladsud** [comment]
If de-duping work is in 0.33, then yeas, we will trip over that assert on images, as they are not included into snapshot.
Should be easy to test in our repo as well

**Comment by jatgarg** [comment]
Sub issue for blob deduping part: https://github.com/microsoft/FluidFramework/issues/4945

**Comment by anthony-murphy** [comment]
if we remove blob debupping as part of #5444 is this work done?

**Comment by vladsud** [comment]
I think so

**Comment by markfields** [comment]
Closing this then... (getting May Reliability items in order)
