### ISSUE TITLE
Make blob deduping deal with blob absences while snapshot fetch

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#4945]
## Describe the bug
As part of implementing better blob de-duping algorithm, we realize full tree.
Blob-deduping process does not deal with it right now at all. It will crash in case of blob absence which will come soon for images.:
        for (const [key, value] of Object.entries(snapshotTree.blobs)) {
            const blobValue = this.blobCache.get(value);
            assert(blobValue !== undefined, "Blob should exists");

Make blob-deduping more intelligent and at least not crashing.

**Comment by vladsud** [comment]
This is regression in 0.33, so we need to get it out soon.
It's not blocking wide public as it impacts only images (external blobs), but keeping it broken will hinder ability to make progress in this space, that's bad.

**Comment by jatgarg** [comment]
Pr is already out. Please review.
