### ISSUE TITLE
Driver: blob read / write is retried infinitely when an assert in hit in the storage service

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#4946]
I was testing a new storage service where I was writing a snapshot. The code hit an assert but the RetriableDocumentStorageService kept on retrying the write.
I don't think we should retry read / write when an assert is hit in the client code.

Maybe the canRetryOnError check needs to be flipped to:
```
export const canRetryOnError = (error: any): boolean => error?.canRetry === false;
```

**Comment by jatgarg** [comment]
Can you also paste an example assert error object that we were catching in this storage service? @agarwal-navin

**Comment by agarwal-navin** [comment]
I implemented an `IDocumentStorageService` whose write method had an assert that was getting hit. I don't have an example right now but I can try to repro or help you repro it.

**Comment by agarwal-navin** [comment]
Oh and I called `snapshot` on the Container which attempted to write.

**Comment by vladsud** [comment]
Raised PR, but there are some big questions for FRS, which might push executing here further out.

**Comment by jatgarg** [comment]
Should we also add some kinf of max retries for errors? 
1.) If we are online then we will respect this limit.
2.) If we are offline, then we can retry indefinitely?

**Comment by agarwal-navin** [comment]
Yes, we should. I was going to create an issue to track this. I think we should give up retrying after a certain number of retries or after certain time.
