### ISSUE TITLE
When parsing handles during load, enable loading the Fluid object locally

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#4950]
Today, when handles are parsed and the underlying Fluid object is loaded, it always goes via the root. The handle resolution logic should be smart enough to load the Fluid object locally without going to the root if possible.

This will enable scenarios such as when a DDS is being loaded but the parent data store has not been loaded. If we always go through the root, it will not be able to reach the data store since it hasn't been loaded yet.

**Comment by vladsud** [comment]
@agarwal-navin, with the move toward reusable components (see https://github.com/microsoft/FluidFramework/issues/4265), there will be more and more cases where data stores will store their dependencies as handles without their own DDSs and will need them to correctly operate. This, couple with potential circular references between data stores will make it impossible for data store to operate on partial state.
As such, I think we should strive to give control to upper layers (like Aqueduct) when data store is fully loaded (up to current sequence number) and registered in system (currently - with container runtime).

I think something like last edited should have some unique treatment here, but not in the form of giving control to random data object before it can operate on any handle.

Let's clarify scenario and clearly articulate success creteria.
