### ISSUE TITLE
SPO driver may need to synchronize calls to storage when working with sharing link that needs redemption

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4954]
This is based on "Possible 404 retrieving SPFile while concurrently redeeming" email thread.

We can get a sharing link to SPO file that needs redeeming.
Hosting app encodes driverID & itemID in query param that is preserved by SPO, so we get resolved URI without calling SPO.
SPO has special logic to try to redeem sharing link in TreesLatest call.

But client could make parallel request to storage (ops) or joinSession, and those fail with 404 if file was not yet redeemed.
As result, we fail to open a file and user needs to refresh page to make it work.

Discussion in the email suggests that the only way to solve this problem is for client to
1. Always retry if first call to storage or joinSession hits 404
2. Do so only after TreesLatest comes back (i.e. add synchronization).

Please note that as result of https://github.com/microsoft/FluidFramework/pull/4905, we do in fetch ops in parallel to TreesLatest in 0.34. If that problem impacts existing shipping scenarios, then we have to have a fix before we fork 0.34.

@sumedhb1995, can you please fill in more details here?
Specifically, does this impact existing shipping scenarios? I assume the answer is yes, and that means it's high priority task, right?

**Comment by sumedhb1995** [comment]
From the Teams 3P integration perspective, we will be showcasing the code to partners in two weeks time and they will be building off of it to develop their Fluid object. 
We were seeing this issue show when one user would share the file org-wide as part of the creation process and the first time the second user attempted to load it. This race condition would trigger anytime the container was loaded in a non-paused state. The second user could see the current state of the object but not make any edits until they refreshed the page.
There's a temporary work-around in place by loading the container in "paused" state in the initial request and resuming after we have resolved it, but ideally the host's interaction with the container should not be dependent on the driver functionality

**Comment by vladsud** [comment]
So some info based on code inspection:
1. It not applicable to ops (on main flow), as we fetch ops only after getting snapshot.
2. joinSession is not impacted in existing shipping workflow, but that's what block exploration in 3P scenarios and not good for long term health of driver, so we need to fix it.
3. Any fix should take into account that operation on a file can start with either of these workflows:
   1. creation of file: there is no TreesLatest call in such case.
   2. TreesLatest call to read snapshot
   3. getVersions() call asking for N versions (that's what fetch-tool does).

3.i works as is, but we need to remember about it when working on 3.ii not to regress it.
3.iii is something that we might punt - as we essentially need to add shared link redemption into it.
