### ISSUE TITLE
Load Container with Storage Only Mode for ODSP Versions

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#4956]
## Work Item
ODSP is working on support for version history, and we'd like to enable loading from those versions throughout the runtime. These versions will be readonly, and only have storage, no delta connection.

From the driver perspective there will be an additional file version token that the driver will pass with all calls. All storage calls will be possible, but there will be no delta connection. This work should be straightforward, as the url revolver will parse the incoming version token, and ensure it's provided on calls.

The more complex work here is choosing the interface between the driver and the Container to support not connection to push, and secondarily support from the Container downwards for this mode. Ideally the behavior here aligns with our current read-only permission mode in terms of signaling to data stores that changes are not allowed. Additionally, we will also need to deal with the lack of, or mimic a connected event, as there will be no signal sent from the sever as this is in our current read only modes

**Approach**
I see a few possible approaches here

- Expand driver interface so driver can tell the container not to connect to storage
- Throw a permanent error from the driver the signals to the container it should not connect to storage
- Have the driver give the container a fake delta connection

Of these approaches I think expanding the interface or using a fake delta connection are the better paths, but open to other ideas.

All of the approaches should align with the existing readonly permission mode for signaling that datastores should not generate operations. However, there will be complexity around the connected properties and events. Currently I'm leaning towards setting connected to true, as it matches the caught-up intention assumed by most consumers of connected. We also need to consider properties like clientid and audience. 

We should be able to test this with our existing test server, local and tinylicious by using whatever contract we decided on to prevent connecting to the delta stream and only using storage snapshots and deltas

**Comment by anthony-murphy** [comment]
fyi @curtisman and @vladsud

**Comment by anthony-murphy** [comment]
we should also consider the work in this project when designing this: https://github.com/microsoft/FluidFramework/projects/43

**Comment by vladsud** [comment]
Snapshot caching should be disabled (read & write) in such mode.
Loader caching containers is another thing to look at.

Not 100% sure, but I think mimicking being connected (at some level, maybe only at Container) is good as it does not blead special casing to every host (i.e. we do not want yellow disconnected banner). That said, I assume host needs to know about this state change existing read-only banner to be more on point on why user can't change file.

While creating fake delta connection is appealing, op fetching is another thing / interface that needs to be faked.

Is it given that such files will not have ops (including cached as part of TreesLatest response)? Or we chose to ignore them? I'd guess SPO versions are cut at random times, are they just ignoring the tail?

**Comment by anthony-murphy** [comment]
good points about caching. 

I've chatted with marcelo, and it sounds like all storage calls including deltas will work as expected in this case. it's just the push channel that will need to be skipped. so files may have an op tail in deltas, but i think we should load it, unless there are unique runtime problems we'll face, as it's really not different than the restore case.

I also agree that host need to be able to detect this. Open to ideas for the api host can use, my guess is we will either expand and existing property, or just add a new one. Existing properties like active, readonly, readonlyPermisison, connected, and connectionMode should also correctly represent this state and be equivalent to readonly permisison

**Comment by vladsud** [comment]
I just raised PR https://github.com/microsoft/FluidFramework/pull/4985 based on data loss accident. I think the key learning - people have hard time reading documentation and following state machine. So I'd suggest expanding existing "readonly" event and adding extra argument (enum) describing why it's readonly, such as
- permissions
- forceReadonly() call
- versioned access

This has a bit more chance of people paying attention, as they are already likely to use this event (it's in readme.md section - one of few things that we say host need to pay attention to).

**Comment by anthony-murphy** [comment]
awesome. that's exactly what i was looking for, and agree the fewer unique state the better, but we can expose metadata to differentiate where those states where necessary

**Comment by anthony-murphy** [comment]
i've started some prototyping of using a fake delta connection
https://github.com/microsoft/FluidFramework/compare/main...anthony-murphy:no-delta-stream
