### ISSUE TITLE
Remove special casing for "_search" path in data store not to treat it as DDS

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#4963]
Openning as a follow up to https://github.com/microsoft/FluidFramework/issues/4414
Once we partition snapshots into "user" and "system" sub-paths (not to have conflicts with "_blobs" data store, and "_search" DDS), we need to remove special casing of "_search" path under data store.
Currently data store needs to know about that special name not to treat it as a DDS.
This is not great, as fluid repo needs to know about concept that is not present otherwise in our repo.

This work depends on Arin completing the work to change file format, so assigning to you :)

**Comment by arinwt** [comment]
This needs to move out until May. The change to read in new format (with write disabled) came in March. The follow-up change to write in new format by default will come in April. Then only after that has settled, can we consider removing this.
