### ISSUE TITLE
Puppeteer end-to-end testing with multiple configs

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#498]
Currently the examples testing have a static config using jest-puppeteer. We should extend them to have a dev and a prod config.

The prod config should run headless with no slow mo. The dev config should run with a default slowmo and non-headless.

Add an additional script to all our examples ex: `npm run test:local` to run the dev script.

**Comment by vladsud** [comment]
Closing, as no progress over 1.5 years.
