### ISSUE TITLE
Uncomment assert to check IConnected contains epoch when connected to push in odsp driver.

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#4989]
## Describe the bug
In odsp driver, in order to make sure we correctly connect to same epoch in push, we make sure that IConnected contains epoch. However in prod, push is not yet returning epoch in IConnected. So once they enable it, uncomment the assert here.
https://github.com/microsoft/FluidFramework/blob/7b3b6c105f1dbc0c240a9070b5c548c88bbf2508/packages/drivers/odsp-driver/src/epochTracker.ts#L50

**Comment by vladsud** [comment]
I've checked and PUSH returns epoch, time to add assert and remove reference to this issue from code
