### ISSUE TITLE
Refactor readBlob consumption to call readAndParse

### ISSUE THREAD

**Issue by chensixx** [microsoft/FluidFramework#4991]
## Work Item

Fixes https://github.com/microsoft/FluidFramework/pull/4856#discussion_r561417581
currently readBlob is called and followed by bufferToString and JSON.parse. We can replace these 3 with one call of readAndParse.

**Approach**

Change readAndParse to call readBlob, then replace readBlob with readAndParse

**Comment by markfields** [comment]
Adding to Reliability Push project simply to track crew members' outstanding work
