### ISSUE TITLE
Incorrect @fluidframework/garbage-collector package version specified

### ISSUE THREAD

**Issue by Flavyoo** [microsoft/FluidFramework#5000]
## Describe the bug
Packages that have **@fluidframework/garbage-collector**  as a dependency, specify version ^34, but the latest published version is 33.3. As a result, when running an example app from the examples directory, npm install will fail.

### To Reproduce
1. Go to `FluidFramework/examples/data-objects/canvas`
2. run npm install

### Expected behavior
Example apps should build.

### Logs

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @fluidframework/runtime-utils@^0.34.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@fluidframework/shared-object-base'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/flavioandrade/.npm/_logs/2021-01-30T23_10_40_803Z-debug.log
```

**Comment by curtisman** [comment]
This package is part of the lerna repo at the root and needs to be built with the rest of the repo.

You can follow the instruction [here](https://github.com/microsoft/FluidFramework/wiki/Client)

**Comment by Flavyoo** [comment]
Sweet, thank you!
