### ISSUE TITLE
Investigate: Fetch error: TypeError: Failed to fetch 

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5009]
seeing an error that needs investigation. We should determine where the error is being thrown from, and if the error represents something we can fix, or if the error represents something we should indicate in an error is user provided functionality

**Comment by curtisman** [comment]
@vladsud I believe these are generic network errors that can happen anywhere.  There isn't more information we can get from the system, right?

**Comment by vladsud** [comment]
This is client being offline - fetch() will generate this error. It can happen for any fetch() call (i.e. snapshot fetch, ops fetch, joinSession, etc.).
We try to detect it and use different "virtual" status codes (mostly for logging, it does not change handling):

        if (`${error}` === "TypeError: Failed to fetch") {
            online = OnlineStatus.Offline;
        }
        if (error.name === "AbortError") {
            throwOdspNetworkError("Timeout during fetch", fetchTimeoutStatusCode);
        }
        throwOdspNetworkError(
            `Fetch error: ${error}`,
            online === OnlineStatus.Offline ? offlineFetchFailureStatusCode : fetchFailureStatusCode,
            undefined, // response
        );

This can probably be improved.

Note that these errors are retryable, but we were missing retry logic for some storage calls (including reading blobs, reading snapshot) and hat was added lately.
So number of cases where it gets to container failure should be small to none (soon).
But you will see things like summarizer failing with these errors all the time - that's normal.

**Comment by markfields** [comment]
This error is not bubbling up anymore.  Leaving this issue open since there is some actionable feedback/ideas in here.

**Comment by vladsud** [comment]
That's because we added retries to all APIs, including snapshot fetching.
The side effect of this - we need to solve the problem of host not having container, i.e. something to observe progress / cancel if user moves away (already tracked by issues)

**Comment by markfields** [comment]
Closing, the retry improvements helped pull this off the top of the curve, not a priority to drill into it until such a time as it bubbles up again.
