### ISSUE TITLE
Store actual code details in Container as result of CodeLoader.load()

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#5012]
It is somewhat common/expected that the actual loaded code version may differ from what's in the quorum. In this case, it would be nice if the Code Loader could give that "actual code details" to the Container along with the IRuntimeFactory. It could then be exposed to the Host along with the one from the Quorum value, giving the Host enough information to make decisions about upgrading the code details in the quorum or not.

Currently the thought is that the value stored in the ContainerContext should be the one returned by the Code Loader (if there is one).

It could even be the case that the Container auto-proposes the new code to the quorum if it's later.

**Comment by arinwt** [comment]
Examples where code details might differ from the quroum:
- quorum value contains a semver range like "^1.2.3" and loads "1.2.5".
- quorum value contains a data schema version for sliding window like { app: "5", data: "2" } and loads { app: "7", data: "2" }
- quorum value contains a placeholder for new documents (related to #5011)

**Comment by alpaix** [comment]
Resolved with #6394
