### ISSUE TITLE
Encapsulate waiting for write connection in Container.proposeCodeDetails

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#5014]
Related to #1539.

It might be nice if proposeCodeDetails waited for write connection before proposing. It needs to run the Code Loader compare with the quorum value at that point in time anyway.

It could also try to consolidate handling race conditions with proposing code. It should probably pull code directly from UpgradeManager. Or maybe we can just use UpgradeManager?

**Comment by vladsud** [comment]
Is this same as https://github.com/microsoft/FluidFramework/issues/1539 ?

**Comment by arinwt** [comment]
> Is this same as https://github.com/microsoft/FluidFramework/issues/1539 ?

I think so. I think that issue is a more robust solution, but this issue is just a part of the problem.
