### ISSUE TITLE
Audience doesn't have the updated current user info after it switches to write mode

### ISSUE THREAD

**Issue by cristighr1995** [microsoft/FluidFramework#5023]
## Describe the bug
The audience from the local server used in demo-host is not correctly updated and doesn't contain the current user information after switching from read to write mode.

The issue here looks like it comes from the local-driver; when the current user switches to 'write' mode, it seems that is inserted into a duplicate audience object and is not the one exposed through the container. Tested with Navin a quick fix using this [package](https://offnet.visualstudio.com/officenet/_packaging?_a=package&feed=prague&package=%40fluidframework-test%2Flocal-test-driver&version=0.1.0&protocolType=Npm) and it seems to work fine.

### To Reproduce
Steps to reproduce the behavior: in order to repro I used demo-host app from bohemia.
1. Insert a component.
2. Attach the component.
3. Write something (so that the client switches to 'write' mode).
4. Insert/Load the same component again.

### Expected behavior
I would expect that the UI would reflect the second coauthor and remove the Last Edited UI from the component ux.

**Comment by cristighr1995** [comment]
@agarwal-navin it seems that I am unable to assign this bug to you

**Comment by agarwal-navin** [comment]
Thanks Cristian. I assigned it to myself.
