### ISSUE TITLE
Enable Real Service Test pipeline to run regularly

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5044]
Pretty simple - just add some trigger to https://github.com/microsoft/FluidFramework/blob/main/tools/pipelines/test-real-service.yml, either after each checkin, or nightly, or whatever.

Also need to review:
- Default value for `poolBuild`
- Default test profile for CI, to avoid hitting ODSP throttling limits

**Comment by anthony-murphy** [comment]
@markfields  I think this is done. is there anything i'm missing? if not, feel free to close after you read this message :)
