### ISSUE TITLE
Refactor DataStoreRuntime and ChannelContexts for testability

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#5057]
We don't have unit tests for data store runtime and channel contexts. We need unit tests for these layers to check things like:
1. Data store runtime can be created and initialized.
2. Data store runtime can create channel contexts and provide correct initialization data.
3. Data store runtime can summarize and generate GC data correctly.
4. Channel contexts can initialize correctly.
5. Channel contexts can summarize and generate GC data correctly.

Once we have these basic tests, we can add more coverage. This will also ensure that adding new APIs / update existing APIs does not break these layers.

**Comment by markfields** [comment]
@agarwal-navin did you do some work here recently? Any PRs to mention here for future reference?

**Comment by agarwal-navin** [comment]
#5686 - This refactored DataStoreRuntime to add some basic tests.
