### ISSUE TITLE
Include sequence number for app summaries

### ISSUE THREAD

**Issue by marcmasmsft** [microsoft/FluidFramework#5060]
When client uploads the app part of the summary (channel), the sequence number in the request payload is not populated to reflect the ref sequence number of the summary. This would be great to have on the server.

**Comment by curtisman** [comment]
@marcmasmsft doesn't the `Summarize` op includes the referenceSequenceNumber?

**Comment by marcmasmsft** [comment]
> @marcmasmsft doesn't the `Summarize` op includes the `referenceSequenceNumber`? Is there other part of the server that needs to know?



> @marcmasmsft doesn't the `Summarize` op includes the `referenceSequenceNumber`? Is there other part of the server that needs to know?

the actual app tree/ snapshot sent to the server does not contain the sequence number; the summarize op sent to PUSH does.

**Comment by curtisman** [comment]
Can you elaborate how this number would be use?  For correctness or for debug/tracking purpose?
Does the summary upload server want to look at it to do verification, (which if we assume the server don't want to unpack and parse the app tree, it will be a protocol level information?)

@vladsud and @tanviraumi for comment as well.

**Comment by tanviraumi** [comment]
We should already have it in ".protocol/attributes/sequenceNumber" field. Scribe calculates the state up to the "ref seq" field and also includes the number in "attributes" node

**Comment by marcmasmsft** [comment]
The system knows about it but on the request that's sent to SPO, the sequence number property in the POST snapshot call is not populated with the reference sequence number, it's always 1. In the call coming from PUSH the field is properly populated.

**Comment by marcmasmsft** [comment]
We'll use it for better telemetry and to make decisions on which app summary to discard in case there are multiple summaries waiting to be committed.

**Comment by tanviraumi** [comment]
I am guessing it should be possible in the driver layer. But @vladsud will have more insight.
