### ISSUE TITLE
[Sourceless Iframe] Support Original Container from loader.

### ISSUE THREAD

**Issue by Czhang0727** [microsoft/FluidFramework#5083]
The major property we are interested is "readonlyPermissions". we need `readonlyPermissions` property returned instead of undefined at init status.  Also related callback is not reliable.

Side request need to verify: In Sourceless Iframe, seems there is no need to use "External Container" any more. We would prefer to have the original Container under sourceless IFrame.
Refer to 
[Discuss Thread](https://teams.microsoft.com/l/message/19:24e2f83fd3be4313b63b221b6d634e98@thread.skype/1606938831887?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1606938831887&teamName=FFX%20(Fluid%20Framework%20and%20Experiences)&channelName=Teams%20Ch1&createdTime=1606938831887)

Task 4692400: Change LoadedInfo to return regular container instead of ExternalContainer

For more Details

**Comment by marco-ms** [comment]
The main issue is readonly, readonlyPermissions are always undefined also for read only files. Plus readonly callback never fires, host doesn't seem aware when a component is in read only mode.
Tested both on sourceless and regular iframes.

**Comment by vladsud** [comment]
This is not at fluid repo layer. We should continue to track it in Task 4692400, unless there is specific request to Fluid.
