### ISSUE TITLE
Add "op timestamp" to "messageClientIdShouldHaveLeft" error thrown in Container

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#5093]
Once we get this error, the container is closed. However, the document is not in an unreliable / corrupted state. The op that causes this can come back and fail at somewhere down the stack.
Adding "op timestamp" will give an indication of when this document was corrupted. Also, investigate and add other fields that can help debugging this issue.

**Comment by agarwal-navin** [comment]
Also related - https://github.com/microsoft/FluidFramework/issues/5095

**Comment by markfields** [comment]
@ksbrar and I may fix this up with #5095
