### ISSUE TITLE
End-to-End test should clean up between tests (as possible)

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#5098]
- At the minimum, containers should be closed after each unittest, so that the connection can be disconnected.
    - This is causing random test failures on some machines from port exhaustion for the tinylicious variant.
    - This [branch](https://github.com/curtisman/FluidFramework/tree/hack) is a hacky implement that monkey patch (most of) the loader to capture all the container and close them after each test.  It unblocks the test to able to complete on my machine.
- Even after closing, we still leak memory.  As we add more test, this can cause issue.
- With tinylicious, we don't delete the data we generate for the test, so it will accumulate in memory.
  - One option is to implement explicit file "delete" API.

**Comment by anthony-murphy** [comment]
Moving this to march, as I won't get to it this month. I'm not so worried about tinylicious, i've run the tests many times on the same instance over weeklong periods and never hit issue. trying to clean up contianer seems reasonable

**Comment by curtisman** [comment]
It is blocking me from running our unit test.   (I assume I am not the only one)

Any object in for me to check in what I have in my [branch](https://github.com/curtisman/FluidFramework/tree/hack)?

**Comment by anthony-murphy** [comment]
I'm just confused what changed. We are running more tests in tinylicious mode, but its now a seperate process. we never cleaned up containers before in local or tinylicious mode. regardless, i'm ok with the change you have
