### ISSUE TITLE
Should summarizer summarize faster after image paste/upload?

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5102]
Can we change summarization frequency logic to not just count number of ops, but also count uploaded blobs?

With images being separate blobs, and summarize taking their "normal" speed, it's pretty obvious to the user our multi-stage loading strategy.
If summary did not catch new image, then refreshing document does not see image for quite a while (there is huge delay that includes connection to ordering service and then downloading image), and visually it's much more obvious than missing text as it's "big" in terms of real estate, so it's very obvious to the user.
If image is part of summary, then we immediately hit storage on boot, and it is prioritized over connection to web socket, and very likely served from cache, so the lag is much smaller (if visible at all).

Some delay is warranted (as user may delete image right away), but I think if user keeps typing, we do not want to wait a minute after image insert. 15 seconds of idle time is a bit too long IMHO.

**Comment by anthony-murphy** [comment]
i don't think this will fit in may, moving to june unless there is strong need for this. also, i think some of the improvement @arinwt is working on will be needed for this anyway

**Comment by vladsud** [comment]
@arinwt - can you please glance? Is there anything cheap we can do here?
Otherwise I'll keep it in "Future" milestone

**Comment by vladsud** [comment]
Punting - we have not heard requests to do so, and it looks like experiences built on top of FF work pretty well in this regard (with latest improvements in Scriptor that just landed)
