### ISSUE TITLE
ODSP driver: blob read API returns cachable result only if epoch is in query params

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5106]
If epoch is in headers, then not only this cases OPTIONS call, but SPO will not mark response as cachable, and we will pay the cost of fetching same immutable blob over and over.

As result we should generate an error telemetry event when that happens.

**Comment by vladsud** [comment]
We need to confirm that with Marcelo (i.e. that description is actually accurate)

**Comment by jatgarg** [comment]
The options call will be removed when we will move to POST calls for these apis. Related to this issue:
https://github.com/microsoft/FluidFramework/issues/4811

For this we just want to log the telemetry error event.

**Comment by vladsud** [comment]
Note - we should double check the claim I put here with Marcelo. He mentioned somewhere that "external" blobs might get unique IDs, and if so - epoch becomes irrelevant (as IDs can't be reused, even if file is restored - they are unique).
Not true for summary blobs though.

**Comment by jatgarg** [comment]
Yes, I talked to him. Attachment blobs are always cacheable as their id is function of their content. For summary blobs, the id is unique per document and per epoch. So In case we provide the epoch as query param, the result will be marked as cachable. For headers it will be not.

**Comment by vladsud** [comment]
Does it mean that SPO will mark ALL request (including ones with headers/OPTIONS) for external blobs as cachable, but will mark request for summary blobs as cachable if headers/OPTIONS is not used?

I believe POST calls are not cachable, i.e. they always hit network, right?
So we have to have both GET and POST. Former - for cases that are cachable, like blob read with epoch on query param.
GET + options call is likely preferred over POST if the request is catchable for sure, as options and/or get can be cached.
Note - we do not know if ID is for summary blob or external blob in driver, so we have to error on safety. At the same time we know that most blobs (today - 100%, but that will change) will be external blobs, so if we know that all such request are cachable, then we would rather stick with GET.

**Comment by jatgarg** [comment]
"Does it mean that SPO will mark ALL request (including ones with headers/OPTIONS) for external blobs as cachable, but will mark request for summary blobs as cachable if headers/OPTIONS is not used?" - Yes
