### ISSUE TITLE
Add additional metadata to container child logger

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5121]
"We might actually want to just add a bunch of this information directly to the logger at the container level, so these field are always available, but maybe it's overkill. or maybe only add them for errors"

_Originally posted by @anthony-murphy in https://github.com/microsoft/FluidFramework/pull/5119#r574193876_

**Comment by curtisman** [comment]
Please be selective and think about the data size if we add it to every telemetry event..

**Comment by markfields** [comment]
Closing in favor of more scenario-focused issue https://github.com/microsoft/FluidFramework/issues/5295
