### ISSUE TITLE
Blob upload should be repeated if we are unable to issue BlobAttach message in reasonable amount of time.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5123]
If blob was uploaded to storage, but we were not able to issue and see the ack for ContainerMessageType.BlobAttach within 36 hours, then blob has to be reuploaded again, as SPO already deleted it.
Referencing it in ops/snapshot will mean we have broken blob reference, which is not good.

Note that ideally this policy (36 hours) should be communicated from SPO.
I'm proposing that response for blob upload return that value in the header.
Note that we should start measuring time from the start of upload that succeeded. I.e. if we are offline, the timer does not start until we actually online and reached SPO with first byte (or rather - just a moment before that).

Also this is driver specific implementation (how it's returned in response), we should change upload blob API on the driver to return this info in driver-agnostic way.

**Comment by vladsud** [comment]
One thing to add: We could not issue ContainerMessageType.BlobAttach right away after image upload, if image handle is not being attached. Attachment could happen much later in time.

This creates a problem, as image might be deleted by storage (if this op does not happen soon enough).
I believe we should change design and issue it right away (and do tracking that is described above), but rely on https://github.com/microsoft/FluidFramework/issues/5161 to cleanup unreferenced blobs after some time (which is much longer,  i.e. likely to be 2 weeks or so and we will ensure GC is safe, for example, we likely to chose design where every client is forced to reload every 2 weeks to ensure that no clients know anything about blobs that are unreferenced and thus they can be collected safely after 2 weeks + 1 day timeframe).

**Comment by markfields** [comment]
@vladsud - FYI this is falling to April. And from your comments, I can't tell - should this be marked as design-required, or is this work clear-cut at this point?

**Comment by markfields** [comment]
@vladsud, @curtisman - updating milestone to Next...

**Comment by vladsud** [comment]
Assigning to June per discussion with Wes

**Comment by wes-carlson** [comment]
> I believe we should change design and issue it right away (and do tracking that is described above), but rely on #5161 to cleanup unreferenced blobs after some time (which is much longer, i.e. likely to be 2 weeks or so and we will ensure GC is safe, for example, we likely to chose design where every client is forced to reload every 2 weeks to ensure that no clients know anything about blobs that are unreferenced and thus they can be collected safely after 2 weeks + 1 day timeframe).

What is the point of the BlobAttach op in this case? Why not just keep all uploaded blobs for 2 weeks and not send the op? Wouldn't the result be the same as sending it immediately?
