### ISSUE TITLE
getRouterliciousContainer can't be imported from @fluidframework/get-tinylicious-container

### ISSUE THREAD

**Issue by Flavyoo** [microsoft/FluidFramework#5148]
## Describe the bug

A `getRouterliciousContainer` function is defined in the the [experimental package](https://github1s.com/microsoft/FluidFramework/blob/main/experimental/framework/get-container/src/getRouterliciousContainer.ts), but the contents of the file is not exported in the index.ts file. Is this method intended to not be publicly available yet or should it be exported?

### To Reproduce
1. install `@fluidframework/get-tinylicious-container`
2. Add `import { getRouterliciousContainer } from '@fluidframework/get-tinylicious-container'` to top of the file;
3. See logs showing getRouterliciousContainer is not defined.

### Expected behavior

The function should be available when imported.

**Comment by tylerbutler** [comment]
@ChumpChief @skylerjokiel @SamBroner Is this part of the API refresh work?

**Comment by ChumpChief** [comment]
Yes - we're still iterating on the design and so it's not exported yet.

**Comment by Flavyoo** [comment]
Great, thanks for following up. @tylerbutler Should I close this?

**Comment by ChumpChief** [comment]
I expect we'll be moving towards better parameterization of `getContainer()` rather than exporting service-specific helper functions (see #5218), but this will serve the same purpose.
