### ISSUE TITLE
Flaky canvas test

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5156]
This test keeps failing for me on various unrelated PRs (over this week-end), and usually succeeds on first retry, occasionally needs 2-3 retries:

**canvas > canvas can be drawn upon with a computer mouse input peripheral**

Error: expect(received).toEqual(expected) // deep equality 

https://dev.azure.com/fluidframework/public/_build/results?buildId=16161&view=ms.vss-test-web.build-test-results-tab&runId=38760&resultId=100000&paneView=debug

Would be great to fix it or disable it.

**Comment by anthony-murphy** [comment]
doesn't look like this test has been touched since it was added 6mos ago:
https://github.com/microsoft/FluidFramework/blob/main/examples/data-objects/canvas/test/canvas.test.ts

@skylerjokiel looks like you added it, or maybe move it, any ideas
