### ISSUE TITLE
Add API to ODSP driver for "prefetching" snapshots in to persistent cache

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#5171]
We have some scenarios where an application hosting Fluid would like to load a snapshot into the persistent cache a few minutes before we actually would like to load a container. This would be done to take advantage of some idle network and CPU time to improve performance later on. An example would be to preload a snapshot prior to the user clicking a link that will navigate to an experience that renders a fluid component.

While this is certainly possible today by just simply loading the container, it would be wasteful. Since we don't need to load a container, we don't want to pull in all the code needed to load a container nor waste CPU cycles processing the snapshot to get a container. 

The feature request here would be to add support for a lightweight API that uses the minimal code and CPU time to opportunistically fetch a snapshot and insert it into the persistent cache.

**Comment by vladsud** [comment]
It would be great to clarify if this is GA blocking or not. If not, we should move it out to April.

**Comment by christiango** [comment]
Not GA blocking for Ch1 for sure. May end up as GA blocking for Ch2. So should not be prioritized at the expense of anything critical for Ch 1 GA.

**Comment by jatgarg** [comment]
So for this I am thinking of adding an api on odsp document service factory which will take resolvedUrl as an argument. This resolved url will be used to attach to storage and fetch the "latest snapshot"/trees latest call and then store it in the persistent cache. @vladsud @christiango

**Comment by christiango** [comment]
That sounds reasonable, would be good to have a quick design proposal written down and run it by the expected consumers of the API. I believe the most prominent place where this would be used is to load meeting notes 5 minutes before a meeting, so we'd want to run the plan by Michael, Jade, and some teams folks. 

As an FYI Michael is taking over Fluid performance from me, so we should loop him in as well (don't have his github alias).

**Comment by vladsud** [comment]
I'd try to make it stand-alone (i.e. not using factory for actual code), such that it's possible to tree shake all the code and leave the minimal amount of code in host. Note that this code will be bundled into app, and run outside of iFrame.
I think expectation on using URL resolver is Ok here, as different host might have different URI schemas and use different resolvers, so core functionality should not care and be independent.

**Comment by jatgarg** [comment]
Created this PR so that we can discuss on the PR itself. Emailing Michael and some other people as I could not add them to the above PR.
