### ISSUE TITLE
Add a Data Integrity metric to daily reliability report

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5179]
We're continuing to get a steady influx of issues, and I'd like to get a query going/growing to easily track burn up/down of the different errors we're seeing.

One approach is to add `errorType` to the queries, now that we have some data integrity related error types (see #4663 and related PRs)

**Comment by markfields** [comment]
@ksbrar - Let's work together on this one since you're OCE and dealing with this stuff anyway, and very familiar with the report.

**Comment by markfields** [comment]
Probably going to close this one.  Need to follow-up on progress on #4663 which I think is also ready to close based on recent PRs from @jcmoore

**Comment by ksbrar** [comment]
Added sections for corruptions and processing errors (current extent of data integrity tracking) to the reliability report.
