### ISSUE TITLE
Testing for @fluid-example packages

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#521]
Add End to end testing with Jest and Puppeteer.

Use clicker/dice-roller as an example.

Here are a list of remaining packages that doesn't have test.
- [ ] @fluid-example/agent-scheduler
- [ ] @fluid-example/badge
- [ ] @fluid-example/client-ui 
- [ ] @fluid-example/codemirror
- [ ] @fluid-example/draft-js
- [ ] @fluid-example/image-collection 
- [ ] @fluid-example/image-gallery
- [ ] @fluid-example/key-value-cache
- [ ] @fluid-example/math
- [ ] @fluid-example/monaco
- [ ] @fluid-example/musica
- [ ] @fluid-example/progress-bars
- [ ] @fluid-example/prosemirror
- [ ] @fluid-example/scribe
- [ ] @fluid-example/search-menu
- [ ] @fluid-example/simple-fluidobject-embed
- [ ] @fluid-example/smde
- [ ] @fluid-example/sudoku
- [ ] @fluid-example/video-players
- [ ] @fluid-example/webflow

**Comment by vladsud** [comment]
Closing, as this issue seems like served its purpose.
