### ISSUE TITLE
Support esbuild 

### ISSUE THREAD

**Issue by mohamedmansour** [microsoft/FluidFramework#5214]
Esbuild is the fastest and most modern JS/TS build system out there, currently FluidFramework makes use of legacy libraries causing build breaks in these modern tools:

```
node_modules/jws/lib/sign-stream.js:5:21: error: Could not resolve "stream"
var Stream = require('stream');
                     ~~~~~~~~
node_modules/jws/lib/verify-stream.js:5:21: error: Could not resolve "stream"
var Stream = require('stream');
                     ~~~~~~~~
node_modules/jsrsasign/lib/jsrsasign.js:237:6252: warning: Suspicious use of the "!" operator inside the "instanceof" operator
```
Would be super awesome if we can support esbuild! It would make development a lot faster than using webpack.

**Comment by curtisman** [comment]
That particular dependency comes from `jsonwebtoken` -> `jws` -> `stream`
And `stream` is a `node` library that is polyfill by webpack4 automatically.   We have an work item #366 and #4843 to figure out how to support webpack5 which doesn't have automatic polyfill, which probably will fix esbuild as well.

In the mean time,  I wonder whether installing `stream` polyfill is enough to work thru these error for now?

**Comment by tylerbutler** [comment]
@mohamedmansour I have successfully built projects using Fluid libraries using esbuild. Have you seen cases where it doesn't work? I wouldn't expect esbuild to be able to build our _repo_ at the moment, but I haven't run into cases where Fluid packages trip it up. If you have a repro I'd be interested to take a look.

**Comment by mohamedmansour** [comment]
Hey @tylerbutler I am using @SamBroner routerlicious-container to connect to routerlicious, and it uses `import jwt from 'jsonwebtoken'`

**Comment by vladsud** [comment]
There seems to be related PR from Tyler: https://github.com/microsoft/FluidFramework/pull/5684
