### ISSUE TITLE
Spawn summarizer when elected client is not summarizing

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#5222]
This is a draft proposal for improving summarizer resiliency in cases where either elected client fails to spawn summarizer client, or spawned summarizer client fails to summarize for too long. Usually clients will get booted from the quorum if they sit too long, but there are exceptions: recently we have seen issues with clients sticking around in the quorum even after they have disconnected. There can always be problems with a specific client preventing it from summarizing as well.

All clients already have a summarizer running which tracks summary ops. It might be good to have this raise some event if enough ops/time pass without a summary attempt (ack?). If this heuristic is deterministic/consistent enough, then clients could unanimously elect a new summarizer client. I think the approach for this can be to pick off clients 1-by-1 from oldest to newest in the quorum.

Ideally it would be aware of which clients are submitting the summaries, so it can handle the case where the originally elected summarizer comes back online.

This requires some current checks to be bypassed/modified:
- We only allow one summarizer client in the quorum at a time. However, if the summarizer client connected isn't summarizing, we need to bypass this check. I think this goes hand-in-hand with specifically marking clients as "bad", so we only allow one non-bad summarizer client in quorum at once.
- It would be more robust if other clients could know who the parent clients are of the summarizer clients. This way, all clients can determine "bad" client pairs.

**Comment by anthony-murphy** [comment]
let's shoot to get a design for march. we can then figure out when to schedule

**Comment by ChumpChief** [comment]
Would love if this is more than just a summarizer election strategy -- e.g. if it actually got the quorum members back into a correct state.

**Comment by arinwt** [comment]
I think they are 2 separate things, with the non-intersecting part being a client is connected and functional for the most part, but cannot summarize for some reason.

I do think that the quorum resolving itself is just as, if not more important though.

**Comment by anthony-murphy** [comment]
The quorum can only get into a bad state due to server side data corruption, and there isn't much the client can do in that state, as allowing clients to boot other clients from the quorum is a security nightmare. this proposal will help in that a new client will summarize, which will get a new quorum stamped by the server, this should fix new clients
