### ISSUE TITLE
Routerlicious building instructions link to a 403

### ISSUE THREAD

**Issue by iamalexmang** [microsoft/FluidFramework#5234]
The README.md links to an Azure Web App which isn't running. Specifically, this link: https://praguedocs.azurewebsites.net/contributing/building-documentation.html

This shows up under "Documentation": _If you want to build API documentation locally, see Building Documentation._

**Comment by curtisman** [comment]
@tylerbutler couldn't find the html file.  Is that old content that doesn't exist any more or it is relocated somewhere else.
