### ISSUE TITLE
buildSnapshotTree and storages using them do unnecessary base64 encoding / decoding

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5263]
Basically it boils down to ChannelStorageService & BlobCacheStorageService having extra blobs as ArrayBuffers, not as base64 encoded strings. This pushes the problem up the stack, where we get these base64 strings from buildSnapshotTree (see flattenCore), which converts input (utf8 or base64) to base64. Instead, it should return arrays and let callers deal with it
 extra blobs should be ArrayBuffers, not base64 encoded strings.

There are other usages affected by it, but they all can and should be converted to using arrays, not base64 encoded strings.

**Comment by chensixx** [comment]
oops i thought this was still in March milestone so i worked on it before my other issues

**Comment by vladsud** [comment]
Well, given that you have it ready, can you please get it in, despite not being marked as March? It's true that it likely has lower priority, but it's great change that we want, sitting on it will just add work for you (extra merges to care)

**Comment by chensixx** [comment]
yeah i will merge it soon! i'm just surprised. i didn't realize it was moved to april 😅
