### ISSUE TITLE
Handle Summarization Failures

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5279]
### Differential Summary Issues
In addition to the below bugs, there is also the problem of unbounded differential summaries. We saw lots of user feedback that perceived performance was bad because there was lots of op replay.
- #4676
- #4296

### To many outstanding ops
Odsp will eventually block a client from sending ops, when the total number of ops passes some threshold (1000). Blocking the main client from sending ops can result in the summarizer not spawning. 
- #4068

### Summarizer Disconnect
The below issue lists several cases where summarization can fall behind in such a way that it is almost impossible to catch up. We should explicitly account for these cases.
- #4069

## Proposals

Differential summaries were added as a way for the container to continue to make progress in the presence of summary failures. However, the current implementation goes too far in the direction of making progress and doesn't adequately incentivize the container developer to fix the issue. The best solution here would proportionally degrade the user experience, provide a means for a user to unblock themselves, and incentivize developers to fix underlying issues. 

Differential summaries are primarily a mitigation for data store summarization problems, but it's also possible for the container as a whole to face similar issues. Currently, we do nothing in this case, and the container will simply carry on until it is blocked, and potentially stuck. Just like differential summaries we should proportionally degrade the user experience, provide a means for a user to unblock themselves, and incentivize developers to fix underlying issues. 

### Proportionally degrade the user experience
In all these cases I believe the best course of action is to make the affected context readonly until the problem can be resolved. Doing this will block additional changes which prevents any additional data loss, but still provides the user with access to their existing content. While at a high level this approach is easy to understand there is significant complexity in making it work in practice which I will expand on below.

### Provide a means for a user to unblock themselves
We are limited in what we can do here in the presence of a code defect in the data store or container which is preventing summaries.

**Comment by tylerbutler** [comment]
Moving to June since we're hitting higher-pri issues at the moment.
