### ISSUE TITLE
Ignore stuck client for summarization purposes

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5283]
We have seen multiple documents being broken due to client sticking in quorum forever.
This was PUSH bug, but it causes summaries not to run, and that completely breaks the document.
For example, Chapter 2 document takes tens of minutes to catch up.

I think summarization process need to have some safety net here. Something stupid and cheap, like if no summaries have been observed from a oldest client in quorum, we somehow mark it dead and start ignoring in all our calculus, unless any op shows up from this client.

I'm putting it to may, given how critical this area to the health of Fluid.
While particular PUSH bug is fixed, we should assume bugs like that happen, and clients might get into bad state (due to bugs on our side) where these things would pop up.
Even if we do nothing in short term, we need to have telemetry to start yelling at us when that happens!

**Comment by arinwt** [comment]
@vladsud - I recently created an issue to track this #5222

**Comment by anthony-murphy** [comment]
@arinwt please move anything new here to #5222 and lets close this a dup.
