### ISSUE TITLE
Last edited is very inefficient

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5285]
Looking at Chapter 2 document, and why it's so large (in terms of ops), this thing stands up:

op/op/set/Plain ([e1497f38-ef07-4245-99b0-3953b05c5576]/14338fcd-e768-4c8e-b65e-ff0edc3c2725) 	233,442 	142,087,000

That's 142Mb of data in 233K ops!
That's 40% of the size of the file!
And 36% in number of ops!

Here is header content of that map (name and email removed):
```
{
  "blobs": [],
  "content": {
    "lastEditDetailsKey": {
      "type": "Plain",
      "value": {
        "user": {
          "id": "_Some email_",
          "name": "_name_",
          "email": "_some email_"
        },
        "timestamp": 1612139086581
      }
    }
  }
}
```
This is not how we envisioned last edited :(
And this is really not good in terms of perf, especially in terms of catching up perf - this generates a lot of ops that we have to download when using cached snapshots.

I'd assume this is because the feature we built (with summarizing dds) is not used, and instead we are sending ops.
This needs to be revisited ASAP, given impact.

**Comment by vladsud** [comment]
ADO item tracking it: https://office.visualstudio.com/OC/_workitems/edit/4906233

**Comment by agarwal-navin** [comment]
I have summarized the solution that we had initially proposed and I still think it is the more efficient way to implement last edited. The concern we had with using a regular DDS (such as SharedMap) was that it would generate too many extra ops in the system. From the description in this issue, it looks like that's the main problem.

Proposed solution
- Use SharedSummaryBlock to store last edited information. SharedSummaryBlock does not generate ops and adds its data to summaries only.
- Always load the data store containing SharedSummaryBlock when the Container loads.
- Use `LastEditedTrackerDataObject` from the framework or extend it if you need custom behavior.
- The concern at the time was always having to always load the last edited component (along with Scriptor which was the default component). With the office fluid container now using a root component, it should be more feasible. Root component can always be loaded which loads the last edited component

**Comment by agarwal-navin** [comment]
This has been fixed by using SharedSummaryBlock instead of SharedMap to implement last edited.
