### ISSUE TITLE
Chapter 2 document has too many summaries

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5287]
I'm looking holistically at the problem of slow catch up.
I.e. loading from previously cached summary that might be a day old and spending substantial time to catch up.
There are various independent bugs opened based on size of the file / ops, this is one of them.

File has 633K ops, Last summary is at op 334K, i.e. half of ops are not summarized (due to bug with PUSH and stuck client in quorum).

There are almost 9K summary ops (and I'd assume as many summaryAk), which creates quite a few ops relative to total payload.
I.e. roughly 5% of payload is summary-related ops.
That means there are plenty of cases where we summarize less than 20 ops, and likely enough cases where we summarize less than 10 ops (including previous 2 summary related ops).

Can we be more efficient here?
Like have different time limits for when you have 10 vs. 100 un-summarized ops?
Can we find something simple that improves it 2x?

More analyzes is welcome! This issue is opened based on high-level observations.

**Comment by arinwt** [comment]
I made a change a while back to support intervals for the configuration. I think that would have covered this. Based on the outstanding ops, it would choose different time configurations (so the current "maxOps" would map to a zero time).

**Comment by arinwt** [comment]
Would a solution like this be suitable? #60

**Comment by vladsud** [comment]
I think so. I'm not sure I buy into (general) direction of server controlling these things, I feel it's very payload specific.
I.e. if I'm building a game, my numbers would be quite different, vs. if I'm building a document container.

**Comment by arinwt** [comment]
Related to this change: idle timer starts too frequently. It shouldn't start if there are no "data" ops since last summary, but sometimes it appears to be.
