### ISSUE TITLE
SharedTree: Perf quickly degrades when disconnected / oscillates when connected

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#5293]
## Describe the bug
When running 'bubblebench' in a disconnected state perf quickly degrades until it is unable to sustain 1 bubble @ 30 fps.

### To Reproduce
> git checkout main && git pull
> cd experimental/examples/bubblebench
> npm run start:tinylicious

(Ignore warning that tinylicious isn't running...  we're intentionally running in a disconnected state.)

### Expected behavior
DDS performance should be stable / not degrade over time. 

### More Info
Per @taylorsw04 - symptoms indicate a known issue where the SharedTree constructs the current view each frame by rewinding to a cached view of the last ACKed edit and applying the new ops.  When disconnected, this leads to exponential work where each rendered frame grows the list of local edits that need to be applied.

In a connected state, the benchmark oscillates between ~8-15 bubbles as the window of unACKed edits grows/shrinks.

### Logs
In the profiler I see that the first call to 'currentView' on each frame performs thousands of B-Tree updates, despite there being only 2 'setPayload' edits emitted per frame.  In the debugger, I see the 'log.length' increasing by 1 each frame while the 'startRevision' in `getSnapshotInSession` stays constant.

**Comment by CraigMacomber** [comment]
Without looking into this in detail, my inital assumption is you are hitting an issue with CachingLogViewer (in LogViewer.ts).

It has two kinds of caching mist recent revision, and caching revisions which have been sequenced.

This means that adding new local edits is O(local edits): adding a new one invalidates the cached previous head, and the next request reapplies all local edits.

This is as designed (my bad design simply didn't handle lots of local edits), so I consider it a design bug/feature request.

The whole 'lastHeadSnapshot' cache is really limited. We really need an actually decent caching system for local edit application, and it shouldn't be hard to do (ex: replace lastHeadSnapshot with lastComputedHeadSnapshot and make it remember which revision it was at and only invalidate on new remote sequenced edits)

**Comment by taylorsw04** [comment]
@CraigMacomber just seeing this, I've confirmed that was indeed the issue. I'll whip up a fix. This should improve perf for both offline scenarios and online scenarios with rapid editing.
