### ISSUE TITLE
Consistent logging of op-related properties to ease debugging via telemetry

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5295]
Most errors coming from the runtime should log the current sequence number and other related properties that will help us rebuild a timeline when debugging from telemetry.  We can consider stamping these on non-error logs too but that may be too heavy.

These properties are logged here and there, sometimes with varying names, etc, so consolidating names and ensuring they're logged pervasively will make a big difference.

Let's document these and consider it almost like an API design that we somewhat "lock down".  And put under test via mock logger?

**Comment by markfields** [comment]
@anthony-murphy - Please add additional details if you have specifics in mind at this point.

**Comment by markfields** [comment]
Message Timestamp will be important here to keep track of when an issue was introduced in a particular doc

**Comment by anthony-murphy** [comment]
i also want the summary handle of the summary we've loaded from
