### ISSUE TITLE
Query Real Service Test data in daily report

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5296]
This month we at Msft are beginning to collect logs from our CI pipeline, so we can do release-readiness analysis based on that synthetic traffic.  We have a daily report we are using to track some core metrics and we should be including this data set as a source for that report.

**Comment by chensixx** [comment]
I have 2 PRs in ADO that updated the daily report query: one is to include all errors in 3 databases, not just the error table; the other is a time chart query for the real service test databases
