### ISSUE TITLE
Properly set sessionId and other correlating info to logs from test runs

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5297]
Right now the internal logger for our CI test runs uses one sessionId per node process, and doesn't do any logging to help correlate logs back to the test runs themselves in the pipeline.

This work needs to cover both e2e tests and the stress test.

**Comment by anthony-murphy** [comment]
dupe of #5295

**Comment by markfields** [comment]
@anthony-murphy - not sure why this is a dupe of that one... did you mean a different issue?

**Comment by markfields** [comment]
This is distinct from the issue mentioned above.  Some specifics here:
* Log the pipeline run id
* Consider focusing on LoaderId as primary key rather than Session_Id since its interpretation in the code is clearer
* Consider reusing existing hostName or hostScenario fields if applicable to concepts here (e.g. Orchestrator v. Runner, Runner ID, e2e test case name)
* Check if runtimeVersion and loaderVersion include the patch/prerelease version numbers in them - that would be great too

Primary goal at first is to be able to go back and forth with ease between logs and pipeline runs for investigation etc.

**Comment by markfields** [comment]
Assigning primarily to Si for March, and myself in case we break this down into multiple items.

**Comment by markfields** [comment]
This has been broken down into specific work items, closing.  cc @anthony-murphy and @chensixx  as FYI
