### ISSUE TITLE
Script to delete old test collateral on SharePoint

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5303]

**Comment by markfields** [comment]
We may just want to take a step back and give test tenant management some more thought in general.  I think @curtisman is thinking in this space?

**Comment by curtisman** [comment]
It seems like a good idea to have if we have a long leave tenant for testing?

**Comment by markfields** [comment]
Sure, but moving to Next for now. Maybe this will make sense/fit for April, but I feel that manual cleanup is acceptable for the time being, so I'm not going to commit to it until April plan is more set (working on it now).

**Comment by curtisman** [comment]
We haven't hit issue with running out of quota yet, and we need to refresh tenant once in a while.  We will reactivate when there is a need.
