### ISSUE TITLE
Update assert in common-utils to require message param

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5314]
Follow-on to #4439 

I think I also want to add an optional `errorType` string, so we can mark up asserts in shared service/client code as indicating a data integrity concern.

**Comment by markfields** [comment]
@anthony-murphy - Any concerns with adding optional `errorType` parameter to our `assert` API? We can tack it on the Error object we throw, which will get picked up by code like `CreateContainerError`

**Comment by curtisman** [comment]
If we are going to change the signature, may be we should name it something different (`fluid_assert`?) to separate it with the other assert library.

**Comment by anthony-murphy** [comment]
My concern with errorType is i'd like to keep the number of distinct error types small. I worry taking string on assert will leads to lots of differ error types

**Comment by markfields** [comment]
That's a good perspective.  Then how about we hardcode the `errorType` property on the `Error` we throw to be `assert`?

**Comment by anthony-murphy** [comment]
seems fine if it's useful for differentiation
