### ISSUE TITLE
Allow Summary Client to Reconnect

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5317]
Currently the summary client sets auto reconnect to false:
https://github.com/anthony-murphy/FluidFramework-1/blob/0076d7e0c23fffcf5f6df042a1f49a6838c1b111/packages/runtime/container-runtime/src/summaryManager.ts#L432

This can create issue where the client is far behind and fails to get caught up. Currently I'm not seeing the client being respawned, and even if it we're respawned it would also likely fail to reach connected with how far behind the client is

**Comment by anthony-murphy** [comment]
discussion here #5313

**Comment by kenluck2001** [comment]
I have done some investigations on how to reconnect or respawn in late clients.
Here is my suggested plan to reconnect in `packages\runtime\container-runtime\src\summaryManager.ts`

`        const shouldReconnect = SummarizerClientElection.isClientEligible(client);
        // TODO eventually we may wish to spawn an execution context from which to run this
        const request: IRequest = {
            headers: {
                [LoaderHeader.cache]: false,
                [LoaderHeader.clientDetails]: {
                    capabilities: { interactive: false },
                    type: summarizerClientType,
                },
                [DriverHeader.summarizingClient]: true,
                [LoaderHeader.reconnect]: shouldReconnect,
                [LoaderHeader.sequenceNumber]: this.context.deltaManager.lastSequenceNumber,
            },
            url: "/_summarizer",
        };`

However, I have a problem as I am unable to get the variable named "client" of type "ITrackedClient"
`      const shouldReconnect = SummarizerClientElection.isClientEligible(client);`

Let me know of possible suggestions on the fix.

**Comment by anthony-murphy** [comment]
This may not be an issue anymore, as there has been work to add things like op caching, so it should be possible for the summarizer to reliably catch up from the cached ops of the main container.

I think the crux of the issue here is the relationship between the main container, the summary container, and other containers is based on the clientIds of these clients. On reconnect clients will always get a new and random client id. In the summarizer case this breaks lots of assumptions.
