### ISSUE TITLE
Redact error message in responseToException

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5326]
Please see https://github.com/microsoft/FluidFramework/pull/5215
and responseToException() that adds URI to message (and stack) that could result in PII info leaking to telemetry if we are running in container with 3rd party code.

The goal here should be holistic approach - any error could container PII. So likely case like that should be automatically covered by not collecting message / stack unless error happens in internal (dogfood) rings.
If we want to address this particular case (without addressing more generic problem), we could drop URI if we are running in container with 3rd party code.
Dropping URI all the time will reduce our ability to diagnose problems.

Related issuds:
https://github.com/microsoft/FluidFramework/issues/4908
https://github.com/microsoft/FluidFramework/issues/1920

**Comment by curtisman** [comment]
I don't think this is limited 3rd party as well, as any one can add query param (that contains PII) in the URI without affecting functionality.

**Comment by vladsud** [comment]
I'll remove URI for now via https://github.com/microsoft/FluidFramework/pull/5327, but it would be great to articular what is safe and in what rings we could collect at least some info. I.e. as Curtis pointed pointed out, path (no query params) is likely Ok for 1st party in general, full path is likely Ok for internal rings in North America (but not in Europe due to differences in privacy laws around using corporate resources).

I think the key in all of that - have proper mark up for central entity (logging implementation in host) to have enough data to decide to strip or leave specific fields intact.

**Comment by markfields** [comment]
@vladsud I didn't get to wrap this up before going on leave. it sounds like the URL is actually still logged, from your PR comments, so diagnostics in the short term is unblocked while there's no specific privacy issue since we don't have 3P code loaded in 1P experiences. I'll address this when I'm back in June, unless you or someone else finds it urgent and does something this month.
