### ISSUE TITLE
SharedText Jest tests are unreliable

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5331]
## Describe the bug
See test failure in [this PR check](https://dev.azure.com/fluidframework/public/_build/results?buildId=17825&view=ms.vss-test-web.build-test-results-tab&runId=87528&resultId=100001&paneView=debug) on an unrelated change to the SharedText example dataObject.  This is the second time I've seen this pop up on a PR check.

### To Reproduce
It's intermittent, but I suppose running the client build pipeline a bunch of times should expose it - hopefully it can be repro'd running the tests locally too but I haven't tried.

### Expected behavior
Test should always pass.

### Logs
See ADO link above.

**Comment by curtisman** [comment]
It may be a puppeteer issue: https://github.com/puppeteer/puppeteer/issues/1648

**Comment by markfields** [comment]
Good catch Curtis.  There's a workaround mentioned in there:  https://github.com/puppeteer/puppeteer/issues/1648#issuecomment-617877021

**Comment by curtisman** [comment]
I believe shared text requires keystrokes.

**Comment by markfields** [comment]
FYI, just hit this again, on pretty recent bits (`main` on `4f9f63ab19661ba2` from last Thursday).  https://dev.azure.com/fluidframework/public/_build/results?buildId=19512&view=ms.vss-test-web.build-test-results-tab&runId=138238&resultId=100001&paneView=debug

**Comment by curtisman** [comment]
The last failure in main is Mar 11, before the latest fix (Mar 15).  
Consider this fixed.

**Comment by markfields** [comment]
@curtisman I think it just happened again... :( 

https://dev.azure.com/fluidframework/public/_build/results?buildId=27817&view=ms.vss-test-web.build-test-results-tab&runId=406122&resultId=100001&paneView=debug

```
Error: expect(received).toEqual(expected) // deep equality

Expected: "sharedTextTest"
Received: ""
    at Object.<anonymous> (/agent/_work/1/s/examples/data-objects/shared-text/tests/sharedText.test.ts:81:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by markfields** [comment]
Hit again:
https://dev.azure.com/fluidframework/public/_build/results?buildId=30845&view=ms.vss-test-web.build-test-results-tab&runId=517400&resultId=100001&paneView=debug
