### ISSUE TITLE
SharedTree: Summary upload sizes exceed service limits

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#5350]
## Describe the bug
Bubblebench experiences periodic hangs of increasing length during summarization until the service rejects the summary upload due to length.  With two Bubblebench clients at ~30 bubbles the summary reaches the service limit within ~15 minutes.

### To Reproduce
```bash
git checkout main && git pull
cd experimental/examples/bubblebench/sharedtree
npm run start:r11s -- --env.tenantId "..." --env.tenantSecret "..." --env.fluidHost "..." --env.production
```

### Expected Behavior
Summary size is proportional to the document content, which at 30 bubbles is constant at ~2KB of data.

### More Info
The unbounded growth of the summary is due to the edit log, which is summarized as a flat list of blobs.

One fix is to replace the flat list with a tree.  A tree allows previously serialized blocks of IFluidHandle[] to be reused in subsequent summaries.  The summary itself need only contain a reference to the root IFluidHandle (plus contents of blobs that have not-yet finished uploading.)

See the SharedLog DDS prototype for an example of a virtualizable B+Tree [here](https://github.com/microsoft/FluidFramework/pull/3906/files#diff-0628f580579635084a19cd43d654c3f451c10d85950c333ef4f2ba1d3a89bcd6).

**Comment by curtisman** [comment]
The number above is for r11s.  Note that increasing the number of blobs infinitely also isn't scalable for some other services as well.
FYI @vladsud.

**Comment by DLehenbauer** [comment]
(FYI: @taylorsw04 - I believe this is known debt wrt. virtualizing the edit log.)

**Comment by taylorsw04** [comment]
Yes, there are incoming PRs that will make the accrual incremental and significantly reduce the size of the upload. Additionally, we would like to see DDSs configurable such that, by default, SharedTree wouldn't even store history--I'm chatting with @DLehenbauer about that.

**Comment by vladsud** [comment]
SPO is rather sensible to overall number of blobs in the system. So any strategy that relies on infinite growth (with user edits) is destined to fail eventually (at least with SPO), or have sub-par user experience.

That said, it would be great to get deeper understanding where r11s fails. I assume "constant at ~2KB of data" is addition per summary, right? Or something else? What kind of limit r11s is sensitive to? Reason I ask - we might have certain solutions already in place or in development that might help here

**Comment by DLehenbauer** [comment]
The summary itself is expanding at ~200kb a minute (my estimate / not measured).  @tanviraumi and company are looking at why r11s rejected the upload.  Currently they suspect it exceeded the Axios 'maxBodyLength'.

(I only mentioned the ~2kb to highlight that what the user thinks of as the "document" isn't growing...  just the summaries.)

**Comment by curtisman** [comment]
@DLehenbauer @taylorsw04, please feel free to move to real milestone once we know when this will lend.
