### ISSUE TITLE
Lost Channel Entry between Summaries

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5353]
might be related to #5224 

We are seeing a channel go missing between summarieshttps://portal.microsofticm.com/imp/v3/incidents/details/229113984/home

**Comment by sumedhb1995** [comment]
Linked IcM has been resolved via hotfix. Should this issue still be kept open @anthony-murphy ?

**Comment by ChumpChief** [comment]
Removing OCE tag per note this was resolved by hotfix.

**Comment by tylerbutler** [comment]
@jatgarg Can you verify that this is resolved and then close this bug? Thanks!

**Comment by jatgarg** [comment]
We are not seeing this issue anymore after disabling blob deduping which we suspected could be the cause. Now we have another issue open for tracking blob deduping with this issue: https://github.com/microsoft/FluidFramework/issues/5444.
So closing this issue.
