### ISSUE TITLE
Write and Integrate Script into release that replaces assert messages with short codes

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5409]
In order to reduce bundle size we should write a script that parses all out code, looks for a asserts, replaces the message with a short unique code, and puts the message in a comment.

**Comment by markfields** [comment]
Nice-to-have: Stability across versions
Must: No dupes within a version

**Comment by anthony-murphy** [comment]
Hoping stability is pretty much free as we likely need to recognize previously shortend asserts, so keep track of used tags shouldn't be much harder

**Comment by curtisman** [comment]
Note that will increase build time quite a bit.  Also, you can only do "invariant" messages only.  Any message that is parameterize might not make much sense.  

IMO, building out the source-map stack resolution pipeline is a better way to solve this problem.

**Comment by anthony-murphy** [comment]
What i don't like about any stack based solution is that we do not control it, or any transformation on the code. that is all done by end consumers. the best we can do is set a policy that we require full stack traces for any investigations, but that doesn't seem tenable. 

Also, it doesn't need to affect build time on a regular basis. we would continue to accept and write strings into our code, and then run a script that short codes all new strings, and then sticks the original string into comments, which are generally compiled out.
