### ISSUE TITLE
Users want to config tinylicious and launch it on a port other than 3000

### ISSUE THREAD

**Issue by celsoaguiar** [microsoft/FluidFramework#5415]
This is the copy of a question asked on stackoverflow:

https://stackoverflow.com/questions/66536190/can-the-tinylicious-server-be-launched-at-a-port-other-than-3000?noredirect=1#comment117623175_66536190

Can the tinylicious server be launched at a port other than 3000? I've tried something like "PORT=4100 tinylicious" and I can see the terminal log saying:

`@federation/shell-app: [1] info: Listening on port 4100 {"label":"winston","timestamp":"2021-03-08T19:23:37.861Z"}
`

but later it fails within my code, indicating something went wrong with the service call:

```
main.js:15815 ERROR TypeError: Cannot read property 'shapeClicked' of undefined
    at Layer.onClick [as zzClickFunc] (collabmap.component.js:45)
    at JS:24817
    at Array.<anonymous> (JS:8190)
    at window.<computed> (JS:1111)
    at Object.<anonymous> (JS:51778)
    at j (JS:51777)
```
and indeed, the Network tab reveals it's still posting via 3000:

```
Request URL: http://localhost:3000/documents/tinylicious
Referrer Policy: strict-origin-when-cross-origin
```

I know tinylicious is not the full Fluid server and it's just for testing purposes, so it might have been hardwired to 3000, but maybe someone has an idea how to launch it on a different port.

**Comment by SamBroner** [comment]
Seems like it should be pretty easy to get this fixed. It'll definitely be necessary for people wanting to use Tinylicious with the Create React App...

**Comment by curtisman** [comment]
Also may be we should not default to 3000 if it conflict with other popular tools?

**Comment by micahgodbolt** [comment]
any suggestions for default port? that's a quick fix I can make, then look at making the port customizable.

**Comment by skylerjokiel** [comment]
This port doesn't need to be easy for users to remember so it's probably better to just stay away from anything that might conflict. `35843` ? Spells Fluid using text to number 😊

**Comment by micahgodbolt** [comment]
hah, totally forgot that you could do 5 digits too. i think we've got a winner

**Comment by micahgodbolt** [comment]
@celsoaguiar do you need the ability to specify any port, or are you just trying to avoid conflicts on port 3000?

**Comment by celsoaguiar** [comment]
> @celsoaguiar do you need the ability to specify any port, or are you just trying to avoid conflicts on port 3000?

sure, any port would be great

**Comment by micahgodbolt** [comment]
@celsoaguiar i mean, do you have a need to specify a specific port? What is that need?

**Comment by celsoaguiar** [comment]
It conflicts with the port the F/E is using in the project I'm working with, which is complicated to change as it's already in prod. no specific port, as long as not 3000 and not commonly used for other things.

**Comment by micahgodbolt** [comment]
yeah...3000 is really common, we were hitting with Create React App as well. It's currently fixed in main, and will go out with next release.

**Comment by paullam328** [comment]
One shall refer to this answer to configure Tinylicious to any port s/he wants: https://stackoverflow.com/questions/66536190/can-the-tinylicious-server-be-launched-at-a-port-other-than-3000/66609059#66609059
