### ISSUE TITLE
Clean up Container.serialize() code path

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#5430]
It should probably have logic more shared with summarize code, i.e. consider removing `createSummary()`.

The `captureProtocolSummary()` and `convertProtocolAndAppSummaryToSnapshotTree()` could be moved to runtime, and in fact most/all serialize logic as well.

**Comment by curtisman** [comment]
@arinwt, is this plan to be done soon, or should it be put into the "Next" milestone?

**Comment by arinwt** [comment]
@anthony-murphy mentioned we should try to do it soon, because it isn't in use yet. If it starts getting used while the logic lies in the loader layer, it will be harder to pull out later. Also, I think this can be done in a small amount of time. I'll take a look at it later today.

**Comment by arinwt** [comment]
Putting it in next, since I'm not sure how simple it is to move the parsing logic.

**Comment by jatgarg** [comment]
Also, what are we going to use instead of createSummary()?
