### ISSUE TITLE
Revisit blob deduping

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#5444]
## Work Item
We disabled the blob deduping with this PR: https://github.com/microsoft/FluidFramework/pull/5401
We were having bug with deduping with handle expansion. So to be safe we disabled both handle expansion and blob deduping.
We are also working on blob aggregation. So revisit blob deduping later to decide whether we want to reenable it in parts or remove it completely.

**Comment by anthony-murphy** [comment]
@jatgarg how much work is it to just pull out the code?  That's my preference for now, and would be good to do in may. @vladsud  has also mentioned that if we decided to bring it back, we'd likely do it at another layer that is more reusable, so that's why i don't think we should keep this code.

**Comment by jatgarg** [comment]
Not much work to remove the code. Yes, I think I can take this in may.
