### ISSUE TITLE
Add typing for KeyValueData to KVPair 

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/FluidFramework#5494]
probably something like

```ts
export interface KeyValueData {
    [key: string]: string | number | boolean | KeyValueData | KeyValueData[];
}
```

**Comment by micahgodbolt** [comment]
Could use https://github.com/microsoft/FluidFramework/blob/16f58fc65c8b6693a04a75e2b9554656a3a47f5c/packages/runtime/datastore-definitions/src/jsonable.ts

**Comment by curtisman** [comment]
I am not sure the usability of those type has been proven yet.  Currently, I believe only SharedCell use it.  I had a hard time using the Jsonable/Serializable type when I try to introduce them to SharedMap/SharedDirectory. It forces a lot of long ugly typing like `SharedCell<AsSerializable<IBadgeType>>`

**Comment by micahgodbolt** [comment]
As an experimental data object, I'll just go with something that works, and we can refine over time. I just want to clean up the `{[key:string]: any}` I'm currently hard coding into the demo, which isn't even fully accurate.

**Comment by tylerbutler** [comment]
> I had a hard time using the Jsonable/Serializable type when I try to introduce them to SharedMap/SharedDirectory.

I have a follow up from #136 to file new issues to remove those types.

**Comment by micahgodbolt** [comment]
closing this down as set sunset KVpair
