### ISSUE TITLE
Unhandled exception in test does not cause test failure

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5522]
packages\dds\ordered-collection\src\test\consensusOrderedCollection.spec.ts
"Event" test hits an exception in this callback:

                testCollection.on("add", (value) => {
                    assert.strictEqual(value, input[addCount], "Added event value not matched");
                    addCount += 1;
                });

However this exception is hit after method was completed, and does not cause test failure.
This seems wrong, as test should properly cleanup after itself, and any unhandled exception should result in test failure!

**Comment by markfields** [comment]
Indirectly related to #5655
