### ISSUE TITLE
NackWithNoReconnect event: "Nonexistent client" errors in telemetry

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5557]
Last 30 days:

Nack: Nonexistent client    write        noninteractive/summarizer    12911
Nack: Nonexistent client    write        interactive    1616
Nack: Readonly client    read        interactive    885
Nack: Nonexistent client    read        interactive    18

Per Gary, this is due to client not sending any ops for 5 minutes.

It sort of makes sense, but it's also weird. I.e. for main client - it's normal and expect - it should just switch to read mode.
Summarizer - maybe? If all clients disconnected, then it makes sense to dump summarizer as well.

I think at minimum we should ensure this is not an error. I.e. if there is unique error code, we should figure out how to not produce these errors for these messages.
Even better - driver maps it to "disconnect" message.

**Comment by vladsud** [comment]
@GaryWilber , to clarify - I assume we get a nack on some of that clients sends at some point.
If so, why client did not get any notification from the server that prior connection is closed?

**Comment by GaryWilber** [comment]
+@tanviraumi 

@vladsud Can you clarify what you mean by "connection is closed". Is the websocket connection closed, or are you referring to the nonexistent client message?

This nonexistent logic is controlled from deli's idle client timer ([here](https://github.com/microsoft/FluidFramework/blob/f29408296248d9b0054ac3d16b7dedd420623390/server/routerlicious/packages/lambdas/src/deli/lambda.ts#L692)). It will insert a "leave" message for clients that haven't submitted any ops for a while.

The frontend websocket server is not aware of that happening - from it's perspective, the client still has a write connection.
So after this happens, the next time the client submits an op, the frontend sends the op to deli and deli will see that the client does not exist and it sends the "Nonexistent client" message ([here](https://github.com/microsoft/FluidFramework/blob/f29408296248d9b0054ac3d16b7dedd420623390/server/routerlicious/packages/lambdas/src/deli/lambda.ts#L384))

The client should see the leave op that deli creates when this is happening. So the client should be able to act on this, such as changing the connection to "read".

**Comment by vladsud** [comment]
Here are top 5 reasons for disconnects from latest TAP 40 run (with all latest fixes):
  | Disconnect: socket.io: server_disconnect: TokenExpired | 158,494 |  
  | Nack: Readonly client | 87,788 |  
  | Container closed | 35,953 |  
  | 0x07b | 87 |  
  | 0x07d | 91

This looks very clean.

Here is latest from Kusto - not all fixes are in prod yet:

Disconnect: socket.io: server_disconnect: InvalidPermissions	302678
Disconnect: transport close	272002
Nack: Readonly client	219231
Container closed	133318
socket.io: server_disconnect: InvalidPermissions	65102
Disconnect: socket.io: server_disconnect: TokenExpired	48309
Disconnect: socket.io:server_disconnect	47755
Nack: Nonexistent client	38539
Disconnect: ping timeout	28614

We know by now that some of the "Nack: Nonexistent client" are due to clients not processing any ops as they were blocked by ops fetch to storage being stalled. This bug is fixed in latest main, so this number is expected to drop similar to latest TAP40 once bits propagate.

So based on all that data, resolving it as fixed

**Comment by vladsud** [comment]
This is definitely happening in prod, where clients do stay idle that long on socket.
That's one of the top disconnect reasons actually.
We can address it by client reconnecting as read whenever it seems its own leave op.
It feels like for most part it's not that important. However there are some cases where it may make a difference.
For example, clients that can't reconnect, i.e. agents, including summarizer.
It would be wrong to keep an agent alive doing some expensive CPU calculations while we know that results of this computation can't be committed to a file. So I think disconnecting / reconnecting sooner is good thing to do.

So reactivating, assigning to October to take a look

**Comment by vladsud** [comment]
#7180 has more data (copied over key pieces from here), so closing as dup
