### ISSUE TITLE
Move handling of tagged telemetry properties to host layer

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5560]
## Work Item
**Describe the outcome you expect**
Follow-on to https://github.com/microsoft/FluidFramework/pull/5308.  Handling of tagged telemetry properties belongs in the host layer, where logs may be uploaded via a telemetry system.

**Approach**
Update `ITelemetryBaseLogger.send` to take `ITaggableTelemetryProperties` instead of `ITelemetryProperties`.
> DONE

See comment below for detailed plan:  https://github.com/microsoft/FluidFramework/issues/5560#issuecomment-867843015

**Open questions**
Consider whether all our logging APIs should speak in `ITaggableTelemetryProperties`, not just error logging - probably so.
 > YES.  Done.

**Additional context**
See https://github.com/microsoft/FluidFramework/pull/5308/ for introduction of the tagging

Pre-requisite is #5561 

**Acceptance criteria**
Hosts are able to handle tagged telemetry data.  Follow-up change will be to remove our handling of tags in telemetry-utils/src/logger.ts

**Comment by markfields** [comment]
When `ITelemetryBaseLogger` is updated to support tags, we should also add an optional flag to it indicating the host's implementation supports them.  If this is unset, then we need to continue scrubbing and returning plain old telemetry props as a back-compat measure.

**Comment by markfields** [comment]
Update: `ITelemetryBaseLogger` has a new field `supportsTags?: true`, if it's true we can send tagged properties on the log events, if not we need to deal with them ourselves.

Also, `ITelemetryProperties` itself was updated to include optional tags, which is different from when this issue was first opened.

Work here is to implement `supportsTags` on all our loggers (`TelemetryLogger` and subclasses), and then only handle tags as we do if `supportsTags` is not `true`.

**Comment by markfields** [comment]
There's also a bug in Office Fluid's ADO list covering the work over there to support tags

**Comment by markfields** [comment]
This plan is changing, per [this conversation](https://github.com/microsoft/FluidFramework/pull/6478#discussion_r654708980).

New plan:

1. Work with Office Fluid team to properly support tags, specifically to pass-through `PackageData`. At this point though, no tagged data will come to their logger due to existing accommodation.
2. Patch the Definitions packages:
  a. `common-definitions`: Mark `supportsTags` as deprecated, or just remove it (if ok breaking semver rules).
  b. `container-definitions`: Add `taggedLogger`
3. Update Loader and Runtime
  a. Loader: pull in updated definitions, and duplicate `logger` to `taggedLogger` on `ContainerContext`.
  b. Runtime: Send tagged data as-is to `IContainerContext.taggedLogger` if present, otherwise continue handling tags and pass untagged data to `IContainerContext.logger`

Along the way, we'll need to revisit `BREAKING.md` to clarify all this.

FYI @ksbrar

**Comment by ksbrar** [comment]
Overview of PRs (not including bohemia changes):
1. (2 PRs) 
- [ ] Change `common-definitions` by marking `supportsTags` deprecated in main. 
- [ ] Then backport as minor patch off of the common-definitions 0.20.1 tag
2. (2 PRs) 
- [ ] Add `taggedLogger` to `container-definitions` in main
- [ ] backport it as a patch off of the build-common 0.22.0 tag
3. (1 PR)
- [ ] One change to update usage of definitions, add taggedLogger to `ContainerContext` and update runtime handling appropriately.

**Comment by markfields** [comment]
For step 2, should be backporting to container-definitions 0.39 I think

**Comment by markfields** [comment]
Office Fluid PR to properly handle tags:  https://dev.azure.com/office/OC/_git/office-bohemia/pullrequest/884580

**Comment by markfields** [comment]
We changed the plan for how to implement this, did plenty of work on it this month but need another week or two to execute on the new plan and multiple staged PRs.

**Comment by markfields** [comment]
btw I think you can also mark `logger` as deprecated on `IContainerContext` and `ContainerContext`, but could be wrong

**Comment by markfields** [comment]
🎉
