### ISSUE TITLE
Move telemetry tagging types to common-definitions

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5561]
## Work Item
**Describe the outcome you expect**
PR https://github.com/microsoft/FluidFramework/pull/5308/ introduced several new types to facilitate tagging telemetry properties [here](https://github.com/microsoft/FluidFramework/commit/41b19e79ba974f8b653be9b5e001103d16ffb0f1#diff-a8e8af708cd24804ad20446f3a666813d33871f415efed5b116b64a381f93298R527).  They belong in `common-definitions` (and maybe some of the utility functions belong in `common-utils`).

**Approach**
1. Copy code over to common package(s), merge, wait for pre-release package(s) to be published
2. Update telemetry code dependencies to updated pre-release package(s)
  a. Note - Remember to update server first then client's deps on server/common together

**Comment by ksbrar** [comment]
Three PRs:
* Move tagging types to common-definitions - DONE: https://github.com/microsoft/FluidFramework/pull/6165
* Update common-utils - DONE: https://github.com/microsoft/FluidFramework/pull/5962
* Update server and client - TODO: waiting on upcoming plans for 0.40 and common-definitions being pulled out of rest of monorepo versioning.

**Comment by markfields** [comment]
@ksbrar - way to go you did it 😅
