### ISSUE TITLE
Real Service Tests - Facilitate debugging the .fluid files generated from a test run identified in the logs

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5563]
## Work Item
**Describe the outcome you expect**
If we find a particular event sequence or error in the logs or in the pipeline output for a Real Service Test (e2e or stress test), we would like to be able to quickly jump to that file in SharePoint.

**Approach**
First identify if it's possible to find the file (is it logged by OdspTestDriver?). If yes - how do we make it more streamlined.  If no, how do we log it to make it streamlined.

**Open questions**
* Is it already logged somewhere? How will we correlate to test tenant info/credentials?
* What about r11s tests?  Not relevant in the short term, right?

**Acceptance criteria**
Given some logs from a Real Service Test, we can go find the file in SharePoint and open it with Fetch Tool

**Comment by markfields** [comment]
@anthony-murphy has done this - today it requires going from logs -> pipeline build console logs -> container URL.  So could close this after documenting that, or streamlining it somehow.

**Comment by anthony-murphy** [comment]
@markfields I don't think we should do more than log it in the pipeline. we should bias towards debugging via our production logs, and if they are not enough, then they should be improved. i worry if we make it too easy to access the file we will bias towards that crutch, and not be in a good position to diagnose issue from logs.

**Comment by markfields** [comment]
That's fine, totally agree on wanting our team to be fluent in our logs and for the logs to be able to stand alone.
