### ISSUE TITLE
Tool to manual delete unreferenced content from file

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5566]
As we get to a point of enabling marking of unreferenced content, we need tools to prove to ourselves that it works correctly.
Using search pipeline for that is too imprecise and slow.
As such, I propose we build workflow (maybe it's a node script, maybe it's some localStorage flag that we can flip in prod) that would delete all unreferenced content in a file, such that we can experience if it works correctly or not.

Combined with some telemetry like [handle resolution logging](https://github.com/microsoft/FluidFramework/issues/5565), we could find and address issues faster.

**Comment by agarwal-navin** [comment]
https://github.com/microsoft/FluidFramework/pull/5539 - I am adding a test mode that can currently be enabled via loader flags. In this mode, data stores that are unreferenced are immediately deleted from the container runtime's data store context list. I think its a start and we can build on it.

**Comment by agarwal-navin** [comment]
@vladsud I added a runtimeoption and localStorage flag that can be enabled to delete unreferenced data stores as soon as GC runs. Is there anything else we need to do for this or can I close this one?

**Comment by agarwal-navin** [comment]
Talked to Vlad. The runtime option that we currently have is good enough for this. Closing this out.
