### ISSUE TITLE
GetDeltas telemetry - use "reason" field instead of appending to event name

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5608]
Today the "reason" for GetDeltas being called is appended to the telemetry event name, which to me looking at the logs distracts from the fact that it's really a single event, regardless of why it's happening.  Also the event name `GetDeltas_Error` in particular is misleading.

We have other code that populates the `reason` field, I think we should use it here and collapse all these down to a single event name `GetDeltas`.

Here's the list today of related event names (_cancel, _end, _start due to perf tracking system):
Data_eventName
fluid:telemetry:DeltaManager:GetDeltas_AfterConnection_cancel
fluid:telemetry:DeltaManager:GetDeltas_AfterConnection_end
fluid:telemetry:DeltaManager:GetDeltas_AfterConnection_start
fluid:telemetry:DeltaManager:GetDeltas_AfterConnection_update
fluid:telemetry:DeltaManager:GetDeltas_autoReconnect_cancel
fluid:telemetry:DeltaManager:GetDeltas_autoReconnect_end
fluid:telemetry:DeltaManager:GetDeltas_autoReconnect_start
fluid:telemetry:DeltaManager:GetDeltas_autoReconnect_update
fluid:telemetry:DeltaManager:GetDeltas_DocumentOpen_cancel
fluid:telemetry:DeltaManager:GetDeltas_DocumentOpen_end
fluid:telemetry:DeltaManager:GetDeltas_DocumentOpen_start
fluid:telemetry:DeltaManager:GetDeltas_DocumentOpen_update
fluid:telemetry:DeltaManager:GetDeltas_DocumentOpenResume_cancel
fluid:telemetry:DeltaManager:GetDeltas_DocumentOpenResume_end
fluid:telemetry:DeltaManager:GetDeltas_DocumentOpenResume_start
fluid:telemetry:DeltaManager:GetDeltas_DocumentOpenResume_update
fluid:telemetry:DeltaManager:GetDeltas_EnqueueMessages_OutOfOrderMessage_start
fluid:telemetry:DeltaManager:GetDeltas_EnqueueMessages_OutOfOrderMessage_update
fluid:telemetry:DeltaManager:GetDeltas_EnqueueMessages_ReconnectOps_end
fluid:telemetry:DeltaManager:GetDeltas_EnqueueMessages_ReconnectOps_start
fluid:telemetry:DeltaManager:GetDeltas_Error
fluid:telemetry:DeltaManager:GetDeltas_InitialOps_cancel
fluid:telemetry:DeltaManager:GetDeltas_InitialOps_end
fluid:telemetry:DeltaManager:GetDeltas_InitialOps_start
fluid:telemetry:DeltaManager:GetDeltas_InitialOps_update
fluid:telemetry:DeltaManager:GetDeltas_OutOfOrderMessage_cancel
fluid:telemetry:DeltaManager:GetDeltas_OutOfOrderMessage_end
fluid:telemetry:DeltaManager:GetDeltas_OutOfOrderMessage_start
fluid:telemetry:DeltaManager:GetDeltas_OutOfOrderMessage_update
fluid:telemetry:DeltaManager:GetDeltas_Reconnect_cancel
fluid:telemetry:DeltaManager:GetDeltas_Reconnect_end
fluid:telemetry:DeltaManager:GetDeltas_Reconnect_start
fluid:telemetry:DeltaManager:GetDeltas_Reconnect_update
fluid:telemetry:DeltaManager:GetDeltas_ReconnectOps_cancel
fluid:telemetry:DeltaManager:GetDeltas_ReconnectOps_end
fluid:telemetry:DeltaManager:GetDeltas_ReconnectOps_start
fluid:telemetry:DeltaManager:GetDeltas_ReconnectOps_update

**Comment by markfields** [comment]
@vladsud Any objections?

**Comment by vladsud** [comment]
Code was refactored and these events are gone - resolving.
