### ISSUE TITLE
Number of unsummarized ops spikes every once in a while

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5617]
Every month (based on stats) we get a case where number of unsummarized ops goes really high and triggers alert on Bohemia side: https://portal.microsofticm.com/imp/v3/incidents/details/229804425/home
While from stat point of view this seems totally normal (assuming normal distribution of the metric), we need to take a closer look and see if there are any bugs or improvements we should / can do to reduce changes of it, or have a discussion with Bohemia team on how to adjust the alert for it to not fire if spike is very short lived.

**Comment by arinwt** [comment]
Planning to resolve this issue from the "adding telemetry" stage outlined in this issue: #5222

**Comment by markfields** [comment]
Quick comment here - One incident I looked at happened over the weekend, when the volume of summaries dropped, so noise from a single document overwhelmed the signal and tripped the alert.  So another strategy may be to add logic to the alert to include a minimum overall volume? On the other hand, simpler is way better so needs some more thought.
