### ISSUE TITLE
Report number of data stores / DDSs on load and upload summary

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5618]
That's rather critical piece of telemetry that helps understand complexity of the document and relationship to snapshot size / blob counts, etc.

Not clear what layer is the best here, it's possible that driver reported it as part of TreesLatest might be the best in terms of having single event with very rich property bag. At the same time that means that only ODSP will get it, which might be a minus.

**Comment by vladsud** [comment]
@jatgarg , any chance you can help me with this in June?
I do not have good feeling on where to add this telemetry. It might be in container runtime, or it might be a property on TreesLatest, or maybe summarizer can add property to one of its events (and maybe report both total number of data stores and number of summarized data stores).
One way or another - I do not want extra event (for COGS reasons).

**Comment by anthony-murphy** [comment]
@jatgarg if we have a clear idea of where to add this telemetry @chensixx should be able to get it added.

**Comment by jatgarg** [comment]
I will take a look and update here.

**Comment by jatgarg** [comment]
We can do it in ContainerRuntime, but for that seems like we need to add another event as I could not find any to which we can add to. While summarization, we don't summarize everything, we only summarize the dirty ones. So feels like at this point we can add it to trees/latest telemetry as that would be natural place to add.

**Comment by vladsud** [comment]
Summarization process (as a whole) has access to all data stores, including those that are not summarized due to incremental summaries. So I think it's useful to have that data point there (also helps to see how effective is our incremental story).

Here are couple places where we can add it:
1. Driver: fluid:telemetry:OdspDriver:uploadSummary_end or fluid:telemetry:OdspDriver:uploadSummaryWithContext_end - driver has full picture of the tree and which paths are reused from prior summary
2. Runtime - fluid:telemetry:Summarizer:Running:GenerateSummary_end - this kind of stats can be added to GenerateSummaryData. Note that it is produced by ContainerRuntime.generateSummary, so it's perfect place to add anything there.

# 2 seems like more logical and inclusive place.
Note that we log props like that (i.e. there is summaryStat, we might add similar topLevelSummaryStat property there and extend it there)
        const telemetryProps: any = {
            ...summaryData,
            ...summaryData.summaryStats,

I'd love to have telemetry both in summarization process and in loading (TreesLatest) process, as they have different distributions, so given different view into usage, maybe we should split item into two and treat them with different priorities (as having at least one would be good starting point, the other can be added later)

**Comment by jatgarg** [comment]
Assigning it to see as per discussion. @chensixx

**Comment by jatgarg** [comment]
@chensixx You can break this in two parts. First PR on recording this while uploading summary and then follow up with another PR on load.

**Comment by jatgarg** [comment]
@agarwal-navin  We were also thinking about adding telemetry about number of referenced and unreferenced data stores in uploaded summary. Do we already record that somewhere? I think Vlad told me that you were already thinking of adding that?

**Comment by agarwal-navin** [comment]
I am planning to add that information when GC runs. How will you get the data stores for which we are uploading a handle in the summary?

**Comment by jatgarg** [comment]
@agarwal-navin So we can skip the handles. Here we are concerned about data stores impacting the size of summary and handles won't be adding much to the size of summary as compared to tree structure and full blobs. 
Also don't we have info on handles whether their data store is referenced/unreferenced?

**Comment by agarwal-navin** [comment]
No, handles do not have that information. The referenced / unreferenced state is whatever it was in the previous summary.
Another thing to look at is if a data store's summary is a handle, you won't be able to get the number of DDSs in it from the summary itself. We may have to add more state into the summary (for e.g., in ISummaryStats).

If you do not care about the DDSs or referenced / unreferenced for a data store whose summary is a handle, then this work item changes a little and we need to log it accordingly - make it clear that this is number of data store and DDSs which have their summary as tree and not handles.
