### ISSUE TITLE
Reconsider noop coalescing

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5629]
When we look a year or two back, we used to sent a lot of noops. Noop coalescing performed by server made some sense (to reduce impact to file size).

Nowadays, after going through two iterations of improvements (due to noticing too high impact on size of files), clients sent noops not very often - at most every 2 seconds, and at most every 500 ops. So the value of coalescing has been reduced substantially.

At the same time, it causes some troubles for client. DeltaManager already has code that has to take it into account, and now we found another case of incorrect logic - see https://github.com/microsoft/FluidFramework/issues/5628.

I propose we take one of these two more extremes views:
1. We remove coalescing and make noop normal ops (i.e. following normal rules)
2. We completely remove noops from op stream. Instead we replace them with these two steps:
   - client is allowed to send noops with clientSequenceNumber = -1, i.e. it does not change client numbering.
   - Server generates a noop from noClient client if it needs to move MSN, i.e. not attributed to any client.

\# 2 will allow client to treat sending noops as signal, and by not increasing clientSequenceNumber leave all the other logic simpler (as it itself will not count it as a real op).
Note that it is pretty much implementation of signaling, but ordered signaling. Signals might be better, but events should be ordered, and today signals do not provide that guarantee.

**Comment by tanviraumi** [comment]
I think it makes sense to make the logic simpler. Ideally, I would like to remove it completely and just follow proposal 1. But I am not sure about the COGS implication. Even if we are less aggressive, idle clients will still send no-ops.

For proposal 2, its possible that no-ops are only sent by server, never attributed to any client, and server only does it when msn advances. However, allowing clients to send no-ops with "-1" is a bit tricky since we need to make it back-compatible, and we check csn to detect gap/duplicate. To enable that, we need to add protocol version to quorum. I think it's a useful thing to have but we don't have it today.

P.S: Today when the client sends us a no-op with not null content, we sequence it immediately (if it advances the msn). I believe it was added because we wanted to expedite code proposal approval. Do we still need it?

**Comment by tanviraumi** [comment]
FYI @GaryWilber

**Comment by curtisman** [comment]
Any algorithm that requires minSeqNum will need to have it updated quickly.   Although currently quorum proposal is the only one.  we probably want to make sure we have a mechanism for quick minSeqNum update.

**Comment by tylerbutler** [comment]
@tanviraumi Are you working on/thinking about this?

**Comment by tylerbutler** [comment]
@vladsud Tagging you as well.

**Comment by vladsud** [comment]
@tanviraumi, @GaryWilber, Do we have any stats on the server side how effective coalescing in terms of COGS? If not, I'd assume that means we do not care about it. :) And that would mean - # 1 is the way to go. Thoughts?

Reference to code - **CollabWindowTracker**, current policy is at least 2 second and 300 ops between noops, so coalescing should be rather rare. Plus we service should be pushing idle client (who generate only noops) out of "write" mode to "read" mode .

```typescript
        private readonly NoopTimeFrequency: number = 2000,
        private readonly NoopCountFrequency: number = 300,

        // If the ops count since last op is greater than NoopCountFrequency and time since last noop is
        // greater than NoopTimeFrequency, then send a Noop.
        // We will send a message(Noop) to update our reference sequence number upon receiving a server
        // operation. This allows the server to know our true reference sequence number and be able to
        // correctly update the minimum sequence number (MSN).
        if (this.opsCountSinceNoop >= this.NoopCountFrequency
            && Date.now() - this.lastNoopTime >= this.NoopTimeFrequency
        ) {
            this.stopSequenceNumberUpdate();
            this.submit(MessageType.NoOp, null);
        }
```

**Comment by vladsud** [comment]
Adding interesting bit based on looking into issue #6364:
- Not sending noops often contributes to summary / snapshot size and number and size of CatchUp blobs for Sequence (quite big impact, actually). It also makes things like Search contract harder to implement correctly, as latest snapshot (even in case of no trailing ops), the "core" part of it ("body" & "head" Sequence blobs) are quite often behind (occasionally - by a lot of ops), as collab window can be quite large due to idle clients very sporadically sending noops
- At the same time if clients send noops too frequently (in current model), then they quickly starts to contribute to file size directly.

So it feels like the best outcome is something like that:
- no changes in "immediate" noops (quorum) acceptances.
- Clients use some kind of "signal" (TBD) to notify server of their latest consumed sequence number (reference sequence number)
   - this can be done at any frequency, and ideally happens often, like every second or even faster.
- Server incorporates this info and continuously recalculates MSN (same as today). If there are no sequenced ops in some time interval (1-2 seconds) but MSN was changed due to "signals", server generates noop to move MSN.

Note that I'm not sure if actual signals can be used for that (is there enough ordering guarantees on the server around processing of ops and signals that would make it work?). I'd guess the answer is no, and we do need ops for that. That brings back original issue with noops, coalescing and missing clientSequenceNumber. I see couple possible outcomes as we expose problem space:
1. Do nothing - pay extra cost of too many noops.
2. We mostly keep existing behavior, but adjust server logic (as described above): client noop is that "signal", i.e. client noops are never sequenced, and instead server generates server noop after 1-2 seconds of idle (no other ops were sequenced during this time that could have been used to communicate change in MSN).
3. Same as above, but clientSequenceNumber is not used by client on noops (it is -1, undefined, or can be repeated on next op), such that client's numbers are always sequential after sequencing.

@tanviraumi , @GaryWilber - what are your thoughts?

I'm considering increasing back noop frequency as immediate fix for above mentioned bug. This will result in file size growth (we observed it in the past to be substantial, before we got today's behavior), slower catchup (when using cached snapshots), unless we figure out some solution that reduces file bloat due to noops.

**Comment by vladsud** [comment]
Here is one alternative:

We drop all this dance with (non-immediate) noops and instead support only server-controlled policy RE collab window size.
Leaving actual policy aside for a moment, let's assume that it's as simple as 5 second. I.e. MSN at any moment is calculated by server to be what was the last sequenced op 5 seconds ago.
Clients submit ops normally, as if they are always within collab window. Server may reject (nack) if the op is not within collab window and client needs to catch up (merge) and retry.
It's exactly how it works today (almost, minus disconnect), with difference that it's 5 minutes, not 5 seconds policy.

Server needs to communicate occasionally MSN change to clients in presence of no ops (let's say there was a burst of ops in 5 second interval, and then silence - it would be great in couple second for all clients to learn about current MSN and run GC / Zamboni processes). Otherwise MSN movement is communicated on sequenced ops as today.

The biggest con with such proposal is that in case of bursts of activity (or sustained high load), the slowest client would not be able to make progress, as it would be always behind and its ops rejected by sever. I.e. it will be in continuous catch up mode. Today's system has the same problem for sustained high load (that overwhelms slowest client), but avoids it for bursts of activity (as client can still submit ops while being substantially behind during bursts).

The actual server policy RE collab window might be anything, including
- 1000 sequenced ops, if ops are coming in continuously
- 0, if idle (no ops) for 2 second, results in server generating noop to notify clients (needed only if more than 1 client in quorum)

It will increase chances of nacks (race condition around last bullet), but we can optimize handling of nacks (reduce cost by not going through reconnect as it happens today).

**Comment by anthony-murphy** [comment]
I like the alternative proposal.  In theory we could even remove immediate no-ops, and server-side coalescing.  

Instead of immediate no-ops we'd have quorum sends its own op, which will remove complexity from the delta manager and the quorum. The current immediate no-ops make it very hard to coordinate quorum rejects with the code being split. 

Secondly, it would also allow the server to remove the coalescing and remove complexity, as now there would only be server initiated no-ops.

**Comment by tanviraumi** [comment]
@vladsud and I spoke about the issue and we realized that we can increase the consolidation timer and observe the effect. The timer lives here (https://github.com/microsoft/FluidFramework/blob/main/server/routerlicious/packages/services-core/src/configuration.ts#L117) and for r11s, its 250ms. We think increasing it to 2000 is reasonable for now.

Note that this does not solve the non-consecutive clientsequencenumber issue. I will follow up with a cost estimate to make that change.

FYI @GaryWilber

**Comment by vladsud** [comment]
To add to what Tanvir said:
- Our higher priority issue is issue #6364, which manifest itself (as a first approximation of the problem) in big file sizes when we go with two extremes - too fast noops (file size growth due to noops) or too slow noops (catchup blobs in summaries). There are other problems for both extremes (slower boot time, search relevance, etc.)
- We would love to solve this problem (ease of coding on client side) but it's lower priority, and solution to both problems does not need to be one and the same.
   - Tanvir to follow up with SWAG for "alternative solution" described above.

We could solve first problem with a bit of help from server by increasing frequency of this timer. That by itself is not likely to change current behavior of the system until we adjust client behavior as well (which should move back to prior logic of sending noops faster). Client changes should go after server, and that change hopefully (need to measure and validate) will not result in sizable growth of files (there will be some growth, and we need to measure that and adjust timer).

And to fill in the gaps, current server logic is that it always sets the timer on client's non-immediate noop and sends server noop only if MSN would be advanced by it, i.e. in reality - there was no op between last noop (that would have moved MSN) and time expiration. Any sequenced op resets timer.

**Comment by tanviraumi** [comment]
Following up on non-consecutive clientsequencenumber (csn) change. Today, server (deli) uses csn to detect duplicates/gaps on incoming messages. If we want client to sends no-ops with only -1 as csn, we need to update the server logic and only detect gap/duplicates for other ops. This will be a protocol change so we will have to rev protocol version. In addition, we will need to propagate protocol version info to deli (currently, only alfred knows about protocol versions). Finally, Deli will have to understand two protocol versions until all clients are updated.

It will probably take 3~5 days to update both server and clients (server needs to be updated and deployed first in all regions). Note that after this change, service will lose the ability to detect gap/duplicates on no-ops. I don't think they are necessary for no-ops but wanted to call it out explicitly.

**Comment by anthony-murphy** [comment]
Are there any other message types, like service help, where we want to support this kind of fire and forget pattern. Just thinking about design here, and whether it's specific to no-ops, or a more general op kind where we don't track csn, or expect broadcast.

**Comment by vladsud** [comment]
We should also into "alternative solution" (described above) that drops non-immediate ops altogether and moves more control and responsibility to the server to control collab window. That might be simpler and better alternative

**Comment by tanviraumi** [comment]
> Are there any other message types, like service help, where we want to support this kind of fire and forget pattern. Just thinking about design here, and whether it's specific to no-ops, or a more general op kind where we don't track csn, or expect broadcast.

The difference between no-op and others is sequencing. We sequence everything else other than no-ops, which means we can plugin any lambda that looks into sequenced ops (output of deli) and react (e.g., serviceHelpProsessor lambda). Applying this to other ops will be tricky because that lambda will now have to look at raw ops and do a bunch of things (deduplication, nacking) that deli does today.



> We should also into "alternative solution" (described above) that drops non-immediate ops altogether and moves more control and responsibility to the server to control collab window. That might be simpler and better alternative

Let's circle back on the alternate implementation once we have some data after our immediate fix. We can keep this issue open or reopen another one.

**Comment by vladsud** [comment]
Copying text from PR #7127 here to make sure it's easily accessible:

With current (prior to fix) numbers, we were spamming PUSH with too many ops, causing it not handling workload.
2s adjustment will have (using TAP 40 payload) 8x difference in outbound traffic, and should have zero impact on final file size (due to 5 ops / sec of real traffic that results in all noops not being sequenced).
That said, it will regress certain workloads (search quality, size of snapshots), so we will need to re-evaluate impact and next steps.

Long term, we should strongly consider "alternative solution" proposed in #5629 (**this issue**), as well as make our system less susceptible to collab window size (i.e. how summaries are working for Sequence and how search works for Sequence).

**Comment by anthony-murphy** [comment]
Another proposal, or maybe just more details on existing proposals

1. Get rid of immediate no-ops, these should just be ops in the cases they are need, like quorum
2. Require ref sequence number on all signals sent from the client
3. Move client no-ops to signals. make them frequent.
4. Have alfreds track min ref sequence across signals and ops for each client. 
5. Have alfreds kickout lagging/idle clients
6. Have alfreds send coalesced no-ops for their clients, aka min-seq of all clients in an alfred
7. optionally coalesce alfred no-ops.

**Comment by vladsud** [comment]
I'd think signals vs. ops would be equivalent, as in both cases it's not about sequenced ops, it's more about workload on ordering service processing incoming traffic. It would be great to better understand where we spend CPU cycles today.

We also should look into how PUSH throttling and FRS costing works for such cases. It would be really bad if client could spam ordering service with very low impact on number of sequenced ops and thus throttling / costing not capturing such activity. That's a path to DDOS attacks. While we can ensure that we account for such traffic, I think it's much better not to have such asymmetry, i.e. every client action results in either op sequenced or signal sent through full pipeline and accounted for in costing / throttling models.

My original "alternative proposal" above assumed no communication from client, and service automatically moving MSN on some schedule, communicating it to client with some frequency (controlled by ordering service) and using existing Nack mechanism to kick out clients that either have not consumed ops with reasonable speed to learn about MSN movement or run into race condition on this flow (exactly how it works today, though we are not testing / stressing these paths, so there might be bugs).

**Comment by anthony-murphy** [comment]
That seems reasonable. I think putting ref seq on signals, and working that into the minseq calculation is still worthwhile, as we are seeing a lot of signal-based workloads around presence and it seems silly to force no-ops when the client is already communicating. alfred is already generating join and leave messages, so i think adding no-ops to the list makes sense, but doesn't preclude removing client side no-ops, which are the main cause of trouble today.

**Comment by vladsud** [comment]
Some interesting data point from TAP40 ODSP scalability runs:

noops sent every 300 ops: 12k ops/sec
noops sent every 250ms: 52k ops/sec
noops sent every 2 seconds: 19k ops/sec

I believe tests use 5 ops/sec/doc rate with 10 users / doc, with half of clients sending ops (i.e. 1 op / active client / sec, which at 2s frequency of noops roughly corresponds to 0.5 noop / non-active client / sec)

**Comment by vladsud** [comment]
@anthony-murphy , @GaryWilber, @tanviraumi  - bringing it to top of your mailbox / notifications.
Per discussion - let's propose server controlled collab window that does not involve client noops

**Comment by anthony-murphy** [comment]
some data
```
Office_Fluid_FluidRuntime_Performance 
| where Data_eventName == "fluid:telemetry:OpPerf:MsnStatistics"
| summarize count(), dcount(Data_containerId), dcount(Data_docId) by bin(Data_msnDistance, 500)
| sort by Data_msnDistance asc 
```

Data_msnDistance | count_ | dcount_Data_containerId | dcount_Data_docId
-- | -- | -- | --
0 | 44258 | 12563 | 1361
500 | 4479 | 1757 | 127
1000 | 1974 | 1034 | 64
1500 | 779 | 524 | 62
2000 | 323 | 247 | 23
2500 | 201 | 178 | 29
3000 | 132 | 130 | 12
3500 | 64 | 54 | 13
4000 | 108 | 106 | 7
4500 | 37 | 30 | 10
5000 | 111 | 100 | 5
5500 | 29 | 24 | 8
6000 | 94 | 94 | 3
6500 | 13 | 13 | 4
7000 | 91 | 91 | 2
7500 | 7 | 7 | 2
8000 | 80 | 80 | 1
8500 | 7 | 7 | 2
9000 | 80 | 80 | 1
9500 | 7 | 7 | 2
10500 | 5 | 5 | 1
11500 | 5 | 5 | 1

**Comment by vladsud** [comment]
Tail is pretty bad, that shows up in other places (size of catchUp blobs).
These numbers should change dramatically with 0.45, due to return of 2s noops.

**Comment by anthony-murphy** [comment]
added loader version. something we don't have great visibility into is dev session that may do things like hold the session due to break points. also added loader version above

**Comment by anthony-murphy** [comment]
I'm curious how we would formulate server side collab window. right now i'm thinking we will need to estimate RTT per op, so basically every op get's something like 2s, after which it is moved out of the collab window. another question is if there are no-ops does server send no-op? the client will need this to collapse local collab window to reduce things like catch up ops.

**Comment by anthony-murphy** [comment]
op RTT data

```
Office_Fluid_FluidRuntime_Performance 
| where Data_eventName == "fluid:telemetry:OpPerf:OpRoundtripTime"
| extend Data_duration = iff(Data_duration > 10000, toreal(10000),Data_duration)
| summarize count(), dcount(Data_containerId), dcount(Data_docId) by bin(Data_duration, 500)
| sort by Data_duration asc 
```

Data_duration | count_ | dcount_Data_containerId | dcount_Data_docId
-- | -- | -- | --
0 | 342629 | 199549 | 38798
500 | 15062 | 10431 | 4043
1000 | 5915 | 4980 | 2055
1500 | 3298 | 2847 | 1228
2000 | 2208 | 1917 | 873
2500 | 1295 | 1222 | 557
3000 | 859 | 809 | 409
3500 | 586 | 552 | 293
4000 | 494 | 464 | 263
4500 | 383 | 355 | 206
5000 | 284 | 267 | 177
5500 | 248 | 229 | 150
6000 | 197 | 185 | 123
6500 | 174 | 164 | 105
7000 | 168 | 162 | 110
7500 | 110 | 105 | 70
8000 | 110 | 104 | 78
8500 | 110 | 108 | 72
9000 | 84 | 79 | 63
9500 | 93 | 86 | 66
10000 | 1556 | 1192 | 482
