### ISSUE TITLE
Service Load Test:  Run in Buddy to protect the test from regression

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5640]
## Work Item
Add support to the service load test for local server. To support this the orchestrator(nodeStressTest) will need to support launching the running in-process. The runner will need to support being run in memory, just split main into main and run, run takes arguments, and returns, main handles getting args, calling run, and exiting the process. We should then add a step into the npm:test command to run a small version of stress. this is primariyly to make sure the stress test itself isn't broken.

**Comment by curtisman** [comment]
Wouldn't it be easier to target tinylicious?

**Comment by markfields** [comment]
Yeah Tony and I are discussing and also thinking of targeting tinylicious

**Comment by chensixx** [comment]
question: what is run supposed to return?

**Comment by anthony-murphy** [comment]
the stress runner should return a non-zero error code on failure. probably just look for that

**Comment by chensixx** [comment]
are we still targeting tinylicious/local driver. or just any driver

**Comment by anthony-murphy** [comment]
either works. tinylicious is probably easier. should just need to start the stress test from a mocha test in like the mini mode and ensure it exits with a 0 exit code.

**Comment by chensixx** [comment]
wait, isn't  orchestratorProcess already doing "takes arguments, and returns"? what should I add to main?

**Comment by anthony-murphy** [comment]
this work is about adding a test that runs a very small stress run to ensure we don't break the stress test themselves. you shouldn't need to modify the stress test. just add a mocha test that run it.

**Comment by chensixx** [comment]
so a new test file that is similar to nodeStressTest.ts but in mini mode and with tinylicious driver? also checking the exit code is 0

**Comment by anthony-murphy** [comment]
no. not similar to node stress test you should run  nodeStressTest from the test either. i think it should actually spawn a new node process and run nodeStressTest.js with the necessary arguments
