### ISSUE TITLE
Switch OdspTestDriver.driverIdCache to use PromiseCache

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#5652]
e.g. if `getDriveId` below rejects, that cache key will be burned, since you don't remove it in a `.catch`, but PromiseCache takes care of that for ya.

_Originally posted by @markfields in https://github.com/microsoft/FluidFramework/pull/5548#discussion_r602576195_

**Comment by markfields** [comment]
Underlying problem was fixed anyway in #7759
