### ISSUE TITLE
Stress Test - top-level listener for uncaught exceptions/rejections

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5654]
## Work Item
**Describe the outcome you expect**
Uncaught exceptions and Promise rejections should appear in the logs for the stress test.

**Approach**
[uncaughtExceptionMonitor](https://nodejs.org/api/process.html#process_event_uncaughtexceptionmonitor) looks like what we want, and just log an error using the logger when it happens.

**Open questions**
We should also think through what to do with the runner process itself in these cases - let it crash and the orchestrator restarts it? Catch the exception and "reset" the runner to keep going?

**Additional context**
Breaking this out as a work item for #5304

**Comment by chensixx** [comment]
right now uncaught exceptions are already handled in `.catch` block. Mark and I decided to add logging of unhandled promise rejections.
