### ISSUE TITLE
Stress Test - Validate Container state after running

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5657]
## Work Item
**Describe the outcome you expect**
After running the Stress Test, the Container is expected to be in a particular kind of state, with particular Data Objects / DDS's, regardless of how it's loaded (been there the whole time listening to ops, loaded from different snapshots, etc)

**Approach**
@anthony-murphy to add details

**Open questions**
What specific conditions do we want to verify here?

**Additional context**
Even if no error surfaces during the run, if the Container doesn't end up in a healthy/expected/consistent state, we should fail the test run and log an error.

**Comment by anthony-murphy** [comment]
i don't think we need this in april and i don't think anyone will have time to do it this month.
