### ISSUE TITLE
Replace TelemetryNullLogger usage with TelemetryUTLogger in all UTs

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5659]
See TelemetryUTLogger [here](https://github.com/microsoft/FluidFramework/commit/c9cfcd1faeb6e5b6e834f2c784b431110670cd75#diff-a8e8af708cd24804ad20446f3a666813d33871f415efed5b116b64a381f93298R519).

It will log to console then throw an error when any error-like API is called on the logger.

**Comment by markfields** [comment]
@vladsud I'm not sure about this.  It will change the control flow of the code under test, won't it?

**Comment by markfields** [comment]
If you want a way to fail the test if an error log is emitted, let's add some capabilities to [MockLogger](https://github.com/microsoft/FluidFramework/blob/42a5d3ff2a28c0fb3cea748eab0e84820fef9743/packages/runtime/test-runtime-utils/src/mockLogger.ts) to indicate if any error events were logged.  (btw MockLogger needs to live somewhere else...)

**Comment by vladsud** [comment]
Yes, but that's the intent. If you expect no errors in tests, you should use TelemetryUTLogger.
If you do expect errors, then you should likely not use TelemetryNullLogger, but use something else that helps you validate that errors were actually logged.
Using TelemetryNullLogger in tests means engineers does not care about logs, which in most cases is ignorance. It maybe Ok if it's not core of what test validates, but it would be great to get better coverage

**Comment by markfields** [comment]
Yeah I guess my real point is, it may _not_ fail the test as written.  The error may be caught in the code in such a way that the tested quantities are still correct (hard to imagine but I can).  Better to use MockLogger and be explicit IMO.

I like this concept though.
