### ISSUE TITLE
ODSP Driver Join Session Forbidden to Enter Storage Only Mode

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5679]
## Feature
For returning specific error codes in JoinSession, I am planning to add a new response header "X-Session-Forbidden" that will be returned in api response when session creation is restricted on a file. Its value will denote the reason why session is not allowed. For example, for PHL scenario, its value will be PRESERVED_FILE.

Below is a sample failure response for preserved files:

HTTP Status code: 400 Bad Request
Custom Response Header: X-Session-Forbidden=PRESERVED_FILE
Response Body:
{
    "error": {
        "innerError": {
            "code": "invalidRequest",
            "errorType": "expected",
            "message": "JoinSession not allowed as file is in preservation library"
        },
        "code": "invalidRequest",
        "message": "Invalid request"
    }
}

 On receipt of this error code the driver should enter storage only mode.

**Comment by tylerbutler** [comment]
Are there any back-compat issues with existing drivers? I.e. if the driver doesn't enforce the new behavior? Maybe that's not a problem because the server is already responding with a 4xx response with or without the header?

**Comment by anthony-murphy** [comment]
i don`t think so. currently the file just won't open, as join session will fail, and the container will close. this change will allow the container to stay open in storage only mode

**Comment by VineetAg125** [comment]
### Response Details:

**HTTP Status code:** 400 Bad Request

**Header Key:** X-Session-Forbidden

**Possible Header Values:**
- PRESERVED_FILE(When file is present in preservation library)
- MODERATION_ENABLED_LIST(When file is present in a list with "Content Approval" Enabled)
- FILE_REQUIRES_CHECKOUT(When file is present in a list with "Requires Checkout" Enabled)

**Response Body:**
`{
"error": {
"innerError": {
"code": "invalidRequest",
"errorType": "expected",
"message": "JoinSession not allowed on this file"
},
"code": "invalidRequest",
"message": "Invalid request"
}
}`

**Comment by vinitisingh** [comment]
### Response Details:

**HTTP Status code:** 400 Bad Request

**Header Key:** X-Session-Forbidden

**Possible Header Values:**
- PRESERVED_FILE(When file is present in preservation library)
- MODERATION_ENABLED_LIST(When file is present in a list with "Content Approval" Enabled)
- FILE_REQUIRES_CHECKOUT(When file is present in a list with "Requires Checkout" Enabled)

**Response Body:**
`{ "error": { "innerError": { "code": "invalidRequest", "errorType": "expected", "message": "JoinSession not allowed on this file" }, "code": "invalidRequest", "message": "Invalid request" } }`

**Comment by anthony-murphy** [comment]
@vinitisingh in the above response body I assume that `code` is actually a numeric code. If so, can you share  the numeric code for `invalidRequest`

**Comment by vinitisingh** [comment]
> @vinitisingh in the above response body I assume that `code` is actually a numeric code. If so, can you share the numeric code for `invalidRequest`

The `code` in response body is not a numeric code. The actual failure reason will come in the response header `X-Session-Forbidden` @anthony-murphy

**Comment by anthony-murphy** [comment]
interesting. do you know what the numeric http status code will be for the response then?

**Comment by vinitisingh** [comment]
> interesting. do you know what the numeric http status code will be for the response then?

Since it will be a 400 Bad Request, it should be 400

**Comment by anthony-murphy** [comment]
I also now see that at the top! Thanks!

**Comment by vinitisingh** [comment]
Just an FYI, these API changes are not checked-in yet, will update once they are checked-in.

**Comment by markfields** [comment]
@vinitisingh - This is minor feedback, but can we consider dropping the `X-` prefix? See second paragraph here:  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

**Comment by vinitisingh** [comment]
> @vinitisingh - This is minor feedback, but can we consider dropping the `X-` prefix? See second paragraph here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

Sure Mark. Header name changed to `Session-Forbidden`

**Comment by vinitisingh** [comment]
The recommended pattern for Vroom APIs is to throw specific vroom exceptions for each scenario. This means for storageOnly mode, JoinSession will throw three different VroomException, one for each scenario : PreservedFile/ModerationEnabledLibrary/FileRequiresCheckout.

**With this change, the specific errorCode will come in response body(inside `code`) and there will not be any custom response header.**

**HTTP Status code:** 400 Bad Request

### Example response body:

**Response body when JoinSession is called on a preserved file**
```
{
    "error": {
        "code": "sessionForbiddenOnPreservedFiles",
        "innerError": {
            "code": "sessionForbiddenOnPreservedFiles",
            "errorType": "expected",
            "message": "Session is not allowed as the file is preserved.",
            "stackTrace": "Microsoft.ODSP.FluidProvider.SessionForbiddenOnPreservedFilesVroomException: Session is not allowed as the file is preserved.",
            "throwSite": "0_ULS"
        },
        "message": "Session is not allowed as the file is preserved."
    }
}
```

**Response body when JoinSession is called on a file in a moderation enabled library**
```
{
    "error": {
        "code": "sessionForbiddenOnModerationEnabledLibrary",
        "innerError": {
            "code": "sessionForbiddenOnModerationEnabledLibrary",
            "errorType": "expected",
            "message": "Session is not allowed as the file is present in a library with Moderation(Content Approval) enabled.",
            "stackTrace": "Microsoft.ODSP.FluidProvider.SessionForbiddenOnModerationEnabledLibraryVroomException: Session is not allowed as the file is present in a library with Moderation(Content Approval) enabled.",
            "throwSite": "0_ULS"
        },
        "message": "Session is not allowed as the file is present in a library with Moderation(Content Approval) enabled."
    }
}
```

**Response body when JoinSession is called on a file that requires checkout**
```
{
    "error": {
        "code": "sessionForbiddenOnRequireCheckout",
        "innerError": {
            "code": "sessionForbiddenOnRequireCheckout",
            "errorType": "expected",
            "message": "Session is not allowed as the file requires checkout.",
            "stackTrace": "Microsoft.ODSP.FluidProvider.SessionForbiddenOnRequireCheckoutVroomException: Session is not allowed as the file requires checkout.",
            "throwSite": "0_ULS"
        },
        "message": "Session is not allowed as the file requires checkout."
    }
}
```

FYI @anthony-murphy

**Comment by vinitisingh** [comment]
The API changes are checked in and have reached SPDF.

**Comment by anthony-murphy** [comment]
Just learned some things. Code and message should always be safe to log, and innerError may not always exist, so we shouldn't use it

**Comment by markfields** [comment]
@anthony-murphy are those semantics true for all ODSP error responses, or just Vroom, or just this case, or what?  I've poked around various error responses before hoping to learn that kind of thing...

**Comment by anthony-murphy** [comment]
right now not all our fluid apis follow the above format, but they have a desire to move to it, in which case it will apply, but we need to update case by case as they update. not sure if there is plan/timeline, or if well bundle with other changes like this. @marcmasmsft

**Comment by markfields** [comment]
Ok cool. @marcmasmsft if you can share any documentation to these APIs and their error responses that would be super helpful, I'm going to be working on cleaning up our error handling/logging this summer.
