### ISSUE TITLE
Need to implement much longer loader compat validation

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5693]
Apps that ship with a version of loader will be in prod quarters, maybe years.
We need to ensure that
- we test older versions that were shipped many months back
- when we decide to break compat, we do it in predictable manner, raising proper errors to the user (Office.com) and falling back to links in Teams / OWA
- Have one error code that is documented (and used in shared UX) to deal with above.

**Comment by tylerbutler** [comment]
@vladsud This looks like a dupe or subset of #2841.

**Comment by vladsud** [comment]
Resolved as dup #2841
