### ISSUE TITLE
Instrument some asserted error conditions with ErrorType

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5696]
## Work Item

**Describe the outcome you expect**
Issue #4663 lists several asserts that should be marked with an errorType, but that's not supported in the `assert` API. We should get these data points properly instrumented.

**Approach**
Two possibilities here:
~~A. Update `assert` to take an optional `ErrorType`~~
B. Switch to if check and explicit `throw`

**Open questions**
A. This is tricky because `assert` is in the `common-utils` package and we don't want to bloat that. And we also want to constrain the values of `ErrorType` rather than just taking a string, which isn't really possible on such a low-level API in terms of enforcing via types or even just setting expectations for its use.
B. Same problem with whether we want to be able to constrain the values of `ErrorType`. Probably ok to punt on that aspect and plan on just not shooting ourselves in the foot.

**Additional context**

**Acceptance criteria**
* Existing error points with a known error type are properly instrumented
* Bonus: It's clear and straightforward how to instrument this way going forward.

**Comment by anthony-murphy** [comment]
assert should stay simple. if we need more context on an error throw a logging error and provide error type as a property

**Comment by markfields** [comment]
> logIfFalse is a replacement for shipAssert and debugAssert, which only logged, none of those throw like assert does

Yeah good catch, updated the original comment to say "if check and throw".

**Comment by markfields** [comment]
Opting to close this one.  Reason being - asserts are kind of in their own category in terms of how we treat them in telemetry:  DRIVE THEM TO ZERO.  So adding advanced capabilities for categorizing or otherwise annotating them isn't super valuable, since they ideally won't get lost in the noise as-is.

Additionally. with #6950 we'll get the shortcodes as `fluidErrorCode` in telemetry so they'll be easy to find when querying for errors for any particular scenario (presuming the error is normalized before logging)

**Comment by markfields** [comment]
@anthony-murphy FYI
