### ISSUE TITLE
Reconsider summary timeouts

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5699]
Relevant issues:
1. Incremental summary uploads: https://github.com/microsoft/FluidFramework/issues/5690
2. An example of file that fails continuously with timeouts, but client timeouts and fetch timeouts

Consider either removing timeout or substantially increasing it if we keep hitting it.
I.e. it feels like the best course of action is to exponentially increase timeouts and reset back to starting value on first successful summary.

**Comment by arinwt** [comment]
The `SummarizeTimeout` events do not interrupt the process, they are just events logged during the process when generating a summary takes a "long" time. Perhaps we could rename the event name?

**Comment by vladsud** [comment]
Good point. I do not see a reason (from logs) why this file was not summarizing that long, so I want to poke a bit more here:

https://office.visualstudio.com/OC/_workitems/edit/4883680

https://microsoft.sharepoint-df.com/:u:/t/OfficeOnlinePrague/EQ-p2Mz2krtCmgiPJoWi5ZMBpzWF74AVUNtgvCjHZDEdWw?e=Nm3ZVv

**Comment by vladsud** [comment]
Closing, as I believe I got it wrong in terms of interpretation of data.
ADO bug has the following comment from Marcelo:

Closing this; file is back in healthy state.
There were several issues at play:
File not summarizing due to bad quorum - fixed in PUSH/ client
No limit on temporary summaries (channels) - changed to 2 max
Total number of snapshots reduced from 10 to 3
