### ISSUE TITLE
Support StorageOnly via FluidMode query param for ODSP Driver

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5701]
This is with reference to changes required for supporting storageOnly mode for files in Preservation library 
I am planning to add a new query parameter "fluidMode" that can signal driver side to not make a JoinSession call on that file. 

This query parameter will be added in redirection URLs for fluid files in Preservation Library. 
For e.g. if the redirection URL for a .note file in PL is https://www.onenote.com/meetingnotes/abc/xyz/123, it will be changed to https://www.onenote.com/meetingnotes/abc/xyz/123?fluidMode=storageOnly.

Rationale behind introducing a new param and not re-using fileVersion param(one used for opening older versions):
As I understand, fileVersion parameter is expected to contain a specific older version of a file. For PL scenario, we would always want the latest version's content. Considering this and also the fact that in future we might want to add specific behavior for older versions, I think having a separate parameter would decouple storageMode with file versions. 
Please suggest if you think otherwise.

**Comment by anthony-murphy** [comment]
related #4956 #5679 #5545

**Comment by anthony-murphy** [comment]
We just need to extend everywhere we extended for fileVersion to also include fluidMode=storageOnly and used everything else that was done in this PR: https://github.com/microsoft/FluidFramework/pull/5137

**Comment by curtisman** [comment]
I assume this is `URLResolver` parsing the URL putting a flag in `IOdspResolvedUrl` for the actual driver to consume?

**Comment by anthony-murphy** [comment]
And then setting storageOnly true in the policies of the documentService. There are also a couple other helper functions/objects to extend, pretty much just follow the same pattern as fileVersion

**Comment by anthony-murphy** [comment]
looks like sharepoint isn't going to implement this, and will need #5545 instead, so we don't need to do this work
