### ISSUE TITLE
Trusted Types support in Fluid?

### ISSUE THREAD

**Issue by shhnjk** [microsoft/FluidFramework#5711]
## Feature
**Is your feature request related to a problem? Please describe.**
It is important for a new framework to support [Trusted Types](https://web.dev/trusted-types/). Because more and more websites will start deploying Trusted Types. For example, we [enabled Trusted Types by default](https://microsoftedge.github.io/edgevr/posts/eliminating-xss-with-trusted-types/) on Edge's browser internal pages.
Frameworks like React already support Trusted Types.

**Describe the solution you'd like**
In the framework, you shouldn't be calling dangerous sinks (e.g. `innerHTML`) which can convert a string to an HTML, which might be an user input. Instead, use things like `document.createElement`, `elem.textContent`, and `elem.appendChild` to construct DOM Nodes.

**Existing work**
Some approach we used to convert existing code to be compatible with Trusted Types on Chromium is described at [here](https://chromium.googlesource.com/chromium/src/+/master/docs/trusted_types_on_webui.md#How-can-I-Trusted-Type-my-code).

**Comment by curtisman** [comment]
Fluid framework is a data sync library, and doesn't have any dependency on the DOM in the framework libraries.
There might be some update that can be done for examples.  Please open specific issue for those, and will address them as warranted over time.   And of course contributions are welcome.
