### ISSUE TITLE
Sharepoint framework integration

### ISSUE THREAD

**Issue by IvoCurado** [microsoft/FluidFramework#5729]
### Issue Category

- Other

### Details

I can't find any documentation about the integration of fluid framework in a SPFx Web Part.
I already saw some videos where the fluid framework is working on a Web Part but I couldn't find any code sample about it.
Is it possible to integrate the fluid framework on a SPFx Web Part?

**Comment by skylerjokiel** [comment]
@IvoCurado , I'm really excited to see your interest in SPFx + Fluid. Currently don't have any formal integration between the two. Within Microsoft we are exploring opportunities between the two products and we believe there are multiple compelling scenarios. Thanks for your patients and definitely stay tuned. We are hoping to release more information about these technologies will be integrated in the coming months.

**Comment by IvoCurado** [comment]
@skylerjokiel , Thanks for the answer. Looking forward to see that integration.
