### ISSUE TITLE
Sweep tests for GC

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#5734]
Add testing for `sweep` stage of GC. The idea is that we create a data store, perform operations on it for a period of time and then remove its handle making it unreferenced. This data store should now be deleted and it should not cause any unexpected issues during normal usage after deletion.

**Comment by anthony-murphy** [comment]
Adding design required here, as i don't think this is actionable without a better idea of what we want to stress specifically

**Comment by agarwal-navin** [comment]
I actually don't see a lot of value in adding more GC specifics to the service load tests. These should probably be added in a separate GC stress test.

**Comment by agarwal-navin** [comment]
Closed in favor of https://github.com/microsoft/FluidFramework/issues/7207
