### ISSUE TITLE
DDS to use deep-cloning / immutable objects when raising events, returning current state

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5738]
Let's consider a case of ISharedMap (as an example) and a value stored in it being an object (any mutable object, like an array, or object with properties).

There are 3 key workflows:
1. Setting new value for a key:
```typescript
   const value = {a: 6, b: 7};
   map.set("mydata", value);
   value.a = 5;
```
2. reading data:
```typescript
   const value = map.get("mydata");
   value.a = 4;
```
3. get, modify, and set data:
```typescript
   value = map.get("mydata");
   value.a = 5;
   map.set("mydate", value);
```
**Requirements:**
1. After value is set on DDS, original object stays mutable. I.e. it's not deep-frozen. Making any changes on this object has no impact on a value stored in DDS.
2. It's impossible to change DDS value by mutating value retrieved from it (case # 2 above).
3. Convenience (optional, but highly desired): get-modify-set cycle should be easy to use, ideally without a need to deep-clone an object retrieved from DDS in order to mutate it.

Today, first two scenarios are broken.
While third one sort of works, but really broken as value change event is incorrect (it would say that nothing changed).

There are 3 possible mechanisms we could use here:
1. **Deep freezing objects**. This does not work well for set & get-modify-set scenarios. 
2. **Deep readonly types** - this only works for get scenario. Does not help at all with set and makes user dep clone data for get-modify-set
3. Deep cloning on get & set. This works pretty well from usability and correctness points of view.

So it looks like deep clone is the only possible solution here.
Please note that from implementation perspective, it does not have to be full clone.
Libraries like [Immer](https://immerjs.github.io/immer/update-patterns/) and [immutable.js](https://immutable-js.github.io/immutable-js/docs/#/) could be used to optimize process here.

As for API surface, that implies to everything, including change event notifications - we should never ever expose internal data structures for user to be able to directly modify them.

**Comment by micahgodbolt** [comment]
Is there value to including this in the DDS vs allowing the dev to user Immutiblejs or Immer? For those that don't need immutability, is this just a cost to them?
