### ISSUE TITLE
Shared String: getPositionOfNextTile

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5747]
## Feature
This is a minor improvement on findTile where we are hoping to save time. A common operation on tile markers is to consider them as a collection and ask questions about their positions. For example, for paragraph tile markers, a common question is “does this range contain any paragraph tile markers”? Others may wish to find the position of the next table cell marker, for example, to extend the user’s selection so it encompasses the whole cell. The current findTile returns the tile information as well, including the marker info.

**Comment by pleath** [comment]
Keeping the issue alive.
