### ISSUE TITLE
Return File information directly with in load info

### ISSUE THREAD

**Issue by Czhang0727** [microsoft/FluidFramework#5749]
Currently we have some complex implementation on "Get filename". It require two calls through SPO apis.
It will better if we could have filename directly returned from the loadComponentInXYZ

Ref:
FluidFramework/contracts.ts at main · microsoft/FluidFramework (github.com)
FluidFramework/odspDriverUrlResolverForShareLink.ts at main · microsoft/FluidFramework (github.com)

**Comment by Czhang0727** [comment]
@AndreiZe , would you help to involve who may know the domain knowledge. I know we discussed this for a while, and we really wanna to make it happen.

**Comment by leeviana** [comment]
To clarify, the ask it to put this info on the odspResolvedUrl info

**Comment by kcurlett** [comment]
Adding that this will also be useful for Outlook. We sometimes do not know the file type and end up showing the wrong icon, which leads to mis-matched branding. So this fix will help multiple teams if it is implemented.

**Comment by vladsud** [comment]
@Czhang0727, @leeviana, can someone work directly with ODSP to make that happen?

That said, I'll point out that with both client & Prague Graph layer in ODSP involved in caching of snapshots, the only guarantee the system can provide is that you are getting back the name of the file that it was called some amount of time ago (which is likely counted in many days). Plus there is likely no way to return it through IOdspResolvedUrl, I doubt there is any guarantee that an object one of the driver classes operates is exactly same instance the factory got not a copy. I definitely see we are making copies as local modifications are made not to affect original object.

I doubt merging these things into TreesLatest is the right approach. Why not have a parallel call with TreesLatest (and work with ODSP to make it single call if needed) to get that data?

**Comment by leeviana** [comment]
I don't think this would happen with the treelatest call, this is for the URL resolver ODSP calls that already occur to get file information.

**Comment by vladsud** [comment]
I do not think we have that data anywhere in the system, including URI resolver.
@jatgarg - can you please glance?

**Comment by leeviana** [comment]
Not currently, yeah. I think as you mentioned above we'd want to work with the ODSP team first to add this to the file info calls that the resolver is making (if not already there) and then the resolved info can expose it.

**Comment by jatgarg** [comment]
On create file path, we do have filename info but not on load calls(trees/latest). So we need to work with spo if we want to add that,

**Comment by vladsud** [comment]
I'd suggest whoever needs this functionality to work with ODSP directly to come up with design here (and double check if this is something they can / want to expose. That said, I highly doubt we want to go this pat h for these reasons:
- It would be stale (consider snapshot caching and the fact that we can load from 2-day old cache).
- PUSH (i.e. on socket connection) is likely better place to get it, but I'd think Push does not know file name either and would need to talk to SPO, so there is not much value in proxying it through PUSH.
- There needs to be some update story here (i.e. user working offline for a day, and then eventually connecting - I'd assume we would want to learn about rename happened during this time and refresh UX).

At the moment, this is just to low priority for platform side, and i do not see good story around how to expose this in generic way that makes sense to all services, so it might be worth keeping this topic outside of FF.

**Comment by kcurlett** [comment]
I don't think staleness/update story are concerns here. At least from OWAs perspective we only care about the file name because its the host's responsibility to show the correct icon for branding. There are several types of fluid components/loops that all hydrate and have different brand icons (.fluid vs .note for example). 

We don't even need the full file name. Extension would be enough, if that is easier.

**Comment by marco-ms** [comment]
@kcurlett Teams doesn't care about staleness as well, however we would like the file name and the file extension, not just the extension.

**Comment by vladsud** [comment]
as you probably know, the notion of file does not exist at Fluid Runtime layer. ODSP driver maps container instance to a file, driver interface is generic and not exposed back to host or runtime (in original form), so there is no easy way to ask driver-specific info.
I believe the problem at hand is much better solved in O365 eco-system (i.e. in FFX repo) by recording such info in the file itself and exposing it as a component. This gives you much more flexibility (info stored and exposed could be easily changed / extended in the future) and its uniform for all storages you might ever want to use. That's essentially "container creation properties" (if we want it to be generic). We could help by exposing generic property bag from container runtime, as Si is in the process of adding such concept to it (current PR is not exposing programmatic access to it, but this could be added in the future). This will not change the need to have some contract spelled out outside of FF repo (i.e. interpreting properties to have some meaning), but may simplify / not require unique storage.

**Comment by leeviana** [comment]
The resolved URL interface is exposed back to the hosts and is how hosts today ask for driver specific information. Actually in the interface today I already see a field for filename. While resolving an ODSP driver URL, the ODSP resolver kicks off several odsp specific API calls that return ODSP specific information. I think the key point here is that we want this behavior to be consistent across usages of the ODSP driver with ODSP concepts. That way there's no secret ODSP handshake between Microsoft container developers who have implemented this interface vs not (and also no odsp specific code in code that isn't driver specific).

**Comment by vladsud** [comment]
> the ODSP resolver kicks off several odsp specific
I believe that number is zero. I might be wrong, but I've never seen it in traces / code.
The only place I see resolver doing network calls is OdspDriverUrlResolverForShareLink.getAbsoluteUrl(), but this is not done by driver itself (i.e. driver does not need it to boot a file). This resolver preemptively makes this call to speed up future calls, but nothing in driver depends / wats for it (i.e. resolved URI is returned right away with empty filename). 

I believe filename is available only for create new scenario where it is provided by host. In all other cases it's "".
The only other place where I see driver doing more calls is if TreesLatest failed and we fallback to redeemSharingLink() flow.

**Comment by leeviana** [comment]
Yes, and similarly I think if we attach a promise to the filename field in a similar manner to getAbsoluteUrl where it might eventually have the file name that would be sufficient for hosts. We do not need the file name to boot a file either, it's exactly similar to getAbsoluteURL.
