### ISSUE TITLE
We attempt to upload summary more often than we generate it, suggesting retry logic kicks in when summarizer is offline and already gone

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5751]
This is not urgent, but worth addressing soon (let's say in June).
Compare results of these two queries:

Office_Fluid_FluidRuntime_Performance
| where Data_eventName contains "GenerateSummary_end" or Data_eventName contains "GenerateSummary_cancel"
| summarize count(), sum(Data_totalBlobSize)

	237,694 	23,856,049,936

This is actual bits attempted to upload:

Office_Fluid_FluidRuntime_Performance
| where Data_eventName contains "uploadSummary_start"
| summarize count(), sum(Data_size)

	268,060 	51,477,499,750

Number of attempted uploads we do is actually ~10% higher than number of times we generated summary.
I believe this is due to retry logic in retry storage adapter.
While it's fine for some random issues, it's likely mostly happens due to client becoming offline.
And if client is offline, it's not worth continuing trying to upload same summary as summarizer already gave up.

Unless we are changing infrastructure here (i.e. allowing summarizer to recover and continue after disconnect), I suggest we add ability to cancel upload by passing AbortSignal to uploadSummaryWithContext() API and signal it on closing on summarization container.
Alternatively we can special case upload in retry storage adapter, but I like this less, as all of our networking API have to have cancellation baked into them either way (see https://github.com/microsoft/FluidFramework/pull/5703 as an example).

**Comment by jatgarg** [comment]
@vladsud As I am checking the stats for last 30 days, it seems insignificant. 482K(Generate Summary end) vs 484(upload summary end/cancel). As I can see, we already handle cancellation on summarizer container close because when retrying we check whether the storage service is disposed. If yes, then we don't retry.

**Comment by vladsud** [comment]
Sounds great, let's close it then!
