### ISSUE TITLE
Fetch can report URIs in error messages

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5756]
This query shows we are trapping URIs in our telemetry:

union office_fluid_ffautomation_error
| where Data_buildId == 21333 
| summarize count() by Data_eventName, Data_message, Data_error

fluid:telemetry:Container:ContainerWarning
Service busy/throttled: Fetch error: FetchError: request to https://a830edad9050849829j20060312.sharepoint.com/_api/v2.1/drives/b!Uz0BCJ....
 failed, reason: connect ETIMEDOUT 104.146.237.89:443
 
 Code in fetchHelper() should be modified to stop recording message from error exception, but continue at runtime to tease out interesting cases and convert them to error codes:

```typescript
    }, (error) => {
        // While we do not know for sure whether computer is offline, this error is not actionable and
        // is pretty good indicator we are offline. Treating it as offline scenario will make it
        // easier to see other errors in telemetry.
        let online = isOnline();
        if (`${error}` === "TypeError: Failed to fetch") {
            online = OnlineStatus.Offline;
        }
        if (error.name === "AbortError") {
            throwOdspNetworkError("Timeout during fetch", fetchTimeoutStatusCode);
        }
        throwOdspNetworkError(
            `Fetch error: ${error}`,
            online === OnlineStatus.Offline ? offlineFetchFailureStatusCode : fetchFailureStatusCode,
            undefined, // response
        );
    });
```

**Comment by anthony-murphy** [comment]
There is a related problem in deltaManger.emitDelayInfo where we manually craft the error message, and don't use our safe property extraction methods. this also leads to loosing the call stack

**Comment by markfields** [comment]
Related: #4908

**Comment by markfields** [comment]
I opened #5774 for @anthony-murphy 's deltaManger.emitDelayInfo case.
