### ISSUE TITLE
Signal are lost on load path

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5762]
Our signal story is not ideal. While we do not provide very strong guarantee around them (clients that are disconnected do not receive any), there is a need for at least some level of SLA being available to be able to do anything useful with them. One such guarantee - signals are not lost while connection is in place. That, coupled with clients (and server) re-broadcasting valuable info on new client connected would allow building features on top of it.

The problem is that we are losing that initial broadcast on connection across layers:
1. If "pause" loader option is not used, connection is established in parallel to loading rest of container (and its code). DeltaManager does not batch initial signals for future consumption by runtime, so they are lost.
2. Container runtime does not accumulate signals the same way it accumulates ops on data store contexts before data store is loaded. Thus such signals are lost and do not get to data stores (if they rely on such signaling).

Components may overcome these limitations by sending their own version of "I'm loaded and connected" signal to let other parties know you are here, but it also not ideal ("listeners" might be online, but not respond, because their components might not be loaded either).

I feel like we either need to provide stronger guarantees around boot, or have some library on top of existing system that adds layer of "join / leave" semantics at component (unit) layer, such that units can build more reliable code on top of it. Later likely can account for GC (unit is no longer in the (storage) graph)

Note that Bohemia does not hit most of these problems yet, as
- Connection is done after initial render
- There is no data virtualization, so everything is loaded right away.

This will have (initial) stronger impact on 3rd parties.

**Comment by vladsud** [comment]
@skylerjokiel - FYI

**Comment by skylerjokiel** [comment]
@vladsud , we have yet to expose signals to 3rd parties through the new developer model. It's been on my mind but it's on critical path for any Public Preview currently. We haven't explored presence from the 3P perspective much but currently our examples use DDSes to save and store user location state.

My current thinking is to stay the course and not make signals blocking for any Public Preview or GA scenarios. This gives us more runway to consider how to expose signals in a way that is useful to developers. As you've pointed out signals have some underlying gotchas that we need to consider as we consider how to expose them.

@SamBroner , @tylerbutler , @ChumpChief as fyi.

**Comment by vladsud** [comment]
Find with me - this issue was not intended as we need to address it now, more of - things are not working well and need to be re-evaluated.

I think we should also critically look at original motivations and if they are valid or have better solutions. The motivations were:
- COGS - adding ops from clients that are mostly viewing
- Last edited: not changing who changed file last if user is only viewing
- Read-only ACLs - users may not be able to submit ops, but should be able to view.

It's interesting to compare to how this is done in Word (does read-only clients show up as "viewing" document?) and how it is implemented (is it a separate channel)?
This is probably more complicated on the server, but can we use ops to achieve same requirements somehow? Like parallel stream that all clients (including read-only ACLs) have write access to?
I'm just afraid that signals will keep giving, though it's worth pointing out that they fill into "screw the client" mantra (i.e. keep server simple).

We should also look at where signals are used today. It will be way simpler to limit them to be only at Container level and used for presence and not expose to container runtime. It limits where they can be used, but substantially simplifies our lives.

Also + @tanviraumi

**Comment by tanviraumi** [comment]
Thanks for kicking it off! I think we should be really clear about when and how to use signal, especially for 3rd party developers. We should also clarify what "Audience" means and how it's different from Quorum. May be provide a unified API that hides Quorum and Audience, and provide one unified membership API?

Another important aspect for 3rd party developer is the cost model. How much we should charge for signals? If we charge them like ops, then a developer is better off using ops. If we charge them less, then we need to be clear about the limitations. @ahmedbisht who is thinking about the cost model of signals.

**Comment by vladsud** [comment]
Audience is secondary in this discussion, but I think it's hard to impossible to combine audience and quorum, unless we are willing to provide unified ordering for the two in some way.

**Comment by tylerbutler** [comment]
@skylerjokiel Do you think we need to figure this out in May/June?

**Comment by vladsud** [comment]
@skylerjokiel, I'll assign it to you to make a final call on the messaging from 3P perspective, as that's where this issue shows up first.
The choses are (as I see them):
1. We document that signals should not be used and not well supported yet. Maybe make some proactive move to hide them (maybe it's already not very accessible from 3P perspective)?
2. We move toward the model of establishing connection after container is loaded (from snapshot), allowing signals not to be lost if connection happened too early.
3. We hoard signals in different layers and deliver them once container / data store is loaded (not an option in my view).
4. We build a separate layer that implements "component joined" / "component left" signals for different parties (components, 3P developers) to be able to use signals and not miss them (in context of a "component" only, of course, i.e. we change granularity when "clients" need to broadcast their state - right not it's assumed it happens on "client joined", but we can move toward model of "component joined" in the scope of component usage. Note that "component" here is broad - it's any entity that wants to use signals, but is not Container object).

I believe we want # 1 above, as I do not even see good story for 3P yet (the way we define it), but I might be wrong.
