### ISSUE TITLE
Add test automation that promotes defensive access of localStorage

### ISSUE THREAD

**Issue by jcmoore** [microsoft/FluidFramework#5783]
* Edit 1: added eslint recommendation and comment on nodejs consideration

## Work Item
**Describe the outcome you expect**
This intends to track follow-ups to #5585 and #5588 -- access to `window.localStorage` can not be guaranteed so the Fluid ought to load/run successfully without it.  Tests might be written to preserve this characteristic.  It might also be worth considering normalization of an access strategy -- perhaps using a pattern like the one seen in [isAfdCacheValid()](https://github.com/microsoft/FluidFramework/blob/d8e382148c2dc8b75c55b80ca1bea097a9134bea/packages/drivers/odsp-driver/src/odspDocumentService.ts#L57-L70).

**Approach**
Executing the following should simulate (some of) the inaccessibility we can expect to encounter -- so including this before a test should create the circumstances appropriate for such a test:
```
Object.defineProperty(window, "localStorage", {
  get() {
    throw new Error("Failed to read the 'localStorage' property from 'Window': Access is denied for this document.");
  }
})
```

A test failure message might also point to documentation regarding the recommended/normalized approach for using `localStorage`.

There was also a suggestion to look into an eslint intervention.

**Open questions**
- Should "all" (unit) tests run with no local storage (to give the confidence of broad coverage)?
  - Would eslint provide the desirable breadth of coverage?
- What is the right unified approach for accessing `localStorage`?
- Since Fluid expects to run in nodejs environments, should localStorage references be removed almost entirely (preferring a dependency injection or similar)?
  - Would removing DOM types give some compiler-level protection?

**Additional context**
#5585
#5588 
[isAfdCacheValid()](https://github.com/microsoft/FluidFramework/blob/d8e382148c2dc8b75c55b80ca1bea097a9134bea/packages/drivers/odsp-driver/src/odspDocumentService.ts#L57-L70)

**Acceptance criteria**
Part of the test suite should fail if an unprotected access of `localStorage` is included in the boot path of Fluid.

**Comment by anthony-murphy** [comment]
closed with #8497
