### ISSUE TITLE
Tinylicious: Document data is lost across Tinylicious sessions

### ISSUE THREAD

**Issue by dcakirkaya** [microsoft/FluidFramework#5810]
## Describe the bug

The document data does not seem to be persisted across different Tinylicious sessions. 

### To Reproduce

Can be reproduced in any of the [FluidExamples](https://github.com/microsoft/FluidExamples/), like this:

1. change directory to e.g `draft-js` example, open two terminals. 
2. npm run start:server
3. npm run start:client
4. Browse to localhost:8080, create a new document (in this case it was _1618424917365_), make some changes.
5. Restart Tinylicious (terminate process on 1st terminal & npm run start:server again) 
6. Browse to the same document (http://localhost:8080/#/1618424917365)

7. Document opens with initial state, all changes are lost.

### Expected behavior
I expected the document data be preserved across sessions. 
Is persistence supported at all by Tinylicious ? See these related issues: 

https://stackoverflow.com/questions/67029805/how-to-persist-fluid-document-data-between-tinylicious-sessions
https://stackoverflow.com/questions/65348259/fluid-clients-get-out-of-sync-when-server-is-rebooted

Is default configuration "db.inMemory: true" the reason for this behavior? 

### Logs
Tinylicious server logs show this error:

error: Error while fetching summary for tinylicious/1618424917365 {"label":"winston","timestamp":"2021-04-14T18:29:35.190Z"}
error: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined {"code":"ERR_INVALID_ARG_TYPE","label":"winston","timestamp":"2021-04-14T18:29:35.191Z"}

(I got a repro on Tinylicious 0.3.x as well as 0.4.x)

**Comment by celsoaguiar** [comment]
humm, correct me if I'm wrong but, in the examples, tinylicious is what's keeping that data alive across clients. If you kill tynilicious, away goes your data. For it to work as you want, you'd have to store it yourself in some DB outside Fluid and on a new session initialize tinylicious w/ your previous state.

**Comment by DLehenbauer** [comment]
> Is default configuration "db.inMemory: true" the reason for this behavior?

That's correct.  See the 'Storage' section of the Tinylicious README for info on how to enable persistent storage. ([here](https://github.com/microsoft/FluidFramework/tree/main/server/tinylicious#storage)).

**Comment by dcakirkaya** [comment]
@DLehenbauer I'm already aware of that [Storage section](https://github.com/microsoft/FluidFramework/blob/main/server/tinylicious/README.md#storage), and I had already set it to false, it [still behaved the same](https://stackoverflow.com/questions/67029805/how-to-persist-fluid-document-data-between-tinylicious-sessions). 

Should I open a new bug ? 

PS. The readme refers to a config.json with a broken link (`see config.json` has nothing to see) and it doesn't explain why there are git folders with my document id in /var/tmp/tinylicious if by default is just db.inMemory, or whether this db.inMemory only applies to delta storage and the summaries are always persisted). Some clarification would be great.

**Comment by DLehenbauer** [comment]
@dcakirkaya - Ah..  I see.  Yeah, I would recommend opening a new issue _just_ to make sure that the next person skimming new issues doesn't see the question about 'db.inMemory: true' and stop reading too soon.

@thea-exe - It would be nice to change 'server/tinylicious/README.md' so that the text 'see config.json' is a link to the Tinylicious config.json file ([here](https://github.com/microsoft/FluidFramework/blob/main/server/tinylicious/config.json)).

(FYI - @SamBroner)
