### ISSUE TITLE
Cleanup uses of getContainer once service-specific client packages are available

### ISSUE THREAD

**Issue by sumedhb1995** [microsoft/FluidFramework#5853]
With the move to have service-specific client packages to manage connections to Tinylicious, Routerlicious, ODSP, etc., the examples that are consuming get-container currently need to be switched to use the new packages instead.

This PR introduces the changes to add in tinylicious-client
https://github.com/microsoft/FluidFramework/pull/5838

With those changes, the examples currently using TinyliciousService from get-container in conjunction with FluidStatic can directly use the default export from tinylicious-client

**Comment by dcakirkaya** [comment]
Will there be a service specific client which provides the _getSessionStorageContainer_ functionality?
