### ISSUE TITLE
Docs PR builds should only run when source branch is in the main repo

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#5870]
The PR docs site deployment requires access to the main repo secrets, which are not granted to PRs generated from forks. We can probably fix it by adding some conditional logic to the GitHub action.

**Comment by anthony-murphy** [comment]
I wonder if these steps should be move to a CI build/release, rather than a PR trigger, so it only runs on committed content

**Comment by tylerbutler** [comment]
The value of the PR trigger is that it builds and deploys a version of fluidframework.com so we can review changes in the site context. That's more critical for (a) changes that require the site to be built, like JS fixes and storybook integration stuff, and (b) bigger scope changes where we want a long-running branch with a "staging site".
