### ISSUE TITLE
Make all retry times to be milliseconds everywhere

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5881]
Personally, I'd prefer all the times to be milliseconds everywhere, and rather rename getRetryDelayFromError and make it return milliseconds (and fix couple places).

Note - same problem exists in getFileLink.

_Originally posted by @vladsud in https://github.com/microsoft/FluidFramework/pull/5873#r617142141_

**Comment by anthony-murphy** [comment]
@chensixx can you take a look at this. basically we use seconds in some places, and milliseconds in others, we should just use milliseconds everywhere.

**Comment by chensixx** [comment]
Am I changing to milliseconds everywhere? or only places with retries?

**Comment by jatgarg** [comment]
Yes, retry times is one of them which may be in seconds. We want to convert functions like "getRetryDelayFromError" to return millisseconds. The other one is Throttling error time.

**Comment by chensixx** [comment]
The remaining `retry` are in a few categories:
1. server packages - no change
2. odsp packages - no change
3. loader package, mainly `createGenericNetworkError` and `IThrottlingError` - okay to change?
4. r11s driver: `restWrapper` and `errorUtils` - okay to change?
5. protocol.ts - no change

@anthony-murphy @znewton does this look correct?

**Comment by anthony-murphy** [comment]
looks like ThrottlingError  implements IThrottlingWarning which is in driver definitions, so you can make the class take ms, but it will still need to expose retryAfterSeconds

**Comment by chensixx** [comment]
oh I see. i didn't notice the IThrottlingWarning in container definitions. So maybe just don't change any more places?
