### ISSUE TITLE
Add flag to ISummaryContent to specify if .protocol is part of client summary

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5900]
Add a flag (I prefer an object with flag as a field for future changes) to ISummaryContent (https://github.com/microsoft/FluidFramework/blob/main/server/routerlicious/packages/protocol-definitions/src/protocol.ts#L183). Flag will be true for requests where .protocol was already uploaded by the client.

_Originally posted by @tanviraumi in https://github.com/microsoft/FluidFramework/issues/5771#issuecomment-822872101_

**Comment by tanviraumi** [comment]
Closed with #5909
