### ISSUE TITLE
Update Scribe to honor ISummaryContext protocol included flag

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5901]
Scribe needs to be updated to check the flag and for now, ignore the ".protocol" part of the client tree where flag is set to true.

flag to be added as part of #5900

_Originally posted by @tanviraumi in https://github.com/microsoft/FluidFramework/issues/5771#issuecomment-822872101_

**Comment by tanviraumi** [comment]
Closed with #5909
