### ISSUE TITLE
Move InsecureUrlResolver to better place

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5917]
Move InsecureUrlResolver to driver-utils or some similar place.
packages/runtime should have zero references to IUrlResolver or IResolvedUrl.

**Comment by curtisman** [comment]
May be `test-driver-utils`?

**Comment by kenluck2001** [comment]
Please assign this ticket to me. I have started working on it

**Comment by kenluck2001** [comment]
> May be `test-driver-utils`?

It seems that it is already in `packages\runtime\test-runtime-utils\src\insecureUrlResolver.ts`
