### ISSUE TITLE
Use "reason" field for Summarizer logs instead of "message"

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5946]
Let's try to converge on "reason" as a common field across events, and avoid using "message" since it's vague/antiquated (now we have structured logs!)

**Comment by anthony-murphy** [comment]
can this move to next?

**Comment by markfields** [comment]
Yeah whatever

**Comment by markfields** [comment]
I think @arinwt fixed this with some recent refactoring?
