### ISSUE TITLE
Ensure build version for shortcode asserts is explicit in the logs

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5947]
Shortcodes can change from build to build. So on its own a shortcode may not be enough to indicate where the error occurred.

Furthermore, different parts of the code can be at different builds in a single session (e.g. loader v. runtime), and there's no indication of which layer a tagged line is in.

Proposal: Add an address space to the shortcodes that indicates which layer it's from, so we can coordinate with the build version property in the logs (e.g. loaderVersion v. runtimeVersion)

**Comment by markfields** [comment]
@vladsud, @anthony-murphy, @curtisman  - This feels really important for our GA release to me.  I think it's a quick fix - Implement `assert` in each "layer" (loader, runtime, driver?) and `|` in a tag like 0x1000, 0x2000 or 0x3000 for each layer so the shortcodes don't overlap across layers, and we know which `fooVersion` field to check in the logs.

Or would it work to import `packageVersion` in each implementation of `assert` and add a column `assertVersion`?

**Comment by curtisman** [comment]
I thought short code are checked in and won't change version to version?   What does the work flow looks like right now?

**Comment by markfields** [comment]
I'll have to look again at how it works. I'm imagining a scenario where a tagged assert is deleted from one layer and an untagged assert is added somewhere else, and reuses that tag.  Maybe that can't happen.

Ok here's a more realistic scenario - some code gets copied from one layer to another, tags and all.

**Comment by vladsud** [comment]
I do not think adding layer tag would help. It might scope the problem (if it exists) to smaller problem, but fundamentally it does not change the problem of moving code around or copying inside one layer.

If problem exists, I'd look into minimizing it in tagger, i.e.
- for removed tags, do not reuse them for some time (this requires some kind of storage / database)
- for duplicated tags, use prior data to resolve which tag stays and which one gets changed.

Overall, this is not unique problem - devmain has exactly same constraints (though it does use DB for tracking and minimizing impact of user operations), but one thing developer has at his/her disposal - using exact branch of code where assert originates from. It does mean that we occasionally need to slice data by versions, but in my experience that's not a big deal (especially if tooling attempts to do its best to preserve tags and resolve duplicates correctly).

**Comment by anthony-murphy** [comment]
We don't reuse tag in and they are globally unique. Currently we scan the code base to find the highest, and increment from there. if the n largest are removed we would end up reusing those. if we are worried about that scenario, we can start stamping the last number is file somewhere.

**Comment by anthony-murphy** [comment]
I'm personally not too worried about the highest code reuse problem. for it to happen a code would need to be added and removed before another code is added. this seems unlikely, and in that case the original code wasn't around very long

**Comment by markfields** [comment]
Ok.  I am willing to close this.  The scenario where we'd be stuck is if someone cuts and pastes and then changes the condition but keeps the shortcode.  We should keep an eye out for this in PRs - don't reuse shortcodes if you're materially changing the condition.

I'm trying to think about where dev docs for this should go.  Maybe the repo wiki...?
