### ISSUE TITLE
Automate the Daily Report for internal team metrics tracking

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5977]
On the FF team at Msft, we manually query for top metric health each day.  This should be automated, including both MS Office usage data and our own synthetic data.

**Comment by chensixx** [comment]
Report is complete and published but unable to refresh due to an error. I'm working with the power bi support team to resolve the issue.

**Comment by chensixx** [comment]
link : https://msit.powerbi.com/groups/9ce27575-2f82-4689-abdb-bcff07e8063b/reports/2ec09d3e-12d4-4642-bbb6-0e02e6971ca2/ReportSection

**Comment by chensixx** [comment]
the connector for auto refresh is updated but because our data is dynamic, power bi sometimes produces errors when refresh, working with the support team again

**Comment by chensixx** [comment]
closing but will follow up with Tony for next steps
