### ISSUE TITLE
Tinylicious reuses state in temp folder between processes

### ISSUE THREAD

**Issue by rsullivan00** [microsoft/FluidFramework#5988]
### Issue Category

- Incorrect/Outdated information
  - [**Link to page**](https://github.com/microsoft/FluidFramework/blob/cd3c8a8f3419f0dd3f68fba4f73024dfad4a12e8/server/tinylicious/README.md)

### Details

Tinylicious seems to not actually run "in memory" in the way I would interpret that part of the documentation. When I:

- Run `npx tinylicious` (runs version `tinylicious@0.4.21640`)
- Add some data to a connection
- Copy one of the GET requests for a commit
- Stop the tinylicious process
- Restart the tinylicous process
- Resend the copied commit GET request

I would expect the data to no longer exist in the new process, but it does, I assume because I can find the commit in `/var/tmp/tinylicious`.

```bash
$ ls /var/tmp/tinylicious/tinylicious/.git/objects/7b/09ae11e428ecadcd9fe0779562ef04cafd18e8
/var/tmp/tinylicious/tinylicious/.git/objects/7b/09ae11e428ecadcd9fe0779562ef04cafd18e8
```

I'm assuming this is a documentation ambiguity, but it's possible this is a bug. **Is this the intended behavior for Tinylicious?**

I have been manually deleting `/var/tmp/tinylicious` between restarts to start from an empty state, which is cumbersome and unexpected from how I interpreted the README. I checked that the behavior is the same on Powershell as well as WSL2 + Ubuntu 20.

**Comment by tylerbutler** [comment]
@skylerjokiel Who's the best person to take a look at this?

**Comment by kevindiclemente** [comment]
gentle ping on this one

**Comment by kevindiclemente** [comment]
maybe could be nice to have a config option for ephemeral use case for testing

**Comment by tylerbutler** [comment]
This should stay open.
