### ISSUE TITLE
ODSP: Sharing link redemption need to have fall back

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5994]
Today, when we call TreesLatest, we support workflow where sharing link is provided such that ODSP could redeem it and return TreesLatest in one call.
Due to some issues, redeem portion of the process could fail and return 403, if person A who opened a document never opened any sharing link shared by user B who produced that link.
The ask is for 403 to always try old flow to redeem link ourselves and follow up with TreesLatest.
Once pair of B -> A sharing (of any document) happens, any future redeeming (including different documents) would work through existing single call mechanism.

We are following up if this is considered GA blocking and needs to be ported into 0.39

**Comment by vladsud** [comment]
Here is the spec for original work:
https://microsoft-my.sharepoint-df.com/:w:/p/hanfliu/EdTC38G80f1PqDqk72Olj7IBFpilu2BfaFkJPAzfY2EXGg

And I'm realizing that maybe initial work was never implemented in the first place? In that case, it's not really a bug (yet), more as FYI, and we need to open original work issues

**Comment by vladsud** [comment]
Actually, both fetchSnapshot() & fetchSnapshotCore() have this code, so it's already in:

        if (this.redeemSharingLink) {
            formParams.push(`sl: ${this.redeemSharingLink}`);
        }

And per discussion with Ben, that's GA blocker, so we need to add fallback logic and get it into 0.39 ASAP.
@jatgarg , any chance you can take care of it?

**Comment by jatgarg** [comment]
Yes, I will work on it from tomorrow.
