### ISSUE TITLE
Implement single URL request for file creation + sharing link (ODSP)

### ISSUE THREAD

**Issue by jbissat** [microsoft/FluidFramework#5995]
ODSP now has a single URL we can hit to do file creation and to get the sharing link back.
Note that the two-link approach needs to be preserved for the cases where sharing link redemption fails (see item https://github.com/microsoft/FluidFramework/issues/5994)

**Comment by tylerbutler** [comment]
@vladsud @jbissat Does this have the same delivery "deadline" as #5994?

**Comment by vladsud** [comment]
@tylerbutler , not that I'm aware of, but @jbissat  would have more data here.
It's a new feature, so I think it's just too late to try to bring it in through release process - it should land whenever it is ready, Jade is working on it as I understand.

**Comment by jbissat** [comment]
@tylerbutler I don't believe it does - @jatgarg #5994 should go in ASAP to avoid issues but this is not as urgent, correct?

**Comment by jatgarg** [comment]
I don't think this has any urgent deadline. Now with #5994 too, we will add this asap but this(5994) no hotfix anymore as the host will add a fallback for now at their end as driver change would take time to propagate.
