### ISSUE TITLE
$mol Destributed framework 

### ISSUE THREAD

**Issue by timeshift92** [microsoft/FluidFramework#6012]
## Feature
**Is your feature request related to a problem? Please describe.**

Hello, I saw this framework, and I wanted to show you another open source project on a clean typescript, if possible, it allows you to work in a distributed manner and also has its own collector that can tree shake

**Describe the solution you'd like**
Microsoft can be implemented this framework
https://github.com/hyoo-ru/mam_mol

**Comment by tylerbutler** [comment]
@timeshift92 Thanks for sharing this! Since this doesn't represent an issue, it will be closed soon, but we do review closed issues for feature requests and suggestions.
