### ISSUE TITLE
Document the behavior of createSubDirectory if the same name subdir already exists.

### ISSUE THREAD

**Issue by dineshkwal** [microsoft/FluidFramework#6015]
### Issue Category
- Can't find an answer to a specific question

### Details

https://fluidframework.com/docs/apis/map/shareddirectory/#map-shareddirectory-createsubdirectory-Method
`SharedDirectory::createSubDirectory` doesn't document what is the behavior when the same subdir already exists. Does it return the existing subdir in that case or creates a new subdir instead?

**Comment by tylerbutler** [comment]
@ChumpChief Can you answer this?
