### ISSUE TITLE
Container closes without proper error.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6027]
We do see in telemetry "**Storage service disposed!!**" errors.
Looking closer, most of these happen through _**fluid:telemetry:Container:ContainerClose**_
And looking at number of sessions, most of them are result of failure to fetch snapshot (**_fluid:telemetry:OdspDriver:ObtainSnapshot_cancel_**). Some of them have specific error (like 404), but many have empty error.

So it sounds like two things needs follow up:
1. We need to ensure that snapshot error message propagates to container correctly (it's not clear why it's not the case).
2. Investigate when some of the snapshot fetches do not have any error.

here is the stack that results in container closure and wrong message:

    at Dn (https://cdn.fluidpreview.office.net/fluid/prod/hashed-assets/sourceless-iframe/index.bundledDriver.f0cb835db608ce94674e.js:2:203860)
    at ao.checkStorageDisposed (https://cdn.fluidpreview.office.net/fluid/prod/hashed-assets/sourceless-iframe/index.bundledDriver.f0cb835db608ce94674e.js:2:219314)
    at https://cdn.fluidpreview.office.net/fluid/prod/hashed-assets/sourceless-iframe/index.bundledDriver.f0cb835db608ce94674e.js:2:218495
    at so (https://cdn.fluidpreview.office.net/fluid/prod/hashed-assets/sourceless-iframe/index.bundledDriver.f0cb835db608ce94674e.js:2:217355)
    at async To.getVersion (https://cdn.fluidpreview.office.net/fluid/prod/hashed-assets/sourceless-iframe/index.bundledDriver.f0cb835db608ce94674e.js:2:259037)
    at async To.fetchSnapshotTree (https://cdn.fluidpreview.office.net/fluid/prod/hashed-assets/sourceless-iframe/index.bundledDriver.f0cb835db608ce94674e.js:2:269127)
    at async To.load (https://cdn.fluidpreview.office.net/fluid/prod/hashed-assets/sourceless-iframe/index.bundledDriver.f0cb835db608ce94674e.js:2:259884),

I believe # 1 might be related to https://github.com/microsoft/FluidFramework/pull/5914
I.e. retry storage adapter might be responsible for looping here after initial error.
But it's not clear how storage get disposed without generating non-retryable error.

Example of the session:

union Office_Fluid_FluidRuntime_*
| where Session_Id == "1c7bacb2-1bf7-4529-80d2-ba2bba86923e"
| project Event_Sequence, Event_Time, Data_eventName, Data_error, Data_stack, Data_hostName

And here is the session without error on TreeLatest:

union Office_Fluid_FluidRuntime_*
| where Session_Id == "0964fa28-96cf-4d8f-92c5-81fdb9c22894"
| project Event_Sequence, Event_Time, Data_eventName, Data_error, Data_stack, Data_hostName

**Comment by vladsud** [comment]
Keeps causing a lot of trouble and misunderstanding as it pops up into a lot of alerts, queries, so bumping priority by moving into May

**Comment by markfields** [comment]
following 👀

**Comment by vladsud** [comment]
I no longer see that many cases on container load/closure path - all existing issues are either on summarize path (opened issue references above) or from 0.38-0.39 loader (just couple instances).
I have a theory that it was related to this period of time when connection to websocket was happening too early in boot sequence (by mistake) and was causing other troubles. It actually matches what I see in those few sessions.

That said, it's not clear how we get that error into Container.close() as storage is disposed by Container.close() itself, and it prevents reentrancy, so there should no way to get such error into logs (i.e. only Container.close() disposes storage, and it would not allow reentrancy at that point).
Error is raised only by RetriableDocumentStorageService

I also do not see any cases of TreesLatest_cancel having empty error any more.
Given no more repro, it would be very hard to figure out what happened. In future, we can instrument calls to dispose() and thus capture if someone else (other than Container.close()) was able to call it and put Container into this situation.

But as of now, this is not actionable bug, so closing.
