### ISSUE TITLE
Deprecation of existing flag (storage)

### ISSUE THREAD

**Issue by tanviraumi** [microsoft/FluidFramework#6033]
Currently, a Fluid client receives an existing flag after connecting to the ordering service. We used to have it for two reasons: code proposal and component instantiation. Given that we handle those scenarios differently now, client should not need to rely on the dependency anymore.

From @vladsud: We must ensure though that all code paths are removed from loader that assume creation of files through establishing connection to ordering service. For example, we have this today: (https://github.com/microsoft/FluidFramework/blob/main/packages/loader/container-loader/src/container.ts#L1187)

Once client can remove the dependency, service can stop sending it and we can remove the flag from IConnectionDetails interface.

Part of https://github.com/microsoft/FluidFramework/issues/3429

**Comment by vladsud** [comment]
@andre4i - this is related, but not exactly the same as the item I've described to you. But it gives some extra background of area.

@skylerjokiel - this particular item needs someone to access current state of UTs / automation and ability to remove legacy paths that we should not be using (creation of files on the fly by calling loader.resolve(). Curtis' team unlikely to have time here any time soon. I've left comment in @micahgodbolt 's PR of not adding ifs around this flow but rather addressing this problem directly - sounds like aliened with what what your team is doing.

**Comment by tanviraumi** [comment]
FYI @GaryWilber for visibility

**Comment by vladsud** [comment]
Coping relevant comments from #1943 and closing it as dup of this task:

This does not allow us to always start with view-only connection - see big comment above that line:
    const connectionArgs: IConnectionArgs = { mode: "read" };

We should simply remove this code (of loading file without snapshot) and always connect as view-only (or rather, rely on correct defaults, i.e. not specify anything to connectToDeltaStream()).
