### ISSUE TITLE
Move NoDeltaConnection out of deltaManager into driver layer

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6050]
I feel like (with addition of https://github.com/microsoft/FluidFramework/pull/6008/files) we are adding more concepts that DeltaManager needs to know about, which is against it being simple and small, and move complexities into up & down the stack (driver and container runtime).

Looking at how it is used, I believe it can be returned from driver and remove any need for DeltaManager to know about.
The only place where it's not the case is readOnlyInfo() and storageOnly. I feel like the way it's done today is not sufficient and needs to be revisited - likely host would want to know why it's storage only, and that can be generalized to "why it's readonly" (permissions part), and likely can be a string or equivalent of error code (still a string) that is propagated from driver to host without DeltaManager needing to know much about it. This opens also more scenarios for driver to differentiate in other places, like sharing link without write access vs. file itself being locked (and different types of locks, like read-only vs. storage-only vs. maybe something else).

@wes-carlson - FYI

**Comment by anthony-murphy** [comment]
This makes sense to me. I'd like to see NoDeltaStream just removed and for the deltamanger to support undefined connection likely via something like you describe above but we need to produce a design for how the driver communicates this
