### ISSUE TITLE
Property demos breaking incremental build

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#6068]
I'm seeing the following build/pack every time using `npm run build:fast` despite no changes:

- `@fluid-experimental/schemas`
- `@fluid-experimental/property-inspector`
- `@fluid-experimental/property-inspector-table`
- `@fluid-experimental/partial-checkout` 

I looked briefly and noticed the following that seemed suspicious, but couldn't find an immediate fix:

- schemas and property-inspector-table specify `"baseUrl": "."` in their `tsconfig.json`, which most of our packages do not
- schemas has a `/built` checked in that doesn't seem to be build output (the normal build outputs to `/dist`).  Maybe this was just a mistake?
- Lots of import cycles in these packages (e.g. schemas `index.ts` <-> `schemasRegisterer.ts`)

Hoping someone more familiar with the build/pack of these can take a look.

**Comment by tylerbutler** [comment]
@DLehenbauer @arno-123 Do you have suggestions for who can look at this more closely?

**Comment by DLehenbauer** [comment]
I'll take it.

**Comment by arno-123** [comment]
@nedalhy PTAL

**Comment by DLehenbauer** [comment]
It's 100% us. :)

Fix in #6326.

**Comment by ChumpChief** [comment]
Reopening, this is still happening in recent main.

**Comment by ChumpChief** [comment]
@DLehenbauer FYI

**Comment by arno-123** [comment]
@ruiterr 
@nedalhy 
@karlbom 
@evaliyev

**Comment by DLehenbauer** [comment]
I suspect we just haven't released a new official version in a while.  I can publish and move us to a prerelease of 'fluid-tools' this afternoon.

@ChumpChief - In the meantime, this should work: 
```sh
pushd tools/build-tools
npm run build
popd 
node tools/build-tools/dist/fluidBuild/fluidBuild.js
```

**Comment by ChumpChief** [comment]
Thanks Daniel, that seems to be the case, workaround works for me.

**Comment by DLehenbauer** [comment]
Fixed.
