### ISSUE TITLE
Separating protocol from service packages

### ISSUE THREAD

**Issue by tanviraumi** [microsoft/FluidFramework#6073]
The goal is to extract “protocol-base” and “protocol-definition” packages from the service monorepo. We will create a top level “protocol” folder and move these two packages there (just like the common folder). 

Once done, service and client can take a dependency on the published packages. The pros are, we will only bump those packages when needed and breaking changes will be easier to track. The cons are, it makes development story harder since we need to update and publish those packages first before we can consume them. However, this additional complexity also forces us to be more deliberate when making breaking changes.

Roughly, the steps of this migration are the following:

1. Create a top level 'protocol' folder and move these two packages there.
2. Set up a build pipeline and publish those two packages. Pre-release should be fine.
3. Update all code with the new pre-release dependency.
4. Update fluid-build to account for the repo structure.
5. Delete existing packages from server mono repo.

**Comment by tanviraumi** [comment]
FYI @GaryWilber

**Comment by tylerbutler** [comment]
I think you should also include updates to fluid-build to account for the new repo layout.

**Comment by tanviraumi** [comment]
> I think you should also include updates to fluid-build to account for the new repo layout.

Great point! Updated the description

**Comment by SamBroner** [comment]
Should we also move @fluidframework/gitresources? It's also included in the runtime.
