### ISSUE TITLE
Stress tests are too noisy: fluid:telemetry:SummaryStatus:Behind

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6082]
> cd packages\test\test-service-load
> npm run start 

Result:
A lot of fluid:telemetry:SummaryStatus:Behind errors.
it would be great to figure out what's going on and make it less noisy.

You can use [this commit](https://github.com/vladsud/FluidFramework/commit/fc70cfac23b96c16dff976166eb248196855f534) from [this branch](https://github.com/vladsud/FluidFramework/tree/ScalableTests_NoNoise) to see all the other changes that help keep it reasonable.

**Comment by anthony-murphy** [comment]
i'm aware of this and need to investigate i. this should only fire when a container has had more than 3000 ops without summary attempted

**Comment by anthony-murphy** [comment]
@vladsud i think you fixed this. correct? or is it still happening even after your changes

**Comment by vladsud** [comment]
Well, sort of. I fixed two issues that were causing really long waits between summaries.
I think main ("ci" profile) is Ok.
I can easily hit this issue with higher loads.

Either way, I think it's fine to close it, but it's not fully gone - I think we would need to continue to push stress tests to their limits, and work with ODSP on speeding up whole summarization process, as it's (overall, from numbers) is very unpredictable, and thus  easy to hit these issues.
