### ISSUE TITLE
Stress tests are too noisy: Asserts in taskManager.ts

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6083]
> cd packages\test\test-service-load
> npm run start 

Result: A lot of these asserts are hit:
                assert(pendingOp !== undefined, 0x07b /* "Unexpected op" */);
                assert(pendingOp !== undefined, 0x07d /* "Unexpected op" */);
It would be great to figure out what's going on and make it less noisy.

You can use [this commit](https://github.com/vladsud/FluidFramework/commit/fc70cfac23b96c16dff976166eb248196855f534) from [this branch](https://github.com/vladsud/FluidFramework/tree/ScalableTests_NoNoise) to see all the other changes that help keep it reasonable.

**Comment by anthony-murphy** [comment]
@ChumpChief curious if you will get to this, or if we should load balance. would be nice to remove noise from stress, with the eventual goal of considering all errors as failing the run

**Comment by ChumpChief** [comment]
It's on my list but not at the top, happy for it to be load balanced.  Earliest possibility for me would probably be late June early July.

**Comment by anthony-murphy** [comment]
June early July! ha :) adding this to the jan milestone
