### ISSUE TITLE
Stress tests are too noisy: warnings about deprecated leader election

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6084]
> cd packages\test\test-service-load
> npm run start 

Result: A lot of these warnings are on screen:
            console.warn("ContainerRuntime with AgentScheduler built-in is deprecated, "
                + "see BREAKING.md for more details and migration instructions");

It would be great to figure out how not to have them on the screen (maybe stress test runner should not print them?)

You can use [this commit](https://github.com/vladsud/FluidFramework/commit/fc70cfac23b96c16dff976166eb248196855f534) from [this branch](https://github.com/vladsud/FluidFramework/tree/ScalableTests_NoNoise) to see all the other changes that help keep it reasonable.

**Comment by ChumpChief** [comment]
I think this might be resolved by my recent change to the options matrix plus flipping the flag default, confirming now.
https://github.com/microsoft/FluidFramework/pull/5833/files#diff-646225b0acb58b92a0fa191e720c3a93141c9b9eeeb67d19a450ab170d082de2L44

**Comment by vladsud** [comment]
@ChumpChief , yes confirming it's resolved. Leaving to you to resolve it :)

**Comment by ChumpChief** [comment]
Done, thanks for confirming!
