### ISSUE TITLE
Shared Interval Programmability: Ability to iterator over shared intervals

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#6107]
## Work Item
**Describe the outcome you expect**

Iteration over the contents of an IntervalCollection will be supported by an iterator object. The object returned by the [Symbol.iterator] method will support JS-style for...of. We'll also support iterating, either forward or backward, over all intervals in the collection with a given start or end position. Iterator objects that support this "special" iteration are returned by additional methods Create[Forward,Backward]IteratorWith[Start,End]Position.

**Approach**

Construction of the IntervalCollectionIterator will take optional forward/backward direction (forward is the default) and start/end position. On construction, we'll walk the underlying tree and collect intervals that match the iteration criteria in an array. The iteration direction will be reflected in the order of the elements in the array. The next() method of the iterator object will walk this array. This will keep the next() method simple, and iteration will follow snapshot semantics, i.e., changes to the collection during iteration will impact iteration.

**Open questions**

There is currently no underlying tree that contains all intervals and is sorted by end position. So whereas finding all intervals with a given start position can walk just the portion of the tree that may contain matches, looking for intervals with a given end position has to walk the entire tree. If this impacts the performance of iteration, we can revisit.

**Additional context**
https://github.com/microsoft/FluidFramework/issues/5427, https://github.com/microsoft/FluidFramework/pull/6202

**Acceptance criteria**

Word's iteration needs are met with acceptable performance.

**Comment by pleath** [comment]
Fixed by https://github.com/microsoft/FluidFramework/pull/6202.
