### ISSUE TITLE
Shared Interval: Functionality: Support multiple intervals on a range

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#6109]
**Describe the outcome you expect**

Whereas we currently keep at most one interval with a given (start, end) in the collection, we'll now allow any number of intervals with the same (start, end). The local delete(start, end) operation will now delete _all_ intervals with the given (start, end). 

**Approach**

The interval ID will be used as a third key to break ties, so collections will still have a well-defined order. Iteration will follow this order. Add and delete ops will be sent over the wire with an ID so that ID's are consistent across clients. So a local delete(start, end) will result in a unique delete op on the wire for every interval that's deleted. 

**Open questions**

**Additional context**
https://github.com/microsoft/FluidFramework/issues/5427

**Acceptance criteria**

Word's programmability needs should be met.

**Comment by pleath** [comment]
Addressed by #6407.
