### ISSUE TITLE
Shared Interval: Functionality: Support well nested and non-well nested intervals

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#6110]
**Describe the outcome you expect**
Intervals in a collection are all visited by iteration, in the expected order, regardless of nesting, overlapping, etc.

**Approach**

**Open questions**

**Additional context**
https://github.com/microsoft/FluidFramework/issues/5427

**Acceptance criteria**

**Comment by pleath** [comment]
This seems to work properly. Word will confirm once they have a package containing the change for #6107.
