### ISSUE TITLE
Shared Interval: Programmability: Event on property changes on shared intervals

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#6111]
**Describe the outcome you expect**

We will provide a hook that can be used to execute user code when an Interval's properties change, as a result of either a local or a remote op.

**Approach**

The event will be associated with an IntervalCollection. The data passed to the event will be the current (changed) state of the interval and a structure containing the previous values of the changed properties.

**Open questions**

Alternatively, the event could be associated with the client. This would cause the same code to be executed for all collections in the client, which may not be desirable, but it would get rid of the need to hook an event to every collection individually.

**Additional context**
https://github.com/microsoft/FluidFramework/issues/5427

**Acceptance criteria**

**Comment by anthony-murphy** [comment]
Something similar exists on sequence/shared string. I think we should model this in a similar way:
https://github.com/microsoft/FluidFramework/blob/35002bd351a4b1e4f8062e41cfec3fc48e2d73d9/packages/dds/sequence/src/sequenceDeltaEvent.ts#L141

**Comment by pleath** [comment]
Moving this out to August, as the priority has been reduced, and there won't be time for it in July.
