### ISSUE TITLE
API: Consider eliding internal methods from *.d.ts

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#6116]
## Work Item
API-extractor omits APIs tagged with `@internal` when generating documentation.  However, these APIs still appear in the published *.d.ts files.

@taylorsw04 tells me that in addition to extracting documentation, API-Extractor can produce a filtered *.d.ts that elides internal methods.

Currently, SharedTree is the primary user of `@internal` in our code base, although there is light usage elsewhere.

**Comment by taylorsw04** [comment]
https://api-extractor.com/pages/overview/demo_rollup/ :)

**Comment by curtisman** [comment]
Typescript already has a [`--stripInternal`](https://www.typescriptlang.org/tsconfig/#stripInternal) flag.   However, quite a bit of our `@internal` functions are still cross package, and I don't think it will work for dependent package if you strip them out.
