### ISSUE TITLE
Lack of PerformanceEvent's _start events makes it hard to diagnose / debug issues by developers

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6160]
PerfornanceEvent constructor has these defaults now:

```typescript
    protected constructor(
        private readonly logger: ITelemetryLogger,
        event: ITelemetryGenericEvent,
        private readonly markers: IPerformanceEventMarkers = {end: true, cancel: "generic"},
    ) {
```

I.e. no start: true.
This was done earlier to reduce impact on telemetry COGS.
We still want this change, however it proved very difficult to do local debugging of async processes (like summarization) when no start events are printed to console.

I think we need a mechanism to enable them.

What I'd propose is that there is a mechanism to mark some events as verbose (including this case, i.e. convert _start_ from boolean to type of event - verbose or not, similar to how _cancel_ works now), and then have a logger adapter that can drop verbose events, and inserted at the front of the chain (likely not even used in FF repo, just an instruction for consumers to wrap whatever logger they are using with this adapter).

**Comment by ksbrar** [comment]
@vladsud I can take this on.

**Comment by vladsud** [comment]
Super - thanks! Might be worth running the design by Monday's meeting, just to make sure folks had a chance to provide feedback (and learn about this new capability if we go with it)

**Comment by markfields** [comment]
Moving to July, still considering the design.

**Comment by markfields** [comment]
What I would suggest is to add a new category (alongside `generic`, `error` and `performance`) called `verbose`, and set that on the start events and anything else we don't want to collect by default in prod but otherwise do want flowing through our own logger chain.

Removing my assignment - if gets punted past September I'm happy to reconsider this when I'm back from leave.

**Comment by markfields** [comment]
Responding to @vladsud's suggestion to use `TelemetryDataTag` stuff - I don't think that's well-suited for this, that's at a per-property level, this ask is at a per-event level.

**Comment by vladsud** [comment]
Closing old issues.
