### ISSUE TITLE
Move protocol-base to common folder.

### ISSUE THREAD

**Issue by tanviraumi** [microsoft/FluidFramework#6170]
Checkout #6073 and #6167 for more context.

While the protocol-base contains some definitions that should should move to protocol-def, it still holds some implementations (e.g., Quorum) that are shared between client and server for protocol specific guarantees. The question is: should we move protocol-base to common folder (along with protocol-def) or we have a better alternative?

**Comment by tanviraumi** [comment]
@curtisman @anthony-murphy

**Comment by anthony-murphy** [comment]
I was thinking about this, and i'm not sure protocol-base belongs in a separate layer. As it doesn't have any requirements beyond any other dds, and the interface is fixed via the protocol definitions change. There may be value is decoupling server and client, but that would require more than just protocol-base given the routerlicious driver reuses a bunch of the server's code

**Comment by tanviraumi** [comment]
I think there is a difference between other service packages used by client (e.g., services client) and protocol-base. Other service packages contains utils and libraries that both client and service share (e.g., shared rest client code).

Protocol-base contains code that affects data and protocol. For example, quourm code that runs in scribe and client. It also contains some shared summary creation code. So this package is much more vulnerable for accidental breaking changes, and moving it will make the upcoming changes more deliberate IMO.

**Comment by anthony-murphy** [comment]
i don't disagree, but it's really no different than any other dds if you consider the server just another client. i don't see unique challenges here, and there is a cost associated with moving it. this is very different than our definitions which break compatibility between layers of the stack if they are changed.

**Comment by tanviraumi** [comment]
The difference with any other DDS is, service takes a dependency on this DDS for booting up. Especially now that client will start writing quorum for push and push will have to start their service based on that.

I am not sure what additional cost you are referring to with this move.

**Comment by tanviraumi** [comment]
Also I feel like we are talking about different types of compatibility. For protocol-base, I am not concerned about interface compatibility. We can move most of those to protocol-def anyway. I am mostly concerned about summary data compatibility and want us to be more deliberate before changing.

**Comment by tanviraumi** [comment]
Can we get a resolution on this? @SamBroner reminded me that we also have "gitresources" package which defines storage specific interfaces. I think we should move that one as well. If reusing common seems awkward, we can move all three into a top level protocol folder.
