### ISSUE TITLE
Remove wait<> on directory and map, since they are hard to debug if they cause deadlock due to runtime being disposed

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6188]
[ChumpChief] Per conversation below, the current plan is to remove the wait methods from map and directory.  For current customers, we can publish a helper function snippet in BREAKING.md they can pick up to match existing functionality, with encouragement to consider timeouts/telemetry/failure logic appropriate to the customer's scenario.

- [x] Deprecate the APIs and remove all local usage from the repo #8663
- [x] Remove the APIs #8744

### Original issue

I run it with our stress tests where wait() hung process forever.
The container runtime was disposed, so no op processing was happening and that deadlocked the run.
It was pain in the butt to figure it out.

I'd propose to fail all infinite waits like that - we already check - see verifyNotClosed() methods (as an example in Container Runtime)

**Comment by curtisman** [comment]
We should review all "wait" functionality to see if they are really needed (and get rid of them) or add abort to them.

**Comment by ChumpChief** [comment]
I'm still in favor of removing `.wait()`s :)

**Comment by curtisman** [comment]
Definitely what I prefer as well.  Just need to make sure to have alternative for scenarios that currently relies on waits.
