### ISSUE TITLE
ISharedCounter to implement set() operation

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6191]
I find it pretty limiting that the only thing you can do with ISharedCounter is InterlockedAdd equivalent.
For it to be powerful DDS, it needs to support at least a bit more from the arsenal of atomic operations (see std::atomic in C++, or Interlocked* APIs in Windows).

In particular, I think set(), and CompareAndSwap (CAS) are the two operations that would be great to add.
Otherwise we will see code like that (just ugly, leaving aside correctness of the whole flow):

                await LoadTestDataStoreModel.waitForCatchup(runtime);
                ...
                counter.increment(-1 * counter.value);

**Comment by vladsud** [comment]
I've marked "design required" to make sure we run it by wider group that it's a good change to have, but also if we want to limit wit set() only or want to add more methods.
Otherwise it's likely good first issue for someone who want to familiarize with DDSs. It's a bit more work than with other first issues, but someone new can be guided to success here.

I'm not sure June milestone is correct - there is no urgency here IMHO

**Comment by ChumpChief** [comment]
I'm not particularly a fan of this idea -- the SharedCounter doesn't have any real customers, so IMO its primary value is [illustrating an alternative approach ](https://fluidframework.com/docs/advanced/dds-anatomy/#conflict-avoidance) to conflict resolution (ensuring the op vocabulary is order-agnostic).

If we wanted such a data structure I think it would be better to implement as a specialized SharedCell (which aside from already having set(), also already has the necessary tracking for pending ops).  But I would defer that until we have a demand (which is honestly probably unlikely).

**Comment by vladsud** [comment]
Here is the place where it would be useful:
https://github.com/microsoft/FluidFramework/blob/main/packages/test/test-service-load/src/loadTestDataStore.ts#L145

It feels like we position it as an example of the area that has (for all practical purposes) only one solution, i.e. I have hard time coming up with any other example of DDS or scenario where order would not matter.

New DDS is fine, but I wonder about implications in broader context of how we roll new DDSs. Alternative to having very specialized DDSs (many of them) is smaller set of powerful (covering many scenarios) DDSs. What's missing I believe is a way to apply policies / limit API surface in some structured way such that it's not possible to perform certain operations or allow different outcome for those operations (and by doing so - essentially creating new DDS from POV of having its own factory type). For example, construct a version of map that does not have clear method on it (if that's desired for given scenario).
This desire to augment existing DDS to serve specialized scenario shows up in another places (specialization may include different merge policy, calculating state like assigning [sequential IDs](https://github.com/microsoft/FluidFramework/issues/4659) to markers in Sequence, etc.)
Semantically - it's new DDS no matter how you look at it, but it would be great for this process not to duplicate code and be simple to build variety with trivial changes.

**Comment by ChumpChief** [comment]
At a glance, that scenario should probably not be using a counter, and should be using a cell anyway.  The only normal call to increment is guarded behind `haveTaskLock` so it seems to explicitly NOT the want the compounded op application that counter provides.

Also is that reset condition ever met?  I'm looking at `runnerProcess()` and it looks like an unreachable condition?  Maybe I'm missing something though.

**Comment by vladsud** [comment]
Guards do not provide strong guarantee :)
Yes, the example as is today could use something else. It used to use map, it was changed to be a counter, and I think it's more inline with intention here. I believe reset is run when the first client in a group starts.

Let's assume we build new DDS that is super set of existing one. I'd think next natural step is deprecate the old one, as there is very little value in supporting both.

**Comment by atiqueahmedziad** [comment]
@vladsud can you please add some guidance how to proceed a fix for this one?

**Comment by ChumpChief** [comment]
Closing this item, as we're not currently investing in changes to SharedCounter.  Can revisit if we get a customer request for enhanced functionality.
