### ISSUE TITLE
Extract delay() implementation into common-utils

### ISSUE THREAD

**Issue by andre4i** [microsoft/FluidFramework#6212]
See [comment](https://github.com/microsoft/FluidFramework/pull/6209#discussion_r637022652) here: https://github.com/microsoft/FluidFramework/pull/6209.

There are a couple of places where the `delay` implementation is the same, it makes sense to make it reusable.

**Comment by vladsud** [comment]
It shows up in different forms:

> const wait = async (timeMs: number) => new Promise((resolve) => setTimeout(resolve, timeMs));
