### ISSUE TITLE
Enable Optional Error Type: DriverErrorType and ContainerErrorType

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#6214]
There is currently no safe way to add a new DriverErrorType within a release, as they cannot be added as optional. If we tried to add it in a dot build it would not exist in the older, and fully exist in the newer this would result in compile and runtime errors if code written against the newer were used with the older, this breaks our back compat guarantees.

https://github.com/microsoft/FluidFramework/pull/6187#discussion_r636053014

**Comment by anthony-murphy** [comment]
I think we probably want these to become `as const` objects: 
https://www.typescriptlang.org/docs/handbook/enums.html

**Comment by anthony-murphy** [comment]
`const enum` could be another good option:
https://www.typescriptlang.org/docs/handbook/enums.html

**Comment by anthony-murphy** [comment]
Fyi @DLehenbauer and @vladsud

**Comment by anthony-murphy** [comment]
Both `as const` and `const enum` will result in inlining, which has good and bad properites. we could also just switch from `enum` to object `{foo?: "bar"}` which will not inline, but does support optional members

**Comment by tylerbutler** [comment]
Are the options roughly equivalent in terms of intellisense/developer experience in VSCode?

**Comment by anthony-murphy** [comment]
@tylerbutler  they should be
