### ISSUE TITLE
Mark SparseMatrix as obsolete in TSDocs

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#6267]
SparseMatrix is obsolete.  I'd consider omitting SparseMatrix from the README.  Its replacement (SharedMatrix) is better in every way.

_Originally posted by @DLehenbauer in https://github.com/microsoft/FluidFramework/pull/6265#discussion_r640034764_

**Comment by narinderberi** [comment]
@tylerbutler could you please assign this to me. Thanks!

**Comment by narinderberi** [comment]
@tylerbutler I have not been able to spend cycles on this. Could you please unassign? Thanks!
