### ISSUE TITLE
Quorum cleanup: hide abilities to make/access arbitrary proposal values

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6274]
The `Quorum` currently permits users to store arbitrary key/value data via the proposal mechanism.  This is undesirable as it limits our flexibility in updating the code proposal mechanism, and we don't have a good schema upgrade story for the data stored within.  Instead, developers should create and use their own DDSs for arbitrary data storage.

This work tracks hiding access to the proposals for general use, such that the only expected proposal will be the code proposal and access to read/modify it is gated through and explicit API contract.

Step 1
- [x] #8036 

Step 2
- [x] Aid partners in removing direct usage of `Quorum` proposals

Step 3 (parallelizable)
- [x] #8039
- [x] #8044

**Comment by vladsud** [comment]
I believe we agreed that's in for 1.0, assigning to you to figure out a plan here

**Comment by ChumpChief** [comment]
Split this in two, see #8089 for the remainder.
