### ISSUE TITLE
Remove Merge Tree Registers

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#6321]
## Work Item
Related to #78. They are not currently supported, and we have no plans to immediately complete the support. so we should just remove what is currently there

**Comment by anthony-murphy** [comment]
releated to #6272

**Comment by narinderberi** [comment]
@anthony-murphy could you please assign this to me? Thanks!

**Comment by atiqueahmedziad** [comment]
@narinderberi are you still working on it?

**Comment by narinderberi** [comment]
@atiqueahmedziad, no. @anthony-murphy could you please unassign.
