### ISSUE TITLE
Storage handling in detach container across layers.

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#6342]
Please note that addressing this issue properly will likely mean introduction of storage object where previously we have not had one.
Note that we were already pretty bad at managing when we have storage and when we do not have it and transitions. I've added this comment in code- it's easy to see here by adding assert and hitting it right away:
```
    public get storage(): IDocumentStorageService {
        // This code is plain wrong. It lies that it never returns undefined!!!
        // All callers should be fixed, as this API is called in detached state of container when we have
        // no storage and it's passed down the stack without right typing.
        if (!this._storage && this.context.storage) {
            // Note: BlobAggregationStorage is smart enough for double-wrapping to be no-op
            this._storage = BlobAggregationStorage.wrap(this.context.storage, this.logger);
        }
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        return this._storage!;
    }
```

It would be great to re-evaluate how we deal with transitions of no storage -> storage, and in order to fix this bug it likely needs to be temp storage -> permanent storage.
For most part that can be abstracted from layers below by always giving storage object and doing switch under the covers, though it begs question - can we do it safely? Or it needs to be an addition (i.e. old blobs are always available, but now we gained write capabilities).
I guess first part on solving problems here - understanding how code works today and how we can remove eslint violation suppressions and make code work correctly with property types, learn and move to fixing this issue.

_Originally posted by @vladsud in https://github.com/microsoft/FluidFramework/issues/4746#issuecomment-785531139_

**Comment by vladsud** [comment]
Thanks for opening the issue! It would be great to populate it with your observations on how system works today RE these states (has no storage, has storage) and transitions, layer by layer (container runtime, data store, dds).
Are there any UTs we can write upfront to ensure that we capture all the interesting side-effects that have to stay the same as we modify the system, such that we increase the chances of discovering any places where we are modifying behavior unknowingly without noticing it? Any other ways we can ensure that we are not adding regressions as we change behaviors?

**Comment by jatgarg** [comment]
So the observation is that in loaded container, we always have storage. For detached container, the container/runtime, datastores contexts/runtimes never use or make any call to storage. For local channels in detached container, we do read read blobs from storage but we always expect the blobs to be already there in blobs from the snapshot and hence the calls does not make to actual storage and it makes sense as the blobs are required to be definitely present in the snapshot for ex for drafts. Missing blob would definitely point to some error.
The transition we are looking for is never actually made because we just pass the getter from container runtime to lower layers and they only make use when we know the storage would be there like in attached container and for rest we just the snapshot to read blobs in detached container as that is the only thing required in detached container.

**Comment by jatgarg** [comment]
So if we like pass a storage service like Blob cache storage service with blobs already present from detached snapshot(draft), and then replace the internal storage service used within BlobCacheStorageService with actual storage on attach, it should just work.

**Comment by vladsud** [comment]
Thanks! I assume this requires such storage (if we no longer use getter) to have all the original blobs even after we got real storage (due to potential delay loading).
Note hat current approach with getter is easy to break, because layers are free to cache result (not call it all the time). So it's not great place to be. Plus I believe our getter is happy to return undefined result when it's called in detached state :)
