### ISSUE TITLE
Remove `existing` state from Fluid Framework - framework

### ISSUE THREAD

**Issue by andre4i** [microsoft/FluidFramework#6348]
(work in progress)

See https://github.com/microsoft/FluidFramework/issues/3429 for details.

The goal here is to remove the state usage from the [framework layer](https://github.com/microsoft/FluidFramework/blob/main/docs/PACKAGES.md#framework) with regards to using the upstream dependencies and refactor as appropriate (split creation vs loading).

**Comment by vladsud** [comment]
Can you please clarify in title what you mean by framework? Do you mean Aqueduct? or something else?

**Comment by andre4i** [comment]
Sort of. I was referring to the layer: https://github.com/microsoft/FluidFramework/blob/main/docs/PACKAGES.md#framework
