### ISSUE TITLE
GC has rather big impact on snapshot size

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6371]
Looking at [Chapter 2.1 Collaborative Meeting Notes — Status](https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!BOyJN6Bkykm_L66EicZFaDKnQ_cydFFLqph8D-t_9vqaMsGC4Tm9RYec9Rh5aw3l&item=01N5X4JN43O5A76LTJGBCKUBJQDSGCUMTE&file=https:%2F%2Fmicrosoft.sharepoint-df.com%2Fteams%2FOfficeOnlinePrague&siteUrl=https:%2F%2Fmicrosoft.sharepoint-df.com%2Fteams%2FOfficeOnlinePrague) document, here is some interesting stats:
- Total number of summary blobs: 3.6Mb
- 567Kb out of that - catchUp blobs - something we should address (see https://github.com/microsoft/FluidFramework/issues/6364)
- 619Kb - gc blobs! That's 20% of total content if I exclude catchUp blobs

Granted this file has a lot of deleted content, and once we run sweep on it, sizes will reduce. But I expect percentage wise GC data to stay pretty high relative to useful content.

Is there anything we can do here to reduce burden on snapshot sizes?
Are there direct ways to reduce impact?

Can and should we write all this data as an attachment blob(s), such that it is excluded from snapshot and does not impact boot times? I believe it would work correctly in a sense of summarizing client always either reading these blobs or reusing in next summary, thus never running into situation where these blobs would be deleted by storage (today that can happen with other attachment blobs, and thus we ensure that all important blobs come in summary and cached by driver forever).

**Comment by vladsud** [comment]
It would be great to have a discussion on what we can do about it. 
And once / if we have a proposal, see who can help implement it.

**Comment by agarwal-navin** [comment]
I am not familiar with attachment blobs but we should definitely have a discussion.

**Comment by vladsud** [comment]
Attachment blobs have the following properties that differ them from snapshot blobs:
1. Each individual blob is uploaded and downloaded separately via http request.
   - There is general agreement that we want to add batching capabilities here in the future.
2. Attachment blobs are not included into snapshot payload, and thus have overall positive impact on boot, assuming their content is not needed on boot.
3. Because they are requested via individual request, such requests are cacheable by browser
   - i.e. images are loaded only once - rebooting document will result in image being provided by browser cache.
4. All blobs can be garbage collected by storage.
   - in case of SPO, it reclaims snapshots quickly, and thus any blob that was references in snapshot that given client loaded from might be deleted at some point in time.
   - We solve this problem for summary blobs by ensuring than all summary blobs are included in snapshot and cached by driver
   - Images (that use attachment blobs) could end up being gone in case client is way behind on ops and attempts to resolve an image. Code (on FF & Bohemia side) deals with it and app recovers quickly when it catches up (there is no longer such image in this doc).

**Comment by vladsud** [comment]
@marcmasmsft, @agarwal-navin, please take a look. This is not super urgent, but I'd love us to agree on high-level design and find a way to move forward here.

Here is a proposal making it possible to reduce impact of GC blobs to boot perf / bandwidth, solved via added generic building blocks that might be useful for other scenarios. It will allow only summarizer to download GC blobs, but do so in perfrormant way:
1. An API that allows client to **download multiple blobs** in fewer network calls (ideally - one).
   - From client perspective, no differences RE attachment or summary blobs
   - Server should be in position to return only subset of blobs requested. Client would follow up with more requests on as-needed bases
   - We should consider using new snapshot file format as a wire protocol for these responses. That said, it can be also used a staging for new format, i.e. a way to get new path going at smaller scale, as shipping multi-blob support would be easier than shipping snapshot format.
   - Request format should ideally be generic, supporting (in the future) ability to ask for combination of blobs, trees (with blobs) and/or full snapshot - all possibly added in the future on as needed bases, but format being flexible enough to allow such extension in the future. We might use it in the future for partial checkout (i.e. getting only sub-tree of the snapshot on boot).
2. An ability to specify **prioritization of blobs in a summary**:
   - I'd make it more generic than specifying attachment vs. summary blobs. For most part I want to keep that distinction abstracted away from client, and instead tell priority of blobs to be included in snapshot. For now, we could support only two priorities (guaranteed to be included into snapshot vs. possibly included or not - server could still include it into snapshot, but client can cope if it's not).
   - Over time, if / when we move to partial snapshots / skeleton, that mechanism can be used to querying partial data (though there is trade off between cached response vs. smaller response).
3. No new API will be added to runtime to request multiple blobs. Instead drivers supporting such API could defer fetch() to a continuation (end of JS turn) and as result batch all requests that come in given JS turn into single request
   - Validation is required to ensure that it would help in case of fetching all of GC blobs.
   - We can get batching (backup strategy via usage of rate limiter, though current limit is too high (24), i.e. client will make first 24 individual request before throttling any network requests and thus creating an opportunity for driver to batch them. This technique is even less efficient in drivers using http/2.0 where limits are much higher.

Alternative solution for this particular problem:
1. We can change GC processes to directly upload attachment blobs instead of using summary workflow.
   - this would add number of calls to SPO, and thus chances of being throttled.
2. We can do blob aggregation to reduce number of blobs, and thus reduce the need to have multi-blob read API.
   - This overall does not work well with current incremental summary upload where we do our best to not summarize paths that did not change. Moving to essentially single blob will substantially increase upload bandwidth requirements, unless we use some kind of differential compression that relies on content of prior blob.

We can also do nothing, and accept the cost of GC to bandwidth and boot perf, though at 20% impact to size that's rather big area to pass by.

**Comment by vladsud** [comment]
Multi-blob read is tracked as individual item - see #4590 - Design ODSP API for requesting multiple blobs

**Comment by agarwal-navin** [comment]
The proposal sounds good to me. Since #4590 is a pre-requisite for this, we should discuss with ODSP and get work started on it. I remember we discussed with Marcelo and he was on board.

**Comment by vladsud** [comment]
We will likely not have data before start of May, and I want to be data driven. Also, if data confirms GC blobs are large, we should look into that other item first about duplicate data.

So, moving it to June for now.

**Comment by vladsud** [comment]
We have data for GC blob sizes. I'm not sure if this data has PR #10016 fix. If it does not, then numbers will continue to shrink over time.

union Office_Fluid_FluidRuntime_*
| where Data_eventName == "fluid:telemetry:Summarizer:Running:Summarize_generate"
| where isnotnull(Data_gcTotalBlobsSize)
| extend blobs = Data_totalBlobSize - Data_gcTotalBlobsSize
| summarize count(), percentile(Data_gcTotalBlobsSize, 99)

P99 is at 248K
Average - 21K
P50 - 10K

Which is much better that what we saw before!

I'd suggest revised plan:
1. We need a fix for https://github.com/microsoft/FluidFramework/pull/10334. This is super important to get process to be more pay-per-play.
    - Once it's in and we have data (including data with above mentioned PR #10016, we will re-evaluate if we need to make any improvements here, including having multi-blob breakdown of GC data. I'd think (based on data we have) that should not be needed.
2. Mark GC blob as not to be returned in snapshot and run experiment with it. Including starting with our stress tests, and eventually shipping to production.

Note that TreesLatest (excluding Whiteboard)
- P99 is 2Mb
- average is 221K
- P50 is 81K

So not including GC blob in payload is still meaningful.
Though for each TreesLatest call that would add 0.2 calls to read GC blob (as that's how many summarizer sessions we have).

**Comment by vladsud** [comment]
I'll keep it on my plate to figure out next steps / funding.

**Comment by vladsud** [comment]
If I got it right, PR #10016 (see commit https://github.com/microsoft/FluidFramework/commit/f2dd3756892e4f3bfd8984e2e653472958835cae) went to [client_v0.59.3000](https://github.com/microsoft/FluidFramework/releases/tag/client_v0.59.3000)

And now we have more data that points out that gcTotalBlobsSize's P99 is above 1M:

Data_runtimeVersion | count_ | percentile_blobs_99 | percentile_Data_gcTotalBlobsSize_99
-- | -- | -- | --
0.59.3000 | 172,169 | 176,232 | 1,125,882
0.59.3002 | 605,387 | 278,560 | 1,578,004
0.59.2000 | 28,227 | 169,074 | 33,3012

If I look at GC blob in range of 1M - 1.5M, that corresponds (on average) to 1600 data stores. I.e. 1K bytes per data store.
That seems about right - I get 13.3K for a file with 4x4 table in it.
There are 71 DDSs, and thus word "outboundRoutes" contributes ~1K to size. Every ID repeats at least twice.
It compresses 7x.

**Comment by vladsud** [comment]
Key next steps:
- Understand how often we write out GC blob after recent changes: https://dev.azure.com/fluidframework/internal/_workitems/edit/609
    - Possible next step - breaking GC blob into more blobs (using some kind of stable partitioning) and leveraging multi-blob read to keep load perf & storage scale reasonable for summarizer client
- Exclude GC blobs from snapshots: https://dev.azure.com/fluidframework/internal/_workitems/edit/418

**Comment by agarwal-navin** [comment]
There are couple of ways we can compress the data written into GC blob. We should probably wait for the next steps outlined above before we go this route:
1. Create simple IDs (integers) for each node and add a simple ID -> real ID table in the GC data. However, there may be plans to switch data store / DDS to use compressed IDs similar to the ones SharedTree uses right? If so, this step is not needed.
2. Use small names for properties - `outboundRoutes` -> `o`. `unreferencedTimestampMs` -> `u`, etc. This will save us quite some space.

**Comment by vladsud** [comment]
I thought about it. We have somewhat similar problems in other places. For example, with 80 lines of code I can compress 3x Sequence payloads for Scriptor.
I'm a bit worried to implement solutions like that. I'd rather add some very trivial (lz4) compression to all blobs, and make sure it's part of protocol (i.e. storage can decompress / recompress them as it sees fit - similar to usage of base64 - one can upload binary and get back base64 or vice versa). This allows us to have zero impact (if we want to) on long term storage, and much smaller payloads.

There are asks from 3rd parties to solve similar problems for other DDSs.

**Comment by agarwal-navin** [comment]
Yes I agree. I wouldn't want to do it unless necessary.
