### ISSUE TITLE
Document differences between attachment and summary blobs

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6374]
Since I've typed it in https://github.com/microsoft/FluidFramework/issues/6371, worth opening an issue to see how we can make it into some official documentation.

@tylerbutler , can you please point me where such topic would be appropriate?
@wes-carlson, any chance you can take it from here and complement it with pointers to APIs, pointers to summary blobs, pointers to data structures involved, etc.

Attachment blobs have the following properties that differ them from snapshot blobs:
1. Each individual blob is uploaded and downloaded separately via http request.
   - There is general agreement that we want to add batching capabilities here in the future.
2. Attachment blobs are not included into snapshot payload, and thus have overall positive impact on boot, assuming their content is not needed on boot.
3. Because they are requested via individual request, such requests are cacheable by browser
   - i.e. images are loaded only once - rebooting document will result in image being provided by browser cache.
4. All blobs can be garbage collected by storage.
   - in case of SPO, it reclaims snapshots quickly, and thus any blob that was references in snapshot that given client loaded from might be deleted at some point in time.
   - We solve this problem for summary blobs by ensuring than all summary blobs are included in snapshot and cached by driver
   - Images (that use attachment blobs) could end up being gone in case client is way behind on ops and attempts to resolve an image. Code (on FF & Bohemia side) deals with it and app recovers quickly when it catches up (there is no longer such image in this doc).

**Comment by tylerbutler** [comment]
@vladsud I created a placeholder for this in the `docs/june-push` branch. It's in docs/content/docs/deep/blobs.md. You can push directly to that branch. It's tied to PR #6401 so anything you push to it will be published on the staging site for that PR.

**Comment by wes-carlson** [comment]
Hey @vladsud , what did you mean by this?
>Images (that use attachment blobs) could end up being gone in case client is way behind on ops and attempts to resolve an image. Code (on FF & Bohemia side) deals with it and app recovers quickly when it catches up (there is no longer such image in this doc).

On the FF side, do you mean that we send the BlobAttach op immediately, and always report all blobs as attached? How will we handle it when GC is implemented for attachment blobs? Will SPO keep all blobs attached to any snapshot they still have?

Also, how does Bohemia handle it? Should there be general advice here for app developers based on Bohemia's code?

Here is a version with more added:
>Attachment blobs have the following properties that differ from snapshot blobs:
>1. Each individual blob is uploaded and downloaded separately via http request.
>	- Attachment blobs are uploaded directly by clients via the `IContainerRuntime.uploadBlob()` API.
>	- A blob handle is returned by this call. Like a DataStore, the handle can be considered attached or unattached. Unattached blobs may be gargabe collected.
>	- Runtime will report attached blobs by including `Attachment` entries in the summary. These do not contain the contents of the blobs, only the ID returned when the blob was uploaded.
>	- There is general agreement that we want to add batching capabilities here in the future.
>2. Attachment blobs are not included into summary payload, and thus have overall positive impact on boot, assuming their content is not needed on boot.
>	- Attachment blobs are referenced in the summary by `Attachment` entries and blob handles, neither of which contain the actual contents of the blob.
>3. Because they are requested via individual request, such requests are cacheable by browser
>   - I.e. images are loaded only once - rebooting document will result in image being provided by browser cache.
>4. All blobs can be garbage collected by storage. In the case of SPO, snapshots are reclaimed quickly, and thus any blob that was referenced in the snapshot that a given client loaded from might be deleted at some point in time.
>   - We solve this problem for summary blobs by ensuring that all summary blobs are included in snapshot and cached by driver
>   - Images (that use attachment blobs) could end up being gone in case client is way behind on ops and attempts to resolve an image. Code (on FF & Bohemia side) deals with it and app recovers quickly when it catches up (there is no longer such image in this doc).
