### ISSUE TITLE
Record SPO error facet information for summary upload API.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6411]
Implement recording info from error facet for summary upload API.
Server tracks implementing actual error facets as https://onedrive.visualstudio.com/SPIN/_workitems/edit/1138128
This is work item triggered from investigation in issue https://github.com/microsoft/FluidFramework/issues/5503

The actual call is in writeSummaryTreeCore(), but ideally implementation should to any ODSP rest calls, and errors automatically get into telemetry.
This will likely be part of https://github.com/microsoft/FluidFramework/pull/6362, but tracking as distinct item coming out of above mentioned investigation

**Comment by jatgarg** [comment]
@vladsud Should we close this after @chensixx PR: https://github.com/microsoft/FluidFramework/pull/6362 because that will record the facet code for all odsp errors supplying response?

**Comment by vladsud** [comment]
I think so

**Comment by jatgarg** [comment]
Closing as task already achieved with #6362.
