### ISSUE TITLE
Summary can start early all the time after opening document due to usage of cached snapshots

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6412]
From summarization presentation by Arin:

> Solution: the initial delay is bypassed if there are more than N (4000) ops since the client connected
We compute this by taking [lastSequenceNumber – initialSequenceNumber] when the client becomes connected for the first time

I assume this means that if we loaded from cached snapshot and there are many summaries posted since it, we will not account for them in this math, and will try to trigger summarizer right away, right? If so, that's likely majority of cases nowadays and I assume we would want to address it.

Arin confirmed that, so we should look into it as it very likely impacts perf without us noticing it.

**Comment by arinwt** [comment]
One thing is to note: the math is definitely wrong with cached snapshots, but 4k ops is a fairly high number, so it may not be most cases.

**Comment by arinwt** [comment]
We can use SummaryCollection or other method of getting latest ack seq # to get this math right fairly easily.
