### ISSUE TITLE
e.trees is not iterable[Validate odsp snapshot in trees latest]

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#6413]
## Describe the bug
Validate the snapshot returned by odsp for contents like presence of trees/blobs etc.
Refer to this ICM incident: https://portal.microsofticm.com/imp/v3/incidents/details/234849739/home
The snapshot expected is:
export interface IOdspSnapshot {
    id: string;
    trees: IOdspSnapshotCommit[];
    blobs?: IOdspSnapshotBlob[];
    ops?: ISequencedDeltaOpMessage[];
}
 But we are seeing that in some rare case, we are seeing no trees. So validate and throw proper error.

**Comment by vladsud** [comment]
Before we add any validation, I'm curious to better understand
- when it happens
- what does it mean
- how client handles it today (i.e. actual behavior we are about to change).

**Comment by jatgarg** [comment]
As per the investigation by FFX folks, it seems that they had a code path where they allowed creating an empty file and then load that. So in that way we get this error where the snapshot is without any trees. They are removing such code path at their end, so we just need to add validation of snapshot and throw a proper error.
