### ISSUE TITLE
DeltaManager closed/disposed event needed

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#6431]
Right now IDeltaManagerEvents does not include "closed" but it does actually emit it.
As per Vlad here: https://github.com/microsoft/FluidFramework/pull/6421/files#r650305359
We should pick one ("disposed") and propagate- including that part of that PR.

**Comment by markfields** [comment]
For the record - It used to include `"closed"` but it didn't actually work if you were using a `DeltaManagerProxy`, see https://github.com/microsoft/FluidFramework/issues/2002.

In terms of the line of code in the PR referenced above, I would think listening for the runtime's own `"disposed"` event should work.
