### ISSUE TITLE
Loader.request("url: componentPath") returns even when wait is not specified to be false

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#6463]
We expect that when wait is not specified to be false that the Loader.request will wait forever for ops to come in. However, we are seeing that Loader.request is not waiting and actually returning values, thus potentially returning 404s for components that are just not in the snapshot yet and so prematurely are determined not to exist before the attach ops can come in.

We have confirmed with specific error stacks in telemetry that this code:

    let response = await container.request({ url: componentUrl, headers: { wait: false, externalRequest } });

    if (response.status === 404) {
    // The component was not in the loaded snapshot, it may be in the unsummarized op stream, let's try to resume the container and try again.
        resumeContainerInternal(container);

        response = await container.request({ url: componentUrl, headers: { externalRequest } });
    }

Which does a first request with wait = false and then a second request _without_ wait = false, appears to behave like wait = false is specified in the second response, resulting in 404s being returned. Perhaps a caching bug somewhere?

**Comment by leeviana** [comment]
I don't think this issue was ever looked into

**Comment by tylerbutler** [comment]
@microsoft/fluid-cr-loader Can you folks take a look this issue?

**Comment by anthony-murphy** [comment]
with some of the current discussions around externalizing the request flow from the platform to the application layer, and unifying the platform on handles i don't think we should invest much here. i'd rather tell partners to keep using resolve. if anything we may want to preemptively mark request on the loader as deprecated to push people down the resolve path.

**Comment by leeviana** [comment]
Hmm interesting, we've been moving to use Loader.request instead of resolve for getting the component based on the results of this issue: https://github.com/microsoft/FluidFramework/issues/4169

If we want to move back towards Container.request for getting components instead then we'll need a way to get the component id from the driver code, we just removed all of this code and moved to Loader.request.

**Comment by leeviana** [comment]
Still active but we are currently trying to remove all the pause stuff from our host code so that we don't get into this particular wait=false to wait=true state (if that's what was causing the issue)

**Comment by leeviana** [comment]
probably not stale (yet) if other teams use this code. Our particular team doesn't use pause any longer.
