### ISSUE TITLE
fetch-tool to adjust to work correctly in presence of deleted ops by SPO

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6479]
SPO is about to start deleting ops from storage.
That means the old flow of fetching ops from # 1 will no longer work.
Also ability of tool to do incremental downloads (update recent messages.json with newer ops) may also not work, if there is a gap that we can not fill in.

The way it is exposed to clients - 410 is returned by SPO, which results in OdspErrorType.cannotCatchUp error being generated in response to ops fetching. We should figure out how fetch-tool should react and not completely fail.

Ideally
- It figures out and downloads all the ops that are there in storage (likely by asking for ops from the oldest snapshot sequence number)
-  If there are some ops on local disk, and there is a gap, we do not immediately delete old ops, as user might want to keep them. I think the tool should fail and ask user to delete messages.json to continue, to give user a choice to do so or not (nice to have - an option to overwrite it and automatically for tool to delete ops).

This will quickly become problematic for OCEs to be able to investigate issues, so putting in July.
@jatgarg - any chance you can break it into individual steps for Si to implement?

**Comment by jatgarg** [comment]
Yes, will take a look and update here @vladsud

**Comment by jatgarg** [comment]
Sample error thrown when ops are not available from the beginning: 
ERROR: Error: Error 410 (Gone)
    at createOdspNetworkError (D:\PragueJatin\fluiderror1\packages\utils\odsp-doclib-utils\dist\odspErrorUtils.js:104:21)      
    at Object.throwOdspNetworkError (D:\PragueJatin\fluiderror1\packages\utils\odsp-doclib-utils\dist\odspErrorUtils.js:181:26)
    at D:\PragueJatin\fluiderror1\packages\drivers\odsp-driver\dist\odspUtils.js:63:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.fetchAndParseAsJSONHelper (D:\PragueJatin\fluiderror1\packages\drivers\odsp-driver\dist\odspUtils.js:119:62)
    at async EpochTrackerWithRedemption.fetchAndParseAsJSON (D:\PragueJatin\fluiderror1\packages\drivers\odsp-driver\dist\epochTracker.js:109:30)
    at async EpochTrackerWithRedemption.fetchAndParseAsJSON (D:\PragueJatin\fluiderror1\packages\drivers\odsp-driver\dist\epochTracker.js:271:20)
    at async D:\PragueJatin\fluiderror1\packages\drivers\odsp-driver\dist\odspDeltaStorageService.js:48:30
    at async D:\PragueJatin\fluiderror1\packages\drivers\odsp-driver\dist\odspDeltaStorageService.js:125:25
    at async getSingleOpBatch (D:\PragueJatin\fluiderror1\packages\loader\driver-utils\dist\parallelRequests.js:323:49)
omitPropsFromLogging: {}
errorInstanceId: "ddb2f292-cb44-4e38-84ce-298088c8062a"
**statusCode: 410
errorType: "cannotCatchUp"**
canRetry: false
online: "Unknown"
facetCodes: [
  "fluidDeltaDataNotAvailable"
]
**response: "{\"error\":{\"code\":\"fluidDeltaDataNotAvailable\",\"message\":\"From '1' must be greater than the GenesisSequenceNumber '1414'.\",\"firstAvailableDelta\":1415}}"innerMostErrorCode: "fluidDeltaDataNotAvailable"**
responseType: undefined
sprequestduration: 116
contentsize: 144
sprequestguid: "6624e79f-5089-0000-d938-d454dc376c6b"
requestId: "6624e79f-5089-0000-d938-d454dc376c6b"
xMsedgeRef: "Ref A: 6834B86CFCA14E67B0DF1F5139B5ABB2 Ref B: CO1EDGE1411 Ref C: 2021-08-19T20:28:13Z"
serverEpoch: "8898de62-7443-4ca2-86cc-d9a916b4e927"

**Comment by jatgarg** [comment]
"--dump:rawmessage" is used to fetch messages in fetch tool and the --saveDir to save it in messages.json in the said directory.
So first lets work on fetching the ops properly in case the ops are not available from seq number 1. 
So lets specify another arg "--dump:rawmessageforcesave" which will delete the already present messages.json and will download new messages and save it in messages.json. 
Method would be to make the delta get call which we already do but then we will catch the error thrown by it(as shown above) and we will look at the "statusCode" = 410 and "innerMostErrorCode" === "fluidDeltaDataNotAvailable". If so we will parse the response and get "firstAvailableDelta" property from the error and then that will be our first available message sequence number. We will then fetch messages from that sequence number and will overwrite the messages.json file.
