### ISSUE TITLE
ODSP driver to provide reason for REST calls for server to log to server telemetry

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6483]
Per ODSP sync, it would be great to add a reason (I assume in the form of query param or header) for the the call on key calls like
- getting snapshot
- getting latest version
- getting ops
- etc.

For example, for server telemetry to know that
- the reason we fetch ops is because there is a gap between initial ops and first op on the socket
- Or we call getVersions because we got a smmaryNack and trying to recover.

Based on feedback, this is useful data to have that helps find bugs.

**Comment by kenluck2001** [comment]
After preliminary investigations, I realized that you should provide more context as what is currently tracked, which files are likely to be affected? Thanks in advance
