### ISSUE TITLE
Preserve and return unreferenced flag in local server / tinylicious / FRS

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#6507]
The unreferenced flag in summary send to the these servers needs to be returned in the snapshot.

**Comment by agarwal-navin** [comment]
We might have to separate this out into two - One for FRS driver and the other for local server / tinylicious that use GIT.

**Comment by znewton** [comment]
#7239 made sure to preserve the unreferenced flag when writing summaries to storage, as well as when reading a summary from storage.

However, @agarwal-navin is correct, there will be more work needed for Git storage solutions:
1. @fluidframework/gitresources would need updating. Probably `ICreateTreeParams` and `ICreateBlobParams` would need the unreferenced flag property to be added.
2. I'm not sure if Git has a way of storing unreferenced data and surfacing it when the summary is read.

FRS is not using Git storage, and the unreferenced flag is being preserved and returned for FRS scenario. I am going to un-assign this issue from myself, but I think we can consider the FRS piece of this complete.

**Comment by agarwal-navin** [comment]
@znewton Are there tests in FRS to validate that the unreferenced flag is stored and returned?

**Comment by curtisman** [comment]
> @znewton Are there tests in FRS to validate that the unreferenced flag is stored and returned?

Do we have e2e test for it to test odsp,  which should be expand to all services?

**Comment by agarwal-navin** [comment]
Yeah, it should. I don't think we have e2e tests for FRS yet. I was hoping if FRS has tests, we would have some coverage until we add ours :-).

**Comment by znewton** [comment]
Unfortunately no, we do not have e2e tests in FRS for validating this behavior.

**Comment by agarwal-navin** [comment]
Okay, thanks. We do have e2e tests in odsp for this. We will expand it to FRS when we add FRS support.

**Comment by agarwal-navin** [comment]
Tracked by AB#426
