### ISSUE TITLE
SummarizerNode shouldn't have logic mapping to children nodes from IDs

### ISSUE THREAD

**Issue by arinwt** [microsoft/FluidFramework#6532]
The logic for traversing from a parent node to a child node in the tree of SummarizerNodes (and their corresponding nodes: ContainerRuntime, Datastore, DDS) should not be replicated in SummarizerNode code.

Anywhere that the SummarizerNode `children` map's keys are used, is an area to fix. We do this during `refreshLatestSummaryFromSnapshot` to map from downloaded snapshot tree to child SummarizerNode, but really that logic should exist outside of SummarizerNode- probably more like how the tree of `summarize` calls work, but with `refreshLatestSummaryFromSnapshot`.

Also see loading from local snapshot, and usages of `parseSummaryTreeForSubtrees`/`parseSummaryForSubtrees` for other examples to fix. If we ever plan to bring back differential summaries (_baseSummary handle + _outstandingOps blob), then we still need to make sure we pass `childrenPathPart` in while fixing these issues.

@agarwal-navin is adding a new usage of ID to map for GC as well.

**Comment by agarwal-navin** [comment]
Tracked by AB#434
