### ISSUE TITLE
Improve telemetry to be able to track lifetime of the file, including when file was created

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6551]
This work is result of investigations for https://github.com/microsoft/FluidFramework/issues/5690. That issue has more data on overall problem and how I arrived to needing these changes.

Here is my proposal to make investigation like that simpler:

1. Add somewhere in summary information like
- time stamp when file was created
- version of FF runtime used to create this file.
- Maybe some more properties that might be useful, like maybe summary counter.
2. Every time we summarize the file, or load a file, we add these properties to some telemetry events (or add new events), such that we can track them over time.

While it will not answer all the questions, it will help us do filtered searches in telemetry, like files created over last 3 months (when images where changes), and thus have better sense on correlation to certain features. It will be exact science (maybe files get bigger over time, and thus filtering on time / runtime version used to create file will tell us less about feature set used but lifetime of file). But certain properties (like number of summarizations for this file) will help to peal the onion.

**Comment by anthony-murphy** [comment]
I really wanted this kind of information for our common error logging, as right now the summary information is pretty sparse: 
https://github.com/microsoft/FluidFramework/blob/da7507ca5f043698c7290e143e9355b8cfeb3fb7/packages/loader/container-loader/src/container.ts#L614-L620

**Comment by vladsud** [comment]
One addition to consider: It would be super useful also to have some application moniker added there like "Whiteboard" or "Bohemia". This kind of information might be useful in various heuristics. For example, we have broken search contract due to changes in structure of snapshots and it went unnoticed. ODSP could have an alert that says Bohemia file has to have at least one Scriptor that is indexed. If it's not the case, alert would fire immediately. Today, it's hard to implement alerts like that because .fluid file may represent something else (3rd party, Whiteboard) and there might be no searchable content, so building heuristics to detect issues is really hard.

Not sure in what form it should show up, most likely as a property bag from app when creating a file, though we may require some specific properties to be there (like app name).
