### ISSUE TITLE
api-extractor not updating common-definitions api-report properly

### ISSUE THREAD

**Issue by ksbrar** [microsoft/FluidFramework#6606]
While updating `supportsTags` in common-definitions, doing a root `build:fast` in the `common-definitions` folder did not update the relevant API. (for reference: https://github.com/microsoft/FluidFramework/pull/6598#pullrequestreview-696630765). Had to go to common-definitions folder and do a manual copy-paste after doing a local ci:build:docs there.

CC @tylerbutler

**Comment by tylerbutler** [comment]
@ksbrar Good catch. Based on [this comment](https://github.com/microsoft/FluidFramework/pull/6187#discussion_r635451731), I think the right thing to do is remove the top-level files. I'll open a PR.

> I've been trying to output all the API reports for a given "mono-repo" (workspace?) to a single folder relative to the workspace root. Since these packages are all independent, I suggest we put the reports directly within the projects. (I'm thinking about this for the API extraction process, too, but those files need to be aggregated as part of the build so it's more complicated.)
> 
> This should make us able to take a workspace and break it out into its own repo without any changes to the API pipeline.

**Comment by tylerbutler** [comment]
Actually, upon further investigation, I can't repro this. @ksbrar Can you repro?

**Comment by ksbrar** [comment]
Turns out this is a bug on my own machine. Closing.
