### ISSUE TITLE
DDS not connecting in Routerlicious

### ISSUE THREAD

**Issue by karlbom** [microsoft/FluidFramework#6631]
## Describe the bug

Encountered in running testing a prototype with Routerlicious

When creating a document with a DDS the expectation is that it is connected after initialisation either when the container is created for the first time or when a user connects to it after creation.

In `tinylicious` initialising a container works as expected, in `routerlicious` it does not. it seems that it only connects on creation of a container but not when connecting to an existing container in routerlicious

### To Reproduce

1. clone the sample repo https://github.com/karlbom/node_fluid_bug
2. install dependencies `npm i`
3. launch tinylicious `npm run start:server`
4. lauch the not application with `npm start`
5. look at console output
6. repeat the step by using routerlicious (uncomment the appropriate line in the repos `index.ts`
7. console output differs from tinylicious in that the second dds never connects
8. this behaviour will also persists if a documentid is hardcoded  and only one container with an existing document is loaded

### Expected behavior
both outputs should be the same in routerlicious and tinylicious. I expect the dds's in a data object to connect in either situation (creation first time and loading an existing container) as it would in `tinylicious`

**Comment by DLehenbauer** [comment]
@karlbom - I think latest docker images pushed by @tanviraumi should fix the issue.

```sh
> docker-compose down
> docker-compose pull   # Should see several Routerlicious images updated.
> docker-compose up
```

In 'init.ts' you'll probably need to change the key to the new default of "create-new-tenants-if-going-to-production" (or 'containerAttach' will return a 403.)

**Comment by karlbom** [comment]
I can confirm that using the latest docker images the sample works as expected
