### ISSUE TITLE
Remove DeltaManager from public API.md

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#6640]
> We should question every change to api.md, and see if API being changed actually belongs here. I believe the answer here is no.
> It would be great to remove ./deltamanager from index.ts and instead export (by moving into other files like utils.ts) anything that truly needs to be exported from this package.

_Originally posted by @vladsud in https://github.com/microsoft/FluidFramework/pull/6635#discussion_r664864646_

And then depending on how that goes, maybe we open an issue for a broader audit/fixup.

**Comment by tylerbutler** [comment]
@markfields I put this in July because I'd like to prioritize public APi changes. Let me know if that's too aggressive.

**Comment by markfields** [comment]
Probably, esp since it has no assignee. @vladsud how do you think we should prioritize/fund this and related cleanup?

**Comment by vladsud** [comment]
I'll move it to August with a hope that it can be picked up by folks looking to start contributing (marked as good first issue)

**Comment by atiqueahmedziad** [comment]
@vladsud can you kindly give some guidance on what's needed to be done here? 
I am getting some result of DeltaManager [here](https://github.com/microsoft/FluidFramework/search?l=Markdown&p=1&q=deltamanager)
but I am kinda confused on how much do I need to remove.

**Comment by vladsud** [comment]
DeltaManager class should not be exported from container-loader package. Any build breaks that result from such change needs to be addressed in some form or shape. Tracking (search) could be useful, but it needs to be case sensitive and match whole word, not to capture things like "deltaManager" variables - this is not useful
