### ISSUE TITLE
0x07b, 0x07d /* "Unexpected op" */ assert in TaskManager in ODSP scalability tests

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6689]
Splitting from https://github.com/microsoft/FluidFramework/issues/6555

We do see these errors in ODSP scalability runs:

  | fluid:telemetry:Container:ContainerClose | 0x07b | 517 |  

This maps to this assert in "volunteer" event handler in TaskManager:

                assert(pendingOp !== undefined, 0x07b /* "Unexpected op" */);

I'm happy to dig more data from their telemetry if it helps, but I'd guess we should see same (maybe different impact) in Bohemia production telemetry.

**Comment by vladsud** [comment]
@ChumpChief , any chance you can take a look? It still happens in stress tests.
I do not see anything in Kusto, not sure if it's because we never hit it or changes did not propagate to prod yet.

**Comment by vladsud** [comment]
Also we hit 0x07d as well in same run. That's same assert but in "abandon" handler

**Comment by vladsud** [comment]
That issues is raising to become # 2 in terms of impact in scalability runs, due to all the other high hitters being addressed.

**Comment by vladsud** [comment]
FYI - latest ODSP scalability run was done with recent change that increased substantially number of non-immediate ops in the system. The run was clean with exception of hitting these asserts - they skyrocketted:

[Logs](https://ms.portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F93543f02-938d-4016-9d15-9cc4329b7033%2FresourceGroups%2FRegressionPrevention%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FFluidClient/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0XNsQ0CMQxG4Z4pTEpGuJ4JmMAkPyLS2Ua2AwpieK66a58%252B6dURaXJ9QzPo9KPPEw66UDVN7hpU4G5eiLVt%252BXz0xzp6WxIrBOlzuQ0R9v7Fjg%252BbZiSss2yHME%252B6T8ouiGR5UUPUPztPLY%252BIAAAA/timespan/P1D)

customEvents 
| where customDimensions.testUid == "ccaca4ea-856a-4fa9-ad65-892031397450"
| where customDimensions.category == "error"
| summarize count() by name, tostring(customDimensions.error)


  | fluid:telemetry:Container:ContainerClose | 0x07d | 2,672 
  | fluid:telemetry:Container:ContainerClose | 0x07b | 2,627

I do not think noop frequency directly relates to these problems, but it shows that some race condition (depending on environment0 can be hit quite often.
That's the only real problem in these runs.

**Comment by vladsud** [comment]
Latest ODSP scalability test run (5a227efb-b899-48de-9191-a87150950c57) has these number of containers lost due to these reasons:

  | fluid:telemetry:Container:ContainerClose | 0x07b | 704 |  
  | fluid:telemetry:Container:ContainerClose | 0x07d | 725 |

That's the only failure that is directly affecting users, as well as has unknown impact to stress tests.

**Comment by jatgarg** [comment]
Thanks for this PR. I will monitor and see if we don't see these errors in our stress tests.
