### ISSUE TITLE
Add a 'outputDir' option for 'MochaReporter'

### ISSUE THREAD

**Issue by cqcmdwym** [microsoft/FluidFramework#6714]
## Feature
**Is your feature request related to a problem? Please describe.**
How to add a outputDir option for @fluid-tools/benchmark MochaReporter, currently always output to @fluid-tools/benchmark/dist/.output

**Describe the solution you'd like**
https://github.com/microsoft/FluidFramework/blob/main/tools/benchmark/src/MochaReporter.ts#L46 add options parameter to `BenchmarkReporter`

**Existing work**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by tylerbutler** [comment]
@CraigMacomber @DLehenbauer Any reason this isn't configurable?

**Comment by CraigMacomber** [comment]
Sounds like a good idea to me.

For compatibility we should probably leave the default alone (at least for now), but adding an optional command line argument and/or environment variable to to control where the output goes seems useful. I'm not sure exactly what would be the best way to configure it.

**Comment by cqcmdwym** [comment]
@CraigMacomber as you said, maybe both of command line argument and environment variable would be better.

**Comment by cqcmdwym** [comment]
PR for supporting command line first: https://github.com/microsoft/FluidFramework/pull/7048
