### ISSUE TITLE
Increase in ODSP PostSnapshot size in stress tests 

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#6732]
## Describe the bug
We're seeing significant increase in the average payload size for PostSnapshot, from around 10k to around 100K. This is triggering their latency alerts

**Comment by anthony-murphy** [comment]
union office_fluid_ffautomation_* 
| where Data_hostName == "@fluid-internal/test-service-load"
| where Data_eventName startswith "fluid:telemetry:OdspDriver:uploadSummary_"
| project Event_Name, Event_Time,Data_eventName, Data_size, Data_blobs, Event_Id
| summarize avg(Data_size),avg(Data_blobs)  by bin(Event_Time,1d)

Event_Time | avg_Data_size | avg_Data_blobs
-- | -- | --
2021-07-13 00:00:00.0000000 | 154549.724489796 | 325.561224489796
2021-07-14 00:00:00.0000000 | 132393.782258065 | 263.758064516129

union office_fluid_ffautomation_* 
| where Data_hostName == "@fluid-internal/test-service-load"
| where Data_eventName startswith "fluid:telemetry:Summarizer:Running:Summarize"
| project Event_Name, Event_Time,Data_eventName, Data_size, Data_blobs, Data_totalBlobSize, Data_fullTree, Event_Id
| summarize count()  by Data_fullTree, bin(Event_Time,1d)

Data_fullTree | Event_Time | count_
-- | -- | --
1 | 2021-07-13 00:00:00.0000000 | 42
0 | 2021-07-13 00:00:00.0000000 | 148
0 | 2021-07-14 00:00:00.0000000 | 404
  | 2021-07-14 00:00:00.0000000 | 18
1 | 2021-07-14 00:00:00.0000000 | 43


here is the data we have. unfortunatly, we don't seem to have data older than the last couple days, but it does align with the sizes ODSP is seeing, and it does seem large for what the stress test does.

**Comment by anthony-murphy** [comment]
let runGenerate = 
    union office_fluid_ffautomation_* 
    | where Data_hostName == "@fluid-internal/test-service-load"
    | where Data_eventName == "fluid:telemetry:Summarizer:Running:GenerateSummary"
    | project 
        Data_totalBlobSize, 
        Data_treeNodeCount,
        Data_blobNodeCount, 
        Data_handleNodeCount, 
        Data_containerId, 
        Data_summaryGenTag
;
let runSummarize = 
    union office_fluid_ffautomation_* 
    | where Data_hostName == "@fluid-internal/test-service-load"
    | where Data_eventName startswith "fluid:telemetry:Summarizer:Running:Summarize"
    | project  Event_Time, Data_fullTree, Data_containerId, Data_summaryGenTag
;
runGenerate
| join kind=inner  runSummarize on $left.Data_containerId == $right.Data_containerId and $left.Data_summaryGenTag == $right.Data_summaryGenTag
| project 
    Event_Time, 
    Data_totalBlobSize, 
    Data_fullTree,         
    Data_treeNodeCount,
    Data_blobNodeCount, 
    Data_handleNodeCount
| summarize avg(Data_totalBlobSize), avg(Data_treeNodeCount), avg(Data_blobNodeCount), avg(Data_handleNodeCount), count() by Data_fullTree, bin(Event_Time, 1d)

Data_fullTree | Event_Time | avg_Data_totalBlobSize | avg_Data_treeNodeCount | avg_Data_blobNodeCount | avg_Data_handleNodeCount | count_
-- | -- | -- | -- | -- | -- | --
0 | 2021-07-14 00:00:00.0000000 | 67829.308056872 | 107.502369668246 | 211.293838862559 | 57.8578199052133 | 282
1 | 2021-07-14 00:00:00.0000000 | 133317 | 335 | 607.5 | 0 | 3
  | 2021-07-14 00:00:00.0000000 | 87113.6363636364 | 165.181818181818 | 304.545454545455 | 49.0909090909091 | 11


looks like most summaries are not full, which is expected.

**Comment by anthony-murphy** [comment]
Looking at the data it looks like the large responses are primarily for failed requests, we are seeing significant increase in fileOverwrittenInStorage (409) and fileNotFoundOrAccessDeniedError (404) errors

This makes sense, as we fall back to the full tree in error cases

**Comment by vladsud** [comment]
I have not looked at telemetry, but that sounds similar to earlier ODSP scalability tests, if we also see summary ack timeouts and nacks with wrong parent. At some point (2 weeks ago?) Arin fixed a bug where once client got incorrect info (nack for a summary that actually would succeed), summarizer would never refresh parent summary and would fail continuously after that, moving back and forth between incremental and full summaries.
With latest bits we try to reduce number of times full summaries are attempted - we do 2 attempts with incremental summaries with refreshing parent in between, so number of full summaries should be lower. If they do happen, we should look into why prior two incremental summaries failed in a row.
