### ISSUE TITLE
Give errors a unique ID for correlation, e.g. between log events or when wrapping errors

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#6746]
## Feature

See Vlad's suggestion here:  https://github.com/microsoft/FluidFramework/discussions/6676#discussioncomment-995772
And this PR which gets explicit about one case of logging an inner error when wrapping it:  https://github.com/microsoft/FluidFramework/pull/6702

**Describe the solution you'd like**

Something like this - add a property `fluidErrorId` to `IFluidErrorBase`, and when wrapping be sure to log the inner error and annotate the new error with `childErrorId = innerError.fluidErrorId`.

**Describe alternatives you've considered**

Even without a unique ID, it's usually possible to infer when the same error has been logged multiple times, or to connect an inner error to wrapped error.

**Additional context**

If we do want to do this and include on `IFluidErrorBase`, we should do it right away, so there's not two versions of the interface floating around.

**Comment by markfields** [comment]
Putting in June, to either implement or decide definitively to punt, since it impacts the shape of a brand new interface and I'd like to be deliberate about what goes in there, and avoid multiple versions of it if possible.

**Comment by markfields** [comment]
`errorInstanceId` is another good candidate for the name of this prop. courtesy of @jvoels

**Comment by jvoels** [comment]
> `errorInstanceId` is another good candidate for the name of this prop. courtesy of @jvoels

I'm more partial to this than I bet people might assume.. Including 'instance' as part of the identifier disambiguates the intent in terms of error object instance identity and error prototype or name identity.

**Comment by jvoels** [comment]
What type for the property are we thinking? String, but expectation is it's a valid guid?

**Comment by markfields** [comment]
I think it's for both.

Wrapping errors must be a very intentional choice to bump to a different abstraction layer. Otherwise just let errors propagate. Possibly normalize or annotate if you "have something to add" (e.g. telemetry props).

But when we do wrap, I'm thinking of adding another method `wrapErrorAndLog` which calls wrap, then logs the inner error. And both inner and outer would love each others' instance IDs. So _if we need to_, we can trace causation like this.

That's for the "former" case. I think just having an ID for deduping errors that are logged in multiple events (which is totally ok - just only analyze error counts/rates on a per-event basis) is a nice-to-have. Probably not critical, but an easy win.

**Comment by jatgarg** [comment]
Closing the issue with this PR: https://github.com/microsoft/FluidFramework/pull/7045
