### ISSUE TITLE
Absence of window.crypto.subtle in insecure browser contexts leads to a crash

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#6757]
When using insecure browser contexts, `window.crypto.subtle` is not present which results in an error "Cannot read property 'digest' of undefined" in the following code:
https://github.com/microsoft/FluidFramework/blob/ce53b6a335a8c79e4e5d0b5fe4dd71707ea7f09c/common/lib/common-utils/src/hashFileBrowser.ts#L38

This file has a comment suggesting to override the hashFn by calling `setInsecureContextHashFn` and that the algorithm should match the one used by `hashFile`. However, this does not seem like a very good user experience and its easy to get the hashFn wrong which results in error in unrelated places.

Also, if `setInsecureContextHashFn` is used to specify as hashFn, the app cannot be used in secure context because of the code here - https://github.com/microsoft/FluidFramework/blob/ce53b6a335a8c79e4e5d0b5fe4dd71707ea7f09c/common/lib/common-utils/src/hashFileBrowser.ts#L33.
This means an app can be used either in secure on insecure context. Is this an expected behavior?

We need to provide a better solution for this as this problem was faced recently by one of our users.

**Comment by agarwal-navin** [comment]
@heliocliu FYI

**Comment by heliocliu** [comment]
The alternative I've explored in the past was to automatically fallback to the node implementation of the function in this case, see #3869 .  The associated PR shows how this might be accomplished too in some of the earlier commits (https://github.com/microsoft/FluidFramework/pull/4525/commits/fc84927ef0e452e3bab6dfc47af6386ab8869428).  The other thing that needs to be considered there though is that the hashing library we use for node (sha.js) is pulled in for purposes of bundle analysis even if it doesn't get served by default to normal browser consumers.  As a result, if someone were to add an illegitimate usage of sha.js for browser, our bundle size automation will not detect it.

**Comment by t-rkrosnick** [comment]
I'm trying to run my app from my IP address (rather than localhost) and am running into the issue described here and in [#3869](https://github.com/microsoft/FluidFramework/issues/3869). I tried to follow the suggestions of overriding the hash function but it doesn't seem to help, I get the same "Cannot read property 'digest' of undefined" error. What code changes do I need to make in order to get this to work? For now I'm ok with a solution that works for only insecure browser contexts.

**Comment by agarwal-navin** [comment]
@t-rkrosnick Overriding the hash function by calling `setInsecureContextHashFn` defined here should work: https://github.com/microsoft/FluidFramework/blob/ce53b6a335a8c79e4e5d0b5fe4dd71707ea7f09c/common/lib/common-utils/src/hashFileBrowser.ts#L18
Since you are still getting "Cannot read property 'digest' of undefined", it seems that either the hash function was not properly overridden or the new hash function is also using `crypto.subtle`.

**Comment by agarwal-navin** [comment]
Can you please share some more details? Like if its the same error stack as before or if its crashing in some other part of the code?

**Comment by heliocliu** [comment]
One of the other issue with the current override function is that it can be difficult to determine where exactly to make the override...  Because frequently where the test code changes might get made aren't in the same context as where the hashing function gets run,  and end up not actually overriding as expected.  E.g. overriding in the test harness code doesn't work because it's run in a separate context as the tests themselves.

**Comment by t-rkrosnick** [comment]
The stack trace seems to be the same before and after I make the change.

Before:
![stack_trace_error_before png](https://user-images.githubusercontent.com/85357779/127049820-920741f5-3420-4918-805d-251a5d7caed1.jpg)

After:
![stack_trace_error_after png](https://user-images.githubusercontent.com/85357779/127049848-f6a7e0c3-e04b-49e4-ad58-d2e00f5fcd15.jpg)

I tried making the changes within my app's `node_modules`. Here's are the changes I made:

Within `node_modules\@fluid-experimental\fluid-framework\node_modules\@fluidframework\common-utils\src\hashFileBrowser.ts` I added the highlighted code below:
![image](https://user-images.githubusercontent.com/85357779/127050525-76516a3c-16c1-4066-a1d8-0ec45bec0cf7.png)

I also tried adding this code in the same spot to `node_modules\@fluid-experimental\fluid-framework\node_modules\@fluidframework\common-utils\lib\hashFileBrowser.js` and `node_modules\@fluid-experimental\fluid-framework\node_modules\@fluidframework\common-utils\dist\hashFileBrowser.js`

Is there a different place within my `node_modules` that I should be adding this code?

Also for additional context, here is how I'm referencing fluid service (the gray streaks are where I replaced `localhost` with my IP address)
![image](https://user-images.githubusercontent.com/85357779/127051588-a57df065-0fe5-4196-ac2b-9a6c9683811f.png)

**Comment by heliocliu** [comment]
Hash function looks good; it's copied from `hashFileNode.ts` as expected.  I agree with Navin that overriding where you create your containers is probably better.  I wonder if in the case above where you modified the node_modules if the changes just didn't recompile into your app though based on the line numbers etc.

**Comment by t-rkrosnick** [comment]
I just tried overriding before I create the FrsClient but still doesn't seem to work.

In my app file I first imported `setInsecureContextHashFn` and `shajs`
![image](https://user-images.githubusercontent.com/85357779/127056236-d9a00403-5043-460c-bfe5-1fc8749af841.png)

Then I did the override before creating my FrsClient:
![image](https://user-images.githubusercontent.com/85357779/127056385-9c9d67aa-cf0e-4848-ab2b-82a601ec405b.png)

But I still get the same error message:
![image](https://user-images.githubusercontent.com/85357779/127056795-00c6d84a-14e4-4dda-86c6-98542078ca10.png)

Any idea what I need to do differently?

**Comment by heliocliu** [comment]
I'd suspect your `setInsecureContextHashFn` import doesn't get mapped to the same function as used by the rest of your app.  Can you try importing it as `import { setInsecureContextHashFn } from "@fluidframework/common-utils";` while making sure your `common-utils` project dependency is the same version?

**Comment by t-rkrosnick** [comment]
I just made that change and unfortunately am still getting the same error. Thanks for your help so far.

Would it be possible for your team to include a sample project on the Fluid Framework website or create a repository that showcases how to get this working for insecure browser contexts? The reason I'm trying to do this is so I can test my Fluid app locally (on the same network) across different devices I have; I'm serving the app from one of my devices and so trying to access Fluid at `<my_ip_address>:7070` rather than `localhost:7070`. Thanks.

**Comment by heliocliu** [comment]
@agarwal-navin probably time to go ahead with the fallback fix... i can go ahead and get that done this week.

**Comment by agarwal-navin** [comment]
I agree. In the meanwhile, any idea on how we help help @t-rkrosnick?

**Comment by heliocliu** [comment]
Root of the issue is that the override isn't being set in the context that's trying to run it.  I don't think I'm familiar enough with the distributed hosting scenarios to be more helpful with that 😕

**Comment by agarwal-navin** [comment]
@t-rkrosnick Helio has a PR out with the fallback fix for insecure contexts. This should be part of the next release (0.45) which will be out at end of next week.
