### ISSUE TITLE
annotateError should probably not overwrite existing telemetry props

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#6758]
See this code:  https://github.com/microsoft/FluidFramework/blob/ce53b6a335a8c79e4e5d0b5fe4dd71707ea7f09c/packages/utils/telemetry-utils/src/logger.ts#L571-L573

Instead the body of that function could be:
```typescript
    // Don't overwrite previously added props
    for (const key of Object.keys(newProps)) {
        if (propsForError[key] === undefined) {
            propsForError[key] = newProps[key];
        }
    }
```

**Comment by markfields** [comment]
@anthony-murphy, @vladsud -- Any definitive opinions on this?  I'm leaning towards not overwriting, but wanted to open it up for discussion here.

**Comment by anthony-murphy** [comment]
in the logger we don't overwrite event properties, as we assume the source knows best, i think we should do the same here. 
https://github.com/microsoft/FluidFramework/blob/4235fa91dfe58cb083ca9f50faa6112eb2718bd0/packages/utils/telemetry-utils/src/logger.ts#L245
