### ISSUE TITLE
Create mechanism for container injected dependencies

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#6769]
Today, we don't know of a good way to inject container specific (optional) dependencies into a component. The closest thing we have today is the dependencyprovider scope object which gets routed through via aqueducts DataObject into a "providers" object however dependencyprovider lives on the scope and is actually a global context and so can't be used for anything container specific (once one container registers dependencies here, all other containers loaded via the same loader will also incorrectly get those dependencies).

Until we have a good mechanism for this, our only option for optional "container context" is to route things through container handlers, however this mechanism is not ideal since it relies on some sort of implicit request contract, is requested through the container runtime object, not the component runtime object, and is completely skipped by all new request paths like handles.

**Comment by anthony-murphy** [comment]
is scope not sufficient here? ContainerRuntime.load task scope, by default this is content.scope, but i can as should be overwritten. I'd suggest setting it to {...context.scope, ...your-scopes} this will then be available to all data stores in the container
 https://github.com/microsoft/FluidFramework/blob/c513f4a4f0c79653e72d2ed5a410f41aed3d6841/packages/runtime/container-runtime/src/containerRuntime.ts#L552-559

**Comment by leeviana** [comment]
Cool, I didn't know containerScope was a parameter on here!

Do you think this can/should be combined with the dependency provider mechanism (which is current implemented like a specific object off of the scope object)? Right now, usage of the dependency provider mechanism basically overrides the global dependency provider but I can imagine the suggestion might be to make a copy of the dependency provider (somehow, hopefully there's an easy API for this?), inject container specific dependencies and then override the containerScope version with the new version?

**Comment by anthony-murphy** [comment]
`DependencyContianer` can take a parent, so i think contianerScope just bascially becomes `{...context.scope, IFluidDependencySynthesizer: new DependencyContianer(context.scope)}`

**Comment by leeviana** [comment]
Great, this has been very helpful! We can close this for now then and I'll come back later with more details if things don't work out :)
