### ISSUE TITLE
Broken image links on https://fluidframework.com/docs/deep/hosts/

### ISSUE THREAD

**Issue by Kening** [microsoft/FluidFramework#6771]
### Issue Category

- Incorrect/Outdated information
  - **https://fluidframework.com/docs/deep/hosts/**

### Details

In this file https://github.com/microsoft/FluidFramework/blob/main/docs/content/docs/deep/hosts.md
, there are two broken image links, including:
```
<img src="/docs/concepts/images/architecture.png" .../>
<img src="/docs/concepts/images/load-flow.png" .../>
```

**Comment by tylerbutler** [comment]
@kening Thanks for the bug report! This was fixed in #6819.
