### ISSUE TITLE
non-immediate noops may or may not have clientId set

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6799]
Based on examining files, non-immediate ops ("contents": null) occasionally have no clientID, but most time do have clientID.
This looks inconsistent.
I personally would prefer to have clientID there, and same be true for ops like join & leave, as that simplifies tracking activity of a client in a session (including discussions about rolling hash).
But either way would work.

**Comment by tanviraumi** [comment]
@GaryWilber Do you have any log for sequenced operations we can examine? Based on deli lambda, I don't expect non-immediate no-ops to have clientId. Deli should always coalesce them and generate a no-op with no clientId.

**Comment by GaryWilber** [comment]
If it has a client id, then a client must be submitting that noop. Deli will never create a no-op on behalf of a specific client

@vladsud Can you share me a file that has those no-ops in them?

**Comment by tanviraumi** [comment]
> If it has a client id, then a client must be submitting that noop. Deli will never create a no-op on behalf of a specific client

That is correct and every non-immediate (content === null) no-op should be coalesced and converted into one no-op with clientId = null. In other words, only immediate no-op (content !== null) should ever have clientId.
