### ISSUE TITLE
ODSP Post Snapshot Provide If-match Header with Previous Snapshot ID

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#6848]
Enforcing latest snapshot id on snapshot upload

Description
This document describes how a client may specify the id of the latest snapshot when uploading a new container or channel, i.e. when the client is uploading a summary or push is committing the summary,

The client may find out the id of the current latest snapshot by several means, i.e. get latest, summary ack message or via the response to a create snapshot tree call when specifying a container. Below is the example response for the latter:

Container creation response:
{
  "id": "bBwAAAAAHAAAA",
  "sequenceNumber": 0,
  "itemUrl": "https://tenant7b1d82e39de34a88bb230996df041457.spgrid.com/_api/v2.1/drives/b!l8so13roKk6XL6GXmhbFRdlsCJnVWh9MsPsTWBXzkQmZbs8FtA7jQaztQGzSxRDo/items/01KEEVZHGFAHHG7RPI4BHKSDN3A47DLQPW",
  "driveId": "b!l8so13roKk6XL6GXmhbFRdlsCJnVWh9MsPsTWBXzkQmZbs8FtA7jQaztQGzSxRDo",
  "itemId": "01KEEVZHGFAHHG7RPI4BHKSDN3A47DLQPW",
  "itemName": "d2548feb-fd83-4d3b-986d-b40f2ceea892.fluid"
}

Specifying an id during upload
When a client is creating a channel or container tree (client uploading the summary or PUSH committing a summary uploaded by the client), the id property can be specified in an If-Match header.

The format for the If-Match Fluid tag would be (including quotes):
"fluid:<tagtype>=<tagvalue>;<tagtype2>=<tagvalue2>"

For container id matching, tag type would be containerid and tag value should be the id to match.

Container creation request specifying id (headers only):
POST https://tenant7b1d82e39de34a88bb230996df041457.spgrid.com/_api/v2.1/drive/items/01KEEVZHH7M44UPERWIBBILXE2ZFSRS3OC/opStream/snapshots/snapshot HTTP/1.1
Prefer: bypassodataserializer
If-Match: "fluid:containerid=bBwAAAAAHAAAA"
Accept: */*
Authorization: Bearer eyJ0eXA...I5PeB-yokd1_ovwsliR71ML5Yg
X-ExpFeaturesOptIn: 30149
X-ExpFeaturesOptOut: 31255
SPResponseGuid: 4151cc20-c0f9-47cd-937a-a6648cbb2cae
X-TestName: Spo.Test.Large.Fluid.FluidTests.TestCreateContainerWithIdAsync
X-TestOwner: marcmas
X-TestExecutionId: 4151cc20-c0f9-47cd-937a-a6648cbb2cae
Content-Type: application/json; charset=utf-8
Host: tenant7b1d82e39de34a88bb230996df041457.spgrid.com
Content-Length: 235
Expect: 100-continue

https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!lql55Wf6D0qBqgrMMcpaiDshzUolNf1DofbCZqkstIk8wHnov-bCQ6pHMry6gSbx&item=016K3AXJCD5PDDJIUTAVBJX2LKBGMZZGN5&file=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fmarcmas_ntdev_microsoft_com&siteUrl=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fmarcmas_ntdev_microsoft_com

**Comment by anthony-murphy** [comment]
related to #5771

**Comment by jatgarg** [comment]
What will happen, if the If-Match header is set and the value is "undefined"? Will it fail the upload summary call?

**Comment by anthony-murphy** [comment]
@marcmasmsft can you answer that?

**Comment by marcmasmsft** [comment]
If the if-match header contains an empty container id, a 400 error will be returned (invalidrequest), e.g.

If-Match: "fluid:containerid=" --> exception thrown

**Comment by jatgarg** [comment]
ok. So I am talking about "undefined" as header and not empty. What will be the response in that case?

**Comment by anthony-murphy** [comment]
I think undefined === emtpy in a header

**Comment by anthony-murphy** [comment]
actually, if the above is the string, then the value you are passing is the string `"undefined"`, which will almost certainly be an error

**Comment by jatgarg** [comment]
Yes wanted to confirm as then we should always have the ackHandle for the last summary and need to assert that. I see a case in container attach() where we are passing undefined as ackHandle while uploading summary.

**Comment by marcmasmsft** [comment]
For SPO, undefined would be treated as a string (it's not a special value) so we'd try to match it against the existing handle; this would fail because the id would be in an invalid format (fluidinvalidnodeid)

**Comment by anthony-murphy** [comment]
If we don't have an ackHandle we should not set the header. No need to assert, at least to start with

**Comment by jatgarg** [comment]
Yeah, I was thinking about same and then we can go on and fix the other case.

**Comment by jatgarg** [comment]
Closing after the PR.
