### ISSUE TITLE
ContainerRuntime Errors Loses Properties when Proxied to Container

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#6850]
## Work Item

In both closeFn and raiseContainerWarning on the container runtime we proxy errors to the loader layer, this results in losingcontainerRuntime properties, like runtime version

we should ensure errors that move through the runtime get annotated with the logger properties

**Comment by kenluck2001** [comment]
In the file `packages\runtime\container-runtime\src\containerRuntime.ts`, It seems that error is encapsulated in the call with the signature
` this.closeFn(CreateContainerError(error));`

For raiseContainerWarning,
packages\runtime\container-runtime\src\containerRuntime.ts
```
    public readonly raiseContainerWarning = (warning: ContainerWarning) => {
        this.context.raiseContainerWarning(warning);
    };
```
	
	
How to use it
```
	this.summaryManager.on("summarizerWarning", this.raiseContainerWarning);
```			
I am not sure of how to proxy a logger, since there is no logger in the source code

**Comment by anthony-murphy** [comment]
For both container close and raise error, we proxy from runtime, to container context, to container and finally log at the container layer. However, this loses information, specifically it loses the runtime version which is a common property set on all logs generated on the runtime: https://github.com/microsoft/FluidFramework/blob/bd8c094220ff9ae8a4defe8e7423ffa9b63f911a/packages/runtime/container-runtime/src/containerRuntime.ts#L536-L540
 
I haven't dug more deeply here, but there could be other loggers at deeper layers, like data store runtime, or like the summarizer which are also losing properties. 

This is related to some of the work @markfields  is doing, and he has some open PR that should help here.

A very rough idea for a solution here is to add those common properties to the error in the functions that proxy up the stack, for for instance, in https://github.com/microsoft/FluidFramework/blob/bd8c094220ff9ae8a4defe8e7423ffa9b63f911a/packages/runtime/container-runtime/src/containerRuntime.ts#L1476-L1478
we would add the properites from the logger to the error before passing the error to the context

**Comment by kenluck2001** [comment]
@anthony-murphy thanks so much for the clear explanation. I am thinking that I should not break the contract by adding an extra argument which will break existing function. I think adding a field in sendEvent inside the implementation of the logContainerError which is called when raiseContainerWarning is called

packages\loader\container-loader\src\container.ts
```
    public raiseContainerWarning(warning: ContainerWarning) {
        // Some "warning" events come from outside the container and are logged
        // elsewhere (e.g. summarizing container). We shouldn't log these here.
        if (warning.logged !== true) {
            this.logContainerError(warning);
        }
        this.emit("warning", warning);
    }

    // Please avoid calling it directly.
    // raiseContainerWarning() is the right flow for most cases
    private logContainerError(warning: ContainerWarning) {
        this.logger.sendErrorEvent(
		{ eventName: "ContainerWarning",
		  runtimeVersion: pkgVersion		
		}, warning);
    }
```
