### ISSUE TITLE
MissingAudienceMember event is hit rather often

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6910]
Latest ODSP TAP20 scalability run has almost 8K fluid:telemetry:Container:MissingAudienceMember events
I also easily rerpo'd it by running shared-text example. This is for 17K container sessions (so every other container session experiences an event on average).
This is newly added event that tells us that Audience is not consistent because signals were coming out of order. Given these big numbers, we should assess what do do next.

**Comment by vladsud** [comment]
Worth adding that only interactive clients hit 99% of these errors (i.e. not summarizer clients), there were only 12K interactive container sessions. There were only 84 hits for summarizer client.

@GaryWilber - FYI, please take a look at this issue (and thread in Teams).
What is really suspicious is that these errors are not randomly spaced out in time, they are grouped at the end of the run.

**Comment by GaryWilber** [comment]
@vladsud When you say `I also easily rerpo'd it by running shared-text example` does that mean it repros easily in routerlicious too? I want to know if this is a common issue between ODSP & R11s

**Comment by vladsud** [comment]
I have not tries, @heliocliu - any chance you can poke around and see how easy it is to repro?
@GaryWilber - FRS also runs their own tests. Not sure how often, but we can get stats RE how often they see these events in their runs.

**Comment by anthony-murphy** [comment]
The number of events being logged here is also very very high, i would consider that in itself a release blocker for the next version of the fluid framework. @heliocliu what are the next steps here, looks like there are bugs in the area, and the new event is way too chatty

<HTML><HEAD></HEAD><BODY>
		<p class="cs95E872D0"><span class="cs97EF4E27">Execute: [<a class="cs7274B9C9" href="https://dataexplorer.azure.com/clusters/https%3a%2f%2fkusto.aria.microsoft.com/databases/742fa5a288b045e5beab1a2b8e445a71?query=H4sIAAAAAAAEAG2OQUvDQBCF74H8hyWnBNKi10AOYq%2f12GvYJG91IDsrs7O1EX%2b8a20Uwes3b973gnM0YXBLonlwziYN3ioFHiASpPgwby8QmINVO%2bAM1ifrYfreVNefTrHAQ2XtHgOrJYZ0R4qR%2bPkhzQSecIQfIVXuwkXBszlDYlaY3pBzNUUOCv%2bqa321SGIlj9N3qGnNP%2fQGl2BnyJYsfw2eOGw8a2Iao0qeVN%2fU7V1rMlnAG2l2xDMuwdWCL4SfQ1vtq2Z33%2bT2mLy3Qu8wU8h76saM6x9XWZTFJ5QRe4lTAQAA"><span class="csDC89E173">Web</span></a></span><span class="cs97EF4E27">] [<a class="cs7274B9C9" href="https://kusto.aria.microsoft.com/742fa5a288b045e5beab1a2b8e445a71?query=H4sIAAAAAAAEAG2OQUvDQBCF74H8hyWnBNKi10AOYq%2f12GvYJG91IDsrs7O1EX%2b8a20Uwes3b973gnM0YXBLonlwziYN3ioFHiASpPgwby8QmINVO%2bAM1ifrYfreVNefTrHAQ2XtHgOrJYZ0R4qR%2bPkhzQSecIQfIVXuwkXBszlDYlaY3pBzNUUOCv%2bqa321SGIlj9N3qGnNP%2fQGl2BnyJYsfw2eOGw8a2Iao0qeVN%2fU7V1rMlnAG2l2xDMuwdWCL4SfQ1vtq2Z33%2bT2mLy3Qu8wU8h76saM6x9XWZTFJ5QRe4lTAQAA&amp;web=0"><span class="csDC89E173">Desktop</span></a></span><span class="cs97EF4E27">] [<a class="cs7274B9C9" href="https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:kusto.aria.microsoft.com,database:742fa5a288b045e5beab1a2b8e445a71,type:Kusto)&amp;query=H4sIAAAAAAAEAG2OQUvDQBCF74H8hyWnBNKi10AOYq%2f12GvYJG91IDsrs7O1EX%2b8a20Uwes3b973gnM0YXBLonlwziYN3ioFHiASpPgwby8QmINVO%2bAM1ifrYfreVNefTrHAQ2XtHgOrJYZ0R4qR%2bPkhzQSecIQfIVXuwkXBszlDYlaY3pBzNUUOCv%2bqa321SGIlj9N3qGnNP%2fQGl2BnyJYsfw2eOGw8a2Iao0qeVN%2fU7V1rMlnAG2l2xDMuwdWCL4SfQ1vtq2Z33%2bT2mLy3Qu8wU8h76saM6x9XWZTFJ5QRe4lTAQAA&amp;runquery=1"><span class="csDC89E173">Web (Lens)</span></a></span><span class="cs97EF4E27">] [<a class="cs7274B9C9" href="https://kusto.aria.microsoft.com/742fa5a288b045e5beab1a2b8e445a71?query=H4sIAAAAAAAEAG2OQUvDQBCF74H8hyWnBNKi10AOYq%2f12GvYJG91IDsrs7O1EX%2b8a20Uwes3b973gnM0YXBLonlwziYN3ioFHiASpPgwby8QmINVO%2bAM1ifrYfreVNefTrHAQ2XtHgOrJYZ0R4qR%2bPkhzQSecIQfIVXuwkXBszlDYlaY3pBzNUUOCv%2bqa321SGIlj9N3qGnNP%2fQGl2BnyJYsfw2eOGw8a2Iao0qeVN%2fU7V1rMlnAG2l2xDMuwdWCL4SfQ1vtq2Z33%2bT2mLy3Qu8wU8h76saM6x9XWZTFJ5QRe4lTAQAA&amp;saw=1"><span class="csDC89E173">Desktop (SAW)</span></a></span><span class="cs97EF4E27">] <a class="cs7274B9C9" href="https://kusto.aria.microsoft.com/742fa5a288b045e5beab1a2b8e445a71"><span class="cs6B773703">https://kusto.aria.microsoft.com/742fa5a288b045e5beab1a2b8e445a71</span></a></span><span class="cs1B16EEB5"><br/></span><span class="csAE2AFBE6">office_fluid_ffautomation_error</span></p><p class="cs95E872D0"><span class="csB8FFDFF9">| </span><span class="cs20C56D93">where</span><span class="csB8FFDFF9"> </span><span class="csCE50032C">Data_eventName</span><span class="csB8FFDFF9"> == </span><span class="cs6BDEBD5E">&quot;fluid:telemetry:Container:MissingAudienceMember&quot;</span></p><p class="cs95E872D0"><span class="csB8FFDFF9">| </span><span class="cs20C56D93">extend</span><span class="csB8FFDFF9"> </span><span class="csCE50032C">version</span><span class="csB8FFDFF9"> = </span><span class="cs2E36FA6C">iff</span><span class="csB8FFDFF9">(</span><span class="cs2E36FA6C">isnotempty</span><span class="csB8FFDFF9">(</span><span class="csCE50032C">Data_runtimeVersion</span><span class="csB8FFDFF9">), </span><span class="csCE50032C">Data_runtimeVersion</span><span class="csB8FFDFF9">, </span><span class="csCE50032C">Data_loaderVersion</span><span class="csB8FFDFF9">)</span></p><p class="cs95E872D0"><span class="csB8FFDFF9">| </span><span class="cs20C56D93">extend</span><span class="csB8FFDFF9"> </span><span class="csCE50032C">minorVersion</span><span class="csB8FFDFF9"> = </span><span class="cs2E36FA6C">substring</span><span class="csB8FFDFF9">(</span><span class="csCE50032C">version</span><span class="csB8FFDFF9">,0, </span><span class="cs2E36FA6C">strlen</span><span class="csB8FFDFF9">(</span><span class="csCE50032C">version</span><span class="csB8FFDFF9">)-</span><span class="cs2E36FA6C">indexof</span><span class="csB8FFDFF9">(</span><span class="cs2E36FA6C">reverse</span><span class="csB8FFDFF9">(</span><span class="csCE50032C">version</span><span class="csB8FFDFF9">),</span><span class="cs6BDEBD5E">&quot;.&quot;</span><span class="csB8FFDFF9">)-1)</span></p><p class="cs95E872D0"><span class="csB8FFDFF9">| </span><span class="cs20C56D93">summarize</span><span class="csB8FFDFF9"> </span><span class="cs2E36FA6C">count</span><span class="csB8FFDFF9">() </span><span class="cs2E36FA6C">by</span><span class="csB8FFDFF9"> </span><span class="csCE50032C">minorVersion</span></p><p class="cs95E872D0"><span class="csB8FFDFF9">&nbsp;</span></p><p class="cs95E872D0"><span class="cs1B16EEB5">&nbsp;</span></p>

minorVersion | count_
-- | --
0.45 | 84157

**Comment by anthony-murphy** [comment]
looks like we have a bunch of end to end tests that hit this reliably

```

office_fluid_ffautomation_error
| extend version = iff(isnotempty(Data_runtimeVersion), Data_runtimeVersion, Data_loaderVersion)
| extend minorVersion = substring(version,0, strlen(version)-indexof(reverse(version),".")-1)
| summarize countif(Data_eventName == "fluid:telemetry:Container:MissingAudienceMember"), make_set(Data_driverType), count() by minorVersion, Data_testName
| where countif_ >= count_
| sort by countif_ desc 

```

**Comment by anthony-murphy** [comment]
i think there is a bug here where we don't wait util we are connected before logging this error, so inital clients may not have even been populated yet

**Comment by vladsud** [comment]
I've looked at couple sessions, and this problem always happens 1ms after connection is established.
I also reliably repro this problem with a single client on a new document using start:spo-df workflow with any sample - whenever first op (edit) happens, connection transitions to "write" and error is hit. I.e. we observe it with same container instance, but it complains about old clientID (verified that).

That looks to be due to initial signals processing right after firing "connect" event in setupNewSuccessfulConnection, and thus some kind of race between initialSignals & initialClients (as initialSignals may contain signals that are delivered while we are waiting for connection handshake, and thus may come out of order relative to connect_document_success message).
I can confirm that if I remove processing of initialSignals, I no longer see it.

I tried to move processing of initialSignals above where "connect" event is raised and constrain logging to not happen in disconnected state (i.e. ignore errors from initialSignals). This does not help as queues always process events on clean stack, so it's async relative to setupNewSuccessfulConnection, and thus moving it around does not help (unless we convert it to processing synchronously, which is not good direction to pursue). Or, we keep some metadata to ignore such signals that came through initial path

**Comment by anthony-murphy** [comment]
I don't fully know the flow here, but this also looks like it could be part of it

https://github.com/microsoft/FluidFramework/blob/f80bccdb377a3a304c1b055ae5e268653ec51ce2/packages/loader/container-loader/src/container.ts#L1569-L1582

**Comment by vladsud** [comment]
I've confirmed that the conflict (or reordering) happens due to early handler. I.e. initialClients & initialSignals are in sync with each other, and all signals that come after that are Ok too (that's not 100% guaranteed, but at least that's the case in all my experiments).
But early signal handler is the one who is causing trouble - it observe events out of order relative to above, and thus things go in wrong direction. We have same problem with ops, but there at least we can detect such cases and self-correct, but not here.

Capturing signals before connection is fully established does not buy us anything, so dropping them - this also simplified code :)

**Comment by anthony-murphy** [comment]
Still seeing quite a few hits here. reopening as i think this still need further investigation

**Comment by heliocliu** [comment]
I can take a look at this further tonight/tomorrow, then remove the event later this week before the release if we're not in a good spot at that point

**Comment by anthony-murphy** [comment]
it may be ok to release now, but i'd like someone to look at it, as we may get questions from partners about this event given its frequency.

**Comment by heliocliu** [comment]
Took a look and it seems to be essentially what @vladsud described earlier with establishing the initial connection, with the race condition between signal processing and connecting (and clearing the audience).  I suspect waiting until we're fully connected (instead of just connecting) before logging any errors would resolve the vast majority of hits, but doesn't actually _fix_ the race condition.  Gonna go ahead with that change and continue monitoring.

**Comment by anthony-murphy** [comment]
I guess i still don't understand if the race condition matters, like what is the impact for consumers? is the audience incorrect? do we emit spurious events?

**Comment by vladsud** [comment]
Race condition likely does not matter, so we can even remove the logging statement.
But it also would be nice to understand if outside of connectivity we have some out of order events. That would influence our confidence in Audience itself, as well as any other workflows we might want to build using signals (for example, probabilistic leader election for "read" clients).

**Comment by anthony-murphy** [comment]
That makes sense, just wanted to double check. Anecdotally there does seem to be issues around audience based on feedback. Whether these issues are real or perceived is unclear, and possibly unimportant, as if the issues are perceived then there is likely too much non-obvious complexity leading to bad user assumptions. This seems likely to be the case given that the behavior of this log event wasn't even obvious to us.

 I'm trying to understand what the next step here are. @heliocliu i see you are changing the log to only log once connected. Is there a hypothesis you are trying validate? Will you be monitoring this log event and come up with next steps based on observed behavior? My guess regardless of what we discover with this event there may still be need for further investigation here. Are there specific scenarios we are trying to validate? Can we write tests for those scenarios?

**Comment by heliocliu** [comment]
@anthony-murphy I'm going to remove the log event instead of only logging while connected, per Vlad's feedback and the actual severity of the error case.  The specific scenarios I was targeting were out of order signals and dropped signals, but aside from what Vlad found and fixed around `initialSignals` all the logging we've seen has not been indicative of anything wrong (and has been an issue with the logging statement itself).  Checking connected was to try to reduce the error there, but it's inherently tied to a (valid) race condition with client disconnects/reconnects so it wasn't clear the resultant telemetry wouldn't still be all noise.

From the feedback I've seen about audience, it mostly revolves around how what it provides is very raw and unintuitive, and as a result requires a lot of supporting code to be really useful, which the `ServiceAudience` classes attempt to address (such as by ignoring summarizer clients, maintaining more descriptive `IMember` objects instead of just `clientId`s, self-identification, etc).  The other reason I felt it was okay to remove the logging is because the scenario is ultimately unimportant to the user because it needs to be accounted for anyway.  I think our follow up here is to acknowledge that there are legitimate scenarios with signals where you can get these sorts of de-syncs, and to provide good guidance/examples on how to handle them.  In the audience's case, that would mean things like using the audience's current member list as the source of truth (vs app-accumulated metadata on members) to guard against member desync as a result of lost signals or member changes during disconnects.

**Comment by anthony-murphy** [comment]
Thanks for taking a look @heliocliu. that all seems reasonable to me.
