### ISSUE TITLE
DeltaManager should not be exported from container-loader package

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6930]
It's a private class to loader layer, everybody should use only IDeltaManager.
The biggest reason why it's hard to fix it - packages\test\functional-tests\src\test\containerRuntime.spec.ts
It should stop using actual class and leverage a mock implementation.

The only other thing that blocks it (but to much smaller degree) is @fluid-internal/local-server-tests.

This is not urgent, but it causes changes to container-loader.apo.md on any change in DeltaManager, which is not ideal.
Plus it allows people to cast interface to a class and poke at internals.

**Comment by vladsud** [comment]
@ssimic2, since you (and folks around you) are poking at API visibility, can you please take a look? It would be great not to over-expose our guts, to remove temptation to cast interfaces to concrete classes and poke at them.

**Comment by agarwal-navin** [comment]
This was fixed via https://github.com/microsoft/FluidFramework/pull/7634
