### ISSUE TITLE
facetCodes are not making it to telemetry

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6943]
Here is what I see in telemetry for ODSP errors:
"facetCodes":"REDACTED (arbitrary object)"

We need to have facetCodes in telemetry. Especially if we are going to remove response (see #6901)

**Comment by markfields** [comment]
Yes I'm planning on fixing this next

**Comment by markfields** [comment]
Btw this is another reason I find the LoggingError paradigm of logging everything on it dubious - there's not type-checking on the kinds of values you put. Using addTelemetryProperties is much better.

**Comment by markfields** [comment]
@vladsud  I think you can close this now.  #6958 doesn't actually change anything here, but highlights that this info is already present in the `response` field (and will continue to be so).

**Comment by vladsud** [comment]
I think that's fine, but I'd keep it to ensure we find a way not to log this message in telemetry (if we do not intend to get facet codes into telemetry). I.e. this message should always be followed by some fix that gets rid of this message in one way or another, unless it comes from 3rd party.

**Comment by markfields** [comment]
Moving out of August though

**Comment by markfields** [comment]
@vladsud - Your concern is covered by #6139.  I'm closing this one.  If you want to see the facets, look at the `response` property in telemetry.
