### ISSUE TITLE
Use specific imports from loadash

### ISSUE THREAD

**Issue by pragya91** [microsoft/FluidFramework#6971]
A few packages within FluidFramework import the complete library of loadash via imports like: 
`import _ from lodash`. While it is convenient, it increases the bundle size of the packages multi folds (~6kb gzipped).
Would be nice to update the imports to follow the following pattern to minimize the bundle sizes:
```
import isNumber from lodash/isNumber
import isArray from lodash/isArray
.
.
```

**Comment by heliocliu** [comment]
Main offender here is PropertyDDS; all other client usages import specific internal modules (which is kind of contradictory to the global no-internal-modules eslint warning we have).  This should be as straightforward as importing just what's used.

**Comment by DLehenbauer** [comment]
According to [this article](https://medium.com/@martin_hotell/tree-shake-lodash-with-webpack-jest-and-typescript-2734fa13b5cd), we should be able to get tree-shaking with the `import { isNumber, isArray } from "lodash"` syntax.

**Comment by heliocliu** [comment]
Iirc there were some issues around tree shaking from the bohemia side.  @christiango do you know if that's still the case/do you know who might know more about it now?

**Comment by christiango** [comment]
There aren't any known issues with tree shaking on our end.

**Comment by heliocliu** [comment]
I must have misremembered something then 🤔 Thanks for confirming

**Comment by heliocliu** [comment]
duping to #3925 since propertydds is the last project to be doing this
