### ISSUE TITLE
0x185 /* "Channel not found" */ asserts in stress tests

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6972]
I've started to see a lot of these events today in our own stress tests when running them manually:

  fluid:telemetry ChannelDisposeError {"fluidDataStoreId":"default","category":"error","error":"0x185","errorType":"dataProcessingError","message":"0x185","canRetry":false,"messageClientId":"39753bdf-a144-406e-9c1c-f866e6eb6ebf","messageSequenceNumber":6242,"messageClientSequenceNumber":12,"messageReferenceSequenceNumber":6235,"messageMinimumSequenceNumber":0,"messageTimestamp":1628014864266,"clientType":"noninteractive/summarizer","loaderVersion":"0.45.0","containerId":"65cf91cc-fee8-4aa4-99a6-8fcad8b63a52","docId":"KEyH1Z8Ba27KxsjOjKb6tfUZjHKiywxhR%2FDytWr0JvI%3D","containerAttachState":"Attached","containerLoaded":true,"runtimeVersion":"0.45.0","dmInitialSeqNumber":6157,"dmLastKnownSeqNumber":13922,"containerLoadedFromVersionId":"bBw0YAAAHAAAA","dmLastMsqSeqNumber":13922,"dmLastMsqSeqTimestamp":1628015356735,"dmLastMsqSeqClientId":null,"loaderId":"d78e8299-13db-4786-b97d-d26178c5db76","runId":"36","driverType":"odsp"} tick=826764 Error
  fluid:telemetry     at Object.assert (E:\Git\FluidFramework3\node_modules\@fluidframework\common-utils\dist\assert.js:17:15)
  fluid:telemetry     at RuntimeWithRequestHandler.processChannelOp (E:\Git\FluidFramework3\packages\runtime\datastore\dist\dataStoreRuntime.js:631:24)
  fluid:telemetry     at RuntimeWithRequestHandler.process (E:\Git\FluidFramework3\packages\runtime\datastore\dist\dataStoreRuntime.js:350:26)
  fluid:telemetry     at RemotedFluidDataStoreContext.bindRuntime (E:\Git\FluidFramework3\packages\runtime\container-runtime\dist\dataStoreContext.js:379:25)
  fluid:telemetry     at RemotedFluidDataStoreContext.realizeCore (E:\Git\FluidFramework3\packages\runtime\container-runtime\dist\dataStoreContext.js:184:14)
  fluid:telemetry     at runMicrotasks (<anonymous>)
  fluid:telemetry     at processTicksAndRejections (internal/process/task_queues.js:93:5) +0ms

**Comment by agarwal-navin** [comment]
The error is not seen anymore when running the stress tests. The issue is kept open to look at telemetry data for stress tests and try to figure out the root-cause for this issue.

**Comment by heliocliu** [comment]
Telemetry for failing runs shows a lot of other errors around odsp communication, which lead to this error.  Additionally all instances of this error were in the same window around 8/2 - 8/5 so I'm comfortable attributing this to odsp since there appear to have been service issues around the same time.
