### ISSUE TITLE
Consider options to protect against accidental document modification by the summarizer

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#698]
In [this issue](https://office.visualstudio.com/OC/_workitems/edit/3816449) the summarizer creates new components in the container, causing a bug.  It seems to go against the spirit of summarization to allow the summarizer to make substantial modifications to the container.  Can we better restrict it to "observe and report" (e.g. maybe better restrict the types of ops that can be sent from the summarizer)?  Or make it more obvious for apps/components to learn that they are not summarizer-safe?

**Comment by vladsud** [comment]
It feels like it should not be that hard to do, given that we pause ops (or could pause outbound) and can always check that outboud is empty before submitting summary op. Or something like that.
@arinwt - is this something you can take a look, design and describe such that someone else can pick it up? Seems like it might be good first issue, if we have proper instructions.

**Comment by ChumpChief** [comment]
Closing this - I think it's still interesting to consider certain clients restricting themselves from certain behaviors but I don't think it's been an issue since this was first encountered.
