### ISSUE TITLE
Perf: Move to MongoDB 3.6+ and remove redundant JSON.stringify() calls

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#699]
In the "op storm" scenario, JSON.stringify() accounts for a large chunk of the time spent in SparseMatrix v2.

Part of the reason is that we're calling it 3-4x per op:
1. Once in `makeHandlesSerializable()`
2. Once to stringify the message contents.
3. Once internally inside Socket.IO to stringify the entire message.
4. If the payload is large, we call stringify to chunk the message [].

(1) is tracked by a separate issue (#697)
(2) was required to work around MongoDB special [character restrictions](https://stackoverflow.com/questions/9759972/what-characters-are-not-allowed-in-mongodb-field-names).  However, these restrictions [have been removed](https://github.com/mongodb/docs/commit/4a3236ff70e9f64c3bce7cdb411aa53bed8f6bc4) for nested objects starting in v3.6.
(4) might be avoided by constructing the chunked payload manually via less expensive string concats / string template ops.

Also note the Scribe service re-stringifies summaries to work around the same MongoDB issue.

**Comment by vladsud** [comment]
@DLehenbauer, can you please take a look if this item is still worth having? You addressed some of these problems lately for all code that deals with handles, right?
