### ISSUE TITLE
Need reliable way for ops to reach SPO for summaries to succeed (single-stage summary commit)

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7021]
We are getting these errors from PUSH as a summary nack:
fluid:telemetry:Summarizer:Running:Summarize_cancel Failed to summarize the document (fluidInvalidOperation).

It means  push tried to post a summary but SPO didn't have all the ops leading to that summary, so SPO didn't let the summary go through. Because the summary op processing logic is separate from the logic that inserts ops into redis, there is a chance we try to post the summary without having the prerequisite ops.
Whenever we post a summary to spo, we also provide all the redis ops with that

If clients requests a flush (via PUSH new flush API), it would get back the sequence number of the last flushed op. and that could be used to check if the summary will succeed or not. Client can retry couple times (with delay).

We can also make it so when push gets that error, it could retry posting the summary a few times instead of immediately sending a summary nack.

This is another case of something that would be solved if Push inserts ops into redis after ordering and before broadcasting/further processing.

**Comment by vladsud** [comment]
We should experiment with two approaches:
1. Flushing ops (on client side, or server side) with retries
2. Putting ops to redis before broadcasting.

#2 is preferred unless it adds too much latency.

**Comment by vladsud** [comment]
Note that this is a race and it's possible we would not see it in well working system as these steps happen:
1. Client generates summary payload
2. Client uploads summary payload to SPO
3. Client issues summaryOp
4. Scribe processes it and flushes ops to SPO.

Ops should really take a long time to hit redis for this problem to happen.
As Gary pointed out, the pending ops app got into a bad state, and it was taking over 30 seconds for ops to reach redis.
If that is fixed and we should not see such unbelievable latencies, then maybe not doing anything is an option.

**Comment by vladsud** [comment]
@GaryWilber, do we need to do anything here, or should we just close / punt it?
There are only 11 cases in last run, which is very low and standard recovery is fine for such low numbers.

**Comment by GaryWilber** [comment]
@vladsud Sounds like we can punt it. I think it's worth leaving open since it's still something that can happen and does feel like an issue we should fix at some point. If the error count remains low in future test runs, we can likely wait for the single-stage summary work to solve this.

Tagging #5771 for reference

**Comment by vladsud** [comment]
Ok, I'll keep it around as it has useful data, and suggestions on need to have retry logic when flushing ops will be more more needed with single-summary commit (as timeframes will be compressed, so more likely to hit it).
I'll push it out a bit to September at the moment, rename title, and assign to @anthony-murphy to track as end-to-end work for single-stage commit. Rebalancing is likely required, we will assign to right person as we move forward with single-stage commit.

**Comment by anthony-murphy** [comment]
From my understanding the client providing protocol tree is blocked on ODSP work the pull ops from push on summary upload, won't that solve this issue as well?

**Comment by vladsud** [comment]
Yes, it will. I'll prototype a solution, we can experiment with in in TAP40 runs and see if we like it.
PUSH can also experiment with not doing extra flushes on summaries for such clients to see where the gaps are (all in controlled environment without change in experience for prod).

**Comment by vladsud** [comment]
Resolving, as https://github.com/microsoft/FluidFramework/pull/7086 implemented functionality.
