### ISSUE TITLE
Closed summarizer may log fluid:telemetry:Summarizer:Running:SummarizeTimeout & fluid:telemetry:Summarizer:Running:SummaryAckWaitTimeout events!

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7023]
Here is an example of query.

[Logs](https://ms.portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F93543f02-938d-4016-9d15-9cc4329b7033%2FresourceGroups%2FRegressionPrevention%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2FFluidClient/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0XNsQ0CMQxG4Z4pTEpGuJ4JmMAkPyLS2Ua2AwpieK66a58%252B6dURaXJ9QzPo9KPPEw66UDVN7hpU4G5eiLVt%252BXz0xzp6WxIrBOlzuQ0R9v7Fjg%252BbZiSss2yHME%252B6T8ouiGR5UUPUPztPLY%252BIAAAA/timespan/P1D) from ODSP stress test.

customEvents 
| where timestamp > ago(5d)
| where customDimensions.containerId == "9ce04c0a-1dbd-4309-b5af-ba903a83f8d8"
| project timestamp, name, customDimensions.reason, customDimensions.error, customDimensions.category
| order by timestamp asc

  | 8/5/2021, 9:16:47.081 AM | fluid:telemetry:Container:Creating Container noninteractive/summarizer |   |   | generic |  
  | 8/5/2021, 9:16:47.082 AM | fluid:telemetry:Container:Load_start |   |   | performance |  
  | 8/5/2021, 9:16:47.587 AM | fluid:telemetry:OdspDriver:GetWebsocketToken_GetToken_end |   |   | performance |  
  | 8/5/2021, 9:16:47.640 AM | fluid:telemetry:OdspDriver:EpochLearnedFirstTime |   |   | generic |  
  | 8/5/2021, 9:16:47.643 AM | fluid:telemetry:Container:ConnectionStateChange_Connecting |   |   | performance |  
  | 8/5/2021, 9:16:48.551 AM | fluid:telemetry:OdspDriver:TreesLatest_GetToken_end |   |   | performance |  
  | 8/5/2021, 9:16:49.016 AM | fluid:telemetry:OdspDriver:ObtainSnapshot_end |   |   | performance |  
  | 8/5/2021, 9:16:49.016 AM | fluid:telemetry:OdspDriver:TreesLatest_end |   |   | performance |  
  | 8/5/2021, 9:16:49.018 AM | fluid:telemetry:DeltaManager:enqueueMessages | DocumentOpen_pending |   | performance |  
  | 8/5/2021, 9:16:49.021 AM | fluid:telemetry:OdspDriver:GetDeltas_end |   |   | performance |  
  | 8/5/2021, 9:16:49.022 AM | fluid:telemetry:CodeLoad_end |   |   | performance |  
  | 8/5/2021, 9:16:49.022 AM | fluid:telemetry:OdspDriver:CacheOpsRetrieved |   |   | performance |  
  | 8/5/2021, 9:16:49.026 AM | fluid:telemetry:ExternalBlobsInSnapshot |   |   | generic |  
  | 8/5/2021, 9:16:49.026 AM | fluid:telemetry:ContainerRuntime:ContainerLoadStats |   |   | generic |  
  | 8/5/2021, 9:16:49.044 AM | fluid:telemetry:Container:ConnectionStateChange_Connected |   |   | performance |  
  | 8/5/2021, 9:16:49.045 AM | fluid:telemetry:ScheduleManager:DeltaScheduler:InboundOpsProcessingTime |   |   | generic |  
  | 8/5/2021, 9:16:49.045 AM | fluid:telemetry:OpPerf:GetDeltas_OpProcessing |   |   | performance |  
  | 8/5/2021, 9:16:49.046 AM | fluid:telemetry:Container:Load_end |   |   | performance |  
  | 8/5/2021, 9:16:49.046 AM | fluid:telemetry:Container:Request_end |   |   | performance |  
  | 8/5/2021, 9:16:49.047 AM | fluid:telemetry:Summarizer:RunningSummarizer |   |   | generic |  
  | 8/5/2021, 9:16:50.033 AM | fluid:telemetry:Summarizer:StoppingSummarizer | parentNotConnected |   | generic |  
  | 8/5/2021, 9:16:50.035 AM | fluid:telemetry:Container:ConnectionStateChange_Disconnected | socket.io: disconnect: socket.io: server_disconnect: TokenExpired |   | performance |  
  | 8/5/2021, 9:16:50.035 AM | fluid:telemetry:Container:noWaitOnDisconnected |   |   | generic |  
  | 8/5/2021, 9:16:50.036 AM | fluid:telemetry:ContainerRuntimeDisposed |   |   | generic |  
  | 8/5/2021, 9:16:50.036 AM | fluid:telemetry:Container:Container Closed |   |   | generic |  
  **| 8/5/2021, 9:16:50.037 AM | fluid:telemetry:Container:ContainerClose |   |   | generic |**  
  | 8/5/2021, 9:26:49.049 AM | fluid:telemetry:Summarizer:Running:SummaryAckWaitTimeout |   |   | error |  
  | 8/5/2021, 9:26:49.053 AM | fluid:telemetry:Summarizer:Running:GenerateSummary |   |   | generic |  
  | 8/5/2021, 9:26:49.053 AM | fluid:telemetry:Summarizer:Running:Summarize_cancel | maxTime | disconnected | generic |  
  | 8/5/2021, 9:26:49.059 AM | fluid:telemetry:Summarizer:Running:RefreshLatestSummaryGetSnapshot_end |   |   | performance |  
  | 8/5/2021, 9:26:49.394 AM | fluid:telemetry:OdspDriver:getVersions_end |   |   | performance |  
  | 8/5/2021, 9:26:49.824 AM | fluid:telemetry:OdspDriver:fetchSnapshot_end |   |   | performance |  
  | 8/5/2021, 9:26:49.827 AM | fluid:telemetry:Summarizer:Running:RefreshLatestSummaryGetSnapshot_end |   |   | performance |  
  | 8/5/2021, 9:26:49.829 AM | fluid:telemetry:Summarizer:Running:WaitingForSeq_start |   |   | performance |  
  | 8/5/2021, 9:27:09.055 AM | fluid:telemetry:Summarizer:Running:SummarizeTimeout |   |   | performance |  
  | 8/5/2021, 9:27:49.056 AM | fluid:telemetry:Summarizer:Running:SummarizeTimeout |   |   | performance |  
  | 8/5/2021, 9:29:09.056 AM | fluid:telemetry:Summarizer:Running:SummarizeTimeout |   |   | performance |  
  | 8/5/2021, 9:31:49.057 AM | fluid:telemetry:Summarizer:Running:SummarizeTimeout |   |   | performance |  
  | 8/5/2021, 9:37:09.059 AM | fluid:telemetry:Summarizer:Running:SummarizeTimeout |   |   | performance

As you can see, summarizing container was closed, yet it keep going and did a bunch of network requests (looks really weird, they should have failed with "storage is disposed" kind of failure - we definitely see that in other cases, for example in https://github.com/microsoft/FluidFramework/issues/6896). But also a bunch of timers were not cancelled and resulted in a bunch of noise in telemetry, making it look like our stress tests were worse than they are.

**Comment by vladsud** [comment]
@GaryWilber - FYI, this is the case you brought to my attention.

**Comment by vladsud** [comment]
Ok, after latest set of fixes, all the other "real" reasons for summary problems are gone, and this case represents one of the biggest sources of noise in stress tests. I.e. it creates false alarms.
We should prioritize addressing this.

**Comment by vladsud** [comment]
It masks potential P0 bug https://onedrive.visualstudio.com/SPIN/_queries/edit/1172452/?triage=true (which I'm downgrading based on a fact that it looks like real problems are gone and only this noise is remaining).

**Comment by arinwt** [comment]
I think we can do 2 things to address this.
(1) Add more checks for disposed before doing things.
(2) For this specifically, it seems like it could be disposing the Summarizer before it finishes starting which is a race condition.

**Comment by vladsud** [comment]
That's same as #6896, so closing
