### ISSUE TITLE
nyc does not properly cover jest tests

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#7039]
nyc, which we use for code coverage, does not properly cover jest tests and we should use jest's coverage tools for that instead.  In practice, the result is that the nyc report doesn't capture code coverage from jest tests, and nyc can also cause jest puppeteer tests using page.evaluate to fail (where the suggested workaround of excluding files from coverage doesn't work because it's not jest's coverage that's breaking things).

We should:
- update our package.json test scripts to only wrap mocha tests with nyc
- update jest tests to use jest's coverage using the `--coverage` flag
- update jest configs to output the coverage reports somewhere (probably with the nyc reports)
- ensure the ci pipeline configs capture both coverage reports for collection

**Comment by curtisman** [comment]
@DLehenbauer  This might be a regression from switching to c8.   We might want to keep it instrumented using istanbul instead for the jest test if possible?
