### ISSUE TITLE
Reduce Routerlicious Driver Telemerty

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#7061]
## Work Item
The routerlicous driver has some very chatty telemetry. We should move to sampling, or only logging errors for the event producing more than a few events per session:

```
union office_fluid_ffautomation_* 
| summarize count(), todouble(dcount(Session_Id)), make_set(Data_driverType) by Event_Name, Data_eventName
| extend eventsPerSession = count_/dcount_Session_Id
| where set_Data_driverType contains "routerlicious" and set_Data_driverType !contains "odsp"
```
Event_Name | Data_eventName | count_ | dcount_Session_Id | set_Data_driverType | eventsPerSession
-- | -- | -- | -- | -- | --
Office.Fluid.FFAutomation.Performance | fluid:telemetry:RouterliciousDriver:readBlob_end | 3604956 | 133 | [ "routerlicious" ] | 27104.9323308271
Office.Fluid.FFAutomation.Performance | fluid:telemetry:RouterliciousDriver:getDeltas_end | 445036 | 133 | [ "routerlicious" ] | 3346.13533834586
Office.Fluid.FFAutomation.Performance | fluid:telemetry:RouterliciousDriver:getSnapshotTree_end | 326608 | 133 | [ "routerlicious" ] | 2455.6992481203
Office.Fluid.FFAutomation.Performance | fluid:telemetry:RouterliciousDriver:getVersions_end | 325442 | 133 | [ "routerlicious" ] | 2446.93233082707
Office.Fluid.FFAutomation.Performance | fluid:telemetry:RouterliciousDriver:createBlob_end | 11269 | 131 | [ "routerlicious" ] | 86.0229007633588
Office.Fluid.FFAutomation.Performance | fluid:telemetry:RouterliciousDriver:uploadSummaryWithContext_end | 10569 | 132 | [ "routerlicious" ] | 80.0681818181818
Office.Fluid.FFAutomation.Generic | fluid:telemetry:RouterliciousDriver:getVersions_cancel | 2 | 2 | [ "routerlicious" ] | 1
Office.Fluid.FFAutomation.Generic | fluid:telemetry:RouterliciousDriver:uploadSummaryWithContext_cancel | 1 | 1 | [ "routerlicious" ] | 1

**Comment by tanviraumi** [comment]
@znewton Can you take a look into this?
