### ISSUE TITLE
Routerlicious Dirver Support for Client Uploading Protocol Tree

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#7102]
## Work Item
This work is part of #5771. We have support for the ODSP driver already, as that supports an `.app` tree already, so adding the peer tree of  `.protocol` was easy, and creates no problem with existing documents. R11s however does not use and `.app` tree, and uploading in the format coming from the container, { `.app`,  `.protocol`} creates issues for existing documents due to blob path changing. The easiest solution here is to just flatten the tree in the driver, but this creates the possibility for conflicts. Ideally we could detect old documents, and flatten or migrate them in the r11s driver, and upload new documents in the { `.app`,  `.protocol`}  format. currently odsp flattens before giving back to the container, but eventually i'd like to see the snapshot tree format given to the container from the driver to also be in the { `.app`,  `.protocol`}  format.

@tanviraumi @znewton

**Comment by tanviraumi** [comment]
@anthony-murphy Its not clear to me what the issue is. But since we are moving to a similar storage model as ODSP, we are also considering adding the .app node. I don't have a strict timeline yet but let us know if you want this to happen sooner.

**Comment by anthony-murphy** [comment]
this is the pr that added ODSP support: #6127 . If i set `summarizeProtocolTree = true` in the loader options for an existing r11s document summarization will fail, as the r11s driver doesn't understand the summary format  `{ .app, .protocol}`

**Comment by anthony-murphy** [comment]
of we can just say we don't care about existing documents in the r11s case, but that seems disruptive for existing users

**Comment by tanviraumi** [comment]
Can we turn this off inside the driver? I don't want r11s to include protocol tree yet

**Comment by anthony-murphy** [comment]
its not on anywhere yet, and yes. we could make it driver configurable. i guess i don't see why you wouldn't want the client to upload it. scribe can still overwrite it. from a test perspective it would still be good if it was supported in test like local-server and tinylicious.

**Comment by tanviraumi** [comment]
Oh I want it. But not before I add the .app support in scribe and driver. Also you guys should not be blocked until we add those support. So my plan is to keep this turned off until we are ready.

**Comment by anthony-murphy** [comment]
seems fine. i just want the work captured somewhere, as it doesn't seems to be captured in the main work item: https://github.com/microsoft/FluidFramework/issues/5771
feel free to close of re-purpose this it you've got a plan

**Comment by tanviraumi** [comment]
I will keep this open for now and close it once we support ".app" fully
