### ISSUE TITLE
Ability for clients to log server provided information when connecting

### ISSUE THREAD

**Issue by GaryWilber** [microsoft/FluidFramework#7135]
There has been some trouble in recent scale test runs in determining the server environment/builds the client has been running against. We can improve this by having the server return some additional information in `IConnected` (connect_document_success message) and having the client log those properties. We would then be able to look at the client logs and determine what it ran against.

Some examples of what we could log:
- Version/build number
- Region
- Environment (spdf, msit, prod, gov)
- Instance id (virtual machine unique id)

The client would strictly use that information for logging purposes and not use it for real logic.

We could expose it a few different ways:
1. Reuse `supportedFeatures` property and add them in there
2. Add a new property and expose it as a string in a key value format - `correlationProperties: "build=20210812.11;environment=s;region=northcentralus;instanceId=3"`
2. Add a new property and expose it as a object -
```typescript
IConnected
{
     ...,
    correlationProperties: {
        build: "20210812.11",
        environment: "s",
        region: "northcentralus",
        instanceId: 3
    }
}
```

Also not sure if `correlationProperties` is the best name but it seems to fit.

I could also imagine us supporting this in the opposite direction. The client could send `correlationProperties` to the server when connecting and the server could log it. An example of a property to log could be the clients run time version.

+ @vladsud

**Comment by vladsud** [comment]
Probably separate property is a bit better, as we could decide to log it differently (i.e. stringy, or log many properties, like in above case - convert it to have correlationProperties_build, correlationProperties_environment, etc.). Similar (but different) decision can be made for supportFeatures. Keeping it at high level will reduce the depth / size of properties in telemetry.

**Comment by vladsud** [comment]
I think you might have already done it and it's a dup? Please take a look.

**Comment by jatgarg** [comment]
Yes, we have already done it. Closing the issue. I will confirm in telemetry if the server has started passing in the props.
