### ISSUE TITLE
It would be great for fluid:telemetry:Container:ContainerWarning event to have "source" property

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7138]
Consider these two sessions - it's pretty clear where error in coming from based on prior to ContainerWarning events:

| 8/9/2021, 12:27:10.809 PM | fluid:telemetry:OdspDriver:uploadSummary_cancel | Error 412 (Precondition Failed)
| 8/9/2021, 12:27:10.810 PM | fluid:telemetry:OdspDriver:uploadSummaryWithContext_cancel | Error 412 (Precondition Failed)
| 8/9/2021, 12:27:10.812 PM | fluid:telemetry:Container:ContainerWarning | Service busy/throttled: Error 412 (Precondition Failed)

| 8/9/2021, 12:07:14.927 PM | fluid:telemetry:Container:ConnectionStateChange_Disconnected |  Nack: Submit a summary before inserting additional operations
| 8/9/2021, 12:07:14.928 PM | fluid:telemetry:Container:ContainerWarning | Service busy/throttled: Nack: Submit a summary before inserting additional operations

But it's really hard to get that insight in aggregations, i.e. across all sessions understand "source" of issues. In many cases it's self-explanatory (based on error message itself), but it's not necessarily the case, so it would be nice to have that info.

~I believe that's precisely what @markfields envisioned errorCodes for, so I assume we should simply use it here.~

**Comment by markfields** [comment]
I'd say either add reason param to API that raises Container Warning, or update that API to take IFluidErrorBase so it has fluidErrorCode


Btw - Some code outside FF (e.g. Scriptor) passes arbitrary error to raiseContainerWarning or whatever. We should advise folks to call normalizeError with errorCodeIfNone param.
