### ISSUE TITLE
Move all Sequence Examples to SequenceDelta

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#7139]
## Work Item
There are some examples in our repo that use op, rather than sequenceDelta event. These do not work, as processing op correctly is very difficult, and error prone. sequenceDelta is always correct. These legacy examples should be updated or removed.

**Comment by anthony-murphy** [comment]
The work here is to look through our examples, and find places where sequences, like SharedString are being used, and see how that example is processing incoming changes. if it is using the `op` event or a mechanism that is not the `sequenceDelta` event we should transition to the example to the `sequenceDelta` event. we should probably create a sub-work item for each example we need to update, so we can more easily track the work here.

**Comment by tyler-cai-microsoft** [comment]
Tasks
[ ] #7688

**Comment by tyler-cai-microsoft** [comment]
Closing the issue, the Prosemirror issue #7776 got moved to a different issue: #7897
