### ISSUE TITLE
fluid:telemetry:DeltaManager:WrapError as an error results in same error counted multiple times

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7151]
These are the top errors from ODSP TAP 40 scalability run:

| fluid:telemetry:DeltaManager:WrapError | Nack: Submit a summary before inserting additional operations | 16,553 |  
| fluid:telemetry:Container:ContainerWarning | Service busy/throttled: Nack: Submit a summary before inserting additional operations | 16,553

Notice that same error is counted multiple times.
We should either not log it, or make it informative (/ verbose / generic) type of category, such that it does not register as unique error.

**Comment by vladsud** [comment]
And not everything that WrapError complains about results (in terms of final error) in being actually in error table. For example this error results in summary failure but it is retryable error so we recover and never record an error, it would not be in error table if not for WrapError. I.e. this code make incorrect determination on what goes into error table and what does not - it reports it as an error, while the code that deal with it 

  fluid:telemetry:DeltaManager WrapError {"wrappedByErrorInstanceId":"78753463-79c0-4bb7-b7fa-905f01fc34da","category":"error","error":"Error 412 (Precondition Failed)","errorType":"genericNetworkError","errorInstanceId":"02a9e5d8-2d70-4880-829e-4f85c7a8a4e2","statusCode":412,"canRetry":true,"online":"Unknown","facetCodes":"REDACTED (arbitrary object)","response":"{\"error\":{\"code\":\"fluidPreConditionFailed\",\"innerError\":{\"code\":\"fluidLatestSnapshotMismatch\"},\"message\":\"Latest container id mismatch. Actual 'bB4MJAAAHAAAA', provided 'bB9MHAAAHAAAA'.\",\"currentContainerId\":\"bB4MJAAAHAAAA\",\"mismatchedContainerId\":\"bB9MHAAAHAAAA\"}}","innerMostErrorCode":"fluidLatestSnapshotMismatch","sprequestduration":1511,"contentsize":184,"sprequestguid":"5132e69f-700e-c000-646c-4bd368a23765","requestId":"5132e69f-700e-c000-646c-4bd368a23765","xMsedgeRef":"Ref A: FB4D7229A1FD48B49D9099C3E7042144 Ref B: CO1EDGE1519 Ref C: 2021-08-16T21:57:29Z","serverEpoch":"b539de8e-ddb3-4558-b1f8-535720f8807f","message":"Error 412 (Precondition Failed)","clientType":"noninteractive/summarizer","loaderVersion":"0.46.0","containerId":"216e63a8-bcfe-474e-8799-947b4b9bfddd","docId":"S0wH9kItWiPbxm3lwKl0TBONz5zOuCe0SOWOtTvGmOI%3D","containerAttachState":"Attached","containerLoaded":true,"dmInitialSeqNumber":2003,"dmLastKnownSeqNumber":2522,"containerLoadedFromVersionId":"bB9MHAAAHAAAA","dmLastMsqSeqNumber":2499,"dmLastMsqSeqTimestamp":1629151049648,"dmLastMsqSeqClientId":"c732bc34-d19c-452a-a0d4-74124d5af811","loaderId":"97c4b266-6dd4-4f72-bc53-de176112076c","runId":"12","driverType":"odsp"}

**Comment by markfields** [comment]
Yeah I debated whether that should be general log or error log. Full support for switching it.  

Btw - I still say when querying errors let's move towards querying by specific eventNames so we know what scenarios we're even evaluating and how to interpret the errors/counts.
