### ISSUE TITLE
Add timestamp to IConnected message sent on "connect_document_success"

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#7152]
For GC sweep phase, we need the current time in the client for two purposes:
1. Ensuring that a client session can only last for a specific time. After that, the session becomes read-only.
2. Calculating how long objects have been unreferenced for.
For this, we need the initial time when a client was loaded. We can then use this time as reference to get the current local time. This will be the timestamp to the `IConnected` message.

**Comment by agarwal-navin** [comment]
@tanviraumi @GaryWilber We need to add a timestamp to the `IConnected` message sent by Alfred when a client connects. We want to limit the time that a client session can be in write mode. The time in the `IConnected` message, i.e., when the client connects, will be used to determine how long the client's session can be active. This is needed for the GC sweep work and here's some more context of that work:

We want to make sure that content being deleted cannot be brought back by a client. So, we are planning to limit the time for which a client session can be active (`maxSessionActiveTime`). After this time expires, they will need to reload. The idea is to get rid of in-memory references to deleted objects. Once we are sure that no client holds in-memory references to these objects, we will delete them.

To implement this, we need a couple of server timestamps - The time when a summary is generated (`summaryTimestamp`) and the time when a client connects (`connectedTimestamp`). When a client loads, it can remain active for `maxSessionActiveTime` amount of time since the summary it loaded from. Basically, we will set a timeout for: `maxSessionActiveTime - (connectedTimestamp - summaryTimestamp)`.

We already have a way to add `summaryTimestamp` to summaries. We need a timestamp of when a client connects. I would love to get your thoughts on this and if there are other ways of getting the time when a client connects.

**Comment by GaryWilber** [comment]
@agarwal-navin Does this actually require a new property? If we added that property to `IConnected`, would we be sending `Date.now()` every time? Could the client determine it themselves based on when `connect_document_success` is received to them?
Alternatively, clients do listen for their own `join` op when connecting. Can you use that op timestamp for this? That's actually the most accurate time for when clients "join the quorum"

**Comment by agarwal-navin** [comment]
Yes, this requires a new property and the timestamp will have to be added by the server on each `IConncted` message. 
Client time is not reliable since it depends on the system time of the client machine. So, we cannot rely on the client to determine the time themselves. There are couple of problems using the `join` op:
- It is received only by `write` mode clients. However, I was thinking about this and we might not need to reset the session for `read` mode clients since they cannot send ops and hence can't bring unreferenced content back. So, this may not be a problem. I need to think a little more about this.
- If a client loads from a snapshot which is old enough snapshot, there is a time period between getting the `connect_document_success` and `join` op where clients can queue up operations that bring back content that have been deleted.

**Comment by agarwal-navin** [comment]
Ping.
