### ISSUE TITLE
Delete objects that are unreferenced for more than maxUnreferencedTime

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#7204]
Add maxUnreferencedTime that tracks how long an object can be unreferenced before it is eligible for deletion. When GC runs, it will identify objects that have been unreferenced longer than maxUnreferencedTime and delete them.
Note - Instead of deleting these objects immediately, we may want to convert them to tombstones first - https://github.com/microsoft/FluidFramework/issues/7205
We also need to ensure that this content cannot be referenced again. This work is tracked here - https://github.com/microsoft/FluidFramework/issues/7206

To find this out, whether objects are eligible for deletion, we need the concept of "current time". We will use the timestamp of the last processed op as "current time". If there hasn't been any op, we will use the timestamp of the IConnected event as described here -https://github.com/microsoft/FluidFramework/issues/7152.

We cannot use client time as it is unreliable, can be skewed and can differ drastically between clients. Using the timestamp as described above is safe because they will always be less than the actual current time. So, in worst case, the deletion may happen a little late which should be just fine.

**Comment by markfields** [comment]
@agarwal-navin  - 

> So, in worst case, the deletion may happen a little late which should be just fine.

How much delay could be introduced here?  If I connect as write and no one edits the document, would GC get scheduled hours or days into that session?

**Comment by agarwal-navin** [comment]
If a client connects as write and no edit happens, summary / GC will not run and nothing will get deleted. We will delete content only when GC runs.
I can see a scenario where we want to run GC only to find if there is content that can be deleted, delete them and post a summary.  For that, we will probably want to add `timeRemainingToDelete` instead of (or in addition to) unreferenced timestamp.

However, the delay in the description is because of the fact that op timestamp will always be behind the "current" timestamp and depends on when the summarizer client gets ops.

**Comment by agarwal-navin** [comment]
Tracked by AB#389
