### ISSUE TITLE
Add tombstone objects - Objects that are deleted as per GC

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#7205]
When GC identifies objects that are eligible for deletion (described [here](https://github.com/microsoft/FluidFramework/issues/7204)), instead of fully deleting them, we can convert them to tombstones. This way, if these objects are used after they are deleted, we can identify such cases and take necessary action (possible fail fast). These are unexpected scenarios and may indicate bugs in the sweep process and / or host code. In any case, we want to fix these cases as and when we identify them.
These tombstone objects can be totally removed after a while.

Another option would be to add a separate "tombstone" blob to the summary that tracks the ids of deleted objects.

**Comment by vladsud** [comment]
I'd suggest we do not do it.

To adhere to 30-day rule, we will need to give storage at least some amount of time (I hear 7-14 days being mentioned) to finish their processes (i.e. deleting Azure blob does not happen instantly). So from client perspective data would need to be deleted from storage pretty soon. There is just not enough time to add more phases here.

As for staging, I think we can still do something like that, but without introducing tombstones.
We will need to switch to communicating time of deleted to storage (not just boolean flag how we do it today).
We could leverage it (initially, while staging this work) for storage to exclude unreferenced blobs in snapshot response after some time (let's say 14 days), but keep them in file longer. That way we will still be able to load them. It's another signal (we already have inactiveObjectX telemetry) that something is wrong that will help us see bugs sooner.

**Comment by agarwal-navin** [comment]
Tracked via AB#380
