### ISSUE TITLE
GC sweep end-to-end tests

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#7207]
When GC sweep phase is implemented, we need end-to-end tests to validate that things are working as expected.
Add tests for the following scenarios:
- Unreferenced data stores that meet the deletion criteria are deleted on sweep.
  - Summarization that occurs right when data stores should be deleted.
  - Summarization that occurs long after data stores should be deleted.
  - Summarization with a different container/client than the previous summarizer.
- Unreferenced data stores that do not meet the deletion criteria are not deleted on sweep.
  - Summarization that occurs right before data stores should be deleted.
  - Summarization that occurs when data stores get referenced.
  - Summarization with a different container/client than the previous summarizer.
  - Summarization with data stores that are always referenced.
- Unreferenced data stores that hit the expiration requirements but are referenced before the next summary.
- Deleted objects are removed from the snapshot that new clients load from.
- Deleted objects are not shown in search.
- Ops for deleted objects results in fail fast and an error telemetry log.
- Attempts to load deleted objects results in fail fast and an error telemetry log.
- After GC version in the “.metadata” blob is updated, GC reruns and the summary is regenerated. Also, previous “unreferenced” flags and “unreferencedTimestamp” are ignored.
- After GC is disabled, GC reruns and the summary is regenerated. Also, previous “unreferenced” flags and “unreferencedTimestamp” are ignored.
- Sweep is only run when the session expiry is met.
- Sweep is only running when there is a session expiry.

**Comment by vladsud** [comment]
Given that issue lists a lot of areas, and it's assigned to current month, can we please break it into smaller issues, and use this issue to clearly articulate priority of each sub-item?

**Comment by agarwal-navin** [comment]
Tracked via AB#365.
