### ISSUE TITLE
Remove "usedRoutes" from "gc" blob in summary

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#7222]
Currently, we store the following in the "gc" blob in summary for each data store:
- `gcNodes` - A list of all nodes (data store and its DDSs) and their outbound routes (link to other nodes).
- `usedRoutes` - A list of routes that are used in the data store.
The `usedRoutes` are added to the summary so that when a new summarizer client loads, it can identify whether a data store's used state changed since last summary. If so, it will summarize it again since it may have to update the unreferenced flag or the data store or its DDSs.

However, the `usedRoutes` can be removed which will reduce the size of the GC blob. We can generate the `usedRoutes` when a summarizer loads pretty cheaply:
- Get the `gcNodes` from the "gc" blob of each data store. We don't need to realize the data stores for this, just read it's "gc" blob. We do this anyway the first time GC runs. We can delay this step until the first time GC runs too.
- Run GC mark phase on the `gcNodes` and get the list of used routes for each data store. These become the reference `usedRoutes` as per the summary of the data stores.

**Comment by agarwal-navin** [comment]
@vladsud @anthony-murphy @pleath FYI

**Comment by vladsud** [comment]
Sounds reasonable with me.
This will be a breaking change, right? In a sense that we need to keep writing old data for at least couple releases while using only gcNodes calculation.

**Comment by agarwal-navin** [comment]
Yes, we will have to write the used routes for couple of versions. However, once we stop writing the used routes, the summary for such files will not have used routes in gc blob. If these files are opened in an older version of runtime (without the new code that calculates used routes), it will realize every data store and DDS while summarizing. It's a corner case and it might be a little expensive but it should be fine.

**Comment by agarwal-navin** [comment]
Closing this in favor of https://github.com/microsoft/FluidFramework/issues/8429
