### ISSUE TITLE
container-runtime package exports too many internal types/APIs (mostly summarizer-releated_

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7226]
Looking at packages\runtime\container-runtime\src\index.ts, I believe big half of exports should be removed from here, as these are internal implementation details of the package:

export * from "./deltaScheduler";
export * from "./summarizer";
export * from "./summarizerTypes";
export * from "./summaryCollection";

(I omitted some that I'm removing in my PR).

Some number of potential complications:
- we may use some things in end-to-end tests, i.e. tests that are in different package. One potential solution here - import sub-module from package, thus making this dependency implicit (not great) but not exported for any other use (good).
- Some types in summarizerTypes are used in public API, it should be split into public & internal files and internal not exported from index.ts

Reason why it's important:
The smaller is out API surface, the more freedom we have to change it without incurring expensive compatibility concerns.

Paul - assigning to you, as this is mostly about summarizer types.
Please do your own assessment here on how to proceed (and if reality matches my understanding).

**Comment by tylerbutler** [comment]
@vladsud An option for APIs that are internal-only but can't be made private is to remove them from [the type rollup](https://api-extractor.com/pages/setup/configure_rollup/). Rollups are not enabled at the moment but #6116 tracks it.
