### ISSUE TITLE
ODSP driver: special handling for data center fall over / read-only farm

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7241]
SPO can occasionally return 403 for r/w operations on document when there is a fail over to another data center.
The intention here is that data is read-only for a while, while fail over happens, to preserve integrity of the data.
While the process can take arbitrary time, we observe that this happens often in SPDF where new features are tested, and tenant is in this state for very short amount of time.

So it's proposed that SPO driver would understand that situation and would retry couple times with some exponential back-off logic and bail out after some number of retries. When it actually fails, it should return unique error code such that host app can reason about it and show reasonable message to user.

Client can differentiate such state vs. other 403 cases by looking at returned header “X-SP-SERVERSTATE : ReadOnly=1” 

Jatin - it would be great to implement this soonish, maybe even port it to 0.46 if change is relatively safe.
I think it should be generic enough (and impact all fetches), but file creation (posting initial snapshot) is the one that is the most impacted. If it does not fit in August, it should be moved to September

Please work with Ben (Teams) & Edmund Wong (SPO) if you need help here.

**Comment by jatgarg** [comment]
I will take a look @vladsud . Will try to squeeze in August itself.

**Comment by jatgarg** [comment]
The error that we get is in the body:
` {
"code": "accessDenied",
"innerError": {
"code": "serviceReadOnly"
},
"message": "Database Is Read Only"
}`
