### ISSUE TITLE
dmLastMsqSeqClientId could be null

### ISSUE THREAD

**Issue by nimgup** [microsoft/FluidFramework#7253]
## Describe the bug
Telemetry properties are of type TelemetryEventPropertyType | ITaggedTelemetryPropertyType; which includes undefined but not null values. One of demo-host's co-auth puppeteer test was failing because `dmLastMsqSeqClientId` equal to null and passed the type check for `typeof propvalue === 'object'`

Cancel telemetry event reported to logger in the FF runtime:
![image](https://user-images.githubusercontent.com/52804857/130852450-9ad3962e-05cd-4008-bb1d-042a1de35ab0.png)

After the event is prepared for logging and sent:
![image](https://user-images.githubusercontent.com/52804857/130852487-dc5870a3-9e89-4a8d-af95-90b0dfc20f60.png)

What the OtelLogProcessor receives:
![image](https://user-images.githubusercontent.com/52804857/130852527-44feb220-52f7-4bb5-b03b-4a2da589520b.png)

### To Reproduce
The only way to reproduce is to run the demo host CoauthoringComponent.livesite-test. Issue does not occur when the steps from the test are performed manually.

### Expected behavior
dmLastMsqSeqClientId is either undefined or an expected telemetry property type.

**Comment by vladsud** [comment]
ISequencedDocumentMessage.clientId can be null - typing should be fixed. All server-generated messages have null there.
TelemetryEventPropertyType should also probably allow null - it might be useful to record null (not undefined or something else) in places where we want to differentiate null from other values.
