### ISSUE TITLE
To parse summary acks and nacks, summarizer should use the "data" field instead of "content" field.

### ISSUE THREAD

**Issue by tanviraumi** [microsoft/FluidFramework#7264]
Currently, scribe uses the "contents" field to populate summary ack and nack payload. However, this is incorrect and we should use the "data" field instead (just like join/leave). PR #7231 updated the scribe code to start populating "data" field. Now summarizer should be updated as well.

To keep backward compatibility, scribe currently fills both "data" and "content" fields. Once all clients are updated, scribe will stop populating "contents" fills completely.

**Comment by jatgarg** [comment]
Comment
