### ISSUE TITLE
Version parameter to loader.resolve is not respected when you have headers

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#73]
We are trying to load a container with a null version as a query parameter to skip snapshots since they won't exist in this scenario. This request also sets some request headers. 

The end result is that this line of code
https://github.com/microsoft/FluidFramework/blob/master/packages/loader/container-loader/src/loader.ts#L263
sets the version back to undefined.

Perhaps, we should only have one way of setting the version?

**Comment by vladsud** [comment]
Not 100% sure what the reference above should point to.
Looking at versions of this file, it should be this one from Sept 9th.
https://github.com/microsoft/FluidFramework/blob/dc84c3cd441b3b0627f59be6d5de98a3b8f52861/packages/loader/container-loader/src/loader.ts#L263

At first glance, I do not see anything wrong here, and we no longer support loading without snapshots (even though there is some legacy code around it). There https://github.com/microsoft/FluidFramework/issues/4049 tracking changing meaning of null to mean oldest snapshot, but even that seems like not that useful anymore with ODSP deleting snapshots very quickly (and not yet having ability to go back by leveraging ODSP file history, though this is something we need in future for correctness).

@christiango, any input here?
I'll mark it as Won't fix for bot to resolve it does not hear from you.

**Comment by christiango** [comment]
Let's just mark it as won't fix. It's so old I don't even remember what problem this caused for us downstream

**Comment by vladsud** [comment]
Sounds good, closing.
