### ISSUE TITLE
FluidExample Brainstorm View Refactor + README Update

### ISSUE THREAD

**Issue by timtwang** [microsoft/FluidFramework#7303]
### 1 . Extract styles into an external stylesheet
  - Extract the styles specified in the return statement `div` of the view files (`NoteFooter.tsx`, `NoteBody.tsx`, `NoteHeader.tsx`, etc) into a new file.
  - create a `styles.css` and use the `webpack style-loader/ css-loader` to pull them in, e.g. like in
  `examples\data-objects\multiview\plot-coordinate-view\webpack.config.js`
  `examples\data-objects\multiview\plot-coordinate-view\src\style.css`
  - Reference: https://github.com/microsoft/FluidExamples/pull/272#discussion_r695035419

### 2. Mention object storing in `SharedMap` doesn't get stored the same way as it would be in a regular map
  - Add a warning or a note box in the `SharedMap` section of the Brainstorm README stating that object doesn't get stored in the DDS map in the same way as it would be stored in a regular map.
  - Reference: https://github.com/microsoft/FluidExamples/pull/272#discussion_r696992962

### 3. Refactor Brainstorm view to allow key-based state update instead of regenerating the entire state each time
  - It's difficult to have both local state and remote state that was governed by Fluid. Anytime that we had the React component logic working correctly to update an `isDirty` state for each note, it would end up getting overwritten since the note state is being completely recreated on each `valueChanged` event on the map. This meant that any local state changes would not get preserved and end up resorting to local values.
  - Reference: https://github.com/microsoft/FluidExamples/pull/272#discussion_r697767002

### 4. Add more code comments explaining `Audience` features
- Reference: https://github.com/microsoft/FluidExamples/pull/272#pullrequestreview-739845061

**Comment by heliocliu** [comment]
For this follow up please also address invalid FrsMember comparison if it wasn't already (https://github.com/microsoft/FluidExamples/pull/272#discussion_r695022956) and make another pass over the README to improve clarity and ensure code snippets reflect recent code changes

**Comment by timtwang** [comment]
all the items listed are addressed except for items 1 and 3 here. https://github.com/microsoft/FluidExamples/pull/309

The PR listed the reasons why items 1 and 3 are not addressed in the description
