### ISSUE TITLE
We still hit "Failed to retrieve ops from storage: too many retries" in prod & stress tests

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7313]
Counts are substantially down, and we identified a ton of issues and submitted fixed for both client & PUSH.
But, loaderVersion == 0.46 still sees cases, same for latest runs in ODSP scalability lab (customDimensions.testUid == "4f78e80f-5704-42c6-abd1-fdba9fe9ffd8")

union Office_Fluid_FluidRuntime_*
| where Data_error contains "too many retries"
| summarize count() by Data_loaderVersion

We need to understand better if this is a client or server issue.
Please note that 0.46 implements get_ops flow allowing us to get ops from PUSH.
We retrieve ops at the same time as we do call to storage. But if one call did not return us anything, but storage call hangs for 30 seconds, we will not retry asking PUSH for same ops again. Ops might have been in transition and did not land in redis yet, so second call might return them. This is all guessing, we need to look at individual sessions to understand better what's going on

**Comment by vladsud** [comment]
42 hits from 0.46, and 9 from 0.40 (loader) - that's all for 30 days. So while we do have hits, number of them is substantially lower than it used to, so priority on that is not that high.

**Comment by vladsud** [comment]
Need to reassess ones https://onedrive.visualstudio.com/SPIN/_queries/edit/1204718/?triage=true is addressed.

**Comment by vladsud** [comment]
21 cases in last stress tests (that were not very successful overall).
And 15 cases in last 10 days in prod.

**Comment by vladsud** [comment]
Spot checking couple sessions, I see a lot of fluid:telemetry:OdspDriver:DeltaConnection:GetOpsTooMany.
Suggesting we need first https://github.com/microsoft/FluidFramework/pull/8067 to re-assess.
It made it into 0.51, so we will need to wait for 0.51.

Looking at ODSP stress test logs, there are couple obvious points:
- Most cases where we hit timeout, we actually do not close container, as it looks like request was already cancelled (i.e. client got all the ops).
- In cases where we actually close container, I see that we can be asking for smaller set of ops because some ops in the range came through socket, but fetch retry logic does not know about it. I might need to change the flow of data. I wonder if retry logic should be moved from driver to loader, at least where service is alive and returned partial data (but leave retries in driver for retryable errors)

Queries to explore it:

> customEvents 
| where timestamp > ago(10d)
| where customDimensions.category == "error"
| where name != "Runner Error"
| where customDimensions.error == "failedToRetrieveOpsFromStorage:TooManyRetries"
| summarize count() by name, tostring(customDimensions.containerId)
| order by customDimensions_containerId

> customEvents 
| where timestamp > ago(10d)
| where customDimensions.containerId == "ec9b67b2-233a-4010-8890-699e516a7037"
| project timestamp, name, customDimensions.error, customDimensions.reason, customDimensions.from, customDimensions["to"], customDimensions.fromTotal, customDimensions.toTotal, customDimensions.length, customDimensions.sequenceNumber, customDimensions.checkpointSequenceNumber
| order by timestamp asc

**Comment by vladsud** [comment]
@GaryWilber, can you please take a look at this case?
containerId == "1b447aac-d871-4366-8ae8-1b13a83079df"
clientId  == "2adfaea8-4d4f-44f9-b990-dd17ed5db893"
This is ODSP stress tests.

checkpointSequnenceNumber = 26664

It looks like we got ops 26675...26677 from socket right away (initial ops?)
We keep asking for ops 26404..26675 from storage and socket for next 30 seconds.

Initially we got 171 ops.
Then 191
Then 228
Then 271 eventually - right before timeout hit (which would kill container if it happened a second earlier).

Why it took so long to get ops from socket?

**Comment by vladsud** [comment]
Moving to December, as from client POV it's not actionable - we will continue looking at potential service issues, and need 0.51 to reevaluate client issues.

**Comment by GaryWilber** [comment]
@vladsud I checked the logs for that client. There was a 1 to 2 minute time window where requests to add ops to Redis were taking a long time (5+ seconds). That time window matches the clients join time. That would have caused the client to miss those ops.
This is related to what I discussed earlier with how the Redis server load is around 95% - 100% during the load tests. This should be fixable on my side by adding an additional Redis cluster. I don't have an ETA for that work yet.

**Comment by vladsud** [comment]
I see 122 hits of this error (fluid:telemetry:DeltaManager:GetDeltas_Exception) from 0.49.2 (loader), which has total 282K sessions over that time
I see zero hits of this error for 0.5x.x builds, that have 14K sessions (roughly 20x smaller penetration at that moment than 0.49.2)
I'd expect to see at least couple hits here and there for 0.5x.x builds by now.

I do see fluid:telemetry:OdspDriver:DeltaConnection:GetOpsTooMany events in those sessions, and it suggests it might be fixed by https://github.com/microsoft/FluidFramework/pull/8067

Running this query suggests that indeed the problem that PR was attempting to address was addressed:
> union Office_Fluid_FluidRuntime_Error
| where Data_eventName == "fluid:telemetry:OdspDriver:DeltaConnection:GetOpsTooMany"
| summarize count() by Data_loaderVersion

Data_loaderVersion	count_
0.49.2	11902
0.52.1	2

These are all the errors in ODSP stress tests over last 30 days:

  | fluid:telemetry:OdspDriver:GetDeltas_Error | 0.53.0 | b708bf72-139d-4819-979f-de3ea46b6387 | 4 |  

  | fluid:telemetry:OdspDriver:GetDeltas_Error | 0.53.0 | 7dcc2d21-30d3-4a5a-8316-b5c9a192146e | 1 |  
  | fluid:telemetry:Container:ContainerClose    | 0.53.0 | 7dcc2d21-30d3-4a5a-8316-b5c9a192146e | 1 |  

  | fluid:telemetry:OdspDriver:GetDeltas_Error | 0.52.0 | 6a216024-0dc0-49ca-936f-fdf21faecc51 | 35 |  
  | fluid:telemetry:Container:ContainerClose    | 0.52.0 | 6a216024-0dc0-49ca-936f-fdf21faecc51 | 3

Not sure if 0.53 has any advantage over 0.52, but hit counts are extremely low.

Closing this item - will (re)open if data suggests it needs attention. At current hit counts, that's too low priority to look at.
