### ISSUE TITLE
Need UT coverage for RunWhileConnectedCoordinator

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7338]
Would appreciate help here :)

This issue is opened in context of https://github.com/microsoft/FluidFramework/pull/7321/ & https://github.com/microsoft/FluidFramework/issues/7311

**Comment by vladsud** [comment]
Actually, thanks to all the comments, I think we need to also simplify RunWhileConnectedCoordinator after we have proper test coverage (which I think requires end-to-end tests to ensure we can validate that disconnected -> disposed for summarizer containers).
There is no reason for this class to care about connected or disconnected states - that together with needing to care about disposed makes it complicated, despite really tracking 4-5 different states.
Once we have test coverage, I'd fully dropped tracking of connectivity and only care about disposed or not disposed.
We still need to wait for connected in waitStart() (as least for now), but things like this.everConnected can be dropped, as "dispose" -> stop() -> this.stopDeferred.resolve is enough to notify everybody about need to move to exit.

And I think it's great change for future, cause I can see us some day allowing summarizer client to reconnect (for example, if dedicated machine, like server box is responsible for summaries), and thus really this code should not care about disconnects, it should care about disposals only, while policy (to allow disconnects or not) is controlled somewhere else (formRequestSummarizerFn(), and [LoaderHeader.reconnect]: false header).

**Comment by pleath** [comment]
Keeping this alive.

**Comment by vladsud** [comment]
Tracked in ADO
