### ISSUE TITLE
Minor Perf Issue: Error.stack called in high frequency

### ISSUE THREAD

**Issue by josephliccini** [microsoft/FluidFramework#7394]
## Describe the bug
High frequency codepath hitting `Error.stack` (which is slow if accessed in high frequency).

Codepath: https://github.com/microsoft/FluidFramework/blob/d451bd668c1dd8da449ababddb82106f4df1112d/packages/runtime/runtime-utils/src/dataStoreHelpers.ts#L26-L36

### To Reproduce

Collect a profile of a document in OneNote meeting notes (I can share trace internally) and notice the codepath being hit in high frequency:

![image](https://user-images.githubusercontent.com/7726025/132384460-21b70cc8-d668-41ff-bea5-1744aa831f64.png)

![image (1)](https://user-images.githubusercontent.com/7726025/132384473-723c9448-b8c7-4cca-83d9-7a195d7d193c.png)

### Expected behavior
Maybe defer or avoid this codepath?

### Logs
N/A

**Comment by curtisman** [comment]
`getStack()` is only called when there is an error when app is trying to resolve a URL/Fluid Handle.  We don't expect this to error happen often, unless the app is requesting to resolve a lot of invalid URL/fluid handle, it would be good to understand why the app code go down this error path so often.

**Comment by curtisman** [comment]
We can probably optimize `generateStack` (the new getStack) I believe you don't need to call `.stack` right away and just save the `Error` object. Measurement on node is about 6x slower with the `.stack` call.

There might be browser that behave differently, but we can do a one-time probe to check the browser behavior and behave different on that (instead of checking every time)

**Comment by vladsud** [comment]
@josephliccini, I'm not sure this is actionable on our side. It basically says - some function is called too many times, but there is no stack, no particular repro (in context of FF repo). And most likely that points to host bug of hitting errors too often, that should be looked from host side first.

**Comment by josephliccini** [comment]
@vladsud I do agree that it's the intersection of a host issue and a Framework codepath.  I think we should visit what's going on with the host.  But if there was a way to use a faster implementation of `.stack` that could be a win for everyone

**Comment by josephliccini** [comment]
@vladsud we have a repro on the FFX side, I will reach out via teams to discuss

**Comment by markfields** [comment]
Looking at this code for the first time myself - Is this as much about the use of `mixinRequestHandler` as anything (and especially with tables where number of data stores is high)?  I could imagine an optimization to avoid generating the stack if we know it's going to be swallowed by the mixed-in handler, but I wonder how messy that will be in terms of keeping a clean abstraction around request handling.

**Comment by vladsud** [comment]
Closing as fixed by above mentioned PR
