### ISSUE TITLE
fluid:telemetry:OpPerf:OpRoundtripTime errors are hit in prod

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7406]
This is error event if duration > 5000.
This is same as https://onedrive.visualstudio.com/SPIN/_queries/edit/1186578/?triage=true which has more info

Queries:
> Office_Fluid_FluidRuntime_Error
| where Event_Time > ago(5d)
| where Data_eventName == "fluid:telemetry:OpPerf:OpRoundtripTime"
| summarize count() by Data_loaderVersion

Latest (as of 12/6) stats for last 5 days:

0.5x.x: 33
0.49.2: 276
0.47.1: 949
All others: 22

Same, but 15 seconds or above duration:
0.5x.x: 6
0.49.2: 70
0.47.1: 207
All others: 2

Numbers roughly track usage stats, so there seems to be no significant changes across versions.

**Comment by vladsud** [comment]
Waiting for PUSH fixes (tracked by https://onedrive.visualstudio.com/SPIN/_queries/edit/1204718/?triage=true) to reassess where we are

**Comment by vladsud** [comment]
There is sharp cut-off somewhere after 17 seconds in ODSP stress tests - number of cases drops substantially.
In prod it's much more nuanced and more expected curve with counts dropping pretty quickly. But there are cases with duration in minutes!

**Comment by vladsud** [comment]
Data_containerId == "3faf7d6c-c7f5-4759-b8b9-76ee7d6eb699" is very interesting.
We see a lot of OpRoundtripTime events with latencies over 30s where they are the next event after fluid:telemetry:Container:ConnectionStateChange_Connected with mode="write".
Duration suggests that op was sent right after connected events.
There are no ops fetches.

Durations suggests that the op was sent couple milliseconds before connected event.
But looking at code, we raise _Connected event after we propagated change in setConnectionState() - something we need to change. So we can assume that op was sent in response to being connected.

Here are the most interesting events from this session (Event_Sequence, Event_Time, Data_eventName, Data_sequenceNumber, Data_checkpointSequenceNumber, Data_connectionMode, Data_duration, Data_clientId):

	36	2021-11-04T08:03:19.684Z	fluid:telemetry:Container:ConnectionStateChange_Connected	1		write	33	0eefe70c-1d67-46b0-865f-5d6a8dc39ad5
	38	2021-11-04T08:03:19.989Z	fluid:telemetry:OpPerf:OpRoundtripTime	2			308	

	1751	2021-11-04T08:57:26.553Z	fluid:telemetry:Container:ConnectionStateChange_Connected	212		write	1552	3a82f20a-4cb4-4fd1-8ebc-3160237e70af
	1753	2021-11-04T08:58:01.727Z	fluid:telemetry:OpPerf:OpRoundtripTime	213			35407	

	1768	2021-11-04T08:58:55.424Z	fluid:telemetry:Container:ConnectionStateChange_Connected	315		write	1535	92c4a94a-8656-44df-98ef-0fe8bd2aa44d
	1770	2021-11-04T08:59:42.212Z	fluid:telemetry:OpPerf:OpRoundtripTime	316			46988	

	1785	2021-11-04T09:00:35.971Z	fluid:telemetry:Container:ConnectionStateChange_Connected	418		write	1491	87a45b11-f729-4f6b-8ef6-1581a9cf2441
	1787	2021-11-04T09:01:16.159Z	fluid:telemetry:OpPerf:OpRoundtripTime	419			40387	

	1845	2021-11-04T09:05:23.808Z	fluid:telemetry:Container:ConnectionStateChange_Connected	630		write	1529	1d6f1dea-a0c4-4d1c-ad4d-4a6d0eb66f7a
	1847	2021-11-04T09:06:02.701Z	fluid:telemetry:OpPerf:OpRoundtripTime	631			39096	

	1890	2021-11-04T09:08:40.923Z	fluid:telemetry:Container:ConnectionStateChange_Connected	739		write	4421	c1a0f1af-3a2d-464e-9bb7-45c0773efc33
	1892	2021-11-04T09:09:22.772Z	fluid:telemetry:OpPerf:OpRoundtripTime	740			41982	

	1920	2021-11-04T09:11:06.238Z	fluid:telemetry:Container:ConnectionStateChange_Connected	845		write	472	7031a243-61ad-4fc8-92af-97b8be0c8e2f
	1923	2021-11-04T09:11:48.865Z	fluid:telemetry:OpPerf:OpRoundtripTime	846			42793	

	1938	2021-11-04T09:12:40.792Z	fluid:telemetry:Container:ConnectionStateChange_Connected	948		write	1569	34bd3d1c-95de-467a-b941-9f5f881abe8d
	1940	2021-11-04T09:13:27.544Z	fluid:telemetry:OpPerf:OpRoundtripTime	949			46882	

	2135	2021-11-04T09:25:24.453Z	fluid:telemetry:Container:ConnectionStateChange_Connected	1090		write	508	4c392488-323e-460c-b567-80cadf4c504f
	2138	2021-11-04T09:26:00.61Z		fluid:telemetry:OpPerf:OpRoundtripTime	1091			36345	

@GaryWilber, any chance if you can glance if we can learn anything from PUSH logs?
I.e. I guess it's some kind of client issue, but I have not information yet here, so worth double checking that op in question was sequenced and broadcast right away after join op was broadcast (if we can confirm that). This will ensure the bug is on client side and worth adding some kind of extra tracking (not sure yet of type of tracking) that would help diagnose the issue.

**Comment by vladsud** [comment]
With PRs #8206, #8232 landing in 0.52, I'll reevaluate where we are in December once 0.52 ships to prod.

**Comment by GaryWilber** [comment]
@vladsud Those clients are in MSIT and the app is Whiteboard.

0eefe70c-1d67-46b0-865f-5d6a8dc39ad5:
11-04-2021 08:03:20 - connect_document
11-04-2021 08:03:21 - join op sequenced, broadcasted, and inserted into redis
11-04-2021 08:03:21 - client submitted their first op

3a82f20a-4cb4-4fd1-8ebc-3160237e70af:
11-04-2021 08:57:26 - connect_document
11-04-2021 08:57:26 - join op sequenced, broadcasted, and inserted into redis
11-04-2021 08:57:26 - client requested ops 209 - 211, returned 404 (no ops returned)
11-04-2021 08:58:01 - client submitted their first op

92c4a94a-8656-44df-98ef-0fe8bd2aa44d:
11-04-2021 08:58:55 - connect_document
11-04-2021 08:58:55 - join op sequenced, broadcasted, and inserted into redis
11-04-2021 08:58:55 - client requested ops 312 - 314, returned 404 (no ops returned)
11-04-2021 08:59:41 - client submitted their first op

So the first client looks normal. The other two stopped for at least 30 seconds between a 404'd get_ops request and submitting their first op.

**Comment by GaryWilber** [comment]
@vladsud Here's more accurate data for the second client. I just figured out how to view events with the milliseconds!

3a82f20a-4cb4-4fd1-8ebc-3160237e70af:
11-04-2021 08:57:26.321 - connect_document
11-04-2021 08:57:26.384 - join op sequenced & broadcasted. op # is 212
11-04-2021 08:57:26.382 - join op inserted into redis
11-04-2021 08:57:26.483 - Push posted ops 209 - 211 to SPO
11-04-2021 08:57:26.498 - Push removed ops 209 - 211 from Redis
11-04-2021 08:57:26.602 - client requested ops 209 - 211, returned 404 (no ops returned) - this is because they were just removed.
11-04-2021 08:58:01.712 - client submitted their first op

**Comment by vladsud** [comment]
Thanks! For that range of 209..211, here is what I think I see from client telemetry:
- connected to socket with last seq# 209.
- received an op with seq# 212
- fetched ops 209-211 (data came not from storage).
- raised "connected" event as processed ops up to 212.
All of that looks good, and happened pretty quickly - 1552ms, based on duration on connected event.

But then it takes 35 seconds for fluid:telemetry:Container:OpsSentOnReconnect to show up for seq# 213, suggesting that client sent this op right away after becoming connected but received 35 seconds later.
Data from above (last line) suggests that actually client sent it 35 seconds later. Which suggests one of the following:
- There is some issue in sent pipeline
- There is some quality issues in fluid:telemetry:Container:OpsSentOnReconnect telemetry payload / calculation of duration

I also looked at fluid:telemetry:Container:OpsSentOnReconnect to see if we can confirm if any ops where sent as part of reconnect logic, but I see something weird: count = 2223. That's just can't be number of ops sent (as we are on 213), so here clearly something wrong in telemetry payload.
Looking at all such events in session, I see that count keeps increasing across reconnects (as if it's not reset) up until 2223, but then it starts dropping on each reconnect. Definitely need to look deeper into it.

**Comment by vladsud** [comment]
Not sure what's the issue with OpsSentOnReconnect (code looks reasonable), but I'll restructure code to assert it's always equal to last clientSequenceNumber - if there is a bug somewhere, we will catch it pretty quickly.

Code around OpRoundtripTime looks reasonable. So I think the problem is with batching, i.e. op reaches delta manager and we start the count, but it is not sent until batch is closed, and for whatever reason it takes that long.

I'll add tracking for batch duration, that will help us better understand where problems are.

**Comment by vladsud** [comment]
One more thing I noted - this event is overreporting errors for summarizer, who frequently pauses inbound queue, and thus slows down op processing. I'm not sure why summarizer sends any ops, but it does (agent scheduler?) and their acks take a while to be processed as we are pausing inbound pipeline. Need to exclude them somehow (and in general - report if inbound was paused, and maybe why if we have that info)

**Comment by vladsud** [comment]
Note - there **MaxBatchWaitTimeExceeded** has been added some time ago to help with some of these investigations

**Comment by vladsud** [comment]
Looking at last 7 days only, and loader version 0.5x, I see this:

2.5K hits of this error / 3M container sessions.
interactive container: 1.9K / 2.6M

So basically, one less than one out of 1K sessions will hit this error once (op roundtrip takes over 5 seconds).
That is actually pretty damn good!

So, all of the work that was put in here paid off.  While I'm sure there are more improvements we can make here (and there are couple bugs are still active for concrete work), it reached the level of diminishing returns where time is spent elsewhere.
It shows up in error table, so we will continue to monitor and if it goes up in counts, we will have time to reactivate or open new issues to track it.
