### ISSUE TITLE
Fix publish step in the pipeline

### ISSUE THREAD

**Issue by sumedhb1995** [microsoft/FluidFramework#7411]
Two current issues in the pipeline:

1. We should only tag the release once, instead of after both scoped and non-scoped package publishes
2. Do a check to see if the package has already been published and, if so, skip the step instead of failing. This will allow us to re-run the step in case there any ephemeral errors in the pipeline that cause the step to fail

**Comment by curtisman** [comment]
When checking, make sure the published package is the same we are going to publish.  We should still error if we are trying to publish a different package of the same version.
