### ISSUE TITLE
Docs: "Libraries" has bug in section names/slugs -  "aqueductundefined", "Fluid frameworkundefined"

### ISSUE THREAD

**Issue by hangtwenty** [microsoft/FluidFramework#7471]
## Describe the bug

![image](https://user-images.githubusercontent.com/2420688/133173966-a445bfa2-8cf2-4de0-84d1-706b43fc156a.png)

In the docs, some section titles (and the slugs that go with them) have an accidental `undefined` in them. 

The slugs have it too:

* https://fluidframework.com/docs/apis/aqueductundefined/
* https://fluidframework.com/docs/apis/fluid-frameworkundefined/

### To Reproduce

Check the links above.

**Comment by hangtwenty** [comment]
Oh, because it affects the slug, there are broken links (i.e. https://fluidframework.com/docs/glossary/ has one). But they'll just work, once the bug is fixed.

**Comment by tylerbutler** [comment]
@hangtwenty Thanks for the bug report! I am working on fixing this.
