### ISSUE TITLE
Unnecessary escaping in op JSON

### ISSUE THREAD

**Issue by yoonk-msft** [microsoft/FluidFramework#7546]
Fluid op messages in websocket are bloated with unnecessary escaping in the JSON, like the following:
```
42/fluid,["submitOp","c20ad82d-ed12-4327-8032-35668f4b5a8b",[[{"clientSequenceNumber":10,"contents":"
{\"type\":\"chunkedOp\",\"contents\":{\"chunkId\":1,\"contents\":\"{\\\"address\\\":\\\"defaultComponent\\\",\\\"contents\\\":
{\\\"content\\\":{\\\"address\\\":\\\"23fd7090-3805-49a0-9438-c270de8835fd\\\",\\\"contents\\\":{\\\"type\\\":0,\\\"edit\\\":
{\\\"id\\\":\\\"4cdf2714-e632-4078-a2bf-84fbaf7aa0ae\\\",\\\"changes\\\":[{\\\"destination\\\":0,\\\"source\\\":[{\\\"traits\\\":
{\\\"3e029a25-a671-459d-a63b-61ff015f3a5a\\\":[{\\\"traits\\\":{\\\"ebbf1545-ba08-48e6-ae20-3962cb0537c3\\\":[{\\\"traits\\\":
{},\\\"definition\\\":\\\"208c7c2e-733d-4f47-af22-ced77889fc46\\\",\\\"identifier\\\":\\\"5dcdc4d0-ec00-4a7c-955c-
f5e79739dad4\\\"}],\\\"d905d3cd-3421-4460-a8a7-97928df1ac4e\\\":[{\\\"traits\\\":{\\\"04f7b6e9-ee61-4d84-b099-
0507a060cbcc\\\":[{\\\"traits\\\":{\\\"c80c5c72-a0a0-48ce-8e60-9f867c33c6f4\\\":[{\\\"traits\\\":{},\\\"payload\\\":
{\\\"base64\\\":\\\"AAAAAAAAP0A=\\\"},\\\"definition\\\":\\\"227b8b24-4c1e-40fe-bd65-
ad26fbbfab27\\\",\\\"identifier\\\":\\\"3fcc7f34-8a81-49a8-88b9-f4ed4b49603b\\\"}]
...
```
This extra level of string escaping makes up around 20% of our op message size. Could this be optimized?

**Comment by DLehenbauer** [comment]
Message chunking looks like the culpit.  In particular:
* 'ContainerRuntime.submit()' stringifies the content to see if it exceeds 'maxOpSize' (escape level 1)
* Normally, the stringified content is then passed to submitRuntimeMessage(), which adds an envelope before stringifying again (escape level 2)

In the case that the content exceeds 'maxOpSize', 'submitChunkedMessage()' breaks the stringified content into several substrings, wraps in an IChunkedMessage instance, and calls 'submitRuntimeMessage()'

A simple "fix" for the common case would be for 'submit()' to throw away the stringified version and pass the original object graph, although _theoretically_ this could be perf negative as parsing/stringifying deep object graphs is slower than parsing/stringifying strings (fewer branches, fewer allocs, better locality).  This impacts the server too, which parses the envelope, modifies, and re-stringifies the message (with contents).

Fixing the chunked case is more involved.  Property DDS has code to calculate the stringified size of object graphs and subdivide them into chunks based on a target size, but does not support subdividing scalars (i.e., long strings).

**Comment by DLehenbauer** [comment]
On the summarization side, @scarlettjlee noticed that ITreeEntry.contents is typed to 'string'.
