### ISSUE TITLE
Fetch summary only when reference sequence number advances

### ISSUE THREAD

**Issue by tanviraumi** [microsoft/FluidFramework#7560]
Currently, refreshLatestSummary() downloads the summary and checks whether the reference sequence number advances (https://github.com/microsoft/FluidFramework/blob/main/packages/runtime/runtime-utils/src/summarizerNode/summarizerNode.ts#L270). However, the summarizer already knows the reference sequence number from the last summary op (https://github.com/microsoft/FluidFramework/blob/main/packages/runtime/container-runtime/src/summarizer.ts#L275).

Rather than downloading the summary, we can just check the condition and only download summary when the refSeq actually advances. This will also help service summaries since summarizer will stop pulling older summaries unnecessarily just to perform the check.

**Comment by agarwal-navin** [comment]
@pleath FYI
