### ISSUE TITLE
Documents are hitting 10K summarized ops while there is no summarizer

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7589]
These two documents hit a lot of 10K unsummarized ops errors in last 7 days:

> Office_Fluid_FluidRuntime_Error
| where Event_Time > ago(7d)
| where Data_docId == "y2d8dKQjVDX2B8IWifWWegaJ7QEj7FuH7cF9h5glzs4%3D" or Data_docId == "z5%2BGiEIzITu3pkAUY29hyWQFK%2FY1GB5s9rn2Ure6KLc%3D"
| summarize count() by Data_eventName, Data_error

Yet we see no summarizer client ever created for these documents in this timeframe:

> union Office_Fluid_FluidRuntime_*
| where Event_Time > ago(7d)
| where Data_docId == "y2d8dKQjVDX2B8IWifWWegaJ7QEj7FuH7cF9h5glzs4%3D" or Data_docId == "z5%2BGiEIzITu3pkAUY29hyWQFK%2FY1GB5s9rn2Ure6KLc%3D"
| summarize count() by Data_clientType

Noted somewhat related bug: https://github.com/microsoft/FluidFramework/issues/7137

**Comment by vladsud** [comment]
For 
> union Office_Fluid_FluidRuntime_*
| where Event_Time > ago(8d)
| where Data_docId == "y2d8dKQjVDX2B8IWifWWegaJ7QEj7FuH7cF9h5glzs4%3D" 
| where Data_eventName contains "Summ"
| summarize count() by Data_eventName

All I see is fluid:telemetry:SummaryStatus:Behind & fluid:telemetry:SummaryStatus:CaughtUp - fired once each. So no summarizer was attempted to be started, I believe. Not sure why.

Similar query for Data_docId == "z5%2BGiEIzITu3pkAUY29hyWQFK%2FY1GB5s9rn2Ure6KLc%3D" gives us 337/336 events for fluid:telemetry:SummaryManager:CreatingSummarizer / fluid:telemetry:SummaryManager:EndingSummarizer, so summarizer was at least attempting to be started, but I do not see any other summarizer events for this doc suggesting it never actually started. This was 0.47 version of runtime (in case it matters).
Looking at startSummarization() flow, we never run through RunningSummarizer* events.
Looking at Data_containerId == "4cad7c3b-ed43-433f-b6c0-f5f9d53904ce", I see a loop of same events:

fluid:telemetry:Container:ConnectionStateChange_Disconnected
fluid:telemetry:Container:ContainerWarning
fluid:telemetry:DeltaManager:WrapError
fluid:telemetry:SummaryManager:EndingSummarizer

Last event fires exactly 5 seconds after first 3 events!

So it's defaultInitialDelayMs and for some reason we do not move to creation of summarizer right away (at least in this case), and when timeout is over, we bail out due to this code I've added:

```typescript
            // Re-validate that it need to be running. Due to asynchrony, it may be not the case anymore
            const shouldSummarizeState = this.getShouldSummarizeState();
            if (shouldSummarizeState.shouldSummarize === false) {
                summarizer.stop(shouldSummarizeState.stopReason);
                return;
            }
```
Which does not allow last summary logic to kick in, because we never created RunningSummarizer to even assess if last summary should be run.

So it's combination of both - waiting 5 seconds when we should not, and bail out soon when we waited 5 seconds.
I'd say that if we did not wait 5 seconds, then it would work correctly, and the code I've added above should likely stay (as in all cases with too many ops we would not wait a bit and this check would not be triggered).
#7403 is not relevant as we had too many ops even before we entered delayBeforeCreatingSummarizer(), so we should have not waited at all.

And here is the most interesting data point - sample fluid:telemetry:SummaryManager:CreatingSummarizer payload:
initialDelay = 5000, throttlerDelay = 40, opsSinceLastAck = 132, opsToBypassInitialDelay = 4000.

This does explains why we wait 5 seconds (client believes there are only 132 unsummarized ops), but this does not match nack which suggest we have 10K unsummarized ops! So things do not end up somehow.
A bit more digging required - this might be a PUSH bug we saw the other day where PUSH would reject client not realizing summary was actually accepted.

@GaryWilber - can you please comment on last paragraph - do we have a fix in prod for that issue, and when it hit production? Can we confirm if given client hit the box that had that fix?

**Comment by vladsud** [comment]
This last doc looks like a PUSH issue.
We loaded from summary at seq = 89728
First nack was when client was on seq = 89860.
So there is definitely no 10K unsummarized ops!

The last set of connection / attempt to start summarizer were for seq = 91734, and opsSinceLastAck = 2003.
So we are getting nacks when we should not.
@GaryWilber, please take a look, first connection to hit it:
socketDocumentId = 17701b29-4808-44cc-b217-d6c9bae9adf5
clientId = 3240eb1f-5989-4d33-9b35-058301a29ddc

**Comment by GaryWilber** [comment]
@vladsud The prod fix for that finished deploying today. Can you provide a timestamp for that `17701b29-4808-44cc-b217-d6c9bae9adf5` session? I can check the build that was running then

**Comment by GaryWilber** [comment]
I found logs for the `17701b29-4808-44cc-b217-d6c9bae9adf5` document in MSIT. The fix was already deployed during that timeframe.
I can't tell why push would be nacking them. There are no other connection/sessions besides that one on 9/22. So there have been no post summary calls for that document within the last 30 days. I have a feeling that doc got into the nack state before the fix and for some reason it isn't exiting it.

**Comment by vladsud** [comment]
Well, how do we make progress here? From client perspective, this doc is broken and client can't do anything to recover (at least without some hacks), as it's pretty up to date, so we do not involve our "recovery" logic of "last summary" that addresses similar cases when doc has 10K unsummarized ops. I've double-checked again, and all the data suggest that document is pretty up to date - sequence numbers hover in 89K - 90K for a lot of initial nacks, as observed form join op, checkPointSequenceNumber and reference seq number of snapshot we loaded from. And the max sequence reported through all session and all events was 92880 (actual final seq might be a bit higher, as we do not report every op). So the should not be getting nacks.

Unfortunately there are no other sessions for this document recorded in Kusto prior to that that summarizer that doc - all sessions loaded from same snapshot with ref seq # = 89728. There were total 5 sessions like that and all of them fetched same snapshot from storage, with 6 days apart between sessions.

What kind of telemetry we can add on your side to learn why document gets nacked? Can we propagate last summary handle / reference seq number of last summary (as believed to be by PUSH)? That way we can see if they differ, and maybe why.

Here is query I use for easier reference:
>union Office_Fluid_FluidRuntime_*
| where Data_docId == "z5%2BGiEIzITu3pkAUY29hyWQFK%2FY1GB5s9rn2Ure6KLc%3D"
| where Data_loaderId == "d6578cb2-3c36-40cb-a42d-21f4b833a40b"
| project Event_Sequence, Event_Time, Data_eventName, Data_reason, Data_error, Data_clientType, Data_connectionMode, Data_containerId, Data_sequenceNumber, Data_checkpointSequenceNumber, Data_opsSinceLastAck

**Comment by vladsud** [comment]
@GaryWilber , any thoughts on how to move forward here? Please see my latest reply

**Comment by GaryWilber** [comment]
I haven't been able to repro this exact issue yet. I made some changes in #7618 that could help here. I'm hoping we can check the telemetry once these changes are deployed.

**Comment by vladsud** [comment]
Thanks! I'll close this item as it's not actionable at the moment and I do not see it happening more. It will be easier to spot this in the future as all the client bugs (I believe) that lead to similar error message are fixed in latest 2 releases. So if it pops up, we will notice right away and I'll ping you :)
