### ISSUE TITLE
[Performance] Lots of timers installed and cleared

### ISSUE THREAD

**Issue by josephliccini** [microsoft/FluidFramework#765]
Hi,

I have a SessionID: `ca3082a6-2a97-4699-9add-eda17ad3b702`
And a profile that goes with it: https://microsoft-my.sharepoint-df.com/:u:/p/joliccin/EX1bkObepNRKkRquZ9DsoCgBwUSiPAxCXkwSwlA75IDWeA?e=5TsSYQ

In the profile, I'm interested in the 9000ms to 10000ms part (not the Scriptor stuff before that, I have already talked to Frankie about that)

I am seeing that Fluid is running some heursitic that says "Should I take a snapshot?", and it seems to be installing and clearing timers frequently.  Since this is a browser API, it's not the most efficient thing to do in high frequency. 

This is the function, in `officeFluidContainer.js`
```js
handleOp(e, t) {
    void 0 === e && (this.heuristics.lastOpSeqNumber = t.sequenceNumber,
    t.type === d.a.Save ? this.trySummarize(`;${t.clientId}: ${t.contents}`) : this.heuristics.run())
}
```

Here's what it looks like zoomed in: 
![image](https://user-images.githubusercontent.com/7726025/70661841-fea1d400-1c19-11ea-965a-c65188b458a5.png)

a little zoomed out:
![image](https://user-images.githubusercontent.com/7726025/70661915-1a0cdf00-1c1a-11ea-89c1-f31e0ab4c701.png)

a little more:
![image](https://user-images.githubusercontent.com/7726025/70662015-47598d00-1c1a-11ea-8458-8302c9fb9735.png)

It's not the biggest bottleneck here in isolation, but if you don't need to install as many timers, you may be able to save a good amount of time in aggregate, especially on slower devices.

**Comment by vladsud** [comment]
@arinwt, is this already addressed? That's an old bug, and I believe we no longer have issues with timers here, but worth confirming.

**Comment by arinwt** [comment]
I did address the excessive restarts within summarizer code using `restart()` in #770, so yes I think we can close this. There may be other places in our code that aren't using the optimized restart function, but it would only matter if they are excessive.
