### ISSUE TITLE
We are inconsistent RE logging connectivity errors in telemetry.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7664]
We are not consistent how we log connectivity errors across ODSP / DeltaManager.

DeltaManager attempts to log only first / last error in a sequence of retries - see logNetworkFailure() usage.
And socket connection flow itself in ODSP driver does not report errors, only propagates them down the stack.
This helps with situation where we might be offline and retry every 8 seconds - we are not putting a lot of noise into telemetry.

That said, join session & token fetch flows always record _end / _cancel events, so they go against the design above.
The reason they usually do not flood telemetry with errors is that token callback (provided by host) does not return back with error if client is offline, and instead waits until connection comes back. That was not the case in very original design (so it's later addition that predates the flow described above).

If we can rely on it (i.e. make it a requirement to all hosts), then DeltaManager should be changed to log all errors.
If we can't rely on it, then we need to make other parts of the system (token fetch / join session) not log events all the time if we are offline.

The part where it shows up - we do see some sessions where there are a lot of successful joinSession calls in a row, with nothing else. That's because websocket fails to connect and DeltaManager only records first such instance. But it's hard to reason about this flow for someone who is now aware of the story above.
And if token fetch fails in offline, then we will also see a ton of failures to get tokens, every 8 seconds while being offline, that will fill in telemetry with a lot of data.

**Comment by vladsud** [comment]
@AndreiZe - curious to hear your thoughts if we could rely / make it a requirement that all token fetch callback has to always block in offline.

@curtisman - FYI, in case you have more thoughts here.

**Comment by AndreiZe** [comment]
I do not think that we can require all token provider implementations to block until client regains connection. We can recommend it  but requiring it might be asking too much. Trouble is that there is no reliable way to detect network issue and not every host would have such ability.

**Comment by vladsud** [comment]
@jatgarg - assigning to you (November) to think about it - I do not have good recommendation here at the moment.

**Comment by jatgarg** [comment]
workitem=505
