### ISSUE TITLE
Client does not refresh when switching server hashes

### ISSUE THREAD

**Issue by tyler-cai-microsoft** [microsoft/FluidFramework#7671]
## Describe the bug

The client does not automatically sync when visiting a new hash.

### To Reproduce
1. Launch the Fluid Hello World example
2. Open another tab/window and go to this link http://localhost:8080/
3. Roll the die on the originally opened tab a few times so that it's not on 1.
3. Copy the original link
4. Paste the original link into the tab/window you had just created and press enter.
5. Roll the die.
6. The two tabs/windows are not synced.

### Expected behavior
The clients should sync with other clients when visiting a different hash.

**Comment by tylerbutler** [comment]
@tyler-cai-microsoft were you testing against tinylicious or azure? Anything in the console logs?

**Comment by tyler-cai-microsoft** [comment]
It was through Azure, I did not see anything in the console logs.
