### ISSUE TITLE
Implement user activity tracking and default policy for maintaining PUSH connection when users (clients) are inactive

### ISSUE THREAD

**Issue by okjodom** [microsoft/FluidFramework#7732]
## Feature
**Is your feature request related to a problem? Please describe.**

Experiences building on top of FluidFramework do implement user activity tracking to detect user presence. When a user is not present, these experiences need to call `Conatainer.setAutoReconnect(false)` to signal FF not to maintain PUSH connection. When they detect the user is back, they need to call `Conatainer.setAutoReconnect(true)`, signaling FF to maintain PUSH connection from this point onwards.

**Describe the solution you'd like**

This request is to implement the desired user tracking and resulting Container API reaction as a default policy within Fluid Framework

**Existing work**

Feature is currently implemented in Fluid Framework Experiences internal codebase

**Comment by vladsud** [comment]
Came out of https://github.com/microsoft/FluidFramework/issues/7651 investigation

**Comment by vladsud** [comment]
Sounds like (per email discussion) this is a must for 3P.
@skylerjokiel, @danielroney, it would be great to track it that way / figure out full set of work, as this item is not tracking things like
- exposure to 3P SDK
- Different use scenarios (it talks only about UX-based apps, where presence / lack of user input is primary driver for on/off  switching).
-

**Comment by jodom** [comment]
Tracking [an item here, in FFX](https://office.visualstudio.com/OC/_boards/board/t/FluidX_SharedExp/Features/?workitem=5546342), but this should be a visible part of Teams backlog. I created an item under FFX and tagged Teams eng so we don't lose track of work.
