### ISSUE TITLE
Need to brainstorm how to fix Audience

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7761]
Using current framework.
This should help us understand the bigger picture on what to do with signals as a whole, applicability, and guidance to developers.

Maybe precursor - we need a doc from Tanvir clearly describing full protocol, reliability, and what can and can't be assumed by clients.

**Comment by tyler-cai-microsoft** [comment]
Doing leader election with signals was added to the stress test. Here's the file: https://github.com/microsoft/FluidFramework/blob/main/packages/test/test-service-load/src/leaderElection.ts

Based on our logging, we found that all our leader lost elections do not recover. We are relying on the audience, what would we need to do to make it more reliable? 

Here are the the average counts per run:
Data_eventName	avg_count_
fluid:telemetry:SignalLeaderElection:UnexpectedLeaderEventWarning	183.72
fluid:telemetry:SignalLeaderElection:LeaderLostEventError	74.28
