### ISSUE TITLE
Start instrumenting errors based on "origin" - which layer is likely to blame

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#7763]
The goal is to mark errors as originating from something like host or datastore or server or runtime.  Not always obvious, but there are some cases that are, that we'll start with, and iterate.

Done criteria for this is 2-3 key code paths instrumented with a new field, with guidance for how to adopt/tune this signal going forward.

**Comment by markfields** [comment]
My observation from looking at Office Fluid error logs is that `fluidErrorCode`'s presence or absence can give us a hint about which errors originated in our code v. the code building with FF. With a couple caveats* in the short term, I believe the set of errors that don't have `fluidErrorCode` set (`"none"` is considered unset) is a good subset of errors that are "not our fault" (at least at face value).

\* Caveats:
1. Some key instrumentation points need to be fixed so they include `fluidErrorCode` (see #8099)
2. We also need #8124, but in the meantime we can work around this using some other props on the logs

We can give further commentary on the "source" of an error as desired on either side of this dichotomy using `errorSource`. This will be helpful for instrumenting errors we raise ourselves, to override the default assumption that `fluidErrorCode` means "our fault". But we're also exploring using `errorSource` to give more color to other errors, like in linked PR #7763.

@anthony-murphy, @vladsud -- I'm really interested in discussing this position with you, before I execute much more in this direction.  Thanks!

**Comment by vladsud** [comment]
I'd love to have categorization of errors like source = ODSP/SPO, ODSP/PUSH, Host/TokenCallback, Host/DDSEventListener, etc. I.e. even if it's true what you describe, I'd love to categorize cases where there is no errorCode, as that will help us directly to quicker understand what happens, but it will also help us indirectly by helping our partners to better understand where problem happens, and thus reduce chances for bugging us with issues that are not ours.

I also can see evolution of that, where we will start grouping our error codes with same source, or breaking existing error code into many while keeping one source. For example source = FF/DataCorruption, with errorCodes - {dataStoreNamingCollision, ddsNamingCollision, ...}

**Comment by markfields** [comment]
I'm closing this.  It lead to good discussion, and actual goal/scenario is tracked by this Epic:  https://github.com/microsoft/FluidFramework/issues/8260
