### ISSUE TITLE
Loader telemetry events do not have loaderVersion property on them.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7778]
These two events do not have loaderVersion property on them (and many others, but loaderVersion is where I noticed it):
fluid:telemetry:Loader:Resolve_end
fluid:telemetry:Loader:Request_end

That's because it is added by Container class, and happens later in the pipeline.
While it's not big deal, and it's easy to patch it in two places (loaderVersion only), I wonder if we need to be a bit more strategic here and ensure that any Loader workflows always wrap logger with adapter that adds loader properties (there might be more properties in future)?

Something like createOdspLogger() that is used on all entry points in ODSP driver to ensure that we have uniform telemetry across all workflows.

Even better, of course, would be to have all the other Container properties, but I do not know if this is feasible to ask

**Comment by markfields** [comment]
> Even better, of course, would be to have all the other Container properties, but I do not know if this is feasible to ask

What would be the correct behavior when there's more than one container in the lifetime of a loader?  I'm seeing this in about 0.1% of interactive (non-summarizing) clients in our prod telemetry.

In light of the feedback on https://github.com/microsoft/FluidFramework/pull/8346 (which would do what this comment is asking), I'll probably punt on that for now and just patch in loaderVersion.
