### ISSUE TITLE
Loader.request() pass down query params unexpectedly

### ISSUE THREAD

**Issue by yzheng72** [microsoft/FluidFramework#7795]
When we call Loader.request(), we pass in the Sharepoint UR with the data store path. However, when the component get the request url from the Loader, it contains additional query params such as driveId which was not in the original request.

From the user perspective, we are only expecting to see componentId in the request when component request function is called. Or only the params we passed in when we called Loader.request()

**Comment by yzheng72** [comment]
Here is an example of input url:
![image](https://user-images.githubusercontent.com/6943276/136867265-a88ea6a8-2e23-47b6-a764-602f0a43be1d.png)

And here is the value we get when component's request() is called:
![image](https://user-images.githubusercontent.com/6943276/136867230-eff2e266-b6d4-4810-ab0b-e6174d7a424f.png)

**Comment by jatgarg** [comment]
So the nav parameter in the original link contains all the info like driveId, itemId etc.

**Comment by markfields** [comment]
Comment about errors and logging and this - Due to https://github.com/microsoft/FluidFramework/pull/6599. even when the URL has the query string when it shouldn't, we won't include it in the error response value.  This came up internally when we found a test environment on a super old runtime version and it _was_ logging these query strings.

**Comment by leeviana** [comment]
I don't know if this issue was ever resolved

**Comment by leeviana** [comment]
Jason ran into this issue again today so I can confirm that this bug was never fixed @jatgarg

**Comment by leeviana** [comment]
We ran into the issue again today while implementing request() in our root component, so I can confirm that this bug is still not fixed. @anthony-murphy FYI

**Comment by jatgarg** [comment]
I am going to open a corresponding ADo item and then schedule that for next sprint. Will post the link to ADo item here.

**Comment by jatgarg** [comment]
https://dev.azure.com/fluidframework/internal/_workitems/edit/3453
