### ISSUE TITLE
Merge Tree: Rationalize registers

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#78]
Related microsoft/Prague#1381

I'm not sure we want to keep registers. They are currently not used heavily, are not snapshotted,  never clean-up, and not tested well.

If we keep them merge tree should add a new op for copying text to a register, and we should remove the register property from remove op, cut then becomes a group op of copy, and remove.
It's probably ok to keep the register on insert for paste.

**Comment by vladsud** [comment]
This issue is 2 years old. Closing. @anthony-murphy - if we need some cleanup due to not supporting registers right now, please open separate issue,
