### ISSUE TITLE
Clarify meaning/utility of fluid:telemetry:ChannelDisposeError

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7802]
There are a lot of errors in telemetry, with two main error reason being
1. Registry does not contain entry for the package
2. No registry for package

But when I look at individual sessions, all of these errors show up after container is closed.
So it seems like something else fails when container is closed and it propagates to this error, which most likely is not worth raising awareness about.

It would be great to understand if this claim is correct and if we want to reclassify it as not an error or maybe remove event altogether.

It would be also great to standard property set (or maybe only to error set) _containerClosed: this.closed_ property:
```typescript
                all: {
                    clientType, // Differentiating summarizer container from main container
                    loaderVersion: pkgVersion,
                    containerId: uuid(),
                    docId: () => this.id,
                    containerAttachState: () => this._attachState,
                    containerLoaded: () => this.loaded,
                },
```
* #7919

It also feels like we want to report channel loading errors up the stack, i.e. in bindRuntime() & realize() should log an error if we failed to load data store, but probably only if it happened before container closed?
* #8065

**Comment by markfields** [comment]
@vladsud what's the follow-up here once 0.51 gets out there? I have these questions to ask of the data:

* Are these new errors happening after close? We can check the `containerLifecycleState` property to see
* If not, then what happens next? Who's awaiting `channelDeferred.promise` and gets the rejection?

I _think_ analysis of the current error event says that these are happening after close - or at least, no one else is awaiting the context realize before then.  I did see that [processAttachMessage doesn't `catch` after this promise](https://github.com/microsoft/FluidFramework/blob/8780e481ac362639abcb506d4eb4fee31aed181c/packages/runtime/container-runtime/src/dataStores.ts#L195), I wonder if we want a log there too?

**Comment by markfields** [comment]
Opened https://github.com/microsoft/FluidFramework/issues/8667 to get eyes on what should happen when prefetch of DS at the end of processAttachMessage fails.

As for other follow-up, I think it's just a matter of going through top errors.  These are on there, but not at the top.  container lifecycle state is `loaded` when this new `ResolveFailed` event fires.
