### ISSUE TITLE
fluid:telemetry:inactiveObjectChanged

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7803]
There are 15475 errors fluid:telemetry:inactiveObjectChanged coming from 0.47 version of runtime.

First of all, the event should have proper "home", i.e. it should not use root "flud:telemetry" namespace.
But also we need to understand if anything needs to be done to address these errors - that's top error in 0.47

**Comment by vladsud** [comment]
@agarwal-navin, I'm starting to see these events in 0.48 payloads in Bohemia. Given 0.47 volume data, I suspect it will also be our top error in all of telemetry. Can you please take a look and assess what needs to happen here?

**Comment by agarwal-navin** [comment]
@vladsud, I think I might know what's going on. In the documents that have these logs, there are few data stores (either 3 or 5) that are unreferenced from the first time GC runs. I believe these are never marked as referenced in the first place. So, when these data stores receive ops after 7 days, we get this telemetry. I looked at the telemetry for about 10-15 docs and they have the same pattern.

I tried to create components in office.com and Teams and they are all marked as referenced as expected. I think either someone is testing a new component or some other app is not storing component's handles when creating them, maybe Whiteboard?

**Comment by agarwal-navin** [comment]
On further debugging a OneNote meeting document, the following components are never marked as referenced: `@fluidx/tasks`, `@fluidx/tasks/PlannerConnector` and `@fluidx/tasks/SyncBridge`. The latter 2 are created by the tasks component.

I remember `@fluidx/tasks` being a root component. However, in the OneNote document it is a named component but isn't marked as "root".
Also, I opened similar components in office.com and I don' see any of the above components. We should get in touch with the tasks component folks to understand what is happening here.

**Comment by vladsud** [comment]
Is there anything we can do to force people to realize mistakes sooner?

One thing to consider - we need to remove ability to bind objects (DDS/data stores), I.e. there needs to be either root object, or it gets attached when its handle is stored somewhere.
Can we make that switch today? At least for data stores?
I think this will make it immediately apparent to developers that such components do not make it into a file.

**Comment by agarwal-navin** [comment]
The tasks bug has been fixed by the tasks team. Also, the telemetry has been updated to log only once per data store per session - https://github.com/microsoft/FluidFramework/pull/7985
