### ISSUE TITLE
convert Buffer Parsing Exception messages to error code format

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#7812]
Looks like all the messages passed to `throwBufferParseException` are hardcoded and should be converted to error codes (camel case) and passed to `createOdspNetworkError` as the `fluidErrorCode`.  Or, we could decide it's better to keep all these under one error code and leave it as-is, and close this.

_Originally posted by @markfields in https://github.com/microsoft/FluidFramework/pull/7788/files#r726618889_

**Comment by mqnguyen5** [comment]
Hi, I was wondering if this is an issue that I could work on. If so, I will probably need some help on where to start since I'm new to contributing.

**Comment by markfields** [comment]
@mqnguyen5 Happy to help, and have your help! Start by looking at the code that calls the function where that log is, and see what kinds of values are passed as message. If they're all string literals describing different cases, then we're in business. The goal then would be to get that info in some fields other than error message. Either fluidErrorCode, or maybe a custom property "reason".

Leaving out some details for now, take a look and let me know what questions come up, happy to spell it out more as you familiarize yourself here.

**Comment by markfields** [comment]
We've moved away from error codes and back to messages, see #9249.
