### ISSUE TITLE
Upgrade to tsc 4.4

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#7817]
See the following release notes, especially the Breaking Changes sections:
* https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html
* https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html
* https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html

Looking it over, there are two breaking changes that caught my attention:
1. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#usedefineforclassfields-now-defaults-to-true-on-esnext-and-eventually-on-es2022
2. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#more-compliant-indirect-calls-for-imported-functions

For (1), ~~we should explicitly set `useDefineForClassFields` to `true` first to flush out any issues there (#7849)~~ we don't need to do anything because we still target ES 2017
For (2), could be a non-issue but `this` is always very subtle so I'm calling it out.

Instructions for doing this update can be found [here in the wiki](https://github.com/microsoft/FluidFramework/wiki/Dev-Tools-Maintenance).

**Comment by CraigMacomber** [comment]
Typescript 4.6.3 is out now. Any reason not to just update all the way?

I'm happy to pick up this work, at least until I run into any non-trivial blockers.

**Comment by CraigMacomber** [comment]
Looks like newest API-Extractor targets typescript ~4.5.2, so I'll try and upgrade to typescript 4.5.5, and update @microsoft/api-extractor. There also seem to be issues with jsdom's types, so updating it as well. So far it looks like this update will be practical.

**Comment by markfields** [comment]
> Typescript 4.6.3 is out now. Any reason not to just update all the way?

Looks like you're set on 4.5 for now, seems fine.  It's just a matter of poring over the release notes and understanding what breaking changes if any will impact the d.ts output (since some partners are on older TS versions, even 3.x)
