### ISSUE TITLE
Perf variability: e2e Perf numbers

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#7880]
Not sure if this an actual issue or just environmental noise (e.g. network), but it is interesting that spikes appear in data from our e2e test targeting ODSP for average time across all tests for those build.  Can we see if there is some cause on the server side not?

```
let testData = union kind=outer database("Office Fluid Test").*ffautomation*
| where Data_testVariant == "odsp" and Event_Time >= ago(7d) and Data_testName contains "Non-Compat";
let passTest = testData
| where Data_eventName == "fluid:telemetry:Test_end" and Data_state == "passed"
| project Data_buildId, Data_testName;
let testDate = testData 
| summarize max(Event_Time) by Data_buildId;
let passTestData = passTest
| join kind=inner testDate on Data_buildId
| join kind=inner testData on Data_buildId, Data_testName
| extend Build=strcat(Data_buildId, " (", format_datetime(max_Event_Time, "MM-dd HH:mm"), ")");
passTestData
| where isnotempty(Data_duration)
    and Data_eventName !startswith "fluid:telemetry:SummaryManager"
    and Data_eventName !startswith "fluid:telemetry:DeltaManager"
    and Data_eventName !startswith "fluid:telemetry:Summarizer"
    and Data_eventName !endswith "_cancel"
    and Data_eventName != "fluid:telemetry:OdspDriver:ConnectionSuccess"
    and Data_eventName != "fluid:telemetry:OdspDriver:MultipleRetries"
| summarize avg(Data_duration) by Build, Data_eventName
| summarize d=make_bag(pack(Data_eventName, avg_Data_duration)) by Build
| evaluate bag_unpack(d)
| render linechart with (xcolumn=Build)
```

**Comment by vladsud** [comment]
No progress yet, keep pinging right folks :)

**Comment by vladsud** [comment]
The most useful visualization of prod data that shows time sensitivity:

> Office_Fluid_FluidRuntime_Performance
| where Event_Time > ago(30d)
| where Event_Time < ago(0d)
| where Data_eventName == "fluid:telemetry:OdspDriver:createNewFile_end"
| summarize count(), P=percentile(Data_duration, 95) by bin(Event_Time, 1h)
| where count_ > 1000
| project P, Event_Time
| render timechart 

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/46826984/174661972-0d76f033-8c62-43d6-b78e-2978818903bd.png">

And the most useful query about our builds:

> let testData = union kind=outer \*ffautomation\*
| where Data_testVariant == "odsp" and Event_Time >= ago(7d) and Data_testName contains "Non-Compat";
let passTest = testData
| where Data_eventName == "fluid:telemetry:Test_end" and Data_state == "passed"
| project Data_buildId, Data_testName;
let testDate = testData
| summarize max(Event_Time) by Data_buildId;
let passTestData = passTest
| join kind=inner testDate on Data_buildId
| join kind=inner testData on Data_buildId, Data_testName
| extend Build=strcat(Data_buildId, " (", format_datetime(max_Event_Time, "MM-dd HH:mm"), ")");
passTestData
| where Data_eventName == "fluid:telemetry:OdspDriver:createNewFile_end"
| where isnotempty(Data_duration)
| where Data_duration < 100000
| summarize count(), P=percentile(Data_duration, 90) by Build
| where count_ > 200
| project P, Build
| order by Build
| render linechart with (xcolumn=Build, ycolumns=P)

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/46826984/174662250-8d0a868a-2de0-421e-8c43-f1c0127d7ebd.png">

The correlation with time is not as strong as per build, so there are some unique things happening per build that I can't explain simply by when build runs.

**Comment by vladsud** [comment]
I've ported it as https://dev.azure.com/fluidframework/internal/_workitems/edit/852
