### ISSUE TITLE
Connectivity eventing improvements

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7884]
Per https://office.visualstudio.com/OC/_workitems/edit/5489692?src=WorkItemMention&src-action=artifact_link, we need to
- ~expose "connect" event from Container, to allow hosts to know when connection has been established (and stop showing disconnected banner).~
  - [update] -- @markfields will work with @scottn12 to clarify the ideal list of events, including updated names and very clear semantics/gaurantees. The plan is written up in https://github.com/microsoft/FluidFramework/issues/9677.
- Change when "connected" event is raised for "read" connections - make it fire only when container is up-to-date (based on what we know, i.e. checkpointSequenceNumber, maybe storage call coming back)
   - This will ensure that transition from "read" to "write" connection will not suddenly make container not up-to-date.

**Comment by markfields** [comment]
Moving to Jan due to my constraints in Dec with OCE and holidays.  On my mind though as I'm working with Office Fluid team on connection API/health metrics.

**Comment by markfields** [comment]
Unless this is directly related to recent problems with visual op replay, I'd like to move to Feb.  @vladsud let's discuss next week.

**Comment by markfields** [comment]
I'm gearing up to work on the parent epic #7995 in March, moving this hear for now to get incorporated into that planning.

**Comment by markfields** [comment]
Tracking via AB#144
