### ISSUE TITLE
Fix e2e tests related to wrong container url generated in create/load tests

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#7885]
## Describe the bug
For FRS the container.id is generated by server and this PR fixed the loading of container by updating the container id after attaching the container: https://github.com/microsoft/FluidFramework/commit/789e0023dbd6fc3d6008b95537e57505d854234b

But for odsp, the id is generated by client and that id could be different from filename or in broad sense it may not be round tripable, as in we might not be able to load the container with same id(container.id). Example, for odsp, the container.id is hash of drive and itemid and we are not able to derive both ids from that. 
So we need to come up with a way which fixes these tests and make the container.id round tripable otherwise it is useless.

**Comment by alpaix** [comment]
Fixed with #8121
