### ISSUE TITLE
Improve audience list reliability

### ISSUE THREAD

**Issue by Dhoot** [microsoft/FluidFramework#7889]
## Problem
Currently, audience list is not reliable because we are using web-socket to maintain and pass-on information about newly connected client and recently disconnected client. But sometimes client miss these events, and we end-up with stale clients in the Audience list.

### Possible Solution
To improve and handle this web-socket message drop issue we can use a simple Heartbeat / Ping-Pong kind of mechanism i.e. all connected clients will send ping message to all another client and every client will keeping last received ping time and in case of crossing threshold difference in time client will fetch a fresh Audience list to all connected from Redis.

**Comment by vladsud** [comment]
There are two reasons / angles where audience is not reliable:
1. Lack of global order of signals and no guaranteed delivery of signals
2. Potential reliability of redis 

We are going to address #1 - this is tracked (for now) in internal [document](https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!-LGon2SERESaUEtDjVeQCQGlntvDqQxInIB2-Tt0tikQ-h6_dlUfQZzxXnTazrK9&item=012NT7JKZKSMXKXBJDV5HIXB3XPUNE64PG&file=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fgarywilb_microsoft_com&siteUrl=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fgarywilb_microsoft_com).

There should be no direct work required on client side to support new flow.
That said, I'll be opening other issues in related areas soon, namely when connected events fire relative to audience population.

@markfields - FYI
