### ISSUE TITLE
*-client packages should update peerDependencies with bump script

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#7913]
the tinylicious-client and azure-client have peer dependencies on the fluid-framework packages. These versions should automatically bump to stay in sync with the latest.

**Comment by tylerbutler** [comment]
@heliocliu Do you have a sense for how hard this is to do? Asking you since you've been working on the version bump tool recently.

**Comment by heliocliu** [comment]
@tylerbutler Pretty easy, I guess that we've decided peerDependencies are the correct thing to use we probably want to get this done in March/April?
