### ISSUE TITLE
Encapsulate container lifecycle state

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#7935]
Vlad had suggested having a method, changeState, that is called in all cases where we change the _lifecycleState, and that method encapsualtes the allowed state change state machine.

I think we could take that even a step further, and add a new class that encapsulates the var , state machine function, and properties. this would put all the lifecycle changes in one place, and allow us to prevent anyone from directly changing the state var

so something like 
```
get state;
get isClosed;
get isLoaded;
changeState(from, to);
```

_Originally posted by @anthony-murphy in https://github.com/microsoft/FluidFramework/pull/7933#discussion_r734046743_

**Comment by markfields** [comment]
I would think attach state could go in the same lifecycle object

**Comment by markfields** [comment]
Not sure if we have a good epic for this one, it's a generic "code health" follow-up item.  Not high priority in and of itself, but more good hygiene to knock it out "soon" - I think I've already failed at that tbh, so planning to prioritize in Jan, I can timebox it and it won't take long.

**Comment by kumarrus** [comment]
Hi, I'm a new contributor. Would it be okay if I take up this issue?

**Comment by markfields** [comment]
@kumarrus Go for it!  Post back with any questions as you go, or even better push a draft PR even if incomplete and we can discuss in there.

@vladsud, @anthony-murphy - Any thoughts on whether this should also subsume attach state? Seems like it to me but wanted confirmation before pointing Rushab in the wrong direction.

**Comment by vladsud** [comment]
I think attach state is orthogonal to lifecycle states (for most part)

**Comment by markfields** [comment]
Ok took another look and I agree. Especially transitioning to the closing/closed state, that could happen whether or not the container ever attached.

I had been thinking about how `attach` asserts the lifecycle state is `loaded` at the top, such that attach state `attaching` and `attached` would each imply `loaded`, but that's only part of the story (and doesn't even hold up looking at the load-existing flow)

**Comment by kumarrus** [comment]
Thanks, @markfields. I'll draft a PR soon. Would need some guidance regarding the possible and impossible state transitions.

**Comment by kumarrus** [comment]
@markfields I've created a draft PR. Looking forward to your feedback.

**Comment by markfields** [comment]
Moving to "Next" milestone since we're not holding this to any internal planning milestones
