### ISSUE TITLE
Collect HW telemetry info 

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7984]
As @curtisman was looking at speed of op processing, I wondered can we get some baseline about machine capabilities, such that we can correlate data we have with capability of machines, and compare apples to apples (for example, distribution of capabilities maybe different for Whiteboard vs. Teams users, so saying that Whiteboard is 2X faster in op processing is not correct without correlating with this data).

I suggest having a separate event from container runtime that does such collection (one event, not property on every event).
Unfortunately I do not see detailed info (better would be cpuid), but even something will go a long way:

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/deviceMemory
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/hardwareConcurrency

Note that it's not supported by all browsers, so any collection should withstand failures.

@markfields - FYI

**Comment by chensixx** [comment]
@vladsud  it seems deviceMemory cannot be accessed yet, since it's experimental. Unless there is another way to do it other than `navigator.deviceMemory`?

**Comment by vladsud** [comment]
Can we write code such that it is collected where it's present and not collected where it's not? If so (and assuming most of our clients would actually collect that data), experimental nature of it does not matter that much in this context.
What we should avoid is crashing or doing something else abnormal if it's not supported on a given browser (or support changes over time)
