### ISSUE TITLE
Schema versioning and upgrade support

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#8006]
The epics covers the design and prototyping of the schema versioning and upgrade feature.

## Goals
- Design a public 3P container-level schema migration API.
- Define a schema versioning entity persisted in the container's quorum.

## Non-goals 
- No support for the component versioning at this point.
- No support for a revision history and recovery in any form.
- Transactional engine for applying data migrations will be covered in a separate epic.

## Work Items
- [x] #8131
- [x] #8132
- [x] #8133

## Tracking Document
[Fluid Document Schema Versioning](https://microsoft.sharepoint-df.com/:w:/t/OfficeOnlinePrague/EbPKLgsE_eNCiDKb97KUoSYBz8EiTbITTzCQyUCZC9Smag?e=JEmTFm)

**Comment by ChumpChief** [comment]
This is better tracked by #9720
