### ISSUE TITLE
fluidframework.com site search

### ISSUE THREAD

**Issue by danielroney** [microsoft/FluidFramework#8012]
Site search should cover our API docs _and_ narrative docs, and search results should be grouped/sorted such that it's easy to get to particular API types (e.g. classes vs. interfaces).

### Inspiration:

* <https://angular.io/>
* <https://reactjs.org/> (Algolia)
* <https://www.typescriptlang.org/> (Algolia)
* <https://code.visualstudio.com/>

### Client-side search libraries

* [Fuse.js](https://fusejs.io/)
* [lunr.js](https://lunrjs.com/)

### Commercial options

* [Algolia](https://www.algolia.com/)

### Useful resources

* [Client side searching for Hugo.io with Fuse.js](https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae)
* [Alternative implementation of Fuse.js](https://gist.github.com/cmod/5410eae147e4318164258742dd053993)
* [Tool to produce JSON from Hugo markdown/front-matter input](https://github.com/arranf/HugoToJSON) -- this JSON data can then be used as input to lunr.js

List of work items:

- [x] #2210
- [ ] Spec search results presentation and grouping.

**Comment by skylerjokiel** [comment]
Moved to ADO
