### ISSUE TITLE
Consider optimizing JoinSession call: reduce Options call.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8032]
Per the table in https://github.com/microsoft/FluidFramework/pull/7896 (copied below), we need to make all POST calls be without OPTIONS call, as any headers can be put into the body of request, and thus eliminate such call.

Exception is create new and snapshot upload, as their payload size likely to exceed 
This leaves us with join session call, I believe.

Note that this is lower priority than some other bugs referring to this table.

<html>
<body>

Call Name | Call Type | Options Call
-- | -- | --
Create new | POST | Yes
Trees Latest V1 | POST | No
Trees Latest V2 | GET | Yes
**Join Session** | **POST** | **Yes**
Get Blob | GET | Yes
Upload Summary | POST | Yes
Ops Fetch | POST | No

</body>
</html>

**Comment by anthony-murphy** [comment]
something to keep in mind here. Options calls are made by the browser automatically for all non-simple requests. I don't think it will be feasible to make all our request simple, so we may not be able to remove options calls: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests

However, we should be able to limit the number of options calls made, as they should be shareable across calls and cached.

**Comment by jatgarg** [comment]
I am able to make it a simple call and avoid options call. Thanks Marcelo for that. 
I see that previously avg time taken by **Join Session Call was 1030 ms + 350 ms for options call**. **Total of 1380 ms.**
With the simple network call, it just takes **400 ms** on average, giving us **savings of about ~1sec.**
