### ISSUE TITLE
Is it possible to remove options call for GetBlobs calls?

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8033]
Per the table in https://github.com/microsoft/FluidFramework/pull/7896 (copied below), Get Blob calls are inefficient - they are making options call due to usage of headers. Is it possible to optimize somehow?

Note that it's much more important for these calls to be catchable GET calls than not have options call (let's say using POST flow). So if it's not possible to reduce usage of headers, it likely has to stay as it is today.

<html>
<body>

Call Name | Call Type | Options Call
-- | -- | --
Create new | POST | Yes
Trees Latest V1 | POST | No
Trees Latest V2 | GET | Yes
Join Session | POST | Yes
**Get Blob** | GET | **Yes**
Upload Summary | POST | Yes
Ops Fetch | POST | No

</body>
</html>

**Comment by jatgarg** [comment]
I have looked about it on the web. For getBlobs call we need to maintain the browser caching and hence we cannot convert it to a ump post request which will make it non cacheable. In some cases we can cache the post requests, but then it results need to be only used by a subsequent GET request and not by a POST. 
Also this is not in critical path. so it can stay as it is. Closing the issue.
