### ISSUE TITLE
Handle parameter default values in API change detection

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#8038]
Parameter default values require additional handling logic
e.g.
```
function dumbFunc(a: number = 111);
```

**Comment by tylerbutler** [comment]
@heliocliu This is marked as complete in #8008. Is it actually done?

**Comment by heliocliu** [comment]
@tylerbutler yeah it's actually done.  sometimes easy to forget that moving an item to the "done" column doesn't actually close it 🙃
