### ISSUE TITLE
Update release system to work with new method of tracking package versions

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#8055]
Dependent on #8054 

When our way of tracking packages changes, we need to ensure the release system is updated to support it as well.  Particularly where the versions to release come from, because the current expected location (the package.json itself) may no longer be the source of truth.

**Comment by vladsud** [comment]
@heliocliu, this item is in December milestone and not assigned. Can you please follow up and figure out what's the plan here?
Is it really happening in December? If so, who's working on it?
If not, what's the right milestone and developer to assign to?

**Comment by heliocliu** [comment]
Not December and should be assigned to me for now; the way we were looking at items for the sprint was causing this to get overlooked.  Thanks for pointing it out
