### ISSUE TITLE
ODSP: Latency optimizations

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#8084]
This Epic tracks issues that aim at improving latency of certain network operations.
They either track known bugs / areas we can improve, or areas that do not look right based on telemetry or ODSP stress tests and need to be looked at.

- [x] #8031 
- [ ] #8694
- [x] #8032
- [x] #8033 
- [ ] #7880
- [x] #7406

**Comment by vladsud** [comment]
I think it's time to close this EPIC.
