### ISSUE TITLE
CI should use node 14

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#8098]

**Comment by curtisman** [comment]
@tylerbutler is this mostly done?  Looks like all the pipeline/github action already uses version 14.
Only the devcontainer still have 12 as the default, right?  Anything else missing?

**Comment by tylerbutler** [comment]
> @tylerbutler is this mostly done?  Looks like all the pipeline/github action already uses version 14.
> 
> Only the devcontainer still have 12 as the default, right?  Anything else missing?

Yeah, I think the pipelines are all done now.
