### ISSUE TITLE
Unknown errorTypes recorded by our telemetry

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8163]
Office_Fluid_FluidRuntime_Error
| where Data_loaderVersion contains "0.49"
| where Data_errorType != ""
| summarize count() by Data_errorType

Gives me these error types that I do not recognize - they are not in our repo!

CreateAndCachePromiseError	34
ErrorWithLocalizedString-CreateAndCachePromiseError	7

Based on the errors for first type (like "-Error: Received an error from IPC::{"eventName":"aadGetToken","error":"resourceDisabled","correlationId":"17610973-923d-4a05-a460-52d1b23e3640"}::isOnline-true"), this looks like token callback, which I assume uses same schema. I think that's rare place where we want to overwrite errorType!

Worth taking a look at second case as well

Also I think this one is the same issue (in a sense that it does not have right errorType, but probably can be verified to be coming from token callback and it should set errorType):

Data_eventName == fluid:telemetry:Container:storage_getVersions
Data_error == popup_window_error: Error opening popup window. This can happen if you are using IE or if popups are blocked in the browser. Details: BrowserAuthError: empty_window_error: window.open returned null or undefined window object.	
or Data_error == _acquireToken::NetworkOffline::isOnline-false
or Data_error == Failed to acquire auth token for SharePoint
or Data_error == Interactive sign-in is required to get access token

**Comment by vladsud** [comment]
Couple more - these seem all token fetches, so assume your fix is addressing that?

fluid:telemetry:Container:ContainerClose	Teams token retrieval timeout	genericError	1563
fluid:telemetry:Container:ContainerClose	_acquireToken::NetworkOffline::isOnline-false	genericError	843
fluid:telemetry:Container:ContainerClose	Broker response returned error: WAM Error  genericError	398
fluid:telemetry:Container:ContainerClose	post_request_failed:  undefined	genericError	263


This one is more interesting - this is host code calling into close with their error object - not sure if we want to put some errorType on it?

fluid:telemetry:Container:ContainerClose	Current version of the container 'Dogfood'-'20211103005' is no longer supported	genericError	383

**Comment by markfields** [comment]
> This one is more interesting - this is host code calling into close with their error object - not sure if we want to put some errorType on it?
> 
> fluid:telemetry:Container:ContainerClose Current version of the container 'Dogfood'-'20211103005' is no longer supported genericError 383

They are setting `genericError` on it.  Are you suggesting we help them find a different errorType?  This case could be fixed up by #8623, they can just pass this as `reason` instead of having to craft an error?  Unsure if that's better.

**Comment by markfields** [comment]
@vladsud, I took a look at these. All the token fetch ones are addressed by #8151 which is in 0.51.  On account of this and my previous comment, closing this issue.
