### ISSUE TITLE
fluidErrorCode content in telemetry does not seem like what we expect to see

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8164]
Office_Fluid_FluidRuntime_Error
| where Data_loaderVersion contains "0.49"
| summarize count() by Data_fluidErrorCode

I think it is supposed to be a call site, i.e. unique tag in the code.
But with exception of very few cases (including first one), it's not the case:

deltaManagerEmitDelayInfo	3337
Error 403 (Forbidden)	2616
fetchError	1477
Error 403	1338
Error 404	674
Error 401	655
Load from summary, runtime metadata sequenceNumber !== initialSequenceNumber	410
realizeFluidDataStoreContext	319
Error 503	288
Error 400	206
Error 401 (Unauthorized)	163
Error 404 (Not Found)	155
failedToRetrieveOpsFromStorage:TooManyRetries	82
errorWhileParsingFetchResponse	52
epochMismatch	37
none	34
Error 412	31
Error 400 (Bad Request)	29
timeoutDuringFetch	14
storageServiceDisposedCannotRetry	13
errorWhileParsingFetchResponse (OK)	7
Error 503 (Service Unavailable)	4
Error 412 (Precondition Failed)	3
Error 500 (Internal Server Error)	1
channelDeltaConnectionFailedToProcessMessage	1

**Comment by markfields** [comment]
Some of these are from #7788 and will clean up over time as that change saturates.  Others need follow-up discussion on how we use fluidErrorCode.  Will dig in in December to get clarity and fix as needed.

**Comment by markfields** [comment]
@vladsud - The list is looking better in >= 0.50:

![image](https://user-images.githubusercontent.com/12305068/145872601-f6d9030a-8eb4-4156-a9d0-a2f66aebee40.png)

Here are the exceptions IMO, but they're from old driver versions (based on knowledge or code, and I spot-checked a couple... #8069 would help here!):
* `Error XXX`
* `socket.io ...`

If you take those out, I'm happy with what's left, for now.

We will continue to refine how fluidErrorCode is instrumented/interpreted, and some issues are open now about it, but as for this issue I'm closing it.
