### ISSUE TITLE
Documentation linked from README.md no longer exists.

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#8177]
Generated from [template](https://github.com/microsoft/FluidFramework/blob/ec68c3665e5df350bdf94a74d871511535f33d03/.md-magic-templates/readme-simple.md)

Links in README.md doesn't work:
https://github.com/microsoft/FluidFramework/blob/ec68c3665e5df350bdf94a74d871511535f33d03/packages/dds/cell/README.md?plain=1#L3
https://github.com/microsoft/FluidFramework/blob/ec68c3665e5df350bdf94a74d871511535f33d03/packages/dds/counter/README.md?plain=1#L3
https://github.com/microsoft/FluidFramework/blob/ec68c3665e5df350bdf94a74d871511535f33d03/packages/dds/task-manager/README.md?plain=1#L7
https://github.com/microsoft/FluidFramework/blob/ec68c3665e5df350bdf94a74d871511535f33d03/packages/framework/fluid-framework/README.md?plain=1#L27

**Comment by pizzaz93** [comment]
Are these the correct links?

* https://fluidframework.com/docs/data-structures/counter/

* https://fluidframework.com/docs/data-structures/task-manager/

* https://fluidframework.com/docs/apis/fluid-framework/ifluidcontainer/

Cell I wasn't able to find except https://fluidframework.com/docs/apis/fluid-framework/#fluid-framework-maxcellposition-Variable
