### ISSUE TITLE
ODSP: Log websocket host name

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8182]
It would be great for JoinSession_end event in odsp driver to log websocket host name (like southcentralus0.pushfs.svc.ms).
This will help us understand where we connect (i.e. if it's SPDF or not), which is helpful in diagnostics of issues (as that's usually the first thing Gary is asking for).

**Comment by markfields** [comment]
@chensixx - Ctrl+Shift+F in VS Code for `"JoinSession"` to find the event. The `_end` is tacked on the event name when the event completes successfully.  The callback where the code is executed is passed the telemetry event, so you can set the new property on it and it will be included when logged at the end.
