### ISSUE TITLE
Deep dive for TableDocument

### ISSUE THREAD

**Issue by scottn12** [microsoft/FluidFramework#8187]
The `TableDocument` class and associated interfaces have been deprecated. To replace its functionality, use SharedMatrix with the `IMatrixProducer`/`IMatrixConsumer` interfaces instead.

## Steps
- [x] #8712
- [x] #8714
- [x] #8715

Final FF removal step based on compatibility resolution: https://github.com/microsoft/FluidFramework/issues/8775

**Comment by ssimic2** [comment]
@DLehenbauer let us know if you have any further context/comments on this deprecation. It seems there are 3 parts that require consideration:

1. Expose annotation on` SharedMatrix` (rows and columns). It should be fairly straightforward to surface the missing API.
2. Consider ability to create "slices" - something table documents can do. I don't see this widely used though.
3. `createTableWithInterception`. This is composition pattern, so again it should be straightforward to move around. However, if the usages are one-offs maybe this logic lands on the consumers and out of FF.

**Comment by ssimic2** [comment]
Hey @leeviana, TableSlice does not seem used any further in tablero, please correct me if I'm wrong. I do see some older tablero snapshots referencing TableSlice. If that is the case, as we transition to SharedMatrix we probably don't need to consider supporting slicing at this point.

**Comment by leeviana** [comment]
Yes, I believe that was removed at some point. Technically because there's no Framework "op upgrader" story, I think we'd still need some component around that responds to the TableSlice component type string and has TableSlice looking DDSes for back compatibility in those documents (among other things, the summarizer running on a document from the beginning of time will crash the document if it can't find all the components that it expects to). But we don't have to consider any more functional support than that.

How old are these "older" tablero snapshots, do you know?

**Comment by ssimic2** [comment]
> Yes, I believe that was removed at some point. Technically because there's no Framework "op upgrader" story, I think we'd still need some component around that responds to the TableSlice component type string and has TableSlice looking DDSes for back compatibility in those documents (among other things, the summarizer running on a document from the beginning of time will crash the document if it can't find all the components that it expects to). But we don't have to consider any more functional support than that.
> 
> How old are these "older" tablero snapshots, do you know?

Those are from Oct. 2019. I'll chat with you briefly on "op upgrader" story. It seems without that story we have very limited path on finally removing some of the deprecated logic here.

**Comment by leeviana** [comment]
Yeah, I think the upgrader story is currently being tracked here, though the need/ask has been around since the beginning of time: https://github.com/microsoft/FluidFramework/issues/8006

For now, we have to keep back compat for all ops and old DDSes forever.
