### ISSUE TITLE
Replace logger with taggedLogger

### ISSUE THREAD

**Issue by scottn12** [microsoft/FluidFramework#8191]
This issue aims to replace the vanilla logger with taggedLogger in the IContainerContext interface. The logger property was deprecated in release 0.45. 

The files affected are:
1. common\lib\container-definitions\src\runtime.ts
2. packages\loader\container-loader\src\containerContext.ts
3. packages\runtime\container-runtime\src\containerRuntime.ts

**Comment by ChumpChief** [comment]
This seems fine to me, with one of two approaches, @markfields in case he has more context/feedback to help choose which.

1. If we think there's risk that some old loader is trying to load modern containers (and also that it's a scenario we need to support), then a reasonable approach might be:
    * Remove the property from the interface and `ContainerContext`, but in `ContainerRuntime` continue to do a last-ditch `TaggedLoggerAdapter` fallback
    * Then log a bug for removing the adapter usage from `ContainerRuntime` and the `TaggedLoggerAdapter` class, including an explanation of when we think it will be safe to do (and/or what metric will inform that decision).
2. If we don't think there's risk, then we should just go ahead and remove it in all locations (including removing the `TaggedLoggerAdapter` class.

**Comment by markfields** [comment]
Let's go with 1.  Reason being, even though there are only a hundred or so clients with very recent runtimes and pre-0.45 loaders in the last month, just 1 will result in bogus columns getting added to our internal data tables for the tag and value.  And worse, if someone _does_ add privacy-impacting data and tag it, we would have to do a whole thing to clean it up.
