### ISSUE TITLE
Repalce OdspDocumentInfo with OdspFluidDataStoreLocator

### ISSUE THREAD

**Issue by scottn12** [microsoft/FluidFramework#8192]
## Overview

The `OdspDocumentInfo` type has to be replaced with `OdspFluidDataStoreLocator` interface.

## Proposed Solution

There are no known instances of these `OdspDocumentInfo` type being used in the internal repositories searched (FluidExamples, Bohemia, OneNote). Bohemia uses `OdspFluidDataStoreLocator` interface. Therefore, the type declarations can simply be removed from the FluidFramework repository.

## Methodology

The `OdspDocumentInfo` type will be removed in the following files:

1. packages\drivers\odsp-driver\src\contractsPublic.ts

The `OdspDocumentInfo` type will be replaced with `OdspFluidDataStoreLocator` in the following file:
1. packages\drivers\odsp-driver\src\odspDriverUrlResolverForShareLink.ts

**Comment by ChumpChief** [comment]
Currently, `OdspDocumentInfo` is used as the type of a parameter to `OdspDriverUrlResolverForShareLink.createDocumentUrl()`.  Is the plan to remove that function entirely (preferable if we can, and I don't see any usage currently)?  Or change the param type to `OdspFluidDataStoreLocator`?

@jatgarg might want to take a look too.

**Comment by heliocliu** [comment]
It looks like those types are aliased so it would probably be fine just to replace it there.  Then as usual, please make sure to add an entry in the `BREAKING.md` with info on the change, the affected packages, and how to migrate from the old type to the new type

**Comment by sdeshpande3** [comment]
> Currently, `OdspDocumentInfo` is used as the type of a parameter to `OdspDriverUrlResolverForShareLink.createDocumentUrl()`. Is the plan to remove that function entirely (preferable if we can, and I don't see any usage currently)? Or change the param type to `OdspFluidDataStoreLocator`?
> 
> @jatgarg might want to take a look too.

I was planning on changing the param to `OdspFluidDataStoreLocator`. Please let me know your thoughts.

**Comment by jatgarg** [comment]
Yes we can remove it and put that info in Breaking.md. It was already deprecated:
/**
 * @deprecated - use OdspFluidDataStoreLocator
 */
export type OdspDocumentInfo = OdspFluidDataStoreLocator;
