### ISSUE TITLE
Odsp fetchHelper fakes offline in fetch error cases

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#8196]
https://github.com/microsoft/FluidFramework/blob/main/packages/drivers/odsp-driver/src/odspUtils.ts#L131

I don't know the history of this so someone with more context should probably offer an opinion, but a fetch failure is not a great indicator of offline (this error can pop from many causes).  Forcing it to be treated as offline results in confusing telemetry where some fields indicate online and others indicate offline, and can easily be a bad assumption as we've seen recently.

I'd recommend leaving online/offline status alone in this case and instead finding a way to log this as an "unknown fetch error" or similar, since we know we don't know enough to deduce the true cause.

**Comment by markfields** [comment]
This logic has been around forever, see #414.

But looking at an arbitrary session that hits these errors, I tend to agree with @ChumpChief that this may not be the right conclusion:

![image](https://user-images.githubusercontent.com/12305068/149239074-c73bec9c-cd5a-4ed0-b818-c4812e2b82cf.png)

I do think we can classify these errors as "blips" that happen outside of our control, but I'm not sure about labeling them as "offline".

@vladsud do you have additional context to share here?

**Comment by markfields** [comment]
@ChumpChief can you remind us what the recent bad experience was, and how this came into play?  Internal ticket https://portal.microsofticm.com/imp/v3/incidents/details/271367005 mentions this issue but doesn't tell the story.

**Comment by ChumpChief** [comment]
I believe in the instance that inspired the bug, there was a DNS outage that was causing fetch failures.  During investigation, the "offline" clue in telemetry was a false lead that slowed us down.

If we get a fetch error, just say fetch error basically.  It may still not be very actionable but at least won't be a red herring.  There are too many things that can cause a fetch error to immediately jump to "we must be offline".

**Comment by ChumpChief** [comment]
Example, while fully online:

```console
> fetch("https://foobar").catch(console.log)
< Promise {<pending>}
  GET https://foobar/ net::ERR_NAME_NOT_RESOLVED
  TypeError: Failed to fetch
    at <anonymous>:1:1
```

**Comment by vladsud** [comment]
There is no way to detect reliably offline in the browser (even most trivial case like no connected network adapter).
Generic error like "TypeError: Failed to fetch" historically make people push bugs our way with narration similar to "that's FF bug"
I do not want to deal with them :) So similar to evolution of fileNotFoundOrAccessDeniedError (error returned on 404) that started to be fileNotFound some time ago, I'd prefer to evolve to something like DriverErrorType.offlineErrorOrDnsResolutionError, but differentiate from other fetch errors.

**Comment by markfields** [comment]
Just did some looking at telemetry here (for something else, but wanted to leave a note here).  In 30 days of recent data for Office Loop telemetry:

* 1.4M log lines with error message `TypeError: Failed to fetch` (this is the error that we take to mean "offline")
* 158k of them also logged what the browser's `navigator` said about online/offline
  * 150k claimed "ONLINE"
  * 7500 agreed "OFFLINE"

Not necessarily actionable, just interesting to see.
