### ISSUE TITLE
Container's "closed" event does not document well PII considerations of logging error objects

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8210]
We recommend consumers to use our APIs to monitor errors and log in there telemetry pipeline.
So using "closed" event, it compiles to IErrorBase interface.
But it's pretty barebones interface and it does not tell all possible combinations of properties there can be (and we can't).
But most important - it does not point to a fact that all properties hae to be of TelemetryEventPropertyType | ITaggedTelemetryPropertyType, and proper description how to think about properties that might have PII content.
That seems like a must, in a form of IErrorBase clearly articulating shape of all properties (including unknown properties).

A great addition on top of that would be a stringify function for errors that would be able to strip all potentially PII holding properties (similar how we do for loggers that do not understand that structure).

Putting it in November, as Teams folks (Marco) are hitting it right now. Some guidance is required with some quick follow up, but maybe we can do it in December.

**Comment by markfields** [comment]
I was just thinking about this yesterday! My plan will be to update `IErrorBase` to:

```typescript
export interface IErrorBase extends Error {
    readonly errorType: string;
    readonly message: string;
    readonly stack?: string;
    getTelemetryProperties(): ITelemetryProperties;
}
```
