### ISSUE TITLE
Replace createCreateNewRequest with createOdspCreateContainerRequest

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8223]
## Overview

The `createCreateNewRequest` function should be replaced with `createOdspCreateContainerRequest` function in `odsp-driver` package. 

## Proposed Solution

There are few instances where the `createCreateNewRequest` function is used in Fluid Framework repository. The function is not being used in other internal repositories (FluidExamples, Bohemia, OneNote). The function can be replaced with `createOdspCreateContainerRequest` function and updated in BREAKING.md.

## Methodology

The `createCreateNewRequest` function is removed from the following files:
1. packages\drivers\odsp-driver\src\odspDriverUrlResolver.ts
2. packages\drivers\odsp-driver\src\odspDriverUrlResolverForShareLink.ts

The `createCreateNewRequest` function is replaced with `createOdspCreateContainerRequest` in the following files:
1. packages\drivers\odsp-driver\src\test\odspCreateContainer.spec.ts 
2. packages\drivers\odsp-driver\src\test\odspDriverResolverTest.spec.ts 
3. packages\tools\webpack-fluid-loader\src\odspUrlResolver.ts

**Comment by ChumpChief** [comment]
In order to remove from webpack-fluid-loader, you might need to update multiResolver.ts to use the real ODSP url resolver (from odsp-driver).  It might be easiest to do this as two separate PRs, one that only touches the odsp-driver files, and a second that modernizes multiResolver.
