### ISSUE TITLE
offline blob support

### ISSUE THREAD

**Issue by wes-carlson** [microsoft/FluidFramework#8246]
related: #7594
While stashed ops have been implemented, there is no blob support. Currently, when `ContainerRuntime.uploadBlob()` is called, the promise returned will not resolve until the blob has been uploaded and a `BlobAttach` op has round-tripped. This ensures that it is not possible to attach a blob handle to the document which refers to a blob that is not present in storage because it was not successfully uploaded, or was GCed before the `BlobAttach` op was sent. However, this means that `uploadBlob()` will never resolve when we are offline.

We need to support "uploading" blobs while offline, getting blob handles, making further changes, stashing these changes, reapplying them in a new container, possibly making further changes while still offline, and finally, upon reconnection, uploading the blobs and resubmitting the stashed ops. In this scenario, we cannot rely on waiting for the `BlobAttach` op to roundtrip, but we must still ensure that we never attach an invalid handle, as it will result in a broken document.

A (partial) solution is implemented in #8159. In this PR, when a blob is uploaded while offline, `uploadBlob()` returns a handle that uses a local ID, which `BlobManager` can redirect to the storage ID once the blob is uploaded (leveraging work already done for detached container blob support). Once we reconnect, when we see a `BlobAttach` op in the resubmit queue in `PendingStateManager`, we block resubmission of any further ops until the blob has been uploaded. It should be safe in this case not to wait for the `BlobAttach` op to round-trip, since we know if it doesn't go through, nothing past it will go through either, and we can make sure upon any subsequent re-resubmission that the blob has not yet been GCed (see #6469). 

This solution is not complete as implemented in the PR since blocking resubmission requires making `PendingStateManager.replayPendingStates()` async. This breaks the assumption in `replayPendingStates()` that all pending ops will be resubmitted atomically without any new ops being submitted. The fundamental problem is that we need to block submission of new ops while allowing submission of resubmitted ops, but it's not easy to distinguish between the two since they both go through `ContainerRuntime.submit()`. If we can distinguish resubmitted ops from newly subitted ops, we can keep them separate in `PendingStateManager`, which should solve the problem.

Another solution, similar to how blobs in detached containers work, would be to upload all of the blobs before emitting "connected" event. This would ensure that all ops can be resubmitted safely.

One downside to the approach above is that it relies on the redirect table in `BlobManager`, which must be persisted in future summaries. There is no mechanism to ever remove entries from this table, so it will grow monotonically. A new entry must be added for every blob passed to `uploadBlob()` while offline, or if we want to treat online and offline blob uploads identically, a new entry must be added for all blob uploads.

**Comment by vladsud** [comment]
First of all, I like the world where images behave as DDSs. I.e. where local changes are synchronous, and the system is doing the right thing to push changes to storage, correctly reflects "dirty" document state, etc. I'd love to see same with images, but with one tiny specific: I believe host would still want to know more about image upload process to show local progress UX to user.

But if we go that route, I'd love to see it to be the only code flow we support. I.e. I do not think it's acceptable for API to be blocking (async) when user is online and not if user is offline. There is no B/W distinction between offline and online. User may lose connectivity while image is being uploaded, and I'd hate us to have to care about that 3rd state (how would we serialize container in such state?)

And if we go that route, I think all op processing (pending state manager) should be uniform in handling all types of changes (ops, pending blob uploads). I.e. ops are never submitted directly to DeltaManager, they always go through pending manager only, and it makes sure that right stuff happens. Only one flow to test and maintain
