### ISSUE TITLE
offline container load/attached container rehydration

### ISSUE THREAD

**Issue by wes-carlson** [microsoft/FluidFramework#8247]
Whiteboard wants to be able to load with stashed ops entirely offline. This is a problem because the current stashed ops design assumes we will be able to connect, load from a snapshot prior to the reference sequence number of the first stashed op, and apply the stashed ops at their reference sequence number as the ops are replayed in order to arrive at the same state as the original container before resubmitting.

One option would be to save the snapshot from which we loaded along with all of the ops after it. For long-lived clients, the amount of ops could grow to be very large, and we would have to do this for any client that might want to stash ops at some point, meaning it would negatively effect performance for all clients at all times, not just when stashing/reloading.

Another option would be to save a snapshot of the document when `Container.serialize()` is called, similar to how serialize/rehydrate works in detached containers. The problem with this approach is that we don't currently have the ability to take a snapshot of a container that doesn't include local changes. In a detached container, including local changes is desired, but once attached it is not, which is why we currently spawn a new container that makes no local changes to take the snapshot. So in order to create a new snapshot to be returned in `serialize()`, we would need to already have spawned a summarizing container. As above, this would need to be done for any client who might potentially want to stash changes and reapply them offline. Additionally, I don't believe it would be possible to take this snapshot at the time `serialize()` is called since the pending ops may have reference sequence numbers earlier than the snapshot, meaning they could not be correctly applied and resubmitted in the new container. So this would still need to work similar to above, taking snapshots periodically and always keeping one older than our oldest pending op, along with all ops that come after it.

Another option would be to simply download new summaries as they are posted in order to reduce the amount of ops we need to store. The downside to this would be the increased bandwidth required to download the summaries. This would also need to be done by all clients that might need to stash changes and then load offline.

**Comment by vladsud** [comment]
Before evaluating possible solutions, it's worth pointing out that there is a feature request ([captured here](https://microsoft.sharepoint.com/:w:/t/Word76/EcdNBOcNR3FFnGM4-aF89FwBPazZzWUiJZqATEE6PzTfAQ?e=gzJoBY)) that has some similarities, in a sense that possible solutions might include
- Making the core of our DDSs to be immutable, such that it's cheap to make clones (rely on copy-on-write). Which is also in line where https://github.com/microsoft/FluidFramework/issues/5738 is pointing too. This kind of direction would allow a lot of advantages overall.
- I think long term (whether it's based on above or not), the right way to solve these problems is 3-way merge. I.e. the solution would look like
   - remember your base (just a reference, similar to how serialize/rehydrate works - it's not a single base, but rather set of instructions to construct that base, some modification likely required here for whole algorithm to work)
   - keep piling local changes. Not track individual ops, just final state.
   - Once online, get base, latest document state (at latest seq#), and latest local state. Do 3-way merge (for starters - using similar merge policy we use today in DDSs, i.e. automatic merging). Result of 3-way merge - a diff on top of latest document state, that we can convert into ops and submit them as normal.

This is not ideal in any form (and future improvements are possible, including around preserving more of user intent / leaving enough data in document for user to chose between conflicting changes in the future in async / non-blocking fashion).
But it would be an order of magnitude improvement over what we have, and would set us up on the right track for f

**Comment by vladsud** [comment]
I'd say that we should evaluate it in context of right long-term solution (which I believe has to involve 3-way merge) and timing requirements. Current flow with using ops is a simpler model that we chose to close particular gap (not lose user data when connectivity is off, assumes relatively short offline duration), but I do not think it will work for completely offline scenarios.

So maybe first - let's put some key requirements from Whiteboard, including ideal timelines, and what's at stake (i.e. is it acceptable if we do not deliver on this direction for next 6 months?)

+@DLehenbauer
