### ISSUE TITLE
redeemSharingLink throws when it shouldn't

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#8250]
We're seeing some cases in telemetry where odsp-driver's `fetchSnapshotWithRedeem` will throw during fallback because it thinks the share link isn't present in the resolved url, even though it makes the same check before doing fallback.  This appears to be because the share link was moved in the resolved url in #7554 - the deprecated property is used to check if fallback should happen (in `isRedeemSharingLinkError`), whereas the new property is checked within the fallback itself.  If one is present, we would expect the other to be present too.  So the suspicion is that as part of that deprecation, code paths were not all updated correctly and we end up in this state.

**Comment by heliocliu** [comment]
@jatgarg are you the best person to look at this?
@pragya91 fyi

**Comment by markfields** [comment]
Another note here - Reminder on the guidance that asserts should be reserved for core invariant validation within the FF. Validating stuff coming over the wire from ODSP should be expressed with a proper error with errorType and fluidErrorCode.

**Comment by jatgarg** [comment]
I think @pragya91 should take this up as maybe she would know this better as she moved the sharingLink with the OdspResolvedUrl in the mentioned PR.

**Comment by pragya91** [comment]
The code in #7554 tries to ensure that the value of `odspResolvedUrl.shareLinkToRedeem` and `odspResolvedUrl.shareLinkInfo.shareLinkToRedeem` remain in sync until the former property is deprecated. So even though there is a mismatch between the property usage within 'isRedeemSharingLinkError' and 'redeemShareLink' methods, the code should still work as expected. I can take a look at the logs to see if there is something else that is triggering the errors. Is there an incident corresponding to this bug?

**Comment by heliocliu** [comment]
IcM 271951213, will tag you in the incident as well

**Comment by agarwal-navin** [comment]
Created an issue to add testing for this scenario - https://github.com/microsoft/FluidFramework/issues/8408
