### ISSUE TITLE
Cleanup usage of createOdspNetworkError/throwOdspNetworkError

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8258]
This API should be used only for actual errors coming from SPO.
The other way to say it - I should be able to add a new property error.spoError = true on these errors and know that indeed these errors are coming from SPO.

Inspecting code, it's pretty clear it's not the case. I'll document some cases, why they are wrong and why following this principle seems like right approach:
1. invalidFileNameStatusCode - this code/symbol should not exist. OdspErrorType.invalidFileNameError could be used directly in place, or better we kill it too and use more generic ContainerErrorType.usageError.
2. fetchTokenErrorCode - similar, NonRetryableError/OdspErrorType.fetchTokenError should be used in place
3. fluidEpochMismatchError - same
4. There are couple places where fetchIncorrectResponse is used 
5. Number of places uses 400 incorrectly, they likely can use fetchIncorrectResponse
   - throwOdspNetworkError("getVersionsReturnedNoResponse", 400);
   - throwOdspNetworkError("getVersionsReturnedNonArrayResponse", 400);
   - etc.
6. Other places uses 400 should be using either custom errors, or maybe ContainerErrorType.usageError?
   - throwOdspNetworkError("methodNotSupportedBecauseNoSnapshotUrlWasProvided", 400);
   - throwOdspNetworkError("methodNotSupportedBecauseNoAttachmentPOSTUrlWasProvided", 400);
   - etc.

I do not know if it's true, but it feels like the smoke test here - places that use this API should always pass response, i.e. response arg should be required, not optional.

Doing this cleanup will help us better track true ODSP errors vs. logic / usage errors.

**Comment by vladsud** [comment]
This is secondary, but I'm not sure fluidErrorCode should be an argument for throwOdspNetworkError.
Basically the idea of having _Data_spoError == true_ check I floated above seems better served by Data_fluidErrorCode == "odspError", i.e. not creating new paradigms. fluidErrorCode represents the call site, and throwOdspNetworkError is that call site. There is some loss of information there, but in my experience I never look at it today for ODSP errors, as the actual event that logs such error (as fluid:telemetry:OdspDriver:ObtainSnapshot_cancel) tells me everything I need to know about code path.

**Comment by markfields** [comment]
Related if touching these functions: #7824
