### ISSUE TITLE
Sequence: Don't fire sequence delta if there are no ranges

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8261]
It is possible for a sequence delta to contain no ranges. a case where this happens in on receiving remote delete for a locally delete range. there is an ask that we just don't even fire the event in these cases. this is in line with the behavior of shared map.

Here is some conversation

> While testing, we noticed that when a client is ingesting a remote deletion for a range that client itself has already deleted, sortedRanges seems to be empty. Can someone confirm that this is a by-design scenario for Fluid SharedString?
>  
> in our OnSequenceDelta callback we pass into Fluid in that we don't check sequenceDeltaEvent.isEmpty before asking forsequenceDeltaEvent.first and crash when we realize the JS object is undefined.
> 
> yes. this is correct. sequence delta provides the delta between the current local state, and the incoming change. in this case, since the range is already removed locally the incoming change is a no-op. 
> 
> i'm open to api improvements here. it seems this case in non-obvious, and needs a very specific test case to catch. any ideas how this could be made better?
> 
> looks like this wasn't represented in the typing. i also added a small comment about this case: SequenceDelta: Fix first and last typing and improve comments by anthony-murphy · Pull Request #8256 · microsoft/FluidFramework (github.com)
> 
>  with SharedMaps, if a similar thing happened where the remote op ingestion is a no-op,  the callback wouldn't be called (or at least that's our impression). do we think it might make sense for SequenceDeltaEvent to not be triggered if the affected range is empty?

**Comment by Yash621** [comment]
@anthony-murphy  can I work on this ?

**Comment by anthony-murphy** [comment]
sure. that would be great. happy to answer questions.

**Comment by Abe27342** [comment]
@anthony-murphy --is the ask specific to Sequence? Or should it apply to matrix / other merge-tree consumers as well?

**Comment by anthony-murphy** [comment]
This was a partner ask, and it seems reasonable. The code isn't factored in a way where we can change this at some fundamental level, so it would need to be done per dds regardless.

That said, i really like the idea of building a set a principle for dds where we articulate things like this and we can work toward bringing dds in compliance.
