### ISSUE TITLE
DataProcessingError issues 

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8262]
1. Looking at DataProcessingError.wrapIfUnrecognized() implementation, I do not understand why we are not using fluidErrorCode and instead coming up with a new concept - dataProcessingCodepath?

        const dpe = new DataProcessingError(errMsg, "" /* fluidErrorCode */);

        error.addTelemetryProperties({
            dataProcessingError: 1,
            dataProcessingCodepath,
        });

2. The following code seems wrong. I feel DataProcessingError's constructor should be protected, and this code likely wants DataCorruptionError instead. It would be also great to have good comments above these classes to clearly articular the expected difference in usage.

            const error = new DataProcessingError(
                "unexpectedAckReceived",
                "unexpectedAckReceived",
                {

3. My main concern though is usage of errorType = ContainerErrorType.dataProcessingError. Given that some data processing error will get it, and some will not (because they already have some other type), presence of this errorType is not something I'd want to rely on. I think dataProcessingError: 1 is the right model here and the right way to find and differentiate these errors.

4. I think we should have some kind of "undefined" or "none" errorType that can be overwritten by any layer (same way as we "overwrite" it if the error does not conform to IFluidErrorBase), but at the same time workflow allows us to convert error to IFluidErrorBase and add properties to it that will be preserved through any future conversions. I have a feeling that some of the other wrap / wrapErrorAndLog / wrapError flows might have similar concern.

### Mark's responses/proposal

1. We are retiring `fluidErrorCode`, see #8929. This `dataProcessingCodepath` will probably not be interesting to primary consumer of these errors, which will be partners who see the container close like this, but might be interesting to us, so stashing in a new prop.
2. Agree on both points - hiding the constructor, and adding comments everywhere
3. See [this comment](https://github.com/microsoft/FluidFramework/issues/8262#issuecomment-1030375584) and surrounding conversation. I agree with how it is now, and will try to clarify in the code / comments why it is this way
4. This is a good point.  Today if someone called `normalizeError` on the way up to a call to `CreateProcessingError`, it would be thwarted and would not classify it properly (it would remain `genericError` rather than `dataProcessingError`.  Opened a separate issue:  #9027

**Comment by markfields** [comment]
@anthony-murphy  -- Please respond to (3):

> Given that some data processing error will get it, and some will not (because they already have some other type), presence of this errorType is not something I'd want to rely on.

This has never made sense to me but it seems like it does to you. I am in favor of ditching this errorType altogether.

**Comment by vladsud** [comment]
I'm not sure if you mean ditching errorType in this particular case or in general :)
In general it allows hosts to show better UX, and potentially react differently to critical errors, so I'm not sure ditching it completely is an option. For this case - it would make sense either not have it (and rely on separate property), or always overwrite it, but somehow preserve the chain of errorTypes for easier analyzes of the problem.

**Comment by anthony-murphy** [comment]
I have a real hard time dealing with these issues in the abstract, as there are not clear right or wrong answers, so i'm happy with whatever shape makes sense for the scenarios we are targeting. 

For instance, do any dataprocessing errors not get the errorType? what error types? what would be the right behavior is those cases.

**Comment by anthony-murphy** [comment]
The current behavior looks right to me:

```
Office_Fluid_FluidRuntime_Error
| where isnotempty(Data_errorType) and Data_dataProcessingError == 1 
| summarize count() by Data_errorType
```
Data_errorType | count_
-- | --
dataProcessingError | 1036
dataCorruptionError | 420

**Comment by vladsud** [comment]
So here is what I see - these 2 queries capture more of the essence of what happens (even though they capture same instance of error multiple times as it gets recorded by multiple events). Not all errors show up as error events, but it does not make a difference in how we should format these errors (as they do show up programmatically, as well as in telemetry).
Plus some were incorrectly not marked as errors in prior builds. Example
- eventName = "fluid:telemetry:Container:ContainerClose"
- errorType = "outOfStorageError"

> union Office_Fluid_FluidRuntime_*
| where Event_Time > ago(10d)
| where Data_dataProcessingError == 1
| summarize count() by Data_errorType, Data_dataProcessingCodepath
```
Data_errorType	Data_dataProcessingCodepath		count_
dataProcessingError					538
dataCorruptionError					293
dataProcessingError	realizeFluidDataStoreContext	161
authorizationError					66
genericNetworkError					35
outOfStorageError					24
serviceReadOnly						16
invalidFileNameError					3
throttlingError						3
dataProcessingError	deltaManagerInboundErrorHandler	3
fileNotFoundOrAccessDeniedError				2
```

> union Office_Fluid_FluidRuntime_*
| where Event_Time > ago(10d)
| where Data_dataProcessingError == 1
| summarize count() by Data_errorType, Data_fluidErrorCode, Data_dataProcessingCodepath

```
Data_errorType		Data_fluidErrorCode	Data_dataProcessingCodepath	count_
dataCorruptionError	duplicateDataStoreCreatedWithExistingId			293
dataProcessingError	realizeFluidDataStoreContext				212
dataProcessingError	deltaManagerInboundErrorHandler				173
dataProcessingError				realizeFluidDataStoreContext	161
dataProcessingError	errorWhileUploadingBlobsWhileAttaching			99
dataProcessingError	channelDeltaConnectionFailedToProcessMessage		54
genericNetworkError	Error 400						27
authorizationError	Error 401						27
outOfStorageError	Error 507						19
authorizationError	Error 403						19
authorizationError	Error 401 (Unauthorized)				18
serviceReadOnly		Error 403 (Forbidden)					9
genericNetworkError	Error 400 (Bad Request)					8
serviceReadOnly		Error 403						7
outOfStorageError	Error 507 (Insufficient Storage)			5
throttlingError		Coherency409						3
dataProcessingError				deltaManagerInboundErrorHandler	3
fileNotFoundOrAccessDeniedError	Error 404					2
authorizationError	Error 403 (Forbidden)					2
invalidFileNameError	invalidFilename						2
invalidFileNameError	Invalid filename. Please try again.			1
```

**Comment by vladsud** [comment]
So here is what I see in the code:
1. wrapError / wrapErrorAndLog - Overwrites errorType. All but DataProcessingError usages are unconditional
2. normalizeError - Preserves error type if any. Otherwise sets it to "genericError"
   - I'd prefer the use of "unknow" type here, not to confuse it with code paths that generate in our code.
3. DataProcessingError.wrapIfUnrecognized - conditionally normalizes errors. 
   - I'd prefer it to always do normalizeError() and not provide any errorType - rely on dataProcessingError = 1 to find these errors.

**Comment by markfields** [comment]
To clear the air real quick... I am NOT suggesting ditch errorType altogether!!  Just re-read this comment and freaked haha:

> I'm not sure if you mean ditching errorType in this particular case or in general :)

**Comment by markfields** [comment]
Important note here - That table is polluted due to a mistake that marked all errors during attach as DPE, fixed here: https://github.com/microsoft/FluidFramework/pull/8136

**Comment by markfields** [comment]
Looking at our data again, now that the instrumentation bug is fixed, it's back to what Tony showed above - only errorTypes `DataCorruptionError` and `DataProcessingError`.  With that in mind, I'm going to do a quick PR to update `CreateProcessingError` function to always wrap, getting rid of the special case when `errorType` is already set.

**Comment by anthony-murphy** [comment]
that sounds wrong to me. we cover pretty broad pieces of code with createProcessingError which could include driver calls, we shouldn't clobber pre-defined error types

**Comment by markfields** [comment]
Ok... I've had a really hard time accepting that approach, but maybe I'm starting to get it.

Thinking about it with the future world where we don't throw well-understood errors but rather return a failure object, it does feel more intuitive.  At that point, we _could_ switch to wrapping anything that's caught in these places, because they would be true exceptional cases arising as part of processing data.  Today we throw our errors, but we can make the same distinction based on the presence of errorType.

**Comment by markfields** [comment]
Question for you @anthony-murphy -- If there were a spike in DPEs in Office Fluid telemetry, would you expect FFX Triage OCE or FF Hot OCE to take the first look?  Based on the last two comments about how it's instrumented, sound like FFX Triage. There's an immediate determination that the errors are originating in the next layer up (probably the data store or container runtime impl), not the core operation of the FF.

And if there were a driver error or something that bubbled up through this path, we may be interested to learn that it impacted a so-called data processing scenario, but we'd want it to keep its original representation, both for programmatic handling at runtime and also for bucketing in telemetry.

cc @SergeyDubinets who I believe owns the Office Fluid processes around these errors.

**Comment by markfields** [comment]
(Side note - asserts in our code do not carry an errorType, because they are exceptional cases, and they would get classified as DPE. This is fine though, that investigation will quickly point back to FF and we can engage at that point)

**Comment by anthony-murphy** [comment]
i would expect FFX Triage OCE to take first look for all issues, including these

**Comment by markfields** [comment]
Of course of course. Wrong question.  Considering parent epic #8260, I'm basically getting back around to what @vladsud already put in that initial comment, point (3):  We would exclude DataProcessingErrors from our "inner-most" triage query (unless it's an assert), because the initial assessment is that these arise from not-our-code.

Although, in more controlled environment like Stress Test, I kind of assume we should see none of these...  And taking a quick look, I only see asserts with this errorType, so this is starting to make sense.
