### ISSUE TITLE
Epic: SharedTree DDS

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#8273]
# SharedTree DDS Roadmap

This epic is deprecated, and has been relocated to [roadmap.md](https://github.com/microsoft/FluidFramework/blob/main/packages/dds/tree/docs/roadmap.md).

**Comment by ungrokkable** [comment]
Hi @DLehenbauer,
I'm trying to get a better grasp on the serde side of M1.  In your feature, do you plan to allow serializing the whole tree or just the changeset itself?  Thanks.

**Comment by DLehenbauer** [comment]
@ungrokkable - We've been working backwards toward API, starting with op and storage formats, so the discussion on the the M1 API is just spinning up.  I just summarized the direction we're currently exploring in #8989 for the underlying API, with opportunity to ship an example/experimental higher level convenience API on top what #8989 describes in the same timeframe.

**Comment by ungrokkable** [comment]
Hi @DLehenbauer, I'm officially requesting a PropertyDDS-like interface for TreeDDS.  I realize that #8989 is more for discussing the internal API.  Do we have something equivalent for the higher level API?  We obviously are flexible and won't require a perfect PropertyDDS interface, but we do want to ensure some of the functionality like binders are there.  Thanks, and if I can help with anything, let me know.

**Comment by DLehenbauer** [comment]
For M7/M8, [this comment](https://github.com/microsoft/FluidFramework/issues/8989#issuecomment-1035197914) nicely describes what integration with external systems and indexed queries look like at scale.

**Comment by DLehenbauer** [comment]
@taylorsw04 - Notes on pending key decisions.

- Data Model
  - Subset of JS, C++, or something else (e.g., Intentional Unified Data Model)
  - Which parts of schema are enforced on read vs. write
- High-level API: General flavor and how early to start? (See @ungrokkable's [request](https://github.com/microsoft/FluidFramework/issues/8273#issuecomment-1034351901) above)
- Responsibility of low-level engine vs. high-level API
  - Who reifies what and when
  - Who caches what and when
- Rebase
  - Sandwich vs. Scaffolding
  - Are we maximizing IDs when available?

**Comment by taylorsw04** [comment]
My WIP aggregation of the open decisions we have. I plan to build a topology at some point to help focus our efforts, and this is absolutely not complete. I'll keep folding in new information here.

Urgent (either impending or have implications for impending work):
- Tree abstraction
  - Is the consumer-facing API different from the underlying representation?
    - Regardless, what is desired for the public API (JS/bespoke/etc.)?
  - Do we expose an immutable or mutable API initially?
  - Where is schema? On-read vs. on-write could impact representation.
  - Data model:
    - All scalars are leaf nodes?
    - Can scalars lack identity?
    - Can traits contain a mix of unboxed scalars and nodes?
    - Always reifying arrays vs. not always doing so?
    - Allow specialized collections (maps/sets)?
- At leaves only?
- Would they have identities?
    - Can identities be present but not usable for lookup?
- Reifying
  - Responsibility of low-level engine vs. high-level API
    - Who reifies what and when
    - Who caches what and when
- Rebasing
  - Do we want to rebase on the server?
  - Should rebasing be temporal onto spatial or spatial onto spatial?
    - If you can only rebase via temporal, how do we rebase the anchors that are inputs to the command? Phantom node approach?
  - Can we better leverage identity here?
  - OT vs. MT/CRDT (aka scaffolding)?
    - If OT, exclusion or inversion?
- How would this allow delta-only rebasing?
    - If MT, how does it work?
- How would this allow delta-only rebasing?
- Can we leverage identities in the scaffolding?
- Squashing
  - How much can we squash intra-commit states?
  - How much can we squash inter-commit states?
- How do we want to allow custom/app-specific merge behavior?
  - Rebase handler/conflict handler?
  - Definitely want re-running of commands
    - How can we make this more efficient?
- Constraints
  - What types do we want?
- "Engine"-side in-memory format
  - Immutable vs. mutable
 
Lower-pri:
- Optional sub-transactions
  - Do we want them?
- Partial checkout
  - How do moves work?
  - How do constraints work?
- Range semantics
  - "Atomic range": do we want it/when do we want it?

**Comment by yann-achard-MS** [comment]
@ruiterr - here is a table summarizing the differences between PropertyDDS and SharedTree when it comes to PropertyDDS constraints. Please let me if I got something wrong or forgot something on the PropertyDDS side.

| Operation | Implicit PropertyDDS Constraint | SharedTree Behavior When Constraint Not Met |
| --- | --- | --- |
| `insert` child at object field | field is empty | inserts before or after the existing content | 
| `remove` child at object field | field is not empty | silent no-op |
| `modify` element at object field | field is not empty | conflicts (drops the modify) |
| `insert` element at array index | none | n/a | 
| `remove` element at array index | elem is present | silent no-op |
| `modify` element at array index | index is not empty | conflicts (drops the modify) |

A couple comments on the above:
* In all cases, once SharedTree supports explicit constraints, we'll be able replicate the implicit PropertyDDS constraints exactly. In that sense, the third column only represents the default behavior of shared tree.
* For the "insert child at object field" case, one approach we can use is to craft edits such that the field is guaranteed to be empty by always removing its contents prior to the insert.
* When it comes to constraints, maps behave like objects in both systems.
* When it comes to constraints, strings behave like arrays in both systems.

**Comment by ruiterr** [comment]
@yann-achard-MS I think you correctly described the current behaviour of PropertyDDS. At the moment, the conflicting cases are all silently handled. There should actually never be "constraint violations", but in the rebase with respect to the previous operation the CS is rewritten in such a way that it can be applied in a non conflicting way (a duplicate insert is dropped for fields, modification and remove are dropped if there is a parallel remove of the same element). Those cases are regarded as conflicts, but since we currently don't report conclicts to the app, they are just silently resolved.

>For the "insert child at object field" case, one approach we can use is to craft edits such that the field is guaranteed to be empty by always removing its contents prior to the insert.

Would this require a slice remove (from beginning to end)? I think it won't be possible via a set remove. Let's assume we have the following situation:

Initial value: *A*
Modification by client 1: `[remove(A, setlike), insert(B, after A)]`.
Modification by client 2: `[remove(A, setlike), insert(C, after A)]`.

Let's assumed client 1 is sequenced first. After its change is applied, we have
Value: *B*

If we now rebase the change of client 2, with respect to the change of client 1, the remove(A) will be dropped, because it is a duplicated remove of the same element, the insert will be preserved, so the result of applying this would be
Value: *A*, *B*
