### ISSUE TITLE
Replace setValue with set() in PropertyDDS - find alternative

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8278]
Remove the deprecated `setValue` function from the `ReferenceMapProperty` class (`\experimental\PropertyDDS\packages\property-properties\src\properties\referenceMapProperty.js`). The current implementation of this function simply calls the `set` function, and can therefore be removed once all uses of `setValue` have been replaced with `set`.

**Comment by ssimic2** [comment]
This looks like a fairly contained change. However, I'm curious about consistency here:

1. I see other DDS properties that have both `setValue` and `set` that are interchangeable (ex. `ReferenceProperty`). If we are deprecating around ReferenceMapProperty  we should probably consider these other DDS-es as well.
2. What's the reasoning behind naming convention (set vs setValue)? I'm assuming we wanted all map-like DDSes to end up with `set` to align with JS naming convention?
cc. @ChumpChief

**Comment by scottn12** [comment]
Closing this issue. This API is already being addressed via https://github.com/microsoft/FluidFramework/issues/8273.
