### ISSUE TITLE
Delete getLegacyInterval method since it only exists to support the deprecated IntervalCollection.delete(start, end)

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8279]
Remove `IntervalCollection.getlegacyInterval()` which is only supported by the deprecated `IntervalCollection.delete(start, end)`. The alternative to `IntervalCollection.delete()` is `IntervalCollection.removeIntervalById()`.

The following files are affected:

1. packages/dds/sequence/src/intervalCollection.ts
2. packages/test/test-end-to-end-tests/src/test/deRehydrateContainerTests.spec.ts (removing the else part)

**Comment by ChumpChief** [comment]
Makes sense to me - @anthony-murphy fyi

**Comment by anthony-murphy** [comment]
@pleath who i think made that change
