### ISSUE TITLE
Remove Shared from ValueType enum

### ISSUE THREAD

**Issue by sonalivdeshpande** [microsoft/FluidFramework#8282]

**Comment by ssimic2** [comment]
@ChumpChief it looks like you have marked this deprecated. I'm assuming the idea here is that even `SharedObject` will be of `ValueType.Plain` type, just having its handle stored as value of `ISerializableValue`. Please correct me if I'm wrong.

What are the guidelines on persisted data compatibility? If we receive `ISerializableValue` as a result of an older snapshot load, removing the support for `ValueType.Shared` may be an issue. We still have live logic that migrates old shared value to handles.
