### ISSUE TITLE
Delete path from remoteObjectHandle.ts

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8290]
Remove `path()` from `RemoteObjectHandle` since it returns the absolute path. 

The files affected are: 
1. packages\runtime\runtime-utils\src\remoteObjectHandle.ts

**Comment by agarwal-navin** [comment]
Sounds reasonable. Can you validate that this is not used anywhere and if it is, update it.

**Comment by sdeshpande3** [comment]
> Sounds reasonable. Can you validate that this is not used anywhere and if it is, update it.

 I have checked Bohemia's codebase and it seems they are not using path

**Comment by agarwal-navin** [comment]
I am curious if there a reason or a use case that you are removing this for?
