### ISSUE TITLE
Refactor/Deprecate createDataStoreWithProps

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8291]
Context: #1537, #3631

The `_createDataStoreWithProps` function defined in interface `IContainerRuntimeBase` and its implementation class `ContainerRuntime` were deprecated in 0.16 and should be removed.

The following files are affected:
1. `\packages\runtime\runtime-definitions\src\dataStoreContext.ts`
2. `\packages\runtime\container-runtime\src\dataStoreContext.ts`

There are no remaining uses inside of FluidFramework, but there are uses found within partner repos, so those must be removed first before they are removed from FluidFramework.

**Comment by ssimic2** [comment]
Duplicate of https://github.com/microsoft/FluidFramework/issues/3631.
