### ISSUE TITLE
`assert` dependency removed from newer version of FF, causing issues in webpack

### ISSUE THREAD

**Issue by Zlatkovsky** [microsoft/FluidFramework#8298]
## Describe the bug

When switching from the previous LTS version (0.39) to current (0.45) or later, I started getting the following error:

```
ERR! BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
ERR! This is no longer the case. Verify if you need this module and configure a polyfill for it.
ERR! 
ERR! If you want to include a polyfill, you need to:
ERR! 	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
ERR! 	- install 'assert'
ERR! If you don't want to include a polyfill, you can use an empty module like this:
ERR! 	resolve.fallback: { "assert": false }
ERR!  @ ../../common/temp/node_modules/.pnpm/@fluidframework/server-memory-orderer@0.1033.0/node_modules/@fluidframework/server-memory-orderer/dist/nodeManager.js 13:21-44
ERR!  @ ../../common/temp/node_modules/.pnpm/@fluidframework/server-memory-orderer@0.1033.0/node_modules/@fluidframework/server-memory-orderer/dist/index.js 24:13-37
ERR!  @ ../../common/temp/node_modules/.pnpm/@fluidframework/server-local-server@0.1033.0/node_modules/@fluidframework/server-local-server/lib/localDeltaConnectionServer.js 6:0-63 36:27-33
ERR!  @ ../../common/temp/node_modules/.pnpm/@fluidframework/server-local-server@0.1033.0/node_modules/@fluidframework/server-local-server/lib/index.js 5:0-45 5:0-45
ERR!  @ ./lib/testUtilities/creationHelpers.js 2:0-81 6:39-72
ERR!  @ ./lib/demoApp/CaptureSnapshot.js 2:0-67 24:31-46
ERR!  @ ./lib/demoApp/index.js 3:0-52 6:43-58 47:130-145 48:10-25
ERR! 
ERR! ERROR in ../../common/temp/node_modules/.pnpm/@fluidframework/server-test-utils@0.1033.0/node_modules/@fluidframework/server-test-utils/dist/testContext.js 8:17-34
ERR! Module not found: Error: Can't resolve 'assert' in '/mnt/vss/_work/1/s/common/temp/node_modules/.pnpm/@fluidframework/server-test-utils@0.1033.0/node_modules/@fluidframework/server-test-utils/dist'
ERR! 
ERR! BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
ERR! This is no longer the case. Verify if you need this module and configure a polyfill for it.
ERR! 
ERR! If you want to include a polyfill, you need to:
ERR! 	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
ERR! 	- install 'assert'
ERR! If you don't want to include a polyfill, you can use an empty module like this:
ERR! 	resolve.fallback: { "assert": false }
ERR!  @ ../../common/temp/node_modules/.pnpm/@fluidframework/server-test-utils@0.1033.0/node_modules/@fluidframework/server-test-utils/dist/index.js 22:13-37
ERR!  @ ../../common/temp/node_modules/.pnpm/@fluidframework/local-driver@0.50.1/node_modules/@fluidframework/local-driver/dist/localDocumentService.js 29:28-72
ERR!  @ ../../common/temp/node_modules/.pnpm/@fluidframework/local-driver@0.50.1/node_modules/@fluidframework/local-driver/dist/index.js 19:13-46
ERR!  @ ./lib/testUtilities/creationHelpers.js 1:0-90 15:25-38 16:36-63
ERR!  @ ./lib/demoApp/CaptureSnapshot.js 2:0-67 24:31-46
ERR!  @ ./lib/demoApp/index.js 3:0-52 6:43-58 47:130-145 48:10-25
```

As a stopgap measure, I was able to bypass the problem by declaring "assert" to be an explicit dependency. But something about that feels incorrect -- if it's the framework's dependency (as it used to be in 0.39), it should remain in the framework's `package.json`-s...

**Comment by JasonGore** [comment]
`assert` is fundamentally a Node utility and am wondering what the rationale is using it in the published package output consumed by web apps running in a browser environment. What is the intended behavior here? What kind of required `assert` functionality is being imposed onto web app consumers? Is there a reason exceptions or some other error handling strategy isn't used instead?

**Comment by tylerbutler** [comment]
> `assert` is fundamentally a Node utility and am wondering what the rationale is using it in the published package output consumed by web apps running in a browser environment. What is the intended behavior here? What kind of required `assert` functionality is being imposed onto web app consumers? Is there a reason exceptions or some other error handling strategy isn't used instead?

I haven't done an exhaustive search but where I spot-checked, we're using it in test code but not the source. But I doubt we're hygienic. :) Related to #8725.

**Comment by tylerbutler** [comment]
The packages that it's complaining about are server packages, though, which should be fine to depend on node stuff. @Zlatkovsky Do you know why Webpack was packing server libraries?

**Comment by Zlatkovsky** [comment]
@tylerbutler , no, I'm not sure why it was happening. If someone on your end is able to take a look, I'm happy to help set them up with a repro...

**Comment by Zlatkovsky** [comment]
@tylerbutler , looks like we just ran into a similar thing with the "url" package dependency as well. E.g., https://github.com/microsoft/FluidFramework/blob/main/packages/loader/container-loader/src/utils.ts has an `import { parse } from "url"`, but does not declare a "url" dependency in its [package.json](https://github.com/microsoft/FluidFramework/blob/main/packages/loader/container-loader/package.json)

**Comment by tylerbutler** [comment]
@Zlatkovsky I think the real ask is to not rely on node libraries. #8725 tracks that. #8760 should address the url module, but assert was already moved to an isomorphic implementation in #6623. So I am not sure why assert is causing you issues. The package.json is correct in those cases -- we don't depend on the assert module, but rather our own implmentation Can you trace the dependency chain in Webpack to figure out why it is trying to pack server packages?

It could also be related to test code, but even in that case, I don't understand why Webpack would be packing test code.

**Comment by DanWahlin** [comment]
I'm hitting a similar issue when trying to upgrade a project to 0.57.2. I also updated react-scripts from 4.0.3 to 5.0.0 which I suspect is causing the webpack issue. Project can be found here:

https://github.com/microsoft/brainstorm-fluidframework-m365-azure

Here are some of the errors I'm seeing:

```
Compiled with problems:X

ERROR in ./node_modules/@fluidframework/container-loader/lib/utils.js 5:0-28

Module not found: Error: Can't resolve 'url' in '/Users/danwahlin/Dropbox/Projects/GitHub/Microsoft/brainstorm-fluidframework-m365-azure/node_modules/@fluidframework/container-loader/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
	- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "url": false }


ERROR in ./node_modules/@fluidframework/driver-utils/lib/insecureUrlResolver.js 5:0-28

Module not found: Error: Can't resolve 'url' in '/Users/danwahlin/Dropbox/Projects/GitHub/Microsoft/brainstorm-fluidframework-m365-azure/node_modules/@fluidframework/driver-utils/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
	- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "url": false }
```

**Comment by tylerbutler** [comment]
@DanWahlin I think your issue is the same as #8725.
