### ISSUE TITLE
Prod: fluid:telemetry:OdspDriver:createNewFile_cancel: Need better back off & progress reporting / cancelation.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8309]
There are a lot of fluid:telemetry:OdspDriver:createNewFile_cancel errors in telemetry.
Looking closer, I see that most of them are concentrated in 10 sessions, with top one probably have 30% of all events (2109 hits in that session alone!)

I believe it works as it was designed (i.e. we keep retrying if user is offline), but
- should it do so in such tight loop? It looks like there is no delay / back off, just straight retry
- should it do so long? I know we went back and forth on it, and allowed (before) to fail and do retry by host.
   - probably better question to ask - can we start propagating IProgress through API and use this flow as a first guinea pig  for flashing out cancelation / progress reporting API?

> union Office_Fluid_FluidRuntime_*
| where Data_containerId == "2316b2db-5472-454b-bc4e-a1138393a477"
| project Event_Sequence, Event_Time, Data_eventName, Data_errorType, Data_error, Data_reason
| order by Event_Time asc

**Comment by jatgarg** [comment]
Moving to Feb as other high priority work turned up.

**Comment by vladsud** [comment]
Let's (for now) address back-off logic first.
Progress reporting / cancelation is important, but let's track it as part of #5192
@jatgarg - if you looked more into cancelation, can you please update above issue with your findings / references?
