### ISSUE TITLE
(Phase 3) Update IContainer interface to have desired developer surface without @Alpha tags

### ISSUE THREAD

**Issue by sumedhb1995** [microsoft/FluidFramework#8319]
**Current State**

IContainer is currently the recommended way of interacting with a container. It is the type of return provided by both Loader and ILoader, and their calls resolve, createDetachedContainer, and rehydrateDetachedContainerFromSnapshot
Based off of the vetted IContainer usage in FFX, all of the used public APIs on Container were made available on IContainer to allow for fewer breaking changes while we modify the interface. These were all labeled with an "@alpha" tag to identify them as candidates for future changes so our partners do not grow too attached to them. These new alpha interfaces fell into the following three categories:
- Connection State Management - For toggling if the container will automatically attempt to reconnect to the service
-- setAutoReconnect()
- Op Processing Management - This is used if the container being requested does not yet have a div for it to be rendered in. FFX uses this in loadComponentFromContainer.ts to manually start fetching ops prior to the container being used to render a view. This is often used in conjunction with deltaManager to control the op flow.
-- resume()
- Read-only State Management - This allows the app to force the container to be in readonly state for the current client.
--forceReadonly()
-Audience Inspection - This is an important piece to understand both the current active members of the container as well as to understand which client is the one representing the current user. It is used both directly (i.e. CoauthExample.tsx) and indirectly (AtMentionsCollection.ts). Furthermore, this is also exposed on the 3P developer surface through the FluidContainer, so it makes sense to also expose it in IContainer as the eventual goal is to merge these two interfaces. However, we should consider refactoring this in conjunction with the audience API to better serve our customers. Client ID for example changes on reconnection and might not be the ideal identifier for the user that a client app is looking for.
-- clientId

IContainer and its alpha APIs are currently exposed to both our 1P and our 3P partners. For 1P, FFX returns an IContainer object both in OWH-loaded components and Chapter 5 Loop Components. For 3P, IContainer is still available as a layer to interact with, but documentation on fluidframework.com and the recommended 3P developer path there is to use FluidContainer, which builds upon IContainer. In both scenarios, we need to consider N/N-1 compatibility breaking changes whenever making additions to the IContainer interface.

The following interfaces need to be updated:

- [ ] #8708
- [ ] #8709
- [ ] #8710

**Comment by skylerjokiel** [comment]
Moved to ADO
