### ISSUE TITLE
Remove containerId from JWT token generation

### ISSUE THREAD

**Issue by sumedhb1995** [microsoft/FluidFramework#8326]
Currently, FRS no longer requires any client-side container ID generation.

We need to scrub this from our current token generation APIs on the developer surface.
Changes for this will include:

- [ ] Making containerID optional from the code snippet for Azure Functions
- [ ] Making containerID optional from the parameters required by the `generateToken` function
- [x] Have InsecureTokenProvider use the `generateToken` function instead of its own `getSignedToken` function. They do practically the same thing so we shouldn't have code duplication

**Comment by skylerjokiel** [comment]
@sumedhb1995 , containerId should be an optional property on generateToken not removed. containerId is not required for creation flow but is required for loading flows.
