### ISSUE TITLE
Feature: Mechanism to identify compatible versions of components for a given runtime

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#835]
The framework lacks a mechanism to identify compatibility between a runtime version used by the hosting container and components. In other words, there's no way for the water park or any container to filter the list of components it knows about based to only load versions that are compatible with the runtime that it uses.

There's a clear application of this in the water park, because people get confused when components don't load in the water park, but I think the feature is more broadly useful, so I'm filing this issue so we don't forget about it.

**Comment by vladsud** [comment]
That's 1.5 year old task. I believe we currently do not support dynamic component loading. Whenever we get there, we will need to re-access. Closing
