### ISSUE TITLE
Control Summarizer Client

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8359]
It is currently not possible to control which clients can create summarizer clients, and which clients can summarize. 

These PRs attempt to do some level of control for different reasons: 
 - #7625
 - #8221

The ideal design here would support a server agnostic way to control which client can summarize and identifying the summarizer client. I say server agnostic, as i don't think the fluid server itself should decide which clients can or should summarize, it should just enforce the decision which is made elsewhere. The primary benefit being that the fluid server doesn't need to be scenario aware to enforce the scenarios desired behavior.

Some example scenarios:

- All clients are eligible to summarize (today)
- Server Nacks for non-summarizer clients
- Affirmative identification of summarizer client, rather than by special user defined client name 
- Some subset of clients are eligible to summarize
- Only a special server client should summarize. related #8251 

One option to do something like this would be to do it via [scopeType](https://github.com/microsoft/FluidFramework/blob/c85fb0023061e633138aed25d25314836ac945ec/common/lib/protocol-definitions/src/scopes.ts) . This would then put the onus on the token creator to provide the correct scope or scopes for the scenario. However, the final approach will require further design work, and may use a different mechanism.

**Comment by anthony-murphy** [comment]
FYI @vladsud @tanviraumi @GaryWilber @pleath @pradeepvairamani

**Comment by vladsud** [comment]
I'm not sure I fully understand what is wrong and what is proposal to fix it :)
Maybe worth starting with some sample scenario and how it can't be accomplish today or implementation of such scenario would be unnatural?

That said, I agree that clientType == "summarizer" can probably formalized better (into some boolean through the stack)
