### ISSUE TITLE
Rename various ways we refer to ordering service to "Fluid Relay"

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8372]
I'd love to see a world where we use one short name to point to these two things (if possible):
- Ordering service (abstract)
- A particular implementation of it
I.e. something like "relay service" and "Azure relay service"

Currently through documentation and code we use
 - ordering service
 - relay service (Azure)
 - PUSH (ODSP)
 - delta stream (in context of "connect to delta stream") and delta connection (though there is a case to be made that this layer abstracts presence of specific service, from practical POV (all discussions with partners involved across stack) these specifics are impossible to hide, including programmatic API we expose like "connected" / "disconnected" events through layers where we talk about some "service"
 - Alfred (IAlfredUser, provider.get("worker:alfredUrl"), http://alfred:3000", etc.)
 - “socket”
 - (probably other names)
Some service may choose to use already established name Internally in their world (PUSH for ODSP), but I think we should avoid such name references in FF code (let's say in driver code) as much as possible.
 
It feels like we are moving to usage of “relay service” and “replay” (where such shortcut is appropriate). If so, we should do appropriate renames in code base.

Matt:
> I think those two make sense, but I think it would be good to continue distinguishing an instance of a delta stream/connection from the service providing it (i.e. DocumentDeltaConnection -> RelayServiceStream or similar – not just RelayService).

Tanvir:
> I think for the open-sourced part, “Fluid Relay” makes sense. And then “Azure Fluid Relay” and “ODSP Fluid Relay” will make it more precise.

**Comment by vladsud** [comment]
@danielroney, assigned to you initially not to lose it and figure out if it's 1.0 blocking/really good to have, and where to land it (i.e. Skyler's team or not).

**Comment by danielroney** [comment]
@ChumpChief , @skylerjokiel  - triage for 1.0
