### ISSUE TITLE
Use IConnected message timestamp when running GC in absence of ops

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#8375]
Follow up of https://github.com/microsoft/FluidFramework/issues/7152.

When running GC, if no message has been processed yet, use the timestamp in the IConnected message while running GC. This will be used to figure out if an unreferenced node has expired and should be deleted.

**Comment by agarwal-navin** [comment]
We can add this timestamp to `IClientDetails` inside the `IClient` object (Currently, it is added to `IClient` which can be moved to `IClientDetails`). This way we don't have to expose new APIs to the container runtime which already has access to `IClientDetails`.

However, the `IClient` in container is not updated when the connection is established with the server. So, we do not have access to the timestamp added by the server. With that in mind, there are 2 ways we can fix this issue:
1. Get the timestamp from `IConnected` message instead in `DocumentDeltaConnection` and expose it to the `ConnectionManager`. The connection manager can add the timestamp to the client details.
2. When a connection is established, get the updated `IClient` from the quorum and update the `IClient` and `IClientDetails` from it. The problem here is that `Container` is the one with access to the quorum whereas client details is owned by `ConnectionManager`. So, the client / client details have to be plumbed from container to connection manager via delta manager.

@vladsud @anthony-murphy thoughts?

**Comment by vladsud** [comment]
I'm a bit lost here, as I do not see connection between multiple paragraphs. So maybe my responses are not on point, but here is what comes to mind:

IClientDetails is what client provides, relay server does not modify (I believe). So, adding server-generated timestamp to it would be weird.

We can make Container update Container.client on connection, but I believe it's not exposed anywhere, so I'm not sure how it helps with anything. This is ugliness of using same type for _in_ & _out_ communication. This IClient is only used for _out_ communication, i.e. sent to relay service. It has nothing to do (at least today) to IClient that is constructed for joining client - it is available only in quorum / Adience, as far as I know. I'd personally keep it that way - it forces us not to add more APIs to expose (and duplicate) info but pushes us to make quorum / audience better.

It's not that hard to find "self" in Audience (I'd assume that you do not want to use quorum as client can be not changing file for a long time, but it does not matter - same is true with quorum). So, if it's there, and timestamp is on IClient, then runtime can easily find it, no?

I think the only hard part here (with Audience) is indeterministic update cycle - there is no guarantee that "self" is there on "connected" event. We can (and should) improve it though.

**Comment by agarwal-navin** [comment]
I think I mixed two different thread there and hence the confusion. Let me try to focus on the issue at hand first - How does container runtime get the timestamp of when the client connected?
This information is present in the `IConnected` message and in the `IClient` that is sent by the server on connection and is present in the audience and quorum.
You are right that the runtime can get this information directly from the audience. Also, we should not use quorum because the client may be in "read" mode.

For this particular issue, we don't really care about the info being there on "connected". We need this information when running GC and it should be there by then.

**Comment by agarwal-navin** [comment]
The other concern I have is about Container.client. I understand that this is the client state that was requested by the creator (host). But what's confusing is the fact that the info in Container.client may not be in line with the actual session. For example, the session may be in "write" mode whereas the mode in Container.client says "read".
At the very least, we should rename it to indicate that this is the requested client info and not the current / actual client info.

**Comment by vladsud** [comment]
I think we should kill Container.client, if possible. It should be enough to pass this info once to DM and forget about it.

I'd focus on exposing easy to use API for getting info from audience. I think much better world is the one where "connected" fires only after "self" is in audience. Please open an issue, feel free to poke as well as assign to me - I'm poking in this area (not directly, but some of the PRs I'll raise likely will make it slightly easier to add this functionality).

**Comment by agarwal-navin** [comment]
I had opened an issue a while back for this with details from a conversation we had - https://github.com/microsoft/FluidFramework/issues/7275. I assigned it to you.
