### ISSUE TITLE
Latest prod regression: assert(isRuntimeMessage(message), 0x122 /* "Message to unpack is not proper runtime message" */);

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8396]
I've hit this assert on a new doc. Looking at Kusto, there are not that many hits, but I worry when I see hits from just released 0.50 & 0.51 builds:

union Office_Fluid_FluidRuntime_Error
| where Data_error contains "0x122"
| summarize count() by Data_eventName, Data_docId, Data_loaderVersion

The doc I hit it with is this:
https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!70_cNOFlWEyzRzEcCorMTZAND7s98E5GvCj7qsbvKwKg49qsUtgNRYr38F2hc1Tg&item=01CGOBCIFXGRNNC4I7TVALTGYILMXTBAOZ&file=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fkening_microsoft_com&siteUrl=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fkening_microsoft_com

Not sure if it's shared with everybody or just me, but if it's not shared widely, we can share it.
Also note that Ke reported that he can still open it with old version of local code, so it feels like there is some bug in latest release(s)?

Can you please take a look?

**Comment by vladsud** [comment]
I also downloaded this file, so have op stream, can share if needed

**Comment by ke-at-microsoft** [comment]
If anyone needs me to share this file, please ping me. I will leave this file alone and won't touch it.

Right now I can NOT open this file on office.com, and I can NOT open it from fluidpreview.office.ne.  But I can open it from dev.fluidpreview.office.net.

**Comment by agarwal-navin** [comment]
I believe this change introduced it - https://github.com/microsoft/FluidFramework/pull/7811

A new ContainerMessageType type "Rejoin" was added. Older versions of runtime don't have this type so when they get this message which was generated by a newer runtime, they assert.

@wes-carlson Can you fix this. We should also add validation around this. This should have been caught by our tests.

**Comment by agarwal-navin** [comment]
Can you also enable full compat for these tests - https://github.com/microsoft/FluidFramework/blob/b086e1187d2af923d22882ba4b274822ddf67fc0/packages/test/test-end-to-end-tests/src/test/stashedOps.spec.ts

**Comment by wes-carlson** [comment]
Shouldn't this prevent that from happening:
https://github.com/microsoft/FluidFramework/blob/8e451ad7cbb58029a5a1ea32c918e1acccdc3175/packages/runtime/container-runtime/src/containerRuntime.ts#L1438

**Comment by vladsud** [comment]
If this is confirmed to be latest regression, I'd love to ask you to focus on quick mitigation first - I really do not want to see more documents being corrupted (even if it's temporarily before new code is deployed) - user experience sucks. Worth starting a thread on LiveSite channel? I assume that made it to prod, right?

**Comment by agarwal-navin** [comment]
> Shouldn't this prevent that from happening:
> 
> https://github.com/microsoft/FluidFramework/blob/8e451ad7cbb58029a5a1ea32c918e1acccdc3175/packages/runtime/container-runtime/src/containerRuntime.ts#L1438

That check is done before unpacking the message to ContainerMessageType. So, there the type is MessageType.Operation.

**Comment by agarwal-navin** [comment]
Looks like it went in 0.51. We should release a patch with fix for 0.51 and 0.52.

**Comment by agarwal-navin** [comment]
Create an issue to add validation for this - https://github.com/microsoft/FluidFramework/issues/8409
