### ISSUE TITLE
Add sprequestguid to errors during fetch calls to odsp

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#8410]
When a fetch call to odsp fails, log the sprequestguid in the error so that it can be correlated with ODSP logs.

**Comment by agarwal-navin** [comment]
I see that the sprequestguid is logged and is part of the error when fetch call fails. I think its not getting propagated to the app / host.

**Comment by agarwal-navin** [comment]
@markfields I assigned this to you since you have been looking into telemetry. Can you please take a look?

**Comment by agarwal-navin** [comment]
@leeviana FYI

**Comment by markfields** [comment]
@agarwal-navin - you immediately unassigned me, was that a mistake? Feel free to actually assign me :)

> I think its not getting propagated to the app / host.

Are you suggesting that the error objects we expose to hosts include this as a first-class property on the type?

cc @jatgarg as FYI.

**Comment by agarwal-navin** [comment]
I think I wanted to unassign myself after assigning you. Technology!

> Are you suggesting that the error objects we expose to hosts include this as a first-class property on the type?
Yes, that sounds about right. @leeviana can confirm.

**Comment by leeviana** [comment]
Yes, a first class property (or second class generic property bucket property of some sort) would be nice. The core issue is that by checking app/host logs we get driver/API errors that seem to have spguids known to the Fluid Framework system, but not known to the error that surfaces in app/host logs. So it's possible to find the spguids if you know to search the framework logs as a second step after seeing a driver error in the first step, but that second step is not obvious (and not obvious why it would be required since it seems like it's supposed to travel with the error)

**Comment by markfields** [comment]
@leeviana - I have a suspicion that if you check for the function `getTelemetryProperties` on an error and call it if present, you'll get this when it's there.

I've had it in my mind to visit the error logging code in Bohemia to do something like this.  Feel free to open an ADO item and assign it to me (or try it yourself of course!).

If that would do it, then let's close this.

**Comment by leeviana** [comment]
Hmm, I think we actually explicitly don't log whole bags of properties on errors (with helper code originally copied from the framework) to prevent PII leakage. Is getTelemetryProperties specific to the framework? Is there maybe some generic bucket of properties we can use to check for a specific field and log it explicitly.

We have something functionally equivalent to this to protect against overlogging data.
`function prepareErrorObject(event: TelemetryEvent, error: unknown) {
  if (isErrorObject(error)) {
    // WARNING: Exceptions can contain PII!
    // For example, XHR will throw object derived from Error that contains config information
    // for failed request, including all the headers, and thus - user tokens!
    // Extract only call stack and message
    event.stack = error.stack;
    const errorMessage = error.message || JSON.stringify(error);
    if (errorMessage) {
      if (event.message) {
        event.message = `${event.message}\n${errorMessage}`;
      } else {
        event.message = errorMessage;
      }
    }
  } else {
    // TODO: We should revisit how we handle error objects that make it into this block to avoid this typecast to any
    event.message = error as any;
  }

  // Collect stack if we were not able to extract it from error
  if (event.stack === undefined) {
    event.stack = getStack();
  }

  // Redact any domain information
  if (event.message) {
    event.message = redactDomain(event.message.toString());
  }
  if (event.stack) {
    event.stack = redactDomain(event.stack.toString());
  }
  if (event.error) {
    event.error = redactDomain(event.error.toString());
  }
}`

**Comment by markfields** [comment]
I'm taking care of updating the above `prepareErrorObject` function in Office Web Host to leverage `getTelemetryProperties`, see https://dev.azure.com/office/OC/_workitems/edit/5758898

**Comment by markfields** [comment]
Closing this.  `sprequestguid` is included on our driver error objects.  We log it in our logging events.  Partners can include it in their logs via `getTelemetryProperties()` if they so choose.

As for the ask from internal Loop team -- in the end, Loop folks decided they didn't want to do that at this time, so this value will not appear in other logs besides in the FluidRuntime tables.
