### ISSUE TITLE
server can launch before client with `npm start` for FluidHelloWorld

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#8413]
## Describe the bug
when running `npm start` in the FluidHelloWorld scenario it kicks off both the server and the client. This can result in the client being launched before the server.

Result: The client is always launched before the server.

### Expected behavior
Client should wait for server before launching the browser

**Comment by tylerbutler** [comment]
An option might be to use pm2 to manage the tinylicious lifecycle. See #4442 for a similar change.
