### ISSUE TITLE
DeltaConnectionFailureToConnect 

### ISSUE THREAD

**Issue by mickaelo** [microsoft/FluidFramework#8416]
## Describe the bug
This bug happens when I tried to connect to a tinylicious session in production but it's really not regular.
![image](https://user-images.githubusercontent.com/6357104/143207043-9ad1e89b-badc-4df9-b11b-3c3c9fb7e482.png)

### To Reproduce
To reproduce, just connect to a session after building up one.

### Expected behavior
Connection to websocket must be done and no error message

**Comment by markfields** [comment]
@mickaelo - Sorry you're hitting this error!  Can you provide some more detail about your setup when hitting this error?  I'm not sure how to interpret "connect to a tinylicious session in production" - Tinylicious only runs locally on your dev box.  Are you connecting to Azure Fluid Relay when hitting this?  Any patterns in terms of when it succeeds or fails?

Also, when you hit this error, it will attempt the connection again a few seconds later.  If you wait, does it ever successfully connect, or just continue in a loop?  (Look for JoinSession_end event over and over again a few seconds apart in the logs)
