### ISSUE TITLE
Add new snapshot test with new metadata format

### ISSUE THREAD

**Issue by chensixx** [microsoft/FluidFramework#8417]
## Work Item

#7527 is adding new things to metadata, so we can add snapshots with the new format to snapshot tests.

**Comment by markfields** [comment]
@agarwal-navin, @pleath - Does this roll up into an existing Epic?

**Comment by agarwal-navin** [comment]
I am not sure. Did the parent (https://github.com/microsoft/FluidFramework/pull/7527) have an Epic? If so, we can add it to the same one.
