### ISSUE TITLE
Remove deprecated `register` function from `DataBinder` class.

### ISSUE THREAD

**Issue by scottn12** [microsoft/FluidFramework#8450]
Remove the `register` function which has been deprecated from the `DataBinder` class in the following file: `experimental\PropertyDDS\packages\property-binder\src\data_binder\dataBinder.ts`.

To replace its functionality, use `DataBinder.defineDataBinding` and `DataBinder.activateDataBinding`.

**Comment by ssimic2** [comment]
@DLehenbauer looking at further code examples, it seems that define/activate is very common 2 step process. What is the reasoning behind deprecating `register` here ? Maybe I am missing something, but if it a common 2-step process, returning single handle to destroy both definition and activation handle, seems appropriate. 

`unregister` definition could be removed, if no current clients further depend on it. But just for my clarity I'd love to understand what is the scope of "current clients" reference here. I'm assuming it's extending to 3P integrations.

**Comment by ssimic2** [comment]
After chatting with @DLehenbauer, this will be tackled as a separate effort that needs more considerations.
