### ISSUE TITLE
Refactor out quorum / join + leave logic out of Container class

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8463]
This will allow custom logic to be plugged in, for hosts like Word be able to control system messages on their own (i.e. not necessarily sequence join & leave ops, but rather have alternative ways of communicating this information).
See Epic #7993 for more details.

**Comment by vladsud** [comment]
It should likely be closed in favor of the item I've just opened in ADO.

**Comment by andre4i** [comment]
Duplicate of [261](https://dev.azure.com/fluidframework/internal/_workitems/edit/261/)
