### ISSUE TITLE
Remove IFluidSerializer from IFluidDataStoreRuntime and container runtime.

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#8467]
`IFluidSerializer` is used by DDSs to serialize and parse handles. These are not needed in layer above. 

There are couple of usages of `IFluidDataStoreRuntime::IFluidSerializer` which can be updated to use shared object's serializer:
1. https://github.com/microsoft/FluidFramework/blob/7446fd3722663402bc4d341bfed94409b8f26f9b/experimental/dds/ot/ot/src/ot.ts#L103
2. https://github.com/microsoft/FluidFramework/blob/7446fd3722663402bc4d341bfed94409b8f26f9b/experimental/PropertyDDS/packages/property-dds/src/propertyTree.ts#L465

**Comment by agarwal-navin** [comment]
@DLehenbauer Any idea why the above DDSs use the serializer on data store runtime and not shared object?

**Comment by DLehenbauer** [comment]
Nope - and I doubt it's a deliberate.  I would switch them w/o hesitation.

**Comment by agarwal-navin** [comment]
Deprecated `IFluidSerializer` in `IFluidDataStoreRuntime`. To be removed when runtime version >= 0.55.

**Comment by agarwal-navin** [comment]
Closed via https://github.com/microsoft/FluidFramework/pull/8635
