### ISSUE TITLE
Review usage of GenericError / UsageError / DeltaStreamConnectionForbiddenError errors in our repo

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8473]
GenericError() and UsageError(), DeltaStreamConnectionForbiddenError() should take a message argument that developers can understand, not reuse fluidErrorCode as a message.
It's possible that some of these call sites should not be generic errors, but rather usage errors.

Also, it would be great for order of message & fluidErrorCode args to be always the same - now it's 50% one way and 50% other way.

There are probably more cases like that. It's easy to find them by seeing who extends LoggingError, as it currently mixes usage of message and fluidErrorCode. That is tracked as separate item - #8474

**Comment by markfields** [comment]
Tracking for Feb via https://github.com/microsoft/FluidFramework/issues/8929
