### ISSUE TITLE
LoggingError usage in our repo needs to be improved / have human readable error messages.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8474]
All the places where we do new LoggingError():
1. fluidErrorCode is used as message. This is wrong - errors should have language that developers of our system can understand, not cryptic code for interna consumption.
2. All the places where we through it should have errorInstanceId ideally.
3. Eventually: remove isValidLegacyError and its usage in repo

Note that #8473 tracks all the cases that extend LoggingError.

**Comment by markfields** [comment]
I don't agree with (1).  camelCase is totally human readable.  In cases where we are writing the message ourselves, let's just have one canonical string there, to reduce cognitive load in terms of how we refer to that error case.

I think the real question is whether we'd ever replace fluidErrorCode with autogenerated hex codes.  I'm not sure I'm on board with that, partly for this reason (being able to reuse as message).

**Comment by markfields** [comment]
I believe (2) is the case as of PR #8383.  I agree with (3).

**Comment by vladsud** [comment]
I think we need to clearly spell out the meaning of all the fields and usage.

Originally, fluidErrorCode was added as a way to identify the callsite where error is thrown and had no other intention (to the best of my knowledge).
If we want to change it to be the main "messenger" of error type/message, then I'd argue we need to change approach - there is no reason to have two fields with exactly same content in our API surface and in telemetry (this is more applicable to all derived classes of LoggingError, i.e. #8473)

That said, I'd love to see our messages to be readable by humans in one form or another. They are part of our API (for example, Container's "close" event, usage errors thrown by Sequence, developers building data stores / DDSs are on both receiving and throwing sides of this discussion). I see two possible directions here:
1. Error.message that we generate is plain English, allowing developers clearly understand what happens and how to go about the problem. That's what developers expect when they get Error object.
   - To some extent it's a shortcut (over # 2), i.e., we assume messages to be self-documentated. But it's well-established path. I.e., fetch() will throw "TypeError: Failed to fetch". V8 will throw "Uncaught TypeError: Cannot read property 'foo' of undefined". And so on. They do not use codes to point to unique conditions - they use English (and occasionally document when/why error is thrown and how to go about it).
2. We do not use Error object (thus do not have to have `message` field) and just have fluidErrorCode on our type. There is a fork here:
   - Some messages might be fine to say - they do not contain any extra data other than errorType and that's the only thing that developers have to interact (programmatically or in diagnostics). This very likely requires a lot of unique errorTypes to differentiate similar (but different) problems that require different approach from developer POV. Eventually one would want grouping for easer programmatic handling - similar to what we have with errorType / message above.
   -  All (unique) fluidErrorCode values are well documented, such that users can understand when and how they run into problems and what to do about them (grouping: errorType / fluidErrorCode). We will run into problem of dual intent - there will be places where we will want to use same fluidErrorCode in multiple places as that's same error type, but different value to indicate different call site.

Yes, bundle size is a problem. So, we should be careful about it. But it's not the only data point we have to consult. End-user facing apps use localize strings for their errors (in UX). While we are a library, it's worth pointing out libraries / core subsystems will provide (sometimes - localized) error strings, even if they do use error codes (like FormatMessage() and GetLastError() in win32).

As for camelCase is totally human readable - this IMHO minor (as above-mentioned issues are more important), but I disagree. What "realizeFluidDataStoreContext" actually means if I hosting app does loader.resolve() and get that error? How does developer get enough context to reason about it? Developer will use errorType to design UX, but he/she will need more info to alleviate / diagnose problem. It's especially confusing when we put such values into Error.message - I'm not aware of libraries that do that, most use plain English with Error object.

I'd look for optimizing fluidErrorCode to be a tag. But I have hard time seeing solving error usability problem without using plain English or extensively documenting each fluidErrorCode.

It's useful to see what we do today. Some examples of how we are totally inconsistent today in this space (spent 2 min looking for examples, i.e., there are more):

Using human readable strings as fluidErrorCode (in many cases - formatting them with error codes):
- rejectDeferredRealize(): "packages is undefined", "No registry for package", etc.
- `summaryNack: ${message}`, 
- `containerNotValidForAttach [${this._lifecycleState}]`

And using tokens, quite often not human readable (or rather - unlikely random developer having any clue what to do with them):
- "bufferParsingException"
- ODSP tokens ("sessionForbiddenOnPreservedFiles", "sessionForbiddenOnModerationEnabledLibrary", "sessionForbiddenOnRequireCheckout")
- "messageClientIdMissingFromQuorum"
- "messageClientIdShouldHaveLeft"

**Comment by vladsud** [comment]
@anthony-murphy & @ChumpChief for their thoughts.
(Matt - not sure if it's clear, but it's part of programmability, i.e. these errors are expose to FF users / aka developers).

**Comment by markfields** [comment]
Vlad and I had a nice chat about this and related topics.  I will be writing up a light proposal to articulate the key "developer cans" about how our errors are consumed, which can then lead to some clear iterations in terms of implementation.

As for this particular topic, I am currently thinking that fluidErrorCode will go away, if we can instead agree on some ground rules for error messages we write, and have a canonical way to distinguish our errors from external errors (including when we wrap them).

**Comment by markfields** [comment]
Tracking for Feb via https://github.com/microsoft/FluidFramework/issues/8929
