### ISSUE TITLE
LoggingError.getTelemetryProperties() should not dropped tagged properties

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8477]
Look for "REDACTED (arbitrary object)" text.
The way code is constructed today - it does not allow tagged properties to ever be logged.

Error objects should provide properties as is
Various logger adapters TelemetryLogger should do the same - blindly organize them into ITelemetryBaseEvent
And only host implemented logger should care with tags (we can help by providing helper adapters that strip tagged properties).

Also, ITelemetryBaseLogger.supportsTags is not used anywhere in our repo, and thus I assume it should be removed.

**Comment by markfields** [comment]
> The way code is constructed today - it does not allow tagged properties to ever be logged.

I don't think so... but will look in case there's a bug. `REDACTED (arbitrary object)` would be for non-tag objects that are slapped on errors.

> Also, ITelemetryBaseLogger.supportsTags is not used anywhere in our repo, and thus I assume it should be removed.

Yeah we should be able to remove it completely at this point

**Comment by markfields** [comment]
@vladsud I'm closing as no repro.  There are some possible follow-ups I identify below, feel free to open issues if any are worth tracking to you.

I am able to find tagged fields such as `packageName` and `dataStoreId` in our logs, and the only instance I've come across of `REDACTED` message is `facetCodes` which is expected (although should be dealt with one way or another at low priority).

Here's the code in `errorLogging.ts` that allows tagged props through but blocks other objects:

```typescript
                if (isTaggedTelemetryPropertyValue(val)) {
                    props[key] = val;
                } else {
                    // We don't support logging arbitrary objects
                    props[key] = "REDACTED (arbitrary object)";
                }
```

I'll note that it would be more useful in the REDACTED case if it added the key to a single prop like `redactedKeys` or something, so we could easily monitor what's in there.  It's nearly impossible to search for these keys in aggregate.
