### ISSUE TITLE
Deprecate IDirectory.absolutePath

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8482]
Objects should never operate with paths, they can and should expose handles if they need to.
Note that handles also do not expose paths (IFluidHandle.absolutePath is deprecated).
All the links without container should be done through storing handles, not paths.

Any chance one of you can follow up here soonish?
Thanks!

**Comment by ChumpChief** [comment]
I think there is some misunderstanding - this is not the same as a handle's absolute path and is not related to paths in a container, this is the path within the directory structure.  So e.g. if I have a `SharedDirectory` with subdirectory `foo`, and under that `bar`, then `IDirectory` for `bar` would have `absolutePath` of `/foo/bar`.

**Comment by vladsud** [comment]
Ah, makes sense, sorry. Any chance it can be named differently? :) If not, fine to punt.

**Comment by ChumpChief** [comment]
Can always consider other names, but I think the concept of an absolute path to a subdirectory is pretty broadly understood so I'd prefer to stick with known concepts.
