### ISSUE TITLE
fetchHelper(): throw OdspErrorType.fetchAborted instead of OdspErrorType.fetchTimeout for aborted fetch calls

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8488]
[Discussion](https://github.com/microsoft/FluidFramework/pull/8464#discussion_r764362770)
Consider throwing new OdspErrorType.fetchAborted instead of existing OdspErrorType.fetchTimeout for cases where fetch was aborted due to provided abort signal.
Need inspect code where we use OdspErrorType.fetchTimeout today to make it safe.

Condition in fetchHelper():

if (error.name === "AbortError") {

**Comment by vladsud** [comment]
This item should take into account back-compat
Given that driver ships dynamically from loader, this means we should
1. Add error definition and requirement for hosts to start handling it (same as old error).
2. Change loader if loader depends on these errors
2. Let some number of versions pass
3. Change driver.

Could you please break it into appropriate issues / PRs? Thanks!

**Comment by markfields** [comment]
Looking back at history and discussing with Vlad, neither of us feel this is particularly high priority.

If we hear from a host (or have a more concrete notion ourselves) that they would really need to know the distinction between a request that timed out v. one that was cancelled by the client, in terms of programmatically reacting to these errors, then we can bump up the priority accordingly.

**Comment by markfields** [comment]
Btw, the link to the original discussion does not really work for me, so here's a screenshot:

![image](https://user-images.githubusercontent.com/12305068/153091277-eee11914-559e-41ee-991f-02f11ab20e02.png)
