### ISSUE TITLE
Introduce DriverErrorType.usageError

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8489]
PR https://github.com/microsoft/FluidFramework/pull/8464 adds DriverErrorType.genericError usage in couple places.
We need to deprecate it, and instead introduce new DriverErrorType.usageError.
This will take multiple PRs and waiting / breaking.md changes for hosts to start handling it.

Alternative is to have some "core" enum somewhere, as every layer will have usageError kind of thing (ContainerRuntime does already)

**Comment by markfields** [comment]
I've been pondering about updating errorType to be namespaced.  If we're going to be working with hosts on breaking changes around errorType, can we take some time to think about forward-compat with this kind of change?  E.g. switching from equality check to contains check.

**Comment by vladsud** [comment]
@markfields, any chance you can built a plan here? I've reassigned it to Si to work on in January. Thanks!

**Comment by markfields** [comment]
Gladly!

Btw, `DriverErrorType.genericError` is deprecated in `0.44`, but we never updated client to depend on that version.

**Comment by markfields** [comment]
Let's give it the value `"driverUsageError"`

**Comment by scottn12** [comment]
@markfields @chensixx is there currently any work in progress to introduce this `DriverErrorType.usageError` enum? If not, I'm happy to make the changes necessary

**Comment by markfields** [comment]
@scottn12 - Thanks for the offer, assigning to you, as we are focused on other items so far this sprint and you should be able to easily unblock yourself.

**Comment by anthony-murphy** [comment]
this seems really odd to me. why is usageError better than generic error. usageError seem likely to be semantically incorrect in most cased

**Comment by markfields** [comment]
@anthony-murphy - usageError is for parameter validation or other checks to ensure invariants/preconditions are met by a caller.  I don't see why it's surprising that driver APIs would want to raise this kind of error.  Can you articulate what your concern is a bit more?

I responded to your comment in the PR asking for examples of where to use it. Looking through the code there are additional places I see that should use this as well.
