### ISSUE TITLE
Formalize fatalConnectError prop in DeltaManager close internal API

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#8502]
> I'd say I'd prefer for close() method to take an extra argument that describes internal DM reason for closure, and just require all callers to pass it, and close() to format it into the error objects in one single place.
We might want to break close() into closeInternal() and public dispose() to ensure that required arg is only needed for internal usage.

_Originally posted by @vladsud in https://github.com/microsoft/FluidFramework/pull/8500#discussion_r765067890_

**Comment by vladsud** [comment]
Note - I already broke close() into internal and external APIs in ConnectionManager.

**Comment by markfields** [comment]
Moving to Jan to complete along with #8623

**Comment by markfields** [comment]
Moving to Feb, after design on #8623 is done this month
