### ISSUE TITLE
"Sequence" term has unintended meaning

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#8506]
From the Twitter thread here: <https://twitter.com/danlyke/status/1463320821603061761>

"Sequence" as a term in computer science usually indicates that there is a regularity to the items in the list. A reader might reasonably assume that our use of sequence also implies this, but that's not true. Our sequences have an order, but they are not regular.

We have avoided the term "array" because SharedSequence cannot fulfill the complete array API (most notably pop and shift), but the "sequence" term also has unintended meaning.

So, we should consider an alternative term -- **list**. I think that sufficiently communicates the ordered-ness of the data while not implying that they're arrays.

We should also consider renaming the DDSes.

## Plan

We're going to add a section to the Sequence docs like, "sequences vs. arrays" to call out the differences. We'll also do the same for Python lists, since those are another example of a data structure that is similar to SharedSequence but has key differences.

We'll also monitor to see if this is a repeated point of confusion. If it is, then we'll re-evaluate this plan.

**Comment by tylerbutler** [comment]
@ChumpChief @skylerjokiel FYI. I added this to the 1.0 list project.

**Comment by anthony-murphy** [comment]
we should just call it shared string and deprecates the other sequences. they are not useful #8526

**Comment by tylerbutler** [comment]
We've removed the data structures in question (for reasons beyond this issue; see #8526), so closing.
