### ISSUE TITLE
Remove `containerPath` from `driver-defnitions`.

### ISSUE THREAD

**Issue by scottn12** [microsoft/FluidFramework#8510]
Context: #4169

**Comment by anthony-murphy** [comment]
#8511 should be done before this. we should remove all usages before we change the undying type. changing the type and then consuming the pre-release is the last step

**Comment by scottn12** [comment]
My understanding was that if we try to make the change in #8511 first, then the compiler will complain about the missing `containerPath` property that is expected in the `DriverPreCheckInfo` interface. So, my thinking was that we should remove the property from the interface in `driver-definitions` first so the compiler will accept the property being removed

**Comment by anthony-murphy** [comment]
ahh. for some reason i though it was optional. so i think you are right about staging if you go straight to removal. you may want to consider a softer removal path, either make it optional first, or just make it optional on the return type of checkurl, before you actually remove the property.

however, the important part of this feedback is really that you should have a clear understanding of all usages and how to migrate those usage before anything is changed, and if possible, always remove or limit usages first

**Comment by scottn12** [comment]
Closing this issue to consolidate work items into https://github.com/microsoft/FluidFramework/issues/8548
