### ISSUE TITLE
Remove GetSharingInformation call in getFileLink

### ISSUE THREAD

**Issue by marco-ms** [microsoft/FluidFramework#8513]
## Update
Per discussion (see comments below) this call should be removed and replaced, and we should not expose more info through this call.

## Feature
GetSharingInformation is called each time a file is opened and provides useful information on the tenant's default sharing permissions.
Exposing this information would help greatly to make more informed decision on which sharing api to call on the host side.

**Existing work**
https://github.com/microsoft/FluidFramework/blob/main/packages/drivers/odsp-driver/src/getFileLink.ts#L81

**Describe alternatives you've considered**
Alternatively, the host can call the same Api, but that would be duplicating the same network call.

**Comment by vladsud** [comment]
getFileLinkCore -> getFileLink -> getShareLinkPromise
   OdspDriverUrlResolverForShareLink.resolve()
   OdspDriverUrlResolverForShareLink.getAbsoluteUrl()

So OdspDriverUrlResolverForShareLink pre-flights the call and caches promise for future getAbsoluteUrl() resolve faster (using this cache).

Today we cache only string (file link), which is
```ts
                const sharingInfo = await response.content.json();
                const directUrl = sharingInfo?.d?.directUrl;
```

There is no type information available.

I see only this documentation - https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-csomspt/e8604c72-262b-490f-933f-ece357258d63
I assume the returned structure should be described here, but I see no details:
https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-csomspt/6b0a906d-703e-4d5b-b199-b3b24dd87761

@marco-ms, to make it actionable, we will need
1. some pointer that describes interface/structure returned in this call.
2. What you need out of that structure (or whole structure)
3. Confirmation where / how to expose it. At the moment, I assume it would be a method (with appropriate name based on above) on OdspDriverUrlResolverForShareLink, is that correct?

**Comment by marco-ms** [comment]
@vladsud 
1. I don't know, can you work it out with the the proper team?
2. The whole structure would be best, but if not possible these are the most useful fields:
defaultLinkKind
defaultShareLinkPermission
defaultShareLinkScope
defaultShareLinkToExistingAccess
3. Same as 1.

**Comment by marco-ms** [comment]
Another useful field seems to be sharingAbilities > peopleSharingLinkAbilities > canAddNewExternalPrincipals > enabled
Which would tell us if we can add or not guest users right away.

**Comment by vladsud** [comment]
Where can I find documentation? I need clear definition of interface, not just some fields.

**Comment by marco-ms** [comment]
I asked Brian and will get back at this by Monday.

**Comment by vladsud** [comment]
Per Sean Livingston, we have to remove this API call as it's not public and should not be in our code base.
Suggestion is to send email to "ask VROOM" DL and figure out other way to get directUrl (what Fluid needs) and not to expose anything else.

**Comment by vladsud** [comment]
Also Sean says that that directUrl is not stable as it can break over time (with site collection rename?), maybe there are other ways to achieve what we need. We should follow up.
