### ISSUE TITLE
Strongly typing a SharedMap

### ISSUE THREAD

**Issue by kevindiclemente** [microsoft/FluidFramework#8520]
## Feature
**Is your feature request related to a problem? Please describe.**
It's not currently clear how to add strong typing to SharedMap. Such as `key: string -> SharedCell<number>`

**Describe the solution you'd like**

Declare a `SharedMap` using generics, like with `SharedCell`; where `SharedCell<string>` we could have `SharedMap<string, string>`

**Existing work**

Not aware of it

**Describe alternatives you've considered**

Having weak typing, which is error prone, or adding a wrapper class around SharedMap.

**Additional context**

**Comment by tylerbutler** [comment]
@ChumpChief @skylerjokiel I think we've investigated this in the past, but I don't know where we landed. Thoughts?

**Comment by ChumpChief** [comment]
This is same as #363 / #1239 / #136 -- currently resolved as won't fix but could be considered.

**Comment by kevindiclemente** [comment]
If you want to hear from a customer about why typing is important, please let me know. Same reason we use typescript instead of Javascript.

**Comment by tylerbutler** [comment]
@kevindiclemente Are you always storing the same type of object in the map? Today SharedMaps can store values of heterogeneous types, so I'm wondering if you're using that capability, or foresee needing it.

**Comment by AndrewCraswell** [comment]
Even if the consumer plans to store multiple types, the SharedMap could still be typed in such a way as to clearly determine which types are expected. TypeScript doesn't have to force a single type.

The lack of proper types has been one of the first difficult aspects of onboarding to Fluid Framework that i envountered. It's not consistent with what I would expect from a client-side library in this regard. I ended up writing my own wrapper classes around the DDS types to add better type handling.
