### ISSUE TITLE
container-definitions Breaking change needs to be accounted for in 0.53 release

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#8532]
See this [build failure ](https://dev.azure.com/fluidframework/public/_build/results?buildId=46272&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=3e8a0811-333e-5612-55d7-750fabab9520&l=457) we're encountering as part of the current release ([this PR](https://github.com/microsoft/FluidFramework/pull/8531)).

> this is what's causing the problem. between prelease 0.43.0-45414 and release 0.43.0 some change came in that is just now being consumed.

_Originally posted by @anthony-murphy in https://github.com/microsoft/FluidFramework/pull/8531/files#r766162346_

**Comment by markfields** [comment]
@scottn12 - Can you please help here to unblock the release?  From looking at the build error (linked above), I believe [this breaking change](https://github.com/microsoft/FluidFramework/commit/78936bed80c950883eb2a5fdeadeab6b267a73a3#diff-1be7320b361ad41f777c2b128a138aca706e437e5d7e6439360c6d22a235a9da) of yours was never pulled in by the rest of the repo.  But since @sumedhb1995 did do the prerelease bump to tell the repo to depend on container-definitions 0.43.0-0, now as part of the release we've published _all_ changes to container-definitions to 0.43.0, and are trying to consume them, and this breaking change needs to be dealt with.

I think it will just be a matter of appeasing the type validator tests to clarify that this breaks some back/forward compatibility.

**Comment by markfields** [comment]
Next time, you can catch this earlier by following [these instructions](https://github.com/microsoft/FluidFramework/wiki/Compatibility-and-Versioning#testing-boundary-cross-changes-locally) for testing changes that impact across boundaries using the `symlink:full` script.

Bonus is to publish a prerelease version with your changes and update the lockfile to make the dependent layers proactively pull in your changes rather than waiting for the release (like you see [in Sumedh's PR](https://github.com/microsoft/FluidFramework/wiki/Compatibility-and-Versioning#testing-boundary-cross-changes-locally) that bumped client to the prerelease dependency)

**Comment by scottn12** [comment]
@markfields , I think you accidentally linked the instructions twice instead of Sumedh's PR

**Comment by markfields** [comment]
Btw, there may be other build breaks from the other changes between Sumedh's and Tim's commits here.  https://github.com/microsoft/FluidFramework/commits/main/common/lib/container-definitions.  We'll see what surfaces once we resolve the runtime-definitions one.
