### ISSUE TITLE
Add policy for snapshot cache expiry and client session expiry

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#8549]
https://github.com/microsoft/FluidFramework/issues/7925 adds expiry to the snapshot cache. https://github.com/microsoft/FluidFramework/issues/7206 adds expiry to client sessions. We should add policy to control the behavior of these.
Ideally, there should be only policy (mostly in the driver) that controls the time after which snapshot cache should be expired and the session expiry time should be derived off of that.
For the snapshot cache policy, we may want to keep a default time (2 days currently) which is also the max and it can only be configured to a value smaller than that.

**Comment by tyler-cai-microsoft** [comment]
Relevant PR thread https://github.com/microsoft/FluidFramework/pull/8198#discussion_r754655027

**Comment by tyler-cai-microsoft** [comment]
After some offline discussion, we determined we do not want to link the snapshot expiry policy with the session expiry. We may change this in the future. The reasons for this are:
- The snapshot expiry can change during the lifetime of a document, whereas the session expiry should not change.
- If the snapshot expiry affects the session expiry, it would cause a side effect hosts may not be able to easily predict.
