### ISSUE TITLE
A container will always reconnect and retry, even for non-retriable errors

### ISSUE THREAD

**Issue by andre4i** [microsoft/FluidFramework#8570]
[Original discussion](https://github.com/microsoft/FluidFramework/pull/7987#discussion_r765939797)

## Describe the bug

**Any** error coming from the driver will cause the container to reconnect and retry pending ops. This risks the container going into an endless loop of reconnects even for errors which should never be retried. 

For example, if the server rejects a payload for exceeding the payload size limitation (this is the particular error type which surfaced the issue in the aforementioned PR), the container will reconnect and will attempt to resend the large ops forever.

The issue seems to be rooted in the `createReconnectError` method will always ignore the `canRetry` property from the supplied error.
https://github.com/microsoft/FluidFramework/blob/f2ea99fe007f4f4e6da9543be203366a1765bc37/packages/loader/container-loader/src/connectionManager.ts#L81

The fix seems trivial at first sight; however, it risks breaking existing assumptions about how errors are handled at that layer. I believe the fix should be deeper and rethink our reconnection strategies.

### To Reproduce

- from the `DocumentDeltaConnection`, emit an error as:
```
this.emit("error", new NonRetryableError("Catastrophic", undefined, DriverErrorType.writeError));
```
- the container will still retry.

### Expected behavior
An error without the `canRetry` property set to `true` should not cause a reconnect and a retry.

cc @markfields

**Comment by markfields** [comment]
Looking through history to see why this may have been set this way, it's been here for years.

**Comment by markfields** [comment]
@vladsud - Looking back at [this PR](https://github.com/microsoft/FluidFramework/pull/2111), you replaced this function:

```typescript
function getErrorReconnectInfo(reason: string, error: any): IErrorReconnectInfo {
    return {
        reason,
        canReconnect: canRetryOnError(error),
        reconnectDelay: getRetryDelayFromError(error),
        getError: () => createIError(error),
    };
```

with this one:

```typescript
function createReconnectError(prefix: string, err: any) {
    const error = createIError(err, true);
    const error2 = Object.create(error);
    error2.message = `${prefix}: ${error.message}`;
    return error2;
}
```

Was it intentional to always pass `true` as `canRetryArg` to `createIError`?  Or should it have been using `canRetryOnError` this whole time?

**Comment by markfields** [comment]
I think this may be the reason that in Office Fluid, a few % of sessions never connect, but never report an error.

**Comment by markfields** [comment]
The observation is that errors that go through this code path never end up logged in telemetry, and when I stepped through an e2e test exercising the reconnect path, it was obvious why - we say it's retryable, and trigger a connect, dropping the error on the floor!

**Comment by vladsud** [comment]
I'm pretty sure that we handle errors correctly, i.e. non-retryable errors will close container.
I believe the issue here is that this specific reason can be retryable or not and there is not enough data which one is which.
If so, should it be closed, and we continue to track 1Mb socket.io limit in appropriate bug?

**Comment by markfields** [comment]
> I'm pretty sure that we handle errors correctly, i.e. non-retryable errors will close container.

@vladsud - See my detailed PR description (#8964).  I do agree that there's no user bad from this at the moment, because all cases that go through this codepath are under `documentDeltaConnection.initialize` which will reject and `connectCore` will fail.

But this should still be fixed.  It is not just about the specific 1MB limit.

**Comment by markfields** [comment]
Ok... I think I am seeing something here I didn't understand before.  I found this comment in one of the tests that's failing:

```
// All errors on socket are not critical!
```

And indeed this is what is accomplished by always setting `canRetry: true`.

In other words, the design of the code is that it's _incorrect_ for an error/disconnect on a live socket connection to close the container.  Rather, it should try to connect again, under the assumption that if there really is a critical failure, the new connection will fail hard and close the container.

@vladsud - Am I on the right track here?  If so, I will rework this PR to maintain this behavior but be more clear.

**Comment by vladsud** [comment]
Yes, I believe that's correct. I do not remember specifics. I think it has to do with a fact that token expiry results in 401/403 (which is non-recoverable error), so we simply leave error handling to be done on one path - connection path.
