### ISSUE TITLE
Store and Retrieve Connected Timestamp

### ISSUE THREAD

**Issue by tyler-cai-microsoft** [microsoft/FluidFramework#8584]
After #7275 is resolved. We should follow up and fix how we retrieve the "connected" timestamp. We should store the "connected" timestamp as soon as we are "connected". We would then retrieve this value in the `getCurrentTimestamp` function in the `ContainerRuntime`. 

[#8580 (comment)](https://github.com/microsoft/FluidFramework/pull/8580#discussion_r771016832)

**Comment by agarwal-navin** [comment]
The `getCurrentTimestamp` method to pass to GC only uses the timestamp from ops and not from the "connected" timestamp. So, this is not required anymore.
