### ISSUE TITLE
Block access to DDS outside of handles

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8588]
in preparation for eventual garbage collection of DDS we should consider blocking access to them outside of handles, such that all used DDS already have an existing handle. The sooner we do this the better.

> > We currently don't have GC at DDS level - there is no requirement of storing a DDSs handle in another DDS. So, we cannot detect when DDSs are referenced between summaries. We could add this capability, but it will make the code complex and won't add much value because we don't collect DDSs. This will be added when we do GC at DDS level.
> 
> How can we ensure we do not forget about it? I.e. is there a test we can construct that would fail if we started to collect DDSs but did not do this work?

I added a test where a new DDS is created between summaries but its reference is not added. Today the test passes but when we do have GC at DDS level, the test should start failing. Also mentioned the issue about GC at DDS level to the test comments.

_Originally posted by @agarwal-navin in https://github.com/microsoft/FluidFramework/issues/8542#issuecomment-997048744_

**Comment by agarwal-navin** [comment]
Does this constitute making DDS live to storing its handle in another referenced DDS. Basically, removing `bindToContext` API from ISharedObject? Or is this tracking more work than that?

**Comment by anthony-murphy** [comment]
I have not idea. just saw your PR and comment, and thought if the only way to get a DDS was via a stored handle somewhere, then we could pretty safely assume we could garbage collect any DDS that doesn't have a handle to it somehere

**Comment by agarwal-navin** [comment]
Ah okay. This is a good starting point but there is more work to be done before we can collect DDSs. Like, we allow creation of DDS with names and don't distinguish them from non-named DDSs. We will have to introduce the concept to root and non-root DDS similar to data stores so that within a data store GC can building the reference graph starting from root DDSs.

I will add this to the GC epic.

**Comment by anthony-murphy** [comment]
for sure. but the sooner we can enforce handles the better. i think it would have also improved the data store GC story if we could have required handles sooner

**Comment by agarwal-navin** [comment]
Agreed. I will plan to do this as soon as the sweep work is done. Scheduled this for February for now.

**Comment by agarwal-navin** [comment]
Tracked by AB#400
