### ISSUE TITLE
policy-check should verify dependencies are not duplicated

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#8598]
There have been a few cases where someone adds something to  `dependencies` that was already present in `devDepenendencies`.  This isn't a huge problem by itself, but the version management/release tooling assuming entries are only present once, and in cases where this is a fluidframework package, it will bump the version of the entry in `dependencies` and not `devDependencies`, then later in the process will complain that the versions are mismatched.  policy-check should warn about this, and when run with `fix` should remove the duplicate entry from `devDependencies`

**Comment by tylerbutler** [comment]
This is addressed by the [no-repeated-dependencies](https://npmpackagejsonlint.org/docs/rules/dependencies/no-repeated-dependencies) rule of npm-package-json-lint, which is run as part of policy-check.

https://github.com/microsoft/FluidFramework/blob/e8e22ab7a6b9a03c8d5d8c0de54ffc21d7d90c87/tools/build-tools/src/repoPolicyCheck/handlers/npmPackages.ts#L524-L536
