### ISSUE TITLE
MergeTree: Need ability to create LocalReferences to end of sequence

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#86]
Many MergeTree operations refer to the position at the end of the sequence.  For example, consider appending to the end of a sequence:
```
"0123"
     ^-- Append = insert @4
```
In order to use LocalReferences to track caret positions, selection ranges, etc. we need the ability to create LocalReference to the position after the last segment in the MergeTree (@4 above).

Today, the LocalReference can only references positions 0..3 in the above example.  This limitation has impacted all user of LocalReferences that I'm aware of:

* FlowView does not use LocalReferences.  Instead, it observes ops to update the caret/selection offsets manually.
* SharedStringInterval users can only include the last position in a sequence if they treat 'end' as inclusive instead of exclusive (#1761).  This has been source of numerous off-by-one errors in Table-Slice / Tablero.  (I found another one yesterday.)
* WebFlow used to attempt to preserve an extra marker at the end of the document.  If this is accidentally deleted, the last position in the document can no longer be edited.
* WebFlow now works around this by crafting a LocalReference that points to sentinel segment that is never inserted into the MergeTree.  (See Flow-Document addLocalRef, etc.)

**Comment by vladsud** [comment]
2 year old issue. @DLehenbauer, @anthony-murphy, we need to either have a plan or punt. Marking as won't for bot to close it if we are not making any progress.
