### ISSUE TITLE
Fluid Debugger localstorage check and activation should exist in the runtime

### ISSUE THREAD

**Issue by leeviana** [microsoft/FluidFramework#860]
Currently when we create the document storage runtime and want to support the fluid debugger, the host has to do a check like _localStorage.FluidDebugger && localStorage.FluidDebugger === '1';_ and then change their document storage creation to include the debugger:

>  driver.documentServiceFactory = await import(
>       /* webpackChunkName: "fluid-debugger" */ '@microsoft/fluid-debugger'
>     ).then(m => m.FluidDebugger.createFromServiceFactory(driver.documentServiceFactory));

Ideally this logic and check should live in the runtime so that all hosts get this functionality and in a consistent manner. Additionally we would also want to keep the performance optimization where the fluid-debugger module is only downloaded when needed and not in all cases.

**Comment by vladsud** [comment]
Given that we made no progress here over last 1.5 years, marking it as won't fix.
