### ISSUE TITLE
"Named root data stores" tests failing in real service

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#8612]
The real service tests are failing - https://dev.azure.com/fluidframework/internal/_build?definitionId=56&_a=summary.
The logs in the pipeline run don't have information on which test is failing but on running locally, I see this failure consistently:
```
Named root data stores
     Non-Compat
       Name conflict expected failures
         Root datastore creation fails at attach op:
   Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (E:\FluidFramework\packages\test\test-end-to-end-tests\dist\test\rootDatastores.spec.js)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

On debugging a little, the following step in line 120 is stuck:
`const dataCorruption = await anyDataCorruption([container1, container2, container3]);`

I believe the problem is that the listener for container.close event needs to be set up **_before_** the inbound queues are resumed. By the time the third container is loaded, the first two container may already have got the duplicate attach op and closed. 

I also see that only one of the container generates the data corruption error, so something seems fishy.

**Comment by andre4i** [comment]
Thanks for catching and investigating this, @agarwal-navin

**Comment by andre4i** [comment]
Confirmed (a couple of times) locally against tinylicious that this particular failure isn't reproducing after the PR above was merged.

I do see `<testcase classname="Summaries Non-Compat" name="Should generate summary tree with isolated channels disabled" time="0.065"><failure>Should not have attempted summary with disposed summarizer` consistently...
