### ISSUE TITLE
Repository field in package.json is improperly formatted

### ISSUE THREAD

**Issue by bekell** [microsoft/FluidFramework#8657]
According to [NPM docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository), the repository field in package.json files should be formatted as such:
`  "repository": {
    "type": "git",
    "url": "git+https://github.com/microsoft/FluidFramework.git"
  },`

Currently, it appears to be formatted as a string:
`  "repository": "https://github.com/microsoft/FluidFramework.git" `

This has caused a few issues with scripts that rely on the formatting.

**Comment by tylerbutler** [comment]
@bekell We'd likely prefer the simpler `"repository": "github:microsoft/FluidFramework"` form. I assume that would satisfy downstream tooling.

**Comment by bekell** [comment]
The downstream tooling we've written relies on an object in the repository field instead of a string. However, this could arguably be considered a bug on our tooling since the shorthand version you provided is an acceptable format according to NPM docs.

Ideally we'd prefer if it was in object format, but understandable if you prefer the simpler shorthand format. We'll update our tooling if you end up going with the shorthand string format.
