### ISSUE TITLE
[MFS] Changes to the tree/blob paths in summaries leading to summarization error

### ISSUE THREAD

**Issue by sgarapati07** [microsoft/FluidFramework#8661]
PR : https://office.visualstudio.com/OC/_git/MfsSDK/pullrequest/1141285?_a=files

This is in regards to the custom OdspSearchableDataObject, CreateOdspSearchDataStorerFactory and getSearchContent method implementation leading to summarization errors. When I created multiple, dynamic search paths, I get a summarization error when the path changes on the next load. For e.g., the following is the latest snapshot with multiple paths each representing a different MFS item. In this case, there are 4 MFS items. Please ignore the replacement of _search with _testing a I'm not testing the actual MS wide search with this code. I'm not testing the snapshot appearance. 
```
{
                    "path": ".app/.channels/default/.channels/_testing",
                    "type": "tree"
                },
                {
                    "id": "bARAO9dM5OFlZiASFdRVDjBj_",
                    "path": ".app/.channels/default/.channels/_testing/testing1",
                    "type": "blob"
                },
                {
                    "path": ".app/.channels/default/.channels/testing1",
                    "type": "tree"
                },
                {
                    "id": "bARAxYryJ3lCHHLXZGcI6ll+N",
                    "path": ".app/.channels/default/.channels/testing1/testing2",
                    "type": "blob"
                },
                {
                    "path": ".app/.channels/default/.channels/testing2",
                    "type": "tree"
                },
                {
                    "id": "bARC0lZJoN_F8agjB0jGAHWUw",
                    "path": ".app/.channels/default/.channels/testing2/testing3",
                    "type": "blob"
                },
                {
                    "path": ".app/.channels/default/.channels/testing3",
                    "type": "tree"
                },
                {
                    "id": "bARCqh9PhNENe_+auc8bnR20C",
                    "path": ".app/.channels/default/.channels/testing3/testing4",
                    "type": "blob"
                },

```

However, if I create a 5th MFS item ( on the same fluid data store), I get a summarization error as follows: 

```
common.js:113 
        
       fluid:telemetry:Summarizer:Running FailToSummarize {"summarizeReason":"maxTime","message":"UnexpectedSummarizeError","category":"error","error":"0x25d","clientType":"noninteractive/summarizer","loaderVersion":"0.52.1","containerId":"8db55d5e-3af5-42aa-bb24-d665db845138","docId":"6pjiyOl1AE56lePeS%2BAjLlHnFaXNoedG57%2F7gqa9qIw%3D","containerAttachState":"Attached","containerLifecycleState":"loaded","containerConnectionState":"Connected","runtimeVersion":"0.52.1","summaryGenTag":1,"dmInitialSeqNumber":53,"dmLastKnownSeqNumber":154,"containerLoadedFromVersionId":"bBzUAAAAHAAAA","dmLastMsqSeqNumber":154,"dmLastMsqSeqTimestamp":1641415227647,"dmLastMsqSeqClientId":null,"connectionState":"Connected","connectionStateDuration":723584.5999999046,"loaderId":"9c9bbbef-e9d5-4f7a-990f-5b8aaaccee22"} tick=784558 Error    at assert (http://localhost:8080/app.bundle.js:43724:15)    at RunWhileConnectedCoordinator.get cancelled [as cancelled] (http://localhost:8080/app.bundle.js:54641:88)    at fail (http://localhost:8080/app.bundle.js:56173:48)    at SummaryGenerator.summarizeCore (http://localhost:8080/app.bundle.js:56215:20) +0ms
```

If I create another instance of fluid data store ( another container/pod), the error doesn't show up. So, I suspect that the summarizer is not able to dynamically pick up changes in the paths ? 

###Expected behavior 

This modified code should create another path as follows and add it to the existing paths in summary ( as this is a new 5th MFS item created ) but instead it throws an exception as outlined above. 

  ```
  {
                    "path": ".app/.channels/default/.channels/testing4",
                    "type": "tree"
                },
                {
                    "id": "bARCqh9PhNENe_+auc8bnR20C",
                    "path": ".app/.channels/default/.channels/testing4/testing5",
                    "type": "blob"
                },
```
Is this an expected behavior and if not, what are the next steps? My goal is to create multiple, dynamic paths each representing a MFS item created on the fly and whenever a new MFS item is created, it should be represented in the snapshot by a new path. That's the goal of my custom code above but it doesn't happen. 

### Steps to reproduce 

1. Run this https://office.visualstudio.com/OC/_git/MfsSDK?version=GBsgarapati/podSearch&path=/examples/mfs-client-prod example in MFS repo
2. Select pick a pod file and navigate to Communication site -> .appdata -> searchTestPod5.pod.
3. Go to network tab in the developer tools and filter using latest snapshot and copy, paste the snapshot object into a text editor to see the summaries. 

CC: @vladsud @anthony-murphy

**Comment by vladsud** [comment]
Searching for [0x25d assert](https://github.com/microsoft/FluidFramework/issues?q=is%3Aopen+is%3Aissue+0x25d) shows that it is being hit in prod:
https://github.com/microsoft/FluidFramework/issues/8626

For some reason search does not find it, but there is bug on that specific isuse - https://github.com/microsoft/FluidFramework/issues/8398
And PR that addresses it - https://github.com/microsoft/FluidFramework/pull/8468

This assert has nothing to do with your changes, you are as likely to hit it without your changes.
And the best course of action is to pick up latest release that should fix it for you

**Comment by vladsud** [comment]
BTW, this assert (I believe) fires only on long idle connections (I think 5 min). So, you should be able to test your code changes even without the fix, if you avoid allowing connections to be idle that long (strictly to unblock you if you can't easily jump to latest bits yet)

**Comment by sgarapati07** [comment]
Hi Vlad,

  Although there is the assert issue, I believe that this is a summarization error because of the multiple search blobs that I have. I think the following is happening:


  1.  A new item is added, so a new search path is being created and the summarizer fails because of the inconsistency with the existing snapshot as it expects the snapshot to have the same paths on the load of the data store.


My question is if that is an expected behavior or a bug on my side or the fluid side ( apart from the assert bug) I see that the assert bug was solved on Dec 7th and our team has upgraded fluid after that as part of our weekly fluid updates.

**Comment by sgarapati07** [comment]
Also, here are some more errors following that: 

`fluid:telemetry:Container ContainerEventHandlerException {"name":"warning","category":"error","error":"Unhandled error. (summarizingError:Error while generating, uploading, or submitting summary)","clientType":"interactive","loaderVersion":"0.52.1","containerId":"2ab49aad-587f-48fb-a041-88a1089e7568","docId":"6pjiyOl1AE56lePeS%2BAjLlHnFaXNoedG57%2F7gqa9qIw%3D","containerAttachState":"Attached","containerLifecycleState":"loaded","containerConnectionState":"Connected","dmInitialSeqNumber":53,"dmLastKnownSeqNumber":156,"containerLoadedFromVersionId":"bBzUAAAAHAAAA","dmLastMsqSeqNumber":156,"dmLastMsqSeqTimestamp":1641500890563,"dmLastMsqSeqClientId":null,"connectionState":"Connected","connectionStateDuration":5425.4000000003725,"loaderId":"ff152e14-e9a3-48d6-9309-746aa080568b"} tick=380394 Error    at OdspClient.emit (http://localhost:8080/app.bundle.js:140375:15)    at OdspClient.emitMfsClientEvent (http://localhost:8080/app.bundle.js:261569:21)    at Container.<anonymous> (http://localhost:8080/app.bundle.js:261643:18)    at Container.emit (http://localhost:8080/app.bundle.js:140386:5)    at Container.emit (http://localhost:8080/app.bundle.js:85683:26)    at Container.raiseContainerWarning (http://localhost:8080/app.bundle.js:46976:14)    at ContainerContext.raiseContainerWarning (http://localhost:8080/app.bundle.js:47620:378)    at SummaryManager.ContainerRuntime.raiseContainerWarning (http://localhost:8080/app.bundle.js:51012:26)    at SummaryManager.emit (http://localhost:8080/app.bundle.js:140386:5)    at Summarizer.<anonymous> (http://localhost:8080/app.bundle.js:56479:65) +0ms`


```
common.js:113 
        
       fluid:telemetry:Summarizer:Running Summarize_cancel {"refreshLatestAck":false,"fullTree":false,"timeSinceLastAttempt":776904139,"timeSinceLastSummary":776904139,"category":"error","referenceSequenceNumber":156,"opsSinceLastAttempt":103,"opsSinceLastSummary":103,"reason":"submitSummaryFailure","duration":9,"error":"channelTypeNotAvailable","errorType":"dataCorruptionError","errorInstanceId":"ffe4cc0b-51b8-4933-81eb-f560a8020c2f","channelId":"_testing","dataStoreId":{"value":"default","tag":"PackageData"},"dataStorePackagePath":"@taoscap/mfs-fluid-data-store","dataProcessingError":1,"fluidErrorCode":"channelTypeNotAvailable","canRetry":false,"message":"channelTypeNotAvailable","clientType":"noninteractive/summarizer","loaderVersion":"0.52.1","containerId":"43e1fdfe-1dcb-4d2d-95b9-8274c3e5c862","docId":"6pjiyOl1AE56lePeS%2BAjLlHnFaXNoedG57%2F7gqa9qIw%3D","containerAttachState":"Attached","containerLifecycleState":"loaded","containerConnectionState":"Connected","runtimeVersion":"0.52.1","summaryGenTag":1,"summarizeReason":"maxTime","summarizeTotalAttempts":1,"summarizeAttemptsPerPhase":1,"summarizeAttemptPhase":1,"dmInitialSeqNumber":53,"dmLastKnownSeqNumber":156,"containerLoadedFromVersionId":"bBzUAAAAHAAAA","dmLastMsqSeqNumber":156,"dmLastMsqSeqTimestamp":1641500890563,"dmLastMsqSeqClientId":null,"connectionState":"Connected","connectionStateDuration":10.5,"loaderId":"ff152e14-e9a3-48d6-9309-746aa080568b"} tick=380395 Error    at RemoteChannelContext.loadChannel (http://localhost:8080/app.bundle.js:58410:23)    at async RemoteChannelContext.summarizeInternal (http://localhost:8080/app.bundle.js:58391:25) +0ms
debug @ common.js:113
send @ debugLogger.js:94
send @ logger.js:245
sendTelemetryEventCore @ logger.js:101
sendPerformanceEvent @ logger.js:121
reportEvent @ logger.js:375
cancel @ logger.js:356
fail @ summaryGenerator.js:122
summarizeCore @ summaryGenerator.js:155
await in summarizeCore (async)
summarize @ summaryGenerator.js:91
(anonymous) @ runningSummarizer.js:257
lockedSummaryAction @ runningSummarizer.js:189
trySummarize @ runningSummarizer.js:231
(anonymous) @ runningSummarizer.js:54
run @ summarizerHeuristics.js:54
start @ runningSummarizer.js:90
await in start (async)
runCore @ summarizer.js:125
await in runCore (async)
run @ summarizer.js:71
(anonymous) @ summaryManager.js:156
timedExecAsync @ logger.js:320
(anonymous) @ summaryManager.js:156
Promise.then (async)
startSummarization @ summaryManager.js:134
SummaryManager.refreshSummarizer @ summaryManager.js:57
emit @ events.js:153
(anonymous) @ summarizerClientElection.js:92
emit @ events.js:153
tryElectingClient @ orderedClientElection.js:184
addClient @ orderedClientElection.js:210
(anonymous) @ orderedClientElection.js:136
emit @ events.js:153
(anonymous) @ orderedClientElection.js:34
emit @ events.js:158
listener @ eventForwarder.js:54
emit @ events.js:158
addMember @ quorum.js:139
processMessage @ protocol.js:54
processRemoteMessage @ container.js:1289
process @ container.js:1163
processInboundMessage @ deltaManager.js:1205
(anonymous) @ deltaManager.js:163
processDeltas @ deltaQueue.js:107
(anonymous) @ deltaQueue.js:83
Promise.then (async)
ensureProcessing @ deltaQueue.js:82
push @ deltaQueue.js:59
enqueueMessages @ deltaManager.js:1133
DeltaManager.opHandler @ deltaManager.js:125
emit @ events.js:158
(anonymous) @ documentDeltaConnection.js:87
(anonymous) @ odspDocumentDeltaConnection.js:410
../../node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
../../node_modules/socket.io-client/lib/socket.js.Socket.onevent @ socket.js:278
../../node_modules/socket.io-client/lib/socket.js.Socket.onpacket @ socket.js:236
(anonymous) @ index.js:21
../../node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
../../node_modules/socket.io-client/lib/manager.js.Manager.ondecoded @ manager.js:349
(anonymous) @ index.js:21
../../node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
../../node_modules/socket.io-client/node_modules/socket.io-parser/index.js.Decoder.add @ index.js:251
../../node_modules/socket.io-client/lib/manager.js.Manager.ondata @ manager.js:339
(anonymous) @ index.js:21
../../node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
../../node_modules/engine.io-client/lib/socket.js.Socket.onPacket @ socket.js:461
(anonymous) @ socket.js:278
../../node_modules/component-emitter/index.js.Emitter.emit @ index.js:145
../../node_modules/engine.io-client/lib/transport.js.Transport.onPacket @ transport.js:149
../../node_modules/engine.io-client/lib/transport.js.Transport.onData @ transport.js:141
ws.onmessage @ websocket.js:160
common.js:113 mfs:loader Call to get the access token for ODSP +0ms
common.js:113 mfs:client Emitting +0ms {event: 'error', arg: {…}}
```

`fluid:telemetry:Container ContainerEventHandlerException {"name":"warning","category":"error","error":"Unhandled error. (summarizingError:Error while generating, uploading, or submitting summary)","clientType":"interactive","loaderVersion":"0.52.1","containerId":"2ab49aad-587f-48fb-a041-88a1089e7568","docId":"6pjiyOl1AE56lePeS%2BAjLlHnFaXNoedG57%2F7gqa9qIw%3D","containerAttachState":"Attached","containerLifecycleState":"loaded","containerConnectionState":"Connected","dmInitialSeqNumber":53,"dmLastKnownSeqNumber":156,"containerLoadedFromVersionId":"bBzUAAAAHAAAA","dmLastMsqSeqNumber":156,"dmLastMsqSeqTimestamp":1641500890563,"dmLastMsqSeqClientId":null,"connectionState":"Connected","connectionStateDuration":5744.199999999255,"loaderId":"ff152e14-e9a3-48d6-9309-746aa080568b"} tick=380712 Error    at OdspClient.emit (http://localhost:8080/app.bundle.js:140375:15)    at OdspClient.emitMfsClientEvent (http://localhost:8080/app.bundle.js:261569:21)    at Container.<anonymous> (http://localhost:8080/app.bundle.js:261643:18)    at Container.emit (http://localhost:8080/app.bundle.js:140386:5)    at Container.emit (http://localhost:8080/app.bundle.js:85683:26)    at Container.raiseContainerWarning (http://localhost:8080/app.bundle.js:46976:14)    at ContainerContext.raiseContainerWarning (http://localhost:8080/app.bundle.js:47620:378)    at SummaryManager.ContainerRuntime.raiseContainerWarning (http://localhost:8080/app.bundle.js:51012:26)    at SummaryManager.emit (http://localhost:8080/app.bundle.js:140386:5)    at Summarizer.<anonymous> (http://localhost:8080/app.bundle.js:56479:65)`

**Comment by vladsud** [comment]
@sgarapati07, can you please take a look if there is anything actionable here?
Asserts you brought up were not specific to search area but were all fixed.
I do not see how or what last stack shows, but I've opened https://dev.azure.com/fluidframework/internal/_queries/edit/850/?triage=true to take a look at somewhat related problem.

Please let me know if you are blocked, but I currently do not see anything on FF side.
