### ISSUE TITLE
Floating Promise calling DataStoreContext.realize prefetching DS after attaching remote DS

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#8667]
I'm seeing evidence in Office Fluid telemetry that DataStoreContext.realize is failing in this case (because the errors don't seem to bubble up, only get logged via `"RealizeError"` event):

https://github.com/microsoft/FluidFramework/blob/124e881fc7fb37e9fa5709fcf7b90ab3e65a9e58/packages/runtime/container-runtime/src/dataStores.ts#L241-L243

I don't know this code/scenario well enough to judge what this means exactly or how application flow will continue from here if we can't realize a newly-attached data store, but wanted to raise the issue.

All other callers to DataStoreContext.realize return or await the promise.  In the logs I can see a subset of failures hitting `Summarize_cancel`, for instance.

cc @vladsud, @agarwal-navin to comment on if this is a problem or not.

**Comment by vladsud** [comment]
This code is wrong and should be removed. And I though Navin had PR to do so (or an issue).

**Comment by agarwal-navin** [comment]
This may help - https://github.com/microsoft/FluidFramework/issues/8494

**Comment by markfields** [comment]
Ok I will close this then, now that it's been tied with that issue :)
