### ISSUE TITLE
Move Shared Cell to Examples Namesapce

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8683]
As a DDS shared cell is a great example for those looking to understand how DDS work, but it generally shouldn't be used in any real scenarios.  It shouldn't be used as the overhead (attributes blob, tree structure, ...) of the dds grossly outweighs the data stored within the DDS itself (a single value). This is why we provide a map/directory as the root dds, such that a number of a key value pairs can be stored without additional overhead per value. This should also be reflected in our documentation.

Fyi @tylerbutler, @ChumpChief

**Comment by ChumpChief** [comment]
We might also want to do this with counter.  It also hasn't been a good scenario match, serves more as an example than a real tool.
