### ISSUE TITLE
Upgrade webpack-dev-server in @fluid-tools/webpack-fluid-loader

### ISSUE THREAD

**Issue by christiango** [microsoft/FluidFramework#8693]
## Work Item
Our repo currently depends on webpack-fluid-loader, which has a dependency on webpack-sev-server v3. This can be problematic as it brings old versions of dependencies like chokidar which can trigger component governance alerts. In the short term, we can dismiss these component governance alerts, but this introduces a risk of us missing real issues down the line for the vulnerable packages.

**Approach**

**Acceptance criteria**
Taking a dependency on webpack-fluid-loader does not require installing webpack-dev-server v3

**Comment by christiango** [comment]
@skylerjokiel / @curtisman - could one of you triage this? I suspect this will trigger component governance alerts for downstream repos like it did for our internal repo.

**Comment by curtisman** [comment]
This has been updated in #9615 to 4.0.0 and then to 4.6.0 in #10293
