### ISSUE TITLE
(IContainer Updates Phase 3) Op processing management: resume, deltaManager

### ISSUE THREAD

**Issue by sumedhb1995** [microsoft/FluidFramework#8708]
**Requirement**

Client applications require a way to manually control when ops are being processed. This is useful both from a UX perspective, i.e. how FFX uses it to process ops prior to rendering a view, and for control over a test harness. One of the most extensively used classes in our end-to-end-tests is the loaderContainerTracker which exposes an API for tests to use when they need to resume and pause ops on containers created by a specific loader.

The current delta manager API which is currently being used for this needs to be improved. To an outside developer, deltaManager is almost incomprehensible due to the myriad of functionality available on its public API. Furthermore, it also exposes values such as sequence number information, access to the inbound and outbound delta queues themselves, service configuration info, and client details that we might not want developers accessing. As such, a more condensed public API is needed.

The new API should be made available and tested such that it does not create any modifications or regressions to the behavior in the sequencing of ops as it would have occurred were direct control applied to the delta manager itself. I.e. the same sequence of operations conducted through the delta manager API and the new API should result in ops being processed in the same order

**Proposed Solution**

PR: [[Draft WiP] Move op processing control and tracking to container level by sumedhb1995 · Pull Request #8707 · microsoft/FluidFramework (github.com)](https://github.com/microsoft/FluidFramework/pull/8707)

In the described PR, the idea is to open up a new interface on IContainer where me migrate some of the functionality from deltaManager and expose it there in a more controlled fashion. The overarching concept here is that we can take the functionality we want to expose from delta manager in a piecemeal fashion and provide it as a new interface on IContainer, until we can deprecate delta manager altogether and only use the new API. Here, we are specifically targeting the functionality for controlling the op stream.

To provide the controls necessary for our users, we provide a new containerOpController value on the IContainer interface. It is of type IContainerOpController and provides four functions:

- pauseProcessing(): Promise<void>;
Pause all queue activities on the current container
- resumeProcessing(): void;
Resume all queue activities on the current container
- processIncoming(): Promise<void>;
Pause all queue activities, and resume only inbound to process ops until it is idle. All queues are left in the paused state after the function
- processOutgoing(): Promise<void>;
Pause all queue activities, and resume only outbound to process ops until it is idle. All queues are left in the paused state after the function

**Requirement Fulfillment** (in order of requirements presented above):

These four APIs fulfill the requirements of both UI-based clients to control when op processing is being paused and resumed, as well as all the necessities of our end-to-end-tests harnesses. In fact, as a way of testing the PR, it refactors the loaderContainerTracker to use the containerOpController in order to manipulate and synchronize the operations of each individual container that the loader creates, instead of reaching into the deltaManager for each of them. This is an example of how this allows the container to independently provide the knobs for its op flow instead of requiring higher-level components to reach into their inner workings.

These four APIs provide an easily understandable way of controlling the op stream. While the move of the other interfaces, such as client ID and if the current client is a summarize client or not, do also need to be moved off of delta manager, that should come in subsequent PRs. This one, however, allows us to capture one of the most popular uses of delta manager, which control over the inbound and outbound queues.

Since loaderContainerTracker is used extensively in our DDS and end-to-end-tests, by incorporating its refactoring into this PR, we have an extensive number of test suites running to ensure that the order of operations stays the same despite the change in the interface with which we apply the control. Furthermore, even after containerOpController is exposed and released, deltaManager will still be available so that our customers can migrated gracefully

**Comment by skylerjokiel** [comment]
Moved to ADO
