### ISSUE TITLE
rootDataStoreRequestHandler should return undefined instead of create404Response()

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8723]
When `rootDataStoreRequestHandler` is passed as a request handler to `buildRuntimeRequestHandler()` and it fails to execute, it returns an error `create404Response()`. This doesn't allow the other request handlers passed after `rootDataStoreRequestHandler` to run. 

Instead, `rootDataStoreRequestHandler` should return `undefined` and the next request handler should get executed.

**Comment by anthony-murphy** [comment]
this seems pretty bad as rootDataStoreRequestHandler is called out in the breaking as what should be used:
https://github.com/microsoft/FluidFramework/blob/main/BREAKING.md#removed-innerrequesthandler

**Comment by ssimic2** [comment]
@anthony-murphy what was original idea behind request handlers and usage with `RuntimeRequestHandlerBuilder` ? It looks like builder is expecting previous handler to return `undefined` when deciding if to consider the next handler. If handler was never returning 404 (container/datastore runtime handlers) this may not have been an issue when the handler was the last in the list. But now, if we are (indirectly) injecting these handlers when we create factories, this becomes a problem.

To be consistent we should probably rework the builder to consider all handlers even in the case where 404 was returned by previous handler. Something that datastore runtime does with `mixinRequestHandler`. 

I know this pattern is going away, we are just ensuing we don't introduce regressions and ensure consistency.

**Comment by ChumpChief** [comment]
Agree this is good to fix immediately, such that it's a good drop-in replacement for `innerRequestHandler`

**Comment by anthony-murphy** [comment]
@ssimic2 the best reason i can give for the way it is in legacy. Way back we just took an array for request handlers, eventually that got factored out into what it is now. It was never really meant to be a full-fledged solution, as i don't think we want to own routing. It's actually a bummer that aqueduct is coupled to it at all, as the original change was meant to allow people to plug in their own routing layer, like https://www.npmjs.com/package/page. 

For now i'd suggest taking a do no harm approach to changes when it comes to routing.
