### ISSUE TITLE
Update event hubs sdk to v5

### ISSUE THREAD

**Issue by GaryWilber** [microsoft/FluidFramework#873]
v5 is releasing soon. We should test and update the server at some point if things look good.

https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/eventhub/event-hubs

**Comment by chradek** [comment]
There's a migration guide for moving over the event-hubs v5:
https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/eventhub/event-hubs/migrationguide.md

Feel free to send me a ping if you want extra eyes on a PR that makes this update (I'm on of the maintainers of the event-hubs library.)

**Comment by znewton** [comment]
@GaryWilber is this being worked on? The current version in use depends on azure-storage which uses md5.js and is a blocker for our team because of that.

**Comment by GaryWilber** [comment]
@znewton It's not being worked on. SPO's fluid service is using Kafka, so we have no need to update the event hubs side of it.
