### ISSUE TITLE
SharedIntervalCollections Reconnect/Resubmit Correctness

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8739]
Looking at the code in 
 - packages\dds\sequence\src\sharedIntervalCollection.ts
 - packages\dds\sequence\src\sequence.ts

both see to just resend the original message in reSubmitCore to the interval map. This doesn't seem right. The op should be regenreate as the undelying sequence could have changed. This may only be a problem in sequence. the first step is to add tests for both.

[AB#48](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/48)

**Comment by Abe27342** [comment]
Closing this--we believe this is correct as of #10342
