### ISSUE TITLE
Dubious switch fallthrough case in undo-redo

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#8755]
> This looks like it found a bug, like there should be a `break` statement above...?  @anthony-murphy, @wes-carlson what do you think?

_Originally posted by @markfields in https://github.com/microsoft/FluidFramework/pull/8685#discussion_r781673019_

**Comment by anthony-murphy** [comment]
there aren't enough details here, and the link to the code doesn't work for me

**Comment by wes-carlson** [comment]
https://github.com/microsoft/FluidFramework/blob/787ab708edc7ca6dad63c988f880b5c4ada485dc/packages/framework/undo-redo/src/sequenceHandler.ts#L118-L129

**Comment by anthony-murphy** [comment]
yeah. looks like a bug. obviously, no one is using this :)
