### ISSUE TITLE
Stop using ErrorType enums in base error interface/type definitions

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#8821]
_[edit: per conversation below, the outcome here may be in the opposite direction from the original statement.  Stay tuned]_

In https://github.com/microsoft/FluidFramework/pull/8803 I realized that since we constrain the type of `errorType` in our error interface/type definitions, any change to the enum breaks backwards or forwards compatibility, potentially in a lot of places.

As far as I see it, the purpose of this constraint is to help devs creating errors to use the right set of `errorType` values in a given context, and not for a consumer of these error interfaces/types.  All these errors end up being cast to `IErrorBase` in the end, which has `errorType: string`.  Anywhere that uses a variable of a specialized type (with specialized `errorType`) would be just as well-served to use `IErrorBase` instead.

To avoid the pain for consumers of our packages represented by breaking changes, I'm proposing we switch to using `errorType: string`.  We will have to be more deliberate in PRs to encourage proper/constrained values for `errorType`, but I think the precedence of using enum values and not string literals throughout the code is enough.

**Comment by markfields** [comment]
@anthony-murphy, @vladsud - I need your buy-off here before proceeding with this change.

**Comment by markfields** [comment]
I'm remembering there's another value to having `errorType` be specialized, which is automatic type guards based on checking `errorType`.  But... I'm not sure we're actually doing this anywhere in the code, so it seems fine to let go of this feature.

**Comment by anthony-murphy** [comment]
I think consumers also use these, basically they look at errors to see if the string matches a known string (the enum) and then use that to do some action if there is a match. In my mind these enums represent a protocol between the layer that allow consumer to act in certain cases. not all errors can or should be part of this protocol.

**Comment by anthony-murphy** [comment]
Moving this to error api is the right path in my opinion. then error type become a clear member of the contract between the layers. unknow things are just thrown, and represent unknown, or unhandelable states.

**Comment by markfields** [comment]
> I think consumers also use these, basically they look at errors to see if the string matches a known string (the enum) and then use that to do some action if there is a match

Looking at Office Fluid code, they cast to the specialized error type, and then do checks of errorType against the corresponding enum.  Yes, they'll get some intellisense after casting, but otherwise there's really no benefit over errorType being a string everywhere.  If you're doing the cast, then you know what you're looking for.

> Moving this to error api is the right path in my opinion

Good point to think ahead to that world.  My starting assumption in the error api world would be to have errorType be strongly typed, but this experience is giving me pause.

We should publish type guards for the important error shapes (likely implemented by checking errorType), but there will be many errorTypes that ought to be treated the same, just differentiated in the logs.  So the flexibility to say errorType is a string, and then write code to handle specific known values (we'd still publish an enum or set of consts for this purpose), is win-win.

All that is to say, whether we throw or return errors, the same principles apply here, and I'm still feeling this is the right direction.

**Comment by anthony-murphy** [comment]
I think we need to consider this protocol. so it needs to be defined. not all errors are in the protocol, then should be a big bucket of unknown things. things in the protocol influence specific behavior in our layers or on the client layer.

**Comment by anthony-murphy** [comment]
I was re-reading your response, and something i would say is that errorType is a runtime thing, not a telemetry thing. It's about handling know error cases and doing actions in response to errors at runtime. It may also be logged, but it's goal should not be around telemetry. We are also likely inconsistent in this regard today.

**Comment by markfields** [comment]
I think it's both.  I don't want so many different bucketing layers.  I'm thinking about your pushback on being strict about the protocol, weighing the convenience of flexibility to modify the values v. the risk of inadvertently breaking partner logic that's expecting certain values.  Today we are kind of in the middle and not really leveraging the strictness.

**Comment by anthony-murphy** [comment]
I really think we need to explicit that it is not both. we should never add something to errorType (or equivalent) unless it is leveraged at runtime; we don't add things to the procotol that are not used. we should have alternate mechanism to different errors in telemetry.

**Comment by markfields** [comment]
> we should never add something to errorType (or equivalent) unless it is leveraged at runtime

Going to check how many of our errorType values trigger specific handling in Office Fluid code...

**Comment by anthony-murphy** [comment]
include our code as well. we use it across our layers

**Comment by markfields** [comment]
Not trying to "prove you wrong" btw, just assessing where we're at today against your POV.

**Comment by anthony-murphy** [comment]
yeah. i'm definitely pushing an agenda. the agenda is that we need a defined error api, right now the best we have is errorType. i wish it was better, and i'm against making it worse.

**Comment by markfields** [comment]
> Going to check how many of our errorType values trigger specific handling in Office Fluid code...

I'd say around half of the enum values are used at runtime across the three enums we've got today, either in our repo or the Office Fluid codebase.  Some switch statements with `// todo`s to add specific handling :P

Some examples today that are unused when handling errors, but are useful in telemetry:

* ContainerErrorType.usageError
* ContainerErrorType.dataProcessingError
* ContainerErrorType.dataCorruptionError
* DriverErrorType.writeError
* DriverErrorType.incorrectServerResponse
* OdspErrorType.cannotCatchUp
* OdspErrorType.fetchTokenError

So these are good cases to think about what errorType do they deserve and how would we categorize them if they each don't get a specific errorType.

It's obviously grey area - We may have an errorType that we believe is an important part of the protocol, but our partners may let it fall through to the `default` case in a switch statement.

> not all errors are in the protocol, there should be a big bucket of unknown things

This speaks to the grey area I just called out.  So two options here:

1. Maintain errorType's specialized types on each layer's error interface/type. This is the protocol.  If we want to change the enum values, we need to stage it over several releases like any protocol change. Then use some other telemetry prop for sub-bucketing generic fatal errors.  (You called this "big bucket of unknown things", I'd call it a big bucket of _uninteresting_ things. And there are also unknown things, separately. I'm focused on how we express errors we raise ourselves).
2. Loosen up errorType to just be a string on our error interfaces/types (the original proposal here).  Meanwhile, keep exporting the enums so consumers know the reasonable set of values to check against, for any that have special handling.  We would have to keep in mind that the errorType enums are leveraged at runtime, and tread lightly when changing them.

Ok.  You convinced me.  (2) is not a good idea :)  Honestly, it's largely where we are at today, but I am now thinking about the pain of the secret importance of stability of our `errorType` values with no help from the type system.

**Comment by anthony-murphy** [comment]
I'd be more open to an opposite change, lock down error type, it is protocol, remove any non-protocol values. This is our v0 api, and will eventually move to be non-exception based. We log error type, but it is not primarily for bucketing, use some other string, message/errorCode/blah for telemetry bucketing.

**Comment by markfields** [comment]
That said, I need some help here with how this will actually play out.  There's a reason that today `ICriticalContainerError` has `errorType: string`, which is of course the mix-and-match of layers in the wild.

If the container wants to be more specific about `errorType`s it's emitting, it's kinda stuck. It can know for sure what's in `ContainerErrorType`, but if it says anything about `DriverErrorType`, it's not really sure.

**Comment by markfields** [comment]
Oh, it's worse than that, because you don't know which driver you're using... :(

**Comment by anthony-murphy** [comment]
container-definition references driver-definitions, so has access to the enum, make it is union.  

Note: i'd also love these to not be enums, and just be a union type of strings.

**Comment by anthony-murphy** [comment]
driver-definitions is for all drivers, and things should be generic there. driver specific errors should probably define their own sub-field that can be leverage for driver aware hosts

**Comment by markfields** [comment]
> container-definition references driver-definitions, so has access to the enum, make it is union.

No I get that.  But, at runtime you could have a different version of the driver running and the actual errorType value may not exist in the enum you compiled against.  Is it a matter of how long you stage your changes, so other layers know about a value before it ever shows up in practice?

**Comment by anthony-murphy** [comment]
it doesn't really matter in practice, if you know about an error type you can handle it, if you don't it just some unknown thing, which should ideally just be like a typed you don't handle

**Comment by markfields** [comment]
> driver specific errors should probably define their own sub-field that can be leverage for driver aware hosts

Yeah I'm thinking about `OdspErrorType`, which has some important cases that the host handles today.  The Container is never going to reference that type.  So are you suggesting we put these values in a different field from `errorType`?  Hmmm...

**Comment by anthony-murphy** [comment]
i agree it isn't ideal. someday the driver method shouldn't normally throw. throwing is a critical error where we close everything down. they should return an object that defines the error, this probably have both strongly and weakly defined portions, maybe there is a medium defined portion, like some generic that specific drivers know, but thats a contract between the driver and host, fluid just passes it along.

**Comment by markfields** [comment]
Great discussion.  Not going to continue tracking anything here in GitHub for now, but I'm working on a guidance doc for errors that will incorporate this feedback.
