### ISSUE TITLE
Custom DataObject as a fully supported extensibility point for azure-client

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#8855]
Currently custom DataObjects are only implicitly supported by azure-client. To provide deeper functionality into Fluid we want to expose this as an explicit extensibility point.

## Concerns/Thoughts
- The existing API surface when building a DataObject is very large
- The patterns for Container/DataObject separation is not clearly laid out
- Current DO creation requires class inheritance which js developers don't like
- Current DataObject doesn't enforce getFactory which is required for azure-client

## Key Results
1. Developers can create DataObjects (or similar)
2. Developers can consume these DataObjects (or similar) in azure-client

> Note: DataObject is a specific aqueduct class but in this context I'm speaking to it as a generic thing that developer can build and not the class specifically

**Comment by AndrewCraswell** [comment]
Is the Data object pattern documented anywhere? I've been trying to grow the examples, but was hoping maybe something had been written up at some point?
