### ISSUE TITLE
Create a mock config implementation for the test object provider

### ISSUE THREAD

**Issue by andre4i** [microsoft/FluidFramework#8861]
We have an [configuration feature](https://github.com/microsoft/FluidFramework/blob/main/packages/utils/telemetry-utils/src/config.ts) which can be used for scenarios involving feature gates. 

It would be great if we could easily enable developing tests against new feature gates. Currently, this is possible by creating mock setting stores and manually creating the config provider ([example in the config tests](https://github.com/microsoft/FluidFramework/blob/e31df8309ad9a96eef50267f5b2a80303f24eea3/packages/utils/telemetry-utils/src/test/config.spec.ts#L55)). [We could also override the actual](https://github.com/microsoft/FluidFramework/pull/8805/files#diff-5f8ba9e0e468e76737c8e8be3c120c57d1901874c686f7e6ce682711ad2c3fb7R37) global `(session|local)storage` object and rely on the end-to-end logic of config management.

But considering that we already optionally provide a config to the loader via the `ILoaderProps` interface ([see](https://github.com/microsoft/FluidFramework/blob/e31df8309ad9a96eef50267f5b2a80303f24eea3/packages/loader/container-loader/src/loader.ts#L223)), for testing, it would be ideal to integrate this feature with the `TestObjectProvider` which is broadly used across the codebase. This would both remove code duplication and limit the surface area of the configuration as we can avoid mutating the storage objects altogether.

Acceptance criteria:
- adapt the `TestObjectProvider` to supply a mock config to the loader. The mock config should not be backed by persistent storage (like sessionstorage/localstorage) in order to minimize the spread of these configurations.
- add methods to the `ITestObjectProvider` interface to be able to provide CRUD operations over named config values. So that developers are able to reset all configs, change and audit individual configs, etc..

**Comment by agarwal-navin** [comment]
We should also have a test implementation of the config provider that can be used by any tests. The test object provider should use that too. There are tests (such as snapshot tests) and tools (fetch and replay) that do not use the test object provider.
