### ISSUE TITLE
Pending Manager Initialization

### ISSUE THREAD

**Issue by ssimic2** [microsoft/FluidFramework#8893]
Pending manager does not consider `initialState` as pending ops. Even after ops are moved from `initialState` to `pendingStates`, if pending state manager was queried for `hasPendingMessages`, it would return false as `pendingMessagesCount` only considers counter that is moved when messages are submitted through `onSubmitMessage`. 

Further `IContainerContext` types pendingLocalState as unknown; Should it be IPendingLocalState ?

Refs discussion with @wes-carlson: https://github.com/microsoft/FluidFramework/pull/8596#discussion_r784436748

We need to solve this ticket to avoid transient issue where isDirty flag on the container is false (after attach was processed), even if there are pending ops in the PendingManager.

**Comment by wes-carlson** [comment]
This was fixed in #9557
