### ISSUE TITLE
FluidHelloWorld - npm install fails with - e401 - HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="https://pkgsprodwus21.pkgs.visualstudio.com/"

### ISSUE THREAD

**Issue by amdeymsft** [microsoft/FluidFramework#8899]
## Describe the bug
following instructions at [FluidHelloWorld](https://github.com/microsoft/FluidHelloWorld), npm install fails with
HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="https://pkgsprodwus21.pkgs.visualstudio.com/"

### To Reproduce
1. git clone https://github.com/microsoft/FluidHelloWorld
2. cd FluidHelloWorld
3. npm install

### Expected behavior
no errors.

### Logs
5426 verbose stack HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="https://pkgsprodwus21.pkgs.visualstudio.com/"
5426 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:84:17
5426 verbose stack     at runMicrotasks (<anonymous>)
5426 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
5427 verbose statusCode 401
5428 verbose pkgid yeast@https://pkgs.dev.azure.com/office/_packaging/Office/npm/registry/yeast/-/yeast-0.1.2.tgz
5429 verbose cwd C:\Users\amdey\repos\FluidHelloWorld
5430 verbose Windows_NT 10.0.19044
5431 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
5432 verbose node v16.13.2
5433 verbose npm  v8.1.2
5434 error code E401

**Comment by tylerbutler** [comment]
@amdeymsft Can you check that you don't have an `.npmrc` file that is configured to pull packages from the Office feed? I can't repro this on Windows, Linux, or mac OS.

**Comment by amdeymsft** [comment]
where could this file be? I don't have any such file under fluidhelloworld.

**Comment by tylerbutler** [comment]
See here: <https://docs.npmjs.com/cli/v6/configuring-npm/npmrc> Check your global and user-level configs.
