### ISSUE TITLE
Remove logger property from IContainerContext

### ISSUE THREAD

**Issue by sdeshpande3** [microsoft/FluidFramework#8902]

**Comment by markfields** [comment]
For the `logger` property - please wait until there are 0 loaders pre-0.45, even if it takes a year or more. There's no harm for this fallback code to live around until then.

See this comment for slightly more context:  https://github.com/microsoft/FluidFramework/issues/8191#issuecomment-985786098

**Comment by sdeshpande3** [comment]
The `logger` property was marked as an optional parameter in `IContainerContext` interface: https://github.com/microsoft/FluidFramework/pull/8886 as `ContainerContext` assumes it to be a required parameter. This would be removed in release 0.57 from the interface and class. 

The fallback code `const passLogger = context.taggedLogger  ?? new TaggedLoggerAdapter((context as OldContainerContextWithLogger).logger)`, `TaggedLoggerAdapter` and `OldContainerContextWithLogger` interface will still remain.

@markfields, FYI

**Comment by markfields** [comment]
Ah righto, carry on
