### ISSUE TITLE
DeltaLatency event should not do aggregation

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8914]
Code:

```ts
    private recordPingTime(latency: number) {
        this.pongCount++;
        this.socketLatency += latency;
        const aggregateCount = 100;
        if (this.pongCount === aggregateCount) {
            this.logger.sendPerformanceEvent({
                eventName: "DeltaLatency",
                duration: this.socketLatency / aggregateCount,
            });
            this.pongCount = 0;
            this.socketLatency = 0;
        }
    }
```
It's great in a way of reducing amount of data sent, and giving us P50.
Unfortunately, aggregation like that does not allow us to calculate P90, P99 easily, as data is already smoothed by averaging, so we can't easily.
I think we should sample one in 100, not average 100.

Alternatively (or in addition to above), we can remember time of last ping and put it as a property on OpRoundtripTime event.
That way we will have individual ping times, and likely can-do math (i.e., calculate how much time service spent processing op).
The more data we can put on a single event, the better analyses we can do, as today we can only work with statistics across each measure, but can't really do any math between them (i.e. calculate service processing time, client processing time, etc.).

We might still leave recording pings as separate events, as it helps access quality of connection for read clients, who never sent any ops.

**Comment by vladsud** [comment]
@chensixx, assigning to you. @jatgarg - any chance you can help Si if she has any questions here? Thanks!

**Comment by markfields** [comment]
FYI I'm also looking at this one with Si 👌

**Comment by chensixx** [comment]
just to confirm, to sample one in 100, we are just recording the `latency` of one ping, instead of `this.socketLatency`

**Comment by vladsud** [comment]
Yep.
Bonus point - if we can figure out a way for same op to report all the data at once, like latency, full ack time, msn info, etc.
Data comes from different angles, so it's not always possible to do so directly, but here (as an example), we can remember duration of last ping, and use it as a property on an event that reports other op-related statistics. Then we can use it as a proxy for how long this op takes to be transferred over the wire, and calculate estimates for other metrics (like server processing)

The reason aggregation in code is not great is - we can't answer basic question, like what's our P95 for latency. Only P50 stays unaffected.

**Comment by markfields** [comment]
@vladsud - We were trying to learn when the "pong" is emitted, just for context.  I don't see anyone in the FF repo emitting "pong" on the server.  Or us sending a "ping" or anything.  Can you explain what this event and its latency means exactly and how it's used?  Thanks!

**Comment by markfields** [comment]
(btw, it was computing average, which is different from P50 aka mean)

**Comment by vladsud** [comment]
You would need to refer to socket.io documentation :) It's part of that layer.
