### ISSUE TITLE
Understanding relay service COGS: Measure socket.io bandwidth

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8932]
We do not have good data on Fluid relay service scalability data, and what impacts it.
But certain data suggests that part of it (active connections) is greatly impacted by CPU (not memory, for example), and CPU usage is directly proportional to size of data processed by system.

I just realized that I believe we have no data (at least on client side) re how much ops we are sending or receiving, specifically - bytes over wire. It would be great to collect that data in some form.

I think the most trivial one - for summarizer to output this info - size and number of ops summarized in a summary. This would not impact main client perf (as long as summarizer yields), and would likely provide good enough starting data point.
That kind of statistic with some average number of connections per doc would give us enough data on bytes in & bytes out.

I'm not sure I want to record actual ops, as client can be closed at any moment without notice, so it's hard to make this data accurate. 

Note that we can approximate here. I.e. if we have message contents as a string, I think it's fine to report that, and number of messages, and we can pretty accurately guess how (minus double-escaping) of overall size.

**Comment by vladsud** [comment]
@GaryWilber, @ahmedbisht - FYI, in case we have any service data in this area (worth sharing, but I'd love client to record it too).

**Comment by vladsud** [comment]
Note - SummaryGenerator.summarizeCore() and "GenerateSummary" already tracks opsSinceLastSummary property - that's count of ops, but not their size. having size here will also help us compare it to size of summaries, and see inefficiencies here.

**Comment by andre4i** [comment]
Telemetry has been added, follow-up https://github.com/microsoft/FluidFramework/issues/9795
