### ISSUE TITLE
Integrate type validation updates in the (bump version | release) tooling

### ISSUE THREAD

**Issue by andre4i** [microsoft/FluidFramework#8944]
When releasing a new version, a type validation test upgrade is also required if the version of the package changes. See https://github.com/microsoft/FluidFramework/pull/8943 as an example.

Currently, getting that update is quite cumbersome. The engineer must:

- list all the definition packages which got upgraded
- for each such package 
     - navigate to their directory
     - run `npm install` to get the type validation tooling
     - run `npm build` to get the type validation version bump which then fails because the dependent package (old version isn't installed here)
     - run `npm install` again to install the new dependency
     - run `npm build` again to finally have the proper type validation test

All these steps seem like great candidates for automation during the release process by also bumping the type validation tests. 

**If we don't want to couple these two concepts (package version + type test version), at least we should write a script to automate this process from the root of the repository in one go.**

In the meantime, we should add some more explicit and up to date instructions in the oncall playbook about how to (manually) integrate this new concept into the release process.

**Comment by anthony-murphy** [comment]
So the tooling itself already has support for a `-p` param, which stands for prepare. This should only modify the package.json, but not generate any tests, so you should in theory be able to prepare all packages, then install, and then build. the final build will generate the new tests.

However, there is another thing to consider here. We may want to exclude new test creation entirely from the build. I would, and only support modification. this would require a tool change, but would be fairly straight forward. Then after release it would be the responsibility of the releaser to generate the new test file for the old release. This is a bit more manual, but more explicit. It avoids the issue where we can't generate the new tests for a new release until after the packages have been released. so we always have a gap, where the version is bumped, but the packages are not available yet, but once the packages become available we try to pick them up. My concern with this approach is that we miss the update step. curious if others have ideas about how to improve this flow.
