### ISSUE TITLE
Updates to repo structure and release processes post 1.0

### ISSUE THREAD

**Issue by heliocliu** [microsoft/FluidFramework#8945]
This epic addresses the additional work needed to update the repo and release processes following #8007 (which is considered the baseline needed for the 1.0 release).  These items are not necessary to make the 1.0 release, but should be considered necessary for the longer-term sustainability of releases following 1.0.

## Goals
- Developers can create releases with minimal manual steps. This involves simplifying the existing release process.
- ~Developers can work easily across multiple development branches that permit different levels of breaking changes.  This involves setting up parallel dev branches for changes that are not allowed on the primary dev branch (e.g. due to the level of breaking changes permitted at any time) and the related processes and dev education to support this.  This is expected to involve creating a branch for major changes that must wait until the next major release cycle while the main branch can only make minor releases.~ Moved to pre 1.0
- Our packages are in the same repository (as opposed to the current split repos of client, server, common-definitions, etc.)
- Packages are versioned independently. Packages may be assigned to groups which are versioned in lockstep 

### Release process simplification
- [ ] #8948
- [ ] #8056
### Developers do not need to consider layers when making changes
- [ ] #8055
- [ ] #8105
### Packages are versioned independently
- [ ] #8459
- [ ] Enable reactive versioning for all packages/groups across the repo

**Comment by skylerjokiel** [comment]
Moved to ADO
