### ISSUE TITLE
Improve semantics of wrapError

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#8954]
Today, `wrapError` does this:

* Generates a new error object with a new errorType, and often a new fluidErrorCode
* Typically takes the original error's errorMessage
* The original stack is used
* A new errorInstanceId is generated, and the logs include a link between the inner (if existing) to outer
* Optionally log via `wrapErrorAndLog`

Problems here include:

* The inner error's message may contain PII or variable data, but we're stamping it on one of "our" errors. This is counter to the goals we have for our errors' messages
* Furthermore, with the deprecation of fluidErrorCode, if we preserve the incoming message we have few options for adding on a meaningful message/description of the wrapping error from our code's POV.
* Stitching together via inner/outer errorInstanceId is prohibitively difficult
* The original error object is discarded, which could hamper debugging

New plan (exact prop names TBD):

* Generate a new error object with a new errorType and message
* At runtime, stick the original error on as innerError. 
* Add a tagged telemetry prop innerErrorMessage which is the inner error's message
* Reuse errorInstanceId between the two
  * If innerError has it, use it. Otherwise generate it.
  * If not, do best effort (in try-catch) to stamp the id on the innerError as well
  * Include it in the log in the case of `wrapErrorAndLog`
* Continue to reuse the stack... Or log it as innerErrorStack?

As we go through current/new usages of `wrapError`, we can adjust this, but I think it's the right way to iterate from here.

**Comment by andre4i** [comment]
> Add a tagged telemetry prop innerErrorMessage which is the inner error's message

Are you referring to `TelemetryDataTag.UserData` or are you planning on adding a new classification?

👍 LGTM anyway

**Comment by markfields** [comment]
> Are you referring to TelemetryDataTag.UserData or are you planning on adding a new classification?

Good question, I wasn't sure so left it ambiguous :P

**Comment by markfields** [comment]
Another design point:

* If the innerError is untrusted, then also mark the wrapped error with `untrustedOrigin` (just like `normalizeError`)

This will allow us to distinguish in telemetry errors we raised ourselves v. those that come from partner code, even after being wrapped.  (see parent epic #8260)

**Comment by markfields** [comment]
I'm second-guessing about relegating inner's message to `innerErrorMessage`.  There may be 2 different use cases to consider:

1. Something like #8262 or #8151 where we are wrapping "someone else's" error to get a specific errorType
2. Something like ThrottlingWarning / SummarizerWarning, where we're forking an error (regardless of existing errorType or not) and wrapping it for a secondary purpose (in this case, ContainerWarning, which is a whole other topic).
3. ~~I'm vetoing this case until there's a hard requirement - but the other piece of the pie is where we do squash the errorType of an error of our own as it propagates out.~~

In case 1, preserving the original error is probably right.  In case 2, having a clean break with fresh message/errorType is probably right.

**Comment by markfields** [comment]
The only instance of case 2 left in the code after some current PRs is ThrottlingWarning, which is the event arg for DeltaManager's `throttled` event.  This might not warrant a general-purpose function to support it.

We actually have an instance of case 3 in here too - SummarizerWarning.  I left a comment here suggesting we get rid of it, so I'll follow up on that.

Then we'll just be left with case 1.

**Comment by markfields** [comment]
New proposal:

### retypeError for cases 2/3

This function will replace `wrapError`, and will copy over not just `message` and `stack` but also all `errorInstanceId` and telemetry props (from `getTelemetryProperties()`.  Basically, it clones the error using `newErrorFn` which yields an error with a different errorType.  No longer supports logging as well - callers should do that only if they care.  This should be used infrequently.

### normalize takes errorTypeIfNone param for case 1

e.g. for `CreateProcessingError` it will be `dataProcessingError`.  This will address #9027, and simplify/clarify the code to no longer call `normalize` in one branch and `wrapError` in another.

**Comment by markfields** [comment]
New new proposal - keeping it simple with only minor tweaks to `wrapError`:

* Reuse `errorInstanceId` as discussed above (but also leave current props for ease of transition in queries)
* Properly set `untrustedOrigin` telemetry prop, to reflect whether the original error was external, even after being normalized and/or wrapped, possibly multiple times.

As for how `wrapError` is to be used in the different cases I've been discussing...

### Case 1 (aka "wrap if unrecognized"):

* Keep one-off `wrapIfUnrecognized` function for `DataProcessingError`. See #9157 for improvements there.
* (out of scope for this issue) For other places with similar semantics (e.g. token provider try-catch), we can consider making a general helper to do the same.  But don't overload `normalizeError`.

### Case 2 (Prep the error for an API that's expecting a certain errorType)

* Start with `wrapError`
* Copy all telemetry props over
* Phase out `wrapErrorAndLog` now that `errorInstanceId` and telemetry props are re-used (and the scenario for case 2 is clearer)

### Case 3 (until it's removed, see [this issue](https://github.com/microsoft/FluidFramework/issues/8903#issuecomment-1027624711)):

* Same as Case 2
