### ISSUE TITLE
Summary telemetry cleanup to make data easier to analyze

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8965]
Based on investigation in #8963 (Summaries are large: Number of blobs in summaries is large)

**Action plan** (see whole issue history for background):
1. Add referenceSequenceNumber to fluid:telemetry:OdspDriver:uploadSummary_end event
2. Add raw blob sizes (in addition to final total payload) to above. i.e. exclude size of all metadata and encoding.
3. I'd suggest removing "uploadSummaryWithContext" event - it does not feel like it adds any value.
4. Rename summarySequenceNumber -> referenceSequenceNumber for "Summarize_end" event (to be consistent across layers).
   - if there are any other cases like that, do the same rename.
5. "GenerateSummary" event should be changed to leverage PerformanceEvent and track time to generate summary.
6. I've love to see "GenerateSummary" repeating all the props that exist on "Summarize_end" that make sense (i.e. fullTree, timeSinceLastAttempt, timeSinceLastSummary, but not refreshLatestAck)
7. If we can get number of blobs to "GenerateSummary" payload, that would be awesome too!

Other than # 2, it all seems rather simple items that we can change this month.
Maybe even # 2 is simple, if not - fee free to fork into separate issue.

**Comment by chensixx** [comment]
to clarify, for #2, is raw blob size the size of just the snapshot entries? or for each entry, we need to exclude metadata and encoding?

**Comment by chensixx** [comment]
@agarwal-navin

**Comment by agarwal-navin** [comment]
For #4, as per my understanding `summarySequenceNumber` isn't the same as `referenceSequenceNumber`. `summarySequenceNumer` is the sequenceNumber of the summaryOp as stamped by the server. `referenceSequenceNumber` of the summaryOp should be logged separately.

**Comment by vladsud** [comment]
Ah, Navin is likely right, we can scratch # 4 then.

Re # 2 - each blob has size. I'd love to see a sum of it. Naturally it will exclude all the metadata size, encoding overhead, or JSON serialization overhead. And "size" may mean different things - it may mean bytes or may mean characters (for strings). But if you trace the code, we can see that getBlobSize() that is used to populate totalBlobSize below actually calculates bytes for utf-8 strings.

That looks to be available through summaryData.summaryStats.totalBlobSize;
See IGenerateSummaryTreeResult

Looking at the code, I think summaryData.stage !== "base" case actually adds all props, so it's actually there, just not very obvious. So, I think we can scratch that too :)

**Comment by agarwal-navin** [comment]
Yes, blob size is there. Although, its worth mentioning that it is only available for nodes that are summarized. So its not a good representation of the total blob size of the summary.

I was also looking at the summary telemetry recently and have a couple of thoughts / changes I would like to make. I will probably do that separately but want to call out here;
1. The sequenceNumber in `Summarize_end` event is incorrect. It is logged as `ackNackOp.sequenceNumber` as show below:
   ```
    const telemetryProps: Record<string, number> = {
      ackWaitDuration: ackNackDuration,
      sequenceNumber: ackNackOp.sequenceNumber,
      summarySequenceNumber: ackNackOp.contents.summaryProposal.summarySequenceNumber,
    };
   ```
    However, `sequenceNumber` is also logged for (almost) all telemetry as the current sequenceNumber and this conflicts with that. We should rename the above one to `ackNackSequenceNumber` or something like that.
2. We should add the GC telemetry to the summary telemetry since we usually want to see them together. For example, I want to see for a GC run, what was the seq#, ref seq#, summary seq#, etc.

**Comment by agarwal-navin** [comment]
We log the following telemetry when a summary successfully completes:
```
fluid:telemetry:Summarizer:Running:GarbageCollection_end
fluid:telemetry:OdspDriver:uploadSummaryWithContext_end
fluid:telemetry:OdspDriver:uploadSummary_end
fluid:telemetry:Summarizer:Running:GenerateSummary
fluid:telemetry:Summarizer:Running:SummaryOp
fluid:telemetry:Summarizer:Running:Summarize_end
```
IMO, its not very apparent what the difference between `GenerateSummary`, `SummaryOp` and `Summarize_end` is. Essentially, they indicate different stages of the summary process. We should rename them to indicate that so that it becomes simpler for the person looking at telemetry (our OCEs for example) to reason about the summary process.

**Comment by vladsud** [comment]
I suggested at the top removing fluid:telemetry:OdspDriver:uploadSummaryWithContext_end.
I'd leave fluid:telemetry:OdspDriver:uploadSummary_end, as that's different layer.
Not sure about GC, but rest likely can be reorganized to be 

fluid:telemetry:Summarizer:Running:Summarize_generate
fluid:telemetry:Summarizer:Running:Summarize_Op
fluid:telemetry:Summarizer:Running:Summarize_Ack
fluid:telemetry:Summarizer:Running:Summarize_end

**Comment by agarwal-navin** [comment]
That sounds much better. Although we don't have a separate event for Ack. So, it would be:
```
fluid:telemetry:Summarizer:Running:Summarize_generate
fluid:telemetry:Summarizer:Running:Summarize_Op
fluid:telemetry:Summarizer:Running:Summarize_end
```

**Comment by chensixx** [comment]
is blobNodeCount the same with number 7? if so, it's already in the event

**Comment by agarwal-navin** [comment]
Yes, I believe is it the same.
