### ISSUE TITLE
Add telemetry to DocumentDeltaConnection reconnect attempts

### ISSUE THREAD

**Issue by znewton** [microsoft/FluidFramework#8968]
## Work Item
**Describe the outcome you expect**

#8820 allows for socket.io to do internal reconnections. Currently, the only reconnection that will happen is when downgrading to long-polling. We should add telemetry to this flow to understand how often this type of reconnection occurs.

**Approach**

> - events for reconnection attempts (and their duration / protocol)
> - Once connection is established - to log (in some form) of long polling or websocket is used.
Ideally the form telemetry takes is left to the caller, so maybe we just need hooks for each driver to be able to leverage them? Maybe not, and this layer just issuing events is fine.
> — @vladsud

**Open questions**

Should the logging happen in the shared driver-base layer or should each driver be responsible for hooking into reconnect attempt events and logging there?

**Additional context**

**Acceptance criteria**

**Comment by znewton** [comment]
This additional telemetry for understanding how often clients downgrade to long-polling won't be particularly helpful for Azure Fluid Relay since we currently have no means of collecting/viewing client telemetry other than via the E2E tests.

@vladsud feel free to take this on if you want it more urgently

**Comment by vladsud** [comment]
I'm happy to consider enabling similar workflow for ODSP (and collect this kind of data), but I'd love to hear from you first on what you learned RE user experience when using long polling. Is this something we hope users will never need to know about (in terms of end user experience)? Or something that degrades perf, and thus is a concern? And possibly needs to be incorporated into application feedback mechanisms?

#7964 tracks potential work on ODSP side. We have no plan yet on when we can take a look at it, but we will consider it as part of that item.
