### ISSUE TITLE
Summarization attempt data in telemetry is wrong

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8972]
Fotking from https://github.com/microsoft/FluidFramework/issues/8963, which has much longer thread about why having this data is importatnt.

Query:
> union Office_Fluid_FluidRuntime_Generic
| where Data_eventName == "fluid:telemetry:Summarizer:Running:GenerateSummary"
| summarize count() by Data_summarizeTotalAttempts
| render linechart 

I get only 5 attempts max, which is too low.
Cross-checking it against this query suggests that indeed data above is wrong:

> union Office_Fluid_FluidRuntime_Generic
| where Data_eventName == "fluid:telemetry:Summarizer:Running:GenerateSummary"
| summarize count() by Data_containerId
| summarize count() by count_
| render linechart  

<img width="845" alt="image" src="https://user-images.githubusercontent.com/46826984/152079080-8be04f0e-110b-4b4a-a342-34c95ac3f10b.png">

It gives me hundreds of summaries per same container session.
Data_summarizeTotalAttempts is supposed to track all attempts to summarize within a session, but it clearly does not. And we have other properties to track other counters like that:

```ts
                const summarizeProps: ITelemetryProperties = {
                    summarizeReason,
                    summarizeTotalAttempts: totalAttempts,
                    summarizeAttemptsPerPhase: attemptPerPhase,
                    summarizeAttemptPhase: attemptPhase + 1, // make everything 1-based
                    ...options,
                };
```

**Comment by vladsud** [comment]
Ah, totalAttempts is local var within trySummarize(). It is useful concept (maybe we should rename it to have clearer name), but we need global counter per summarizer session as well.
@pleath - any chance you can add it? Sorry for jamming into Feb, but stats in related bug as really bad, and we need to get to the bottom of it soon - looks like some regression from GC work affecting prod

**Comment by pleath** [comment]
Sure. I'll take it up this week. Some of what is scheduled for February is lower priority.

**Comment by pleath** [comment]
BTW, I assume you're not interested in tracking attempts that result from calls to trySummarizeOnce (onDemandSummarize, enqueueSummarize, last summary).

**Comment by vladsud** [comment]
> BTW, I assume you're not interested in tracking attempts that result from calls to trySummarizeOnce (onDemandSummarize, enqueueSummarize, last summary). Are you interested in total attempts for a given Summarizer or for all Summarizers of a given document?

Not at the moment. That said, I have a feeling we will have similar scarmble moments with Word / service-controlled summaries, so some approximation of same thing might be useful

**Comment by pleath** [comment]
Actually, if we're going to track RunningSummarizer.totalSuccessfulAttempts, then I think it makes sense to include on-demand, etc., in that count.

**Comment by pleath** [comment]
BTW, we do have Data_summaryGenTag. This is the current value of RunningSummarizer.summarizeCount, which is just the number of times a given summarizer has been asked to summarize. For the query above, the max summaryGenTag for a given summarizer that I get is 146.

**Comment by vladsud** [comment]
Ah, I thought something like that exists, but could not find it.
I think it's fine as is, but given you already started poking, can you please take a closer look to make sure names make sense? summaryGenTag  is not very descriptive of what it means.
Also, can we comment code to make sure an event lists all properties it has? It's so hard to traverse this code, as we pass generic properties through layers.
Maybe make it more type-strict, such that one can quickly and easily answer what payload fluid:telemetry:Summarizer:Running:GenerateSummary actually produces?

**Comment by pleath** [comment]
Yeah, I can change summaryGenTag to something like summarizeCount. A comment listing properties per event sounds hard to maintain, since, as you say, thinks are passed across layers. Type-strictness would be great, but I may not get to it in February.

**Comment by vladsud** [comment]
I'd say - any improvements in this space will go a long way :) If it takes you and me couple days to figure out what's available, I can only imagine how frustrated other people would be when they need to look at summary issues for the first time (OCEs)
