### ISSUE TITLE
Odsp Driver: Join Session Errors

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#9000]
- Site read-only mode
   - Expected state on the server where clients can read data but no modifications can happen e.g. during moves
 - User out of quota
   -  User can delete data/ empty recycle bin
 
Whatever we do, we must also be able to communicate error via PUSH as it can happen mid-session

**Comment by anthony-murphy** [comment]
in the load case we may want similar semantics to #5679

**Comment by marcmasmsft** [comment]
Some more details about the errors:

Both can happen during any write calls, i.e. join session, create attachment blob, post ops, post snapshot.

- ODSP will return 403 with error code "servicereadonly" when the site is in read-only mode
- ODSP will return 507 with error code "quotalimitreached" when the user is out of space

@anthony-murphy let me know if more details are needed
@GaryWilber a similar change will be needed as these errors can happen when PUSH is calling ODSP and when client is connected to PUSH

**Comment by vladsud** [comment]
we should start with clear definition of responses for both SPO & PUSH when that happens.
Sample payload from SPO would be great. I assume that will apply to APIs like summary upload, blob upload, join session.
PUSH is likely less interesting as we always go through full reconnection flow on connection / disconnect error, so as long as join session flow exposes right data, we should be fine.
