### ISSUE TITLE
Move to using ICodeDetailsLoader while ingesting code loader types from container definitions

### ISSUE THREAD

**Issue by ssimic2** [microsoft/FluidFramework#9033]
At this point we should be able to fully consume code loader types from container definitions.

1. Consume code loader types from @fluidframework/container-definitions
3. Transition FF codebase to use ICodeDetailsLoader instead of ICodeLoader.

**Comment by ssimic2** [comment]
Hey Sonali - Are you pulling out "Transition FF codebase to use ICodeDetailsLoader instead of ICodeLoader." as a separate item here ? I think we concluded we will have to wait to transition definitions.

**Comment by sdeshpande3** [comment]
> Hey @sdeshpande3 - Are you pulling out "Transition FF codebase to use ICodeDetailsLoader instead of ICodeLoader." as a separate item here ? I think we concluded we will have to wait to transition definitions.

Yes, this issue essentially captures "Transition FF codebase to use ICodeDetailsLoader instead of ICodeLoader" but this would have to wait until `driver-definitions` does not transition to start using `IContainerPackageInfo`.

**Comment by sdeshpande3** [comment]
The changes are expected to go in next branch -- release 0.59

**Comment by skylerjokiel** [comment]
Closing since it was moved to Done on the board. @sonalivdeshpande follow up with me if this is still active.
