### ISSUE TITLE
Cleanup code loader types from @fluidframework/core-interfaces

### ISSUE THREAD

**Issue by ssimic2** [microsoft/FluidFramework#9034]
After ensuring we have transitioned all partner repos to ingest code loader types @fluidframework/container-definitions, let's clean up deprecated types around @fluidframework/core-interfaces.

1. Delete fluidPackage.ts from @fluidframework/core-interface.
2. Remove remaining deprecated code loader types from @fluidframework/core-interface.

Given that reverting code around definitions would be multi-step process, let's take care of this item only when we are sure all is well in partner repos.

**Comment by sdeshpande3** [comment]
The changes are expected to go in next branch -- release 0.59
