### ISSUE TITLE
Stop always summarizing DDS (because of blob aggregation)

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9047]
Currently, we always summarize DDSs by calling `summarize` with `fullTree=true`:
https://github.com/microsoft/FluidFramework/blob/3cdb3d842456307a88ec9adc48313a5710966c16/packages/runtime/datastore/src/dataStoreRuntime.ts#L690

This was done because it was needed by blob aggregation. However, blob aggregation isn't enabled so we should stop doing this as this increases the summary size substantially.

**Comment by agarwal-navin** [comment]
@vladsud FYI.
My understanding is that we need this to saturate before we can enable blob aggregation. We can stage this change as follows:
1. Put the above piece of code behind a feature flag.
2. Put the code to enable blob aggregation behind another feature flag. Once # 1 saturates, we can enable writing blob aggregation via the second feature flag (when we decide to do it of course).

**Comment by vladsud** [comment]
I'd recommend removing this code for now. Along with disabling blob aggregation altogether (i.e. not make it possible to enable through localStorage). If we bring back blob aggregation, we will figure out how to do it safely.
Assigning to Tyler to take a look next month (we might need to rebalance closer to milestone start)
