### ISSUE TITLE
Design a way to mark blobs / trees in summary not to be included in snapshot

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9052]
Design a way to mark blobs / trees in summary not to be included in snapshot.
This capability is useful for these flows:
- Reduce snapshot payload by excluding all GC-based blobs. Such blobs are required only by summarizer and summarizer always works on top of latest summary, so correctness is not affected by storage deleting summary blobs eventually with deletion of old summaries.
- We can leverage that capability as a proxy for tombstoning deleted data stores for GC

Related issues:
- https://github.com/microsoft/FluidFramework/issues/4590
- https://github.com/microsoft/FluidFramework/issues/6371
- Design on deleting / tombstoning deleted data stores on GC

**Comment by vladsud** [comment]
I think that would not be sufficient for GC tombstones, or rather any tombstone solution will need more tools.
Let's look at scenario:
1. Some violation happens (or it's part of main flow) and data store is loaded that is marked that way by client A
2. This client mutates it by issuing ops.
3. Summarizer summarizes it.
4. Over time, original summary with original blobs is deleted by ODSP.

A client that follows handle to load that data store (because it's now part of graph) needs to
- Refresh its knowledge of latest snapshot
- Load snapshot tree + relevant blobs
- process all ops on top of it till latest seq number (that one we almost have, as clients keep ops around).

Reason for this flow - a client may be offline for a while, so it can't assume it can use original summary tree to load missing blobs from it by the time it sees an op for such data store.

Alternative and simpler (but more impactful on COGS) solution - we load all such blobs in one http request that follows loading summary. Such that each client has these blobs to allow existing data store delay-loading logic to work. But that has complication - snapshot caching, that would need to be adjusted for this flow. I'd recommend not to go that route.

**Comment by vladsud** [comment]
We still need this functionality for gc blobs, so I want to keep it in the list of things we are tracking but using it for tombstones is not easy - see above.

**Comment by vladsud** [comment]
And for trees, should unreferenced automatically mean - not include into snapshot?
Is all the usage the same, where we can use unreferenced and "not bring in snapshot" as one and the same (at some point in future)?

**Comment by vladsud** [comment]
That issue is a peer of https://github.com/microsoft/FluidFramework/issues/6371

**Comment by NicholasCouri** [comment]
Tracked by https://dev.azure.com/fluidframework/internal/_workitems/edit/418
