### ISSUE TITLE
Lint errors in connectionManager.spec.ts

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9072]
CI loop is failing with the following lint errors. Looks like these tests were added in https://github.com/microsoft/FluidFramework/pull/8964.

@fluidframework/container-loader: /mnt/vss/_work/1/s/packages/loader/container-loader/src/test/connectionManager.spec.ts
@fluidframework/container-loader:    72:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:    74:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:    86:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:    90:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:   100:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:   104:15  error  Multiple spaces found before '('  no-multi-spaces

**Comment by agarwal-navin** [comment]
@markfields FYI

**Comment by markfields** [comment]
@tylerbutler - Looks like your lint changes and my PR conflicted.  Your checks must have run before my PR merged. https://dev.azure.com/fluidframework/internal/_build?definitionId=12

I can make a quick fix

**Comment by tylerbutler** [comment]
@markfields Sorry about that! Please let me know if I can help with anything.
