### ISSUE TITLE
Some lint rules are not working

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#9093]
This is probably a bug in eslint or a plugin, but I've noticed at least two rules that are not being enforced properly in the code.  For these two I can paste in the "Incorrect" code examples from the docs and it builds just fine.  They are both enabled in the eslint config, as far as I can tell.

[typescript-eslint/promise-function-async.md at main · typescript-eslint/typescript-eslint (github.com)](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/promise-function-async.md)
[typescript-eslint/strict-boolean-expressions.md at main · typescript-eslint/typescript-eslint (github.com)](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md)

**Comment by markfields** [comment]
Assigning to March milestone but ideally we can get to the bottom of this sooner than that.

**Comment by markfields** [comment]
Closing this - I was looking at eslint7.js, which is no longer used. These rules are just not enabled.  Following up in https://github.com/microsoft/FluidFramework/issues/9082

**Comment by tylerbutler** [comment]
@ChumpChief Was this addressed by #9135? Are there other rules that need to be re-enabled other than unbound-method (#9082)?

**Comment by ChumpChief** [comment]
I'd probably close this one since based on @markfields description I think he was just expecting eslint7 to be enabled.  Maybe open a new epic to survey our rules, add missing rules that are worth having, and unify them.

**Comment by tylerbutler** [comment]
The remaining work is tracked by #9501, so closing this.
