### ISSUE TITLE
Aliases should be considered only when `getRootDataStore` API is used

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9109]
The `getDataStore` function in `dataStores.ts` always checks whether the given id is an alias. However, we should only do this if the data stores is requested via the `getRootDataStore` API since that should be only entry point for aliased data stores. All other data stores should be retrieved via their handles.

However, currently root data stores can still be requested via the `request` / `resolveHandle` APIs so we need to handle those scenarios.

**Comment by andre4i** [comment]
https://dev.azure.com/fluidframework/internal/_workitems/edit/358

**Comment by andre4i** [comment]
closed as duplicate ^
