### ISSUE TITLE
Move odsp-driver public contracts to odsp-driver-definitions

### ISSUE THREAD

**Issue by tronguye** [microsoft/FluidFramework#9142]
# Action items
1. Rename odsp-driver-definitions to clearly indicate it tracks only interfaces that have to stay compatible across versions, i.e. it tracks what is consumed and produced by driver factory
2. Create another package for all other contracts that driver has and move definitions there.
3. (Optional) Break driver into two packages, according to above split.

# Earlier discussion

## Work Item
**Describe the outcome you expect**

Allow consumers to import the contracts for odsp-driver from odsp-driver-definitions. This would allow for consumers to refer to the types such as `OdspFluidDataStoreLocator` without taking in the transitive dependencies of odsp-driver.

Additionally, since odsp-driver-dependencies has a smaller footprint, its package version will remain more stable than odsp-driver. Consumers will not have to upgrade as frequently with this proposed change.

**Approach**

Move contractsPublic from odsp-driver into odsp-driver-definitions. Change all references to these files to import from odsp-driver-definitions.

**Open questions**

N/A

**Additional context**

FFX's host-ux package is currently taking dependency on odsp-driver. When hosts upgrade host-ux, they also need to bump all the transitive dependencies which is cumbersome, and can possibly cause build errors or duplicate dependencies in their bundles

**Acceptance criteria**

Move contractsPublic from odsp-driver into odsp-driver-definitions. Change all references to these files to import from odsp-driver-definitions.

Bump odsp-driver-definitions and odsp-driver versions

**Comment by vladsud** [comment]
At the moment, odsp-driver-definitions tracks all the types that must have higher compat requirements due to being used by driver factory. I explicitly did not put any more stuff there.
I'd say that we likely want to rename it and keep this higher bar, and have separate package for other definitions, as well as split driver (actual code) into two packages - factory and all the rest (uri resolvers, etc.).

**Comment by tronguye** [comment]
> At the moment, odsp-driver-definitions tracks all the types that must have higher compat requirements due to being used by driver factory. I explicitly did not put any more stuff there. I'd say that we likely want to rename it and keep this higher bar, and have separate package for other definitions, as well as split driver (actual code) into two packages - factory and all the rest (uri resolvers, etc.).

Hey @vladsud I think that proposed change makes a lot of sense! Should this issue be edited to capture that split/rename? For my own curiosity, what do you mean exactly by "higher compat requirements?"

**Comment by vladsud** [comment]
We promise that one version driver factory can be used with a different version of loader or container runtime.
This applies only to driver factory (and any objects that it produces), but it's not true for other parts of driver package, like URI resolver.
I.e. URI resolver is bundled into host app and ships with it (along with loader), but host app may dynamically (or statically) run against another version of driver factory.

**Comment by vladsud** [comment]
I've updated description a bit.
