### ISSUE TITLE
Re-evaluate op chunking algorithm

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9154]
Today, we break ops with content larger than 16K into smaller chunks (ops).
This feature was added before batches existed, and we were hitting 1Mb limits as described in other bugs (see #9023).

With addition of batches, and further switching to batching being by default at JS turn, we can expect most ops to be in a batch. I.e. large op be part of batch that has at least one other op (in a batch) and requirement (in current system) to send all of these ops (including chunks of big op) as one socket.io message.

As result, chunking does not solve the problem with 1Mb limit anymore, and actually does the opposite - it makes payload much larger, as chunking (due to escaping) causes payload to grow. As result, we hit 1Mb limit much sooner.

We can do one of the following to address these problems:
1. Raise chunking limit (but below 1Mb).
   - Does not help address the problem when it's above limit, but reduce overhead if it's below limit
2. Raise it above 1Mb. This is essentially similar to no limit, as any message above limit will not go through.
3. Remove limit altogether
4. Change limit to something below 1Mb (let's say 512Kb) and close container when we breach the limit.
   - the assumption here is that that way we will catch most cases that result in batch being over 1Mb in size, while not being too aggressive (i.e., not having too many false positives - when we close container, but batch could have gone through because collectively all ops in a batch are below the limit).

I like # 4 from above as it closes the gap of infinite retries that we have when we hit 1Mb, at the same time allows a bit smaller payload not to grow due to overhead, and thus go through. 

We can revisit this area once batching limits are solved. That said, I expect us to always have limits to both op size and batch size, so I do not think that direction actually against long term vision.

**Comment by andre4i** [comment]
Keeping this open just in order to deal with the possibility of fallout from the experiment.

**Comment by andre4i** [comment]
There are still no events in Kusto with the `OpTooLarge` message.

**Comment by vladsud** [comment]
Whiteboard is on 0.55, and I believe they are the one hitting these issues the most, so I think we are still couple months out?
I see 4 hits in 0.58.1001 :) So maybe it's coming, but I'd ping them as clearly, they do not have bits required to mitigate

> union Office_Fluid_FluidRuntime_*
| where Data_hostScenarioName contains "Whiteboard"
| summarize count() by Data_runtimeVersion
| where count_ > 1000

| runtimeVersion | count |
|-|-|
| 0.55.4 | 8,513,066 |
| 0.54.1 | 11,165,181 |
| | 36,103,375 |

**Comment by vladsud** [comment]
There is total 10 events in 30 days. Closing
