### ISSUE TITLE
Update documentation for connection APIs

### ISSUE THREAD

**Issue by scottn12** [microsoft/FluidFramework#9170]
We will create well documentation to demonstrate how a developer can use the new `Container.connect()` and `Container.disconnect()` functions in their applications. Additionally, old documentation for previous code patterns will be updated.

Context: https://github.com/microsoft/FluidFramework/pull/9439

**Comment by scottn12** [comment]
@tylerbutler, what do you think is the best spot for this documentation? It won't require very much explanation/code to demonstrate, so it could certainly fit into an article. I believe the wiki is intended for articles related to contributing to FF, so I'm thinking this is better suited for ff.com?

**Comment by tylerbutler** [comment]
@scottn12 Sorry for the delay! I agree that for.com is the best place for this. We have a section on the container lifecycle already: https://fluidframework.com/docs/build/containers/#container-lifecycle-and-manipulation

Could you work it in there? Or as another subsection in that article.

**Comment by scottn12** [comment]
This looks like a great spot, thanks!
