### ISSUE TITLE
Ops cache is slower than storage (at the tail of distribution)!

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9177]
There is something really fishy RE how ops cache works.
This is demonstrated by this query:
 
Office_Fluid_FluidRuntime_Performance
| where Data_eventName == "fluid:telemetry:OdspDriver:CacheOpsUsed"
| where Data_length < 10
| summarize percentile(Data_duration, 95)

It gives me these percentiles:
90 - 1.1s
95 - 1.9s
99 - 5.4s

That's how long it takes to get result back from single request (it can actually be 1-2 requests, with average around 1.1 - 1.2 requests per telemetry event). That's too slow!

For comparison - fluid:telemetry:OdspDriver:OpsFetch event tracks requests to actual storage, and it has these percentiles:
90 - 1.2s
95 - 1.7s
99 - 3.2s

So, requests to storage are faster than talking to local cache!

OdspDeltaStorageWithCache.fetchMessages() waits that long before we issue request to storage, so it slows down us getting up to date. This is done so that if we have everything in cache, we can avoid network call. With this kind of perf, we might want to revisit this decision.
Note that 75th percentile is 262, so we might wait just a bit (like 300-500ms) and then let storage call go through in parallel to cache call running, to avoid such slowdown in whole sequence.

This also slows down container boot - see https://github.com/microsoft/FluidFramework/issues/8931.
So, this is rather important item to get right.
We should start with understanding why cache is so slow!

**Comment by vladsud** [comment]
@Zlatkovsky - FYI, I think we need a bug on your side to look deeper into it. Numbers are pretty bad, and they impact boot & getting connected.

@christiango, @markfields - FYI.

**Comment by vladsud** [comment]
For whatever reason, getting snapshot is faster at 99th percentile:

Office_Fluid_FluidRuntime_Performance
| where Data_eventName contains "fluid:telemetry:OdspDriver:ObtainSnapshot_end"
| summarize percentile(Data_duration, 99) by Data_method

method = cache gives me 585ms.

Given that we chunk ops and each op should never be over 32K, 10 ops payload should not be larger than snapshot (on average)

**Comment by vladsud** [comment]
Just realized that we do not report numbers for all invocations, so data is actually skewed toward tail of the curve:

```ts
        if (messages.length > 0 || duration > 1000) {
            this.logger.sendPerformanceEvent({
                eventName: "CacheOpsUsed",
                from,
                to,
                length: messages.length,
                duration,
            });
        }
``` 

We also have extra cache requests due to overlapping requests (that does not affect boot of perf, but adds more pressure to indexDb). instead of today's modes of "cache only" and "cache + storage" we should switch to "cache only" & "storage only" and push responsibility into Container / DeltaManager level to control any parallelism, if needed.
I'd think that we should never need to hit cache & storage at the same time, as we get all the ops from cache in boot, so all other request that come in should go directly to storage. But data suggests we do get ops from cache, and looking at individual sessions - this looks like due to user keeping multiple tabs opened with same file (i.e. I can see in a session that we just got cached ops, and request a second later on connection gives me more ops, suggesting that another client on same box just pushed ops to cache).

**Comment by Zlatkovsky** [comment]
@vladsud , I just had an interesting repro that happens consistently with a specific (somewhat complex, but not unreasonable) document, on my rather fast machine:

![image](https://user-images.githubusercontent.com/2230453/155790656-3d42ca05-c307-4c82-a263-90ee71c79d4d.png)

The `ObtainSnapshot` is fast -- so fast that its label doesn't fit. It's under 17ms, with its corresponding `FluidCacheAccess` taking 15ms (by contrast the TreesLatest that it kicks off takes nearly a second). So that's great.

But then the `GetDeltas` activity takes a really long time (1.53s). Of that, 1.21s are in waiting for the FluidCacheAccess for the Deltas, which seems inexplicably slow. Only after that it makes a network call to the OpStream (which takes the remaining 300+ms).

Is this the sort of thing that you're trying to probe in this bug?

**Comment by Zlatkovsky** [comment]
@vladsud , I didn't have logging turned when I captured that particular profile, but I just re-ran the scenario with logging and got a very similar result. If it helps:
* docId: `HT8xqcoB7q16yQ9FZu4fhX1m3TVDz9cabuiGV2nt3yA%3D`
* hostCorrelationId: `49faad21-c0ca-4f35-bca5-0c5d934b3719`
 
![image](https://user-images.githubusercontent.com/2230453/155793441-48179a0d-8248-4a86-b787-399634f0fcb8.png)

Let me know if you want me to share the specific document with you

**Comment by vladsud** [comment]
Yes, that's the core of the problem. I'll use this issue to figure out how to optimize it on our end (add parallelism), but I think you need to take a look into why it takes that long.

Note that boot is in particular problematic, and we do not have good solution on our side. That's because 
- We do want to apply ops that this client observed in the past before we render. There is really big push back from users if they load old snapshot and do not see their own changes they made in previous session right away - they consider it data loss.
- But at the same time, we do not want to wait for storage call to get latest ops, as usually that's slow. We can do parallel request to cache and storage, but that to some extent defeats the purpose of cache, which was supposed to give us quick access to data.

So, I think we need to better understand why reading ops from cache is so slow. We do not have good data here (like size of that payload) to have any theories, we only know how many requests we made to cache, but in majority cases that's just one request, and it's slow.

**Comment by vladsud** [comment]
some notes from FRS folks on same subject in https://github.com/microsoft/FluidFramework/pull/9307

**Comment by vladsud** [comment]
Tracked in ADO: https://dev.azure.com/fluidframework/internal/_workitems/edit/952
