### ISSUE TITLE
"Post API should not be called when in read-only mode" error in telemetry

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9183]
Office_Fluid_FluidRuntime_Error
| where Event_Time > ago(7d)
| where Data_eventName == "fluid:telemetry:Container:ContainerWarning"
| where Data_error == "Post API should not be called when in read-only mode"
| summarize count() by Data_loaderVersion, Data_error

I do not know where this error comes from (I assume from ODSP?) and I'm not sure what it means.
It's not new (I see errors in 0.47, 0.52), so no urgency here, but would be great to get to the bottom of it (and ideally do something so this error is gone one way or another).

**Comment by markfields** [comment]
Sounds like a Scriptor issue.  Sergey (can't find his GH alias) said this in an internal conversation about this error:

> The error by itself is 'by design', bug is that model shouldn't be in read-only mode.

I will mention this issue in #8260 as a case study to make sure it gets bucketed properly as "probably not ours"
