### ISSUE TITLE
fluid:telemetry:DeltaManager:OpenBatchOnDisconnect

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9184]
Office_Fluid_FluidRuntime_Error
| where Event_Time > ago(7d)
| where Data_eventName == "fluid:telemetry:DeltaManager:OpenBatchOnDisconnect"
| summarize count() by Data_loaderVersion, Data_error

I think I was the one who added this error logging.
We should define if this is normal supported flow or not. And react according to it (i.e., either remove this error or figure out why we are getting to this state).

**Comment by andre4i** [comment]
This error has turned into a regular telemetry event with https://github.com/microsoft/FluidFramework/pull/8833 as it seemed to be part of the normal flow. I will add a test to persist the assumption.
