### ISSUE TITLE
fluid:telemetry:DeltaManager:DeltaConnectionFailureToConnect

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9185]
This is not really an error, so I'd love to see it gone from error table.
When I added logNetworkFailure() long time ago, I assume that we can reliably detect offline vs. online.
But there is no way to do it in debugger, so I think we should stop trying and just put these logs to generic table.
I.e. remove dependency on newEvent.online.
I'm not sure about canRetryOnError(error) check. Looking at actual data in telemetry, it's never false, but there are some cases where it's undefined, which is equivalent to false. But counts are so tiny, that I probably do not care about seeing these in error table - they will show up through other events in error table.

**Comment by markfields** [comment]
canRetry is only undefined for old loader (47 and before).  In the current code if canRetry is not true the container is closed and the error is thrown, so that's why it's almost always true here.
