### ISSUE TITLE
Running stress tests on tinylicious results in many NoJoinOp errors

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#9188]
These risk hiding other errors that would occur after connection.

start tinylicious, then do:
\packages\test\test-service-load>npm run start -- -d tinylicious

**Comment by anthony-murphy** [comment]
we may want to get this running in our CI loop to keep tabs on tinylicious

**Comment by vladsud** [comment]
Not sure if this is still active, but worth pointing out that FRS hit the same (see https://github.com/microsoft/FluidFramework/issues/9699) and it sounds like issue is in enabling compression at websocket layer.
Disabling it brings down P50, P95 down substantially (for op roundtrip times - P95 by 10x).

If I remember it correctly, Gary also run experiment with compression on socket.io level in the past and had somewhat similar bad results (there were a bunch of discussions about it on internet, and I'm not mistaken - socket.io had to revert to compression being off by default in some version and later on provided some fixes in this domain, but we never retried experiment).

**Comment by anthony-murphy** [comment]
we have tinylicious stress running in the CI loop and have for a while. not seeing these any more:
https://dev.azure.com/fluidframework/internal/_build/results?buildId=72371&view=logs&j=5d40b943-5a8e-529c-ed4b-95198832abfc&t=fb8cf0ae-41a8-58f6-d156-329de70d0970

 i think we can close this
