### ISSUE TITLE
Replace Moniker Dependency

### ISSUE THREAD

**Issue by jsnoyes** [microsoft/FluidFramework#9203]
## Describe the bug
A very old, unlicensed package named Moniker is used in several places inside of Fluid Framework. Since the package is unlicensed, it is legally not considered open source. Businesses that release products using the unlicensed library could be at risk legally. 

The package appears to only be used in a few non-production locations inside of Fluid Framework, but it seems like a lot of risk for little gain since Moniker is just used to generate random names for testing scenarios.

Moniker's repo's last activity was 11 years ago and there is an un-resolved issue open since 2014 asking for a license to be added. So, we won't be getting a license for it.

I haven't researched a proper alternative, but I assume there are plenty of properly licensed alternatives to Moniker.

Package:
https://www.npmjs.com/package/moniker/v/0.1.2 

Dependency in an app consuming Fluid:
"@fluidframework/server-lambdas-driver@^0.1034.0":
  dependencies:
    moniker "^0.1.2"

"@fluidframework/server-memory-orderer@^0.1034.0":
  dependencies:
    moniker "^0.1.2"

### To Reproduce
1. Create a new project.
2. run "npm i @fluidframework/local-driver"
3. Open package-lock.json
4. See moniker was included in the dependencies.

### Expected behavior
Fluid's included dependencies only contain properly licensed packages to avoid putting consumers at legal risk by using Fluid.

**Comment by ChumpChief** [comment]
We already use `sillyname` elsewhere in the repo, which is probably a fine replacement:
server\routerlicious\packages\services-client\src\generateNames.ts
server\routerlicious\packages\services-utils\src\generateNames.ts
