### ISSUE TITLE
Attach should use summaries

### ISSUE THREAD

**Issue by scarlettjlee** [microsoft/FluidFramework#9227]
IAttachMessage and CreateChildSummarizerNodeParam have ITree properties which should be changed to ISummaryTree instead (also it's confusing that something named "snapshot" is not ISnapshotTree). There are already some usages where conversions to and from summaries are used to create and consume attach messages so that can be avoided. This will have to be done in at least two stages (read first, then write behind feature gate) since it crosses layers. 

convertToSummaryTree and convertToSummaryTreeWithStats could be removed after this change (and #8997), if ITree is removed entirely and not only isolated further.

**Comment by vladsud** [comment]
If I'm not mistaken, IAttachMessage is part of file format, i.e. that's the format of data showing up on the wire.
If so, there is no way to get rid of it. We could make new code path that will use different format, but unfortunately, we have to be able to open old files, so there is no way to remove it completely from code base anymore.

That said, ideally, all the code that "summarizes" content (in wide definition of this term. i.e. including generateAttachMessage() flow) should use summary interfaces and only summary interfaces/terms, and we would convert to whatever wire format we need right before sending data and right after receiving it (though I think on receiving side we always expect it on snapshot format, and that's what it is, so no conversion is expected).

It would be great to fix typing here as part of this work:
```ts
        private readonly submitAttachFn: (attachContent: any) => void, 
```

**Comment by scarlettjlee** [comment]
From talking to Tony and Navin, we could start only writing in new format, but we'd need to be able to also read from file in old format forever.

**Comment by vladsud** [comment]
Yep. That said, it's worth calling out one thing: for normal summary / snapshot flows, service is the one who accepts summary and converts it to snapshot. Client is not involved here and expects snapshots on all load paths.
With attachment flow of objects (data stores, DDSs) to live container, we write in some format and have to consume back same format. I believe (very briefly looking at it) that it's in snapshot format, i.e. exactly what most of our loading code expects. Changing it to something else will results in extra conversion on load. If so, I'd rather keep it as is (on the wire), and make any changes in generation code path, i.e. generate summaries, but make sure we convert them to snapshot before sending an op, i.e. keeping existing file format unchanged.

Note that I really want to get rid of all of the attachment flow. I have a plan in my head, but I'm waiting for Andrei's changes with alias to settle in and be non-conditional (i.e. remove all feature gates) before we can chat about any plan here.
So maybe we should do nothing here for now? :) I can share more thoughts on that (I think I did somewhere, can open new EPIC as I'll have to do it either way soon)

**Comment by vladsud** [comment]
Tracked in ADO - closing
