### ISSUE TITLE
Usage pattern for generating URLs to a data store in absence of absolutePath

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9235]
There are scenarios where an app wants to generate a URL to a data store. For example:
- A data store created in a document needs to be shared with an external app.
- A data store is copy-pasted in the same document.

Currently, this is implemented by most apps by getting the URL of the data store via `handle.absolutePath` and calling `getAbsoluteUrl` with the URL on the data store context / container runtime or container. On loading, this URL is routed via the loader, container and container runtime  which loads the data store.

`absolutePath` is deprecated and we are moving towards using handles. So, we need to provide recommended patterns for the above scenarios. This is one of the existing usages that is blocking the removal of `absolutePath` from handles (https://github.com/microsoft/FluidFramework/issues/8271).

**Comment by agarwal-navin** [comment]
@anthony-murphy @vladsud @leeviana There have been scattered conversation about this for some time. I created this issue so we can discuss this in one place and come to a conclusion.

**Comment by agarwal-navin** [comment]
@ssimic2 FYI as this is one of the usages blocking removal of https://github.com/microsoft/FluidFramework/issues/8271

**Comment by vladsud** [comment]
The right long-term direction - not provide this functionality at all. Internal routing (handles) should stay internal, and how it's done (organization of paths) should not be exposed to API surface. There are two possible sub-solutions here for developers:
1. All external requests to go through a redirection. I.e., containerPath/localPath/Tail?queryArgs external request maps to reading a key "localPath" from some root-y map, that points to a handle. Once resolved, app can interpret /Tail?QueryArgs however it wants, including passing it to the resolved object.
   - We can support strong & weak handles to ensure that app has control over lifetime of such links.
2. Applicaiton implements its own handling or external URIs that is not tied to how internal routing is done. We could make ContainerRuntime.getDataStore() public to facilitate that.
   - That said, I really want to hide internal IDs from API surface (see https://github.com/microsoft/FluidFramework/pull/8168). So I think direction here would involve app layer to assigning their own ID system to data stores and their own management of resolution logic. Which is basically equivalent / can be achieved only through # 1.

The reason for this long-term solution - we have to ensure that our API surface does not allow wrongdoing. If we expose internal paths and ability to resolve them, then it's trivial to build a system that is incorrect from GC perspective. And while it's a problem for the app, it makes it very hard for us to reason about system and if we have GC bugs, and thus quickly react to issues, and thus have much more chances to lose user data. We want API that is sealed and does not allow wrongdoing.

What blocks app (FFX container) from implementing this direction?
There are obviously some small missing building blocks from our side (like weak handles, ability to GC such map of handles not to grow infinitely), ability to compare handles (not to create duplicate entries in such map), but they are very easy to fill in if there is actually a desire to solve this problem.

**Comment by vladsud** [comment]
I'll add that it's useful exercise to compare what we are building to "traditional software engineering", and clearly articular where we are different, where we are not. I'll argue that there are only two key angles that are unique to Fluid:
- eventual consistency of data
- serializability of in-memory state and ability to rehydrate it back on container load.

When it comes to creating links between in-memory objects, Fluid should not be involved other than providing serializability of those links (handles) within container boundaries. How application exposes parts of itself / its own programming model to external world are not really Fluid core layer to solve. Solutions in this space should be the same if Fluid was not in the picture.

**Comment by leeviana** [comment]
Option 1 seems like it would require a singleton or container handler, both patterns that we avoid. It also adds more dependencies from component -> container implementation since that means that at the very least a component would need to go through a global root component/DI service, otherwise creation/references would not function. So we'd need something like a base root component (we've discussed doing this before) for all containers to use. However, this seems in contention with the fact I think that data object and other handler systems also provide their own "creation/generation" APIs. Also for back compat reasons, we would always still need to be able to fall back to the old URL path routing system since there's no way to guarentee that all runtime attached references get transferred to some root component DDS.

Option 2 is application specific and the whole point of the loop stuff is that it's not application specific and can break application boundaries. We are aligning around URLs and content types being this routing system and have no plans on asking hosts/internet to implement a competitor routing system to URI/URLs. I actually thought one of the core Fluid principles was that "it works like the internet", i.e. had URI routing throughout and all pieces. If this is no longer a Fluid principle then we should remove all the URL resolver/loader.request() handling from the fluid system and put them into the base container layer.

**Comment by vladsud** [comment]
It has to be singleton from implementation perspective, it does not have to be singleton from API perspective.
As everywhere else, components that need access to some capability should ask for it at construction time and consult with such object later on. I.e., pass around IGlobalUriGenerator implements IFluidLoadable.
Yes, it adds back compat concerns. 
I do not think their own "creation/generation" question is relevant here. In a sense - if we were not talking about Fluid, but a general app, passing arguments around (and though layers on as needed bases) would not be a problem we need to discuss. Fluid is no different, it only adds requirement / complication of serializability of Fluid graph.

One thing to note is that once we have channel unifications (and thus ability to have child data stores), I think it's fine to provide a way for data store to always have access to parent object, and thus ask any such question to it, without a need to store explicitly pointer to parent. We can consider exposing something like that now, where parent (for now) would be some root data store or container runtime, but with an eye to a future where child-parent relationship is a tree. That way objects in the system can always reach parent without need to store a reference to it. And app decides (through creation) how data store graph looks like, and who is root (there might be multiple roots) that provide key capabilities to all objects underneath.

I'm not sure I follow application specific note. Maybe what we want to say - it's FCL specific, and FDL is not the right place for it? It can still be shared across all scenarios that are built on top of FCL, and FDL may not have notion of such capability. It's layering, and we are free to add layers as we sit fit, FDL does not have to implement something that can be done as a separate layer. "it works like the internet" - not really, FDL (aka FF) is all about data management only. That shift happened when we went OSS, all component and higher-level constructs (as well as any O365 constructs) are pushed out. FF is all about data management only.
Request pattern was a mistake IMHO. I compare Fluid container to a service, with container runtime being front-end and exposing all the guts of that service to whoever is willing to ask for it. It's a wrong model - it should be moderated by app and expose only very small subset of guts it sees fit.

**Comment by leeviana** [comment]
We are aligning on a datastoreservice right now, but the datastoreservice (or any dependency injected layer) has no connection with a particular component/DDS at the moment. We'd need to tightly couple a datastoreservice to a particular root component implementation. This could be put on our future plans and made to aligns with other similar areas like collection management.

We'd essentially be moving the whole request layer into our ecosystem, like you said. I don't particularly have a preference, I just hope that all capabilities can be functional in one place. The current system has a semi-functional request layer in the framework which leads to some confusion about ownership. If we want to move it to a different layer/rewrite it, it'll require some work and funding to happen.

**Comment by leeviana** [comment]
not stale
