### ISSUE TITLE
Tinylicious end to end test error: ResolveRefError

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#9238]
Seeing errors in our tinylicious end to end test runs:
```
let buildId = "51993";
database("Office Fluid Test").office_fluid_ffautomation_error
| where Data_buildId == buildId and Data_driverType == "tinylicious" and Data_error contains "ResolveRefError"
| project Data_testName, Data_error, Data_stack
| limit 1
```

Data_testName | Data_error | Data_stack
-- | -- | --
Detached Container compat N-1 - new loader can create DDS in detached container and attach / update it | {"code":"ResolveRefError","data":{"ref":"be291361-9df1-4db2-8281-211bb0b8cf8c"},"caller":"git.log","message":"Could not resolve reference \"be291361-9df1-4db2-8281-211bb0b8cf8c\"."} | Error at Object.createGenericNetworkError (/mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/node_modules/.legacy/0.57.0-51086/node_modules/@fluidframework/driver-utils/dist/network.js:109:12) at createR11sNetworkError (/mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/node_modules/.legacy/0.57.0-51086/node_modules/@fluidframework/routerlicious-driver/dist/errorUtils.js:34:35) at Object.throwR11sNetworkError (/mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/node_modules/.legacy/0.57.0-51086/node_modules/@fluidframework/routerlicious-driver/dist/errorUtils.js:39:26) at RouterliciousStorageRestWrapper.request (/mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/node_modules/.legacy/0.57.0-51086/node_modules/@fluidframework/routerlicious-driver/dist/restWrapper.js:72:22) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async Function.timedExecAsync (/mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/node_modules/.legacy/0.57.0-51086/node_modules/@fluidframework/telemetry-utils/dist/logger.js:334:25) at async ShreddedSummaryDocumentStorageService.getVersions (/mnt/vss/_work/1/test/node_modules/@fluidframework/test-version-utils/node_modules/.legacy/0.57.0-51086/node_modules/@fluidframework/routerlicious-driver/dist/shreddedSummaryDocumentStorageService.js:40:25) at async Object.runWithRetry (/mnt/vss/_work/1/test/node_modules/@fluidframework/driver-utils/dist/runWithRetry.js:20:22) at async Container.getVersion (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-loader/dist/container.js:703:26) at async Container.fetchSnapshotTree (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-loader/dist/container.js:1209:25) at async Container.load (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-loader/dist/container.js:749:41)

**Comment by curtisman** [comment]
#11189 has reenabled that task since 7/21, and still don't see this error since then.  Closing this for now.
