### ISSUE TITLE
Remove IDocumentStorageService.write

### ISSUE THREAD

**Issue by scarlettjlee** [microsoft/FluidFramework#9250]
This is no longer used and causes another reference to ITree which we want to eliminate. This probably doesn't need to be first deprecated.

**Comment by vladsud** [comment]
Usually, when we remove APIs, we first mark them deprecated, and then remove after some time.
I'd suggest first to create a draft PR that removes all the usage from the repo to access (or make it easier to inspect) couple things:
- Who actually implements it property. For example, OdspDocumentStorageService does not implement it (it throws). While ShreddedSummaryDocumentStorageService & ShreddedSummaryDocumentStorageService do.
- If there are any calls from the runtime code to this API (there should not any, as our main driver is odsp).

Please note that definition of IDocumentStorageService comes from @fluidframework/driver-definitions package which is not build as part of client mono-repo. It comes from earlier build (and published to npm) package.
One can either change version directly code (compiled .js files) in node_modules to find all the places where client code might be calling it, or better - link definition mono-repo with client mono-repo to do same validation.

Once we have full picture, we can proceed with changes via these steps:
1. (Possibly optional, need to check) deprecate write() method.
2. Remove method from IDocumentStorageService
3. Consumer latest version of @fluidframework/driver-definitions and make final changes in client mono-repo.

This is a bit involved task (even though pretty mechanical and trivial), but it's nice in a sense of understanding how builds and mono-repos work.
