### ISSUE TITLE
Odsp Driver: Stop using access_token query string

### ISSUE THREAD

**Issue by marcmasmsft** [microsoft/FluidFramework#9266]
We shouldn't use access_token when making calls to ODSP; tokens should be passed via the regular auth header instead.

In most cases (all reads and small writes where the body doesn't exceed 80KB), ump can be used to prevent an extra OPTIONS call.

Based on conversation, that likely includes these two flows:
- file creation, and using either ump path for small summaries, but using existing flow (or one with headers/OPTIONS call) for larger summaries
- for blob read, investigate if POST/ump call can be cachable by browsers. If the answer is no, then we should either not do anything, or go back to headers / OPTIONS call.

**Comment by vladsud** [comment]
It would be great to provide some info on why it's not advised, given that URI itself (other than domain name) are encrypted on the wire (when using https). Is the issue here browser history?
And if this is a policy, why such support exists in SPO?

**Comment by vladsud** [comment]
@jatgarg , can you please check if we have recovery path for create new if payload is bigger than 80K? Do we capture that in telemetry?

**Comment by jatgarg** [comment]
https://dev.azure.com/fluidframework/internal/_workitems/edit/237
