### ISSUE TITLE
The rootiness of a data store is not updated correctly for aliased data stores

### ISSUE THREAD

**Issue by tyler-cai-microsoft** [microsoft/FluidFramework#9286]
When a data store is aliased, it is marked as root by calling `setRoot` on the data store context which updates its `isRootDataStore` property. However, the following places still return the value from the initial snapshot details of the data store context:
- `isRoot()` that is used by garbage collection to determine which data stores are root and should be marked referenced.
- On summarizing a data store via `summarizeInternal` method.

Aliased data stores are created with `isRootDataStore` initially false and after aliasing, the `isRootDataStore` will remain false in the initial snapshot.
Find and fix any other isRootDataStore inconsistencies.

**Comment by agarwal-navin** [comment]
@andre4i FYI
