### ISSUE TITLE
Consider removing `summarizingError` event 

### ISSUE THREAD

**Issue by sonalivdeshpande** [microsoft/FluidFramework#9290]
Context: https://github.com/microsoft/FluidFramework/pull/9275/files#r817128519

**Comment by markfields** [comment]
I spent some more time looking at this code.  I think until it is removed, I'm going to revert the part of the change linked above, such that the Summarizer will raise the summarizingError event (this is the non-interactive client), and then the summaryManager can log about it (this is in the interactive client).  Not sure who is looking at these logs, but there's no reason to move this one at this time.

Stepping back - I presume the purpose of the event is for the summarizing client to notify the user's client when something goes awry.  This seems worthwhile, and so I bet this issue should be closed with no further action.

@pleath - please weigh in if you can, I'm happy to discuss offline as well if you want more context.

**Comment by agarwal-navin** [comment]
`summarizingError` has been removed - https://github.com/microsoft/FluidFramework/pull/15080
