### ISSUE TITLE
Summarizing container hurts responsiveness

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#931]
Notes based on [Igor's feedback](https://ocv.microsoft.com/#/item/fdcl_v4_3593a111a3555d72a045c314391bfced/?tab=Messaging)  and [Team's thread](https://teams.microsoft.com/l/message/19:53328301da384b33bcc81111124e3ab4@thread.skype/1579042988752?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1579042988752&teamName=WAC%20Bohemia&channelName=Bugs%20and%20On-Call&createdTime=1579042988752)

There are other reasons for unresponsiveness (like we are breaking op processing into chunks and yielding between batches every once in a while to let other activity go through). 

1) We create summarizing container right away on becoming connected (which happens right after processing a ton of ops for main container).  Can we have some delay / maybe heuristic to know when there is some idleness?

2) I'm not sure this is Igor's issue, but we could be more efficient by not closing summarizing container on loss of connection (which happens frequently due to PUSH closing socket). Instead of starting expensive process of hydrating new summarizing container after main one connects, we can have some fuzzy logic to reuse old container in some cases. For example, if we reconnect within next 15 seconds, processing ops would be more efficient. Or even better - if re-connection and processing of ops by main container was fast / did not include summary acks, then processing of ops is preferred over starting new summarizing container.

3) We have awaits in many places, but these places are unlikely to yield enough time for user-critical tasks. Should we insert in various places calls that would assess duration between those calls and if too much time elapsed, they would use timer to yield some amount of time for other things?

**Comment by markfields** [comment]
Related: #3969  (if not dupe...)

**Comment by vladsud** [comment]
Yes, it's a dup and not worth keeping.
