### ISSUE TITLE
Shared Intervals: Notification on collection creation

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#9310]
## Work Item
Currently the interval collection api on shared string assumes the usage of well-known interval collection names, that are pre-loaded. There has been a request to not have to depend on specifically named interval collections, and to get events when a collection is created.

Likely this is a new top level event on sequence, like "sequeceDelta", maybe called something like "intervalCollectionCreated"

**Comment by anthony-murphy** [comment]
Putting this on your plate for now @pleath. Another related this that i'm not sure exist is the ability to enumerate collections? if that doesn't exist, i assume it would be an ask right after this, as if they are not using well-known names they will likely want to enumerate existing collection at some point.

**Comment by pleath** [comment]
Thanks. You’re talking about the ability to enumerate all the independent collections, not enumerate the intervals within a given collection, right?

**Comment by anthony-murphy** [comment]
> Thanks. You’re talking about the ability to enumerate all the independent collections, not enumerate the intervals within a given collection, right?

exactly

**Comment by pleath** [comment]
Fixed by #9834
