### ISSUE TITLE
odsp-driver throws genericNetworkError for fluidNotSupported error

### ISSUE THREAD

**Issue by amruth-ms** [microsoft/FluidFramework#9374]
## Describe the bug
A tenant disabled fluid by setting "Set-SPOTenant -IsFluidEnabled $false". After that tried to open a .fluid file with the setting and an error was thrown. This is the information in the error message {"error":{"code":"notSupported","innerError":{"code":"fluidNotSupported"},"message":"Fluid protocol not enabled"}}

### To Reproduce
1. Disable fluid by "Set-SPOTenant -IsFluidEnabled $false"
2. Open a .fluid file with this setting. 
3. Observe that the file cannot be opened and an error is thrown. 

### Expected behavior
In step 3 the user should be able to open the .fluid file.

**Comment by jvoels** [comment]
Title could be updated to "odsp-driver throws genericNetworkError for fluidNotSupported error"

For fluid experience developers using odsp-driver it is an important distinction to be able to provide an appropriate UX when fluid is _disabled_ in ODSP. (non-retriable, "contact your system admin")

Today the error="odspFetchError [400]" and errorType="genericNetworkError" is what bubbles out, while the detailed information is buried.

The response is {"error":{"code":"notSupported","innerError":{"code":"fluidNotSupported"},"message":"Fluid protocol not enabled"}}  -- so the fluid error may have some better details to dig out by contract, such as ITelemetryProperties. But imo we should start with Error.msg, Error.name being distinct enough and then extend that to FF's errorType.

Host UX should be able to handle a specific error for this case w/o much digging and no ambiguity.

The customer facing SPO doc page for this is here:  https://docs.microsoft.com/en-us/sharepoint/manage-loop-components   (SharePoint organization properties -> IsFluidEnabled )

**Comment by markfields** [comment]
@nmsimons - here's a bug to triage, let's talk next week

**Comment by kmui** [comment]
@markfields, @nmsimons can we please try to triage this issue this week?

**Comment by markfields** [comment]
@kmui @jvoels - Obviously we did not come back to this.  Can you please update here on the priority from your perspective?
