### ISSUE TITLE
Missing API: SharedTreeEditor.setValue

### ISSUE THREAD

**Issue by yann-achard-MS** [microsoft/FluidFramework#9385]
## Feature
The `SharedTreeEditor` API does not expose a `setValue` methods. This is inconsistent with the rest of the API which purports to support all types of edits.

**Describe the solution you'd like**
Add a `setValue(target: NodeId, payload: Payload): EditId` function to the API.

**Current workaround**
`const editId = tree.applyEdit(Change.setPayload(target, payload));`

**Comment by taylorsw04** [comment]
@yann-achard-MS yes, the Change API has been improved and should be the primary method for building changes. Those can be submitted either through the applyEdit API or the Checkout API.
