### ISSUE TITLE
SummaryAckWithoutOp being logged when running SharedMatrixDeletes snapshot tests

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#9401]
SummaryAckWithoutOp being logged when running SharedMatrixDeletes snapshot tests
we should figure out why this is being logged, fix it, and remove this supression

_Originally posted by @anthony-murphy in https://github.com/microsoft/FluidFramework/pull/9400#r822077672_

**Comment by agarwal-navin** [comment]
I repro'd this locally and I think I know what is happening. The snapshot frequency for the stress test is 50 which means that after every 50 ops, it take a snapshot of the container, loads a new container from this snapshot and replays rest of the ops (among other things).
In the `messages.json` file that you added, op# 100 is `summarize` and op# 101 is `summaryAck`. So, at some point, a container loads from snapshot at op# 100 and sees a `summaryAck`. It thinks it got a summary ack without an op. If the snap point was an op above or below, you would not see this errror.

**Comment by agarwal-navin** [comment]
This is actually happening in real documents more often than you would think:
<html>
<body>
union Office_Fluid_FluidRuntime_Error
| where Event_Time > ago(7d)
| where Data_eventName contains "SummaryAckWithoutOp"
| summarize count() by Data_eventName, Data_sequenceNumber, Data_summarySequenceNumber, Data_initialSequenceNumber

Data_eventName | Data_sequenceNumber | Data_summarySequenceNumber | Data_initialSequenceNumber | count_
-- | -- | -- | -- | --
fluid:telemetry:SummaryAckWithoutOp | 670 | 621 | 615 | 34
fluid:telemetry:SummaryAckWithoutOp | 670 | 621 | 455 | 5
fluid:telemetry:SummaryAckWithoutOp | 388 | 385 | 368 | 3
fluid:telemetry:SummaryAckWithoutOp | 388 | 385 | 384 | 6
fluid:telemetry:SummaryAckWithoutOp | 388 | 385 | 353 | 2
fluid:telemetry:SummaryAckWithoutOp | 2,012 | 2,006 | 2,005 | 11
fluid:telemetry:SummaryAckWithoutOp | 2,012 | 2,006 | 1,996 | 1
fluid:telemetry:SummaryAckWithoutOp | 2,012 | 2,006 | 1,786 | 3
fluid:telemetry:SummaryAckWithoutOp | 2,012 | 2,006 | 176 | 1
fluid:telemetry:SummaryAckWithoutOp | 13,649 | 13,556 | 13,548 | 5
fluid:telemetry:SummaryAckWithoutOp | 13,649 | 13,556 | 3,318 | 1
fluid:telemetry:SummaryAckWithoutOp | 13,649 | 13,556 | 13,064 | 1
fluid:telemetry:SummaryAckWithoutOp | 13,649 | 13,556 | 13,073 | 1
fluid:telemetry:SummaryAckWithoutOp | 65 | 61 | 29 | 1
fluid:telemetry:SummaryAckWithoutOp | 65 | 61 | 0 | 1
fluid:telemetry:SummaryAckWithoutOp | 503 | 495 | 0 | 2
fluid:telemetry:SummaryAckWithoutOp | 82 | 72 | 0 | 1
fluid:telemetry:SummaryAckWithoutOp | 82 | 72 | 59 | 1
fluid:telemetry:SummaryAckWithoutOp | 82 | 72 | 71 | 1
fluid:telemetry:SummaryAckWithoutOp | 2,012 | 2,006 | 942 | 1
fluid:telemetry:SummaryAckWithoutOp | 503 | 495 | 494 | 1
fluid:telemetry:SummaryAckWithoutOp | 65 | 61 | 49 | 2

</div>
</body>
</html>

**Comment by agarwal-navin** [comment]
For the snapshot tests / replay tool, I think its fine to ignore this error.
But for real docs, I would not expect this to happen. I think this needs to be looked at.

**Comment by vladsud** [comment]
I'm not sure I understand the problem. @agarwal-navin, when you say "container loads from snapshot at op# 100", do you say that summary reference sequence number was 100? If so, summary op has to be > 100, it just can't be 100, right?
