### ISSUE TITLE
ODSP driver and utils: Review URL substring sanitization

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#9417]
Tracking issue for:
- [ ] https://github.com/microsoft/FluidFramework/security/code-scanning/24
- [ ] https://github.com/microsoft/FluidFramework/security/code-scanning/25
- [ ] https://github.com/microsoft/FluidFramework/security/code-scanning/26
- [ ] https://github.com/microsoft/FluidFramework/security/code-scanning/27
- [ ] https://github.com/microsoft/FluidFramework/security/code-scanning/29

**Comment by tylerbutler** [comment]
@microsoft/fluid-cr-odsp Can you folks take a look at these (and any other ODSP-related code scanning issues you see) and either dismiss them or otherwise deal with them? Thanks!

**Comment by vladsud** [comment]
Seems to be valid warnings, I'd keep this bug.
