### ISSUE TITLE
Add telemetry for size of GC blobs

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9436]
The GC blob is currently written as a single blob at the root of the summary tree. The size of this blob can end up being very large and we may not be able to fetch it from the service.
We should log the size and monitor it. If needed, we can break the blobs down and then upload it. The code to read these multiple blobs already exists so it should be trivial to do so.

**Comment by vladsud** [comment]
We should log total size for now. Once we learn total size is large (relative to number of nodes), then we can do deeper digging / extra telemetry.
