### ISSUE TITLE
GC data is duplicated and is very large in table heavy files

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9472]
Fluid DocId == “aMtUNIYUVCTh9pnXng3MeXBc4k11eKpqrj4xeLK8S3A%3D”
[Actual File](https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!sT6xOCLunUaw96VVvQpfKDMINLoURjxDlZOHWW-VJzmXkPSR7oYpSYFq_u8nsw1D&item=01H3KDHNH6PY5TBAJNXFD3MQGLPCNQTUPZ&file=https:%2F%2Fmicrosoft-my.sharepoint.com%2Fpersonal%2Fdevverma_microsoft_com&siteUrl=https:%2F%2Fmicrosoft-my.sharepoint.com%2Fpersonal%2Fdevverma_microsoft_com)

Data_eventName | Data_deletedNodes | Data_totalNodes | Data_deletedDataStores | Data_totalDataStores | count_
-- | -- | -- | -- | -- | --
fluid:telemetry:Summarizer:Running:GarbageCollection_end | 599 | 76,566 | 162 | 1,302 | 7

GC blobs are 44Mb in size (1378 unique blobs)!
So I think we have to take a closer look at GC in general, and telemetry to catch issues like that (more on one angle below)
 
There is a lot of replicated data that feels like should not be there in GC blobs. I.e.:
{
  "gcData": {
    "gcNodes": {
      "/d016fa27-8dfc-4d14-b41a-db660dede561": [
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae"
      ],
      "/72436162-1b8b-4cc6-a155-b77d13beeca7": [
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae",
        "/571dd49a-6477-4807-99d9-5808f70ddcae"
      ],

**Comment by vladsud** [comment]
Actually, @tyler-cai-microsoft, any chance you can glance at this (April is fine)? If you have enough knowledge to make some progress here, it would be great to assign it to you to free up Navin a bit. I think that's pretty big issue (we do not have data, but that file alone has some staggering issues with GC blob sizes)

**Comment by tyler-cai-microsoft** [comment]
Yeah, I probably will have to rearrange some of my slated April work, I think I am able to look at this (if not I can always bug @agarwal-navin 🙈)

**Comment by vladsud** [comment]
Ok, I'll assign it to you and we can look together at overall scheduling a bit later.

**Comment by tyler-cai-microsoft** [comment]
Able to repro this, still debugging
