### ISSUE TITLE
SharedTree: Initial Changeset Rebase Implementation

### ISSUE THREAD

**Issue by taylorsw04** [microsoft/FluidFramework#9477]
Implement a prototype that handles the rebasing of multiple local commits over a single base commit to produce updated (i.e., rebased) versions of the local commits as well as a changeset that describes the net effect of the base commit on the local branch.

The prototype should support the follow change operations:

- insert
- set-like range delete
- set-like range move
- slice-like range delete
- slice-like range move
- set-value

It should not support:

- drill-down anchoring
- explicit constraints

The prototype may make some simplifications such as:

- Eschew performance for the sake of implementation simplicity.
- The inverse of a change need not include all information necessary to its application on a tree. The caller of the rebase function can supply this information separately.

**Comment by yann-achard-MS** [comment]
Implemented so far:
* insert
* set-like range delete
* set-value

In progress:
* set-like range move
