### ISSUE TITLE
Make flushMode immutable for a container. Deprecate `ContainerRuntime.setFlushMode()`

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9480]
From the conversation in https://github.com/microsoft/FluidFramework/pull/9432, we should make flushMode immutable.

Primary reason for this work is to enable / make it easier to do
- #9481

**Comment by andre4i** [comment]
To add:

- flushmode may be set via `IContainerRuntimeOptions`
- must follow the guidelines at https://github.com/microsoft/FluidFramework/wiki/API-Deprecation
- must ensure whether or not someone is using actually using this API (add a telemetry event when this property is toggled). My guess is that the feature is not currently used.

**Comment by andre4i** [comment]
## Deprecated API

`IContainerRuntimeBase.setFlushMode(mode: FlushMode): void;`

**Context**

The API is not currently used and enables a set of scenarios which should not be supported. Maintaining this API is costly and it adds a non-trivial amount of complexity to the adjacent logic.

**Approach**

`FlushMode` can be set at runtime creation, using `IContainerRuntimeOptions` and will remain immutable for the lifetime of the object.

Workarounds for the existing scenarios:

- Runtime has **FlushMode.TurnBased** and the client needs ad-hoc behavior similar to **FlushMode.Immediate**? Force a JS turn after each operation (use a construct such as `Promise.resolve().then`)
- Runtime has **FlushMode.Immediate** and the client needs ad-hoc behavior similar to **FlushMode.TurnBased**? Use `IContainerRuntimeBase.orderSequentially`

**Dependencies**
n/a

**Compatibility Concerns**
n/a

**Phases**

- Mark the API as deprecated and emit a telemetry event for its use
- Remove the API and all it's usages

**Expected Timeline**

- 0.61

**Open Questions**

TBD

**Comment by kian-thompson** [comment]
Closed to track in AB#393
