### ISSUE TITLE
Remove flushMode tracking and validation in PendingStateManager

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9481]
From the comment here https://github.com/microsoft/FluidFramework/issues/9432#issuecomment-1065578584_, we don't need to track flushMode. We can track batches and then replay a batch together via orderSequentially. This will make the tracking and validation much simpler.

**Comment by vladsud** [comment]
How big is work here? Can someone else help with it?

**Comment by agarwal-navin** [comment]
It should be a smaller amount of work if this goes in - https://github.com/microsoft/FluidFramework/issues/9480. Andrei might be able to help here since he is already working in this space.

**Comment by vladsud** [comment]
Ok, I'll assign to Andrei and will move to May to account for that pre-work

**Comment by andre4i** [comment]
I agree with Navin, https://github.com/microsoft/FluidFramework/issues/9480 should be tackled first.

**Comment by kian-thompson** [comment]
Closed to track in AB#394
