### ISSUE TITLE
NodeErrorTrackingService incorrectly implements IErrorTrackingService

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#950]
NodeErrorTrackingService  is the only implementation of IErrorTrackingService, but it implements it's own API, not that of IErrorTrackingService. We should fix the implementation or interface, or remove the interface.

**Comment by vladsud** [comment]
Can't find either of the symbols. I believe I saw some cleanup PR some time ago.
Closing.
