### ISSUE TITLE
Update the fluid handle document 

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9514]
The following fluid handle document is out of date and needs updating - https://github.com/microsoft/FluidFramework/blob/9c767dc4834c0bd2894fe21a0ce491951854c0c9/packages/runtime/datastore/README.md.
The IFluidHandle implementation has changed over the years and this document is stale and has broken links.

**Comment by pizzaz93** [comment]
Additional broken links and references https://github.com/microsoft/FluidFramework/search?q=handles.md

**Comment by agarwal-navin** [comment]
Tracked by AB#440
