### ISSUE TITLE
Compatibility-and-Versioning doc is wrong and needs to be fixed

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9517]
It would be great to update https://github.com/microsoft/FluidFramework/wiki/Compatibility-and-Versioning#testing-boundary-cross-changes-locally to be more realistic.

Here are some high-level obeservations:

There is no such thing as N/N-1. There is N/N-2 for runtime to data store, and essentially infinite between loader & to driver / runtime (it's capped at LTS, which I believe is 0.45 at the moment).

This is about runtime compatibility. I do not think definition compatibility is a thing. I.e. you always compile against specific version of definitions. Our build system will try to impose certain limitations, but they are not stopping at N/N-1, i.e. they are either enforced across many versions or not.

I personally do not like "The runtime version is bound to the document" narration. Code proposal (name should be changed) is a document schema proposal.

**Comment by markfields** [comment]
@heliocliu FYI, I am working on a doc on the side to try to articulate all the different compatibility considerations around our code. I find it's always very confusing to talk about, and there are so many different axes along which to consider compatibility, so I thought it would be useful to try to write it down.  Keep me in the loop as you clarify this documentation, and I can share my notes if/when I get time to work on it too.

**Comment by heliocliu** [comment]
@markfields Yeah definitely.  Fwiw I also wrote https://github.com/microsoft/FluidFramework/wiki/Breaking-vs-Non-breaking-Changes which lightly covers what it means to be breaking.  I'm thinking that page is better suited for describing what it means to be breaking/compatible whereas the Compatibility and Versioning page should be adjusted to focus more on the procedural side of how we handle compatibility.

**Comment by heliocliu** [comment]
I updated the breaking vs non breaking changes page to include some more specific information on the different version breaking interfaces and clarified the N/N-k expectations there. I also updated the compatibility and versioning page to remove that information and point to the breaking vs non breaking page.  I think this should help focus the scope of the two pages and that the information I added is correct - lmk if anyone thinks these changes are insufficient

**Comment by heliocliu** [comment]
Also please close this issue if it does seem sufficient since I can't anymore 🙃

**Comment by vladsud** [comment]
Thanks @heliocliu! @markfields, can you please glance if we should close it or we want to keep it to track some more work? You mention that you are working on something...
