### ISSUE TITLE
Test failure "can send and receive consecutive batches that are flushed on JS turn" in e2e against local server

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#9546]
Test failure is happening in @fluidframework/test-end-to-end-tests - local
can send and receive consecutive batches that are flushed on JS turn
Build link for more info: https://dev.azure.com/fluidframework/internal/_build/results?buildId=58232&view=ms.vss-test-web.build-test-results-tab&runId=1212590&resultId=100875&paneView=debug

Stack trace:
Batch end metadata not found
AssertionError [ERR_ASSERTION]: Batch end metadata not found
    at verifyBatchMetadata (dist/test/batching.spec.js:48:21)
    at Context.<anonymous> (dist/test/batching.spec.js:240:17)

**Comment by andre4i** [comment]
cc @agarwal-navin 

@jatgarg is this blocking PRs or the release? I'm not seeing these failures in the PR tests.

**Comment by jatgarg** [comment]
Sorry, this is not failing in PRs. This was failing in Real service e2e tests pipeline. @markfields

**Comment by markfields** [comment]
Unless I'm mistaken it _could_ fail a PR, it just hasn't yet.  It's intermittent, and failing against local server.

**Comment by jatgarg** [comment]
Seems like this is blocking the PRs. Failed twice on my PR. Should we disable the test for now?

**Comment by andre4i** [comment]
> Failed twice on my PR. Should we disable the test for now?

Yes
