### ISSUE TITLE
Work with Relative Path in Shared Directory Events

### ISSUE THREAD

**Issue by jatgarg** [microsoft/FluidFramework#9559]
Currently there are 2 events fired by SharedDirectory which contain paths and keys.
1.) "containedValueChanged": This event is fired by SubDirectory whose key is changed/deleted. The info provided on this event is:
```
export interface IValueChanged {
    key: string;
    previousValue: any;
}
```

2.) "valueChanged": This event is fired by SharedDirectory whose any key is changed/deleted. The info provided on this event is:
```
export interface IDirectoryValueChanged extends IValueChanged {
    path: string;
}
```
The path here is the absolute path for the directory firing the event. Not sure how useful it is since nobody might be interested in full absolute paths and knowing how deep they are in tree structure. If they want to, they can construct from the absolute path of the object they are working with and the relative path provided on the event.

**Comment by jatgarg** [comment]
We can change the IValueChanged to be:
`
interface IValueChanged {
    path: string,
    previousValue: any,
}
`
where path represents the relative path from the object firing the event to the key that is modified/deleted. So, if we have directory structure:
root->A->B->c(key), and we change the value for key c,
1.) The path will be /A/B/c for "valueChanged" event.
2.) The path will be c for "containedValueChanged" event.

**Comment by ChumpChief** [comment]
`IValueChanged` should definitely not add a `path`.  Both for the reasons Vlad describes ("reaching" via path frequently maps to violating encapsulation), but also because it is used by the map DDS where path is not a concept.

Could you describe the problem you're trying to solve?  I'm not certain what the motivation for this would be.

**Comment by jatgarg** [comment]
For IValueChanged, since it is fired by the parent directory only, key and relative path from object firing to value is changed is same. So, key === relative path for IValueChanged.

**Comment by jatgarg** [comment]
Here is a written proposal for the same:
https://microsoft-my.sharepoint-df.com/:w:/p/jatgarg/EVUL5BHmTkxBkqWtYds2O5kBdkRjdzE6kO8lIUhw_gVcJg?e=ak2D4U
