### ISSUE TITLE
Update to Webpack 5

### ISSUE THREAD

**Issue by CraigMacomber** [microsoft/FluidFramework#9568]
## Work Item
**Describe the outcome you expect**
All usages of webpack 4 are replaced with webpack 5

**Approach**
Follow https://webpack.js.org/migrate/5/

This guide does not mention updating web-pack-dev server, but its v4 is compatible with webpackv5, so it will be updated first following https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

**Open questions**

There might be some unexpected issues discovered while working on this. The two mentioned below are examples of the kinds of issues that might crop up.

**Additional context**
#4843 may have to be fixed or worked around as part of this.
#9443 may have to be fixed or worked around as part of this.

**Acceptance criteria**
All usages of webpack 4 are replaced with webpack 5.
Built works, tests pass. Manual testing of a webpacked example works.

**TODO**

- [ ] Update storybook to use webpack 5 (Accounts for 4 copies of webpack for in client mono-repo)
- [ ] Update version of @fluidframework/bundle-size-tools used in build-tools, and remove use of @types/webpack latest webpack has types built in)

**Comment by CraigMacomber** [comment]
To get fully off webpack4, looks like we will want to do adopt https://www.npmjs.com/package/@storybook/builder-webpack5 . This might not block the main transition though.

Plugins with possible issues:

```
css-loader@1.0.1 requires a peer of webpack@^4.0.0
extract-text-webpack-plugin@4.0.0-beta.0 requires a peer of webpack@^3.0.0 || ^4.0.0
file-loader@3.0.1 requires a peer of webpack@^4.0.0
istanbul-instrumenter-loader@3.0.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0
less-loader@4.1.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0
monaco-editor-webpack-plugin@1.7.0 requires a peer of webpack@^4.5.0
react-docgen-typescript@2.2.2 requires a peer of typescript@>= 4.3.x
sass-loader@7.3.1 requires a peer of webpack@^3.0.0 || ^4.0.0
html-webpack-plugin@3.2.0 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0
terser-webpack-plugin@1.4.5 requires a peer of webpack@^4.0.0
url-loader@2.3.0 requires a peer of webpack@^4.0.0
webpack-filter-warnings-plugin@1.2.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0
webpack-karma-die-hard@1.0.4 requires a peer of webpack@^1.9.11
```

https://www.npmjs.com/package/extract-text-webpack-plugin is deprecated. Migrate to https://www.npmjs.com/package/mini-css-extract-plugin ?

**Comment by tylerbutler** [comment]
@CraigMacomber Are you planning to address the use of node libraries and polyfills with this work item? I have been doing some related work to better support Webpack 5 and other modern bundlers (see #9506) so it might intersect with your plans here.

**Comment by CraigMacomber** [comment]
@tylerbutler I haven't looked into that yet. If it ends up blocking the v5 update I'll sync with you about it. For now I'm just doing the preparer changes of updating webpack-cli and webpack-dev-server, so I won't be getting to that for another PR or 2.

**Comment by CraigMacomber** [comment]
Looks like duplicate-package-checker-webpack-plugin is not ready for webpack v5, but there is a fork that is: https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin/pull/46

**Comment by CraigMacomber** [comment]
The portion of this work I consider worth prioritizing is complete. I have updated the TODO in the issue and will be unassigning myself from this issue.

**Comment by zubeirtech** [comment]
Hi, when can we expect this issue to be solved, we have this issue in CRA and angular => https://github.com/microsoft/FluidFramework/issues/10383 and it makes it problematic for people to try fluid framework.
