### ISSUE TITLE
Update describeLoaderCompat to test both old and new loader relative to driver/runtime

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#9581]
Currently, using `describeLoaderCompat` in our e2e mocha tests will only vary the loader version to the legacy version, but won't test the current loader with legacy versions of the driver and runtime.

While "old loader" is by far the more common configuration we see in the wild, it's important that new loader versions remain compatible with recent driver/runtime versions as well.

See https://github.com/microsoft/FluidFramework/pull/9578#discussion_r834586326

**Comment by curtisman** [comment]
Please look at the existing usage to see if those tests would actually benefit.  
Maybe we should deprecate this one and expose a `describeCompat` that will accept a list of compat kind instead.
