### ISSUE TITLE
Prevent Summaries when there are no ops

### ISSUE THREAD

**Issue by tyler-cai-microsoft** [microsoft/FluidFramework#9583]
In the absence of ops, there is no data to summarize, so summaries shouldn't be run. Additionally, GC shouldn't run without summaries.

GC runs when summaries are run, it would best serve GC to not run when there are no ops as there is no value yet for GC to delete anything or mark anything as unreferenced locally.

When there's no Summary or op timestamp, GC should not be run.

**Comment by agarwal-navin** [comment]
The Summarizer has heuristics which would not run when there are no ops. However, with on demand summaries, its possible to trigger a summary without ops. We should either ignore such summary requests or return an error.

GC relies on the timestamp of the last processed op to mark when an object becomes unreferenced. So, if there isn't an op ever processed by the summarizer client, running GC means that it won't have any timestamp to make unreferenced content with. Note that this can happen only when the summarizer is loaded from the very first summary generated by the detached container and it attempts to summarize without any ops. This is a corner case and should rarely (or never) happen. However, there is code in GC that explicitly handles this scenario and it makes the logic more complex than it needs to be.

So, not allowing summaries without ops seem like a solution that will solve it for GC as well.

@pleath @vladsud

**Comment by vladsud** [comment]
@tyler-cai-microsoft, @agarwal-navin, we should either assign this item to a person, or unassign from April

**Comment by agarwal-navin** [comment]
I created another issue that talks about letting GC run in absence of non-system ops for specific scenarios - https://github.com/microsoft/FluidFramework/issues/9841. It also solves the issue this item talks about. We should close this issue in favor of that one.

**Comment by vladsud** [comment]
I'm all for simplicity :) I think we can always rely on summarizer being a write client, at least in current design where it has to submit summary op. If that were to change in the future, we would revisit these decisions.

**Comment by agarwal-navin** [comment]
Yes, I agree. If we can assume and validate that, we can make the GC code simpler. Closing this issue in favor of https://github.com/microsoft/FluidFramework/issues/9841.
