### ISSUE TITLE
Collect stats on number of trailing user ops

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9621]
"TreesLatest" perf event longs number of trailing ops:
>                     ops: snapshot.ops?.length ?? 0,

We need to continue doing it, but also log number of ops that are not system ops (see isSystemMessage()).
This will help us understand how much user content is there.

We need to port this change to the version of runtime that is currently shipping in Chapter1 & Whiteboard and deploy it there.

**Comment by vladsud** [comment]
It sounds like Ch1 is on 0.58.1001, so that's the release we want to port changes to (and any releases after that, like)

**Comment by NicholasCouri** [comment]
@vladsud,  would this get what you want: 
nonSysOps:  snapshot.ops?.filter((op) => !isSystemMessage(op)).length ?? 0,

**Comment by vladsud** [comment]
Yep. Probably not as efficient as it could be (as it creates temp array), but that's probably fine

**Comment by NicholasCouri** [comment]
I could use a foreach instead and add a new variable to count ?

**Comment by vladsud** [comment]
Do we need fixed in 0.55, 0.56, 0.57?
FFX is already on 0.58.1001 (I believe, worth double checking). If so, I do not think there is a need to have older releases.
Maybe 0.57 is Ok for someone who is a bit behind, but I'd probably not touch the older releases.

**Comment by NicholasCouri** [comment]
You mentioned Ch1 and Whiteboard (0.55) - For Ch1, we looked at this query that Navin shared with us: 

union Office_Fluid_FluidRuntime*
| where Event_Time > ago(7d)
| join AllHostScenarioNamesExtended() on Data_hostScenarioName
| summarize count() by Chapter, Data_hostName, Data_runtimeVersion, Data_driverVersion, Data_loaderVersion

![image](https://user-images.githubusercontent.com/26266632/160224308-e3f1d74e-702f-4f21-9cc1-149e3b77b224.png)

Please let me know if you still want >= 57 so I can proceed with the pipeline releases.

**Comment by vladsud** [comment]
0.56 has the most usage, and driverVersion is what matters here. So yes, maybe 0.56 should be patched.
The part that I do not know is if apps can deploy hotfixes for old versions. I'll ask around

**Comment by vladsud** [comment]
@NicholasCouri , I believe this issue should be closed (I'll track separately analyzing data)

**Comment by NicholasCouri** [comment]
Sure thing.
