### ISSUE TITLE
Summary data: Notes based on observation of telemetry data & code

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9635]
1. I was looking at summarize telemetry code, and I'm not sure I follow this logic:

```
        const summarizeEvent = PerformanceEvent.start(logger, {
            eventName: "Summarize",
            refreshLatestAck,
            ...summarizeTelemetryProps,
        });
```
```
            const generateSummaryEvent = PerformanceEvent.start(logger, {
                eventName: "Summarize",
                ...summarizeTelemetryProps,
            });
```

Why do we need to events with exactly same name in same function? I think you can leverage first one just fine - they represent the same starting point in time.

2. I'm not sure there is a value in recording constants:
> message: "summaryAck",

3. Why Whiteboard data is different from Chapter1? opsSinceLastSummary & timeSinceLastAttempt is missing:
union Office_Fluid_FluidRuntime_*
| where Event_Time > ago(7d)
| where Data_eventName == "fluid:telemetry:Summarizer:Running:Summarize_end"
| extend WB = Data_hostScenarioName contains "Whiteboard"
| summarize count(), avg(Data_timeSinceLastAttempt), avg(Data_opsSinceLastSummary), avg(Data_totalBlobSize), avg(Data_duration)
by Data_eventName, WB

| Data_eventName | WB | count_ | avg_Data_timeSinceLastAttempt | avg_Data_opsSinceLastSummary | avg_Data_totalBlobSize | avg_Data_duration |
|-- | -- | -- | -- | -- | -- | --|
|fluid:telemetry:Summarizer:Running:Summarize_end | false | 1,580,649 | 8450170 | 30 | 117863 | 2518|
|fluid:telemetry:Summarizer:Running:Summarize_end | true | 388,603 | 21678480 | NaN | NaN | 3533|

Note that if we look at fluid:telemetry:Summarizer:Running:GenerateSummary data, we will see that Whiteboard has both opsSinceLastSummary & timeSinceLastAttempt payload. So maybe it's a mix of different versions and their format that screws the data.

4. I'm not sure how to interpret timeSinceLastAttempt - see above: average is in millions!

**Comment by vladsud** [comment]
Hey @NicholasCouri , any chance you can provide some insights here on what was wrong with # 4 item from above?
Also can we create some query (filter data) to look at valid data based on earlier available telemetry?
It would be useful to poke at data earlier if there is any way to do so, without waiting for changes to propagate through the system

**Comment by NicholasCouri** [comment]
@vladsud  - Working on it
