### ISSUE TITLE
Summarizer: track number of non-system ops we are summarizing.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9637]
We record opsSinceLastSummary in summary telemetry.
I've opened #8932 to record size of ops summarized.
We would also benefit from reporting how many of these ops are system ops vs. not system ops.
This will help us understand
- if we need to adjust frequency of summaries, as we might be summarizing too often when we do not need to
- As part of this work, we should actually consider counting only non-system ops when deciding if "idle" & "maxTime" triggers should fire.

**Comment by andre4i** [comment]
Hey @vladsud , what do you mean by `system ops vs. not system ops` ?

Is it messages vs signals? Or `FluidDataStoreOp` vs `Attach`, `Alias`, `BlobAttach`?

**Comment by vladsud** [comment]
See isSystemMessage()

**Comment by vladsud** [comment]
FluidDataStoreOp, Attach, Alias, BlobAttach - these are all internally types, they will show up (at the level of loader) as "op" type.
Everything else is a system op

**Comment by andre4i** [comment]
Perfect, thank you!

**Comment by andre4i** [comment]
Telemetry was added, follow-up https://github.com/microsoft/FluidFramework/issues/9793
