### ISSUE TITLE
Investigate impact of GC blob sizes to total summary size

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9652]
See PR https://github.com/microsoft/FluidFramework/pull/9485/files
May need to wait till June for data to come in.

**Comment by vladsud** [comment]
@tyler-cai-microsoft , can you please own this?
The plan should looks something like that:
1. Once we have data, we should understand it's impact on overall summary & snapshot sizes.
2. We should have an opinion if duplicated routes has big impact here. If it is, we might want to backport it as a hotfix to fix issues sooner than later.
3. Once we have any data or estimates how it looks like after fixes, we should figure out if we should exclude GC blob from snapshot payload (i.e. only summarizer to load it), as well as if we have to break it into pieces in order to have more incremental summaries.

The outcome of this investigation - an opinion on next steps we have to take.

**Comment by vladsud** [comment]
@tyler-cai-microsoft , can you please own this?
The plan should looks something like that:
1. Once we have data, we should understand it's impact on overall summary & snapshot sizes.
2. We should have an opinion if duplicated routes has big impact here. If it is, we might want to backport it as a hotfix to fix issues sooner than later.
3. Once we have any data or estimates how it looks like after fixes, we should figure out if we should exclude GC blob from snapshot payload (i.e. only summarizer to load it), as well as if we have to break it into pieces in order to have more incremental summaries.

The outcome of this investigation - an opinion on next steps we have to take.

**Comment by agarwal-navin** [comment]
Closing as this is tracked internally AB#190
