### ISSUE TITLE
Azure Client document recovery API - Post V1.0

### ISSUE THREAD

**Issue by ssimic2** [microsoft/FluidFramework#9670]
#9442 captures current work around container recovery. This ticket is meant to help us get clarity around long term (post v1.0) solution and offer visibility into open questions - so we can all make better decisions down the road. I’m gathering here key points we discussed as a group.

## Assumptions ##

The purpose of v1.0 is to learn through various use cases. However, it is highly likely that post v1.0 we will end up supporting some solution offering ability to rollback existing documents - therefore we will likely need to tackle following topics: 

(1) previewing document versions.
(2) rolling back documents to earlier version.
(3) client synchronization (post-recovery).

What's less certain is maybe how clients will interpret "minimum data loss", and what configuration/policy we need around versioning. 

## Where we can learn from ##

ODSP - Some of this was discussed in #8870. The burden of rollback/recovery falls on the service. Other than killing session on epoch changes and opening read-only sockets for doc previews, most of the process relies on ODSP storage layer for versioning & arbitrary rollbacks - one of the use cases being corrupted container recovery. FF snapshots and other FF native mechanisms play no part in this process.

Azure Storage – Since existing FRS implementation is relaying on Azure Storage (for summaries now and likely for ops in the future as well), natural assumption is that we end up relying on native backup/recovery capabilities of azure storage (Ex. Point-in-time restore for Azure blobs).  This would be similar to ODSP in a sense that we are using storage layer for backup/recovery purposes. The difference here is that we are exposing FRS capabilities as a set of APIs that clients can use to build any tools they desire, including portals to expose their own rollback/recovery capabilities.

Git – Git naturally offers ability to preserve history as each summary is saved as its own commit that has a reference to previous commit/summary. In the case of FRS, document id is really just a git `ref` that keeps moving while always pointing to the latest commit/summary. Of course, we can always think of backup/recovery of the whole repo, but we should consider more optimal solutions that in conjunction with FF could aid rollback/recovery process while leveraging commit history. One of the key issues here is ops - as ops seq. # always monotonically increase for the given doc id. However, this should not be too difficult to solve. Generally speaking, git offers various apis/tools that can aid corruption detection (like `git fsck` for example)

## Open Topics ##
These are open topics in no particular order.

General expectations around recovery & data retention policy, as compared to other services we might be compared to.

Cost implications - If we end up adding another backup/restore layer what would the cost implications be? How would we expose & reason around added cost? Corruption errors are rooted in FF – if clients don’t care about arbitrary rollbacks (to fix errors they introduced), can we still justify added cost?

Configuration implications – What we should think about in regard to configuration policies?  Examples:
- Would the umbrella feature be arbitrary rollbacks, so we can more easily reason around config. policy? 
- Would desired versioning policy needs (say frequency) be different for corruption vs arbitrary rollbacks.
- Clients may have different ideas on what minimal data loss is. It may range from “I don’t care if you lose all of it”, up to “I care about few seconds worth of data”. Down the line, would our existing infrastructure let us configure backup policy per-client? Any special considerations there?

Server-side corruption – We have discussed cases where server can detect corruption and may want to signal FF client that error has occurred. Can we please elaborate on those cases here? **We need to understand if there are existing cases where client truly cannot act as a “catch-all” place for server-side errors**. I have seen Scribe respond with errors on seq. num errors, but I understood there are cases where server marks document as "corrupted" and allows no further ops. How does this manifest itself from perspective of client ? We need to understand if this has any immediate v1.0 implications.

Leveraging FF native mechanism (server vs client) – Is it worthwhile further exploring FF native mechanism for recovery/rollback purposes? Are there significant advantageous offered? Are there limitations/constraints of using snapshots for versioning purposes? Even if we had another server-based “versioning” mechanism, would “minimal data loss” still be more easily offered through native FF mechanism? Could size/speed be optimized, and document re-identification be achieved through git-based solution? Are we solving similar problems (offline editing?) that may help guide us towards best overall direction. We probably don't want duplication of functionality across client/server, but rather look for areas where they can complement each other.

Document re-identification – Posting this here as capability we may need down the line. If this capability comes out of the box with versioning/rollback capability, we should be fine here.

Document locking – Surfacing this here as we are seeing more and more use cases where client has a need to lock the document to ensure no further updates are done. It may be in the context or recovery, schema upgrade etc.

Control vs Data Plane – Ahmed brough this question up. Is this concern of data/control plane?

What else?

Again, the goal here is visibility and early discussion. We are starting with simple offering, but at the same time we should be aware of the road ahead. The goal is not to determine one ideal solution. Given we may have wider range of needs, we may land on multiple solution layers.

**Comment by vladsud** [comment]
Some random thoughts based on description:

I think we need to clearly define what "document recovery" actually means. I find these two scenarios vastly different:
- User operates on a single file and wants to revert back some changes / use older version of a file
- Admin controlled backup / restore functionality (which IMHO is more a function of whole tenant, more on that a bit below).

The do overlap (first item can be done via using backup), but only in most critical data loss scenarios.

Rollback in storage can happen for any reason (data center fall over, data center restore, ordering service failing to preserve ops to storage and eventually giving up, etc.). This is true for both ODSP & Azure.

Client has to be prepared for this scenario. This is partially done by existing flow (client checking for interruption in op flow / ops with known sequence numbers but different content). Partially should be improved by checksum work (that is on pause), and partially (in case of ODSP) by notion of epoch that is changed when service detects file overwrite.
Today, when clients detects file overwrite (for any reason), client closes session and removes all the knowledge about a file (caches), such that new session (for same file) can restart successfully.

Client detecting file overwrite (as result of restore from backup) is same as above.

Git IMHO does not provide any help with backups. It's easy to move ref 100 commits down and do GC and all these 100 commits are gone. Backups would be at higher level (whole repo), and they should be done periodically to be able to restore repo, but backup logic could leverage ultimate knowledge of git storage to make it more efficient (incremental).

I think same sentiment should be applied to Fluid. I'd add that I'd expect most customers to have a need to backup their storage (all files in some partition / tenant) on a schedule, and automate it (with good reliability), and thus I'd expect backup logic not to run any Fluid code and be fully centered around storage and storage representation (i.e. not at Fluid protocol level). Ideally storage provides that (either at level of cire Azure, or at lever of Fluid Azure storage).
