### ISSUE TITLE
Generalize summary-related telemetry data collection 

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9694]
This issue tries to unify collection of data and discovery of issues.

## Examples

First, some examples to demonstrate how we do similar work today, and the potential value of future work:
- #9485 (counting GC blobs)
    - #9472
- **IGCStats** interface (counting data stores)
- #6364
   - It's likely still a problem - see #9682
- **ISummaryTreeWithStats** interface, collecting high-level stats about summary

## Proposal
Provide generic mechanism to collect statistics about summary content and summary process.
For example, to collect such data as
- Number of maps, directories, and their sizes
- Number of Sequences, and sizes & number of header, body & catchup blobs
- GC blob sizes & count
- Time it takes to generate summary for particular type of DDS
    - mostly assumes synchronous execution.
- etc.

## Possible Designs
There are two ways to accomplish it:
- Extend ISummaryTreeWithStats to have generic key-value storage that various players can use to store data.
- Provide a context object (possibly just a map) to various summarize APIs to be able to achieve the same.
In either case each player (DDS, DataStore, GC sub-system) can record data as it generates summary.
Once done, central summarizer code can log it as part of summary telemetry.

I'd prefer context approach, as it's more explicit, and aggregation happens more explicitly (and allows different types of aggregation, not just addition), whereas if it's part of ISummaryTreeWithStats, then shared (unrelated) code aggregates (sums up) data across child nodes into parent node. For example, some DDS might want to record a maximum blob size for such DDS type - this kind of aggregation is impossible with ISummaryTreeWithStats approach.

One thing that I'm not sure about:
Given **global nature** of such mechanism, key names need to be unique. So, we either need to use guids / assert tags, or very long identifiers (like DDS factory type). Which will make analyzes of data (by humans) a bit harder - human eye would prefer to see short names like "DirectoryCount", but that could run into conflicts if there are multiple entities who call themselves "Directory". We can likely use prefixes (like "fluid:") to differentiate against external entities (as within single repo we can ensure uniqueness).

## Data to collect using this mechanism

1. For key DDSs (map, directory, sequence)
   - number of instances summarized
   - Total number of bytes in summary blobs (across all instances of that type).
2. Sequence DDS:
   - size of catchup blobs and number of them
3. Same for GC info (i.e. make #9485  not a snowflake, but use same mechanism and remove GC metrics from interfaces)

\# 1 is a top priority! So if other items are slowing down shipping it, we should split into number of PRs / items to track.

**Comment by vladsud** [comment]
@agarwal-navin, @tyler-cai-microsoft, @anthony-murphy - please take a look, critique.

**Comment by vladsud** [comment]
@kian-thompson, can you please glance at this item? Is this something you can take on?
@NicholasCouri - let me know if you already started here. I'm simply looking at rebalancing / finding new work for Kian :)

**Comment by NicholasCouri** [comment]
No worries - I can continue to 9686.

________________________________

**Comment by kian-thompson** [comment]
> Is this something you can take on?

Yes, it seems straightforward enough at first glance to take on

**Comment by kian-thompson** [comment]
@vladsud After looking into this more, it seems there are a number of involved packages. Here are some that I think apply:
`@fluidframework/runtime-utils`
`@fluidframework/container-runtime`
`@fluidframework/shared-object-base`
`@fluidframework/datastore`
`@fluidframework/map` and other key DDSes

Is this change expected to be a slow rollout?

**Comment by vladsud** [comment]
Yes, and possibly it will need to be staged across versions (to support back compat).

Which direction you are thinking to go? I see two ways:
1. Passing new context object to all summarize() methods. It will result in changes to all packages you mentioned (and more), but we can make context object optional, and thus propagate that change in one PR. Usage in DDSs would be conditional (if context is provided) and eventually we can make it non-conditional.
2. Adding optional payload to ISummaryTreeWithStats. That way no need to directly change all DDSs right away, but code like mergeStats() would need to be merging this info as it propagates from leaf nodes to root. Chance of making mistake here (forgetting to change logic like that somewhere else, if it exists) will result in dropping such props on the floor.

I feel like # 1 is more elegant and more explicit, even though yes, it requires more changes. Context object might be useful for other things in the future (like passing extra hints about summary itself). For example, we thought about adding yielding capabilities to summarization process to ensure we keep app responsive, and thus it would be nice to have an object that every DDS and data store can call into to ask if it needs to yield or keep going. We can easily add such capability to such context object in the future.

**Comment by kian-thompson** [comment]
Closed to track in AB#161 AB#446 AB#447
