### ISSUE TITLE
Get rid of IsSystemMessage 

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9732]
Replace usage of IsSystemMessage with !IsRuntimeMessage
See https://github.com/microsoft/FluidFramework/pull/9714

We should stop testing for system messages, as client does not know full set of messages that system can send.
Instead, we should assume that there is a limited set of messages client sends (and validate it on sending, as well as filter out all non-client messages on processing / receiving), and test against that set everywhere where we test for system messages today.

```ts
 function isClientMessage(message: ISequencedDocumentMessage | IDocumentMessage) {
    switch (message.type) {
        case MessageType.Propose:
        case MessageType.Reject:
        case MessageType.NoOp:
        case MessageType.Summarize:
        case MessageType.Operation:
            return true;
        default:
            return false;
    }
}
```

The work will include couple steps:
1. Defining this new function in definition package next to where IsSystemMessage, and possibly removing IsSystemMessage in the same change (we can remove it later, removing it right now is non-back compat change).
2. Publishing new package for definition package.
3. Consuming it in client repo and replacing all usage of IsSystemMessage with !IsRuntimeMessage

**Comment by dannimad** [comment]
In the code the function is called "isClientMessage" but in the steps is called "IsRuntimeMessage". 
1 Are they referring to the same method?
2 Which name should we use?

**Comment by vladsud** [comment]
That's good question! I think we should add both :)
1. isClientMessage() is what it looks above
3. isRuntimeMessage is op.type === MessageType.Operation || op.type === MessageType.Summarize

Depending on where !isSystemMessage used, we should replace it with one or another, it should be easy to see which one to use based on context.
One thing I'll point out that today container runtime can send both "op" & "summarize" ops, but we allow to inbound only "op" (see Container.processRemoteMessage). I think it's fine to change that to make it more symmetrical and use same isRuntimeMessage() check both in Container.processRemoteMessage but also in submitContainerMessage (NOTE: MessageType.RemoteHelp should be removed, I think I opened separate bug about that - feel free to do it as part of this change) 

And, looking at the usage, we should not define both in protocol-base package.
We should define both of them somewhere in client space.
Probably @fluidframework/container-definitions ?
