### ISSUE TITLE
Server: Address server-side URL handling

### ISSUE THREAD

**Issue by tylerbutler** [microsoft/FluidFramework#9743]
- [ ] https://github.com/microsoft/FluidFramework/security/code-scanning/72
- [ ] https://github.com/microsoft/FluidFramework/security/code-scanning/71

**Comment by tylerbutler** [comment]
@microsoft/fluid-cr-server Can you folks take a look at these two problems? They were just recently detected but the code in question is ~18 months old.

**Comment by hedasilv** [comment]
+ @yangg-msft to help triage this.

**Comment by tylerbutler** [comment]
It looks like the changes in #9779 didn't resolve CodeQL's detection. It's very possible that the alert is now a false positive, but I would prefer if someone with server expertise could look at them. Anyone with write permissions to the repo should have access to the CodeQL alerts. Links are in the issue description. If you don't have access please ping me and we'll figure something out.
