### ISSUE TITLE
JoinSessionRefreshNotScheduled error in logs

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#9762]
@jatgarg - In the last week we're seeing 10k hits to the new error event  `fluid:telemetry:OdspDriver:JoinSessionRefreshNotScheduled` across 2400 sessions.

Based on the comment in the code where this is logged, I've got a branch open where I'm downgrading to a Generic event instead of Error.  Is that the right move?  Or are these serious problems we need to jump on with OCE?

**Comment by jatgarg** [comment]
Hey mark, it seems fine to degrade it to generic event,

**Comment by vladsud** [comment]
10K hits over those few sessions is a lot. We should figure out why we fire it that often, and if we should.
@jatgarg - can you please take a closer look?

**Comment by jatgarg** [comment]
Currently the time returned to refresh the join is same as the token expiration time and that does not change even if we make the join session call again. So as per logic it is not a bug. When the server starts to move to new logic of returning the increased refreshSeconds on making the join session call, it should go away. So maybe for now we could just remove the event if it is noisy.
