### ISSUE TITLE
Message payloads - contents in system messages

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9775]
This issue is based on [this discussion](https://github.com/microsoft/FluidFramework/pull/9687#discussion_r844541808)

Core of the problem:
- Most system messages use data property on message (string), not contents.
- All client messages use contents property, and it's string
- But summary ack/nack use contents, and it's an object. I.e. above two rules are broken,

We should make system consistent and uniform.
I see two possible directions:
1. System messages (including summary ack/nack) to use data property only
2. Move all messages (including system) to use contents (and only as a string).

I think we prefer # 1, mostly because service is not supposed to even crack contents (that's client payload), but does crack data property. I find this argument not strong, as someone needs to make determination if it's Ok to crack some payload, and it's based on op type, so one way or another service knows when it's Ok to crack payload (and controls who can send ops with specific type / payload).

Copying Gary's reply from the thread:

ClientJoin & ClientLeave messages use `data`. Control messages also use it, but clients will never see those since they are not sequenced. 
Relevant code is [here](https://github.com/microsoft/FluidFramework/blob/11d8226e478519bd7d46563d8629f6a2008bec58/server/routerlicious/packages/lambdas/src/deli/lambda.ts#L809) and [here](https://github.com/microsoft/FluidFramework/blob/11d8226e478519bd7d46563d8629f6a2008bec58/server/routerlicious/packages/lambdas/src/deli/lambda.ts#L861).

The summary ack and nack case is odd. Scribe will set both the contents and data property for it ([code](https://github.com/microsoft/FluidFramework/blob/11d8226e478519bd7d46563d8629f6a2008bec58/server/routerlicious/packages/lambdas/src/scribe/lambda.ts#L499)). However the summaryAck & nack type are missing from deli's `extractDataContent` method so the data property is essentially ignored. Maybe someone meant to migrate those 2 types to use `data` instead of `contents` but didn't finish? That seems to be the case based on [this PR](https://github.com/microsoft/FluidFramework/pull/7231)

**Comment by GaryWilber** [comment]
@vladsud For going with # 1 - Does the client already support parsing `data` from a `summaryAck`/`summaryNack`?
Trying to see how we would sequence the changes. I'm guessing the server should continue filling out `contents` but also add `data`, and clients can eventually start reading `data` instead.

**Comment by vladsud** [comment]
No, client only parses _data_ for join/leave messages.
We can easily add have extra code to get data from either content or data (whatever present) and get it in. Depending on which direction we talk about, it may take weeks (# 1 approach) vs. months (# 2 approach) - it's difference between where parsing happens (container runtime vs. protocol/loader layer).

As for sequencing, we can go in multiple directions. I think the easiest one would be to have least amount of synchronization - i.e. service starts duplicating data and client can work with either formats. Alternatives are also Ok
