### ISSUE TITLE
Evaluate summarizer frequency and triggers

### ISSUE THREAD

**Issue by andre4i** [microsoft/FluidFramework#9793]
See https://github.com/microsoft/FluidFramework/issues/9637#event-6320124651

Based on insights from the telemetry added in the aforementioned issue:

- adjust the frequency of summaries, as we might be summarizing too often when we do not need to
- decide if "idle" & "maxTime" triggers should fire

**Comment by CraigMacomber** [comment]
Currently fluid's definition of idle doesn't allow (at least to my knowledge) the application to provide extra hints of when it's really idle. It would be nice, for example, if Whiteboard could let fluid know when the user is in the middle of drawing a stroke, and hint that is a bad time to take the summary. This could be in the form of fluid calling into the app to ask if it's a good time (maybe in the form of an async method that completes when it is a good time?), or the app calling into fluid to inform it of when its either busy of idle. Fluid could then follow the app's hints unless it reaches some higher threshold of being too far behind.

**Comment by andre4i** [comment]
https://dev.azure.com/fluidframework/internal/_workitems/edit/518/
