### ISSUE TITLE
Fix disconnect reason propagation issue

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9799]
There are a lot of cases where client report connection being closed with "transport disconnect" reason.
Most likely we lose the actual reason for disconnects.

For example, in case client submits too many ops too quickly (as in a session captured in https://github.com/microsoft/FluidFramework/issues/9798), Gary says that PUSH will sent server_disconnect with these details:
- code will be 429
- message will be “Policy violation for {policy name}”  - {policy name} would be “OperationCount” or “PacketCount” for this case
- retryAfter will be set to how long the it takes the client to get unthrottled (in seconds)

But we clearly lose that info somewhere (we likely lose all the info from server_disconnect), and report actual closure of websocket.

We need to experiment here - create an example exactly like that and debug where and how we lose data.
And ideally add UT to make sure we never regress it again, as it has been continuos struggle to get proper disconnect reasons for very long time.

**Comment by vladsud** [comment]
@GaryWilber - FYI.

**Comment by vladsud** [comment]
BTW, I do see some disconnects having "OdspSocketError (server_disconnect): Policy violation for MessageCount." reason. But very few.

**Comment by markfields** [comment]
I've been wanting disconnect plumbing to pass around full error object not just string - relevant here?

**Comment by jatgarg** [comment]
I do see this error which you are suggesting: ODSP socket error (server_disconnect): Policy violation for MessageCount.
About 350 instances in last 30 days. I am not sure if it's supposed to me more. But I don't think we are parsing for some and not for others. As I checked the error message is plumbed properly. But if they sent this vital info in any other property then we might be missing it.

**Comment by vladsud** [comment]
Not sure what to make out of it, but I remember I've opened a bug when we had an issue where client was reconnecting continuously and not reporting (in telemetry) right reason, and Gary helped with his logs and pointed out that this info should have been propagated to client.
Can you please force this issue and test it in a loop to see if we always get proper info and properly wait for 429?
It's possible that due to some asynchrony we might occasionally lose it - not sure.

If we have no luck, I think we should choose random set of "transport disconnect" sessions and correlate it against service logs to see if there are cases where connection was closed by server with proper server_disconnect message. The number of transport errors suggests that in some of these cases we are not propagating error info properly.

**Comment by jatgarg** [comment]
Opened in ADO.
