### ISSUE TITLE
fluid:telemetry:OrderedClientElection:UnexpectedElectionSequenceNumber

### ISSUE THREAD

**Issue by tyler-cai-microsoft** [microsoft/FluidFramework#9810]
```
let buildId = "60809";
database("Office Fluid Test").office_fluid_ffautomation_error
| where Event_Time > ago(7d) and Data_hostName  == "@fluid-internal/test-service-load" and Data_buildId == buildId
| summarize count() by Data_eventName
```

Happened after https://github.com/microsoft/FluidFramework/pull/8951

**Comment by pleath** [comment]
Did this and the other summary-related stress failures (https://github.com/microsoft/FluidFramework/issues/9806, https://github.com/microsoft/FluidFramework/issues/9807, https://github.com/microsoft/FluidFramework/issues/9808, https://github.com/microsoft/FluidFramework/issues/9809) pop up after https://github.com/microsoft/FluidFramework/pull/8951?

**Comment by agarwal-navin** [comment]
@tyler-cai-microsoft Same here. Can you please add a more descriptive title and description?

**Comment by jatgarg** [comment]
Resolved with PR: https://github.com/microsoft/FluidFramework/pull/9891
