### ISSUE TITLE
Track size of quorum when summary is generated

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9818]
Someone asked me if it makes sense to have more sophisticated algorithm to elect more capable client (in terms of CPU / bandwidth capabilities) to summarize document, not first in quorum.

My reaction to that - I believe (but do not have data) that most sessions have only one client when summarizer is elected, and thus spending time (and adding complexity to runtime) on something that is very likely not going to make a difference is not worth it. But, we should be data driven, and we do not have this data!

This issue tracks adding to summarizer telemetry size of Quorum.
A trivial change that would influence such discussions in the future.

**Bonus:**
Collect quorum size as part of container load sequence as well.
All is required is add a property at the end of Container.load() here and it will get logged as part of Container:Load_end event:
```ts
        return {
            sequenceNumber: attributes.sequenceNumber,
            version: versionId,
        };
```

And as part of connectivity events (Container.logConnectionStateChangeTelemetry)

This might be useful to understand how much actual collaboration happens in Fluid documents.

**Comment by kian-thompson** [comment]
@vladsud What's the best approach for adding this information? Most of the summary telemetry logic seems to be in the `SummaryGenerator`. Currently, the `SummaryGenerator` does not have access to the `QuorumClients` stored in the container runtime's `context`.
I was thinking of trying to take advantage of the `summaryLogger` property that gets passed back to `ContainerRuntime.submitSummary` from the `SummaryGenerator`. We can then log an event that contains this quorum size information.

**Comment by vladsud** [comment]
We can add it to IGeneratedSummaryStats.

ContainerRuntime has access to everything, so it can easily capture this.getQuorum().getMembers().count.

Here is where we add it to telemetry (see summaryData.summaryStats):
```ts
            if (summaryData.stage !== "base") {
                summarizeTelemetryProps = {
                    ...summarizeTelemetryProps,
                    ...summaryData.summaryStats,
                    generateDuration: summaryData.generateDuration,
                };
```

Here is where we record it:
```ts
            const summaryStats: IGeneratedSummaryStats = {
                dataStoreCount: this.dataStores.size,
                summarizedDataStoreCount: this.dataStores.size - handleCount,
                gcStateUpdatedDataStoreCount: summarizeResult.gcStats?.updatedDataStoreCount,
                gcBlobNodeCount: gcSummaryTreeStats?.blobNodeCount,
                gcTotalBlobsSize: gcSummaryTreeStats?.totalBlobSize,
                opsSizesSinceLastSummary: this.opTracker.opsSizeAccumulator,
                nonSystemOpsSinceLastSummary: this.opTracker.nonSystemOpCount,
                ...partialStats,
            };
            const generateSummaryData = {
                referenceSequenceNumber: summaryRefSeqNum,
                minimumSequenceNumber,
                summaryTree,
                summaryStats,
                generateDuration: trace.trace().duration,
                forcedFullTree,
            } as const;

            continueResult = checkContinue();
            if (!continueResult.continue) {
                return { stage: "generate", ...generateSummaryData, error: continueResult.error };
            }
```
