### ISSUE TITLE
AzureClient supports discovery endpoint URLs

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#9837]
AzureClient currently requires ordererUrl and storageUrl to connect to the Azure Fluid Relay service. This needs to be changed to support a single discover URL. This discovery url will be called to determine which endpoint to connect to and will allow for support of Data Recovery (DR) scenarios.

# Goal
Developers can provide a discovery endpoint instead of explicit orderer and storage endpoints

# Requirements
- Developers will only ever need one URL (the discovery URL) to connect AFR

# Current Config
```ts
// AFR Connected
const config = {
    connection: {
      tenantId: "_GUID_",
      tokenProvider: new TokenProvider(/*...*/),
      orderer: "https://myOrdererUrl",
      storage: "https://myStorageUrl",
    }
};

// Local Mode Connected
const config = {
    connection: {
        tenantId: LOCAL_MODE_TENANT_ID,
        tokenProvider: new InsecureTokenProvider("", { id: "userId" }),
        orderer: "http://localhost:7070", 
        storage: "http://localhost:7070",
    }
};
```

# Proposal
## 1. Use single discovery url for AFR and Local
In this model the developer would only supply one URL for local and remote scenarios. In the local case we would use the URL to craft the appropriate orderer and storage URLs. 

### Pros
- Consistant Config

### Cons
- Discovery isn't really happening in local model and could be confusing to the developer

### Config Examples
```ts
// AFR Connected
const config = {
    connection: {
      tenantId: "_GUID_",
      tokenProvider: new TokenProvider(/*...*/),
      discoveryUrl: "https://afr-discovery.azure.com/.../.../...",
    }
};

// Local Mode Connected
const config = {
    connection: {
        tenantId: LOCAL_MODE_TENANT_ID,
        tokenProvider: new InsecureTokenProvider("", { id: "userId" }),
        discoveryUrl: "http://localhost:7070", 
    }
};
```
## 2. Use discover for AFR only
In this case we keep the params of the local config the same and move to a single endpoint only for the non-local scenario. This would require a typing change to make sure we can successfully support two types of configs with different properties.

### Pros
- type makes it clear what scenario they are in
- more specific support for local vs remote scenarios

### Cons
- developer needs to understand different configs
- developers don't need to understand orderer vs storage for local (internal concept to them)

### Config Examples
```ts
// AFR Connected
const config = {
    connection: {
      type: "remote",
      tenantId: "_GUID_",
      tokenProvider: new TokenProvider(/*...*/),
      discoveryUrl: "https://afr-discovery.azure.com/.../.../...",
    }
};

// Local Mode Connected
const config = {
    connection: {
        type:"local",
        tokenProvider: new InsecureTokenProvider("", { id: "userId" }),
        orderer: "http://localhost:7070", 
        storage: "http://localhost:7070", 
    }
};
```

## 3. Use discover for AFR, reduce Local to single endpoint
This proposal is a hybrid of 1&2. It reduces the Local to only one endpoint since that's all developers really care about and it also keeps the remote vs local typing.

### Pros
- type makes it clear what scenario they are in
- more specific support for local vs remote scenarios
- aligned to what developers actually care about for local mode

### Cons
- developer needs to understand different configs
- the same config with discovery vs endpoint might be overkill

### Config Examples
```ts
// AFR Connected
const config = {
    connection: {
      type: "remote",
      tenantId: "_GUID_",
      tokenProvider: new TokenProvider(/*...*/),
      endpoint: "https://afr-discovery.azure.com/.../.../...",
    }
};

// Local Mode Connected
const config = {
    connection: {
        type:"local",
        tokenProvider: new InsecureTokenProvider("", { id: "userId" }),
        endpoint: "http://localhost:7070", 
    }
};
```

# Recommendation
After considering I would recommend 3. The reasons being:
1. It creates the most accurate representation of the required properties for both remote and local scenarios
2. It clearly outlines when the user is connecting to local vs remote.
3. Provides extensibility for future connection configurations if needed

# Issues 

- [x] #10118

**Comment by ms-avocado** [comment]
Should we close this issue?
