### ISSUE TITLE
Eslint: Clean up no-param-reassign violations

### ISSUE THREAD

**Issue by curtisman** [microsoft/FluidFramework#990]
Follow the `no-param-reassign` rules for Eslint. 
Remove all instances where it was disabled in the repo and fix the eslint issue by create a local variable and rename all usage.

Recommend breaking it into multiple small PR to easy code review and make the work more managable.

**Comment by atiqueahmedziad** [comment]
@curtisman can you provide some guidelines on what's expected to be done? 
For example: should I make a new variable [here](https://github.com/microsoft/FluidFramework/blob/81795eedd5c562646a62a70c8b8996dcf3e86746/packages/drivers/local-driver/src/auth.ts#L23,L26) or should I turn off the `no-param-reassign` rule in the respective eslint config file?

**Comment by curtisman** [comment]
@atiqueahmedziad we would like to follow the eslint rule here.  So making a new variable and renaming all usage is the way to go. 

Also, since there are a lot of instances in the repo, it is preferable to make multiple small PR to make progress and reviewing them easier.

I have updated the description of the issue to include this guideline.

Thank you for your question.

**Comment by curtisman** [comment]
Thanks @atiqueahmedziad  and @hantatsang for your help in resolve this issue!
