### ISSUE TITLE
Update documentation for API around `documentPostCreateCallback` to make expectations around error scenario more clear

### ISSUE THREAD

**Issue by skylerjokiel** [microsoft/FluidFramework#9913]
The AFR service now returns a signed token by the service. This needs to be returned as apart of attach. This is a breaking change since it will impact the response.

Currently the response object is just a string representing the id. We need to pass through the token that the service returns along side the id. This new token is generated by the service and can be used by the client to validate who created the container.

The primary scenario here is that an app's service want's to track container creation. Because the client is the one crating the container the client needs to update the app service once the container is created. In the rouge client scenario the client could lie and say they created a container to get permissions to another container. By instead providing the server signed token the app service can use this to validate who created the container.

## Example Change Proposal

```ts
// current
const { container } = client.createContainer(...)
const id = container.attach();

// proposed
const { container } = client.createContainer(...)
const {id, token} = container.attach();

```

## Unknowns
- Does Tinylicious and Azure have the same behavior here? Seems like it's service specific which could be challenging when thinking about where to place it.
- This will make attach() service specific which is not ideal. Is there a way to not do this?
- What's the signature of the token?

## Tasks
- [ ] Propose design
- [ ] Plumb through work
- [ ] Update documentation

**Comment by Josmithr** [comment]
Relevant (previous) PR: [9411](https://github.com/microsoft/FluidFramework/pull//files#diff-936bb2bfc0ba782920b87486004cf256d90d83f7eaf645ee02b60c436ff8bcbf)

**Comment by Josmithr** [comment]
There was some miscommunication about what work remaining work was actually required here. The goal of this work is no longer to update the `attach` API, but instead to do the following:
1. Add an explicit Error type to be thrown by `RouterliciousDocumentServiceFactory.createContainer` in the case that `ITokenProvider.documentPostCreateCallback` threw an error during its execution. This new Error will wrap the caught error and serve primarily as documentation for the consumer's benefit.
2. Update documentation of surrounding APIs to make implications and expectations around the error scenario more clear.
