### ISSUE TITLE
Add summary telemetry when summaries are not catching up

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9952]
As we are making a lot of adjustments in summarizing flow, it would be great to learn how often summarization process does not catch up, i.e., signal to summarize comes sooner than previous summary is complete.
I'd start with making it an error event here, where we switch this.tryWhileSummarizing from false to true:

```ts
    /** Heuristics summarize attempt. */
    private trySummarize(
        summarizeReason: SummarizeReason,
        cancellationToken = this.cancellationToken): void
    {
        if (this.summarizingLock !== undefined) {
            // lockedSummaryAction() will retry heuristic-based summary at the end of current attempt
            // if it's still needed
            this.tryWhileSummarizing = true;
            return;
        }
```

**Comment by kian-thompson** [comment]
@vladsud FYI this new error event triggered a Sev2 incident due to the number of errors raised. I changed the event to telemetry instead of error.
[Incident-305649615 Details - IcM (microsofticm.com)](https://portal.microsofticm.com/imp/v3/incidents/details/305649615/home)
