### ISSUE TITLE
Summarizer to log summary policies in telemetry

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9969]
We need to ensure that summary policy is present in telemetry in some form, ideally as payload on one of the summarizer events when summarizer starts. This way it will be possible for us to better uderstand summarizer perf in various environments.

Related issues:
- https://github.com/microsoft/FluidFramework/issues/9948

**Comment by kian-thompson** [comment]
@vladsud What is meant by summary "policy"? Is this in reference to the `ISummaryConfiguration` or `ISummarizerOptions` interfaces?

**Comment by vladsud** [comment]
ISummaryConfiguration
