### ISSUE TITLE
Remove bindToContext calls for non-root data stores after they are created

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#9971]
After a non-root data store is created, its handle should be stored in a visible DDS for the data store to become visible and to mark it as referenced. Currently, some consumers use the old pattern of calling `bindToContext` to make these data stores visible. These should be removed as they hide bugs where data stores are used before they are marked referenced by adding their handles.

https://github.com/microsoft/FluidFramework/issues/9127 was blocking this removal. This bug is fixed and is in 0.59.1000 release but the calls cannot be removed yet because it will break compatibility between container runtime and data store runtime layers. Once we move past the compatibility window, these calls can be removed.

**Comment by markfields** [comment]
We can consider staging this by doing 

```
if (featureFlag_disableBindToContext) { throw ... }
```

And leave the code there as fallback for some time?

**Comment by agarwal-navin** [comment]
Tracked by AB#385
