### ISSUE TITLE
GC / summarization is not incremental

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#9979]
Opening issue based on discussion, please verify all claims.

Per Tyler:
> We overwrite the blob every single time when we run GC. Since GC is currently tied to summaries, we can say that we overwrite the GC blob every single time. Each summary contains the whole GC blob for that summary at that time. This occurs whenContainerRuntime.summarizeInternal is called which callsContainerRuntime.addContainerStateToSummary

We should figure out a way to only overwrite this data when it changes. If I typed couple paragraphs in Chapter1 scenario and did not change in any way reference graph, we should not send this data to service, and simply reuse blobs from previous summary.
If this is hard to do within GC code, we should look into adding more general (i.e. applicable to whole container) blob deduping code that can detect blobs in new summary being exact copies of blobs in prior summary and removing content by reusing old blob IDs.

Once we have that, we should revisit telemetry in this space:
```ts
    /** The size of the gc blobs in this summary. */
    readonly gcTotalBlobsSize?: number;
    /** The number of gc blobs in this summary. */
    readonly gcBlobNodeCount?: number;
```
We should continue to collect incremental data for summaries, but it would be great to get data for snapshot, i.e. full impact of GC blobs to snapshot. If we know for sure we will continue to be in all-or-nothing design (i.e. either all GC blobs are overwritten or none is written because all are reused), then it's probably fine to leave it as is, as we can almost always fish this info from previous summaries. But if this is going to change, we should reconsider how we log it and provide both incremental and full picture.

We should look into this telemetry to understand if keeping it as one blob is efficient. It all depends on
- how big this blob is (distribution)
- how often something changes causing us to write it out.

**Comment by tyler-cai-microsoft** [comment]
It seems like we should add telemetry for the snapshot to impact/size of the GC blob(s). 

After a conversation with @agarwal-navin we determined that:
- Older clients have the ability to process multiple GC blobs, which means we should be able to chunk blobs
- We are limited by how older clients can process blobs
- We may want to chunk them into 10 blobs or some other finite number.
- We may want to chunk them into a blob per datastore/blob.
- We do not have the ability to read and submit a tree with subtrees.

We know that we are essentially rewriting the whole GC blob as we are reserializing it every time we summarize. 

Feel free to correct me if I'm wrong.

**Comment by vladsud** [comment]
I'd say from priority perspective, I want to see these things:
- If there are no changes in GC graph, there are no or minimal updates to GC info
    - I believe most summaries will hit this state, and thus we should optimize that case the most.
- If GC graph changes, all I care amortized bytes over wire are small. If you can prove to me that's the case (for example, it does not happen often, and when it happens - the size of total blob written is relatively small, assuming single blob).

Breaking GC blob into many blobs is implementation detail. You might need it or might not need it to achieve these goals.

Some decisions in this space will depend on analyzing telemetry you have added. But even without telemetry I can say (based on how big GC blobs are in some files), that it would not be acceptable to write all this data on every summary.

Back compat considerations are important, but I think we can work them out. I'd start with how we want to see end system RE its characteristics first.

**Comment by agarwal-navin** [comment]
At some time, we were thinking of writing the GC blobs as attachment blobs. That would reduce the GC blob size in the summary (both on upload and download). If we do that, do we still need to worry about the GC blob size?
Having increment summaries for GC blob would be a nice to have even with the above, but should we do the above first?

**Comment by vladsud** [comment]
Attachment blob only helps with boot (download), not upload. For boot, we can leverage other ways to exclude GC blobs from snapshot - either use attachment flow or invent new mark up (SPO is looking into it). In general, I prefer
- Single roundtrip, as it's faster
- Incremental summaries and pay-per-play as a way to "address" large summaries.

For summaries, I want to be able to get to a point (at least theoretically) where I can run summary every second and system would keep up. This kind of thinking forces right architecture, even if we never actually use that kind of extreme setting.

I'll say same thing as in previous reply - breaking GC blobs into chunks and writing only blobs taht changed is one way to achieve it. If GC data is relatively small, and is written only if it changes, we might be fine for very long time with single GC blob. We will get data soon, which helps answer size problem, but #9472 suggests we have to do some work in size domain no matter what.

I'd attack it in this priority:
- First, understand how big blobs are in general
- Address any known issues like #9472
- Consider if we cannot write single blob today, i.e. if we can detect nothing changed. Should not be that hard - just calculate sha1 from prior blob and new blob, and if they are the same - just reference old one (I'd prefer it to be at container level for all blobs by default, but it will take a while to build such capability).
- Use data after first two items to decide if we have to go with multiple blobs, and what is the design here (one per DS, or some other partitioning).
    - Note that if it's some arbitrary grouping (not per one per channel), we need stable partitioning algorithm.

**Comment by agarwal-navin** [comment]
Yes, it will not change upload time but it will help with the size of the summary (ISummaryTree) that is uploaded since the GC blob will be uploaded separately. We can do "Consider if we cannot write single blob today" and add to stats how many times we do this vs how many times we re-write the summary. That should be another factor in doing follow up work.

**Comment by agarwal-navin** [comment]
There are other ways we can reduce the size of the GC blobs but I would rather wait for the stats after the above work to do them.

**Comment by tyler-cai-microsoft** [comment]
When 0.59.1000 gets integrated, we can do something like this:

```
union Office_Fluid_FluidRuntime*
| where Event_Time > ago(1d)
| where Data_gcTotalBlobsSize >= 1000000
| project Data_docId, Data_containerId, Data_gcTotalBlobsSize, Data_gcStateUpdatedDataStoreCount, Data_summarizedDataStoreCount, Data_dataStoreCount
| summarize summary_count = count() by bin(Data_gcTotalBlobsSize, 1000000)
| sort by Data_gcTotalBlobsSize asc 
| render columnchart 
```

**Comment by agarwal-navin** [comment]
Tracked internally AB#188
