### ISSUE TITLE
Add new pipeline to run end-to-end test against configurable tinylicious version

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#998]
Both the tinylicous version and the end-to-end test version should be configurable, so we can run old tests against new servers and vis-versa.

We should schedule builds (daily?weekly?) on our old release branches that run against the lastest tinylious

**Comment by markfields** [comment]
Essentially covered by https://github.com/microsoft/FluidFramework/issues/4660 and other related improvements we're making to our e2e tests.
