### ISSUE TITLE
Simple container debugger

### ISSUE THREAD

**Issue by ssimic2** [microsoft/FluidFramework#9980]
As part of FHL week we have created simple telemetry-based container [debugger](https://github.com/ssimic2/FluidFramework/commits/fhl-container-debugger-v2) that can be used to observe underlining container state and events, while running FF-based web applications. Initial goal of this project was to offer it as a learning tool for new developers joining in, who want to get familiar with what is happening under the FF hood.

The following is a short-term follow up list:

1. General clean up and documentation of the project. Readme should be clear about the setup and usage.
2. Surface document state. Currently we are streaming events only, but we should be displaying current document state as well (attached/detached, connected/disconnected, clean/dirty).
3. Event templating. We should be able to load "templates" that define filtering and event conversion rules. The idea behind the template is to present state/events in some context that user is interested about. Say "Connection State" template only highlights events/state dealing with connection. 
4. PR the project to our tools directory. We could have debugging-tools folder there.

(Note: Synthetic event triggers can be removed for now, just to make this tool simpler for now)

**Comment by unaisshemim** [comment]
can i join with you

**Comment by ognis1205** [comment]
Is this still an active issue? If it is the case and no one was assigned, I would like to work on this.
